# **응급상황 자동 인식 및 응급실 연계 서비스**
# **단계1 : 응급상황 음성 인식 및 요약**

* 음성인식 : STT(Speech-to-Text)
    * 사용 모델 : OpenAI의 **Whisper-large-v3**
    * 제공받은 음성 파일과 새로 제작하는 5건 이상의 음성파일을 텍스트로 변환하고, 변환작업이 잘 되는지 확인해 봅시다.

* 텍스트 요약 및 핵심 키워드 도출
    * 사용 모델 : EXAONE-3.5 7B

#### 1) 구글 드라이브 연결

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
path = '/content/drive/MyDrive/KT_aivle/미니프로젝트/2024.11.18_미니프로젝트_6차_4일차_실습자료/'

### (2) 라이브러리

#### 1) 필요한 라이브러리 설치

In [ ]:
# 경로 : /content/drive/MyDrive/project6_2/requirements.txt
# 경로가 다른 경우 아래 코드의 경로 부분을 수정하세요.

!pip install -r /content/drive/MyDrive/KT_aivle/미니프로젝트/2024.11.18_미니프로젝트_6차_4일차_실습자료/requirements.txt

#### 2) 라이브러리 로딩

In [ ]:
#필요한 라이브러리 설치 및 불러우기
import os
import requests
import xml.etree.ElementTree as ET
import pandas as pd
import matplotlib.pyplot as plt
import openai
from openai import OpenAI
import json

# 더 필요한 라이브러리 추가 -------------
import torch
from datasets import load_dataset
from transformers import pipeline
from transformers import AutoProcessor, AutoModelForSpeechSeq2Seq, pipeline, AutoModelForCausalLM, AutoTokenizer
import librosa

In [ ]:
import warnings
warnings.filterwarnings("ignore", category=FutureWarning)

### (1) 제공된 데이터 변환
* 세부사항
    * 사용 모델 : whisper-large-v3
    * 제공 받은 오디오 파일을 읽어서 텍스트로 변환시켜 봅시다.
        * 반복문을 통해 파일 하나씩 읽어서 텍스트 변환
        * 변환된 텍스트를 데이터 프레임에 추가

|filename|text|
|----|----|
|audio3.mp3|어쩌구 저쩌구...급해요.|

* 음성파일 변환

In [ ]:
# 음성파일 경로 지정
audio_path = '/content/drive/MyDrive/KT_aivle/미니프로젝트/2024.11.18_미니프로젝트_6차_4일차_실습자료/audio/'

In [ ]:
from transformers import AutoProcessor, AutoModelForSpeechSeq2Seq, pipeline

processor = AutoProcessor.from_pretrained("openai/whisper-large-v3-turbo")
model = AutoModelForSpeechSeq2Seq.from_pretrained("openai/whisper-large-v3-turbo")

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

preprocessor_config.json:   0%|          | 0.00/340 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/283k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/2.71M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/494k [00:00<?, ?B/s]

normalizer.json:   0%|          | 0.00/52.7k [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/34.6k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/2.19k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/1.26k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.62G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/3.77k [00:00<?, ?B/s]

In [ ]:
import torch
from datasets import load_dataset
from transformers import pipeline

In [ ]:
#오디오 30초 자르는건 선넘네
device = "cuda:0" if torch.cuda.is_available() else "cpu"
torch_dtype = torch.float16 if torch.cuda.is_available() else torch.float32

model_id = "openai/whisper-large-v3-turbo"

model = AutoModelForSpeechSeq2Seq.from_pretrained(
    model_id, torch_dtype=torch_dtype, low_cpu_mem_usage=True, use_safetensors=True
)
model.to(device)

processor = AutoProcessor.from_pretrained(model_id)

pipe = pipeline(
    "automatic-speech-recognition",
    model=model,
    tokenizer=processor.tokenizer,
    feature_extractor=processor.feature_extractor,
    torch_dtype=torch_dtype,
    device=device,
)

dataset = load_dataset("distil-whisper/librispeech_long", "clean", split="validation")
sample = dataset[0]["audio"]

result = pipe(sample, return_timestamps=True, generate_kwargs={"language": "korean"})
print(result["text"])

In [ ]:
# numpy 배열로 변환하는 코드
import librosa
filename = 'audio2.mp3'
audio_file = open(audio_path + filename, "rb")
audio_array, sampling_rate = librosa.load(audio_file, sr=None)
result = pipe({"array": audio_array, "sampling_rate": sampling_rate}, return_timestamps=True)
print(result["text"])

/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
Due to a bug fix in https://github.com/huggingface/transformers/pull/28687 transcription using a multilingual Whisper will default to language detection followed by transcription instead of translation to English.This might be a breaking change for your use case. If you want to instead always translate your audio to English, make sure to pass `language='en'`.
Passing a tuple of `past_key_values` is deprecated and will be removed in Transformers v4.43.0. You should pass an instance of `EncoderDecoderCache` instead, e.g. `past_key_values=EncoderDecoderCache.from_legacy_cache(past_key_values)`.

 119조 제가 지금 열이 열이 올랐어요. 몇 도냐면은 38도 정도 돼요. 머리가 아프고 좀 띵한 것 같아요. 오하니 좀 들어요. 어떻게 해야 할까요?

* 음성파일 변환 함수 생성

In [ ]:
audio_path = '/content/drive/MyDrive/KT_aivle/미니프로젝트/2024.11.18_미니프로젝트_6차_4일차_실습자료/test_audio/audio/'

In [ ]:
def audio_to_text(audio_path, filename):
    # 오디오 파일을 읽어서, 위스퍼를 사용한 변환
    audio_file = open(audio_path + filename, "rb")
    audio_array, sampling_rate = librosa.load(audio_file, sr=None)
    result = pipe({"array": audio_array, "sampling_rate": sampling_rate}, return_timestamps=True)

    # 결과 반환
    print(result["text"])
    return result

In [ ]:
# 음성파일 이름을 리스트에 담기
file_names = [f for f in os.listdir(audio_path) if os.path.isfile(os.path.join(audio_path, f))]
print(file_names)

In [ ]:
# 반복문을 통해, 파일 하나씩 읽어서 텍스트 변환, 변환된 텍스트를 데이터 프레임에 추가

# 빈 데이터프레임 선언
df = pd.DataFrame(columns=['file_name','transcription'])

# 반복문 수행하면서 오디오 변환
for i, file_name in enumerate(file_names):
    transcript = audio_to_text(audio_path, file_name)
    df.loc[len(df)] = {'file_name': file_name, 'transcription': transcript}

# 데이터프레임 결과 조회
print(df)

 네, 119입니다. 말씀하세요. 아 네, 그 계속 토로 해가지고. 어느 분. 어 어 병원은 지금 움직일 수가 없어서. 어느 분이 계속 토로 하세요? 아 저희 언니요. 언니가요? 네. 토하시고. 네. 우리 쪽이랑 호흡은 다 있어요? 네. 아 네, 보급차 보내드릴 건데 주소가 어떻게 되세요? 강서구. 네. 화공로 18길. 잠시만요. 화공 18길. 강서 뉴 타워. 잠시만요. 강서 뉴 타워. 네. 아 잠시만요. 언니분이랑 동생은 최근에 뭐 코로나 관련해서 의심 증상이나 뭐 접속했다고 문자 받으신 거 없으시죠? 아 네 알겠습니다. 배원도 나가면서 전화드릴 수 있으니까 전화 한번 안내 좀 부탁드릴게요. 아 네 알겠습니다.
 감사합니다. 무슨 일이세요? 아 네 여보세요? 네 말씀하세요. 무슨 일이세요? 아 지금 뭐 현압을 해보니까 현압이 너무 높아요. 누구야 선생님이요? 네 177이 넘고 지금 막 그 약간 말이 안 나오고 춥고 막 그러거든요. 조금만 보내드릴까요 선생님? 네 여기 아우 힘들어요. 말이 어눌하신 거예요? 말이 하는 게 어려운 거예요? 아 추워요 지금. 그냥 추운 거예요? 말이 어누라 그냥 한쪽으로 힘 빠지는 건 없으시죠? 네 추워요. 네 구급차 위치 좀 보내드릴 구급차 좀 보내드릴게요. 위치 좀 알려주실 수 있으실까요? 네 여기 포르주아 아파트. 하곡 포르주아 맞으세요? 선생님? 네. 맞으세요? 네 네. 혹시 근데 코로나 관련해서 뭐 확진자를 접촉하거나 그러신 거 있으세요? 아니요. 코로나 주사를 제가 화요일 날 맞았어요. 네. 아 그러는데 한 3일만은 괜찮았는데 어제서부터 약간 하락이 올라가더라고요. 선생님 그쪽으로 하구 프로지오 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 혹시 모릅니다. 문 좀 열어두세요. 선생님. 전화 구급회원들 가면서 전화할 거고요. 전화 잘 받아주세요. 알겠습니다. 감사합니다.
 여보세요? 예예. 왜 애가 갑자기 지금 시선을 이렇게 며이셔죠? 빨리 와주세요. 어디로 가요? 여기 송방어 오금로? 오금로 36길 36길에 36길에 네 저희 여자 남자분이세요? 여자에요 우리 몇 개월 했네요 성인이에요 성인 30살 34살이라고요? 아니 30살 잡아 잡아 잡아 잡아 잡아 이거 낫잖아 얼른 잡아봐 늦게 봐 보냈고요 알려드릴게요. 전화 끊지 마세요. 네네네. 네네네. 이게 왜 이래. 여보세요? 선생님 숨은 쉬는 왜 숨? 숨은 쉬는 거 같아요. 가슴이 오르렉 내려갈게요? 아니 아니 지금 가슴 숨은 쉬는가 봐. 숨은 쉬는데 눈동자가 지금 사람 저기에요. 예, 평평 바닥에 눕히세요. 선생님. 그 침대. 침대에 눕혔거든요? 애가 일단 침대에 누워갖고. 예, 예. 아 네, 알겠습니다. 예, 예. 어떻게 해야 돼? 어? 왜 그래 얘. 아니, 왜. 어떻게. 어떻게. 아니, 여기 여기.
 네 여기 저 방산 센트럴 아이터크. 잠시만요. 방산 센트럴 아이터크. 그 펜트 그 딴 게 아니고요. 그 저 그 변을 좀 심하게 보다가 그 그 안에 그 있잖아요. 그 저. 안에 안에 있는 거 그 튀어나온 거 뭐라 하죠 그게. 탈장됐어요? 예예. 탈장돼가지고 지금요. 예. 누가? 저희 집사람이요. 예. 아 잠시만요. 네. 부급차 보내고요. 집에 따로 열 있거나 코로나 관련돼서. 없습니다. 없습니다. 없습니다. 예. 없습니다. 예예. 차 보냈게요. 좀 기다리고 계세요.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네 그 어 여기가 보문동 자이 아파트거든요. 보문 파크뷰 자이요? 네. 여기 할아버지가 지금 쓰러지셔 가지고. 집 안에서요? 네. 몇 동 몇 호예요? 네 되세요? 하루가 돼. 응세가. 일. 네 움직임 전혀 없으시고요. 음 의료지도 제가 연결할게요. 의료진한테 안내 좀 해주세요.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 1월 1일부터. 아 네 저기 지금 요양원이에요. 네 근데 그 어르신께서 지금 갑자기 아침에 질출혈을 좀 많이 하셨거든요. 할머니 질. 예 할머니 예 10시부터 해가지고. 그래서 출혈량이 있어가지고요. 병원 가시려고요? 예 지금 보호자 연락했는데 출혈이 많고 혈압이 지금 떨어져요. 계속. 네, 50 있어요? 지금? 예, 지금은 있어요. 60 근데 지금 혈압 60에 40이에요. 예. 혈압이 60에 40이라고요? 네, 지금요. 막. 아, 지금 얼른 보낼게요. 주소 알려주세요. 예, 수색동이요. 네네. 수색 실버케요. 수색 실버케요? 몇 층으로 가면 돼요? 아, 1층으로 오시면은 저 갈게요. 네. 따로 거기에 확진자 있거나 그런 거 없어요? 정리 사항이. 아 저희 그런 거 없어요. 네 없어요. 지금 차는 보냈는데요. 네, 네. 어 집에서 나오는 게 맞아요? 대변 쪽에서 나오는 거 아니고? 아 집에서 집에서요. 나오는 거예요? 어저께 근데 그 2차 백신 맞으셨거든요? 아 네, 네. 네, 네. 차 보냈고 그 수색역 쪽에서 구급차 어 수색역에서 구급차가 없어가지고 조금 멀리서 가요. 소대문서가 저쪽 한 5km 떨어진 데서 가요. 연희대에서. 아 네 네 알겠습니다.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 여보세요? 예 선생님 119 입니다. 네네. 예 선생님 아 부모는 아이 자 파크자이 아파트 말씀하신 거 맞죠? 예예. 아내 분이 뭐 지금 의식도 없고 호흡도 없는 거예요? 아 아 돌아가신 것 같습니다. 며칠 전에 돌아가신 것 같습니다. 예. 아 이 부인 분 맞는 거죠? 예? 부인 분이 맞아요? 집사람? 예 집사람 맞습니다. 예예. 알겠어요. 선생님 출동 때 갖고자 의료 상담사 연결해서 전화 끊지 말고 기다리세요.
 119입니다. 예 저 119죠? 네네. 아 여기 아저씨가 자리를 자리가 부러진 거 같은데. 네. 장애인이라서 어떻게 할 수가 없어요. 119가 와서 좀 데려가. 누가요? 우리 남편인데요. 남편이 넘어졌어요? 예 넘어졌어. 넘어진 게 아니라. 실체에서 떨어졌어. 실체어에서 넘어져가지고 납작에서 다리를 부정당했어요? 예 다리가 괜찮은데 몰랐는데 막 다리가 막 통통 굽네요. 발목이 발목이. 예 발목이요? 예. 어디로 가는데요? 어 저기 남가자동 현대아파트. 잠시만요. 남가자 현대아파트. 네 그쪽 보내고요. 뭐 열이거나 기침 콧물 있으세요? 아저씨? 아니 그렇지 않아 아무렇지도 않은데 이거 그런지 한 1시간 됐는데 이거. 차는 보냈고요. 따로 코로나 때문에 격리 하시는 분 하시는 분이나 확신도 없죠? 가족분들 중에? 예 없고 우리 다 3차 다 맞았어요. 알겠어요. 선생님 좀 기다리고 저기가 휠체어를 못 데려가니까 이렇게 대리기 알겠어요. 네. 네.
 119 입니다. 여보세요? 예. 예 여기 노인장반이 좀 저 쓰러지지 않아서 이거 여자분 남자분이요? 남자분입니다. 골절이 된거 같은데 골절이 넘어지신거에요 그럼? 네 넘어있었어요. 남자분 납상이요? 예. 그 어디쪽 다시 고셔야 되신거 같아요? 왼쪽 골반같아요. 아 골반 골절이요. 주소 알려주시고 제가 출동할게요. 저희가 어, 희경동. 희경동 동대문구. 이게 저희가 억군이라고 해야 되나 어떻게 되나? 아니 일단, 일단 출동을 해볼게요 일단. 예, 저기 일단 출동하고요. 예. 선생님 저기 뭐 기침 발열, 호흡기 질환, 인후통 그런 거 있으세요? 거기 계신 분들? 예? 기침 발열, 호흡기 질환, 인후통 그런 거 있으세요? 계신 분들? 그게 무슨 얘기예요? 기침 발열 호흡기 질환 인후통 있냐고 예유 그런건 없어요 없어요? 뭐 코로나 관련 접촉 문자 받으신거 있으세요? 예 알겠습니다. 알겠습니다. 출동했어요. 네. 네.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네. 일로 봅니다. 아 네. 그 이거 제가 예 저거 운기차 좀 불러줘. 무슨 일이신데요? 어 저 우리 아버지가 지금 그 그 몸 차갖고 숨을 안 차갖고. 주소 알려주세요. 네. 그 풍납 1동에. 네. 몇 번지예요? 몇 번지냐고요 풍납동 잠시만요 코로나 관련된 거 없으시죠? 네 숨 안 쉬는 거예요? 네 숨 안 쉬고 예 구급차는 보냈고요 풍납동 전화 끊지 마세요.
 응. 여덟입니다. 네 안녕하세요. 네 말씀하세요. 제가 지금 제가 너무 아픈데. 배가 아프시다고요? 네. 어제 저녁부터는. 계속 배가 아파할지. 네 알겠습니다. 소급자 보내드릴게요. 주소가 어떻게 되세요? 응. 서초구. 서초구. 어? 효령로. 효령로. 네. 네. 어. 34길. 38길이요? 34길. 3일 아파트. 3일 아파트. 네. 예 알겠습니다. 호흡차 출발했고요. 뭐 코로나 증상 같은 거 경소에 없으셨죠? 네 그런 건 없었고요. 네 알겠습니다. 내 통전에서 아랫배가 아팠는데 네. 아래 대목부터 심해져요. 예 아유 가고 있으니까 전화 가면 전화 좀 받으세요. 대원장 전화 갈 거예요. 네. 네.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네, 119입니다. 네, 안녕하세요. 네, 말씀하세요. 배가 너무 아파가지고 지금 병원 응급실에 좀 갖고 싶은데 들여다 주실 수 있을까 해서요. 어 혹시 열이 나거나 기침 코로나 관련. 아유 전혀 그건 아니고 장면. 주소 주소. 주소. 이태나우스. 심장 이태나우스 맞죠? 예, 예, 그 저 홍익병원 응급실이요. 알겠습니다. 출동하겠습니다. 네 고맙습니다.
 수고합니다. 말씀하세요. 무슨 일이세요? 아 좀 아파가지고 병원을 좀 데려가야 되는데 거동을 좀 못해요. 네 누구시 그 위치가 어떻게 될까요? 여기 삼선동 2가 선생님. 네. 누가 아프신 건가요? 아 저 친구인데요. 어머님이 이제 혼자서 못하시니까 제 친구인 제가 지금 대신해서 지금 신고를 하는 거거든요. 그 태극 그린빌인가요? 폐급 그림들 바로 앞집이에요. 그 폐급 그림들 앞으로 가면 되는 건가요? 선생님? 네네네네. 그 친구분이실 친구 지금 어디가 불편하신데요? 지금 뭐 여기저기 원래 지정이 좀 있어요. 전신이 다 아프신 거예요? 네 그런 거 같아요. 의식은 있으신 거죠? 네 의식은 있는데 정확하게 뭐 가타부타 대답을 못하고 있어요. 그쪽으로 선생님 구급차 보낼 거고요. 혹시 코로나 관련해서 해당 사항 있으실까요? 코로나 바이러스 주사 저기 뭐냐 주사 2차까지 다 맞은 친구인데? 그 삼성동 맞으시죠? 선생님. 네, 네, 네. 그쪽으로 구급차 보냈고요. 선생님 저희 응급실로 가는 거 알고 계시죠? 응급실로 가야죠. 우선은 주차도 받아야 되니까. 일단 구급차 보냈고요. 선생님 전화 좀 잘 받아주세요. 네.
 알겠습니다. 안녕하세요. 예 말씀하세요. 선생님 아 그 그 구도차 좀 보내주세요. 예 어디 가 보세요? 아저씨 아 잠깐 사고가 있어가지고 아저씨 사고가 나셨다고요? 네네네 아저씨 아 칼이 좀 깊숙하게 찔렸어요. 칼이 찔렸다고요? 네네 다리가 줄였는데. 어 다리 다리가 줄였어요? 네네 지금 피 좀 많이 나가지고. 네네 선생님 일단 주소 주소 먼저 좀 불러주세요. 네 여기 송파구 오금로. 오금동. 오금동. 오금동. 몇 층 몇 층 있으세요? 여기가 더스. 네네 아. 알겠습니다. 고급차 출발했고요. 선생님 혹시 혼자 계세요? 와이프 있는데 이게 뭐 어떻게 찔린 거예요? 떨어뜨린 거예요? 팔을 떨어뜨린 거예요? 네네 어 일단 알겠습니다. 그 전화 가면 전화 받으시고요. 그 수건 같은 걸로 지혈 좀 하고 계세요. 7V 아 네 알겠습니다. 얼마나 걸릴까요? 저 지금 어디가 어지러운데 한 10분 내외로 도착할 겁니다. 최대한 빨리 바로 갈게요. 네 알겠습니다.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 아, 시험 온 사이트. 네, 여보세요? 네. 네, 안녕하세요. 저기 여기 그 여기 그 친구 어제 그 HPV 그 백신 맞았는데 지금 파리 전체 다 부었고 그리고 열 젊은 난 것 같아요. 아, 구급차 요청하신 거죠? 네. 주소 불러주세요. 소대문구 연세로 연세로? 네 이낙일 이낙일 몇층 몇호요? 아니요 그러면? 네 아니요 아니요 네 감사합니다.
 네, 여보세요? 예, 안녕하세요? 저 다른 게 아니고. 예. 백계병인데. 예예. 하 지금 몸이 너무 안 좋아가지고 백계병을 했는데 눈이 안 보였어요. 그 골치이시고 하고. 예예. 근데 지금 몸에 헤르페이스가 와서. 예. 지금 뭐 방법이 없어 지금 응급실에 가야 되는데. 아 지금 골치에 보내드릴까요? 예 저 근데 집에서 다른 병원 받아주시질 않아요. 지금 서울대병원 2병원인데 저 글로 가야 되거든요. 서울대병원이요? 예 일단 주소가 거고요. 주소가 어떻게 돼요? 네 서울시 대본구 방학청 청구 아파트요. 예 청구 아파트. 가족분들 포함해서 코로나 자아경이나 확인 관련한 건 없어요? 없어요. 알겠습니다. 수고할게요.
 네, 읽습니다. 네, 여기 전차렌즈. 네. 저희 직원 식은땀을 흘리고 잘 안 들린데요. 얼굴이 하얘졌어요. 아, 그래요? 여자분인가요? 아니 남자분이에요. 아, 뭐 어지럽든 증상도 있으신가요? 어지러워? 어지럽대요. 그래서 잘 안 들린데요. 네. 코로나 관련해서 열이나 기침. 호흡곤. 열은 없어요. 붙임도 안 해요. 열 수 다 됐어요. 네 알겠습니다. 그 전자랜드 매장 앞으로 갈게요. 구급차요. 네 알겠습니다. 이거. 네.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 예, 입니다. 수고하십니다. 여기 저 신강역 일본 측 옆에 송동 차차차 스톤도 빠는데요. 우리 손님이 손님을 믿었는데 머리가 좀 많이 아프시다고 해가지고. 지금 못 바시라고. 아 머리가 아프시다는 거예요? 남성분이세요? 예, 남성분이군요. 남성분이시고 머리 아프시라고 그러시고 뭐 의식이란 보면 다 괜찮은데 머리만 아프다 그러시는 거예요? 예, 예. 알겠습니다. 선생님 신강역 일본 측으로 솔직히 이름이 뭐라 그러셨어요? 차차차? 알겠습니다.
 어. 어. 어. 여보세요? 네. 선생님 그 앞으로 나올 수 있어요? 글쎄요. 모르겠어요. 한 먹은 지 한 10분 정도 되는 것 같은데. 아니 건물 앞으로 못 나오겠어요? 네 지금 왔다 갔다 해 아니 못 나오겠냐고요 밖으로 걸어서? 예 예 천천히 나오시겠어요? 아니 지금 힘이 없어요 힘이 없어요? 예 알겠어요 전화오면 잘 받아요 아니 그거를 확인을 못 하겠어요? 예 모르겠어요 그 아니 하나 있네 잠깐만요
 네, 일요일입니다. 말씀하세요. 예, 여기 지금 취객 한 분이 누워 계셔서 길에. 남자분인가요? 예, 예. 의식이랑 호흡은 있으세요? 잠시만요. 네. 의식 아, 일단 예, 그 지금 오락가락 하시는 거 같고. 출근에 출시 있죠? 잠꼬대. 예, 예. 아, 그 위치가 어떻게 될까요? 어, 교보 타워 뒤쪽인데. 교보 타워요? 예 교보타워 아 교보 교복 뒤쪽이고 교보 탱년? 예예 노원역 교보 뒤쪽이고 여기 전주 콩나물 국밥 전문점이라고 해서 잠시만요 전주 콩나물 국밥 아 노원역 교보 탱년 뒤쪽으로 전주 콩나물 국밥 그 앞으로 가면 될까요? 예예 여기 들어가겠습니다. 아 신고자분 지나갔다고 신고하신 거죠? 예예. 네 알겠습니다. 저희 대응도 나가면서 전화드릴 수 있어요. 전화받아 안내 좀 부탁드릴게요. 예.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네 누구입니다? 네 안녕하세요. 여기 그 명동인데요. 주소가 어떻게 되세요? 여기 잠시만요. 여기 서울 중구. 예 중구. 잠깐만요. 서울 중구 명동 탈락이. 나가 나라 할 때 난가요? 네 네 가 나 할 때 나요. 나 탈 나기. 네. 그 몇 층 몇 호예요? 어 여기. 로드샵이라서 매장인데 아 무슨 일이세요? 지금 그 직원 한 명이 그거 손톱이 들려서 손까지 끼워졌거든요 아 손이 뭐에 다치신 거예요? 이게 그 철문에 손이 찢어가지고 아 철문에 뭐에 끼어 있거나 지금 아니 아니 그런 건 아닌 거죠? 아니고 남자분이세요 여자분이세요? 남자예요 남성분이시고요 예 알겠습니다. 그분 뭐 코로나가는데 연락을 뭐 기침 가려진 사람 없으신 거죠? 네 알겠습니다. 예 구차 보냈습니다. 전화 잘 받아주세요. 네 감사합니다.
 네 119입니다. 안녕하세요. 예 말씀하세요. 생일통이 너무 심한데요. 예. 저는 못 가겠어서 그럼 가야 되는데. 아 통증이 너무 심해서 응급실에 가보시라고 하시는데 지금 거동이 안 되시는 거예요? 네. 예 그 주소 좀 알려주세요. 상봉동. 네. 지금 쌍용아파트. 상봉동 쌍용아파트? 잠시만요. 그 지번은 모르세요? 구주소나 신주소? 상봉동 네. 매출 몇으로 가면 돼요? 지금 아파트 앞에 내려와있어서 앞에 나와있어야 1 2번 걸어가겠어요. 그 앞에 있다는 거죠? 네 LG 아파트 맞아요? 네 아 예 알겠습니다 보러 가볼게요 선생님 네 예 구급자 보이면 이쪽이라고 안내 좀 해주세요 네 네 네 선생님 심호흡하고 계세요 금방 가볼게요 네 네 네 네 네. 네. 선생님 구급차 가고 있어요. 뭐 최근에 발열이나 코로나 관련 사항 없으시죠? 네. 네. 알겠습니다. 가고 있어요. 좀만 기다리고 계세요. 선생님. 네. 네. 네 선생님 통화 종료할게요. 네
 일로 봅니다. 예 여기 저기 프라이팰리스. 네? 아 아파서 그러는데요. 몇 호예요? 이름이 뭐라고요? 아파트 이름이? 아파트 프라이팰리스 저 롯데캐슬 앞에 서. 여기가 어디고요? 지금 위치가 안 떠서요. 아 여기요. 고등로. 고등로요? 예. 잠시만요. 광동구 고동로 네네. 네. 어디가 아프세요? 가슴이 아파서 지금. 쫄쫄 맨에요. 아 누가 아픈 거예요? 신고자분 본인이 아픈 거예요? 아 아저씨가. 남편이요? 네네. 가슴 통증이 심하대요? 네네. 심하고 고정 힘들어요? 아니 걸어갈 수도 있어요. 걸어갈 수도 있어요? 네. 그럼 뭐 전화받으면 1층으로 내려오실 수 있겠어요? 예 1층으로 내내 예 이따가 전화받으면 내려오시고 열이나 기침 뭐 코로나 관련 사항 있으세요? 예 그런 건 아니에요. 맞아요. 여기 프라이어 팰리스 예예 예 알겠습니다. 전화 잘 받으세요. 예예 예
 네. 안녕하세요. 저 지금 오른쪽 옆구리가 갑자기 너무 아파서. 네. 병원에 가고 싶거든요. 주소가 어떻게 되세요? 거기가 강남역. 센트럴 프루지오 센터 센트럴 프루지오. 네. 네네. 네. 우차는 출발했고요. 강남역 센트럴 프루지오 시티 맞아요? 오피스텔. 네. 프루지오 시티 오피스텔. 알겠습니다. 차 출발했고 열이나 기침이란 증상 있나요? 그런 건 전혀 없습니다. 아. 네. 알겠습니다. 조금만 기다려 주세요. 문 열어 주시면 한번 열어주세요. 네네. 네.
 수고하십니다. 그 제가 지금 머리에서 피가 나가지고요. 어디 맞았어요? 아니면 뭐 어디 넘어졌어요? 왜 그래요? 그 문 그 앉았다 이러다 문꼬리에 찍혀가지고 머리에서 피가 좀 나는 거 같은데. 구급차 보낼까요? 네. 네. 주소 어떻게 돼요? 지금 서명한 거 간호대로 1대1. 간호대로 1 길에. . . 집에 코로나 확진자 자가격리자 있어요 없어요? 없어요? 네. 부급차 보낼게요. 전화 잘 받으세요. 네. .
 네, 일요일입니다. 말씀하세요. 예, 저희 어머니 좀 더. 네. 어, 원래 거동을 못 하셨는데요. 네. 다리가 너무 큰 다리 너무 부었고 지금 너무 아프시다고 하시네요. 잠시만요. 89세시고요. 지금 응급시 가지고 오신 거 맞으시죠? 주소 어떻게 될까요? 아, 어, 9000요? 9000 에 구. 네 구천면으로. 구천면으로. 몇 층 몇 도로 가면 될까요? 잠시만요. 탕. 청. 청문 빌라요? 청남. 청남. 예예. 몇 도 몇 도시라고요? 아 죄송해요. 전화가 좀 끊겨가지고 어머니 의식이랑 호흡은 다 있으시죠? 네네. 아 최근에 코로나 관련해서 뭐 접촉했다고 문자 받으시고 하나 그런 거 없으시죠? 네네 없습니다. 배원들 나가면서 전화드릴 수 있으니까 전화하면 잘 받아주세요. 네. 네.
 네 빨리 와주세요. 여기 구로로. 네 계단에서 불렀어요. 빨리 와주세요. 누가 구단을 계단을 구른거에요? 아아아아아아아 네 남자분이요 돌려주세요 의식이 있어요 없어요? 있어요 없어요 숨을 쉬어요 안 쉬어요? 그건 모르겠어요 지금 한번 보세요 숨을 쉬는지 안 쉬는지 곧장 가고 있어요 네에에에 괜찮아요 한번 보세요 지금 그건 못 쉬어요 저는 지금 몰라요 몰라 나도 보시라고 곧장 가고 있으니까요 보고 있어요 숨을 쉬냐고 물어보시네 몰라요. 아 빨리 와보세요. 고급차 가고 있으니깐요. 몇 층에서 지금 고른 거예요. 예? 아 정신 있대요. 예 정신 있다고요? 예 예 예. 빨리 와주세요. 몇 층으로 가면 돼요? 1층이요. 1층 2층에서 제가 다시 불렀어요. 1층이요. 예 예. 고급차 불렀어요.
 여보세요? 예, 119예요. 저희 순복원교에 예, 순복원교에 앞에 있는 버스에서 어르신이 쓰러진 거예요? 어머니가? 네, 일어나지 못하셔가지고 119로 여기로 119예요? 그러면? 예, 제가 고쳐서 가는데 어디가 아프시대요? 어머니가? 아 이 다리가 아프셔서 약을 드셨는데 일어나지 못해가지고 다리 힘이 없어 일어나지 못하세요. 지금. 아 힘이 없어서? 뭐 이식 없거나 숨 못 쉬거나 코로나 관련 열흘 그런 건 없으시고요. 거기 순복음교회 앞으로 가면 만날 수 있는 거죠? 어 어디냐면 순복음교회. 버스 안에 계신 거죠? 순복음교회 앞에 있는데. 예. GS 칼패스 주유소 바로 옆에 있어요. 배원들 가고 있으니까 전화하면은 위치 설명해주세요. 출동했어요. 같이 계시죠? 예.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 예. 여기 어 이거 이 한 아버지로 누워 계신데 건물 안 계세요? 예예. 주소 알려주세요. 주소가 여기 그 은평구 불광동 연신교회. 연신교회요? 예. 연신교회 옆에 그 세븐이너번 편의점 있거든요. 그 건물. 무슨 점이요? 편의점이요. 편의점 무슨 점이냐고요. 그니까. 그만 있어. 그 연신교회 옆에. 연신교회 옆에 작은 데 하나 있어요. 세븐일러고 무슨 점이. 무슨 점이냐고 적혀 있어요. 안 적혀 있어요. 안 적혀 있어요? 예 세븐일러브만 적혀 있고. 그 두 군데 있는데 큰 길거리고 안쪽에 있는데. 그 연신께하고 그 연신께 바로 옆에 있어요. 그 건물에 그 세븐일레븐 건물에. 연신께 옆이에요? 예예. 그 세븐일레븐 그 그 거기서 들어와 그 큰 길에서 들어오셔가지고 연신께 쪽으로 들어오시면은 지금 그 건물에 할아버지가 누워 누워 계신데 지금. 옆에 있는 세븐일레븐에 누워있어요? 예예예. 세븐일레븐 건물에 이거 지금 날이 영화 11도인데 지금. 연신교회 옆에 있는 세븐일레븐에. 예예예. 바로 옆에. 누워있다는 거죠? 의식이 있어요? 예예. 건물에 예? 예. 예. 신문을 신문을 내시는 거 보니까 의식은 있는 거 같은데. 네. 차 나가볼게요. 예
 네 여기 여기 그 한 분이 조금 무릎이 조금 다치고 손이 조금 다쳤거든요. 근데 이게 되게 유사는 아닌데 조금만 해주실 수 있나요? 어 남자 여자예요? 여자분이요. 주소 아세요? 네. 어 주소 어떻게 돼요? 잠시만요. 네. 반포동. 예. 예. 예. 한솔밀라. 한솔이요. 한솔. 한솔? 예. 그 가족 되시는 거예요? 예. 제가 보호자예요. 가족분들 중에 코로나 지역 반영원화 관련 증상 있나요? 아니요. 음료실 간 사항은 아닌데요. 아 그러니까 동선 겹치거나 기침 발효 아 그런 건 없어요. 네. 가볼게요. 네.
 예, 알겠습니다. 예, 이거 지금 코로나 백신 기사를 맞고요. 너무 아파서. 예, 누가 그러신 거예요? 예, 집사람이 좀. 아 아내분께서요? 지금 며칠 맞고 지금 많이 아파하시는 거예요? 주소가 어떻게 되세요? 예 은평구 고카발 어 장림 마을 그 롯데 몇 호예요? . 네 알겠어요 어머니가 지금 의식이랑 그런거 괜찮으신거죠? 네 계속 통하고 있고요 열이 너무 많아요 예 알겠습니다. 그럼 저 지금 가볼게요. 네 알겠습니다. .
 네, 16입니다. 말씀하세요. 네, 여보세요. 네, 말씀하세요. 힐탑 힐탑 하우스요. 여보세요? 네, 힐탑 하우스요. 수일이. 잠시만요. 힐탑 하우스요? 하우스. 그 하트는 안 주세요. 제가 지금 호흡이 곤란해갖고 전화하기가 힘드니까요. 아버님 인수복로 맞아요? 네. 힐탑 하우스. 네 몇 호예요? 힐팍하우스 네 내가 1층 1층 내려가 서 있을게요. 아 1층에 내려가 계신다고요? 네. 선생님이 숨쉬기 힘들다는 말씀이시죠? 네 숨쉬고 병원에 누워서 잠을 못 자서 삽니다. 그러니까 고 때 고 때 병원이라고 하라고요. 네 병원은 출동 나간 병원 기장 상의해 보시고요. 최근에 코로나 관련해서 뭐 의심 증상이나 접착착 문자 받으신 거 있으세요? 그거는 수원에다 입원 안 지겠어요. 10월 전에. 코로나 관련해서는 없으신 거죠? 네. 알겠습니다. 대원들 나가면서 전화드리시니까 전화받고 안내해 주세요. 네.
 7.9입니다. 네 여기 지금 직접 상황인데요. 누가 어떻게 안 좋으세요? 저희 할머니가 지금 의식 없으세요. 그 주소 좀 불러주세요. 선생님. 여기 망우 3동. 네. 네. 몇 층이에요? 일단 구급차 나갔고요. 할머니 의식 없는데 호흡은 하고 계신 거 맞아요? 네? 호흡은 하고 계세요? 호흡은 있어요. 호흡은 있어요. 호흡은 있으시고? 불러도 반응이 없다는 거죠? 네. 거기 진명아파트 맞나요, 선생님? 네, 네, 네. 대원들 가는 동안 전화드릴 거고요. 할머니 혹시 지금 코로나 확진자거나 정리 상태는 아니시죠? 아니요, 그런 건 없어요. 가는 동안 응급처치 안내해드릴게요. 끊지 마세요. 네.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네 여보세요? 아 네 안녕하세요. 여기 119인데요. 네 남자분 사러진 거 지나가라고 오셨어요? 아 지금 저희 집 앞에 지금 차 주차를 하려고 차를 댔는데. 네 앞에 누워계시거든요. 근데 앞으로 꼬꼬라져가지고 이렇게 누워계셔가지고. 아 그럼 의식이 정렬었어요? 아니 도착할 때는 옆으로 누워 움직이는 거 같았었거든요. 지금은 아예 아예 안 저기 안 움직이시거든요. 앞으로 지금 꼭 구워져 있어요? 네 앞으로 이렇게 이렇게 누워 누워 누워 그래서요. 일단 소방차랑 고급차랑 가고 있고요. 혹시 숨 쉬는지 멀리서 혹시 확인 가능해요? 모르랑 내력하는 그런 움직임 같은 거는 대충 이렇게 보이나요? 멀리서? 누가 뭐가요? 그 남자분이 숨을 쉬는 거 같아요. 아니 그래서 지금 불러도 안 깨시고. 아 그래요? 예 그 수고 계신 거 같은데 처음에 도착할 때는 움직이는 걸 봤었거든요. 아 그래요? 알겠습니다. 제가 바로 가볼게요.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 예, 읽습니다. 아 저기 어 신입병원에 지금 환자분이 계시거든요. 예, 예. 그래서 지금 어디 병원에 응급실을 가고 싶은데요. 여기 이 신입병원에서는 못한다고 그래서 지금. 지원 중이신 환자분이세요? 아니면. 아니에요. 그냥 지금 응급실에 있는 환자예요. 아 어디가 안 좋으신 건데요? 어 저기 허리가 지금 안 좋고요. 코로나를 22일날 맞았어요. 22일날 백신 맞으신 거네요? 네네네. 지금 필요하신 거는 병원 안내세요? 아니면? 아 병원을 좀 가려고요. 구급차가 필요하신 거네요? 네네. 신일병원 앞으로 보내드리긴 할 텐데 조치가 이송이라든지 그 병원 결정 나중에 대원들하고 다시 한번 상의를 한번 해주세요. 어떻게 해요? 그 병원 결정이라든지 그런 부분은 나중에 대원분하고 대원들하고 대원들하고 다시 한번 상의해주세요. 네네네네네네. 어느 병원으로 가는 거는 그분들이 아신라거든요. 네 감사합니다. 실정원 앞에 그러면 나가는 나가지 못하는데. 전화 받고 안내해 주세요. 예.
 네. 저희 어머니가 좀 많이 아픈데 병원에 좀 갔으면 해서요. 예. 어디가 아프세요? 감을 먹었는데 그걸 다투하더니 힘을 못 쓰시네요. 예. 의식은 괜찮으신 거죠? 그냥 잘 못 그냥 겨우 그냥 말만 못 일어나요. 아니요. 뭐 헛소리하거나 뭐 논 돌아가거나 그런 상황은 아니에요? 예. 아직 그러진 않아요. 예. 알겠습니다. 주소 불러주시면 주소 나갑니다. 흥낙동 네네 몇 호세요? 건물 이름 혹시 있으세요? 최동산 약국이에요 약국 건물이요? 예예 예 그 코로나 환자 있거나 재택치료자 있거나 그런 상황 아니고 없어요 없어요 네 직통했으니까 전화 올 거에 잘 받아주세요 예

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네, 1 9입니다. 예, 안녕하세요. 그 코로나 혹시 그 코로나 환자는 아닌 거 같고요. 예, 예. 아버지가 지금 저 속이 좀 많이 안 좋아서 모숨 죽이고 계시는데 제가 모시고 갈라 그랬는데. 예, 그 지금 일부분들이 좀 도움이 필요해서. 도움이 잘 필요하신 거고요? 네, 네. 네, 응급식으로. 속이 속이 좋지 않으시고 또 다른 다른 증상 같은 거 있으세요? 아니면. 일단 식은땀 나고 변이 좀 많이 까맣고. 아 예. 좀 두통도 조금 있으시고. 삼계층 나서. 아 주소 한번 불러주세요. 주소는요. 네. 묵동 중남구 묵동. 묵이동. 네네. 몇 주 몇 주 계세요? 어 여기 계시면 제가 밖에 나와 있을게요. 아 알겠습니다. 혹시 뭐 가족분 포함해서 기침이나 고울 같은 코로나 관련 증상. 여행량이 없으시죠? 네. 없습니다. 차 나갑니다. 전화 잘 부탁드려주세요. 네. 감사합니다.
 수고하십니다. 여보세요? 아 예예예. 저기 지금 딸내미가 복통을 일으켜가지고 좀 참을 수가 없어요. 그래서 병원을 좀 가야 되는데. 여기 신반포 청구 아파트입니다. 신반포 청구 아파트고 몇 동 몇 도예요? 네, 네, 네. 예, 지금 집에 코로나 환자나 자가격리자 없는. 그건 없습니다. 배가 아픈 거죠, 딸이? 예, 예, 예. 구급차 보냈습니다. 전화 잘 받으세요. 예, 예, 예. 구급차 구급차 구급차. 호름아, 어디있다 구급차.
 예. 수고하십니다. 말씀하세요. 예. 여기 서초구 방대천로. 방대천로. 16길. 16길. 네, 감사합니다. 일단 시켰고요. 코로나가 걸렸던 적 있거나. 28일날 아 자가 격리가 26일날 해결했어요. 접촉자. 아 작년에 12월 26일자로요? 그렇죠. 예. 26일날 자가 격리 해제. 뭐 밀접 접촉이었어요? 아니면 해외에서 입고 가셨어요? 접촉자. 접촉자 국내. 알겠습니다. 그 보급 대원님 가면서 전화 오니까 잘 받아주세요. 그리고 여 28일날 제가 여 어 코로나 예방접종 이사를 받았어요. 네 알겠습니다. 고급 대원이 일단은 가는 중에 전화 옵니다. 잘 받아주시기만 하면 됩니다.
 예, 여보세요? 예, 저 어머니가 아프시다고 지금 전화 전화 주신 거죠? 강동 리버파크. 네. 네. 어머니 어디가 안좋다고 말씀하시나요? 일단 오하심같이 덜덜덜 떨리고 춥고 어머니 지금 몸살이 있는거 같다고 하시는데 지금 어제 밤에도 많이 아프셨다고 하셨거든요. 아 뭐 선생님 뭐 코로나 관련된 상황이 있으셨나요 어머니가? 어 지금 그런건 없었던거 같은데 좀 걱정도 되고 제가 확인할건데 시간이 한 두세시간 걸릴거 같아서 네. 저도 가보셔야 될 것 같아요. 그래서. 알겠습니다. 저희가 어머니랑 통화를 한번 하면서 가볼게요. 저희가. 강일 리버파크 10단지 말씀 강솔 초등학교 옆에 있는 거 말씀하시는 거 맞죠? 네네. 강일 리버파크 10단지요. 알겠습니다. 저희가 통화해볼게요. 어머니랑. 예. 감사합니다. 예.
 1 2 5 5 6 6 6 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 . . . . . . . . . . . . . . . . 차 나갔으니깐요. 조금이라도 좀 안 좋아지시면 다시 전화하세요. 아 네네 감사합니다. 전화 오면 잘 받아주시고요. 네.
 예, 여기 뚝선로. 잠깐만 뚝선로. 예, 예. 200 몇 동이요? 예, 예. 무슨 일이에요? 아 갑자기 저 다리가 이게 돌아가가지고 지금. 예, 예. 학생분이요? 아니요. 지금 가족이요. 누구요? 와이프요. 아 네. 그 오성아파트에서 예 예 예 예 구급 접근했고요. 그 가족분들 중에 코로나 지역 다녀오거나 관련. 아 없어요 없어요. 예 예 없어요. 네 네 가볼게요.
 네. 여보세요? 예. 아버님이 119 오지 말라고 하시는데요. 아니 어머니 상태가 안 좋으신데 어떻게 안 온가요? 일단 가서 가서 다 보셔야 될 것 같아요. 어머니 지금 상태가 너무 안 좋으세요. 일단 가고 있는데 아버지가 거부하시면 저희가 이성 못합니다. 선생님. 네. 아 네. 말씀 드려볼게요. 네. 말씀 좀 드려두세요. 설득하고 계셔야 돼요.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 입니다. 여보세요. 예 말씀하세요. 응급실을 좀 갈라 그러는데요. 아 예 어머니 본인이 아프신 거예요? 예. 어디가 안 좋으세요? 제가 여기 고관절이 너무 아파갖고 화장실 좀 못하고. 아 고관절 아파서 아예 고등이 안 되시고요? 움직이도 못하고. 어 예 주소 어떻게 되세요? 어. 양충도. 예. 목동동로. 잠시만 목동동로 예. 12길 12길 목동 현대 아파트. 예 몇 도 몇 도예요? 상단문 열어주실 수 있겠어요? 아니요. 식구들이 있거든요. 아 식구들 있어요? 예 알겠어요. 그쪽으로 갈 건데요. 제가 열어버려 뭐냐 못 움직여요. 어 열은 어때요? 지금 열 증상 같은 거는. 열은 하나도 안 나요. 지금. 열은 안 나시고? 예 알겠어요. 자 글자 가볼게요.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 죄송합니다. 말씀하세요. 여기 저 어 용산구. 네. 무슨 무슨 한강대로 한강대로 한강대로 한양대로 한양량이 예. 한양량 예 출발했고요. 선생님 전화 끊지 마세요. 예, 예. 야, 소리 안 났던냐?
 네. 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여� 예? 의식이 있어요? 없어요? 의식은 있는데. 아 그래요? 그냥 꽉 찢어져가지고. 요 동네 병원이 다시 오늘. 예 일단 저 예. 구급차 그쪽으로 보냈고요. 예. 네. 깨끗한 수건으로 꼭 눌러서 지여 좀 하고 계세요. 아 지금 지여를 하고 있는데. 예 알겠습니다. 구급차 가고 있습니다. 출동 시켰어요. 예 빨리 좀 해주세요. 예.
 1 2 9 입니다. 네 지금 할아버지가 쓰러져서 주셔 가지고요. 그럼 주소 좀 불러주세요. 여기 해바라기 정육식당이요. 해바라기 정육식당. 잠시만요. 북산동 해바라기 정육식당. 네 네 네. 선생님 고급차 나갈 거고요. 할아버지 지금 의식 있어요? 없어요? 의식이 있는데 지금. 뭐 하다가 쓰러지셨어요? 어? 있다 없다 그래요. 뭐 하다가 쓰러지신 거예요? 밥 먹다가 쓰러지신 거예요? 식사하다가 식사. 식사하다가. 고급차 나간다고 보호자분한테 얘기 좀 해주시고요. 네. 그 할아버지 혹시 뭐 기도에 뭐 이물 걸려 있거나 그러진 않아요? 아니요. 없어요. 그런 건 없고? 네. 알겠습니다. 대원에 가니까 안내 좀 해주세요. 네. 네. 네.
 네, 알겠습니다. 여보세요? 예, 말씀하세요. 예, 여기 저 합정동. 네네. 여기 저 3구 아 가만있어. 여기가. 아 저 지금 저 몸이 좀 안 좋아서 저 세계란서 좀 가려고 그러는데요. 주소 알려주세요. 선생님. 예? 주소. 네, 합정동 여기가 청도 청도 빌라. 성도밀라요? 예 여기 저 저 저기 저 어디냐 하면은 그 저 망원정 밑에요 성도밀라가? 예 누가 어디가 아프신 거예요? 아 저 집사람이 좀 몸이 좀 안 좋아서요 세부랑 좀 좀 하려고요 증상이 어떤 증상이 있으신 거예요? 어디가 아프신가요? 아 그 저 목 있는 데가 아파갖고 가슴이 벌렁벌렁 뛰고 그래서요 가슴이 아프신 거예요? 가슴은 아프 아파? 아프지는 않은데. 아프지는 않은데. 벌렁벌렁 뛰고 막 그냥 아파서 목이 매우고 그랬어요. 선생님 주소가 그 학생동. 예 잠깐만요. 내가 그걸. 주소 좀 어떻게 보세요. 정확하게. 예. 예 적어 놓은 것이 그 당신 저 전화에 찍혔잖아. 그거 좀 봐봐. 주소 여기. 아이고 아이고 내가 그 종이를 다 적어놨었는데 이거 들어가고 없네. 어디. 예. 얼른 찾아봐. 선생님 11차 성도 빌라가 맞아요? 아 11차 여기 저 저 거 저 저기 장면은 군부자 뒤에 거 저 밑에인데요. 그 저 어디냐 하면은 그 저 망원동 바로 밑이에요. 아 선생님 선생님 11차 성도 빌라가 맞냐고요. 몇 동이에요? 몇 동 가나다라마동. 합정동. 네 알겠습니다. 코로나 관련해서 열린 기침 호흡곤란 같은 건 없어요? 네? 감기 증상 같은 건 없어요? 코로나 관련 증상? 네 없어요 그런 건 없어요. 아 그래요 알겠습니다. 3차 다 맞고요. 네. 네. 네. 넌 챙겨.
 119입니다. 말씀하세요. 잠시만요. 아버지가. 네. 네. 저희 아버지님이 연세가 좀 있으신데. 네. 혈전이 좀 나오신다고. 머리가 좀 많이 안 좋으신가 봐요. 네. 네. 아버지 뭐 코로나 관련해서 열이나 기침 이런 증상이 있었나요? 아니요. 그런 증상은 없으셨고. 이따까지 저기 백신 맞으셨고요. 네. 알겠습니다. 조금만 기다려주세요. 네. 네.
 예, 안녕하세요. 예, 말씀하세요. 네, 저희 아버지 방에서 돌아가신 거 같은데요. 좀 와서. 아, 아버지가요? 아, 예, 지금 의식으로 호요 아예 없는 거예요? 네, 아버지가 인종 맞으셨는데 그 와서 사망 진단하는 의사도 같이 동행해 주세요. 그러면은요. 아, 선생님 주소지만 불러주세요. 네, 마포구 구수동. 구수동이요? 네. 예. 알겠어요. 곧 저쪽으로 가고요. 선생님 저희가. 네. 의료 상담원서 연결이 되니까 전화 끊지 말고 기다리고 계세요. 네.
 예 119입니다. 아 예 안녕하세요. 여기 지하철 2호선 잠실나루역입니다. 예 2호선 잠실나루역이요. 네네 여기 그 승객분 1분이요. 예예. 그 약간 음주 상태시긴 한 것 같은데 숨이 안 쉬어진다고 지금 계속 못 일어나시고 누워 계셔가지고요. 아 잠시만요. 남자분이에요? 여자분이에요? 여자분이요. 여자분이 호흡 곤란 호수하고 계신다는 거죠? 네네. 저희가 잠실나루역 어디로 가면 돼요? 어, 고객 안전실 바로 앞에 화장실이 있는데 거기 앞으로 오시면 돼요. 잠시만요. 그 잠실 나루역이요? 잠. 네, 잠실 나루역입니다. 2호선. 잠실 나루역 2호선 화장실 앞으로 가면 된다고요? 그 몇 번 그 이거 딜껏 들어가려면 몇 번 출고로 가는 게 빨라요? 어, 차를 대실려면 1번 출고 쪽에 거기 그 공용 주차장이 있으니까 그쪽으로 대시는 게 나을 것 같아요. 아 그 저희 들 것이 있어서 그 엘리베이터 타야 돼가지고 여쭤본거죠? 저희가 엘리베이터가 아니라 1층입니다. 지상 아 지상에 계세요? 예예 아 예 알겠습니다. 그럼 1번 출구 쪽으로 가볼게요. 잠시 그 화장실 앞에 있다는 거죠? 네네 네

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 일단 일단. 여보세요? 네. 어 저기. 여기가. 네. 어 옥수동에 있는 경희 한의원 앞에요. 경희 한의원이요? 네. 예. 무슨 일이세요? 네? 무슨 일이세요? 아 사고 났어요. 교통사고인가요? 네 네. 오토바이가 저 박아가지고. 오토바이랑 차가고 있으신 거예요? 예예. 차는 나갔고요. 선생님 다친 사람 그럼 1명인가요? 네. 선생님 지나가다 보신 거예요? 아니면 운전자세요? 아니 아니 제가 운전자예요. 제 뒤에서 뒤에서 오토바이가 받았어요. 아 의심은 있죠? 예예. 구급차 간다고 얘기 좀 해주세요. 예.
 119입니다. 예 저기 오목로 38길. 예 무슨 일이세요? 예 그 여 지금 사람이 쓰러져가지고 못 일어나서요. 아 예 남자분 여자분이요. 길 가다 보이시세요? 네? 길 가다 보신 거세요? 신고자분이요? 예 예 저희 집에 사시는 분 같은데 계단 쪽에 그냥 쓰러져가지고 못 일어나세요. 아 예 구급차 저희가 보내드릴게요. 주소 다시 한번만 말씀해주세요. 오목로 38길 알겠습니다. 저희가 출동해보겠습니다. 네.
 여기요. 강서로. 근데 1분이 지금 네. 지금 인사 불편이세요. 누워계세요. 어 술 많이 드시고? 어 술을 잘 모르겠어요. 술을 드신 건지 어떤 건지 모르겠는데. 술 냄새 안 마신데요. 그냥 누워계신 거예요. 그러면 모르는 할아버지예요? 네. 어 그래 알겠어요 갈 텐데 수능 정상적으로 쉬고 있어요? 예 그 말은 말씀은 하세요. 알겠습니다. 가보겠습니다 빨리. 네. 네.
 예, 119입니다. 네, 수고하십니다. 아, 우리 아씨가 갑자기 이렇게 아파가지고요. 어디가 아프신 거예요? 남편? 어, 가슴 통증이 있다 그래서. 통증세로 그러시는 거예요? 예, 어디에. 참다가 지금 못 참아가지고. 어, 주소를 좀 불러주실래요? 아, 여기 어, 광복구 번동. 광복구 번동. 몇 층이에요? 네. 콕사 진단받고 이런 건 없으신 거? 아유 지사는 진단 맞았어요. 12월 1일 날 맞았어요. 알았어요. 구급차 보내드렸고요. 네. 어 대원들 미화동에서 나갈 거예요. 가면서 전화드릴 수 있어요? 예.
 여보세요? 네네. 구급처 가고 있고요. 네네. 네. 그 어시피 호흡은 있어요? 있어요. 있어요. 근데 지금 일어나겠대요. 아 그래요? 예. 구급처 가고 있고요. 네네. 그 ...으로 가면 되죠? 네네 예, 가고 있습니다. 조금만 기다려주세요. 코로나 된 상황처럼 머리 열나고 있잖아. 그런 건 없죠? 네, 열은 없는 것 같아요. 네, 조금만 기다려주세요.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 아 알겠습니다. 근데 위치만 좀 정확하게 한번 거기 앞에 뭐 간판 같은 게 보이는 게 있을까요? 아 여기가 다리 그 고가도로 같은 데 바로 옆 도로거든요. 고가도로 아래예요? 네 여기 여기. 위치 추적을 한번 해보고 있긴 한데 위치 추적이 안 돼서요. 여기가 경남 특수광이라고 써 있는 간판이 보이긴 하는데. 특수광이요? 아니 아니 여기 여기가 주차장인데 제가 레벨을 한번 볼게요. 레벨을 한번 볼게요. 네 여기 그 GS 타임즈 영등포 주차장 옆에 있거든요. GS 타임즈요? 예 GS 타임즈 영등포 주차장이요. 아 알겠습니다. 거기 주차장으로 들어가야 될까요? 아니요. 주차장으로 들어가면 안 되고요. 여기 어차피 딱 보시면은 고가도로가 바로 보여서. 그렇죠. 고가도로 위에 있네요. 예 그 옆에 도로예요. 알겠습니다. 알겠습니다. 그 고급대가 갈 건데 선생님 좀 기다려 주실 수 있나요? 아니면 지나가실 건가요? 어 저도 금방 얼마나 걸릴까요? 지금 가는 길에. 아 신도림동에서 출동해서 3km 거리에서 출동해서 한 10분 정도? 5분에서 10분 정도요. 네 그 정도면은 있을 수 있을 것 같아요. 네 알겠습니다. 일단 경찰관님 모르니까 경찰관이나 고급대랑 가보겠습니다.
 네 여기 고려대로 11길 11길에 네 지금 저희 어머니께서 저녁에 저녁 주시고부터 오시는 구초가 있고 지금 어지럽다 하시고 혈압 떨어지시는 것 같아서 병원을 좀 가야 될 것 같은데 혹시 운송이 좀 가능할까요? 네. 구급차 보내고요. 열 있거나 그러진 않으세요? 열은 안 마시고요. 지금 코로나 때문에 격리하시는 분이나 확진자 가족분들 중에 있거나 그런 거 없으세요? 네. 그런 분은 없고요. 그리고 뭐 의식은 괜찮으시고요. 네. 차는 보냈어요. 조금 대기동역 쪽에서 가니까 조금 걸릴 거예요. 기다리세요. 네.
 일제곱니다. 어 저희 할아버지가 호흡이 잘 안 돼요. 의식은 있으세요? 할아버지? 네. 주소 좀 불러주세요. 선생님. 여기 성원 아 강복구 어디서 불러요? 지금 오이동 성원 아파트. 잠시만요. 거기가 삼양로. 네. 고급차 갈 거고요. 네. 혹시 할아버지 평소에 지저질환 같은 게 있으셨어요? 네. 당뇨 있으시고. 네. 심장질환이나 폐쇄질환 같은 거는요? 심장질환 있죠. 심장질환 있는데 정확한 병명은 모르겠어요. 그래요? 지금 열나거나 기침할거나 그런 점은 없고요? 여름 뭐 체온계가 없어서 모르겠는데 기침은 딱히 없으세요. 혹시 코로나 때문에 격리 상태를 아니시죠? 네. 구급처 나갔고요. 할아버지 대화도 많이 힘드신가요? 지금 호흡 때문에? 근데 말이 평상시 같진 않아요. 그래요? 저희 구급처 가는 동안 응급처치 안내해드릴게요. 끊지 마세요.
 네. 열리 겁니다. 여보세요? 예. 말씀하세요. 저희 여기 범양 아파트. 범양이요? 네. 범양 아파트요. 네네. 저기 지금 누나가 173차를 맞았는데. 열이 39점 몇 도에서 떨어지지가 않아요. 39도에서 떨어지지가 않아서 지금. 병원에 가려고 하는데 혹시 구급차 부를 수 있을까요? 예. 부를 수 있고요. 지금 의사 선생님도 연결해 드릴게요. 나가면서 전화 끊지 마세요. 코로나 확진되신 분 없으시죠? 가족 중에? 네. 전화 끊지 마세요.
 네, 수고하십니다. 예, 예. 예, 저는 소대문 노인 복지관에 생활 지원사인데요. 예, 예. 예, 제가 돌보는 어르신께서 지금 배가 많이 아프셔가지고. 여성분 보내세요? 남성분이세요? 여자입니다. 아, 어르신이 배가 아프다고요? 예, 배가 많이 아프셔가지고. 예, 그거 하고 막 그러시나 봐요. 예, 주소 좀 알려주실래요? 예 세검 동로 1 1길 어 세검 동로 예 일길 일길에 예 풍림 2차 아파트 예 2차 아파트 예예 그 환자분하고 지금 같이 계신 거예요? 아닙니다. 저는 다른 곳에 있습니다. 그러면 전화번호 알 수 있을까요? 그 어르신은요? 예 어르신 전화번호 예 네, 맞습니다. 예, 알겠습니다. 예, 집 전화는 안 가르쳐 드릴까요? 예, 예, 핸드폰 있으면 됐고요. 그 분이 뭐 자가격리자는 확진자는 아니신 거죠? 코로나 관련돼서. 네, 아닙니다. 네, 아닙니다. 예, 알겠습니다. 그쪽으로 구부차 보낼게요. 네, 네, 감사합니다.
 일요일 주구입니다. 네 여기 저 동대문구 용두동 용두동? 예 오션 고시원인데요. 오션 고시원. 네 지금 여기 저 1분이 지금 아주 저 아파가지고 그러니까 좀 빨리 오세요. 아 예 남자예요 여자예요? 남자분이세요? 나이가 많으세요. 어디 아프신 거 같아요? 아이 지금 저기 숨 쉬기가 좀 불편하다고 막 가슴을 탁탁 때리고 그러니깐. 예 고시원 몇 층으로 가야 되죠? 예예. 고급차는 여송 중이고요. 지금 뭐 코로나 환자 시거나 그런 거나 확인이 되신가요? 아이 저 다 하는데 그 이상 없어요. 며칠 전에도 왔었는데 119 불러서 다 검사했는데 아무 이상 없는데 조금 나왔다가 안 간다 그래가지고 있는데 지금 오늘 더 대단하다 그러니까. 알겠습니다. 동시에 제가 고급차 요청했으니까 전화 올 거예요. 잘 받아주십시오. 네 주동 나갔습니다.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네 조금 전에 전화했었던 어 71세 여성 환자 태양 환자 보호자인데요. 어머니요? 어머니? 네 어머니예요. 네. 지금 현재 좀 호흡곤란이 한 4 5시부터 계속 있으면서. 구급차 구급차 요청하시려고 하는 거예요? 어 구급차 요청을 하고 싶은데 지금 와서 일단 상황을 좀 판단해주셨으면 해서요. 주소 좀 알려주세요. 빨리. 여의대방로 44개 시 7 대방주공 아파트 2단지. 선생님 잠깐만요. 제가 받아서 가야 되니까 여의대방로 44길. 혹시 열이 있거나 비친 코로나 관련 증상이 있어요? 열은 없습니다. 출동하겠습니다.
 수고하십니다. 말씀하세요. 여보세요? 예 말씀하세요. 선생님. 여보세요? 예예 말씀하세요. 예 수고하십니다. 예예. 독수남념 1번 출고 앞인데요. 예예. 술이 많이 드신 분이. 예. 여기 계시는데 날씨가 추워가지고. 예예예. 걱정이 돼가지고 전화드렸어요. 제가요. 아 예예 알겠습니다. 선생님 관계가 어떻게 되시는데요? 선생님 관계가 어떻게 되세요? 관계가. 아 저 모르는 사람인데요. 아 예 알겠습니다. 알겠습니다. 독산역 1번 측으로 가면 만날 수 있어요? 네 저 보면 저 가던 저 나들 가게 바로 앞에 있어요. 금고 금고 있죠? 금고? 새말 금고? 아니 새말 금고가 아니고. 예. 독산 1번 측으로 바로 앞에. 예. 저 그 손때는 자판기 자판기 있잖아요. 자판기 자판기 예예예. 예예 거기 길이 해가지고 저 술 너무 많이 돼 지금 날씨가 추운데. 예예 아 거기 앉아 있는 거예요 지금? 예 앉아있다가 이렇게 좀 놀으려고 그래 지금. 아 예예 알겠습니다. 알겠습니다. 저희가 한번 가볼게요. 예 날씨가 너무 추운데. 예 알겠습니다. 알겠습니다. 저희 갈 테니까 전화 다 좀 받아주세요. 예예. 예예.
 119입니다. 아 여보세요. 여기 어떤 사람이 자전거 타다가 쓰러져가지고 지금 무식불명 같은데요. 선생님 우리 주소가 어떻게 돼요? 어디로 가면 돼요? 아 여기가요. 어떻게 여기가 올림픽 공원 옆이거든요. 공원 안에 있는. 어 이쪽에 뭡니까? 골프장 있고요. 올림픽 공원 골프장이요? 네. 이쪽 야외 골프장 있잖아요. 올림픽 공원 안에 있는 골프장이에요? 네? 네? 올림픽 공원 안에 있는 골프장이요? 아 밖에 밖에 밖에 있는데 그 올림픽 이쪽에 성냥 둘레길 있잖아요. 성과 성과 둘레길 자전거 도로. 둘레길 자전거 혹시 주변에 보이는 건물 상호 같은 거 있으면 불러주세요. 주변에 보이는 건물이나 상호명 같은 거 있으면 좀 불러주시겠어요? 아니 그니까 이쪽에 그러면 골프장 있잖아요. 야외 골프장. 선생님 그렇게 말씀하시면 저희가 찾을 수가 없고요. 아 그럼 이 측에. 아 이 측에 현대 현대 차이더 아파트 현대 차이더. 개인 아파트 그 인근이에요? 네. 부급처 나갔고요. 지금 의식 있어요? 없어요? 예? 의식 있어요? 없어요? 환자분. 아 저 움직이는 못하고 있어요. 그니까 의식은 있다는 거죠? 네 네 의식이 없어요. 의식이 없어요? 아예? 네 아 제가 모르니까요. 아 저 선생님 저희가 환자분 상태를 정확히 알아야지 호흡이 없으셔도 의식이 좀 없으니. 아 지금 어떻게 해야 하는데 그 지나가지고 하는데요. 일단 구급차 간다고 그거 얘기 좀 해주세요. 기반에. 네? 구급차 간다고 얘기 좀 해달라고요. 네 네.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네 여기 코에트 코에트 4거리인데요. 네 HDC 건물 앞에. HDC 건물 네. 네 그 HDC 건물에서 영동 설교 바라보고 가면 그 도로가에 택시랑 일반 일반 차량 급성 사고 났는데요. 네 잠시만요. 그 뭐 누구 나오셨어요? 그 운전자는 다 나왔어요? 예 운전자는 지금 안에 있고. 예 못 나오는 건 아니에요? 아 예 다 의식은 있는데 목 같은데 아프다고 구급차 들어달라고 해서. 아 예 무지할 거나 하신 건 아니고요. 예 예 예 예 알겠습니다. 저희 경찰하고 같이 가고 있습니다. 경찰이요? 네. 그 교통사고는 경찰이 같이 가거든요. 아 지금 제가 경찰관인데요. 아 그러세요? 아 예 알겠습니다. 제가 불렀어요. 아 그래요? 그럼 구급차가 있으면 돼요? 예 알겠습니다. 네.
 네, 감사합니다. 선생님 그 여기 그 논현 1 파출소인데요. 네, 무슨 파출소라고요? 논현 1 파출소요. 논현 1 파출소요? 예. 네, 여기 그 부급차 좀 필요할 것 같습니다. 네, 무슨 일입니까? 그 신고 나갔었는데. 네. 그 좀 얼굴에 상처도 좀 많고. 음 남자분 여자분이요? 그 남자 2명 다 필요할 것 같아서요. 아 환자분이 2분이세요? 그럼? 네. 병원 이송을 원하시는 분들은 아니시고 현장 이송으로 같이 원하시는 거죠? 알겠습니다. 예. 고생 보냈습니다. 네.
 네. 수고. 네. 수고. 네. 수고. 네. 수고. 네. 수고. 네. 수고. 네. 수고. 네. 수고. 네. 수고. 네. 수고. 네. 수고. 네. 수고. 네. 수고. 네. 수고. 네. 수고. 네. 수고. 네. 수고. 네. 수고. 네. 수고. 네. 수고. 네. 수고. 네. 수고. 네. 수고. 네. 수고. 네. 수고. 네. 수고. 네. 수고. 네. 수고. 네. 수고. 네. 수고. 네. 수고. 네. 수고. 네. 수고. 네. 수고. 네. 수고. 네. 수고. 네. 수고. 네. 수고. 네. 수고. 네. 수고. 네. 수고. 네. 수고. 네. 수고. 네. 수고. 네. 수고. 네. 수고. 네. 수고. 네. 수고. 네. 수고. 네. 수고. 네. 수고. 네. 수고. 네. 수고. 네. 수고. 네. 수고. 네. 수고. 네. 수고. 네. 수고. 네. 수고. 네. 수고. 네. 수고. 네. 수고. 네. 수고. 네. 수고. 네. 수고. 네. 수고. 네. 수고. 네. 수고. 네. 수고. 네. 수고. 네. 수고. 네. 수고. 네. 수고. 네. 수고. 네. 수고. 네. 수고. 네. 수고. 네. 수고. 네. 수고. 네. 수고. 네. 수고. 네. 수고. 네. 수고. 네. 수고. 네. 수고. 네. 수고. 네. 수고. 네. 수고. 네. 수고 네 갑니다
 119입니다. 어 네 여기 저기 어디지? 고속터미널 맞은편 6교에 있는 6교 다리 밑인데요. 네 그렇게 말하면 저희가 알기가 어려우니까 고속터미널에서 그 6교가 어느 방향치에요? 거기 근처에 주소 아세요? 아 고속터미널 그 지하철역 1000번 출구 앞에 있는 6교거든요. 3번 출구요? 네네네. 고속터미널 3호선 3번 출구? 네네네. 아 7호선이구나 그쪽이. 네 7호선 3호선 다 다니니까 어쨌든 3번 출구 7호선일 거예요 아마. 네 7호선 3번 출구 그 옆에 스타벅스 있고 그런 데 쪽 말하는 거죠? 네 맞아요 맞아요 맞아요. 네 그쪽 아래 6교 쪽에. 거기 이쪽. 다리 밑인데 여기 남성 1분이 쓰러져 계시는데요. 네 그 한번. 정념도 좀 하시는 것 같고. 정녀하세요? 네 의식은 있으신데. 네. 의식은 있고 호흡도 있고 그분이 막 힘을 떨고 있어요? 바로바를? 네네 몸을 떨고 계시고요. 지금 약간 배설물도 나오시는 것 같거든요. 네 그래요? 선생님 그쪽 근처로에 한번 각 보시고 저희가 의료 지도도 해드릴 거니까 전화는 끊지 말고요. 잠시만요. 네 네. 지금 구급차는 나왔어요. 저희가 부탁드릴 거니까 잠시만 기다릴게요.
 네. 119 상황실입니다. 네. 서울 쪽에 국립대청입니다. 말씀하세요. 네. 여기 서울 쪽에 서울시 인천구 응남동에 구급차 1개 보내주실 수 있을까요? 주소 아세요? 네네. 응남동 몇 번지인가요? 응남동 그 위생 원더시트로 검색하면 나오는데요. 잠시만요. 미사 원더시티요? 리산 원더시티 리산? 네 응암동 리산 원더시티요? 위요 위 위산 위산? 네 응암동 예 오피스텔 몇으로 가면 되나요? 제가 예 예 현관 비밀번호가요 . 여자친구분 연락 달려주세요. 예. 잠시만요. 네. 네. 네. 네. 2가 3개인거죠 선생님? 네 맞아요 음 예 알겠습니다 고고차 소통하겠습니다 네 예
 1 2 2 3요? 아 지금 고속도로를 가다가. 예. 이게 공항 같은 게 아닌지. 진짜 숨이 안 쉬어지고 이래서. 본인께서요? 네. 호흡골 있으시고요? 공항 뭐 발전 경기 있으세요? 네 원래 약을 먹었어요. 공항장에 있으시고요? 고속도로 어디 고속도로예요? 네 고속도로 지금 서울 톨게이트 나와서 지금 잠표 반포 그쪽 넘어가는 데거든요. 서초 그쪽이거든요. 서초 그쪽이에요. 지금 서 있다고요? 네 갑길에 지금 잠깐 휘어놨어요. 잠시만요. 서울 톨게이트고 지났고. 서울 쪽이에요? 아니면 그 반대쪽이에요? 서울 가는 쪽이에요. 서울 방향이고. 혹시 양자이신 지났어요? 여보세요? 양자이신 지났어요. 서초아이시까지 1.7kg 넘었거든요. 아 서초아이시 전 1.7kg요? 양자이신 지나서 서초아이시 1.7kg 전이고 숨호흡을 천천히 한번 해보시고요. 지금 차 아 어떤 차예요? SUV요. SUV 차종하고 색깔하고 번호 좀 알려주세요. 지프 검은 색깔 잠시만요 지프 검은색 네 받드리고요. 알겠습니다. 차 그쪽으로 보낼 테니까 잠시만 기다려주세요. 네.
 네. 제가 아까 10초 정도 부서에 왔었는데. 어 네. 지금 수면서를 너무 많이 먹어가지고. 예. 누가요? 제가요. 고기처럼 보내드릴게요. 주소가 어떻게 돼요? 용산동 2가. 예. 2가. 네. 예. 얼마나 먹었어요? 몇 알이나? 어 1통 먹었어요. 그 코로나 상황이나 확인 관련된 건 없죠? 네. 네. 그것은 인근해서 알 거예요. 주말 인근해 주세요. 그 현관은 열어놓고 계세요. 그만 알 거예요.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 아 예. 아 네 안녕하세요. 여기 위치로 앰뷸러스 하나 불러주세요. 지금 몸이 안 움직이다 그래가지고. 누가요? 지금 여자친구가 같이 있는데 여자친구가 지금 머리를 떼었는데 몸이 안 움직이다 그래가지고요. 아 예 주소가 어떻게 돼요? 그 천주 천중로 천중로 몇 층이에요? 1층으로 가면 되나요? 네. 보호차 가니까 전화오면 잘 받아요. 네. 감사합니다.
 네, 여기 모래내 지하차도 앞인데요. 네. 그 사천교 가는 그 삼거리에서 오토바이 길이 부딪쳤거든요. 잠깐만요. 사천교로 가면 돼요? 그럼? 아니요. 사천교 말고 모래내 지하차도라고 써 있는데 중동 초등학교 좌회전하고 중동 중앙 중교 직진하면 되는데. 혹시 보이는 가게 간판 같은 거 하나 있을까요? 가게 없고요. 여기. 어 선생님 모래내 지하차도 밑으로 가면 돼요? 모래내 지하차도 네네네 거기 삼거리요. 모래내 지하차도 삼거리요? 네네. 사천교랑 가는 삼거리 쪽 말씀하시는 건가요? 사천교로 올라가시면 안 되고 그 상암동 가는 쪽으로 일단은 직진하는데 일단 2분 못 일어나시다가 2분 일어나셨거든요. 지금? 오토바이랑 오토바이 유통사고예요? 네네. 네. 출동하고요. 환자는 몇 명이에요? 2분이요. 근데 뭐 오토바이 깔려 있거나 그런 건 아니시죠? 지금 이제 일어나가지고 두 분이 또 오토바이 세우시네요. 알겠습니다. 출동하겠습니다. 네. 네.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 여보세요? 예. 네 여기 1구 3이신데요. 아 저는요. 네? 아까 신고한 사람인데 저는 지금 집에 가려고 버스를 탔거든요. 아 그러니깐요. 그 환자분이 그 버스 정류장에 계셨어요? 네. 아 이대역 방향으로 있는 버스 버스 가신 거죠? 네 막 몸을 못 가놓으셔가지고 떨어지셔서 남자분이 여자분이세요? 네? 남자분이었어요? 여자분이었어요? 아 남자분이에요. 아 의식은 있으셨죠? 의식은 있으신데 아마 중증이 있으신 분인 것 같아요. 살짝요. 근데 날씨가 추운데다가 버스를 잘못 타셔가지고 이제 그냥 막 말을 안 들으셨나 봐요. 네 알겠습니다. 수고하십시오.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네 안녕하세요. 지금 어 신랑이 손이랑 눈썹이 삐져져가지고 피가 너무 많이 나가지고요. 네. 선생님 일단 그쪽으로 고수사는 보냈어요 환자분 의식은 있구요? 어 있어요. 감기 증상이 있거나 코로나 확진자는 아니구요? 네 그런건 아니고 그냥 좀 찢어졌어요 손이랑. 깨끗한 수건. 깨끗한 수건으로 지혈하고 계세요? 네 지혈하고 있어요. 물티슈는 좀 감염 우려 있으니까 깨끗한 수건으로 지혈하고 계세요? 아 수건으로요? 네 알겠습니다. 네.
 네 여보세요? 네 안녕하세요. 서울 119 상황실이에요. 예 마포구 서교동 고기꾼 김춘배 홍대 본점 앞으로 가면 되나요? 어 지금 경찰 분들 오셨는데 또 오세요? 아 아 아 경찰 분들이 저희한테 또 상태받아달라고 요청을 해가지고요. 아 예예 여기 맞아요. 남자분 여자분 1명씩이요? 2명씩이에요. 남자들은 남자들은 의식은 있거든요. 남자는 의식이 있고 예 근데 여자 2분이 쓰러져서 지금 잠들었어요. 남자 2명은 의식 있고 여자 2명은 잠들어 있고요. 2명 다 숨은 쉬신다는 말씀이네요. 숨은 쉬는 것 같아요. 아 또 피를 흘린 거 다 그랬다. 아 구토인 적도 있고요? 예 구토를 하고 음 피를 흘리진 거가 보이지는 않은 거죠? 예, 피까지는 안 보였고요. 아 네, 알겠습니다. 저희 내면대로 한번 나가 볼게요. 선생님 고생하셨습니다. 몇 분 정도 걸릴까요? 아 잠시만요. 예. 아 근처에 차가 없어서 소대문구 연희동 쪽에서 나가서 한 5km 정도 떨어져 있거든요. 시간이 조금 걸릴 것 같아요. 10분 15분 걸리겠네 그럼? 예, 15분 한 20분 정도? 아니 만약에 그 경찰 분들께 좀 말씀을 전해 주실 수 있을까요? 저희 좀 오래 걸릴 것 같다고? 예, 예. 아 선생님 감사합니다. 예.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네, 여보세요? 예. 저기 화장실에서 넘어지셔가지고 우리 아저씨가. 네, 어디 다쳤어요? 다친 게 아니라 머리로 머리로 길 떨어지면서 저기 다른 게 다른 게 깨지긴 했는데 머리가 좀 뻘겋게 하고 생각이 안 난다고 그러셔서. 네, 주소 불러주세요. 서울 강서로 팔길. 강서로 팔길에. 네. 네. 가족분 중에 코로나 관련 지역 다녀오거나 관련 증상이 있나요? 아니요. 없어요. 네. 가볼게요. 전화 오면 잘 받으세요. 네.
 16입니다. 네 저 71세 여성이고요. 71세요? 어머니예요? 네 네 네 맞고요. 어제 어제 11시경 백신 3차 접종 후에 지금 9도 정도까지 열이 올라서요. 아 지금 발열이 심해요? 네. 네. 의식. 네 괜찮아요. 아 의식은 있어요? 네. 예 그 열만 나는 거예요? 네 고요이요. 39도까지 올랐어요. 방금 전화했어요. 아 주소가 어떻게 되세요? 여보세요? 여기 아트자이 아파트. 아트자이 아파트. 네. 예 알겠습니다. 전화 잘 받으세요. 오시나요? 전화하고? 아 예 전화하고 갈까요? 혹시 거동 가능하세요? 지금요? 5화 때문에 아까 걸을 수 있겠지? 살짝 걸을 수 있을 것 같아요. 그러면 전화받으면 1층으로 내려올 수 있겠어요? 네네. 그렇게 해볼게요. 아 네 그러면 전화 잘 받아주세요. 네 이 번호로 연락드린 거죠? 예예 그 번호로 전화할까요? 네.
 네, 119입니다. 여보세요? 예, 말씀하세요. 아 저 예, 저희 어머니가 지금 좀 좀 상태가 안 좋으셔가지고. 아 고거서 들어간 거예요? 예, 예, 예. 주소요? 주소? 그 은평구 불광동. 코스는 따로 없고요? 예, 예. 차 차는 출발시켰고요. 죄송하지만 어머니 의식이 없는 거예요? 아니 지금 뭐 중고 갔다고 돼서 그래가지고. 배가 아프신 거예요? 아니 지금 어디 아프신지도 지금 말씀을 못 하셔요. 지금 거의 뭐. 거. 지금 해가지고 항암 치료 중이신데. 아 지금 열은 안 나세요? 열은 그냥 만져봐도 열은 없으신 것 같은데. 네 알겠습니다. 예.
 네 119입니다. 네 어제 그 3차대 집 맞고요. 지금 오한이 들고 춥다고 그러고 이게 그것 때문인지 아니면 뭘 잘못 먹어서 그런 건지 잘 모르겠는데 가까운 근처로 좀 옮겼으면 하거든요. 가까운 근처로 옮긴다는 게 무슨 말이세요? 선생님? 아 병원으로 좀 갔으면 해서요. 응급실 들려보시려고 하시는데 지금 거동이 안 되시는 거예요? 거동이 뭐 이렇게 오함 들려가지고 이렇게 있으니까. 아 예 선생님 주소 좀 알려주세요. 어 광진구 자양로. 그 광진구 자양로. 그 건물 건물이고요. 자양물 예예 거기 그 현대 홈시티라는 건물인데 아 현대 홈시티에 거기에 그 환자분 남자분이 여자분이에요? 여자요. 여자분이시고 어제 3차 백신 뭐 맞으셨어요? 화이자 화이자 3차 접종하신거고 오한이랑 그 이렇게 뭐 쉽다고 그래요. 출근 증상 보급실 거부실 하시는 거고 지금 거동이 힘드신 상태라는 거죠? 예 몸살 증상이 있고. 알겠습니다. 그쪽으로 구급차 지금 보냈고요. 환자는 뭐 발열이나 코로나 관련 사항이 있으세요? 발열은 없어요. 정상이에요. 추원은. 아 예 알겠습니다. 그쪽으로 가볼게요. 네네. 네.
 네. 여기는 여기 오경실 내과라고 신장실인데요. 저희 환자분이 지금 몇 박에 너무 떨어져가지고 고대 구로병원으로 이송해야 될 것 같아요. 오경실 내과 주소가 어떻게 돼요? 어 잠시만요. 가마산로 27길 잠시만요. 21길에 27길 가마산로 27길 1번 남자분 여자분이에요? 여자분이에요. 지금 의식은 있고요? 의식은 있는데 몇 바게 너무 떨어져요. 30번 이렇게 밖에 안돼요. 30개요? 네 30 몇 개 이렇게 밖에 안돼. 네 여기는 저희가 구급차도 없고 해가지고. 아 예 저희 구급차 수동하고요. 잠시만요. 아 여기 저희 의료진 연결하려고 그러는데 지금 다 통화 중이네요. 여기 구로에서 가니까요. 금방 알 거예요. 네 알겠습니다.
 입니다. 무슨 일이세요? 아 그 입장이 너무 아파서 그러는데요. 아 네 그 구급차 필요하세요? 선생님? 네네. 현장 본인이 아프신 건가요? 네. 저 지금 거동이 힘든 상태세요? 선생님? 아 거동은 되는데 입장이 너무 아파가지고. 네 선생님 그 구급차 보내드릴게요. 위치 좀 알려주세요. 여 강서구 공항동이요? 네. 맞으세요 선생님 몇 층 몇 톤가요 지층이요 지층 몇 호에요 공항번호 맞으시죠 선생님 예예 지층 몇 호세요 1호 2호 없으세요 그냥 한층인가요 예예 알겠습니다 그쪽으로 탁 탁 갈 거고요 선생님 혹시 선생님 코로나 관련해서 뭐 열이 나거나 어 큰일 없어요. 학생과 접촉하거나 그러신 거 있으세요? 없어요. 아 그쪽 지금 출발했고요. 저희 축복하는 대원이 전화할 거예요. 전화 잘 받아주세요. 네.
 누릅니다. 여보세요? 여보세요? 맞으세요? 예예. 예 우리 애가 많이 아파요. 남자 여자예요? 남자예요. 어디 몇 살이에요? 몇 살? 어 33살. 33살 30살 어디가 아파요? 아니 어제 취했다는데 경신을 못 차리네요. 여기 예. 여기 저기 저기 여기 여기요. 여기요. 강남 터미널이요. 강남 터미널이라고요? 예예. 여수. 예, 여수에서 이제 도착했는데 애가 어지러워서 정신. 애가 어지러워서 정신을 못 차려요. 아 그래요? 지금 여수 트레일러에 지금 도착한 거예요? 네, 네, 네. 지금 11시 40분에 도착 35분에 도착했어요. 아 여 그럼 강남 그 호남고속한 날이에요? 호남고속한 날? 네, 네, 네. 예, 예, 예. 몇 층에 계세요? 몇 층에 계세요? 아니 지금 하차 1대 있어요. 고속버스 하차 하차 1대 바로 있어요. 고속버스 하차 1대 바로 있어요. 예, 예, 예. 아 알겠습니다. 코로나19에서 연락 기침 오는 거 없어요? 10기침 없어요? 없어요. 알겠습니다. 주무관님 전화 잘 받으세요. 옆에 뭐가 보여요? 옆에 가게 같은 거 뭐가 보여요? 여기 아니 가게요? 상점 가게 뒷밥지라든가 뭐 여기 11번이요. 11번. 11번? 예 여기서 내리는데 11번. 아 내리던 곳 11번이에요? 네 알겠습니다. 거기 계세요. 바로 가볼게요. 예예. 예 바로 오는데 너
 예 여기 반도 2차. 예 예 예. 예 무슨 일이세요? 아기가 아기가 내장증인데 지금 경년이 왔어요. 아직 몇 살이에요? 지금 6살 됐어. 7살 돼요. 6살. 지금 호흡은 하고 있죠? 네? 수고하시고 있죠? 네, 네, 네. 수정할 거고요. 저희 가는 동안 그 간호사하고 의료진으로 연결할 거예요. 전화 끊지 마세요. 잠시만요. 네, 네. 가족분들 코로나 자가 경위나 학생 가야 되는 건 없죠? 없어요. 잠시만요. 전화 끊지 마세요. 예, 호흡하고 있지.
 여기. 아 네 여기 그 사람이 쓰러져가지고 지금 피 흘려 오셔가지고 전화 주셨거든요. 위치가 지금. 네네. 남자분이요? 여자분이요? 아 남자분이시고. 예 피로 그걸리고 있어요. 그 얼굴 쪽에 부딪히 얼굴 쪽에 피 나시고 계시고. 계시는 거 보이지만 알았고요. 네 한 50대 남자분이시고 위치가 지금 3456길이에요. 3456길이. 몇이에요? 건물 번호는 네. 건물 번호가 잠시만요. 여기가 3456 아 다시 말씀드릴게요. 구찬멜로 12길. 10천멸. 네 12길. 그 앞이시고요. 네네네. 혹시 경찰관이세요? 아니요. 그냥 네네네. 그럼 의식 상태 호흡 상태는 괜찮으신 거예요? 네. 의식은 있으신데 몸은 이렇게 잘 일어나지 못하시는 것 같아요. 혹시 술 취하신 상태예요? 술 약 약수하셨어요? 네. 아 네. 하자 네. 하신 걸로 보입니다. 그쪽으로 설정해서 보내드렸고요. 그러면서 전화드릴 수 있으니까 전화 좀 전화 받아주세요. 네. 알겠습니다. 예.
 수고하십니다. 저기 저 잠깐만 좀 오세요. 뭐. 무슨 일이에요? 저 성북구 덜거지. 성북구. 성북구. 덜거지 산수지. 거기 몇 층이에요? 단독에 어린이집이죠? 단독이요? 어린이집 좀 빠질 게 없어요. 아 거기 무슨 일이에요? 아니 죽으려고 그랬고. 누가? 아들 아들 아들이 아프대요? 빨리 어디서 아 빨리 갈건데 어디 아프대요? 아이 몰라 이거 일하려 아 좋다고 어디서 빨리 저거 밥 밥 먹고 다녀오겠소 숨을 쉬어요? 숨을 쉬어 알겠어요 빨리 가볼게요
 아 네 저기 포즈를 깨고 계시는데요. 아파갖고 식사랑 약을 못 드리고 있거든요. 아 그래요? 병원 응급실에 가야 되는데. 주소 좀 알려주실래요? 세창로? 네 세창로 도원 삼성 네 세창로 아이요. 예. 도원 삼성 네미안 아파트. 네미안 아파트. 네. 환자분이 남성분이세요 여성분이세요? 남성분이요. 배송은 못하세요. 그래요? 예 알겠습니다. 코로나 뭐 자가격리나 확진자분 계신거 아니시죠 집에? 네. 그런 사람은 없어요. 예 알겠습니다. 네. 9자 보낼게요. 네.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 예 알겠습니다. 사람이 술 잘 지금 술 먹고 지금 숨 쉬는 거 힘들어하면 어떻게 해야 되죠? 어 같이 계세요? 네 옆에 있는데 주소가 어떻게 되세요? 서울시 중랑구 면목동 면목동 면칙 몇 호세요? 안쪽입니다. 한쪽 집이요? 네네 남자분이세요? 아니요 여자요 여자분이시고 의식은 있으시죠 지금? 네? 의식은 있으시죠 지금? 정신은 있으시죠? 네 정신은 있는데 갑자기 막 숨쉬기 막 낑낑거려가지고 알겠습니다. 고급자 보내드릴게요 코로나 증상 같은건 없으셨죠 평소에? 그전에 코로나 감염됐다가 지금 자가격리하고 끝났는데 끝났는데 알겠습니다 전화가면 전화받아주시고 예
 119입니다. 네 안녕하세요. 애기가 지금 알러지가 더르면서. 네. 요리가 나는데 지금 심하거든요. 네. 예. 그래 119로 좀 불러 불러가지고 좀 가려고요. 일단 주소 좀 불러주세요. 양천구 목동로 3개. 선생님 여기 지금 혹시 이래목동병원 아닌가요? 맞아요. 이래목동병원. 이래목동병원에 지금 애기가 있어요? 아니에요. 지금 어제 밤에 급하게 그 일부 불러서 갔는데 괜찮다 해서 보냈는데 지금 집에 와서 더 심해졌거든요. 어 병원에 갔는데 괜찮다 그래서 지금 편했는데 지금 그러신다는 거예요? 예. 어 병원에 가서 그래서 엉덩이 주사만 맞고 약을 처방해 가지고 왔는데 지금 집에 와서 더 하거든요. 심하거든요. 어 지금 피부 뭐 피부 발진도 있어요? 아니 그럼 예. 알러지가 지금 심하게 돋았거든요. 어 열도 나고요? 네 열도 나요. 열 몇 도예요? 열이가 지금 잠깐만요. 아 잠깐만. 네. 전화 여보세요. 네 여보세요. 네 잠깐만요. 네. 38도 2. 48도 2요? 네 1. 예 알겠습니다. 선생님 제가 구급차는 또 취소했고요. 혹시 가족분들 코로나 관련해서 기침 발열이나 확진자 사항 있는지 이런 것들 있나요? 아 그런 건 없거든요. 예 알겠습니다. 제가 고객센터에서 통화했으니까 모르는 번호 전화하면 전화 잘 받으세요. 네.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네. 119입니다. 네. 지금 시대 시어머니가 지금 시아버지가 아프셔 가지고요. 119를 좀 불러오려고요. 남 그 시아버님께서 어디가 아프신 거예요? 모르겠어요. 어머니가 지금 전화 올면서 오셨는데. 예예. 그 어디 계세요? 시아버님 주소 전화해 주세요. 개봉동인데요. 개봉 15길? 개봉로 15길에. 개봉로 15길. 몇 층 몇 호에요? 브라운빌? 브라운빌 잠시만요 선생님 네 네 브라운빌 그 지금 무슨 증상 무슨 상황인지 모르신다는 거죠? 네 어머니가 지금 좀 원래 건강검진을 며칠 전에 받으셨는지라 몸이 안좋다고 하셨는데 지금 우시면서 전화와서 저러심만 아 예 선생님 그러면 일단은 그 어머님 전화번호 알려주세요. 어머님 번호가 몇인가요? 예 알겠습니다. 그 저희가 어머님한테 전화해볼 테니까 그 걸지 말고 계세요. 전화. 네. 네. 네.
 네, 119입니다. 아 예, 아 집에 학생이 아파서 그러는데 약을 먹었는데 그 약이 뭐가 잘못해 먹었거든요. 학생이 몇 살이죠? 아 22살이요. 22살 남자분. 여자예요. 여자예요. 따님이에요? 예예. 네, 차 구호차 먼저 출발시킬게요. 주소 먼저 불러주세요. 레미안 신반포 펠스. 레미안 신반포. 예. 예예. 예 차는 출발 시켰고요. 지금 어디 가서 무슨 약을 먹은 거예요? 아 예예 몸 약자 몸살기가 있어서 어떤 병원에서 제조한 약을 먹었는데 그 약을 먹었는데 갑자기 너무 통증이 심해서 병원에 얘기했더니 운동실에 가보라 그러거든요. 아 그래요. 지금 혹시 열나세요? 아까 아 그 코로나 검사 다 끝났어요. 했어요. 오늘 운동 나왔어요. 지금 지금 열이 있어요? 없어요? 지금 주소는 해볼게요. 지금 없어요. 네 알겠습니다. 차 나오고 있어요.
 네. 고객차 하나 보내줄게요. 예예. 고객차 보내드릴게요. 주소가 어떻게 됩니까? 잠시만요. 1번 말씀해 드릴게요. 예. 성북구 안암동인가요? 보물로요. 예? 보물로? 잠시만요. 보물로. 보물로? 네. 보문 엘타워요. 보문노. 예예예. 잠시만요. 네. 보문 엘타워. 보문노. 보문노가 있고 보문노가 있거든요. 그냥 보문노죠? 예. 그럼 보문 엘타워 맞아요? 보문 엘 타워. 맞아요? 네. 네. 몇 층이에요? 몇 호에요? 어 저희가 내려가 내려갈게요. 보문 엘 타워 밑으로 내려오신다고요? 예. 누가 아파요? 전화 한번 부탁드릴게요. 예? 도착하면은 전화 한번 부탁드릴게요. 아 가면서 전화드릴 거예요. 선생님 누가 아파요? 고급자 보내드릴게요. 누가 아파요? 누가 누가 아파요? 친구 1명이 좀 쓰러졌는데. 남자예요? 남자. 예. 예. 예. 갑자기 넘어졌다고요? 예. 예. 의식 상태는 어때요? 수업하고. 어 귀가 귀가 좀 아파 그러거든요. 귀가 아프다고요? 귀? 귀 통증이 있고. 어 코로나. 예. 예. 코로나 증상처럼 머리. 제 이야기 좀 들어주세요. 코로나가 없어요. 예예. 코로나 증상처럼 무리 1라는 거 없죠? 네, 예. 네, 고쳐 갈게요. 네. 어. 이게 이게.
 네, 1 9입니다. 여보세요? 네, 1 9입니다. 아, 뭐야 우리 아저씨가 밥을 일주일이나 안 먹었어요. 그래서 병원에 입원시키려고 그러거든요. 아, 선생님 죄송하시면서 입원하실 때는 1 2 9가 나갈 수가 없어요. 예, 예, 예, 응급실 가시는 경우에 응급실로 보시는 경우에 가능하시고요. 예, 그래서 응급실에 가야지 오늘 불편일이고 일요일이고 아니 아니 폐업일이고 해서 응급실은 없을 건데요. 예, 그니까 지금 응급실 가신다는 말씀이시죠? 예, 근데 여기 여기 여기 정보는 거 있는데 그 정립 의뢰원인가요? 네. 거기서 가고 싶은데가 가능할까요? 아, 그거 이제 고급대가 선정을 하는 거라 이제 고급대한테 제가 얘기는 할게요. 네 네 그쪽으로 가능하신지는 제가 말씀 못 드리고 국립의료원이요? 예. 어디 있는 국립의료원이요? 예 정병원 정병원 쪽에 가봐 있지 않아요? 음. 여기 신방동에서 얼마 안 가지고요. 응급실에 있는 병원은 유송 가능하신데 그 응급실 상황이 그때그때 변해서 가능하실 때는 고급자 확인하고 갈 거고요. 동립운용 이제 전달은 할게요. 주소 좀 알려주세요. 일단 주소 주소 알려주세요. 여기 3개월 47길? 네. 47길에 몇 층 몇 호예요? 네 네 단지요? 번지? 네 네 한옥동이요 서울동 맞아요? 네 세교록 87회 네 몇 층 몇 호요? 네 네 네 구급자한테 전달할테니까 한번 통화해보세요 네 감사합니다.
 네. 일렉입니다. 네. 수고하십니다. 지금 와이프가 좀 너무 고통스러워 해갖고. 예. 어떤 게 어떤 도움이 필요하세요? 구급차 필요하세요? 예예예. 주소 알려주세요. 청담동 10번지 삼한 아파트. 잠시만요. 청담동 그 삼한 아파트. 네. 아내분 어피 아프시대요? 몇십원전에 그 해초밥을 먹었는데 그게 잘못됐는지 고통하고 막 난리가 났어요 지금 거의 탈진해가지고 쓰러져있어요 예 신고자분 지금 차 출발했구요 예예 예 의식이랑 호흡 있으시구요 의식은 있구요 그냥 누워서 꿈짝도 못하구요 네 알겠어요. 지금 코로나 특진된 분 없으시죠? 지금 가고 있어요. 2.9km 남았습니다.
 괜찮아요? 예? 아 예. 사람이 처리했는데 좀 빨리 와주실래요? 예. 주소 말씀해주세요. 아 여기 리빙텔인데요. 예. 해기로 저 여기가 해기로 예. 그래서 저 리빙텔이라고 모른미 인텔 예 몇 번에 계세요? 예 남자분 여자분이요? 아 알겠습니다. 그 부터 보내드릴게요.
 아 네 여기 네 홍대 젤라 띠 젤라 띠 홍대 본점인데요. 네 그 소주병으로 맞은 분이 있어가지고 빨리 와주셔야 될 것 같거든요. 거기 몇 층에 있어요? 1층에 있어요? 여기 1층인데 그 젤라 띠 젤라 띠 홍대 본점 바로 옆이거든요. 집하 그려져 있고. 선생님 일단은 공부서 나갔고요. 그 남자분이 여자분이에요. 환자분이. 남자다 어 어 어 남자 의식은 있어요? 네, 의식은 정신 있어요? 네, 정신은 있어요. 아 일단 일단 경찰이랑 119랑 같이 갈 테니까 그분 어디 가지 말고 거 계시라고 하시고요. 머리에 피 많이 나요? 어 어 피 많이 나요? 어 많이 나요 많이 알겠습니다. 지원할 수 있으면 지원할 수 있고 지원 좀 해달라고 얘기 좀 해주세요. 아 네 그

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네. 119입니다. 아 예 안녕하세요. 송파경찰서 방위지구대 경찰관인데요. 네네. 아 저희가 지금 친구 나왔는데 지금 완전 만치자가 지금 일일이 없어가지고. 제가 한번 실성을 좀 주려고요. 아 그래요? 주소가 어떻게 되시나요? 주소가 잠시만요. 네. 송파구 5금으로 11길에. 네. 예예. 어 남자분이 여자분이에요? 여성분인데요. 지금 완치해서 필요 없어요. 아 예 알겠습니다. 선생님.
 네. 옵니다. 아 네. NCB 사정 강서정 킹스 안내대스크인데요. 저희 고객님 1분이 지금 토하시고 지금 이렇게 기력이 좀 쉐어하셔 갖고 움직이질 못하시고 계세요. 그래서. 의식은 있으신 거죠? 예. 의식은 있으세요. 이렇게 앉아있으. 네. 킹스요. 안내데스크 앞쪽에 입구 쪽에 앉아계시거든요? 아 네 1번 바로 보내고 고급대원 보내고요. 혹시 연락을 하거나 뭐 이런 코로나 격리자인지 이런 건 아니시죠? 어 코로나 코로나 그런 건 아니신 거 같은데 제가 모르겠어요. 고급대원 보내서 아 확인하겠습니다. 네. 아 코로나는 아니시래요. 저기 이렇게 토는 하셨어요. 토는 하셨어요. 고급대원 보냈거든요. 전화 드릴 수 있어요. 고급대원이 전화 오면 잘 받아주세요. 네.
 네, 이른바입니다. 네, 안녕하세요. 네. 여기 저 저 저 저 오류동 동부 골든 아파트. 몇 호세요? 네. 병원에 좀 우리 아저씨 모시고 갈라니까. 아우 내 혼자 어여 보지를 못하겠네. 어디가 아프신 거예요? 아니 그 주사 맞고 저 3차 주사 맞고는 감기 거치로 그리 아프더니 정신줄을 딱 놓은 거 같아요. 말을 안 들어요. 사람이. 의식은 있어요? 예? 의식은 있고? 의식은 있는데 막 막 저 헛소리 자꾸 하면서 내가 어떻게 하다 뭐 죽어도 막 주먹 휘두르면 말을 안 들어. 혼자서 지금 오직 피다 이 피다 못해가. 좀 와서 병원에 좀 이송해 주시면 좋겠는데. 선생님 아파트 이름이 동부 골든 아파트 맞아요? 예 오류동 동부 골든 아파트. 아 예 알겠습니다 선생님. 구비자 보내드릴 거고 혹시 코로나 관련해서 열이나 기침, 호흡 곤란 같은 건 없어요? 열은 안 나고 기침도 많이 안 하고 그런데 음식을 통 입맛이 떨어져서 음식을 못 드시고 변도 일주일 동안 변도 못 봤어요. 아 그래요? 예 알겠습니다 선생님. 구비자 보냈어요. 예 예. 예예
 네 여보세요. 지금 저기 여기 은평 유타운 10단지인데요. 몇 등 몇 호예요? 무슨 일이세요? 남편이 갑자기 숨을 안 쉬어요. 의식호흡도 없어요? 아 지금 지금 숨이 막히는 것 같아요. 어떡하죠? 차량 보냈고요. 제가 의료진 연결할게요. 전화 끊지 마세요. 네네. 아 어떻게 해. 아. 여보세요? 예. 의료진 국산에 가고 있.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네. 여보세요? 예. 저희 지금 119인데요. 네. 저희 119 지금 나가고 있어요. 신사 1번 출고 머리 머리 보상으로 신청 신고하신 거 아니죠? 네. 다리가 밝히 깔렸어요. 예. 지금 다리 보상했어요? 아 네. 지금 너무 아파요. 예. 알겠습니다. 지금 나가볼게요. 네. 1번 출구여 신사역 1번 출구. 네. 예 알겠습니다. 아 네.
 네 안녕하세요. 지금 어머님이 조금 의식이 없으시다고요? 네 주소 알려주세요. 저희 고 부처 빨리 가겠습니다. 네 지금 여기가 불광동 못 알아보시나요? 네. 네. 숨 쉬는 게 코로 숨 쉬는지 입으로 숨 쉬는지 귀에 한번 대서 들어보시겠어요? 지금 입으로 숨 쉬죠. 입으로 숨 쉬거든요. 입으로는 숨이 잘 나와요? 느리거나 너무 헐떡거리거나 그러진 않아요? 지금 숨이 좀 이렇게 거칠다고 해야 되나? 음. 지금 연락을 하는 코로나 관련해서 그 가족분들 전부 다 포함해서 연락을 하는 코로나는 있으신 분은 없으시죠? 네 지금 열이 조금 내리긴 했는데. 열이 났었어요? 어머님이? 예. 아 그래요? 잠깐만요. 저희 의료팀 연결할게요. 전화 끊지 마세요. 차는 나오고 있습니다. 네.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네, 아기가 뭐 먹고 숨 못 새는 거 같은데 어떻게 해야 되죠? 아들이요? 딸이에요? 딸이요? 딸이 몇 살이에요? 몇 살 몇 살 몇 살? 8개월. 8개월 지금 뭐 목에 뭐 이물질이 걸린 거예요? 숨을 잘 못 새는 거 같아가지고. 예, 빨리 출동하고요. 주소 좀 알려주세요. 주소. 예. 주소요. 네, 글로리아 아 거기에 인수복로 55 각일. 인수복로 55 각일. 지금 아예 숨을 안 쉬고 있어요? 아 지금 잘 모르겠어요 지금 입어 오물거리는데 글로리아 캐슬 몇 동 몇 호에요? 빌라에요 빌라 출동하고요 저희 의료진 연결할게요 전화 끊지 말아주세요 예? 전화 구급차 출동하고요 의료진 연결할게요 전화 끊지 마시라고요 아 예 예 예 감사합니다.
 119입니다. 말씀하세요. 네 안녕하세요. 서울역 파출소 경찰관입니다. 네 네. 네 그 저희 여기가 서울역 파출소 여기 이제 지하도 있잖아요. 서울역 파출소 지하도요? 네 그 우체국 우체국 쪽에 지하도 있거든요. 거기 이제 노숙자분 한 분이 넘어지셔 가지고 눈을 크게 다 치셔서 네 지금 약간 칠회를 입고 붓고 하셨거든요. 그래 가지고 지금 네 7월 좀 빨리 가르셔야 될 것 같아 가지고요. 그 지하도 우체국 쪽으로 가면 될까요? 예 우체국 쪽으로 오면 제가 있으니까 예 바로 안내해 드릴게요. 노숙자 눈부상인가요? 예. 네 알겠습니다. 잠시만요. 저희가 좀 찾아서 보낼게요. 근데 그 경유주광선 아니죠? 선생님. 네 잘못 들었음 뭐라고요? 서울역 파트에서 지하도 우체국 쪽으로 보내면 되는 거죠? 그렇죠. 예예예예. 네 알겠습니다. 저희가 또 궁금하면 연락드릴게요. 네네네.
 네 1 9입니다. 말씀하세요. 네 여기. 네. 저기. 영나루 노타리. 영나루 노타리요? 네. 역천동이요. 네. 역천동 몇 번지세요? 몇 번지는 모르겠고. 네. 길에 지금 나왔길래 버스 정류장 있는데. 버스 정류장이요? 버스 정류장 뭐 번호 보여요? 아니면 버스 정류장 이름이나요? 네 1번 볼게요. 빨리 와야 되는데. 버스 정류장 번호나 아님 이름 알려주세요. 이 이 이 이 역마루. 역풍동. 역마루요? 네. 버스 정류장. 버스 정류장 보면은 번호가 있어요. 숫자 5자리 그거 불러주세요. 다른 분 안 계세요? 지나가던 행님분들? 아니 저기요. 저기요. 네 네 네 아이씨. 네 다른 분 좀 바꿔주세요. 네네네. 아 선생님 119 상황실인데요. 네네네. 네. 거기 위치가 어디가 어디일까요? 아 예. 여기가 저기 거 여기. 역말 4거리입니다. 선생님. 역말 4거리요? 네. 역말 4거리 버스 정류장입니다. 혹시 버스 정류장 번호나. 네. 잠시만. 역말 4거리. 어 역말 4거리 버스. 저 아이디 번호가. 네네. 1 2 다시 180번. 1 2 다시 180번. 네 1 2 다시 180 네네네. 네 잠시만요. 2번 출고. 2번 출고가 아니고. 아 예 이제 검색했습니다. 0 말 4월 1. 네 그 다 그분 다시 바꿔주시겠어요? 네네네. 네 없습니다. 여보세요? 네 어디가 아프신데요? 지금 나 좀 지금 나 넘어져요. 지금. 네? 지금 나 쓰러진다고. 쓰러진다고요? 응. 대원들 나가면서 전화드릴 거고요. 최근에 코로나 관련해서 뭐 접촉했다고 문자 받으신 거 있어요? 아이 그런 건 없어요. 네 대원들 전화할 수 있으니까 전화 잘 받고 안내해 주세요.
 네, 일요일 겁니다. 네, 안녕하세요. 저 지금 아 심장이 너무 아파가지고요. 아 심장이 아프시다고요? 네, 심장이 너무 아파요. 어디로? 네, 80% 돼요. 심장이 너무 아파요. 여보세요? 예, 예. 네, 빠져도 없는데 심장이 너무 아파요. 80% 너무 수업을 갔을 수 없고요. 파츠스요? 그럼 파츠스 이름이 어떻게 되세요? 파츠스 어딥니다. 시간이 너무한데 노일받치 있습니다. 노일받치예요. 알겠습니다. 예 시간이 너무 보여. 아 아
 119입니다. 여보세요. 말씀하세요. 아 제가 지금 배가 너무 아픈데요. 병원에 데려가실 수 있나요? 지금 병원에 응급실로 가야 된다는 거죠? 그 공급자로 응급실 갈 수 거죠? 거동이 안 돼서. 계신 곳 좀 알려주세요. 계신 곳 주소. 주소 알려주세요. 계신 곳. 네 잠깐만요. 후방터 이 다람쥐할 때 다길. 네. 후방터 이 다람쥐할 때 다길. 네. 본인 폭풍이 심해서 거동이 안되시는 거예요? 코로나 관련 열 기침 감정상 이런거 없으신거죠? 네. 문 열어주세요. 출동했어요. 네. 알겠습니다.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 16입니다. 아 여기 노량진 장성 사우난데요. 장성 사우나요? 예예예. 네. 아이고 탕에서 할아버지 쓰러지셔 가지고. 잠시만요. 선생님 그 계주물에서 한번 찾아볼게요. 저 탕 안에 계신 거예요? 아 지금 이제 밖으로 이제 뜨냈거든요. 아 나왔어요? 잠시만요. 잠시만요. 장성 사우나요? 예. 장성 맞아요? 선생님? 예예예. 직원은 아니시고요? 예? 직원은 아니시고요? 아니요. 손님이 손님이 지금. 아니 아니요. 지금 저는 아 장성 24시 그랜드 보석 사우나 여기 맞아요? 네. 장성사우나 남탕이시고. 네. 의식을 회복하신 거죠? 아니요. 의식은 지금 약간 있어요. 약간. 약간 의식이 좀 뻗어서요. 잠시만요. 열탕 안에서 그러신 거예요? 남탕이요. 예. 의식 저하되시고 호흡은 있으신데 제가 혹시 모르니까 지금 구급차 먼저 출발하고. 네. 제가 도와드리지로 안내해드릴게요. 이거 반응은 있으신가요? 아니요. 지금 말씀을 잘 못 하시고요. 말씀을 못 하세요. 길이 없어서 못 하시는 거예요? 네 한번 말 좀 시켜주세요. 정신은 약간 있는 것 같기는 해요. 이제. 그래요? 어. 네 지금 고급자 출발했고요. 어 거리가 조금 있어서. 잠시만요. 음 이제 의료주로 한번 연결해 드릴게요. 주먹 한번 접으실래요? 가능 있으세요? 다 알아들으세요?
 할렐루입니다. 여보세요? 네. 네 저기 딸이 그 갑자기 지금 많이 아파가지고 그러는데 여 걷지도 못하겠대요. 어디가 아프신데요? 네. 의식은 있어요? 예? 의식은 있어요? 예예. 계신 주소가 어떻게 돼요? 어. 범행로. 30 가게. 아 노회로 30 가게. 몇 번이지? 노회로 30 가게. 선생님 주소 다시 한번 불러보세요. 노회로 34길 여보세요? 주소 다시 한번 말씀해 보세요. 예 예 수요 2동 수요동 예 예 예 몇 층 몇 호예요? 단독이에요? 네네네 일단 그쪽 고객센터는 보냈고요. 환자분 감기 증상이 있구나 코로나 확진자는 아니에요? 맞죠? 네 고객센터 보냈습니다. 기다려주세요.
 감사합니다. 예 말씀하세요. 네 어디로 오세요? 선생님 지금? 예 지금 어디 계세요? 지금? 여기 중구 통일로. 중구 통일로에 예. 예. 위치 한번 확인해 볼게요. 네, 바비에 그리빙 네, 그 무비에 무비 앞에 어지럽고 지금 그러신 거예요? 네 열은 어떠세요? 지금 열 증상 같은 거는? 열 없어요 열 증상 이런 거 힘들어 네, 그쪽으로 가볼게요 네

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 예, 일곱 번호. 아 저. 여보세요? 제일 가스가 찬 것 같은데. 그럼요. 예. 지금 운구실에 가실 거예요? 혹시 손발이 저리고. 제일 가스가 찬 느낌이 드는데. 지금 혼자서 할 수 있는 게 있을까요? 하. 하. 근데 뭐 소화제 같은 거 드신 그런 거 드셨어요? 소화제나 뭐. 아, 수행정수 일단 먹었고 혼자 걸어보려고 했는데. 유상증 같은 거 좀 많이 드시면은 좀 좋을 수 있겠. 일단은 그럼 지금 병원에 가실 거예요? 아니면 의료 상담하실 거예요? 하. 응급실에 간다고 달라지는 게 있을까요? 아유 응급실에 대해서는 저기요. 의사들이 처방을 하죠. 얼마나 걸릴까요? 구급차요? 네. 1.7 투로 하니까 뭐 10분 내로 가요. 하하 하하 그러면 와주세요. 네 주소 불러주세요. 여기 관악구. 관악구. 2000원 342단지. 잠깐만요. 이편은 이편은 서울대 입구 이 이 단지 아파트요. 예. 네. 네 여성 그리고 목소녀 그리고 손발조림 그리고 코로나 관련해서 의심할만한거 있어요? 코로나? 없어요. 그런건 없구요. 빨리 바탕으로 들으신다. 네. 네.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네 119입니다. 아니 자가 격리자고요. 예예. 폐무 2개월째 아기가 있는데요. 예예. 지금 확진됐다고 오늘 아침에 연락을 받았는데. 예예. 거기서 연락이 좀 안 돼서요. 아이가 확진됐다고요? 확진 판정을 받은 거예요? 네네 근데 아이가 지금 열이 38.5도까지 올라가고요. 예예. 지금 몸이 좀 터져 있거든요. 의식은 있어요? 눈 뜨고 있어요? 네 지금 잠 잠은 드는데 제가 의식은 있는 것 같아요. 그 발열 증상이 있고 계속 처진다는 거죠? 네네. 1일밖에 안 됐어요. 잠깐만요. 2개월 남하에요? 여하에요? 남자아기요. 생후 2개월 남하고 자꾸 처지고 그 선생님 일단 저희가 가서 확인해 볼 건데 주소 좀 알려주시겠어요? 성동구 아차산로 9길? 아차산로 9길. 금강 아미움 맞아요? 맞아요. 금강 아미움. 예 일단 그쪽으로 저희 가볼 거고요. 그 지금 신고하신 분은 자가 격리자라는 거고 아이가 확인됐다는 거죠? 네. 아 잠시만요. 아이가 태어날 때. 예. 새 미성숙으로 중학년에 9일 입원했었거든요. 아 잠시만요. 일단 그쪽으로 9호차 빨리 가볼 거고요. 저희가 의료진 연결시켜드리기 통화 끊지 말고 계세요. 숨 쉬는 건 잘 쉬고 있어요? 아이가? 네 숨은 잘 쉬고 있어요. 예 알겠습니다. 빨리 가볼게요. 감사합니다.
 일로 봅니다. 네 뭐 1 여쭤볼게요. 지금 저기 폐암을 앓고 계시고 고대 안암병원에 다니고 계시는데 지금 상태가 너무 안 좋은데. 네 그리고 탈 수 있나요? 네 탈 수 있나요? 가까운 응급실 쪽으로 모셔다 드릴게요. 계신 곳 미치지 말 수 있어요? 예 여기가 오피산로 3길 아 동신아파트인거에요? 네네 예예 아버님이 아프신거에요? 네네 폐암 환자신가요? 네 지금 뭐 혹상태는 어때요? 숨쉬는거 이런거 호흡이 오늘 지금 눈을 거의 안 안 감고 깜빡깜빡을 안하시고 예예 숨은 원래 폐암이라서 좀 이렇게 통증이 말씀하세요? 말씀은 아예 못하세요? 아니요. 제가 볼 때 지금 오늘 상태가 안 좋은 것 같아요. 말씀을 거의 안 하세요. 고개만 까딱까딱 아직 의식은 있으세요. 의식은 있으시고요? 아 저희 차는 지금 처리가 되시고요. 그 병원 저희 고급대원들 출동 고급대원들이랑 상의를 하셔야 될 것 같고요. 용원을요? 고대병원으로 갈 수가 없나요? 거기 다니시는데요? 그 결정은 이제 고급대원이 할 수 있게 돼 있어서 저희가 병원에 대한 선정권이 없어요. 네, 대원 전화 드리면서 갈 거니까 그때 말씀 좀 해주시고요. 혹시 가족분들 중에 뭐 발열이나 고열 뭐 코로나 관련 중도 있으신 분 안 계시죠? 아, 없어요. 저희 다 3차 끝날 수 있어요. 알겠어요. 그 동신 아파트 하면 전화 드릴게요. 전화 좀 받아주세요. 예.
 네 세종이고요. 데이터 들어갔나요? 서울 심정지 구급 요청건입니다. 아 심정지요? 네. 예 여보세요? 여보세요? 예 심 아 성원 성원 169에요? 네네 시흥동 미소지역 아파트요. . 동대문구가 시흥동에 없어요. 선생님. 아니 서울시 동대문구 휴경동. 휴경동에요? 네. 휴경 미소지역 아파트요? 예. 어. 휴경 미소지역 아파트. 예 알겠어요. 그 혹시 선생님 선생님 거기 전화번호 있어요? 전화번호. 누구 전화번호? 수업문제 전화번호. 잠깐만요. 일단 잠시만요. 예? 어머니 성함이 어떻게 되세요? 알겠어요 일단 콜차 남았으니까 집 근처에 그 무슨 병원이지? 선생님 병원은 병원은 지금 고급대원들이 판단할거에요 심정지 환자분이시면 제가 통화 좀 해볼게요 집에 어머니랑 예예예
 예, 알려봅니다. 아 저기 그 그 응급실에 가야 될 것 같아서 전화드렸는데요. 아 구급자 필요하신 거예요? 네, 네. 네, 주소 알려주세요. 어 어 여기가 서초 레미안이요. 서초 레미안이요? 네. 서초 레미안 아파트. 네, 네. 몇 동 몇 호요? 네. 감사합니다.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네, 옵니다. 아저씨. 아저씨. 네, 무슨 일이세요? 너무 아파요. 어디가 제일 아프신 거예요? 하. 다 아픈데요. 네. 다리를 전혀 못 쓰겠어요. 아. 어디시죠? 지금 주소가? 여기가 여기가 강북구 미화동 에? 몇시요? 강북구 미화동 . 호가 번지 말하는거요? 아님 그 동 말하는거요? 하아 그 다른 주소는 응 삼양로 삼십 박 삼십 팔 가길이 이X 맞아요? 네 어 몇 층 몇 호에요? 주급차 바로 보내드릴게요. 혹시 열나거나 기침감기 증상 코로나 격리 중이시거나 한 거 있으세요? 그런 건 없어요. 그런 건 없어요? 전화 오면 잘 받으세요. 문 좀 열어 놓으시고요. 네. 네.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 여기 그 자전거 타다가 쓰러지셨는데. 근처에 길거리에 계시면 보이는 간판 같은 거 한번 불러보세요. 간판이요? 예. 서향 중식당이라고 있어요. 선 선. 서향 중식당이요. 서향 서향? 네. 아시는 분이요? 모르시는 분이요? 모르시는 분이요. 의식은? 의식 계세요. 아 교통사고랑이 그냥 넘어진 건가요? 아니면. 아 근데 막 토하고 계세요. 아 남자분이시고. 네. 교통사고 아니고 혼자 넘어지신거죠? 아 네. 알겠습니다. 차 나가면 전화 받으시면 안내해주세요. 네. 예.
 아, 여기 봅니다. 어, 예, 예. 기다려주세요. 어디 계세요? 여보세요? 네, 여보세요? 네, 말씀하세요. 네, 어디 어디 어디 어디 어디? 여보세요? 네. 아, 안돼요. 잘못, 잘못 떨어지는 거 같아요. 말씀하세요. 아파트예요? 어, 어, 여기가. 어, 그 한겨레 신문서 본사 바로 옆에이거든요. 아니, 주소는 모르세요? 선생님. 잠시만요. 여기 마포구 시청 몇 길 한결의 신문 한결의 신문사 한결의 신문사 건물이에요? 네네 맞습니다. 그 반대편 그 빌라거든요. 아 그러면 주소가 이 주소가 아니에요? 어 그러면 마포구 아 서청목길 아닌가요? 서청목길 한결의 신분사 주소인데요? 네. 일단 무슨 얘기세요? 어 여기 그 어 그 친구가 락스를 먹어서 락스를 먹었다고요? 네네. 음 언제요? 지금이요. 아 방금. 네. 고객님 지금 의식은 있어요? 아 네네네. 어 얼마나 먹었어요? 어 조금 후량 정도 먹은 것 같아요. 뭐 종이컵으로 뭐 한 어느 정도? 아니 반 종이컵 반컵? 네네. 반컵 정도? 아 네네. 빨리 좀 부탁드릴게요. 네 일단 거기 주소를 모르시는 거죠? 그러면? 네네. 그러면 한결의 신문 일단 앞으로 갈 테니까 밖에서 한번 안내를 해주세요. 아 네 알겠습니다. 아 선생님 잠깐 끊지 마시고 잠깐만 일단 어려운 선생님 잠깐만 좀 연결할게요. 일단 보고서 했으니까 끊지 마세요 잠깐. 네.
 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 아 네 그럼 방문은 출발할 거고요. 지금 뭐 열흘 같은 증상 있나요? 예 없습니다. 할머니요? 할아버지예요? 아니 예 할머니 아무리 혼잡니다. 예예. 알겠습니다. 조금만 기다려 주세요. 네.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 19 상황실입니다. 아 다름이 아니고요. 네 선생님. 저 Y2가 네. 저 당뇨가 있거든요. 아 안에 당뇨 분이 당뇨 있어요? 네. 예 근데 갑자기. 몸이 이렇게 옆에서 자는데 몸이 차요. 몸이 차다고요? 아 몸 몸이 차가요. 그래갖고 내가 홍수나 이렇게 위에다 잠기가 되게 밝거든요. 네네네네. 근데 아무리 흔들어도 안 깨나요. 근데 코는 계속 걸어요. 아 근데 그 깨워도 안 일하는데 이제 저 호흡을 하고 있죠? 숨은 잘 기식적으로 잘 쉬고 있죠? 예예 잘 쉬고 있고요. 네 그 아이 그것도 먼저 보내기 이대 이대 보니 예 예 입을 보니까 침이 침이 계속 나오고요. 그 몸이 차요. 그 몸 만져보니까 다 땀이에요. 아 식은 땀이었는지. 아 식은 땀 한다고요? 선생님 혹시 전에도 저혈당 같은 거 증상이 있었어요? 아니 그니까 병원을 다니고 있는데 아무리 지금 깨워도. 아 네 알겠습니다. 공급차 먼저 보내드릴게요. 용산구 신청만 맞아요? 잠깐만요. 주소만 좀 확인할게요. 혹시 빌라에 뭐예요? 아니 여기가 빌라긴 한데 빌라는지 뭔지 알겠습니다. 네. 구급차가 지금 갔고요. 몇 가지만 더 물어보면 구급차가 갖고 있는 아내분 나이트가 어떻게 돼요? 지금 마흔 마흔이요. 마흔 된거예요. 코로나 관련해서 키친가드 콧물 이런거 없으셨죠? 예. 다 맞았어요. 예. 알겠습니다. 신창동 신창동 빨리 갈게요. 예. 전화 잠깐만요. 현금사체팀 연결할게요. 전화 끊지 마세요.
 예. 일을 봅니다. 예. 여기요. 서울시 구로구 천황로 1길? 천황로 1길에. 천황 타운하우스. 무슨 일이세요? 선생님? 아 저기 저희 와이프가 신상에 기계가 있는데요. 어. 여보세요? 선생님. 예. 여보세요? 뭔가 멀어서 잘 안 들려요. 아내분이 뭐 심장이 아프시대요? 네네. 가슴이 아프시다는 거고 뭐 지병이 뭐 있으세요? 네네네. 심장이 달았거든요. 페이스메이커 달았다는 거예요? 네네. 예예. 그거 달았는데 심장이 아프다고 그래가지고 지금 응급실에 가봐야 될 것 같아가지고요. 아 응급실 가보시는 거고 그 천황 타운하우스 예예예 잠시만요 천황타운하우스 차 가볼건데 아내분 지금 의식은 있으세요? 네네 예 의식 있으신거고 그 최근에 뭐 발열이나 코로나 관련 사항이 있으셨어요? 아 그런거 없어요 아 예 알겠습니다 천황타운하우스 구급차 가볼게요. 선생님 가슴이 어떻게 아프시대요 환자분께서? 지금 막 심장이 안 드는 것처럼 꽉 잡는 게 들었거든요. 꽉 조이는 듯한 통증이래요? 네. 알겠습니다. 선생님 저희가 의료진 연결시켜 드릴게요. 통합 끝이 말고 계세요. 네.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 119입니다. 아 예 119죠? 어 저기 저희 어머니가 치매 환자인데요. 얼마 전에 허리 골통 때문에 입원을 하셨는데 그게 좀 충족이셨는지 이제 식사도 거의 안 하시고 어 그러다 보니 이제 그렇게 해서 시술은 받으셨어요. 근데 집에 오셨는데 계속 이제 잠을 못 자면서 잠을 계속 못 자요. 못 자면서 수면제를 달라고 계속 요구를 하시는데 제 문제는 뭐냐면 지금 식사를 거의 거부를 하고 계셔가지고 제가 아는 이제 의사한테 물어보니까 노인인 경우는 이렇게 안 먹고 있으면 저혈당이 와서 좀 위험하다고 그러는데 지금 어머니가 뭐 밤새도록 계속 이렇게 잠을 못 자고 거기다가 이제 기록도 없는 상태여가지고 뭐 이거를 응급실에 어쨌든 가가지고 무슨 영양제라도 맞추고 수면제를 초병을 받을 수가 있는지를 좀 모르겠습니다. 아 그러면 지금 그 의식에 가시려고 구급제 요청하시는 거죠? 예예예 그렇죠. 아 예 주소가 어떻게 돼요? 여기 손등로 103길. 잠시만요. 예 103길에. 네. 네. 어머니 지금 의식은 있으시고요? 네 음식은 있었는데요. 워낙 지금 뭐 밥을 거의 식사를 거의 못하고 계셔가지고 너무 기력이 없습니다. 아 예 그 가족분들 포함하셔서 코로나 자아 격리는 확신이 되는 건 없고요? 예 그거는 없습니다. 저희 아내랑 저는 다 6차까지 접종 완료했고요. 어머니는 부스터샷까지 다 완료하셨습니다. 아 예 알겠습니다. 지금 경전에 역삼동에서 출동할 거예요. 좋은 밤 기다리세요. 네 혹시 가능하면 세브란스가 원래 어머니 가던 그 치매 그게 있거든요. 아 예 그 병원 가시는 건요. 그 취등하는 9국 대원하고 한번 얘기해 보시면 돼요. 네 네 알겠습니다.
 네. 아 네 안녕하세요. 아 네 저 다름이 아니라 저기 와이프가 위심 중이기는 한데 지금 허리가 너무 아프다고 해가지고 혹시 그 앰뷸런스 부를 수 있을까 해서 지금 응급실 가고 싶다고 하는데 주소가 어떻게 돼요? 네 여기 저기 자양동 광진구 자양동 네. 대동 아파트. 네. 네. 네. 일단 그쪽으로 고객님 편성했어요. 네. 몇 주 산 부분이세요? 28주에서 지금 29주 사이요. 감기 증상했거나 코로나 확진자는 아니고요? 네. 그런 거는 아니고요. 네. 그냥. 대동 아파트. 네 맞아요. 네 고객님 저 편사했습니다. 기다려주세요. 네.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 아 네 여기 주소가요. 예 남현동 예 옥산빌라 옥산빌라요? 위에다 기억해서 옥산이요. 옥산. 옥산빌라. 아버지가 83세이신데 미끄러져서 넘어져서 꽝 했거든요 머리도 부딪히고 근데 지금 모든 여기 가슴이랑 다 너무 막 관심이 아프는 거 하세요? 모든 기능이고요 알겠습니다 선생님 의식은 있으시고요 호흡 괜찮으세요? 네 괜찮습니다 혹시 아버님 연락이거나 코로나 관련 없으시고요? 네 네 예 옥상 빌라티 맞으세요? 예 지금 곧 다 출발했고요. 아 선생님 거리는 3km에서 한 15분 정도 예상하셔야 될 것 같아요. 예 출발했습니다.
 예 119입니다. 아 예 안녕하세요. 여기 천호동 어 대우 한강 베네시티인데요. 그 환자가 너무 지금 하열해 가지고서요. 아산병원 응급. 잠시만요. 선생님 대우 한강. 예 천호동. 개우한강 베네시티 아파트 누가 아프신거에요? 저희 언니요 언니분께서 아프신거고 어디가 아프신거에요? 하혈했어요 하혈을 하신다는거고 지금 의식은 있어요? 어 그 뭐 있죠 그 위가 그 하이 그 위가 그 하.. 피가 난거 같아요 그.. 그니까 피를 토한다는거에요 아니면 아니에요 변으로 나와요 그 그 혈변을 본다는거죠? 어 뭐 있죠 그 항문으로 나왔어요 항문으로 네 항문으로 나온다는거잖아요 피똥을 예 예 피똥으로 나왔어요 예 선생님 그래서 지금 뭐 그 응급실 가보시라 하시는데 지금 거동이 안되시는거에요? 예예 그 다리가 또 골절이 됐어요. 그래서. 지금 의식은 있어요? 환자분? 예 의식은 있어요. 근데 혈압이 지금 떨어져 가지고 있어요. 아 예 알겠습니다. 한강 대우 한강 배너시티 가볼 거고요. 그 신고하신 분은 관계가 어떻게 되세요? 어 저 여동생이고 남동생. 아 예 알겠습니다. 그쪽으로 구호차 가고 있고 환자분 최근에 발열이나 코로나 관련 사항 있으세요? 없어요 그거 다 없어요 다 며칠 전에 아삼 응급실에 갔다가 다 검사했어요 아무 저희들 다 없어요. 아 네 알겠습니다 그쪽으로 빨리 가볼게요 선생님. 예 감사합니다. 네.
 네, 안녕히 계십니다. 네, 저기 75세쯤 되신 아버지인데요. 네. 방패 소액이 좀 의심돼서. 네. 주차 좀 이용. 예, 예, 예, 예, 주소 좀 알려주세요. 네, 여기 금호동 3가. 금호동 3가 네. 음 어 태호 커피 쪽으로 오시면 되거든요. 주택이라 가지고. 네, 그 번호 좀 다 불러주세요. 아 네. 네 그 앞으로 가면 될까요? 네 근데 이제 집이 골목길이니까 차가 못 들어오니까 네 세오커피라고 있어요 세오커피요? 네 세오커피 세오커피 네 그 앞으로 가면 돼요? 근데 거기까지 고급차가 못 들어간다는 말씀이시죠? 네 집 앞에 가셔서 꼭 들어가요 네 고급차 골목길 섭서해서 네 아버님 온 집에 계실 수는 있어요? 아니요 아 그럼 2권씩 들어가야 돼서? 예 알겠습니다. 아아 아 아 아 그 제가 말기를 잘 못 하셨는데. 네. 네. 네. 조금씩 걸으실 수는 있으세요. 아 네. 그러면서 저희가 뭐 집까지 안 들어가도 돼요? 네네네. 그럼 그 앞에 뭐 가시면 그 앞에 가서 전화를 드리라고 할까요? 아니면 저희가 댁까지 올라갈까요? 아 전화를 주시 아 어떻게 하지? 음 그러면 오실래요? 그 몇 층으로 가면 돼요? 단독인가요? 네 네 알겠습니다. 지금 출발하겠습니다.
 네 119입니다. 네 네 저 어머님이 지금 갑자기 그 못 움직이셔 가지고 자동이 안 돼요? 네 네. 네 구급자 필요하신 거예요? 네 네 저 양지병원으로요. 거기서 맨날 진료 보시거든요. 주소가 어떻게 되시는데요? 여기 관악 푸르지오 아파트 관악 푸르지오 아파트 네 네. 네. 네. 어머니 거동이 안되고 의식이나 그런건 다 괜찮으세요? 네네. 근데 어제부터 식사도 못하시고 아예 움직이질 못하셔가지고 막 걸어다니시고 이랬는데 갑자기 못 늘어나시고 기저귀 차고 계시고 소변 대소변 잘 못보시고 관악 끊어지요? 네, 네, 양지 병원으로. 네, 네. 네, 코로나 관련 그런 증상은 없으시고요? 글쎄 그건 모르겠어요. 12월 1일날. 네. 2차 접종까지 하셨거든요. 연락 오나 그런 증상은 있으세요? 없으세요? 아니 혈압만 어제 재니까 혈압이 조금 높으셔가지고. 있어요? 없어요? 지금은 없어요. 네, 일단 나가볼게요. 전화 잘 받으세요. 네.
 안녕하십니까? 예 저희 저희 어머니가 여보세요? 네. 예 저희 아버님이 지금 안 좋으셔가지고요. 어디 가쁘신데요? 어 지금 넘어주셨는데 좀 이렇게 안 좋으시라고 그러시거든요. 같이 계세요? 아니요. 저희 어머니가 저한테 전화해달라고 그러셔가지고. 어디 계세요? 지금 주소 불러드릴까요? 네. 예 지금 화공로 31층. 예? 네. 넘어져서 어디다 치신 거예요? 그거는 저 이제 그거는 그거까지는 제가 따로 계시거든요. 지금. 현장 전화폰 알려주세요. 예예 저희 어머니 전화 주소가 화공로 31개 맞죠? 예예예예 예 그쪽에서 좀 고사는 편성했구요 저도 이쪽에 전화 한번 해볼게요 예예 감사합니다
 예, 여기 롯데타워 앞인데요. 여기 저기 사람이 여기 자동차에 치였어요. 남자 여자요? 여자요. 여자분 의식은 있는 거죠? 네, 의식은 있어요. 네, 롯데타워 앞으로 가볼게요. 아 롯데타워랑 이제 그 건너편 롯데타워 건너편. 롯데타워 건너편? 어디 쪽 건너편이요? 저 제가 딱 저희 앞에 롯데타워랑 롯데 아 롯데 그 택하는 디파트먼 스토어가 있어요. 음 그 롯데캐슬 쪽이라는 거죠? 건너편이? 여기가 그 엔젤 엔젤이나 커피. 커피. 네 커피요? 네네. 아 알겠습니다. 아 롯데카페 플라자 앞이에요. 롯데카페 플라자? 네네. 아 예 알겠습니다. 그걸로 가볼게요. 네.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 아 여보세요? 네 그 주소 불러드릴게요. 저희 동교동? 마포구 동교동이요? 네. 몇 층 몇 호요? 몇 층 몇 호예요? 무슨 일이세요? 어 그 여자친구가 샤워하다가 네 넘어진거 같은데 머리에 살짝 피가 많이 나가지고 머리 살짝 찢어져가지고 아 여자친구 납상 있어요? 머리에가 찢어요? 네 아 의식은 있죠? 의식은 없어요 음 보급처 지금 보냈구요 네 머리 뭐 안쪽에서 나는거에요? 이마쪽 아니고? 어 뒤쪽이요. 네 정수리 조금 뒤쪽에. 차는 보냈고요. 선생님 따로 뭐 열 있거나 기침 콧물 있거나 거주하시는 분들 중에 확진자. 네 저희 없어요. 네 빨리 번호해주세요. 네.
 네 119 상황실입니다. 네 여보세요? 말씀하세요. 아 다른 게 아니라 애기 엄마가 예. 저거 다 치다가 무릎이 나간 거 같은데 네 예. 예. 근데 병원을 안 간다고 해서 근데 이거 긴급으로 해야 될 거 같아서 지금 옆에 계신 거죠? 아니요. 전 나와서 따로 전화한 거예요. 아 아내 분은 그니까는 집에 계신 거예요? 아내 분은 집에 계신 거예요? 환자분은 집에 계신 거에요? 예 직접 살려주세요. 김고랑로. 광진구이시죠? 네, 예. 예 김고랑로. 46 가길. 음 여쭤면 어떻게 되세요? 열은 안 나시죠? 네? 현자분이 열은 안 나시죠? 코로나 관련해서 특이사항 없으시고요? 예, 예. 예, 고급차 출동하겠습니다. 얼마나 걸릴까요? 지금 저기 용곡 초등학교 쪽에서 갑니다. 선생님. 네.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 수고하십니다. 네 안녕하세요. 저기 환자 환자가 지금 열이 너무 많이 나서 고정을 못해요. 그래서 그 응급실에 좀 가야 될 것 같은데 어떻게 하면 될까요? 구급차 보낼까요? 네 그 어떤 환자죠? 남자 여자요? 남자고요. 68세고요. 네 지금 뭐 코로나 관련해서는. 예 부스터샷까지 맞고 어제 제가. 언제 맞았죠 부스터? 어 한 2주 전이요? 어 그거 맞고 열이 있는 거예요? 아니면 감기 있는 거예요? 감기 같아요. 그래서 어제 제가 코로나 검사까지. 어 받았어요. 어제요? 네 밤에 음성이 나왔어요. PCR 검사 맞았다는 거 맞다는 거죠? 네 네. 구급차 음성 판정 받았고. 네. 주소 불러주시면 구급차 보내겠습니다. 예 저기 남대문구 전동동. 예. SK 아파트. 예. 네. 남편분이 그러신 거예요? 아니면. 네. 네. 남편이요. 남편이. 열이 많으시고. 구급차 보낼 테니까 전화 좀 잘 받으세요. 네 감사합니다.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 연락 옵니다. 네 수고하십니다. 다름 아니고요. 병원에 좀 가려고 그러는데요. 예예. 예 저기 여기가 주소가요. 예예. 보건 팔길. 무슨 구예요? 무슨 구? 아 예 관악구. 관악구에. 예 관악구 저기 보건 팔길. 보건 팔길에? 전원빌라예요? 네 전원빌라. 변원빌라 집 몇 동 몇 도예요? 뒤에 지하 102호. 네. 어디가 어떻게 아프신 거예요? 아 갑자기 집사람이 다리가 그렇게 쥐시고 막 움직이들모델 한 2시 정도 아프게 잘 움직이들모델. 아 저희가 그 모든 주소권에 코로나 관련 질문 드리고 있어서. 네. 보급차 가는 동안 제가 몇 가지만 여쭤볼게요. 예예. 아 발열이나 고열 기침 인후통 호흡기지나 코로나 관련 증세 있으세요? 아 그런 건 없어요. 예 3차 다 맞아서. 아 코로나 확진자로 만나셨거나 뭐 자가격리하시는 분도 안 계시고요? 네. 아 알겠어요. 그런데 가면서 전화드릴 거니까 전화 좀 받아주시겠어요? 예예. 이 전화로. 예 전화 주면서 갈게요.
 이리로 봅니다. 아 네 저기 저희 아버님이 지금 자택에서 인종을 하셔서 연락드렸습니다. 아 그 게시문 주소지 알 수 있을까요? 네 잠깐만요. 여기 소대문구 홍재동. 홍재동. 예. 예 홍재동 몇 번지인가요? 홍재원 4길. 여보세요? 홍재원 4길에. 예 동양 골드빌. 아 저 번지수는 번지수는 모르시고요? 아 홍보원 4길에 네네. 아 그 몇 몇으로 가면 될까요 저희가? 동양 골드비 네네. 구급차는 저희가 갈 거고요. 전화 끊지 마시고 잠시만요. 저희 울려크림 한번 연결해 드릴 거예요. 네.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 연락 옵니다. 여보세요. 아 예 저희 애가 경기를 해가지고요. 예. 아 그 경기 있어요 지금? 예 지금 경기를 하고 있습니다. 남자애고요. 예. 아 20살이요. 예. 그 주소 좀 알려주세요. 구급차 보내드릴게요. 아 여기가 그 음청유타운 예. 네. 아 거기 아 우물골 아파트 여기 맞나요? 우물골. 예예. 우물골 예 맞습니다. 쉬는 건 어때요? 호흡 상태는? 아 지금 막 정기는 멈췄고. 멈췄어요? 예 막 멈췄고 방금 예. 아 지금 구급차가 가고 있는데. 아 주변에 있는 제일 가까운 차가 딴 데 출동 나가 있어서 역촌동에서 올라가고 있어요. 금방 갈 거군요. 혹시라도 뭐 코로나 관련 증서를 다 여쭤보게 되는데 뭐 가족들 중에 그런 증세 있으신 분 안 계시죠? 아 출? 출동 대원이 전화를 드리면서 갈 거니까 전화 좀 받아주세요. 예 알겠습니다. 우리 애 아산 가야 된다고 그래요.
 네, 아기 가요. 해외제를 용량 이상으로 먹어서요. 상태가 안 좋은데요? 빨리 해주시겠어요? 아 지금 가보시겠어요? 아기 의식이면 괜찮아요? 네, 의식은 괜찮은데 어제 10 정도 되서요. 예, 잠시만요. 아기 몇 개월 몇 살이에요? 어 20개월이요. 20개월이고 네, 약은 언제 먹었어요? 어 지금 한 10분 전에 먹었어요. 네 알겠습니다. 주소 좀 알려주세요. 네. 대원빌라. 예 여기 열 있어요? 열 아니 동상태원. 해야 할 때 먹어서 예 지금 고급전 출발했고요. 10분 내외로 가실 것 같아요. 지금 출발했습니다.
 네, 일곱입니다. 예, 고분 다리 시장 안인데요. 할아버지 1명이 너무 술 드셔 갖고 너무 얼굴 다 까졌는데. 이렇게 해갖고 들어가시라 그러는데 조금 한 50m 가다가 또 앞으로 거꾸로 드는데. 몇 일을 하시네요. 아 그래요? 뭐 구급차가 필요하신 상황이신 거예요? 네? 구급차가 필요하신 상황이신 거예요? 구급차? 네. 얼굴이 많이 없어요. 아 그 구분다리 시장 어디로 가면 되는 거예요? 보이는 간판 같은 거 없어요? 여기가 교회 앞에요. 무슨 교회에요? 시장 안에 천호 천호 교회. 천호 교회? 예예. 선생님 뭐 지나가다가 발견하신 건가요? 예예예. 아 그래요. 알겠습니다. 시청해 볼게요. 예. 네.
 네. 읽습니다. 네. 여기 그 요양원 그 어르신이 조금 상태가 안 좋아지시는 것 같아서요. 네. 남자분 여자분이요? 여자분이요. 증상이 어떤 증상이 있으신 거예요? 어 그니까 아침에 물을 원래 식사를 드시는 분들이 아침에 물도 못 드시고요. 네. 지금 통증에 어떤 반응도 없으시고. 숨 쉬는지 확인해 보세요. 네? 숨 숨은 쉬고 있는지 확인해 보세요. 네네. 숨 쉬고 계세요. 호흡은 있으시고? 통증해주는데 방향이 없다고요? 네. 선수포화도도 나오고요. 아 그럼 몸에 힘이 없으신 거예요? 어 그니까 평소에도 원래 조금 많이 연루하셔서 이제 어 조금 연루하신 어르신이었는데 오늘 아침에 지금 이제 물도 못 드시고 약도 못 드시고 조금 네. 의식이 조금 막 왔다 갔다 하시는 것 같고 지금 어 어떤 통증에 자극에도 반응도 없으시고요. 코로나 관련 증상은 없어요? 선생님? 네. 없으세요. 열이나 기침 혹골나 이런 건 없으세요? 네. 체온 정상이고요. 주소 좀 알려주세요. 여기 서울시 강서구. 네. 급랑하루. 네. 어 배경 실버 스테이. 들어가면 되는 거예요? 선생님? 아 그래요? 네 알겠습니다 선생님 고기차 보내드렸습니다 네
 아 네 저 지금 그 여기 독산령 롯데캐스로 뜨긴. 네. 어 지금 계속 뭔가 어지럽다고 해가지고 계속 토론하고 있거든요. 남자여서요? 어 남자여서. 지금 롯데캐스를 안에 계신 거예요? 지금 정확히 어디 계신 거예요? 아파트 아니에요. 교차 롯데캐슬 골드파크 1차예요? 아니요. 아니요. 독산형 롯데캐슬이요. 그냥 독산형 롯데캐슬. 독산형 롯데캐슬. 네 집안에 계시고 여자분이 어지러운 구조 있으시고 환자분 의식은 있어요? 네 의식은 있어요. 제가 구급증을 보냈어요 환자분 감기 증상했거나 코로나 확진자는 안 해요? 네 그런 건 없었고요 3차 백신 맞은 지 일주일 지났거든요. 일단 구급증을 보냈으니까 만나보세요. 네.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 수고하십니다. 아 예 전 배가 아파서 그러는데. 누구 누구예요? 아 저 그냥. 선생님 본인이? 예. 예 그 주 구급차 보내드려요? 예 배가 아파서 그럴 수가 없거든요. 응급지가 그랬는데. 주소는 어떻게 돼요? 앞으로 나올 수 있어요? 방화 3단제? 집에 코로나 환자 자가 격리 발열 기침 있는 거 혹시 있어요? 없어요? 없어요. 없어요. 구급차 보낼게요. 병원 갈 준비하고 나오세요. 전화 잘 받으세요. 나오시면. 병원은 어디로 가나요? 이대병원으로 가나요? 병원은 구급대가 산점하게 돼 있으니까 구급대랑 상의하셔야 돼요. 아셨죠? 전화 이거 받으셔야 됩니다.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네, 여기 봅니다. 아 네, 저 택시 타고 지나가고 있는데요. 네, 네. 여기 길 바닥에 오토바이 쓰러져 있고 거기 운전자분이 그냥 쓰러져서 계시거든요? 어 지금 정확한 위치는 말씀해 줄 수 있어요? 지금? 아 잠깐만요. 기사님 아까 그 정확한 위치가 어디였어요? 그니까 저기 가리 공항이 뜨셔서. 네. 그 전화하고 방향. 가리 말씀해주세요. 여보세요? 네. 예 저기 시흥 아이씨 그러니까 저기 저 가산 쪽에서요. 여보세요? 가산 쪽에서 구로 전화국 쪽으로 오다 보면 시흥 아이씨 있는데 오토바이가 쓰러져 있고 사람이 쓰러져 있더라고요. 가산에서 구로 전화 쪽으로. 예 구로 전화구 방향으로 시행 인터체인지 거기 거기에 있어요. 거기에. 아 인터체인지 쪽에? 네. 어 그니까 방향은 여기 가산에서 구로 방향이고 시행 인터체인지 그 그. 부분. 네네. 아 교차로 이. 예예. 부분에 있다는 거죠? 예 구로 전화국 쪽으로 가다 오면은 있어요. 오토바이 넘어져 있고. 예. 제가 이미 지나가신 거죠? 예. 저는 지나가고 손님 오기 가기 때문에 지나가고 있는데 손님이 지금 전화한 거거든요. 네. 알겠습니다. 제가 한번 볼게요. 네. 빨리 좀 한번 가보세요. 예. 네. 잠시만요.
 119입니다. 아 예 아삼병원 지금 갈 수 있나요? 어디요? 선생님? 아삼병원. 아삼병원 직접 가시려는 거예요? 아니요. 응급실 가려 그러는데 가능한가 하고요. 아 문의 그 병원 안내하는 대로 연결해 드릴게요. 그쪽으로. 아니 아니 아니 그게 아니라 저기 환자가 간지론 해가지고 가야 되거든요. 그니까 구급차로 가신다는 거예요? 아니면 직접 가신다는 거예요? 아니요. 구급차로 가야 돼요. 아 일단 차는 보내는데 아산병원이 뭐 될지 안 될지는 저희가 뭐 간다 안 간다 말씀 못 드리고 현장 병원이 환자 상태 보고 가는 거예요? 알려주세요. 능동로 5길에 능동로 5길에 예? 몇 층 몇 호예요? 뭐 누가 경연했어요? 아 예 아빠가 지병이 있어요. 남편분이요? 예예. 아 지금 멈췄어요? 예예. 근데 지금 계속해서 가야 될 것 같아요. 아 지병이 뭔데요? 선생님? 많아요. 지금은 강경전이라 저기가 와요. 강원수 상태가 와요. 아 지금 그럼 의식은 있나요? 예 예 예 예약돼 있는데 예약 딱 예약 있을 때까지는 못 기다렸어가지고. 알겠어요. 차는 보냈고요. 기침 꽃물 뭐 열 뭐 코로나 관련된 사항 없으세요? 어 그런 건 없어요. 다 보냈어요? 좀 기다리세요. 네 감사합니다.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 1 2 9 입니다. 아 여기 그 중앙대학 병원에 와 있는데요. 응급실 입원을 할 때 입원이 입원실이 없어요. 응급실에 자리가 없다 해가지고 1 2 9 0이라고 해가지고 다른 데 가라 그러거든요. 저희 뭐 환자가 거동이 안 되는 상태인 거예요? 거동이 불편해요. 그니까 다른 병원 응급실로 가야 된다는 상황인 거예요? 그러면? 중고자분이? 그렇게 그냥 119 상의를 해버려요. 그렇게 그런 상태예요. 그니까 말씀드릴게요. 일단은 뭐 환자가 거동이 전혀 못하시는 상태면은 119가 가서 예송을 할 거고요. 이동 가능하시면은 병원 안내 부서로 연결해 드릴 수 있거든요. 아 병원 안내 부서로? 어떻게 하시겠어요? 목표 차로 보낼까요? 병원 안내 부서로 연결을 해드릴까요? 그러면은 119 그 오면은 조금 전에 얘기했던 병원 안내병원 그쪽으로 알아가고 문을 갈 거 아닙니까? 거기 병원 결정은 여기서 하는 게 아니라 현장 대원들이 환자 상태 보고할 거라서 여기에서는 어디 병원으로 갈 수 있다 이렇게 말씀을 못 드려요. 여기에서는. 그러면은 그 116 병원에 병원 안내라 안내라 그 안쪽으로 다 그죠? 그럼 정신차고 우리 갈아야 되죠? 예예. 내가 지금 전화하기도 불편하고. 어디가 아프신 건데요? 지금 남자분 분이. 한 1달 반 동안 식사를 못 했더니요. 뭐를 못 했다고요? 식사를 제대로 못 해가지고 온몸에 기력이 없어 기력이. 식사를 못 해서 지금 어디에 계세요? 중앙대 병원 응급실 앞에 계세요? 예예. 이 앞에 일곱 차 1도 있는데. 열 기침 뭐 감기 증상 이런 게 있으신 건 아니죠? 없어요 없어요. 그 앞에 있는 차들은 거기 앞에 있는 차들은 거기 다른 환자분 이송하고 뭐 소독하고 막 이해야 돼서 그 사용하실 수 없고요. 고객사를 새로 보냈으니까 열 기침 이런 건 없으신 거죠? 없어요. 없어요. 없어요. 예. 병대병원 지금 입원 진료 불가상태. 네. 한급실에 기다릴게요. 병원에서 전화하면은 위치나 상황 설명해주세요. 딱 가고 있어요. 지금 가까이 있는 사람들은 출동당 4km 떨어진 데서 방금 출동했습니다. 감사합니다.
 예. 말씀하십시오. 예. 저 호흡 곤란 때문에 그러는데요. 아 예. 공급차 필요하신 거죠? 예? 공급차 필요해서 전화하신 거예요? 예. 예. 주소가 어떻게 됩니까? 여기 마포자의 3차인데요. 네. 몇 분 몇 회요? 네. 누가 환자분이시죠? 저인데. 아 본인이세요? 네. 뭐 특별한 질병이 있으세요? 아니 그거는 아닌데 호흡곤란이 좀 종종 있었는데 오늘 좀. 말을 잘 못하겠어요. 알겠습니다. 저 보냈고요. 저 이거 코로나와 관련된 증상이 있나요? 호흡곤란이. 그런 건 없습니다. 열나시거나 기침하시거나 그런 건 없어요? 그런 건 예 없습니다. 확진자동산 겹치시거나 그런 것도 없으시고요? 예예. 저희가 잠시 의료진점 연결하겠습니다. 잠시만요. 네.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 어디잘요? 여보세요? 왼쪽에. 네. 어 왼쪽 발목이 너무 아파서 지금 못 걷는다고 하는데. 어 왜 넘어진 거예요? 아니면 띈 거예요? 어 계단에서 굴렀거든요? 그냥 발목 그 염자 띈 거 같네요. 그럼 여자분이요? 남자분이요? 여자요. 주소는 어떻게 돼요? 여기 홍대. 아 어디야 여기. 아. 선생님 가장 가까운 곳에 보이는 간판 뭐가 보여요? 세계 과자 할인점? 거기에 혹시 번호 써 있어요? 전화번호? 아 아니요. 여기 투썸 플레이스도 있어요. 투썸 플레이스? 무슨점이에요? 여기 그냥 홍대인데? 그니까요. 투썸 플레이스 여러 개 있잖아요. 그 무슨점이에요? 어 언니 잠깐만 여기 기다려봐. 여기 기다려? 어? 아이고 어 하 여기 그냥 홍 아 어떡하지? 어디 있지? 어디 홍대 뭐 예술 그래 거리점이에요? 거기가? 어 여기 그 창상마당 아세요? 아 그니까 선생님 저희는 정확한 주소가 필요해요. 거기가 투썸 플레이스면은 거기에 보면은 투썸 플레이스 무슨 점이라고 써 있잖아요. 그거 한번 점 거기에 투썸 플레이스가 꽤 많아요. 거기 무슨 점이에요. 거기가 여기 그냥 주소 얘기해 주셔도 돼요? 네 주소 얘기해 주면 더 좋죠. 와우살로 네 21길 네 네 네 그 1층에 있는 거예요? 그 앞에? 네 여기는 앞에 있어요. 네 알겠어요. 네.
 예 그 지금 저기 허리 통증 때문에 움직이질 못해서 그러는데요. 누가요? 아 제 와이프가요. 근데 지금 지금 마당에 지금 누워 있어서. 넘어졌어요? 마당에서? 넘어진 건 아니고 어제부터 허리가 안 좋았었는데. 네 지금은 허리를 전혀 움직이를 못해서 지금. 이 좀 옮겨야 될 것 같아서. 예 병원으로. 병원 가시려는 거죠? 예예. 아 주소 알려주세요. 어 상대 4동. 네. 단독주택이에요? 예예. 예. 잠시만요. 상대 산 4동. 산 4동이에요? 아 네. 상대. 아 잠시만요 여기 도로 주소를 봐야겠네 여기 우편물 온 거 있죠 아버지 여기 주소가 어떻게 되었지 우편물 온 거 없지 3번 출구 당국의 역 3번 출구로 오면 되는데요 바로 앞인데 잠시만요 네. 장보 계약 3번 출구 바로 앞이에요? 집이 많이 있는데 선생님? 예. 거기에 저희가 나가 있을 테니까요. 예. 3번 출구 앞에서 멀어요? 집이? 가까워요? 아니 가까워요. 가까워요. 예. 3번 출구 앞에 일단 그쪽으로 가라고 할게요. 예예예. 앞에서 기다리세요? 예. 네.
 예 119입니다. 아 여보세요? 말씀하세요. 네 엄마가 엄마가 숨이 안 쉬어져서요. 호흡은 안 하신 거 같으세요? 네 돌아가신 거 같아서. 의식은요? 의식도 없어요? 네 네. 예 주소 불러주세요. 뭐가 찍어 주소. 응암동. 응암동? 네네 조용히 와주세요 네네 응암동이 맞아요 선생님이 계신 곳이 연신대 쪽으로 나오는데 은평구청 앞쪽에 계신 거 맞아요 그러면? 네네 맞아요 맞아요 리치빌이요 리치빌? 네 빨리 와주세요 우리 안내원 영향이라면 구급차는 이미 출동했어요 끊지 마세요
 예, 알겠습니다. 예, 예. 예, 말씀하세요. 예, 집사람이 코로나로 저기됐거든요. 예, 예, 예. 자가. 예. 자가 치료하고 있는데요. 혈압이 올라가고 있거든요. 아 혈압이 올라가고 있다고요? 예, 예. 근데 보건소에서 전화 안 받아가지고요. 예, 전화 안 받으시는 거예요? 지금 보건소 쪽에? 예. 아 뭐 지금 상태가 뭐 혈압이 올리시고 뭐 상태는 어떠신 거예요? 가슴이 통증인데요. 가슴 통증이랑? 네. 알겠어요. 지금 구급차 한번 가볼게요 선생님. 주소 좀 불러주세요. 은평구 역촌동. 예. 번호 아파트. 번호 아파트 예 몇 층 몇 호예요. 예. 알겠습니다. 구급차 지금 출발시키고 보건소 전화 계속 안 받는 거예요? 계속 하시는데? 그 몇 번 했는데 제가 안 받네요. 지금 뭐 병원 배정됐다고 뭐 연락받으신 것도 없고요? 병원 청심 저 뭐야. 연신내. 연신내? 아 이 전화 성함이 어떻게 되세요? 어머니? 네. 저희 출동돼 지금 출발시켰고 저희 의료 상담원서 연결 테니까 전화 끊지 말고 기다려 계세요.
 예, 119입니다. 예, 어머니를 좀 응급병원에 좀 옮겼으면 하는데요. 그 어디가 어떻게 아프세요, 어머니가? 일어날 시간이 됐는데 안 일어날 제가 보고 보니까 지금 의식이 없으신 것 같아요. 숨은 쉬세요? 예. 그 주소 불러주세요. 여기 은평구 역첨동. 역첨동. 풍림 아이원 아파트 아그네스 풍림 아이원 아파트 풍림 아이원 아파트 아그네스 풍림 아이원이요 주소는 모르세요? 역촌동 일거에요 아마 예예 몇 호요? 1박 동은 1뿐인 거예요? 예예예 그 환자분이랑 같이 계신 거 맞죠? 예 그 차 나갔고요. 지금 의식 없다고 하셔서 응급처치 할 수 있도록 도와드릴게요. 끊지 말라고
 실례합니다. 여보세요? 네. 네 저기 지금 신랑이 아파가지고. 네 어디가 아파요? 아 오른쪽 다리요. 오른쪽 다리? 네 오늘 전화해가지고 다녀오게 했었거든요. 응급실을. 네. 근데 지금 차도가 없고 계속 더 아파가지고. 아. 거실을 미쳐서. 네. 네 주소는요? 미화동? 네. 몇 층이 몇 초에서요? 코스는 따로 없나요? 네 네 혹시 코로나 관련해서 고열이나 기침이나 이론천 증상 같은 건 없고요? 네 그런 건 없고요 예 알겠습니다 어저께 검사 받아가지고 음성들 다 나왔거든요 결과는 아 예예 알겠어요 네 네
 네, 6입니다. 아 네, 저 응급실 좀 가려고 하는데요. 예, 누가 어떻게 아프세요? 아 지금 기본적으로 암 환자인데. 예. 갑자기 지금 다리를 걷지를 못하게 돼서. 예. 예, 예, 응급실 근데 지금은. 주소 좀 예, 주소 좀 알려주실래요? 도봉구 도봉로. 도봉로. 창동. 예? 100 114길. 도봉로 114길에. 네. 그 누가 그 거동이 안 되신다는 거예요? 이 보 아 이미 아 여기 지금 살고 저는 이제 뭐 4천 5개고요. 지금 여기 계시 이 성함이. 아 그 여성분이시고요? 네네 무슨 암으로 치료 바꾸게 돼요? 아 그 지금 유방암에서 치료는 받았었는데 스스로는 나중에 예 또 뭐지? 의식은 있으신 거죠 지금? 아 예 의식은 다 있어요 있는데 아 근데 선생님 하나 부탁 말씀드릴게 서울대 응급실로 가야 되거든요 여기서는 저기 확정드릴 수가 없어요 그 병원 선정은 네 출종하신 고급 대원들하고 상의하셔야 되었고요. 아 그러면 고급 대원분 나중에 전화 주실 겁니다. 예 그럼 연락 좀 부탁드리겠습니다. 네 출종해서 고급 대원들하고 상의하세요. 아 네네네. 뭐 집에 자가 격리자나 뭐 확진자 계신 분 아니 계신 분 아닌 거죠? 예 없습니다. 예. 예 알겠습니다. 네네.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네. 일로 봅니다. 네. 안녕하세요. 홍익지구대인데요. 네. 말씀하세요. 예. 그 여기 그 술 먹은 사람 그 계속 소여가지고. 네. 네. 그 1번 아까 와주셨는데 1번 더 와주셔야 될 것 같아요. 예. 홍익지구대 안으로 가면 돼요? 예예. 서교동 서교동 양화로 11개

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네, 안녕하세요. 저 죄송한데. 예예. 지금 액체가 떨어지는 바람에. 액체가 떨어지는데 애기 손을. 애기가 손이 상처가 좀 많이 났어요. 예예. 근데 제가 지금 소리를 한잔 마셔가지고. 네. 못 할 것 같아요. 아 그 가까운 응급실로 모셔다 드릴게요. 아이가 남자예요? 여자예요? 남자요. 몇 살이에요? 저 이제 9살에 이제 예, 10살됐어요. 아 손쪽에만 출혈이 있는 거예요? 예. 왼손이요. 아 저희 구급차 나갈 거고요. 그 위치 주소나 위치 좀 알려주겠어요? 여기 저기 파크 데이. 어디요? 마천 1동 파크 데이 아파트요. 아 송파 파크 데이 1단지인가요? 지금 전화가 계속 울려서 들려서 잘 안 들리거든요? 몇 동 몇 호시라고요? 네네. 아 저희가 요즘에 모든 출동권에 코로나 관련 질문을 드리게 돼 있어서 몇 가지 질문 좀 드릴게요. 아 가족분들 포함하셔서 발열이나 고열 기침 이모통 호흡기장에 주시면 안 계시죠? 예예 괜찮습니다. 아 코로나 확진자를 만나셨거나 자가격리하신 분도 안 계시고요? 네. 아 저희가 송파파크대일 1단지. 전화 드릴게요. 전화 좀 받아주세요. 예 알겠습니다.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네. 안녕하세요. 어머니가 노출내신데요. 네. 어젯밤에 마루에서 크게 엉덩방아지셨거든요. 네. 거동을 못하시는데 병원에 좀 데려다주시면 안 될까요? 세상에. 제가 언제쯤 가실 거예요? 예예. 어디예요? 주소가? 소초구 자문록. 네. 자문록. 자문록 아파트. 네. 네 잠 없는 잘 안들려요 잠 없는 신간보 치트야 흔들거려가지고 뭐가 잘 안 되나요? 아니요 선생님 그 심란포 7차 예. 네 어머니 의식이나 그런 건 다 괜찮으세요? 예 의식은 있는데 엉덩이로 너무 심하게 와가지고 전혀 고통을 못하세요. 네 차 나가볼게요 전화 잘 받으세요. 예. 네. 감사합니다.
 Thank you. Thank you. I don't know. Hello. Hello. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. I'm not a good one. Ah, so? I'm not a good one. I'm not a good one. I'm not a good one. I'm not a good one. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. 네, 네. 어 조금 술도 먹고 그래가지고. 음 저혈압이 왔었어요? 알겠습니다. 선생님 저희 갈 때까지 조금만 기다려주세요. 네. 네. 아, 엄마 거야.
 네. 일곱니다. 예. 수고하십니다. 저 어지럽고 막 쓰레질 것 같고 짓다기 나서 그러는데요. 요건 입원 좀 하려고 합니다. 아 저 주소 알려주세요. 아 여 저 음천구 불방로 예예예. 예. 힐스테이트 힐차요? 네. 어지럽다고요? 네. 어지럽고 막 긴 땀이나고 쓰러질 것 같아요. 네. 코로나 관련된 거 최근에 없으신가요? 예예. 그런지 몇 시절 한 보름 전에 받았거든요. 네. 알겠습니다. 빨리 갈게요. 네.
 119입니다. 말씀하세요. 네 여기 저기 동남구 장안동. 어 저기 청원 파크빌 잠시만 장안동. 네 청원 파크빌. 그 아저씨가 갑자기 어지럽고 아프다 그랬는데 병원에 좀 가야 되겠는데 아 네 알겠습니다. 코로나 관련해서 열이나 기침 이런 증상 있나요? 아래 분이 네? 열이 나기침 이런건 없구요? 예예 알겠습니다. 조금만 기다려주세요.
 일일 9입니다. 말씀하세요. 그 제가 계단에서 불러가지고. 예예. 지금 병원에 봐야 될 것 같. 아 일단 거기 위치 알 수 있을까요? 어 그 강남역 10번 출구 그 술집 많은데 쪽인데. 강남역 10번 출구 그 술집 이름 뭐 아무거나 말해 볼래요? 그 앞에 있는 술집. 그 치치라고. 치치? 네 치치요. 잠시만요. 한번 찾아볼게요. 일단. 아 네 뭐 지치 앞으로 가면 되는 거예요? 그러면? 고 앞에 계시고 저희가 가면서 전화드릴 테니까 전화 잘 받아주시고요. 뭐 코로나 기준에서 열이나 기침 이런 증가 있었나요? 네 없어요. 없고요. 예 알겠습니다. 조금만 기다려주세요. 네.
 실례합니다. 예예. 도봉구 방학도. 예예. 예. 지금 저 호흡이 지금 숨을 안 쉬고 있어가지고. 숨을 안 쉬고 있다고요? 예예. 지금 몇 층이에요? 단독주택이라고. 잠시만요. 선생님 누가 숨을 안 쉬어요? 지금 저기 보살님이. 여성분이. 예예. 의식은 전혀 없어요? 지금 예. 잠시만요. 선생님 일단 저희 2회 출발하고요. 네. 이제 주소 의료 지도를 안내해 드릴 거예요. 방학동 지금 출발합니다. 네. 네. 네. 이제 한번 깨워보시겠어요? 지금 의식이 지금 없어졌어요. 저 여기까지 숨을 쉬었는데 숨은 쉬다 갑자기 호흡은 있어요? 호흡? 호흡이 없어요. 지금. 호흡 전혀 없어요. 잠시만요.
 예. 경기도고요. 들어갔나요? 네. 통화하겠습니다. 네. 여보세요. 선생님. 여보세요. 예예. 우설초등학교 정문 앞으로 가는 건가요? 저희가? 아 우설 아 이게. 상황이. 서울 우설초등학교 앞에 양계천 면에 그 양계천 산책로인데요. 네. 어느 분 일단 의식은 있고 말은 하시는데 못 일어나고 거기 계셔가지고 전 자리를 일단 떴는데 그 자전거와 함께 양재 첨면에 떨어져 계셔가지고. 아 그래요? 혹시 몰라서 드렸어요. 예 수강. 의식은 있고 말은 하시는데 잘 일어나지는 못하시는 거 같아요. 예 알겠습니다. 수강하러 나가보겠습니다. 네 일단 저는 자리를 떠서 잘 모르겠 어떻게 될지 일단 혹시 몰라서 신고했습니다. 예 알겠습니다. 남자분이셨어요? 여자분이셨어요? 남자 노인이셨어요. 네 알겠습니다. 한 50대 60대 분이셨어요. 예 감사합니다. 주황색 패딩 주황색 패딩이었는데 어두워가지고 잘 확인을 못했어요. 주황색 패딩 잠바? 아아 주황색 패딩 잠바 주황색 자전거였어요. 주황색 자전거? 네 알겠습니다. 수강하늘 나와서 확인하겠습니다. 네.
 네, 일요일입니다. 여보세요? 예. 우방 아파트요. 우방이요? 네. 네, 무슨 일이요? 아이 허리가 막 너무 돼가지고 방에서 허리가 아파가지고. 본인이요? 예? 본인이요? 예예예. 네. 가족분들 포함해서 코로나 지역 다녀오거나 관련 증상 있나요? 없어요. 네. 우 방 아파트예요? 네? 우 방? 우 방 우 방. 경산동 우 방 아파트. 아 경상도예요? 네. 경상남도예요? 경상북도예요? 아이 저 저 저 경산동. 경산동. 정산동? 예. 아 증산동? 예. 우방 아파트가 안 나오는데 주소는 모르세요? 아 그 DMC 우방 아파트 말하는 거예요? 예예 맞습니다. 진산초등학교 옆에 있는 거 맞죠? 예. 알겠습니다. 가볼게요. 전화 오면 잘 받으세요. 예.
 1 9 입니다. 여보세요. 여보세요. 아 1 9 예요. 말씀하세요. 여보세요. 예 수강서에요. 말씀하세요. 예 제가 도저히 못 견뎌갖고 예 전화를 드렸습니다. 어제 아프신 거예요? 예 그 저 아침에 병원비가 없어요. 안 된다 그래갖고. 병원비를 보내주기로 누가 했어요. 예 좀 저 좀 살려주세요. 대신 곳이 어디예요? 주소 좀 알려주세요. 예? 주소 주소 좀 알려주세요. 대신 곳 주소. 제기동. 예? 양양 양 중앙로? 어디가 어디가 아프신 거예요? 지금 방역 때문에 양쪽 한쪽 다리는 자르고 한쪽 다리는 지금 괴사가 돼갖고예. 예 그래갖고 지금 정신을 못 찾을 수 있는 걸 아프예. 아 거기가 제기 고시원이에요? 아 뭐 저희가 코로나 관련 증세 뭐 다 여쭤봐야 되는데 그런 증세는 없으세요? 다른 다른 기사는 없습니다. 아 알겠어요. 그러면 가면 전화드릴 거예요. 예. 감사합니다.
 1 1 9입니다. 말씀하세요. 예 저기 여기 상봉동. 상봉동. 중랑구 동일로. 동일로. 네. SD 사워 아파트. 네 근데 아버지가 요즘 허리를 못 써갖고 꼬치상 못 해갖고 어제 병원에 갔다 오는데도 전혀 소용이 없고 아버지가 혼자 계시기 때문에 제가 왔더니 침대에서 움직이지 못해갖고 소변 싸고 난리가 났어요. 일단 저희 나가볼거구요. 그 아버지가 열이나 기침 이런 증상 있나요? 코로나 관련해서. 없어요. 전혀 없어요. 어제도 저거 갔다왔어요. 근데 처음이 없어요. 네 알겠습니다. 조금만 기다려주세요. 네 감사합니다.
 119입니다. 네. 몸이 아파가지고 저기 전화하라고 했었어요. 선생님이 아프신 거예요? 예. 어디가 아프세요? 몸이 전체가 그냥 아프고 한 5일 동안 밥을 입에 남겼으니까 막 입술 타고 몸이 힘들어요. 전신이 아프다고요? 예. 주소 어떻게 돼요? 네. 금천구 어 시흥동. 네. 음 격산 아파트. 네. 격산 아파트. 네. 뭐 열 있거나 기침 콧물 있으세요? 그냥 위치 차고 너무 아파요. 선생님 벽산 아파트 있나요? 여기 몇 단지예요? 벽산 지금 선생님. 6단지. 알겠습니다. 차 보낼게요. 코로나 때문에 격리하시는 분 없죠? 확진자 있거나? 선생님 코로나 확진 되셨거나 격리하시거나 그런 거 없으신가요? 차가 격리돼 있어요. 지금이요? 네. 어디서요? 집에서 갔어요. 자가격리 중인 거예요? 확진자예요? 네. 확진 되셨어요? 아내분? 네. 선생님은요? 나도 확신이 나와가지고 선생님 지금 확진자예요? 예 아 말씀을 해주셔야죠 선생님 좀 확진되셨다고 아 코로나 확진되셔서 집에서 지금 뭐 재택치료 하시는 거예요? 예 너무 힘들어가지고 아 재택치료 하시는 거예요? 아니면 병원상 대기 중인 거예요? 재택치료? 아 알겠어요. 고객사 보낼게요. 네

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네. 네 119 상황실입니다. 예 구급차 지금 금방 도착할 거고요. 신고자분. 발열이나 기침 같은 증상은 있으세요? 없으세요? 아이를 포함해서 지금 격리 중인 분들 중에는 발열 기침 특이사항은 없으신 거네요. 일단은 그래도 자가 격리 자기 때문에 아무 데나 갈 수가 없고 보건소에 통보도 해야 되고 지정 병원을 받아서 병원에 가던가 해야 되거든요. 저희 9급대 오면 그 그 부분 말씀해 주시고요. 그 보건소 담당자 연락처 혹시 번호 있으신가요? 담당자가 연락 경위라고 자가 경위를 뭐 통보 받은 게 지금 그쪽에 있는 연락처 말씀하시는 거예요? 예예. 잠시만요. 예. 아 신고자 그럼 그쪽에 한번 전화하셔갖고 지금 상황을 말씀해 주시겠어요? 이래 이래서 구급차 타고 갈 예정인데 병원을 혹시 선정해 주겠냐 아니면 임의로 선정해도 되냐 확인 좀 해달라 이렇게 한번 통화해 주세요. 구급대 오기 전까지요. 예 지금 금방 도착할 겁니다. 예. 네.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 여보세요? 예예 그 무슨 중간에 끊어져서요. 예. 아 여기 병원이 그 저양동에 건대 옆에 있는 서울 프라임 병원으로 갈 거거든요. 그러니까 저희가 그 병원 선정은 상담실에서는 할 수는 없고요. 출근 구급 배원들이 판단하시는 건데 그니까 입원 목적으로 이렇게. 아 거기로 가기로 했어요. 지금 병원에 연락을 해가지고 거기서 응급 수술이 가능하니까 그럼 저 그 원래도 성격병을 했으면 월요일까지 수술이 안 된다 그래가지고 집으로 퇴원이 퇴원 입원도 안 되고 그래서 지금 집으로 퇴원을 했다가 어제 그러니까 지금 뭐 병원 연락해서 가시는 거는 그 사설 구급차를 이용하셔야 돼요. 그러면요. 선생님 그러니까 예예 119 얘기해가지고 가면 안 돼요? 예 저희는 저 응급실 진료만 그 이송이 돼서요. 그 사전에 연락해서 받으시는 거는. 그쪽 그 프라임 병원도 정형외과이기 때문에 그 24시 응급 수술하는 병원이라 밑에도 응급실로 가면 되는데. 예 그러니까 일단 저희가 이제 구급차를 보냈는데요. 네. 대원들이 판단하는 거여서 여기 사무실에서 뭐 된다 안 된다 이렇게 확답을 드릴 수가 없거든요. 아 그러면 대원들 오시면 그분들이랑 얘기해서 우리 동사무소도.
 네, 봅니다. 예. 지금 차가 좀 와야겠는데. 누가 어떻게 아프신데요? 어 엄마가 배가 다가가 다가가 아파갖고. 어머니가 복통이 있으세요? 예, 지금 배가 아파가 죽겠어요. 주소는요? 집 주소요. 그 그 시흥제로 120길. 시행대로 127 지금 몇 호요? 예. 열 있거나 기침 콧물 있어요? 어머니? 아 저 그냥 배 아프다 그랬다고. 아 코로나 때문에 격리하시거나 가족분들 중에 확진자 있거나요? 없어요. 그러면. 네. 차는 보냈어요. 네.
 네 저 혹시 지금 네. 호흡 곤란 때문에 공항장에 공항장에 와가지고 호흡 곤란이 있는데요. 혹시 구급차 보내주실 수 있나요? 혹시 경험을 못 받으시는 거예요? 아니 아까 왔는데 네. 그냥 가셔가지고. 구급차원이 뭐라 그러고 갔어요? 코로나 진상. 괜찮다고 했는데. 아 진정제 맞으라고. 아 나 그것도 기억이 안 나. 진정제를 맞으라고 했는데 지금 뭐야. 호흡곤란이 코로나 증상이라고. 네. 병원을 못 간다고 해가지고요. 호흡곤란 있으시면 무조건 격리실로 들어가야 되기 때문에. 그 격리실이 없으면 병원에서 안 받아주거든요. 그거 말씀하신 것 같은데. 보급대원이. 지금 근데 호흡곤란이 지금 계속 심해지는 거예요? 아. 괜찮아요. 아 이게 심해지는 건 아닌데 진정이 안 돼가지고. 제가 응급실 진료 보려고 하는데. 저희가 근데 선생님 진정제를 놔드릴 순 없어요. 저희 의사가 아니기 때문에. 그럼 진정제 놓을 수 있는 건 아니거든요. 119가. 저희는 2종만 아는 거예요. 응급 현장은 응급처치를 하는데. 아 그건 아는데요. 제가 차를 타고 일단 어쨌든 가야 되잖아요. 네 지금 응급실 진료를 보신다는 거죠? 네 그냥 진정제 1 놔두려고 하는 건데. 못 들어간다고 해가지고요. 그 부급대원들이 현장에서 판단한 거고요. 그 다시 요청을 하시는 거죠? 선생님 그 주소 불러주세요. 주소요? 하곡동 맞아요? 몇 층이에요? 돌계단 돌계단 네. 네 그 응급실에서 단속에 증정제만 놓을 수 있는지 선생님 모르겠어요. 일단 가봐야 되고요. 혹시 지금 회사분 열나거나 뭐 기침하시거나 감기 증상은 없죠? 그 그때 가니까 전화 잘 받으시고요. 그 쉴 호흡 좀 하고 계세요.
 네. 여기가 고맙습니다. 마찬가지로. 여보세요. 아버지가 지금 너무 아프셔 갖고 지금 돈도 못 드시고 밥도 못 드시고 하는데 지금 병원을 가봐야 될 것 같아가지고요. 아 예. 어디가 불편하십니까? 아예 움직이지를 못해서요. 그냥 거의 누워가만 계시고 아예 그냥 컴퓨터를 못하시고 그래 갖고 지금 당장 움직이지를 가야 될 것 같아가지고요. 아예 음식도 못하시고 지금 정신도 거의 없으세요. 지금요. 아 그래요? 어디로 차 보내드릴까요? 주소가 어떻게 됩니까? 서울시 성동구 마장동 현대아파트 아파트요? 예 마장동 현대아파트 예. 네 지금 차 보냈습니다. 환자분 호흡은 어떻게 하고 계세요? 숨쉬는 거? 호흡은 하시는데 가래가 많이 끓여서 제대로 막 가래가 끓는 것처럼 가빠요. 호흡이 바쁘시다. 그럼 저희 어르신 좀 잠시 연결해 드릴게요. 전화 끊지 마시기 잠시만 얘기해 주십시오. 코로나 관련된 거 혹시 그건 없어요. 지금 나갈 적이 없어가지고요. 알겠습니다. 잠시만요. 감사합니다.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 여보세요? 네 선생님 119인데요. 경찰에 할아버지 쓰러져 있다고 신고하셔가지고 구급차가 같이 나갈 건데요. 앞으로 가면 돼요? 네. 아 지금 보고 계세요? 할아버지? 아니요. 제가 출근 중이어가지고. 네 그 앞에 그냥 뭐 움직임 있고 눈뜨고 다 하시는데 얼굴에 피가 묻어있는 거예요? 아니요. 피가 묻었다는 얘기 안 했는데 그냥 쓰러져 계셨어요. 꿈틀거리고 계셔가지고 신고했어요. 아 피인단 말은 안 하셨어요? 아 일단 쓰러져 계신다고요? 일단 저희 집 통화할게요. 앞으로 가요. 네.
 아 네 여기 지금 약간 호흡곤란이랑 쓰러진 건 아닌데 지금 응급실에 가야 될 것 같은데. 누가 누가 그래요? 그 여기 여자친구인데. 예 호흡곤란 증사가 있어요? 지금? 지금 같이 있어요. 쓰러질 것 같다고요? 아 네 그 세워지진 않았는데 지금 계속 폭우 권란이랑 계속 답답해하고. 아예 이동 사전 아예 못하거든요. 지금. 예 주소가 어떻게 돼요? 지금 계신 데가. 잠시만요. 네. 어 여기 이거 부문동 국민은행 있는 쪽이거든요. 잠시만요. 국민은행 거기 보문동 지점이에요? 네 맞아요 맞아요. 거기 그렇게 써 있어요? 보문동 지점이라고? 네 보문동 KB 국민은행이요. 외암프라자. 아 잠시만요. 여기 지금 거기 혹시 대광초등학교 옆에 있어요? 지금? 아 네 맞아요. 아 거기 사이 골목길이에요? 아니면 여기 사거리 쪽이에요? 그 사거리 쪽이요. 은행 딱 앞이요. 아 그 은행 앞에 이쪽으로 하면 돼요? 네네네. 예, 여자친구 열이나 계층 뭐 코로나 관련 사항 있나요? 아니요, 없습니다. 아, 그런 거 없어요? 네, 알겠습니다. 전화 잘 받으세요. 네. 네.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 이제 끝번째로. 감사합니다. 예. 여기 지금 일고 사용을 이용하고 싶은데요. 네. 무슨 일이에요? 아 지금 혼자. 예. 누가 어떻게 아파요? 아이 지금 많이 안 아파요. 어디가. 아 저는 눈하고. 네. 동생이 아프신 거죠? 예. 어 어디 주로 아픈 데가 어디예요? 그럼 아예 그냥 기억이 없는 거예요? 예. 오늘 알았습니다. 네. 주소는 어떻게 돼요? 금호산 2길. 잠깐만요. 금호. 산 2길. 금호산 2길. 예. 아 잠깐만요. 20 금호산 2길에. 응? 잠깐만요. 네. 다시 한번 검색해 볼게요. 금호산. 금호산 금호산 2길. 네. 저희 행정지도 보고 네이버지도 검색하면 네이버지도도 안나오고 금호산 이 길에 없는 주소로 나오거든요 몇 층이에요? 여기 지하에요 지하 지금 집에 코로나 환자나 혹시 네 알겠습니다 네 감사합니다 감사합니다.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 예 119 사항이십니다. 말씀하세요. 아 여기 혹시 그 아 무슨 아파트지? 아 아 경제록길. 네. 여 경제록길 요 4거리에 우리 어떤 아주머님이 지금 저기 몸을 못 감으시고 여기 계시는데. 모르는 분이에요? 예 저는 모르죠. 여자분이 잠깐만요. 의식은 있어요? 예예 있습니다. 대화도 되고 근데 아 사거리 쪽에요? 예예 여기 화장실 1 있죠? 여기 간화당실. 사거리. 반영장실 있다고요? 예예 여기 예. 어디 사거리인지 뭐 아파트 아까 뭐 어디 맞어? 여기 안함 아파트. 안함 아파트 뭐라고요? 예예예. 그 사거리에 얼른 와주셔야 되겠네. 다꾸만 누워 계시네. 이 추운데. 알겠습니다. 차 보낼게요. 네네네네.
 네. 일고생 하셨습니다. 네 안녕하세요. 지금 하고 위가 너무 아프고 7번이나 토해서. 예 주소 먼저 불러보세요. 주소. 보문록. 승국구 맞죠? 승국구. 네. 보문록. 네 매칭이에요? 선생님? 여보세요? 주소가 다시 한번 확인 좀 부탁합니다. 공문노 34길 그 다음에요? 여보세요? 예? 네. 네. 네. 잠시만요. 몇 층이에요? 예. 예. 그 그 병원 가실 거죠? 네 배가 아파요? 그 토요일 7번을 했는데요 밤이 안 와요 온몸이 쑤셔서 그래도 가야 할까요? 예 국차 보내드릴게요 선생님 저기 그 뭐지 열이 난다거나 호흡 기절한 그런 거 없죠? 코로나 증상처럼 아 그런 건 없고요. 주거하기 바늘은 안 맞아요. 여보세요? 예 구급자 측발 할게요. 병원 가실 거죠? 네 구급자 측발 합니다.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 죄송합니다. 수요 주사 방 앞으로 할 수 있나요? 어디요? 수요 주사 방 앞이요. 어떤 일 때문에 어떤 일 때문에 불난 거예요? 아니 그 소주병으로 사. 아 싸움이 싸움이 나세요? 네 소주 방으로 사. 아 제가 서울시 전체에서 전화 받고 있는데 계신 곳이 어디예요? 수요동 어디예요? 수요동 수요동 앞이에요. 어디요? 주사 방 앞이요. 주사 방 앞에. 주사 방 앞에? 네네. 아 알겠어요. 혹시 다 치신 분 몇 명 계세요? 제 바람에 빨리 오세요. 지금 인사에 빨리 오세요. 빨리 오세요. 야 호수님 어디로 가. 야.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네. 1 9입니다. 예. 여기 관자가 1 있어서 그러는데요. 네. 그 병원에 지금 가야 되는데 어지름증이 생겨갖고 걷지는 못해요. 네. 응급실 가보시겠어요? 예예. 예. 주소 말씀해 주세요. 예. 조금 기다려 주세요. 예. 주소 자리. 기다려 주세요. 여보세요? 예. 네 주소 불리세요. 예. 서울시 양천구 목동 중앙 북로 팔길 금호 베스티벌 아파트 아 다시 1번만 천천히 불러주세요. 양천구 목동 중앙 북로 팔길 북 북로요. 북로. 북로 8길. 예. 금호 베스트빌 아파트. 예. 누가 어떻게 아프신 거예요? 예. 어머니가 지금 어지럼증으로 투하시고. 예. 예. 지금. 어머니 나이대가 어떻게 되세요? 예? 몇 살 60대 70대 몇 살 정도 되세요? 70대 어머니. 여보세요? 예. 네 구급차 보내드릴게요. 선생님 기침하고 열나고 코로나 증상 있으세요 없으세요? 아 그런 건 없어요.
 예 여보세요. 예 선생님 일일구 상황실인데요. 예예. 네 1호선이에요? 아니면 경위중앙선이에요? 예예 1호선이에요 1호선. 1호선 1번 출고요. 예예예. 아 네 알겠습니다. 대원들 나오고 있어요. 예예 얼른 좀 오셔야 되겠어요. 사람들이 많이 있어서 예예예예 예
 어, 실례합니다. 이런, 이런거. 네, 자꾸 쥐가 혼자 사는데 쥐가 나와갖고 아프갖고 그, 몇 시에요? 네, 아. 본인이 그러세요? 네, 쥐가 나와갖고. 아. 아우 어떡하면 좋겠어요. 아우 기가 나서 지금 아프신 거예요? 네. 아우 차 나가볼게요. 전화 잘 받으세요. 네. 아우.
 115입니다. 네 여기 부민병원 앞인데요. 무슨 병원. 연락하신 분이 지금 숨이 숨이 저기 차가지고. 천십 병이. 이제 목장 병원으로 좀 가려고 하고 있어요. 선생님 병원은 구간 구급대원이 판단을 하는 거라 저희가 알 수가 없고 선생님 무슨 병원 앞이라고요? 아 부민병원 앞이요. 아 그 중학교 중간쯤에. 동의병원 정문 앞이요. 아이 정문 앞이라 해야 돼. 아 그니까 1분만 얘기하세요. 1분만 여기저기 자꾸. 경향교회. 경문교. 경향교회 정문 앞. 경향교회 정문 앞. 무슨 교회? 경향교회 정문 앞. 주소 알아요? 주소? 아 그 발음이 너무 울려서 그러는데 천천히 한자 한자 또박또박 무슨 교회? 경향교에. 경향교에? 예. 간호법 사거리에 있는 곳이에요. 잠시만요. 좀 찾아볼게요. 네. 경향교에 있고 거기에 부민병원 있고 그런데 경향교에 앞으로 가면 돼요? 네. 예. 거기에. 그래서 증세가 어떤데요? 아 숨을 숨이 차가지고 숨을 잘 못. 누가 숨이 차요? 네 97세 되신 저희 98세. 아버님 어머님. 어 어 어 아니야 시어머님. 여자분이시고 98세고 숨이 찬다는 거죠? 네 숨이 고라가 저기 차가지고 막 숨을 못쓰셔요. 예 알겠어요. 그 경향교회 앞으로 갈게요. 네 예 감사합니다.
 네, 1분입니다. 말씀하세요. 네, 안녕하세요. 선생님 저 저 할머니가 네, 서랍이 200이 넘고 몸이 안 좋아요. 엄청 지금 그래가지고 연락드렸어요. 구급차가 필요하세요? 예, 구급차가 필요할 것 같아요. 예, 주소 알려주세요. 예, 서울특별시 상복구 정릉로 12길 70번. 예. 영흥주택입니다. 영흥주택 몇 층 몇 호예요? 할머니 어때요? 증상이 의식이랑 호흡 있어요? 의식이랑 호흡은 있는데 200에서 지금 149 나왔어요. 146 나왔어요. 고연합이 나온다고요? 예 예 예. 평소에 고압 고압 고압 있으셨고. 손자분이요? 네 네 네. 그 차 출발해서 나가고 있고요. 코로나 확진자분 가족 중에 계신가요? 예 없어요. 없어요. 예 알겠습니다. 영흥주택. 네.
 119입니다. 네 안녕하세요. 여기 세문환로 그 포시스 호텔인데요. 무슨 호텔 이름이 어떻게 되신다고요? 광화문 광화문 포시스 호텔이요. 네 무슨 일인가요? 네 저희 직원이 요리하다가 칼에 베었는데 심하게 베어 가지고 어제름증을 느끼고 있어 가지고 병원에 손 부상 손 절단되거나 손가락 절단되거나 이런 건 아니죠? 출혈이 많아서 그런 거예요? 네 많이 돼요. 그 고차 어디로 가야 되나요? 포시스 호텔 뭐 정문으로 네 일단은 안내하는 분한테 좀 얘기를 해주세요. 성함은 있는 거 맞죠? 근데 혹시?
 감사합니다. 전화하고 있어요. 여보세요? 네 저희 그 저희 가족이 발을 헛디려가지고 발을 배웠는데 네? 가족 누굴? 어머니 아버지 아니면 동생 누구? 형이요 형. 형이 발을 배웠대요? 칼로? 네네 발을 배웠는데 피가 좀 나가지고 지금 움직이기 힘들 것 같거든요. 구급차 보낼까요? 어 어떻게 할까 구급차 네 오시는 게 좋을 것 같아요. 주소가 어떻게 되죠? 서울시 그 광진구 중곡동. 몇 층 몇 도예요? 네 있어요. 그냥. 네 혹시 열이나 기침, 코로나 확진자, 자가격리자 해당이 있습니까? 아니요 없습니다. 다 아마 기차까지 다 접종할 수 있겠군요. 네 알겠습니다. 구급차별로 보내겠습니다. 전화 잘 받으시고 문자를 열어주세요. 네 감사합니다.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 아 여보세요. 저 다리가 부러져서요. 계단에서 넘어졌는데. 계단에서 넘어지셨다고요? 예예. 어 어디가 제일 많이 갇힌 것 같아요? 본인이 다리가. 아 지금 다리가 아예 안 더러가요. 아 본인 제 다리가? 예. 본인이신지 주소 혹시 아세요? 예? 예 여기 면목 4동이고요. 면목 4동. 네, 네. 잠시만요. 아, 아. 일단 구급차 보냈거든요. 몇 층으로 가면 되죠? 아, 여기 지금 1층 내려오다가. 1층? 아, 연락하나 혹시 기침감기, 코로나 격리는 아니시죠? 아, 그런 건 없습니다. 아닙니다. 움직이지 말고 계시고요. 최대한 바로 보내드릴게요. 전화 오면 잘 받아주셔야 돼요. 예.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 110입니다. 예 여기 그 이문로 32길인데요. 이문로 32길에 몇이에요? 20 32길에 어 여기가 바로 앞에 보인 내과 의원 있거든요? 무슨 내과? 그 3거리에요. 보인 내과 의원이요. 잠시만요. 검색 좀 해볼게요. 보인 내과의원 그 앞에 예 무슨 얘기세요? 네 삼거리요. 거기서 오토바이랑 한의원이랑 같이 있는 거죠? 거기가. 네, 네, 네. 네. 거기 앞에 삼거리에서 지금 오토바이랑 캐시가 그 부딪쳤는데요. 접속 사고가 나서. 네 몇 명이 다쳤어요? 지금 1분이요. 남자 1분 오토바이 타신 분이에요? 네, 네, 네. 그분이 차 아래 깔려 있거나 그래요? 아니요. 지금 나오시긴 했는데 다리가 좀 불편하신 것 같아요. 그래요? 네네. 예 알겠어요. 그럼 앞으로 갈게요. 선생님은 지나가시다 본 거예요? 아니면은 뭐. 네 지나가다가요. 예 알겠어요. 네.
 아니 아니요. 고객님. 여보세요. 네 안녕하세요. 여기 GS 슈퍼 광진 하향점인데요. GS 뭐요? GS 슈퍼 마켓 광진 하향점이요. 광진 하향점? 네 네 네. 무슨 일이세요? 네 고객님이 계산하시다가 쓰다지셨는데 피가 좀 많이 나셔가지고요. 남자분요? 네. 여자분? 남자분? 여자분이세요. 할머니. 의식 있어요? 네네네. 의식 있는데 피가 좀 많이 나셔서 얼굴에서요? 얼굴에서요? 얼굴이 있어요? 머리 쪽에서요? 네. 수강하늘 가고 있어요. 얼마나 걸릴까요? 5분 10분 걸려요. 5분 10분이요? 네. 네. 알겠습니다.
 예 1 9입니다. 아 예 그 아내가 자다가 일어나서 갑자기 아랫배 통증이 너무 심하다고. 구급차 보내드려요? 네? 구급차 보내드려요? 아 네. 주소가 어떻게 돼요? 어 서울시 영등포구 버드나르도 네. 11길. 버드나르도 11길. 네 한가람 더원. 삼가람 더원 예. 코로나 이런 관련 증상 이런 건 아니신 거죠? 네. 배가 갑자기 통증이 심하다고 허리까지 아프다고. 자 영등포 쪽에서 보내드렸어요. 영등포 소방서에서. 대한별 강의를 전화드릴 수 있어요. 네.
 예, 의리구입니다. 아 네, 저기 그 저기 뭐지 뭐지 지금 환자 있어서 전화드렸는데요. 심장이 뻐근하고요. 숨이 찼고 지금 뭐지? 뭐지 두통이 있고 열은 없어요. 예, 지금 여자분이세요? 여자고요. 지금 고급자가 필요하단 말씀이신 거죠? 네, 저희 아산병원으로 갔으면 하는데 네, 네. 주소 알려주세요. 예, 저기 그 강동구 고등로. 예, 예. 롯데캐슬. 예. 예. 롯데캐슬 퍼스트 아파트 말씀하시는 거죠? 예, 예, 맞습니다. 예, 차는 출발시켰고요. 환자분하고 감기가 어떻게 되세요? 아, 동생이에요. 지금 열나거나 코로나 관련 증상은 없으세요? 예 그 열은 없고요. 코로나 백신 맞고는으로부터 숨이 좀 이렇게 가끔씩 찼대요. 근데 이게 지금 오늘 엄청 심하거든요. 예 저 코로나 관련해서 보건원서 연락받으신 건 없으시고요? 예 없어요. 아 출발시켰으니깐요. 조금만 기다리세요. 예 감사합니다. 예 예. 네.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 감사합니다. 말씀하세요. 네. 여보세요. 여기 도남 힐스테이트. 도남 힐스테이트? 예. 예예. 네, 제가 지금 배 왼쪽이 그 대장 쪽이 엄청 아파서 지금 막 막 뜨겁뜨겁 구를 정도거든요. 근데 이게 막 변해봤는데 피가 나오는 것 같구나. 네, 알겠습니다. 혹시 뭐 반려 증세도 있어요? 반려 증세? 반려 증세가 뭐예요? 열도 나세요? 코로나 관련해서? 아니요, 아니요, 없어요. 네 알겠습니다. 저희가 수정할테니까 문을 열어주세요.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 안녕히 계십니다. 예 여기 청동주공 사단지 예 예 무슨 일이세요? 저희 예 저희 어머니께서 지금 어지럽고 막 조금 어지럽고 뭐 움직이지 못하실 정도로 그래가지고 예, 보호자 요청하시는 거죠? 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예,
 네. 1 2번 일단 부르고 전화를 드릴게요. 여보세요. 여보세요. 예. 여기 답신리 주민 주민센터 이동 앞에 있는 주민센터 묘량 사무자인데요. 네. 네. 지금 사람이 쓰러져가지고. 남자분 여자분이요? 여자분이요. 음식이 있나요 선생님? 지금 계속 음식은 약간 있으신 것 같은데 최대한 빨리 오셔야 될 것 같아요. 선생님은 뭐 지나가다 보신 거예요? 아니 아니 저희 안에 여기 음식 드시러 오셨는데 갑자기 쓰러지셔서. 아 손님이? 네 아 그 가게 이름이 뭐라고 하셨죠? 요리왕 사무점이요 요리왕? 예예예 잠시만요 아 혹시 코로나 관련 사항은 확인 안 되시죠? 열이 있는지 비침 있는지 감기 생산 같은 거 있는지요? 그것까지는 제가 어떻게 자세히 모르겠고요 일단 오셔서 확인하셔야 될 것 같아요 요리왕 짬뽕 전문점 맞아요? 네네네 맞습니다 아 예 알겠습니다 고객님께 보냈습니다 네

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 말씀하세요. 네 저 성북구 월급도에는 영광교회 앞인데요. 네 어디 앞이시라고요? 아니 영광교회. 영광교회요? 네 어떤 분이 넘어오셨나 봐요. 근데 자리를 심하게 덜으셔가지고. 남자분이 넘어지셨어요? 아니 여자분이요. 저희가 잠깐 영광교회 좀 검색 좀 해볼게요. 선생님 잠시만 기다려주세요. 안 가겠어요. 그 월공연장교회인가요? 그 아파트 근처요. 네, 두산 아파트 옆에. 예, 그쪽으로 구급차 보내면 될까요? 선생님. 네, 네, 네. 그 여자분이 넘어지셨고 지금 다리 쪽이 아파하신다고요? 네, 오른쪽 다리 굉장히 많이 심하게 떨어졌어요. 네, 알겠어요. 그쪽으로 구급차 보내드릴게요. 선생님. 네, 네.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 예, 여보세요? 아, 119 상황실이에요? 예, 예, 예. 아, 경찰 쪽에서 연락 받고 저희 구급차 오징어 청춘 쪽으로 가고 있는데. 예, 예, 지금 상황이 좀 심각해서 테이블이 몇 개 넘어졌고요. 혹시 뭐 출혈이 있으신 분 계세요? 충분히 없는데 지금 많이 뭐 다친 사람도 있고. 몇 분 계세요? 환자분은? 지금 환자는 없고요. 지금 계속 행사하려고 하거든요. 아 예 알겠습니다. 경차차하고 소방차하고 같이 갈게요. 예.
 실례합니다. 말씀하세요. 아 네 안녕하세요. 그 지금 아파가지고 저한테 연락을 했는데. 네. 증상이 조금 의심적어가지고 먼저 그냥 119에 연락을 했거든요. 뭐 구급차가 필요하신 건가요? 선생님? 네 네 구급차가 필요해요. 그럼 위치 좀 알려주시겠어요? 논현동. 강남구 논현동인가요? 선생님? 네 네 맞습니다. 잠시만 계세요. 네 논현동이요. 선생님. 네 논현동. 죄송합니다 전화가 이렇게 음이 끊겨 돌려서요 숫자가 1밖에 안 들리거든요 뭔가요 선생님 네 선생님 네 그 건물에 선생님 네 밑에 들어가는 중단 비밀번호가 또 있어가지고 그거는 네네. 그거는 아마 그것 때문에 전화할 거고 지금 전화를 아예 못 받는 상황이신 건가요? 그 누가 아프신 거라고 하셨. 누가 아프신 거라고 하셨죠? 친구인데 이 친구가 이제 외국인 친구여가지고 근데 전화 받을 수는 있어요. 한국말 할 수 있을까요? 이 일을 천천히 뜯고 말씀해주시면 이해할 수 있을 거예요. 아 외국인 친구가 지금 어디가 아프시대요? 지금 아침에 일어났더니 토를 먼저 했고요. 에. 열을 재봤더니 37.5도고. 미열이 있다는 얘기신 거죠? 혹시 확진자 접촉하거나 그런 건 모르시겠네요? 잠시만요. 잠시만요. 어 자기가 알기로는 없대요. 아 그래요? 선생님 저희가 그쪽으로 보내드릴게요. 그분 혹시 모르니까 전화번호 좀 알려주세요. 아 네 잠시만요. 네. 네. 네. 네. 선생님 혹시 모르니까 중간 번호 좀 알 수 있을까요? 중간 비밀번호 좀 알 수 있을까요? 아 네. 네. 네. 누르면 된대요. 한국말을 조금은 하는 상황이신 거죠? 네. 네. 네. 말하기가 조금 어려운 상태긴 해요. 알겠습니다. 그쪽으로 구급차 보낼 거고요. 선생님. 네네. 혹시 모르니까 저희 구급대가 선생님한테 연락을 할 수 있어요. 전화 좀 받아주세요. 그 주소 좀 다시 한번 확인할게요. 논현동 네 맞습니다. 네 알겠습니다. 그쪽으로 구급차 출발했어요. 네네 감사합니다.
 네, 여기 서울역인데요. 여기 여학생이 하나 쓰러졌는데 빨리 오셔야 될 것 같은데. 의식이 있어요? 몇 박은 뛰어요. 몇 박은 있어요? 숨도 쉬고 있는 거죠? 어, 손이 엄청 숨는데. 서울역 어디로 가면 되는 거예요? 서울역 대학실이요. 맥도날드 앞이요. 서울역 대학실 맥도날드 앞이요? 네, 네. 아, 숨을 쉬고 있는 거죠? 숨을 쉬죠. 마스크를 하고 있어요. 선생님은 지나가다 발견하신 거고요? 예? 지나가다 발견하신 거죠? 네, 뒤에 앉아 있었어요. 아 네, 알겠습니다. 그럼 쉬고 있고요. 어 호흡이 있는 호흡 어 눈이 파르르파르가 하는데. 잠시만요. 선생님. 의식은 있어요. 네. 의식은 있고요. 선생님 저희가 쉬고 싶었고요. 예. 아 저희가 의류지 담겨서 문자책 안내 안내할 거니까 전화 끊지 마세요. 그냥 옆에 어.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 119입니다. 네 안녕하세요. 네. 우리 아들이 지금 허리가 너무 아파갖고 꼼짝을 못 하거든예. 잠시만요. 예. 원래 질환 있으세요? 아니 그 허리가 좀 약하긴 했었는데 이렇게 꼼짝 못 하기는 처음입니다. 네 지금 회수에 가보실 거죠? 예. 어디로 가면 될까요? 뉴스타트라고 병원을 가주고요. 아 예예. 리센트 아파트. 잠시 리센트. 아파트. 잠깐만요. 예. 잠깐만 제가 잘못 부럽습니다. 네, 감사합니다.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 일로 봅니다. 아 네 저희 아이가 25개월 됐는데 열이 39도 39.5도 이렇게 왔다 갔다 해가지고요. 이제 목동에 있는 거기 그 소아가 따로 결제돼있다 해서 가고 싶거든요. 아 그 고열이 있으면 병원 선정하는 거를 좀 전화해서 확인해봐야 될 것 같고요. 네 전화해서 확인했습니다. 네. 그 병원 선정은 제가 결정할 수 있는 게 아니고요. 부급보원들이 환자 상태로 보고 결정하시는 거라. 아 그래요? 현장에 도착을 해보셔야 될 것 같고요. 남자인가요? 여자인가요? 여자아기요. 그 주소 좀 알 수 있을까요? 잠시만요. 네. 관악구 신림동 맞습니다. 혹시 건물이 모카빌라예요? 네 맞습니다. 고열 증상 말고 다른 증상 혹시 있으세요? 대책을 하고 어제부터 대책을 가졌게 했고요. 대책이 뭐 어떻게 그냥 지금도 좀 대책을 하고 지금 애기는 자고 있고요. 아 저희가 그 모든 수도권에 코로나 관련 주문 중인데 아기 말고 다른 가족분들 중에 발열이나 고열 기침 민호통 코로나 관련 증세 있으시면 안 계시고요? 없습니다. 네, 네. 아 확진자를 만나셨거나 자가격 있는 상태이신 분들 안 계시고요? 어 그런 거 없습니다. 네. 아 그 혹시 그 코로나 그 온도 고열이 39도라 저희 대원들이 혹시라도 그 보호복 같은 걸 착용하고 갈 수도 있어요? 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네
 네, 누구입니다? 예, 여기 정릉인데요. 환자가 폐암 환자인데. 누구세요? 남편이세요? 네. 추경 중이시고 좀 호흡 곤란하시고요? 예, 예. 의식은 어떠세요? 예. 어? 의식 있어요? 눈 뜨시고. 눈 뜨고 부르면 반응해요? 눈 뜨고 계시냐고요? 아 네 아예 그런 거 같은데. 네 지금 주소 주소 알려주세요. 정릉 1동? 몇 층 몇 호예요? 어? 몇 층 몇 호. 골목으로 가면 돼요? 네. 골목에 이렇게 들어오셔서 동생에서 앞에 보면 쭈꾸미집 있거든요. 골목으로 이렇게 들어오시면 쓰댕 때문에 있어요. 그 집이에요. 골목길에 들어와서 쓰레기 줄어다서 있으니까 저희가 알아서 시작할게요. 네. 맘편보신 열나시거나 코로나 관련 증상 없으시고요. 네. 그런 건 없고 제 쪽은 투명이시고 알겠습니다. 지금 고통 수강할게요. 얼마나 걸려요? 얼마나 걸려요? 네 그 방 앞에서 가요. 300m. 네 지금 준비하세요. 네.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 죄송합니다. 아 예 죄송합니다. 제가 저기 응급실 좀 갈 수 있을까 해서요. 어 병원 응급차가 필요한 거예요? 예 배가 아픈데 응급실에 가려면은 그냥은 못 가잖아요. 그냥 갈 아니 그냥 그냥 갈 수 있으면 가셔도 되는 거고 그냥 이동이 불가하면 저희 차가 가고요. 아 배가 아파서 움직이기가 좀 힘든데 지금. 주소는 어떻게 돼요? 예 여기. 무슨 동인데요? 예 미화동이요. 미화동에? 몇 층에 계세요? 내려와 있는데요. 앞에? 예 예 예. 예 배 아픈 거 말고 혹시 열나거나 기침 코로나 관련 자가격리 확진자 해당 없고요? 그런 건 없고요. 지금 화장실이 경비가 안 나와가지고 배가 막 계속 아픈데 저는 못 봐가지고 지금 그런 거예요. 아 그래요? 죄송합니다. 조금만 더 기다리세요. 그 구급차 보낼게요. 지금 근거리에 차가 안 잡혀서 조금 도남동에서 출발해야 돼요. 그래서요. 좀 기다리셔야 됩니다.
 예 119입니다. 예 애가 중심적인 듯이 난동을 부려가지고 병원에 좀 보내드릴 같은데요. 그 남자의 여자예요? 여자 고등학교 2학년입니다. 그 세브란스에서 진료를 받고 있고요. 선생님이 좀 생각해야지. 예예. 말씀하십시오. 주소요 주소. 아 예 여의도 은하 아파트. 잠시만요. 볼게요. 여의도 무슨 아파트요? 음마 아파트요? 은하 은하. 은하 아파트? 예예. 찾아봐야 되겠지. 잠시만요. 예예. 은하 맨션으로 나올 겁니다. 은하 아파트 돈을. 맨션 그거 주소는 모르세요? 주소는. 여의도동. 여기 네동 몇 동 몇 도로 가면 될까요? 알겠습니다. 그 차 출발했고요. 전화 오면은 잘 받아주세요. 예, 예, 일단 좀 알려 보고 있겠습니다. 예.
 네, 119 입니다. 여보세요. 예, 119 입니다. 여보세요. 여보세요. 예, 말씀하세요. 119 입니다. 아우 갑자기 댓글 가다가 어지러워가지고요. 거치를 못하겠습니다. 어지러워요. 아, 정말. 여보세요. 위치가 어떻게 되세요? 위치가 지금 정확하게 아, 이거 어디야. 저기 어, 그 석. 삼전역하고요. 석전 우체 중간 지점이거든요. 선생님. 삼전역요? 예? 삼전역하고요. 삼전역하고 석천 거분역 중간 지점이거든요. 석천 거분역이요? 잠깐만요. 석천 거분역 중간 지점이요. 그리고 보이는 게 뭐 혹시 6교 뭐예요? 6교하고 건너편에 뭐 우측인가 뭐 거울 막 몰아가지고요. 아 예 선생님 근데 지금 뭐 보이는 게 뭐 주유소 뭐예요 뭐. 6주로. 6주 안 들고 건너편에 우체국인가 빨간 거. 아 막 어지러워가지고요. 우체국이 보인다고요? 아 예예 우체국인가 뭐 빨간 거. 선생님 여기 또 어디쯤 어디쯤 돼요? 아 아. 아 여보세요. 여보세요? 잠깐만요. 아 저 앞자 안 찍힙니까? 제가 우체국 좀 찾아볼게요. 잠깐만요. 아우. 어우. 선생님 거기에요. 예 고 고분 석촌 고분역 그 근처에 상장 그 우체국이 있어요. 네 건너편이요. 그 건너편으로 가면 될까요? 예예예. 최근에 기침하고 열 그런 건 없죠? 아 기초에 한 3일 전에 저 코로나 3차 맞았거든요. 다른 증상 문제 지금 어지러워가지고 갑자기 어지러워가지고요. 지금 땅이 불이 돌아가지고 지금 어떻게 할 수 없나. 아무튼 코로나 관련은 없고요. 빨리 갈게요. 예.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 여보세요? 예예. 네 여기 119 4번에 129 상황이신데요. 예예. 네 그 환자분이 뭐 하다 채 못에 끼어 있거나 이런 상황은 아니실 거예요? 아 저 그렇진 않고요. 네 그런 건 안고요. 아 의식은 있으신가요? 예예. 환자분 몇 명이에요? 1분이세요? 3분이요. 예예. 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드 오드
 안녕하십니까? 네. 네. 그 고급 병원 좀 보내주실 수 있나요? 예. 주소가 어떻게 돼요? 네. 본인이 아프신 거예요? 어디 아프신 거예요? 아 오늘 아침에 제가 고급차 타고 가서 그 코로나 검사 받았거든요. 예. 그리고 거기서 약을 받았는데 그 코로나 음성으로 나왔고요. 근데 지금 잠을 전혀 못 자겠어요. 너무 몸이 뜨겁고 그리고 머리도 좀 아프고 그래가지고 이거 좀 병원을 가야 될 것 같아요. 아 알겠습니다. 식사할게요.
 네, 안녕합니다. 아, 여기 건대 동문회관 앞인데요. 네. 여기 그 남성분 한도 쓰러지셔 가지고. 아, 의식 있어요? 네? 의식, 의식 있어요? 네, 네, 의식 있으신 거 같은데 지금 잘 못 일어나고 계시거든요. 아, 그래요? 알겠습니다. 숨을 쉬고 의식은 있다는 말씀이신 거죠? 네, 의식 있습니다. 타 사고 난 거 아니고요? 아, 그냥 그냥 쓰러지셨습니다. 네, 수강 한도 빨리 가겠습니다. 네. 다음 영상에서 만나요.
 네, 16입니다. 말씀하세요. 예, 여기 저기 그 약수동 동아 약수 하이츠 아파트. 잠시만요. 약수 하이츠. 무슨 일이세요? 저희 어머니가 지금 쓰러지셨어요. 숨으시네요. 의식 호흡 있어요? 예, 의식 지금 이러셨다가 잠깐. 지금 이제 말씀하시는데요. 토를 막 하시고요. 연세가 좀 많으시고 지금 정신을 잠깐 이러셨다가 네 알겠습니다. 대원들 나가볼 거고 여기가 약수역 앞에 있는 약수화이체 맞죠? 네, 네, 네. 어머니 그 어머니랑 신고 좀 최근에 코로나 관련해서 의심 증상이나 저 그렇게 또 문자 받으실 수 있으세요? 그거 없으시고 저희 어머니 어머니 3차까지 다 받으셨죠? 네 알겠습니다. 대원들 나가면서 전화드릴 수 있으니까 전화 받고 안내받으세요. 네, 네, 네, 네.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 일곱. 어? 일어나주세요. 아니요. 일어나도 아이 지금 노인네가. 네. 그 화장실에서 아침에 넘어져가지고요. 네. 지금 갈비뼈가 지금 많이 아프려 해가지고 이거는. 아 할머니예요? 예예. 아 화장실에서 납상돼가지고 어디 뭐 피나거나 그래요? 피난 거는 없는데 갈비가 이쪽에가 지금 무지매 아프려 해가지고. 어 옆구리 통증이 심하대요? 예예. 거동 안 돼요? 안 될 것 같아요. 네. 주소가 어떻게 되세요? 서울 영등포구 여의대방로 다시 삼성 아파트 잠시만요. 여의대방로 몇 번지라고요? 네 삼성 아파트 네 할머니 열이나 기침 뭐 코로나 관련 사항 있으세요? 없어요. 네 전화 잘 받으세요
 네, 여름입니다. 네, 저 지금 언니가 그 뭐지? 어 몸을 지탱을 못해서 그러는데 빨리 와주실 수 있을까요? 네, 언니가 지탱 못한다는 게 무슨 말씀이세요? 뭐 어디가 쓰러지면 못 하시는 거예요? 아니요. 원래 그 그 심의가 좀 안 좋아가지고 약을 우울증 약을 먹는데. 지금 손도 잘 못 쉬고 그래가지고. 어디예요? 지금 여기 샛빛 상당 그 반포 샛빛섬? 있는데 쪽 주차장이요. 세빛 둥둥선 말씀하시는 거예요? 네 맞아요. 아 거기 앞에 있는 주차장이라는 거죠? 네. 네 주택 나라 바로 나가고요. 혹시 코로나 관련 있는 분 현장에 계세요? 아니요. 아무도 없어요. 알겠습니다. 조금만 기다리세요. 네.
 네, 일류보입니다. 예, 여보세요? 네, 말씀하세요. 아, 예, 배가 너무 아파가지고요. 네, 고급자 필요하신 거죠? 예. 주소가 어떻게 되죠? 아, 아, 기름도. 기름도. 몇 층 몇 호예요? 아. 문 열 수 있겠어요? 본인이? 아, 네. 네 문 좀 열어놓으시고요. 저희 코로나 관련된 거 최근에 있었어요. 최근에 코로나. 없습니다. 네 얼른 갈게요. 문 좀 열어주세요.
 네 119입니다. 말씀하세요. 아 예 저희 어머니가 예전에 무릎 관절 수술하셨는데 일어나다가 뭐가 잘못되셨는지 아예 움직이시지 못하거든요. 그래서 예. 운전 일어나다가 부산 거동불가 지금 응급실 가주려고 하신 거죠? 아 주소 어떻게 되세요? 아 여기 박신미로 63길. 잠시만요. 박신미로 63길. 네 뉴베스트빌 잠시만요 뉴베스트빌 네 아 여기가 전국시장 근처네요? 아 예 저희가 어떻게든 부축하려고 그러는데 아예 움직이지 못해서 어머니 뭐 최근에 코로나 관련해서 접촉했다고 문자 받거나 그런건 없으시죠? 네네 아 네 알겠습니다. 대원들 나가면서 전화드릴 수 있어요. 전화받으면 안내 좀 부탁드릴게요. 아 네 감사합니다. 네.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네 알겠습니다. 네 구급처 좀 불릴 수 있을까요? 네 주소 알려주세요. 저희 차 나가겠습니다. 강남구 성무 126주 네네 롯데캐슬 프레미어 아파트. 프레미어 아파트. 네네. 네네. 네 차 출발 시켰고요. 제작원님 선생님 어디 아프신 거죠? 위가 너무 아파가지고요. 위요? 네. 네 열나가는 코로나 증상은 없으시고요? 그저께 세븐아스에서 코로나 검사 배신증 증상 나왔고요. 열은 없으세요? 아니 열이 있어요. 열이 있어요? 네. 코로나는 음성 나왔고요? 네. 조만간을 나갑니다. 네. 감사합니다.
 네 119입니다. 말씀하세요. 말씀하세요. 여보. 네. 라이프 아파트인데요. 라이프 아파트요? 여기 몇 번지일까요 어머니? 저희가. 아 네. 건용 아파트 옆에 있는 거 맞아요? 네 네. 저기 미성 초등학교 바로 앞 맞은편에 있는 거죠. 미성 초등학교 바로 맞은편에. 예 무슨 일이세요? 네 네. 저기 라이프 아파트. 큰 태도로 아파가지고 등짝이 아파져가지고 지금 어떻게 할 줄을 몰라 해요. 어느 분이요? 저 저기 여기 동생이요. 아 그냥 지인분이요? 네. 여성분인가요? 네. 잠시만요. 등이랑. 아 등짝이 그래요 우선. 잠시만요. 지금 고급차가 필요한 상황이세요? 네네 그러면요. 라이프 아파트 몇 호죠? 예. 4개 갈 수 있는. 의식이랑 호흡 다 있으시고요? 네. 최근에 코로나 관련해서 뭐 접촉했다고 문자 받으시거나 그런 거 있으세요? 아니 그런 건 없어요. 아 허리 통증이요? 대원들 나가서 전화드릴 수 있으니까 전화 안내해 주시고요. 어 관악구에 지금 구급차가 없어서 독산동 쪽에서 나가느라 시간이 조금 더 걸릴 것 같아요. 양해 부탁드릴게요. 네 그럼 그쪽에서 오면서 이렇게 오시면 되겠네 우리 나이프는. 네 그냥 독산동 쪽에서 나갈 거예요. 네 그러니까 번호사로 들어가지 말고. 네. 아 일단 대한민국 전화 올 수 있으니까 전화 받고 안내해 주세요. 네. 네.
 1회 봅니다. 아 네 여기 마로니 공원점이거든요. 네. 그 어떤 출처하신 여성분이 저희 현장 밖으로 나가다가 넘어지셔 가지고 지금 좀 술을 많이 치우셨어요. 의식은 있어요? 지금? 네 의식은 있으세요. 근데 지금 혹시 뭐 피나거나 그런 데 있어요? 어 안면 쪽에 살짝 피가 나는 것 같긴 한데. 아 그래요? 혹시 일행분은 따로 없고 그냥 혼자 계신 거예요? 네 네 네 네 네. 아 그래요? 저희 9급대 간다고 그 환자분한테 얘기 좀 해주세요. 네 감사합니다.
 주택자이시잖아. 주택자입니다. 네 안녕하십니까. 여기 교통사고가 나서 다쳤거든요. 사람이. 사람 뭐라고 부딪친 거예요? 어 예 사람이 이제 집회 행진 도중에 그 주변 차하고 부딪쳤어요. 네 차랑 행진이랑 부딪친 거예요? 네네네. 사람이요. 환자는 몇 명이에요? 환자는 1명이고요. 아 의실 있나요? 네 지금 다리가 앉아 있습니다. 의실인 상태고 삼성병원 정문 앞쪽에 지금 돌에 좀 앉아 있어요. 아 그래요? 선생님은 관계 어떻게 되시나요? 아 지금 모르는 사람이에요. 아 그래요? 예 알겠습니다. 네.
 네 119입니다. 아 네 안녕하세요. 저희 아이가 그 요즘 출연이 너무 많아가지고 병원에 가서 이제 조사를 어 검사를 다 받았는데 오늘 아침에도 너무 이제 이 출연이 많아서 어 어지러움증이 너무 심하고 이래서 병원에 가서 수혈을 좀 받았으면 좋겠는데 병원을 갈 수 있는지요. 아 아드님 아이 그 어디서 키가 난다는 거예요? 아 그 위하고 대장하고 안 좋아서 계속 출혈이 있었거든요. 그래서 병원에 가서 위내시경 대장 내시경 받고 어제 병원에 갔을 때도 병원에서 수혈을 좀 받으라 그랬었거든요. 아 예. 너무 심하니까 근데 저희가 수혈을 못 받고 왔거든요. 아 근데 이제 밤 사이에도 계속 출혈이 조금씩 있어가지고 지금 너무 아이가 어지러움증이 있어서 네. 수혈을 받았으면 좋겠는지 좋겠는데 병원에 갈 수 있는지요. 아 그니까 병원 응급실 가보시러 가시는 거죠? 네 지금 그 아드님이에요? 따님이에요? 딸이요? 아 따님이 위랑 대장에서 출혈이 있고 지금 성향이 많아서 어지럼증 호수도 하시고 응급실 진료 못 드렸는 거죠? 네 그 주소 좀 알려주세요. 구급차 가서 확인 좀 해볼게요. 네 성산동 성산동 몇 층 몇 호로 가면 돼요? 지금 따님분 의식은 있어요? 의식은 있고요 일어날 때마다 너무 어지러워서 일어날 수가 없어가지고 선생님 무리해서 일어나지 마시고 넘어지면 다치시니까 다리 올리시고 누워계시고요 저희가 그쪽으로 구급차 가볼 건데 따님분 최근에 발열이나 코로나 관련 증상은 있으세요? 그런 건 없었어요 예 알겠습니다. 그쪽 구급차 가볼게요. 성산동 2 예.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 아 예 여기 앞에서 아 네 제 애기가 좀 높은 데서 떨어져가지고요. 어 계속 울다가 지금 그치긴 했는데 어떻게 머리를 좀 어떻게 액세지 좀 찍어봐야 돼서 응급 응급으로 가야 될 것 같아서요. 아 구급차 출동해서 병원 가보시겠어요? 알겠습니다. 주소 불러주시면 출동 나갈게요. 예 여기 신월동 신월동 예예 대운 노블 했어요. 대운 노블? 네에. 몇 호에요? 여기 오시면 저희가 내려갈 수 있어요 제가 엣지하고. 구급차는 신월동에서 인근에 구급차 있어가지고 금방 가고요 전화 오면 내려와 주시고. 네 네. 아이가 한 몇 개월이에요? 8개월이요. 8개월이고 코로나 관련해서 가족 중에 치료자 코로나 재택치료나 뭐 코로나 환자 있는 건 아니에요? 아 없어요. 다 2차까지 맞아서 예 알겠습니다. 출동하면서 전화 옵니다. 잘 받아주세요. 네 감사합니다.
 예 그럼 여보세요? 예 여기 금천구 시흥동 벽산 5단지 아파트 예 저 와이프가 혈신증이 있는데 지금 숨을 못 쉬고 있거든요. 지금 의심이 되게 힘들어요. 지금 예 의심이 있는데 지금 움직이지 못하겠다고 그러더라고요. 예 코로나 관련된 거 없으시고요? 예 없습니다. 예 벽산 5단지 예예예. 몇 주 발 앞 되요네?
 네. 119입니다. 예. 수고하십니다. 예. 오늘 자고 일어났더니 예. 어. 목이 아파서 침을 못 하시겠어요. 예. 그리고 뭐 기 있는데 여기서부터 막 흔들려요. 예. 그 병원에 갔더니 응대실에 갔더니 뭐 괜찮다고 네. 오늘은 진료가 없다고. 그래서 약방에 가가지고 또 뭐 해야 되나. 뭐 뭐 하는데 나 몸이 흔들리고 식은 땀이 나고 지금 죽겠어요. 예. 응급실로 가보시겠어요? 구급차로 보내드릴까요? 응급실은 뭐 안 된다니요. 호흡기 적어서. 예. 아휴. 제가 안 받는다고. 아 아프지 않겠어요. 돌아 눕지도 못하고 고기만 돌려도 아프고. 예. 어떻게 방법이 없나요? 아픈 거도 통증만 좀 가르쳐 드리면 좋던데. 예 저희가 해드릴 수 있는 거는 이제 응급실 이송하는 병원 이송하는 것까지 해드릴 수 있는 거거든요. 네 현재 은도실에서 그 여 매도 매도 병원에 갔는데 예 거기서 호흡기 저쪽이라서 안 된대요. 예 다른 데 격리 병실이 있는 곳으로 가실 수는 있으시거든요. 예예 좀 부탁드릴게요. 예 그럼 구급차 보내드릴까요? 예 조금 더 편 내려가 있을게요. 주소나 위치 말씀해 주세요. 아 주소가 아유 잘 모르겠는데 아 잘 모르겠네. 주소를 알려주셔야 찾아갈 수 있고 그렇지 않으면 찾아갈 수가 없습니다. 아유 어이 없이 으음 선생님 주소부터 확인하시고 다시 신고해 주시겠어요? 맞아요. 내가 내려가 있을게요. 무슨 동? 무슨 구 무슨 동? 예 신월 3동. 예. 예. 예. 그럼 그쪽으로 구급차 보내드리고요. 기침하고 열나고 코로나 증상 있으세요 없으세요? 기침은 없어요. 열나시는 건요? 열고 나서 그러면 목이 아파요. 목이 아파가지고 말을 못 하거든요. 네 알겠습니다. 고객님 잘 출동하겠습니다. 네 내려가 기다릴게요.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네, 예고입니다. 네, 그래서 혹시 그 2도 화상인 거 같은데 그 구속차가 가능할까요? 그 환자분이 남자예요? 여자예요? 남 접니다. 그 어디가 어떻게 아프세요? 지금 팔목에 거의 한 20cm 정도로 화상이 생겨가지고. 아 화상이요? 네. 그 주소 좀 불러주세요. 어 강남제로 84길. 84길. 며칠 몇으로 갈까요? 일단 내려갈 수 있을 것 같은데. 며칠 몇으로에요? 말씀해주세요. 네 아 네. 차 나갔고요. 그 병원 가시려고 전화하신 거잖아요. 네. 전화는 잘 받아주시고 본인 혹시 코로나 확진자거나 자가격리자는 아닙니까? 아닙니다. 아닙니다. 네. 알겠습니다. 기다려주세요. 혹시 뭐 올라오시나요? 그러진 않죠? 저희가 전화할 건데요. 전화하면은 그때 내려와 주시면 돼요. 아 네 알겠습니다. 네.
 안녕하세요. 선생님 119인데요. 지금 그 길에 남자 누워있어서 신고하신 건 거기가 대림동 잠시만요. 예, 예, 맞아요. 아 예, 알겠습니다. 지금 의식은 있으세요? 움직임은 있어요? 모르겠어. 눈 지나왔거든요. 아 이미 지나치셨어요? 선생님? 예, 예. 예, 알겠습니다. 그쪽 가서 확인해 볼게요. 그 네.
 예 지금 바로 불러드리겠습니다. 예. 예 119 입니다. 예 안녕하세요. 종로 이관지구대 경찰관입니다. 예예. 예 여기 지금 보호 조치 사건 나갔다가 지금 이마에 이마에서 출혈이 있으셔가지고 예 남성분이세요? 예 예 50대 정도 되는 남성분이시고 일단 응급처치는 해놨는데 지금 치가 계속 조금씩 흐르고 있어가지고 치료해보나서 예예. 이 종로 이가 지구대로 가면 되는 거죠? 예예. 알겠습니다. 예. 감사합니다.
 예, 예, 예, 예, 아버님이 지금 누워 계셨는데 돌아가신 거 같거든요. 예, 주소 알려주세요. 여기 동작구 사당 2동. 사당 2동. 사당 2동. 사당 우성 아파트. 우성 아파트요? 예, 사당 우성 아파트. 네, 아파트. 네. 네. 아버지 지금 꼭 없으시다는 거죠? 예. 잠시만요. 사당우성이에요? 예. 사당우성아파트. 잠깐만요. 아 아 아 아 아 아 제아 아파트 옆에 있는 데 맞아요? 거기 통신대역에서 쭉 올라오시면 되는데 상일초등학교 옆에 있는 거기 맞아요? 상일초등학교 예예예 맞아요. 거기 옆에 옆에 예 이쪽으로 차 먼저 출발하고요. 출발하고요. 응급처치 좀 연결할게요. 끊지 마세요. 아니 뭐 지병으로 치매로 누워계셨는데 호흡을 안 쉬는 것 같으니까. 응급처치 좀 연결할게요. 끊지 마세요.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 일일곱니다. 아 네. 어 85세 된 남자가 그럴 수 있는데요. 어 예예. 지금 산소 수치가 잡히지도 않고 아 지금 엄청나게 급하네요. 거기 주소 좀 불러주세요. 예예. 여기 상하 저 대동역에 상하 아파트. 네, 네.
 네, 지금 입니다. 아 예, 좀 환자가 있어서 그러는데. 응급실로 좀 가야 되는데 어떻게 해야 되죠? 누가 환자예요? 어 저기 딸이요. 딸이 어디가 어떻게 아파요? 배가 너무 꼬여가지고 어떻게 할 수가 없어요. 주소 좀 알려주세요. 어 성대로. 성대로 39개. 예, 예. 열이 나거나 기침 코로나 관련 증상이 있어요? 아 그 상황이 아니고 갑자기 배가 막기 틀린데요. 출동하겠습니다. 평대로 39개 네 네 네 네.
 일로 봅니다. 네. 여기가 여기 안 했어요. 여기 찾아서. 여보세요. 여기 그 자랑 좀 다쳐가지고 그러는데요. 누가 어떻게 다치신 거예요? 아 여기 할머니가 허리를 다쳤어요. 할머니가? 예. 할머니만 다치신 거예요? 허리를? 예예. 아 거동이 안 되시면 움직일 수가 없어요? 아 여기 뭐 우리 걷긴 잘 못해요. 아 그 가까운 응급실 쪽으로 모셔다 드릴 거고요. 계신 곳 주소나 위치도 알려주세요. 여기가 수색동. 아 옛날 주소가 수색동. 며칠 며칠 계세요? 세대가 1뿐이 없나요? 한 세대요 한 세대? 아 저희가 가까운 응급실 쪽으로 모셔다 드릴 거구요 지금 저 저기 동구 한 방 동안에 약을 짐 맞으러 가야 되는거 아닌지 짐을 맞으러 가야 되는거 같을거 같으니 저희는 응급실로만 이송이 가능해요 환자들 응급실 응급실로만 가요 응급실 가까운 응급실 쪽으로 모셔다 드릴 거구요 네 모든 출동권에 코로나 관련 질문 드리고 있어요 혹시 분들 중에 발열이나 고열 기침 아 코로나 증세 없으시고요? 확진자로 만나셨거나 자가격리하시는 분 안 계시죠? 아 대원들이 가면서 전화드릴 거예요. 그 앞에 있는 구급차는 집 근처에 계신 구급차는 딴 데가 나가서 지금 마포구 서교동 쪽에서 가고 있어요.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네 여기 을지병원 응급실인데요. 여기 여기가 아파서 그냥 왔는데 여기 병실에 코로나 그 검사 하니까 열도 나고 열이 조금 있고 호흡이 좀 안 좋다고 119를 타고 다른 병원으로 가라고 그러네요. 119를 타고 가라고요? 예, 아이고 예 원인이신 거예요? 환자가? 여기요. 저기 을지병원 예? 누가 환자라고요? 제가 환자인데요. 아 저희 뭐 일단은 알겠어요. 뭐 저희가 근데 병원 응급환자 이송 목적이어가지고 자세한 거는 가까운 데 뭐 일단 가는 거여가지고요. 네 우선 그냥 얘기해 보세요. 저희는 뭐 가까운 데는 을지병원이니까 또 그쪽에서 진료가 안 된다고 하니까요. 잘 가고자 응급대원한테 물어보시고요. 열나는 거 말고. 어떤 응급대원한테요. 지금 출동한다고요. 좀 진정 중이고 지금 열나는 거 말고 호흡기 증상이나 코로나 격리 중이신 거 있으세요? 없어요. 그런 거는요. 병원 앞으로 나오셔야 돼요. 여기 어디 응급실인데. 병원 앞으로 나오세요. 그 안에 못 들어가니까. 예. 예.
 119입니다. 아 네 여보세요. 네 말씀하세요. 네 그 과양 5단지인데요. 과양 5단지. 네네 여기 아저씨분께서 이제 넘으셔서 피해를 좀 흘리고 계시거든요. 몇 동아트예요? 잠시만요. 여기 몇 동이지? 정문아트예요? 아니면 예 동을 얘기해주시는 게 제일 정확해요. 잠시만요. 아프고. 남자분 낙상으로 얼굴 쪽에. 어 네네네네네. 계속 피가 나 흐르고. 의식은 있어요? 네네네네. 알겠어요. 그럼 앞으로 갈게요. 뭐 대화는 잘 되시는 거죠? 뭐 의식 없거나 이런 거 아니죠? 하고 있습니다. 취소했어요. 예.
 119입니다. 선생님 그거 주소 다시 천천히 불러봐요. 가양 구단지예요? 거기가? 선생님 잘 안 들려요. 네? 네 전화기 좀 가까이 대고 좀 얘기해줘요. 이게 무슨 일인데요? 예 저기 넘어져서 발가락이 이렇게 부러진 것 같아요. 누가요? 제가요. 본인이? 예. 발가락 엄지 발가락 아니면 어디 발가락이요? 아니요. 새끼 발가락 가운데 발가락이 풀려졌어요. 완전히 꺾였어요. 가운데 발가락이? 예. 예 알겠어요. 집에 혼자 계세요? 아니면 누구랑 같이 있어요? 아이 우리 손자 있는데 나 혼자 손자 집에 있을 거예요. 아니 그니까 문을 열어줄 수 있는지 없는지를 여쭤볼까요? 예 예 열어놓을게요. 문을 열 수 있어요? 네 아이 우리 예 시킬게요. 예 예 알겠어요. 거기 구두 단지에 예 예 알겠어요. 과연 구두 단지 네 그쪽으로 갈게요. 예
 119입니다. 여보세요. 119에요. 말씀하세요. 아 예 여기 경남 아파트인데요. 예. 예 저기 병원에 가려고 그러는데요. 은근씨 가실 거예요? 예 예 예 콧줄을 떼서. 경남 아파트 몇 동 몇 호에요? 누가 아프세요? 남자 여자에요? 여 남자분이요. 남자분이 콧줄을. 뺐어요. 예. 여기 경남 아파트. 빠졌다는 거죠? 예 콧줄을 뺐다고요. 예. 선생님 그래서 의식이나 그런 건 다 있어요? 예예. 경남 아너스 길이에요? 예예. 여기 요새 백화점 뒤에요. 아. 거기가 주소가 그러면 어떻게 돼요? 전지역? 경감 아파트. 전지역. 미화동이요? 예예 미화동 여기 롯데카 좀 뒤에 롯데카 좀 아시죠? 미화사거리. 잠깐만요. 롯데캐스 옆에 있는 거예요? 예 맞아요. 롯데캐스 가기 전이지니까. 그 옆에 있는 경남 안어스딜 맞아요? 예예 하늘 위엔아이 거기 옆에 있는 거? 예예예예예 맞아요 그 앞에 맞아요 거기 가운데 있는 거 네 코로나 관련 그런 증상은 없고요? 아 그런 건 없어요 네 차 나가볼게요 아 몇 시쯤 와요? 지금 출발해요 아 예 알았습니다 네
 예금주. 예 제가 얼굴에 피를 좀 흘려갖고요. 피를 좀 받으려고요. 예 고급차 필요하신 거예요? 다시 얘기해 주세요. 예? 다시 얘기하세요. 아 고급차 필요하세요? 아니요. 고급차 안 필요해요. 아 고급차는 필요 없고 저 뭐 의료 상담 받으시려고요? 아 구급대원 왔고 그냥 취소 좀 받으려고요. 아 그래서 주소 어떻게 되세요? 거기 봉천동. 예. 몇 층 몇 호요? 예. 아 얼굴에서 피가 난다고요? 예 제가 칼로 그었어요. 아 코로나 관련된 거 책은 없으신가요? 예 멀쩡해요. 예 알겠습니다. 네.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네, 고기다. 예, 저 응급차 좀 불러주세요. 네, 선생님 주소 먼저 알려주세요. 예, 여기 심정 7동이고요. 네. 예, 목동 우성 아파트. 목동 2차 우성이요? 예, 2차 우성 몇 동 몇 호요? 터져가지고. 근데 손을 비인 거예요? 유리를 깼는데. 아 이게 좀 쭉 배웠어요? 예 지금 막 피가 막 너무 많이 나서. 아 잠시만요. 예예. 차는 지금 보냈고요. 예예. 뭐 깨끗한 수건 있으세요? 그걸로 좀 꼭 눌러야 돼요. 뒤를 좀 세게 눌러야 돼요. 생각보다 세게. 아 지금 유리가 어디에 막혔는지 몰라서요. 어 일단은 그래도 좀 그래도 좀 막고는 계세요. 그 차는 보내셨으니까요. 그리고 선생님 혹시 집에 뭐 코로나 관련해서 격리하시는 분은 확진자이신가요? 그런 거 없으시죠? 네 차는 보냈고요. 어 한 1.5km 정도 떨어진 곳에서 차가 출동할 거예요. 기다리세요.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 예예. 예 저 119 사무실인데요. 차량은 가고 있는데요. 그러니까 주민센터 바로 앞으로 가면 되는 거예요? 예 주민센터에 오시면 돼요. 바로. 예 예 알겠습니다. 주민센터에 붙은 버스 정류장 배수실이 있어요. 거기에 있네요. 그니까 장이 그 버스 정류장이에요? 아니면 주민센터 앞에? 버스 정류장 주민센터 앞에가 버스 정류장 있어요. 바로 건너편이에요? 바로 앞이에요? 바로 앞이에요. 예 알겠습니다. 예예.
 네. 안녕하세요. 아 저기 애기 손가락이 눈에 힘겨서 좀 많이 다친 것 같거든요. 손가락 뺀 상태예요? 뒷가락은 뺐는데 손가락이 지금 간호대로 네. 주완에 변빌 네 알겠습니다. 지금 차는 방금 제가 출발시켰고요. 애기가 몇 살이죠? 네 한 살이에요. 돌 됐어요. 돌 아이고 지금 기침 같은 증상이 있었나요? 애기가? 아 없습니다. 지금 제가 무늬에 끼워가지고 손가락이 모양이 있어요. 네 알겠습니다. 가고 있습니다. 네.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네. 네. 1 2 5입니다. 아 예. 다리가 풀어졌거든요. 다리 골절이요? 다리가 풀어져서 길가인데. 네. 다리 골절. 위치 좀 가르쳐 주세요. 위치 좀 가르쳐 주세요. 위치 좀 가르쳐 주시고요. 여기. 강남구 어디 강남구. 예. 보이는 게 또 뭐가 있어요? 거 건물 이름이. 네. 호텔 호텔도 에이스라고 써 있어요. 호 호텔? 호텔도 에이스. 발 풀어져 가지고. 호텔 더 에이수요. 그리고 그 그 앞에고요. 그 본인이시고요. 발목 위에 발목 위에 발목 발 그 발 발 발 등이 깨졌어요. 발등요. 발등 발목 발목 발목 골등 그리고 그 최근에 기침하고 열나고 코로나 관련하고 의심할 만한 거 아 그런 거 없어요. 그런 거 그런 거 없어요. 선생님 저 혹시 그 근처에 뭐 편의점 같은 거 보이는 건 없어요? 저기요? 예? 아 여기 호텔 전화번호가. 네 호텔 전화번호가요? 위치 물어보시고. 예 알겠습니다. 예 알겠습니다. 예. 여기 여기 입구로 아주 뭐 딱 때문에 입구로 남았거든요? 예 알겠습니다. 가면 저 전화하면 전화 받으세요.
 네 안녕하세요. 여기 마포구 예 서교동 경사대 어디에 좀 그러세요? 예 어떤 분이 여기 오셔가지고 과호흡증이요? 과호흡증 그게 나와가지고 누워계시거든요. 그 건물 몇 층 앞으로 가면 돼요? 방구장이에요. 방구장? 아 그 서교동 네 네 경섭 1층 아 그 구급차량 가고 있는데 저희가 모든 수준권에 코로나 관련 질문 드려야 되는데 혹시 그 부분 환자분 대화 가능하시면 네 네 뭐 발열이나 고열 뭐 그런 증상이 있는지 없는지 확인 가능할까요? 발열이나 고열 같은 거 있어요? 아니요 그런 건 없어요 그냥 가오오칭이요? 네 네 가오오칭이 갑자기 생겨가지고 여기 잠깐 누워계시거든요 아 고급차랑 가고 있는데 제가 확인 한번 해볼게요. 아 거기가 VIP 당구장 맞나요? 네 맞아요. 아 예 알겠습니다. 대원들 가면서 전화드릴 수도 있으세요? 혹시 전화가 오면 좀 안내 좀 해주세요. 빨리 갈게요.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 Oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, Oh, yes. Hello, is there? Oh, yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. There's a lot of people who are not in the hospital. Oh, my God. I'm not hearing that. I'm not hearing that. I'm not hearing that. I'm hearing that. There's a lot of people who are going to go to the hospital. I don't know if they're going to get sick. I'm sure they're going to get sick. Yes, yes. I'm not sure. I'm not sure. I'm not sure. Ah, that's what I heard. It's not a virus. It's not a virus. Yes, it's a virus. Yes, it's a virus. Yes, it's a virus. It's a virus. Yes, it's a virus. Yes, it's a virus. Yes, it's a virus. Thank you.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 입니다. 지금 계세요. 여보세요? 예 말씀하세요. 예예 저 아이가 저 아이를 좀 옮겨야 되는데 아이가 옮길 수가 없어서 아이를 어디에서 어디로 옮겨달라는 말씀이세요? 예 저 지금 집 앞에 있는데 집 앞 차에서 집까지 집까지 올려야 되는데 올릴 수가 없어서 힘들어서 좀 도와줄 수 있을까요? 층 몇 호까지예요? 예예. 2동 도움 여친이고. 아이가 지금 어떤 상태인 거예요? 아 만취 상태에서 지금 일어나지 못하고 있습니다. 습지 상태신 거예요? 예예. 그 엘리베이터가 있긴 있는데. 아이가 몇 살이고 남아의 여아예요? 여자아이고 지금 스무 살. 스무 살 20세. 예. 예. 잠시만요. 일단은 지금 어디 아프신 건 아니세요? 예 아예 뻗어가지고 정신이 없어요. 아예 정신을 찾을 수가 없으니까. 의식 코 괜찮은지 좀 봐주세요. 의식이요? 예. 아예 없습니다. 아예 없어요? 의식이 없다는 말씀이시죠? 주신 상태로. 예. 예예. 잠시만요. 잠시만요. 숨은 잘 들으시는 줄 봐주세요. 예? 호흡. 호흡이요 호흡. 호흡이 있습니다. 예예예. 설아는 있어요. 주소지 어떻게 되세요? 여기. 잠깐만요. 강남구. 강남구 무슨 동? 논현동. 논현동. 앞이시고요. 예. 일단은 그쪽으로 구급차를 보내드렸어요? 구급차 보내드리고. 예. 아. 도움 요청 같은 경우는. 예예. 다른 곳에 이동 어, 도움 요청하시면 되고요. 지금 의미가 없다니까 구급차를 보냈어요. 예. 저희 대원들이 이송 여무를 파악할 겁니다. 예 알겠습니다. 고맙습니다.
 119입니다. 아 여보세요? 네. 아 지금 아 저기 성인이 지금 계속 토하고 그래가지고 병원 좀 가야 될 것 같은데요. 누가요? 아 저희 딸이요. 나이는요? 아 23살이요. 구토를 하세요? 네. 주소 어떻게 되세요? 저희가 개봉로 잠시만요. 아 여기 주소가 있어요. 그 분? 잠시만요. 대공동? 네. 네. 네. 몇 층 몇 호요? 열은 없어요? 네 열은 없어요. 진풍물 열 없고 구토만 하시는 거예요? 네. 전화 보냈고요. 코로나 격리자일 거나 확진자일 거나 가족분들 중에. 아니요. 없어요. 저희 다 3차까지 맞았거든요. 영수아 A3 맞아요? 네. 네. 네. 기다리고 계세요. 네.
 네. 안녕하십니다. 예. 안녕하세요. 네. 아 저희 어머니께서 조금 건강이 많이 안 좋으셔가지고 어머니께서 거동이 안 돼서 1일 9로 문구실로 가야 되는 상황인 거예요? 예. 문구실 조금되세요 어머님이신 곳. 예. 어머니가 지금 손톱이 파래져요. 네. 손톱이 파래져요. 조금되세요. 여 서울시 동작구. 네. 어 달맛하게. 예? 알마타길. 알마타길이요? 알마타길. 알마타길. 현대 2차 아파트. 현대 2차 아파트요? 예. 저쪽으로 저쪽으로 하고 싶은데. 대방 현대 2차 아파트 말씀하시는 거예요? 예예예. 아 대방동. 예에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에에 아파트 맞죠? 의료진 연결할까요? 끊지 마세요.
 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네 지금이요? 제가 그냥 간이 아 1번 병원 갔던데 간이 그 병원이 문 안 열어서 간이 치료했는데 지금 너무 뭐 기침이 나고 아파 죽겠어가지고 어디가 기침 나고 어디가 아프신 거예요? 저 발목이 양쪽 다 아작났거든요. 아 언제 사고 나신 거예요? 저 그 주말 전에 사고 난 거라 치료를 제대로 못 받았어요. 며칠 전에 사고 났어요? 며칠 전에? 그래서 가톨릭 서무병원 가서 코로나 검사 결과가 있어서 아마 거기에 오실려나 갈 수 있을 것 같아요. 선생님 코로나 검사는 며칠이 지나면은 저기가 떨어져가지고요. 다시 다 해야 되고요. 일단은 병원은 대원들이 선정하게 돼 있고요. 예 가서 환자 상태 확인하고 병원 선정할 거고요. 일단은 따로 뭐 열이거나 그런 건 없으신 거죠? 열은 전혀 없는데 지금 지침할 때마다 이게 피스코트 사고 때문에 갈비뼈가 아프고요. 그냥 발목 양쪽 발목에 제가 지침할 때마다 173차까지 마쳤어요. 몇 점 들어오게 있어요. 네. 알겠어요. 차 보낼게요. 네 감사합니다.
 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 무엇 우리가 어 현관으로 내려갈게요. 아 지금 머리가 아파서 병원을 간다는 거고. 예 예 응급기업. 코로나 관련해서 열이나 기침 이런 증상이 있었나요? 아 그런 건 아니고요. 찐 것 같아요. 찐 거. 아. 극 찐 것 같아요. 예 예 알겠습니다. 예 예 예.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 예, 일곱니다. 네, 저 아기가 열이 너무 많이 나서. 네, 지금 구급차가 필요해요? 아니면. 네, 네, 구급차가 필요해요. 몇 살 아이죠? 어, 8개월이요. 5월생이요. 어, 체온 체온 체온은 몇 도예요? 지금 잠시만요. 대충 조금 전에 마지막에 있던 체온이. 아, 지금 39도 이래요. 99도 의식 같은 건 괜찮고요? 어, 많이 처져요. 지금 열이 난 지가 6시간 이상 됐거든요. 의식은 있는 게 처진 거예요? 의식은 있어요. 네, 네, 의식은 있어요. 주소는요? 주소는 어 한신무학 아파트? 무슨 아파트요? 한신무학 아파트? 한신무학? 예. 네. 그 무화초등학교 바로 옆에 있는 그 단지이세요? 네, 네. 맞아요. 자, 아예 차 나가면서 전화드릴 수 있고요. 다른 가족분들은 뭐 코로나 관련된 기침 보율 같은 증상 뭐 여행료 같은 거 없으신 거죠? 네, 전혀 없어요. 네, 그 정도 나가면서 전화드릴 수 있으면 전화 잘 받아주세요. 네. 네. 감사합니다.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 실례합니다. 무슨 일이세요? 아 아기가 아기가 어제 저녁에 열 열이 났어요. 네 지금 선생님 구급 처비를 하신 건가요? 아 네. 구급 처비를 아기 지금 병원에 가려고 신고하신 거예요? 선생님? 네 네. 네 지금 아기 상태가 어떤데요? 아 지금은 열이 났어요. 열. 열 맞나요? 아님 경련을 했어요? 연이 나고 토 토해요. 자꾸 토해요? 연락 아기 연락을 자꾸 토해요? 위치 좀 알려주세요. 연이 나고 토해요. 집 주소 집 주소. 아 집 주소요? 네. 서운지? 네. 땅겄구? 네. 한청로? 한청로 네. 166길. 166길인가요 선생님? 네. 네. 네 몇 층이신가요? 골든 그랜드비 맞아요 선생님? 네 맞아요. 몇 층이세요? 네 1요 1. 아 단독이에요? 네. 골든 그랜드빌이고 단독이에요. 선생님. 네, 네. 알겠습니다. 그쪽으로 고급차 보내떠 거고요. 선생님 혹시 아기 뭐 학생자 접촉하거나 코로나 격리 중이거나 그런 건 아니신 거죠? 어 그거는 애기가 어린이 집을 다녀하고. 어머니 어머니 뭐 보건소에서 문자 받거나 그런 거 있으세요? 아 없습니다. 학생자 접촉했다 문자 받은 신자 코로나 검사하거나 그러신 적 있으세요? 아 그거는 저기 언니들이 학교에서 뭐 언니가 애기가 언니 있어요. 언니가 학교에서 뭐 코로나 접속하는 거 검사하는 것도 있어요. 그니까 애기는 학생자를 접촉하거나 자가 격리라는 그런 문자를 받은 적이 없다는 얘기신 거죠? 아 네 네. 어머니도 아니신 거죠? 네 네. 저희 일단 구급차 출발했고요. 선생님. 지금 주변에 구급차가 없어서 구본구에서 차가 가요. 차 좀 시간 걸릴 거고요. 선생님. 네. 전화 잘 받아주세요. 이 번호로 전화할게요. 네, 네. 혹시 외국인이신가요? 선생님. 아 네, 네. 네, 한 번만은 잘 알아 다 알아 듣는 거죠? 선생님. 네, 좀 알아 들어요. 네, 알겠습니다. 선생님 구급차 가면서 전화할 거예요. 전화 잘 받아주세요. 네, 네.
 네 알겠습니다. 저희 집이 여기 S 아파트. S 아파트? S요? 무슨 일이세요? 네 근데 저희 할머니가 지금 셀리가 목에 걸리셔가지고 쓰러지셨거든요? 셀리가 목에 걸렸다고요? 네 근데 지금 의식이 없으셔서. 숨으셔요? 아니요 아니요. 지금 입술도 막 까맣게 변하시고. 지금 지금 응급처치 안나올까요? 전화 끊지 마세요. 네. 잠시만 전화 끊지 마세요. 차도 안 오고 있어요. 엄마 울지 마 엄마 울지 마.
 네, 여기 경찰관인데요. 그 강남역 강남역 10분 출구에 파고다라고 써있는 건물 있어요. 거기 앞에 그 실제하신 분이 호흡불로 호소하고 있거든요. 여성분인가요? 아 그거는 그걸 몰라요. 지금 제가 이동하고 있어서 거기로. 무슨 건물이라고요? 잠깐만요. 잠깐만요. 뭐 좀 쳐볼게요. 네, 이 분이요? 남도로 있습니다. 네, 남도입니다. 남자분이시고요? 건물 건물 이름 다시 한번 말씀해 보시겠어요? 파고다라고 써있고. 파고다? 파고다 그 부지 있는 건물. 파고다 어학원이네요. 파고다 어학원. 파고다 어학원. 외벽에 빨간색으로 크게. 아 그래요? 지금 뭐 의식은 있나요? 선생님? 의심은 있는 거 같아요. 쓰러져 있는 분이시고? 네네. 아 예 알겠습니다. 예 수고하세요. 네.
 네, 제가 너무 아파서. 어디가 아프세요? 제가 아픈데요. 네, 네, 아무것도 못하고. 어디에 위치가. 네, 여기. 예. 주소를 다 말씀드렸을까요? 네, 네, 도봉구. 도봉구예요? 예. 네, 도봉구 창사동. 창사동. 주공 아파트 17단지. 아 창동지공 17단지예요? 예. 코로나 진단받거나 그런 증상은 있고 그런 건 아니죠? 알았어요. 그 복지자 보내드릴게요. 그쪽으로.
 예, 수고하세요. 나 저 저 앞에 여기 저 앞에 현실이 나오지 택시가 없어가지고 병원에 갈라 그래. 꼰대 병원에 눈 붙지. 아 선생님 어디가 아프세요? 눈 때문에 아까 넘어져가지고. 아 눈썹 찢어졌어요? 아니면은 티가 나요? 티 나고 찢어 보이지도 않아요. 예 선생님 거기 앞에 뭐 근처에 보이는 뭐 편의점이라든지 뭐 상가라든지 보이는 거 하나만 불러주세요. 편 편의점 28시 대림 아파트 서울숲 서울숲 대림 아파트? 네 편의점 앞에 편의점 이름이 뭐예요? 이제 편의점 뭐라고 해요? 이름 편의점 이름 뭐 CU 편의점 DS 편의점 네? 편의점 여보세요? 네 119인데요. 거기 위치가 편의점이 있다고 하는데 어디예요? 예 전임 아파트 저 예. 건너편은 아니고 예예예 예 알겠습니다 예 지금 지금 다 같이 나와 기다리고 있습니다 예 출동했습니다 예 기다리고 있습니다
 네 여기 신나 동 서울의료거든요? 응급실 성함을 안 받은다고 해서 제가 지금 전화드렸어요. 국가운데 있어요? 서울의료원 인근에 다른 응급실 문의해 보시려는 거예요? 예 그거 119 좀 보내주면 좋겠네요. 무슨 일이신데요 선생님? 속이 안 좋대요. 뭐 택시 타고 이동이 안 되시는 상태예요? 좀 어지러울 게 있고요. 그니까 그 서울 의료원까지 어떻게 가셨어요? 선생님? 집 앞이요. 아 그니까 거기까지 걸어서 가신 거예요? 예예. 아 근데 다른 병원까지는 못 가실 컨디션이에요? 선생님 그러면? 예예. 요 속이 안 좋아서 어지럽고. 네 서울 의료원 응급실 앞에 계신 거고 남자분이 여자분이에요? 예. 응급 병원요. 응급. 여 서로 전문적으로 들어와 있어요. 병원 앞에 안으로. 아 그니까 전문 쪽에 계시다는 거예요? 여기 전문이죠? 예예. 그니까 그 아프신 분이 남자분이에요? 여자분이에요? 예 30대 중반이요. 그니까 남자분이에요? 여자분이에요? 남자요. 30대 남성분이신 거고 어지럼증으로 응급실 가보신 듯이 거동이 힘드신 상태인 거죠? 예예 또 속도 좀 안 좋고요. 아 잠시만요. 예 그쪽으로 구급차 가볼 건데 환자분 최근에 발열이나 코로나 관련 증상이 있으세요? 아니요. 그런 일 없어요. 아 예 알겠습니다. 그쪽으로 구급차 가볼게요. 네에 밖에서 서 있을까요? 아 예 출동 때 전화하라고 할게요. 전화하면은 그때 말씀해 보세요. 네 알겠습니다. 빨리 좀 부탁해요. 아우 가고 있어요. 네에. 네에.
 1.9입니다. 고척 이동에? 네. 어머니가 어제 말에 또 괜찮으셨는데 오늘 아침에 의식은 있는데 말도 못하시고 보포에 가스가 찬 것처럼 배가 계속 불러오고 있거든요. 아 그래요? 선생님 그 몇 층 몇 호예요? 거기? 어머니 혹시 지금 열나거나 감기 증상은 없으세요? 네. 허핀받거나 정리상은 아니시고요? 네. 엊그저께 지금 고대병원에서 심장 쪽으로 좀 안 좋으신 것 같다고 진료받아야 될 것 같다고 검진은 받았거든요. 네. 그것 때문에 그런 건지 지금 계속 멍허하시거든요. 말을 못한다는 게 말씀하실 때 말이 어눌하다는 거예요? 아니면 대답을 좀... 아예 대답을 못하세요. 그래요? 부르면 쳐다보기는 하신다는 거죠? 예, 눈으로는 보시는 거 같은데. 지금 혹시. 선생님 공사 나갔고요. 그 병원 갈 준비하고 기다리세요. 네. 병원 갈 준비하고.
 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 몇 층이에요? 네 나삼민찬 맞아요? 네네네 빨리 와주시지 전화 끊지 마세요 전화 끊지 마세요 응급처치 안내할거에요 전화 끊지 마세요 네 네 네 잘 안하고 있어요 빨리 와주시지
 예, 입니다. 네, 여기 오늘 손님이 뭐 일부러 달라고 그러는데요. 손님이요? 예, 선생님 남성분이세요? 어떤 분이세요? 어, 남성분이요. 남성분이요? 어디가 안 좋다 그러세요? 어, 목에서 뭐 피곤하시는 거 같은데? 목에서요? 토요일하고 있어요? 지금? 네, 여기 여기 주소가 어떻게 돼요? 거기? 여기 도봉구 잠깐만요. 강복구 도봉로. 이 사은거 뭐에요? 시음이요. 시음. 시음. 시유. 알겠어요. 1층에 있는 식당이에요. 네네. 1층. 알겠습니다. 네.
 네 수고하십니다. 저기 저희 어머님이 지금 엄청나게 심하게 취하신 건데 취하신 정도가 좀 취한 정도가 아닌 것 같아서. 지금 엄청나게 이제 뭐 다 토하를 토하시고 지금 가슴이 아프시다 그래가지고 병원에 좀 가보자 그래서. 계신 분 주소 어떻게 되세요? 예 그 대방동 대림 아파트. 같이 계시는 게 아니에요? 아 같이 있어요. 잠시만요. 대방 아파트. 대방 대림 아파트? 대방동 아파트 대방 대방 대림 아파트 대림 아파트 몇 장 몇 초요? 네 네. 그쪽으로 차 보내드리고 있고요. 기침이나 열 목구멍 통증 같은 코로나 증상은 없으세요? 네 그런 증상은 없었어요. 이게 많이 아세요? 백신은 다 맞으셨어요? 그게? 네? 통증 위생인지 얼마 지나셨어요? 예 지금 한 2 3시간 됐는데요. 음식 먹고 토하셔가지고 근데 토하건 게 뭐 안에 속이 다 개워내셨는데 한 4시간 정도 걸렸어요. 한 통해서 가고 있고요. 전화 주신 거 아직 받으시고 통통에 받으실 거 좀 연결 좀 할게요.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네. 119입니다. 네. 수고하십니다. 다른 뭐 어머니가 좀 그 통이 있고 좀 많이 아프셔서 네. 네. 네. 네. 응급실료를 좀 받아야 될 것 같아서요. 고급차 필요하세요? 네. 네. 네. 네. 네. 주소 알려주세요. 네. 동승동 예. 네. 예린빌라입니다. 예린빌라. 몇 도세요? 열 나세요? 열은 없으신 것 같고요. 어제 저녁부터 이제 좀 복통이 조금 쉬다 그러고 그래서 화장실을 그 수는 좀 어려워 하셨고 예. 연세는 204이시고요. 네. 코로나 관련해서 특이사항 없으시죠? 코로나 관련된 그런 증상은 좀 아닌 것 같고요. 최근에 뭐 접종하시기 한 2주 정도 되셨는데 그들이 약간 컨디션이 좀 조화된 부분이 좀 있으셨거든요. 예. 고고차 보내드리겠습니다. 네 감사합니다.
 네, 수고하셨습니다. 저희 그 저는 이제 그 저 생활지원사 그 복지의 생활지원사라고 하는데요. 복지의 생활지원사요? 네. 네. 어 제가 이제 그 도서는 어르신 중에 이제 그 남자분이 계시는데요. 네. 그 그분이 이제 좀 전에 연락이 온 거예요. 이분이 에 주소는 한천로 동대봉구 한천로 38 다길 한천로 다길 그 장안 2동이죠? 네 거기 이제 그런데 이 암흑은 걷지를 못하고 잠을 툭 못 자고 골수염이 수암마비인데 다리가 넘어져서 다리가 이게 원래 수암마비에요 다리가. 치료를 쭉 받아들어 다녔는데 관절도 너무 심하니까 머리 검사가 거의 엎어질 뻔했나 봐요. 걷지를 못하고 속이 너무 통증이 심하고 그 다음에 잠을 전혀 1틀 동안 잠을 못 지무셨대네요. 응급실 가시는 거예요? 네 그 추우고 좀 떨리며 오나 봐요. 이번에 원래 청년 성실 병원에 다녔거든요. 청년 성실 병원에 그 내과 그걸로 다녔는데. 자세한 거는 제가 여기서 다 처리해두기는 어렵고요. 일단 필요하시면 그 혹 때문에 보내드릴 거고요. 네. 네. 그 분이랑 한번 통화하시면 뭐 자세한 거 병원이나 이런 거 얘기하시면 되고요. 네네. 전화번호. 기침 감기 증상이나 코로나 격리 중이신 건 아니시죠? 그거는 없어요. 3차까지 제가 다 받을 거 같아요. 어르신 그 성함이랑 문의시고 네네네. 네. 저희 구급변 보내서 확인할게요. 전화드리는 경우 있으니까요. 전화 오면 잘 받아주시고요. 예 감사합니다. 네. 부탁드리겠습니다. 네.
 네, 여깁니다. 네, 저 여기요. 어 롯데캐슬 알고 롯데캐슬 몇 등 몇 해요? 네, 근데. 무슨 일이세요? 아 미리 말씀드릴게요. 먼저도 왔다가 그냥 가셨는데. 네. 코로나가 아니거든요. 네. 지금 얘가 위에 호수를 꼽았는데 그 호수가 막혀가지고 어 저 삽입을 못해 아무것도. 음식물을. 그래서 지금 응급실에다가 전화를 하니까 응급실에도 내일 모레 월요일 날에 내야 된다고 우선 와가지고 상황을 보고 곧줄이라도 키워야 된다고 하니까 데려오락 하긴 데려오락 하거든요. 예를 통합에 원해서. 지금 코 튜브가 빠진 상태신 거예요? 빠정 빠진 거예요? 아 코 주브가 빠진 게 아니고 얘가 위로 삽입을 해놨어요. 아 위에. 코 주브는 아니었고 그러게 그 위에 삽입했는 죽이 막혔어요. 지금. 그래서 가가지고 막힌 거는 원래 오늘 못한다고 그러고. 네. 코로나 코로나 도 치워가지고 음식을 섭취시켜야 되잖아요. 아 그래요? 지금 코로나 관련해서 열이나 기침 호흡 관련 같은 건 없어요? 그런 거는 없어요. 저는. 자가 경기증 아니시고 확진자 아니시죠? 네 자가 경기증 없고 예 지금 다 저 독감도 맞고 로테캐슬. 선생님 제 말 들어보세요. 그 로테캐슬 아이비 아파트 맞아요? 네네. 로테캐슬 아이비 아파트 네 고맙습니다 선생님 네
 119입니다. 말씀하세요. 예 여보세요? 예예. 여기요. 길동이에요. 예. 여보세요? 네네. 예예. 그 계단에 내려가다가 여기 조금 넘어졌는데 눈 좀 위에가 좀 찢어졌어요. 아 구급차를 바로 보내드리면 되는 거예요? 예예예예. 또 어떻게 되세요? 여기가 강동구 길동. 예. 마산 아구찜이요 아구찜집 앞으로 가면 되는거죠? 네 네 뭐 앞에 있어요 아 네 남자분이에요? 여자분이에요? 남자분이요 아 넘어져서 지금 눈썹 쪽이 찢어졌다는거죠? 네 네 눈 찢는 데 찢어져가지고 찢어야 될거같아요 네 알겠습니다 네 네 네 네

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네 그 혹시 네 안녕하세요. 네 그 집에서 넘어졌는데 그 턱 쪽이 다 찢어졌 턱 쪽이 좀 찢어졌거든요. 네 근데 이거 지금 응급실 가야 되나요? 출혈이 좀 출혈이 피가 좀 나서 아 턱에 걸려서 넘어졌는데 네 혹시 여기 많이 찢어졌으면은 좀 그 봉합을 하셔야 될 것 같은데요. 그 구청 좀 보내드릴까요? 그럼요? 네. 예. 주소가 어떻게 돼요? 주소는 여기 도봉구 도봉로 121 빌라. 그 세월. 세월세빌라요. 네. 세월세빌라 몇 호예요? 환자는 남자분의 여자분이에요? 남자요. 예. 지금 의식은 있고요? 네네. 그냥 찢어졌는데 이게 응급실을 가야 될 거고 제가 가야 될 거 같아서요. 아 예. 그 코로나 장학연이나 확진 관련된 건 없으시죠? 네네. 네. 알겠습니다. 수고할게요. 네. 예.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 아 현대 오일 뱅크에 부탁드릴게요. 119 사항입니다. 말씀하세요. 네 안녕하세요. 본국사 옆에. 예. 119 아 뭐냐 본국사 옆에 현대 오일 뱅크 있거든요. 현대 오일 뱅크요? 네 거기 건너편 횡단보도 건너시면. 예. 사람 한 분이 술 드시고 거기서 주무시고 계시는데. 모르는 분이 있다는 거죠? 네 저희 차판에서 본 거라. 아 지나가셨어요? 네 지나갔는데. 옷차림이 어때요? 일단 패딩 입고 계셨는데. 무슨 색깔이에요? 검정 색깔이요. 아 남자분? 네네. 아 예 가보라 그럴게요. 감사합니다. 네 감사합니다.
 여보세요? 여보세요? 네 선생님 말씀하세요. 이태원 있는 크라운 호텔 이태원 크라운 호텔요? 무슨 일이신데요? 선생님? 제가 너무 아프고 옆구리가 아우 어우 본인이 그러신 거예요? 선생님? 네 알겠습니다. 그 지금 옆구리하고 옆구리가 많이 아프시다고요? 옆구리가 한 2시간 전부터 너무 막 찢어지게 아파요. 네 알겠습니다. 그럼 뭐 이전에 뭐 같은 증상으로 병원 치료받은 적 있어요? 아니요. 없어요. 이번 처음에 이제 갑자기 그러신 거예요? 예 알겠습니다. 그 고급차 갔고요. 제가 1가지만 더 물어볼게요. 최근에 기침가래 콧물이나 코로나 관련해서 뭐 확인받았다거나 그런 사항은 없으시죠? 예 알겠습니다. 고급차 가면 또 전화드릴 수 있으니까 모르는 전화도 잘 받으세요. 네.
 아 여보세요? 아 예 선생님 119입니다. 네 네. 예 구급차가 거의 도착했는데 혹시 선생님. 예 예 예. 이죠? 네? 아니시죠 혹시? 아 아닌데요. 아니 아니죠? 예 아니 그 옆에 동에서 또 신고가 또 들어온 게 있어서 혹시 확인하라고 전화드렸거든요. 아 예 예. 고급자 통과하입을 시작했습니다. 아 예. 예.
 네, 12입니다. 말씀하세요. 아 예, 저도 뭐 저기 남자분 1분이 이 길거리에 주무셔 가지고요. 길거리에 쓰러져 있어요? 예, 예, 예. 혹시 의식이랑 호흡은 있을까요? 아 그냥 이 이 쓰레기 해갖고 주무신 거 같은데. 아 네, 알겠습니다. 주소 어떻게 되죠? 여기가 그 가마산로. 가마산로. 예예예 주유소 앞에 예예예 주유소 앞이요? 네네네 네 알겠습니다. 전원길 나가볼게요 예 한번 나와보세요
 119 입니다. 무슨 일이세요? 여보세요? 네 말씀하세요. 119에요. 그 허리 일어나자면 허리가 좀 안 좋은데. 본인께서요? 예 그래서 택시 타고 가려고 그러는데. 예. 허리가 힘이 안 들어가서 허리를 못 서서. 고정도 안 되시겠네요? 아 조금 조심스러운데 혹시요. 몇 시에선 거 주소지 어떻게 되세요? 여기 강진구. . 거기 몇 층 몇 도에 계세요? 강진파크 프라이빗인데요. 잠시만요. . 예 그 1층에 혹시 제가 내려갈까요? 잠시만요. 일단은 지금 차를 편성해서 보내드렸고요. 예, 정말 죄송합니다. 고통 자체가 힘드시면은 혜택에 계시는 게 낫고요. 기침이나 열 목포 폭증 같은 코로나 증상은 없으세요? 예예. 문 좀 열어놓고 좀 기다려주세요. 살짝. 예예. 문 열어주실 분 있으시죠? 예, 문이 있는데 아니면 연락 주시면 제가 문 열어드리면 안 될까요? 2.5km 떨어진 곳에 가니까 대원들이 가면서 전화 드릴 거예요. 전화 잘 받아주시고요. 네 감사합니다.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네, 봅니다. 아 저기요. 네, 네. 네. 어 여기가 지금 잠시만요. 네. 네. 삼성 쉐르빌. 삼성 예. 삼성 쉐르빌. 누가 아프세요? 아 남편이 자꾸 숨이 안 숨이 안 쉬어진다고요? 네 네 원래 지병 있으세요? 아니요 없어요 백신 맞으신 건 아니고요? 네 의식이나 의식 괜찮으시고요? 열 없으시고요? 네 열이나 코로나 관련 이력 없으시고요? 예 지금 그부터 수강하겠습니다.
 일렉입니다. 아 네 여기 그 중랑구 상봉동. 네. 지금 넘어져가지고 머리가 여기 뭐야 피어나가지고. 선생님 본인이에요? 같이 본인? 아니요. 저 동생이요. 남자 여자요? 여자예요. 의식은 있어요? 네? 의식은 있어요? 아 지금 아니요. 그냥 이렇게 지금 지금. 숨으시고 있어요? 네 숨고 넘어졌는데 여기가. 뭐 복도에 계세요? 아니면 뭐 집 안에 들어가셨어요? 집에 집에. 복도예요? 어 그냥 1예요. 선생님 일단 그쪽으로 보호차 보냈고요. 환자분 감기 증상에 번호 확신단 아니에요? 네 아니에요. 네 보호차 보냈습니다. 기다려주세요.
 네. 1 6 9 입니다. 말씀하세요. 아 지금 저희 어머님이 네. 어 이속주인 있으셔서 지금 어지러우셔 가지고 못 일어나시거든요. 아 지금 구급차가 필요하신 상황이세요? 예. 구급차 좀 보내주셨으면 해서요. 미성 아파트. 잠시만요 미성아파트 여기가 하계역 앞에 있는거 맞죠? 공구 하계동 잠시만요 여기가 장미아파트 건너편에 있는거 맞죠? 네네 어머니 의식이랑 호흡도 있으시고 최근에 코로나 관련해서 뭐 기침 콧물관계 의심증관나 그런 거 없어요. 예예. 접착했다고 문자 받으신 거 없으시죠? 예예. 아 계연들 나오면 전화드릴 수 있으니까 전화 받으러 안내 좀 부탁드릴게요. 얼마나 걸릴까요? 음 여기 바로 앞에서 나가요? 한 1.5km 정도 떨어져 있거든요? 여기 노관 소방서에서 바로 나가니까 얼마 걸리진 않을 거예요. 아 네 알겠습니다. 네.
 네. 안녕하세요. 혹시 그 역삼동 좀 알려주실 수 있겠어요? 무슨 일이신데요? 아 제가 친구랑 술을 먹었는데요. 네. 그 친구가 이제 한 40분 동안 길꼬리 썰어라 했었나 봐요. 네. 그니까 뭐 의식이 있는 상태고. 네? 근데 한 의식은 있는 상태고요. 네. 근데 이제 추운 겨울에 한 40분 동안 써져 있어서 건강 상태가 좀 이제 모르겠어요. 제가 지금 저도 뭐 가고 있는데 제보를 받아서 가고 있는데. 네. 그 혹시 그 응급차 1만 좀 보내주시겠어요? 부분이 아프신 거예요? 아니 그게 아니라 40분 동안 술 취해서 한 40분 동안 쓰러져 있었나 봐요. 네. 그니까 건강 상태 그니까 술 취해서 지금 이렇게 숨을 쉬는데 어 좀 응급처로만 보내서 그 의식 상태를 좀 봐야 되겠습니다. 이렇게 좀. 지금 옆에 계신 거예요? 아니 지금 저는 가고 있어요. 제보를 받고 그 친구를 좀 확인하려고 가고 있어요. 옆에 누가 계신데요? 어 뭐 아는 사람이 제보를 해줬어요. 아는 사람이 그냥 네 친구 아니냐고 이러면서. 네. 그분 응급실에 가실 거예요? 아마 혹시 안 되면 가야 될 것 같고 아니면은 이제 뭐 확인만 하시면 될 것 같은데 그래도 뭔가 앰부런스가 좀 있어야 될 것 같거든요? 위치가 그러면 강남 강남구에. 예. 역삼동. 뭐요? 사기 맞나요? 어 어 어 맞아요 몇 층이요? 그 길꼬리 있어요. 길꼬리 그냥 아 도로상이요? 네 남자 여자에요? 남자입니다 남자분이 길에 쓰러져 있다고요? 응 네 네 전화번호 어떻게 있으세요? 네? 선생님 전화번호 말고요. 거기 현장에 있는 전화번호요. 이거 제가 지금 현장에 한 5분 안에 도착하니까 더 빠를 거예요. 네. 저희가 현장에 있는 분하고 통화해서 형태를 확인하려고 그래요. 제가 그 생명의 번호 주는 번호를 잘 몰라요. 모른다고요? 네 알겠습니다. 전화 잘 받아주세요. 그럼 선생님.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 안녕하십니다. 예 여보세요. 네. 예. 상대동 청암 아파트인데요. 상대 3동. 상대 3동에. 예. 청암 아파트. 청암이요. 청암. 청암. 청암 아파트. 네. 예 아버지가 호흡 확인 해주시다고 앰뷸러스 좀 불러달라고. 예 몇 호세요? 저기. 청암 아파트. 예 아버님 호흡볼란 있으시고 대화는 가능하세요? 예 대안은.
 네, 일곱니다. 네, 죄송해요. 우리가 급한 일은 아닌데요. 네, 네. 우리 아저씨가 70이 좀 넘었는데 네, 한 열흘째 변을 못 봐가지고 너무 힘들어해서 약국에서 있는 건 다 써봐도 안 돼가지고요. 아 병원에 가보시고 하시는 거죠? 네, 근데 거기 제가 어떻게 혼자 움직일 수가 없어서 좀 아 그래요? 주소 좀 알려주세요. 고창 2동. 네. 네 몇 층 몇 도세요? 그냥 마당이 있어요 마당으로 예예 혹시 코로나 관련해서 열이나 기침 호흡곤란 같은 건 없어요? 그런 건 없어요 그런 거 없고 자가격리증 아니시고 코로나 확진자 아니시죠? 네 정확히 아니에요 네 알겠습니다 구급차 보냈습니다 선생님 우선 죄송해요 그 차를 1일 9차에 우린 휠체어를 태울 수가 있나요? 어 좀 글쎄요. 장소가 좀 협소해서 쉽게 좀 어려울 것 같은데 그 7동안 고객단들한테 한번 말씀 좀 한번 해보세요. 네 알겠습니다. 감사합니다. 네.
 네, 여보세요? 예, 여기. 하여 아파트. 예. 예, 무슨 일이세요? 아, 지금 병원은 가야 되는데. 예, 누가요? 선생님. 누가 어디가 아픈 거예요? 아, 확실히는 모르죠. 어떻게 아는지. 누가 아픈 건데요? 누가. 어르신이요. 뭐 아버님이신 거예요? 예. 증상은요? 확실히 몰라요. 가봐야죠. 의식 있어요? 없어요? 잘 움직이질 못하시니까. 의식은 있어요? 그냥 그냥 쪼하고. 의식은 있다는 거예요? 확실히? 예. 어디가 아픈지 모르신다는 거예요? 말씀을 안 하세요? 아버님이? 예? 아버님이 말씀을 안 하시냐고요? 아 확실히 모른다고요. 혹시 코로나 같은 증상 없어요? 열이나 기침 호흡 곤란이요? 네 그런 거 없어요. 그런 거 없으시고? 아 한남남포테 네 알겠습니다. 구조차 수정할게요.
 윤랭구입니다. 아 네 안녕하세요. 저기 여기 길거리에 사람이 약간 불편해 보이셔 가지고요. 여자분이요? 여자분이요? 여자분이요. 여자분이시고 그거 쓰러지신 거예요? 아니면 뭐 앉아 있는 거예요? 쓰러지셨다가 앉아 계시는데 지금 의식이랑 호흡은 딱 있으신 거겠네요. 그럼 어디 불편했는지는 모르시고? 네 제 의사소통은 잘 안 돼요. 의사소통이 잘 안 돼요? 네. 네 알겠어요. 어디로 가면 돼요? 중남구청 여기거든요. 버스정류장 앞에. 버스정류장에 보면은 그 아이디 번호라는 게 있어요. 아이디 번호가 07 다시 267이요. 07 다시 267이요? 네. 07 다시 267? 네 잠시만요. 검색 좀 할게요. 예 그 앞으로 가면 될까요? 네 알겠어요. 네.
 네, 알겠습니다. 아 네, 여기 지금 사고 나서 같이 서가지고. 무슨 사고요? 선생님 교통사고요? 네, 교통사고요. 차랑 뭐랑 계신 거예요? 어 오토바이랑 오토바이인데 숨쉬기가 좀 힘들다고 하시거든요. 숨쉬기 힘들다고요? 네. 환자 몇 명이에요? 선생님? 어 1명이에요. 1명. 환자는 1분이시고? 아. 호흡 곤란 있으신 거예요? 지금? 어 아 약간 갈비뼈가 다 뒤졌는데 호흡하기 좀 힘들다고 하셔가지고. 아 그래요? 네. 선생님이 지나갔다 발견하신 건가요? 어 아니요. 아니요. 같은 사고가 나가지고. 아 그래요? 예. 알겠습니다. 제가 출동할게요. 주소 좀 알려주세요. 위치. 아 상도로 34일. 네. 네네. 아 예 알겠습니다. 출동할게요. 네.
 수고하십니다. 네 여보세요. 네. 아 그 어머님이 별로 하셨는데 넘어지셨는데 뭐지 왼쪽 팔목을 좀. 왼쪽 팔목 다시 썼다고요? 예 예 근데 지금 이게 계속 쑤셔 가지고 잠을 못 주무시는데. 주소 구급차 보내드려요? 네네 그랬으면 좋겠습니다. 주소는 어떻게 되세요? 반포 4동. 예. 네. 매칭 몇 초에요? 네. 잠깐만요. 네. 지금 코로나 환자나 자가격리 확진자 있어요? 그런 건 없습니다. 네. 주소 잘 그로 그로 드렸는데. 네. 그쪽으로 가볼 테니깐요. 전화 잘 받으세요. 네. 걸으실 수는 있어요. 네. 네 맞습니다. 네 가고 있습니다. 네.
 네 여보세요. 예 말씀하세요. 예 지금 배가 너무 아파서요. 아 지금 본인이 그러신 거예요? 네 운전을 할 수가 없을 것 같아서. 아 지금 위치가 어떻게 되세요? 어 겸재로 26길. 잠시만요. 26길에. 예. 하인하우스요. 여쭤면 어때요? 알겠어요. 구급차 그쪽으로 가볼 건데 열은 어때요? 지금? 열이나 전혀 없고요. 열은 없고? 그 근처 녹색 병원에 전화 문의를 했는데 예예 거기 뭐 지금 입원할 수가 없어서 자기네 병원은 안된다 그러는데 아 예 알겠습니다 금상 얘기했는데 이제 뭐 맹장령일 수도 있다고 알겠습니다. 그럼 제가 가볼게요 예 아

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 말씀 1번. 1 9입니다. 말씀하세요. 예예. 지금 저기 저기 상현동 동사무소 앞인데요. 예예. 그 계단에서 저기 넘어지셔가지고. 예예. 머리에 지금 수렬 있거든요. 상현동 동사무소요? 네네네. 예 잠시만요. 남자분이에요. 여자분이에요. 네네. 남자분이요. 잠시요. 거기 상현동 무슨 구예요? 어디가? 무슨 동이에요? 관악구 관악구. 관악구 상현동? 네네. 일단 저희 바로 출발할 거고요. 그 저희가 바로 전화드릴 테니까 전화 좀 연락 주세요. 네.
 안녕하세요. 119입니다. 네 인천 소방입니다. 들어갔나요? 예 제가 말할게요. 여보세요. 여보세요. 예 선생님 서울이고요. 예 예 예. 네 뭐 어떤 것 때문에 그런 거예요? 구급차 신고하시려는 거예요? 예 예 예 제 동생이. 네. 지금 뭐 코로나 의심이에요. 저 검사를 못했대요. 근데 애가 지금 점점 심해져가지고 막 죽을 것 같다 그러네. 막 오한다고. 아 주소가 어떻게 돼요? 예 여 송파구 잠실 본동. 잠시만요. 네. 네네네. 한강 빌딩. 한강 빌딩. 네. 예? 남자분? 동생? 네네네네. 아. 아 선생님 전화 온 거예요? 제가 어디다가 전화 온 거예요? 직접 통화하신 거예요? 말도 할 수 있는 상태인 거죠? 네 말은 해요 제 동생이랑 제가 전화를 했는데 지금 그런 상태예요 처음에 간뒀 줄 알고 동생 전화번호 하나 주세요 전화번호요? 네 네. 잠시만요. 잠시만요. 남자분이시고 뭐 몸에 열이 많이 난대요? 아유 지금 막 오후 한이 오고 뭐 어떻게 할 수가 없대요. 먹기 하나도 먹기도 못하고. 예. 하나분은. 하나분은. 예. 네. 나이는 어느정도 돼요? 남 동생? 남 동생이 지금 50대? 57살 되나봐요. 아.. 네 근데 제가 좀.. 예예 좀.. 혈압도 좀 있고.. 열도 있어요? 몸에 열이 돼요? 아.. 그것까지는 자세히 못 물어봤네요. 지금 막 오한이 나고 뭐.. 덩덩거리고.. 통화는 하지만 제대로 못해요. 아.. 차는 지금 보냈는데요. 혹시 뭐 코로나 때문에 격리 중이시거나 그런 건 아니셨던 거죠? 검사를 못했대요. 아니 검사는 못한 건 못한 건데요. 뭐 확진자를 만나거나 집에서 자가 격리 중이셨던 건 아니에요? 그러니까 지가 집에서 혼자 지금 몸이 아프니까 꼼짝도 못하고 진행이 상태래요. 네 제가 전화해볼게요. 차는 보냈어요. 네 네 네 네.
 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 예. 역전 빌라 출동하고요? 혹시 열이 나거나 기침 코로나 관련 증상이 있으신가요? 아니요. 2차 접종까지 다 마쳤어요. 역전 빌라 출동하겠습니다. 네. 감사합니다. 네.
 정확합니다. 네 저기 119 그 아니 앰뷸런스 좀. 네 어디가 누가 아파요? 누가 어디가 아파요? 아 저희 어머니 연세가 100세세요. 네. 근데 지금 어지러워가지고. 어지러우신 거세요? 수소 의식은 있으신 거죠? 네. 예 주소는 어떻게 돼요? 여기가요. 저기 영동포구. 예. 선유로 33길. 매칭 몇 도에요? 예. 각 경남 안옥시빌 맞죠? 네 맞아요. 집에 코로나 확진자 자가격리자 해당 사항 혹시 있어요? 없어요? 없어요. 없어요. 네. 구급차 보냈습니다. 병원 갈 준비하고 계세요. 네.
 일일이 입니다. 말씀하세요. 네 안녕하세요. 아 좀 전에 사고가 나가지고. 예예. 네 접속을 끝내고 이제 좀 병원 좀 가려고 그러는데. 아 일단 그 위치가 어떻게 되세요? 위치가 과자역 1번 출구에서 나오셔서. 과자역 1번 출구 앞에서 연남동 방향으로. 예. 바다 보면 연남교에 있거든요. 조그만한 거. 연남 아 연남교 앞으로 가면 돼요? 예예예. 아 네 알겠습니다. 그 앞에 계시는 거고 뭐 차랑 부딪치셨었나요? 아니 오토바이 길이 부딪쳤는데 이제 마무리 다 짓고 이제 병원 좀 가야 될 것 같아요. 그 환자 1명이죠? 구급차 1대만 가면 되죠? 아 네 알겠습니다. 그 연남교 앞에 계세요. 그러면 네 알겠습니다. 선생님 그 경찰도 보내드려야 되나요? 아니면 경찰은 아니 경찰 본다고 나가 이야기 다 썼려고 가셔 가지고 예 알겠습니다. 네.
 입니다. 아 네 안녕하세요. 네 말씀하세요. 아 지금 속이 너무 안 좋아서 잘했거든요. 속이 안 좋다고요? 뭐 어떤 증상인 거예요? 어 그냥 소를 많이 해야 되고. 아 예 지금 아예 고등이 안 되세요? 지금? 네 저 문제집. 아 예 주소는 어떻게 되세요? 저 남부 순환로 210길. 잠시만요. 남부 순환로 210길에. 서초하우스? 네네. 네. 알겠어요. 고객님 그쪽으로 갈 건데 지금 열 같은 건 어때요? 지금 열 증상은? 아 열은 없어요. 열은 없고요? 알겠어요. 고객님 가니까 병원 갈 준비하고 계세요. 네 감사합니다 네

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 119입니다. 아 여기 길가에 사람이 쓰러져 있어가지고요. 거기가 어디 위치 알려주시면 될까요? 어 이거 어디지? 앞에 뭐 건물 이름이나. 평물 요양병원이요? 평물 요양병원 옆에 편의점. 2001 아울렛 지구 GS25 편의점 어텔리요. 지우시 25 편의점. 무슨 점이 무슨 점이에요? 무슨 점. 편의점이 무슨 점인지는. 예 그니까 편의점 보면은 뭐 무슨 천호 천호 무슨 점 뭐 암사 무슨 점 이렇게 있거든요. 그거 얘기해 주셔야 정확해요. 너무 많아서. 아니 이 편이라 아울러주신데 잠깐만요. 편의점 제가 확인해 볼게요. 아 강동 리버힐 리버힐점이요. 강동 리버힐점. 앞이 뭐 쓰러진 분 남자분이 여자분이에요? 남자예요. 어디 앞에서 한번 물어봐 주실 수 있나요? 어디 아픈지요? 예, 대화가 아, 저기 아프세요? 그냥 길가에 치워져서 누워 계신 거 같아요. 뭐 이렇게 뭐 의식이 없거나 이런 건 아니죠? 예, 지금 살짝 눈은 뜨긴 하는데 뜨는데 기잡은 안 하고 예, 알겠어요. 옷은 옷은 살짝 벗겨져 있어요. 아, 이거 노숙인 분이세요? 그건 아니시죠? 아, 노수기는 아니신 것 같고. 번호 리버 좀 앞으로 갈게요. 네, 네, 네, 네. 저는 이동으로 해도 될까요? 길가 갖다 줘도. 네, 네, 네, 네.
 저 여기 그 마곡 킬 스테이트. 마곡 킬. 이 1명 사람 1명이 쓰러져가지고요. 쓰러지신 분이 가족이에요? 네, 네. 남자분이에요? 여자분이요? 남자분이요. 그러시면 의식 있어요? 없어요? 의식 있어? 어 지금 살짝 거의 없어서. 의식이 살짝 있어요? 의식 저 숨 쉬는 건요? 숨은 잘 쉬고 있어요? 숨 숨 잘 쉬고 있는 거죠. 가족분이세요? 네? 관계가 어떻게 되세요? 저 이모부요. 이모부. 이모부? 예 알겠어요. 네. 회원님 전화 끊지 마시고요. 네. 네. 그래서 여기 왔습니다. 아니 주물러 주물러 했다.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네. 일곱니다. 예. 수고하십니다. 그 충만구 묵동. 네. 그 극동 늘 푸른 아파트. 네. 네. 몇 잠깐만요. 몇 쪽인가 좀 볼게요. 잠깐만요. 네. 아 봉지를. 아니 아니. 나왔습니다. 네, 무슨 일이세요? 예, 거기 할머니 한 분 계신데요. 지금 일어나지 못하고 있거든요. 아 뭐 어디가 아프신 거예요? 증상이요? 증상이 어떤 증상이 있으신 거예요? 심장이 아이가 뭐 아직 뭐 저 뭐 계속 통화하고 아직 통화신다고요? 할지 내가지고 병원에 갈 정도가 못 해가지고. 아 의식은 있어요? 선생님? 네 의식은 있어요. 아 친구자분은 관계 어떻게 되세요? 아 동생이요. 동생. 친동생 분이시고? 예예예. 아 혹시 열이나 기침 호흡 곤란 같은 건 없어요? 코로나 같은 증상. 네 그런 건 없어요. 그런 건 없고 자격률이 좀 아니시고 코로나 확진자 아니시죠? 아 아닙니다. 예. 네 알겠습니다. 그렇게 되셨습니다. 예 감사합니다.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네. 여기 한양 아파트 한양 2차 아파트인데. 몇 에 몇 호세요? 몇 호? 아니 호수가 아니라 지금 경비실 앞에 아주머니가 됐는데. 아 예. 병원에 가시길 원하셔서. 아 어디가 아프신 건데요? 손을 못 쉬기시 어떻게 손을 안 써주세요? 예? 아줌마 손이 안 써주세요? 먹으 아 드신 게 취인 거 같으대요. 아 배가 아프신 거예요? 그러시면? 네 지금 막 먹어서. 혹시 코로나가 그냥 증상이 있는지 한번 여쭤보시겠어요? 열이나 기침이. 코로나 코로나 다 맞으셨죠? 네 다 맞으셨대요. 네 그런 증상은 없으신 거죠? 발열이나 기침이네요. 네 알겠습니다. 앞으로 출동할게요. 네 쌍분 환영 부탁드리겠습니다.
 예 여보세요? 아 예 안녕하세요. 119 상황실인데요. 예예. 제가 가고 있는데 서울 방향 그 경보고속도로상 맞죠? 예 만남의 광장 맞은편이에요. 맞은편인데 저희가 지금 서울 쪽에서 가고 있는데 만남이 광장에서 유턴에서 서울 방향으로 올라갈 수 있어요. 그렇게 저희가 진입을 하면은 현장을 확인할 수 있을까요? 아니면 저 밑에까지 가서 이렇게 돌아와야 되는지 어 지금 여기 양재 아이씨 같은데 나가기 직전이에요. 아 양재 아이씨 서울 방향 오른쪽으로 빠르기 직전이란 거죠? 예예. 그 뒤쪽으로 보면 이렇게 남남이 광장에서 어, 아이튼 그 서울 양지 아저씨 직전이란 거죠? 그러면 남남이 광장에서 이렇게 돌아서 나오면 되겠네요? 어, 제가 길이를 잘 몰라서 아, 예, 예, 뭐 올라오는 길 하나 있네요. 아, 예, 예, 맞아요. 알겠습니다.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네, 열립니다. 네, 지금 저기 화장실에서 쓰러지셨는데. 주소 알려주세요. 네? 고급차가 필요하세요? 네. 주소 알려주세요. 네, 여기 금호동 일가. 삼성 매매하는 여보세요? 예, 말씀하세요. 네, 금호동 일가 삼성 매매하는 아파트. 네. 할머니 쓰러진 사람이에요? 네. 할머니 쓰러졌는데 춤춰요? 춤을 출말를 텐데 의식이 안 돌아오세요. 예. 신고자분 코로나 확진 된 분 가족 중에 없으시고요? 네. 없어요. 지금 차 출발했고요. 3분 대미안 아파트 네. 네. 예. 저희 의사 선생님 연결해드릴게요. 가면서 전화 끊지 마세요. 감사합니다.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 실례합니다. 아 네 안녕하세요. 여기 동선로 어 전화가 끊겨서요? 동선로. 동서문 아 저 저 성북구 동서문로 15길 잠시만 동서문로 15길에 네 2차 아파트. 네 동서문노 한심시우 플러스. 주소는 알고요. 저희가 모든 출동권에 코로나 관련 질문 드리게 돼 있어서. 아 그래요? 제가 몇 가지 여쭤볼게요. 가족분들 중에 뭐 발열이나 고열 기침 이런 동호기지 않고. 아니 없습니다. 네네. 어 확진자를 혹시 만나셨거나 자가 경영인 상태이신 분도 안 계시고요? 네네 없습니다. 아 그 대원들이 전화드리면서 갈 거예요. 승인동 쪽에서 가니까 전화 좀 받아줄게요. 네 고맙습니다.
 119입니다. 말씀하세요. 네 여기 노숙인인 것 같은데 좀 쓰러져 있는데 여기 위치가 어디냐. 예 위치가 어디냐 하면은. 네네. 얼찌 4가 1번 출구. 아 1번 출구 앞으로 가면 돼요? 아 예 밑으로 내려오십시오. 지하로 내려오면. 글씨 속 예 그래 오십시오. 이 빨로. 아무리 흔들 떼어도 사람이 지금 반응은 안 보이는데. 남자분이시고요? 예. 숨 쉬는지 안 쉬는지 혹시 보이나요? 선생님? 어 이게 제가 지금 주문시는 거 같아요. 을지로 4가역 1번 출구. 예 예 예. 을지 을지 4가 1번 출구 예. 을지로 4가역 1번 출구 저희 회원들 그 내려가면 안내 좀 해주세요. 예 알겠습니다. 예.
 예, 안녕하십니다. 아 예, 여기 어 노량진에 그 강남교에 앞에 그 GS25시 편의점 앞인데요. 강남교에 앞에 GS25요? 예, 그 편의점 앞인데 어떤 분이 지금 그 약간 간절히 신지 뭔지는 모르겠는데 막 부들부들하면서 지금 숨어 주셨거든요. 숨을 전혀 못 쉬는 곳인 거 같은데 눈은 일단 지금 흰 사이로 까지 집어 주셨고. 지금 불러서 대답해요? 못해요? 차는 출발 시켰어요? 못해요? 못해요? 남자분? 네 남자분이요. 알겠습니다. 우리 수박하는 데 빨리 갈게요. 그 그 학교에 바로 앞에 있는 GS25예요? 예예예. 알겠어요. 수박하는 데 빨리 갈게요. 예.
 연락합니다. 아 네 여보세요? 여기 면목로. 면목로. 사람 쓰러졌거든요? 혹시 넘어지신 거예요? 아니면 의식을. 아니요. 아니요. 정신이 없어요. 남성분이에요? 여성분이에요? 남성분이요. 아 그 모르시는 분이에요? 아니요. 아버지인데 쓰러지셔 가지고. 아 쓰시는 거 확인 좀 해주세요. 네? 제가 지금 있는 게 아닌데 엄마가 지금 거기 가겠었는데 지금 전화 왔거든요. 현장 전화번호 좀 알려주세요. 잠시만요. 어머님 전화번호요? 네네. 엄마 엄마 전화번호요. 네. 예? 네. 알겠어요. 구급차 가면서 전화해볼게요. 현장으로요.
 어디다. 예, 알겠습니다. 여보세요? 네. 아 그 엄마가 그 좀 코에 좀 닫혀가지고. 네. 주소 주소 불러줘. 아 멸목동. 멸목동 몇이요? 마지막에. 몇 층 몇 호세요? 어. 음. 뒤 몇 층 몇 호예요? 어. 무슨 일이신 거예요? 아. 그. 그 앞에다가 그. 나라져서 가지고. 코가 조금 뒤 남았어요. 코피 나신다고요? 아니요. 그 그 머그 머그잔으로 그 떨어져가지고 그 좀 콧백이? 위마 부분에 피나 많이 피나가지고. 아 그래요? 네. 코로나 관련 증상은 없나요? 열이나 기침 혹곤란이요? 네 없어요. 관심사 없으시고요. 예 알겠습니다. 구비자 보냈어요? 선생님? 네. 네.
 네, 1 2 9입니다. 여보세요? 여기 가산 디지털 단지인데요. 어떤 할아버지 분이 엘레 에스컬렛에서 엄청 욕기서 창불어주셨는데 그냥 어떤 분 데리고 가시거든요? 머리 엄청 세게 박으셨는데. 가산 디지털 단지 어디 쪽이에요? 여기 1번 1호선 쪽이요. 1호선 1호선 쪽 어디예요? 1번 7구? 지금 가고 있거든요. 친구 잡아 데리고 가고 있는데 우리가 나가면 없잖아요. 그분 붙잡으세요. 아니 여기 여기 계세요. 네, 네. 그니까 1번 어 잠시만요. 여기 4번 출구 쪽이 빨리 와주세요. 친구 잡아 지금 차는 가고 있는데 위치를 알려주셔야죠. 그 1번 1호선 1호선 몇 번 출구 쪽이에요? 어 잠시만요. 친구 잡아 옆에 0번 없어요? 잠시만요. 할아버지 지금 숨 쉬어요? 어휴 모르겠어요. 안 잡으세요. 그냥. 신고자분은 차는 지금 나가고 있어요. 위치를 제가 여쭤보는 건데 할아버지 숨 쉬어요? 여기 역 안이라서 4번 3번 2번 중 다 있거든요. 그 안으로 들어오시면 바로 있어요. 그 뭐 매장이라든지 뭐 표 뽑는 데라든지 그런 거 없어요? 여기 나오시면 그 빵집 있거든요? 무슨 빵집? 무슨 빵집이요? 샷 브레드요. 네? 샷 브레드. 샷 브레드 알겠어요. 네.
 네 서울의 출고 상관실입니다. 네 들어왔습니다. 친구자분. 네 말씀해 주세요. 몇 동이라고요? 전화가 안들려 1단지요 1단지인데요 여기 어떤 할머니가 쓰러져 계셔서 네 몇 동 앞이라고요? 네? 몇 동 앞이요? 32만원이 갔대요 네 자 주동하고요 혹시 할머니가 의식은 어때요? 의식은 있어요? 의식은 깨어있는데 일어서질 못해요 알겠습니다. 출동해볼게요. 경찰관님 혹시 왔어요? 아니 아직 못 왔어요. 예 출동하겠습니다.
 네, 누구입니다? 네, 그 저기 사람이 여기 뭐가 떨어져야 되는데 발가락을 좀 다쳤는데요. 움직일 수가 없을 좀 그러거든요. 누가요? 아 저 40대 남자가. 남편이요? 남편? 아니요. 사위예요. 사위. 사위가 발가락이 뭐 어떻게 된 거예요? 아 위에서 저기 캔 같은 게 떨어져가지고 계속 지금 피가 나서 움직이질 못해서 전화드렸거든요. 주소 좀 알려주세요. 송죽길? 서대목 서대목 송죽길. 네. 필탑 아파트. 필탑 아파트. 네네네. 출소하겠습니다. 혹시 열이 나거나 코로나 관련된 거. 아 그거는 없어요. 출소할게요. 네.
 실례합니다. 네 아우 불이 난 건 아니고요. 너무 아픈데 병원까지 좀 데려다줄 수 있을까요? 어디가 아프신가요? 아 병원에서 척추 출만이라고 진단을 받았는데요. 옆구리하고 허벅 저기 내가 너무 아프대 무릎까지 어떻게 저기 내가 뒷눌리니까 너무 아프갖고 옆구리랑 무릎이 다 아프시다고요? 네 네 네 네. 본인이요? 네 본인이에요. 계시면 주소가 어떻게 돼요? 어 그 정릉로 421이요. 제가 저기 뭐야 문 앞에까지 나갈게. 사이렌 울리지 말고 그냥 오시면 안 될까요? 하 선생님 일단 그때 언제 갈지 모르니까 거기서 통화하시면 그때 내려오시고요. 네 한참 걸려요. 감기 증상에 코로나 확진자는 안 해요? 어 아니에요. 저 코로나 3차까지 다 맞았어요. 병원으로 19개 사인 혜수비 맞죠? 네 그렇게 보냈어요. 기다려주세요.
 네 구급차가 119 맞나요? 네 저 그 여기 개포동 그린빌라 네 그린빌라. 네 여기 삼성의료원에서 저희 어머니가 신장수술을 하셨는데 지금 좀 호흡이 좀 곤란하시고 맥박이 좀 많이 왔다 갔다 거리시고 하셔가지고 병원을 가려고 하거든요. 어머니 지금 호흡곤란 행사가 있고. 예 그러면 맥박도 이제 좀 많이 흔들리시고요. 네 거의 빨라요? 아니요 뭐 빠른 것도 있고 다 내렸다고 빨라졌다고 뭐 이래요. 그래서 지금 수분이 너무 이제 가빡으시니까 힘들지고 하니까요. 의식은 괜찮아요? 예 괜찮습니다. 아 뭐 그 거동 가능하세요? 예 예 예 거동 가능하시고요? 어머니 열이나 교통 코로나 관련한 사항 있으세요? 예 없습니다. 열은 체크하여 있고 문제 없습니다. 예 전화 받으면 1층으로 내려와 주실 수 있으세요? 그리고 이 근처에 그 수리 안 내고 와주셨으면 좋겠어요. 아 예 알겠어요. 네? 네? 1층으로 내려와서 전화 받으면. 예예. 1층으로 내려오네요.
 여보세요? 예 저 119인데요. 지금 119 가고 있는데 화곡동 맞아요? 예 그 맞죠? 3호 3호 아 그린 3호 오피스텔? 아 오피스텔이 아니고 3호 그린 12초 측입니다. 예 알겠습니다. 제가 지금 나와 볼게요. 의사 선생님 연결해 드릴게요. 전화 끊지 마세요.
 네, 119입니다. 여보세요? 여보세요? 네, 119에요. 왜? 119 전화하신 거 아니에요? 아, 우리 딸이 네. 공항전 해갖고 막 괴로워하는데 어디가 아프다고요? 공항전이요. 구급차 요청하시는 거예요? 네. 주소가 어떻게 돼요? . 독산동이요? 네. . 몇 층 몇 호요? . 가족분들 중에 코로나 지역 다녀오거나 관련. 없어요. 구급차 가볼게요. 네.
 네, 네, 네. 아 여기 지금 저 핸드폰으로 위치 조회에 계시나요? 혹시? 어 위치 조회를 동시에 해보겠습니다. 무슨 일이세요? 지금 돈까스를 먹으러 왔는데 좀 매운 거를 먹었는데 애가 계속 속이 아프다 그러고. 아이가요? 아니요. 아니요. 어른이에요. 어른이고요? 남자의 남자예요? 남자요. 남성분이고 구급차가 필요하신 거 맞으세요? 네, 네. 아 잠깐만요. 위치는 좀 조회는 됐고요. 여기 보람의 자이 아파트 나오는데요? 네 자이 아파트 맞은편에 있는 그 생선가스 전문점이거든요. 아 예 찾았습니다. 그 앞으로 고급차 보내드릴게요. 혹시나 환자분이 코로나 관련자는 아니신가요? 네 뭐 열나고 감기 증세 없고요? 네 초등학생 전화 옵니다. 잘 받아주세요.
 119입니다. 여보세요? 네 여보세요? 예 예 저희 어머니가 좀 안 좋으셔서. 어머니 어디가 안 좋으세요? 아니신데 지금 못 움직이시고 뭐 상태가 안 좋으셔 갖고. 네 선생님 그 일단 주소 좀 불러주세요. 가재울 미래로. 미래로. DMC 파크 파크 뷰 자이. 파크 뷰 자이. 네. 혹시 어머님 포함해서 가족분들 코로나19 기침 반려전상 있다거나 사회응장 확보 이런거 있나요? 없습니다. 예 알겠습니다. 네. 네.
 119입니다. 여기 그 동대문구 전동동. 레미안 크래시티. 잠시만요. 레미안 크래시티. 무슨 일이세요? 저희 어머니가 손가락 쪽이 부러지신 것 같아서 넘어지셨어요? 손 쪽이 부어가지고 손이 부었어요? 뭐 다치신 거예요? 네 그런 것 같아요 뭐 하셔서 그러신 거예요? 어디 부딪히셨나 봐요 손가락이 골절된 것 같아요? 아니 손 바닥 그 엄지손가락 밑에 부분이 좀 부었어요. 그 팔꿈치 쪽도 좀 부었고. 아 병원 가시려는 거예요? 구구차로? 네 그러 그러신 거 같아요. 아 지금 차 그럼 구구차 타고 하시 옆에 계세요? 네 지금 아래에 계세요. 싸우시거나 그런 건 아니죠? 경찰 필요하거나 그런 건. 네 건 아니에요. 아 열이거나 지친 꽃물 있으세요? 아니요. 집에 코로나 때문에 격리하거나 확진자 있거나. 아니 없어요. 2분 다 보낼게요. 네.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네, 말씀하세요. 네, 말씀하세요. 무슨 일이세요? 예, 애가 욕실에서 넘어져서 좀 다쳤어요. 아 네, 그 부처 보내드릴까요? 그 위치 좀 알려주세요. 우성 아파트 잠깐만요. 강동구 천중로 49일. 잠시만요. 천중로 49일 맞나요? 선생님. 예, 49일. 우성아파트에요? 네. 우성아파트 맞으세요? 네. 몇 동이세요? 아기가 어디가 아픈가요? 지금. 22살이고요. 네. 욕실에서 미끄러져 넘어졌는데. 네. 남자분이세요? 여자분이세요? 여자예요. 알겠습니다. 욕실에 넘어지셨다고요? 제가 두 분으로 요금차 보내드릴게요. 선생님. 혹시 코로나 관련해서 해당사항 있으실까요? 없어요. 알겠습니다. 선생님. 저희가 출동하는 구급자 전화드릴 거고 전화 좀 잘 받아주세요.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 예 열리 겁니다. 네 그 그 계속 급체해가지고 토하고 그래서. 네 급체요? 네네네. 임플런스가 필요할 거 같아요. 예 급체의 그 토요? 그 토. 본인이세요? 본인? 누구 여보세요? 배우자요. 남편이요? 남편이 급체하고 그 토요? 그리고 주소 좀 불러주세요. 아트요. 잠깐만요. 도영로에요? 네. 도영로. 잠깐만요. 어. 영동동 아트 자이언 아트 자이언. 네. 몇 동이에요? 네. 몇 동이에요? 네 남자 극제구통 그리고 코로나 관련해 갖고요 의심사항 같은 거 혹시 없어요? 기침하고 연락하고 이런 거 없어요? 감기지사? 네 없어요. 네 빨리 바뀌어요. 양성포 아트 자이어야. 네.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 예 119입니다. 여보세요? 예 말씀하세요. 예 병원에 좀 갈려 그러는데요. 아 예 어디가 아프신 거예요? 선생님? 아니 열이 그냥 열이 막 그렇게 38도까지 올리고 그래가지고 그래서 지금 이제 8도는 먹고 있길라니요. 예예. 그러니까 지금 뭐 응급실 가보시라 하시는데 지금 거동이 안 되시는 거예요? 아 거동은 내가 슬슬 걸을 수 있어요. 아 그럼 병원 안내가 필요하신 거예요? 선생님 어디 병원 가야 되는지? 내가 저기 있었던 그저에 코로나로 내가 병원에 가서 한일병원에 가서 있었더라니요. 한일병원이요? 예, 그저 글로 갈까 하는데요. 아 선생님 거동 가능하시면 택시 타고 가셔도 되잖아요. 아우 이게 바람 좋아서 힘들어가지고. 아 그니까 뭐 지금 뭐 조금 걸을 수는 있는데 병원까지 이동할 컨디션은 안 되는 거예요? 예, 예. 아 누가 아프신 거예요? 본인이 그러신 거예요? 예, 예. 발혈 증상 말고 뭐 제일 불편하신 게 뭐예요? 발혈 밖에 없어요. 발혈하고 좀 이제 뭐랄까 염증이 있어서 그런지 하나 열 번에 안 좋고 발혈 좀 하고 그래요. 아 기력이 좀 없으세요? 네. 기력 없으시고 발혈 증상으로 응급실 가보시려는 거죠? 예. 한일 병원으로요. 아 선생님 그 병원 선정은 출동한 고급대가 선생님 상태 보고 가장 가까운 병원에 이송하게 되어 있어요. 이렇게 원하시는 병원 가시고 싶으시면 사설 구급처 이용하셔야 되거든요. 일단은 저희가 그 어머님 상태로 확인을 해야 되니까 꼭 한유병원에 간다고 말씀을 못 드려요. 아 그래요? 네, 그럼 어디로 가요? 그거는 말씀드렸잖아요. 구급대원이 선생님 상태 확인하고 병원 선정하게 되어 있다고요. 음 알았습니다. 예, 선생님 그 주소 좀 알려주세요. 그러면. 여기 저기 시흥 2동 벽산이요. 6단지. 벽산 1단지요? 6단지요. 6단지? 잠시만요. 네 6단지. 벽산 아파트 6단지. 그거예요? 네. 예. 잠시만요. 신 벽산 아파트. 그쪽으로 구급차 가볼게요. 최근에 코로나 증상이나 발열은 있으셨고 코로나 확진 됐다거나 그런 건 없으시죠? 아 확진 돼서 전번에 병원에 치료 다 봤고 음성 진단이 나왔거든요. 아 확진 되셨었는데 그 완치로 이제 격리하거나 그러진 않았던 거죠? 예예예. 아 예 일단 알겠습니다. 네. 네 그쪽으로 구급차 가볼게요. 네. 네.
 1급입니다. 말씀하세요. 네 여기가 여기가 어디지? 인수복로 17길인데요. 길가에 할아버지가 네? 어디요? 인수복로 17길이라고요? 네 인수복로 17길. 네 그다음 뭐예요? 17길 다음에? 라고만 적혀 있어요. 여기 양군교회도 있고요. 아 교회 그 교회 앞으로 가면 돼요? 네 지금 할아버지가 길가에 지금 쓰러지신 걸로 돼 있다고요? 아 네 알겠습니다. 일단 그 교회 앞으로 갑니다. 아 네 알겠습니다. 한번 빨리 나가볼게요. 이거 숨 쉬는지 안 쉬는지 혹시 보이나요? 할아버지? 아 지금 호흡은 하세요. 근데. 순복음 생명교회 맞아요? 순복음 생명교회? 양문교회? 양문교회. 양문교회? 아 네 알겠습니다. 조금만 기다려주세요. 네 넘어지셔 가지고 가시다가. 아 네. 예. 피도 안 하거든요. 이면. 네네. 알겠습니다. 네.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네 여보세요. 저 여기 합정역 건어물 여기. 네 여보세요. 예, 누구입니다. 말씀하세요. 어 여기 지금 합정역에 있는 건어물 카바레라는 설치 바로 앞인데요. 예예. 친구 1가 지금 팔꿈치 쪽이 1.5cm 정도가 찢어져가지고 전화드렸거든요. 아 그 넘어지신 거예요? 어 지금 어디에 부딪친 거 같은데 찍힌 거 같아요. 아 그 그 건물 차렙에 그 건물 앞쪽에 계시는 거예요? 네 여기 지금 그냥 앞쪽에 계속 앉아있거든요. 지금. 어 남성분이에요? 여성분이에요? 다치신 분이? 어 남성분이에요. 어 그 출혈이 심하신 거예요? 어 네 띠가 지혈이 계속 안 돼서. 아 제가 가까운 응급실도를 모셔다 드릴 거고요. 네 네 네. 그 모든 출동권에 코로나 관련 질문을 드리고 있는데. 네 네. 혹시 뭐 코로나 관련 발열이나 고열 기침 위로통 코로나 관련 증세는 없죠? 어 네 아예 없습니다. 아 확신대로 만나셨거나 자가금이 상태이신 것도 아니시고요? 네 네. 아 알겠습니다. 계연분들이 가면 전화드릴 거예요. 전화 좀 받아주세요. 네 알겠습니다. 감사합니다. 네.
 16입니다. 아 예 여보세요? 예 말씀하세요. 아 여기 청량리. 어디에 청량리 동이에요? 예 청량리 동. 청량리 동. 예예. 예. 예예 예 몇십 몇 호에요? 제가 예 무슨일이세요? 마비가 와서 되니까 예 어디에 마비가 와야죠? 한쪽으로 마비가 와요? 오른쪽 왼쪽 오른쪽으로요 예 이쪽으로 예 집중할거에요 그 코로나 장학용이나 확진자에 가려는건 없으시죠? 예예 없어요 상단문은 열어줄 수 있어요? 예예 제가 지금 나갈 수 있어요 아 밖으로 나올 수도 있고요? 예예 청년에서 그만 알 거예요? 예예 알겠습니다
 119입니다. 예 안녕하세요. 네. 여기. 어디 아파요 선생님? 네. 위가 너무 아파요. 어디 위가 아프다고 위통? 예예. 위쪽에 위경련 증세 있어요? 맞아요. 예 주소가 어떻게 돼요? 네. 여기 독산. 독산목? 예예. 독산로 87 87길 87길에 몇 시에요? 아니 독산로 87길 맞아요? 네네. 잠깐만요. 실무수 확인해 볼게요. 예 몇 호요? 일단 호수부터 말해주세요. 잠깐만요. 아 여보세요? 예 87길 맞아요. 87길에 몇 호예요? 거기가? 예예. 예 알겠어요. 선생님 코로나 관련해서 고열 기침이나 인원통증세 같은 거 없죠? 아니요 아니요 그냥 이 통증 너무 심해서. 코로나 관련 증상은 없다는 거죠? 예 없어요. 예 알겠어요. 구구차 가고 있어요. 응.
 네, 1 9입니다. 네, 여보세요? 네, 말씀하세요. 아 네, 저기 병원에도 좀 급히 가야 될 것 같아서요. 누가 환자분이세요? 어 아들이요. 아들이 어디가 어떻게 아프세요? 어 저기 술 술을 먹고 약을 좀 많이 먹었어요. 술을 먹고 무슨 약을 먹었어요? 좀 구체적으로 말씀을 해주세요. 어 우울증이나 신경 안정제 같은. 술을 먹고 신경 안정제 우울증 약을 많이 몇 달이나 구경했어요? 많이 많이 먹었어요. 지금 어떤 인상 있어요? 토하고 있어요? 많이 토했고요. 네. 물 물 어. 주소 주소 좀 알려주세요. 주소. 어? 주소 좀 알려주세요. 어 저기. 어. 어. 아니 아니 여기 마포구 성산동 몇 층이에요? 골든빌 아파트 몇 동이에요? 어 한 동이에요 여기는 골든빌 아파트 64 골든빌 아파트 출동하고요 네 64에요 은우진 연결할게요 전화 끈지 말아주세요 네 네 거기 성님사 옆에 있는 거 맞죠? 성님사. 네 네 맞아요. 네 네 맞아요. 의료진 연결하겠습니다. 혹시 열이 나거나 기침 코로나 관련 증상 있어요? 아니요 없어요.
 수고하십니다. 네 안녕하세요. 여기 고덕 리엔파크 3단지 네 저희 할머니가 지금 그니까 내 경세기 때문에 퇴원하신 지 얼마 안 됐는데 지금 소화하고 되게 어지러워 하시거든요. 어 그래요? 부속차 보낼까요? 네 열이나 기침 코로나 관련 확진자 자가 경제에 해당 사항이 있으신 분 없으세요? 거기 네 없어요. 네 고덕 리엔파크 3단지 맞아요? 네 맞아요. 네 구급차 보냈습니다. 네 감사합니다. 네.
 아 네 여기 그 창천동 리츠하우스 잠시만요. 서계문구 창천동 네 창천동 네 리츠하우스 맞죠? 네, 무슨 일이에요? 그, 래니에르 그 병 때문에 네? 그, 어지러워 래니에르라고 래니에르, 이게 무슨 병이에요? 그, 어지러워가지고 토하고 이제 그러는 건데 지금 일어나질 못하거든요? 누가요? 선생님이랑 다른 분이에요? 아, 엄마, 엄마가요. 어머니가 지금 어지럽고 구토하고 거동이 힘들어요? 네, 네, 지금 구토를 계속하고 있어서 인간한 것 자체가 없는데 네, 병원 가실 거죠? 네, 네, 응급실 좀 그 엠브로스 좀 부탁드릴게요. 알겠습니다. 그럼 지가에 코로나 환자나 고역에 주민 호텀 증서에 있는 분 없으시고요? 네, 없어요. 네, 없어요. 네, 네, 감사합니다.
 네 일류붑니다. 네 군원주그대 경찰관인데요. 네. 예 그 술을 많이 드신 분이 있는데. 네. 의식이 없으시고 입에서 거품이 나오시네요. 예 남자분이에요? 여자분이요. 예 친구자 분 주소 알려주세요. 동서문로 24길. 숨을 쉬어요 그분? 숨은 쉬는데 의식이 전혀 없어요. 예 지금 빨리 나가볼게요. 주소 알려주세요. 동서문로. 24길. 예. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네.
 네 여보세요? 119 상황실이에요. 아 네 여기 동강역 11번 출구인데요. 지금 경찰 아저씨도 오셨어요. 근데 그 에스컬레이터 오시다가 취객분이 눈이 찢어져가지고. 피가 너무 많이 나가지고. 그 정도인데요? 오셨는데. 예. 119분들 안 부르셨냐 해가지고. 예. 예 지금 그런 상황이에요. 전 집에 가야 돼가지고. 아 네네. 눈부위 출혀있으시고. 네네네. 11번 출구구 바로 앞에 계시는 거예요? 네 11번 출구에 바로 앞에 계세요. 아 11번 출구 바깥 죽이고. 네네. 중강역 11번 출구. 네. 출구 바깥 죽이고. 차 편상해서 보내드렸고요. 가면서 전화 드릴 수 있어서 전화 신청 받아주세요. 네 감사합니다. 네.
 네, 읽습니다. 네, 읽습니다. 말씀하세요. 네, 여보세요. 네, 말씀하세요. 어 지금 여기에 그 뭐야 이거. 예, 개성구 앞인데요. 어디 앞이라고요? 개성구 앞이요? 개성 예, 예, 기름동 개성구 앞이요. 네. 지금 그 그 배달 거 타시던 분이 넘어져 가지고 많이 다치신 거 같아요. 오토바이 타고 넘어졌어요? 오토바이 아니고 이게 뭐냐. 예 전동 배달 민족 이거 전동 킥보드? 전동 킥보드 낙상이요? 예예 그 다리 사고 잡히신 거 같아요. 혼자 넘어진 거예요? 아니면 뭐 차량 부딪친 거예요? 네 혼자 넘어지신 거 같아요. 단독 사고 남성 다리 부상이요? 예예 개성구 앞이요? 개성구 종문 앞으로 가면 돼요? 예예. 출동하겠습니다. 네.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네, 이리 봅니다. 네, 아까 전화했었는데요. 애기가 그 애기가 자꾸 그 배가 아프고 울고 그 열이 나오고 그래가지고요. 그 좀 전에 그 우리 방락을 했는데 그 그 구독자 부르는 수밖에 없을 것 같다고 그래가지고. 주소 알려주세요. 그 애기가 서울 마포구 현대 1차 아파트. . . 몇 호요 선생님? . . 몇 살인가요? 애기 지금 만. 9살하고도. 9살하고 1개월 더 됐어요. 25개월. 열도 나요 선생님? 네 열 한 39도도 있고. 그 자꾸 아프다고 아프다고 그랬는데 어디 아프냐고 그러면 배를 가르쳐요. 보호차 수동하겠습니다.
 네. 입니다. 네. 저기 어머니가 넘어져서요. 네. 못 일어나서 병원 가는데 못 가겠네. 혹시 어머니 열이 나거나 기증 코로나 관련 증상 있으세요? 없어요. 주소 좀 알려주세요. 석천동. 석천동. 석촌동. 석촌동 이예요? . . . . . . . . . . . . . .
 네. 일곱니다. 네. 저 어머니가 많이 천천하셔서 그런데요. 예. 어디 가쁘신가요? 선생님 증상이요? 그 오른쪽 옆구리가 이렇게 바쁘셔가지고 아예 움직이지 못하시겠다고 그러거든요? 아 그래요? 예. 코로나 관련 증상은 없나요? 열이나 기침 호흡 곤란 같은 증상이요? 네. 선생님 주소 좀 알려주세요. 여기가 그 이화여대 팔길 네. 네. 스테이트 신촌. 네. 네. 네. 네. 알겠습니다. 이제 부탁드렸습니다. 네. 감사합니다. 네.
 네, 지금 전화시입니다. 아, 여보세요? 예. 네, 저희 어머니가 조금 아프셔갖고 지금 병원에 좀 가려고 하는데. 어떻게 괜찮으십니까? 지금 몸이 좀 호흡이 좀 곤란하고요. 호흡이 곤란하시고 또 뭐라고요? 몸이 얼굴 막 온몸이 붓는다고요. 전신이 마비 증세가 있다는 얘기예요? 아니요. 그 입기가 그냥 붓는다고요, 붓는다고요. 아 몸이 부었다고요? 음 알겠습니다. 그 상품을. 어디로 차 보내드릴까요? 예 그 여기 그 한빛로. 한빛로. 한빛로. 예. 예 그 저 저희 어머니는 고등을 못 하신데. 아 예 지금 차 보냈고요. 혹시 뭐 코로나 관련된 거 있으세요? 아니요 그건 아니고요. 거기 산물 병원에서 계속 통원 치료받고 있었는데요. 지금 상태가 안 좋아져서 지금 가려고 합니다. 예 제가 의료진 좀 연결해 드리겠습니다. 예 감사합니다. 전화 좀 더 기다려 주십시오. 예.
 네. 119입니다. 말씀하세요. 네. 안녕하세요. 여기 지금 중복 환자가 있어서요. 어느 분이 어떻게 괜찮으세요? 아 좀 계속 구토로가 좀 심을 하시고요. 어느 분이요? 어 여자분이요. 여자분이요? 신고자분 관계가 어떻게 되세요? 현실이 있고 아 여기 아버님이 계시고 따님이세요. 아 따님이요? 그 주소 어떻게 되세요? 네. 서초구 효령로. 서초구. 효령로. 효령로. 61길. 61길. 몇 층 몇 호요? 네. 우선 빌리지고요. 네. 오시면서 연락 주시면. 몇 호요? 그냥 단독인가요? 네. 아 네 알겠습니다. 대원들 나가면서 전화드릴 수 있고요. 저희가 그리고 걷는 거 정도는 할 수가 있으니까요. 오시면 바로 탑승할 수 있게 전화를 주세요. 아 네 대원들 나가면서 전화드리라고 말씀드릴게요. 최근에 코로나 관련해서 의심 증상이나 접시겠다고 문자 받으신 거 있으세요? 전혀 없습니다. 네 알겠습니다. 대원들 전화드리라고 말씀드릴게요. 네 감사합니다. 네. 대원들이.
 네. 안녕하세요. 네. 안녕하세요. 네. 선생님 저희 공급차 가고 있고요. 네. 네. 여기 찾아뵙니까 런 빌리지가 석촌보. 네 맞아요. 네 알겠습니다. 감사합니다.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 수고하십니다. 안녕하세요 여기 그 방금 교통사고 봤는데요. 교통사고 목격하신 거예요? 네 내가 내가 섞인 거 아니고 길거리 다니다가 네 차례 뭐예요? 차랑 오토바이 오토바이 어디 위치는 여기예요? 위치는 영도포구청 쪽에 영도포구청 아 잠깐만요 여기 주소가 어떻게 되지? 아 옆에 보이는 간판이라도 아 네네 여기 영등포로 영등포로 네 그 앞인 거예요? 어 네네 알겠습니다. 뭐 운전자 몇 명 있었나요? 오토바이에는 오토바이 1명이랑 택배 1명 네네 그니까 그 부상자는 오토바이 시장으로 맞죠? 네네 알겠습니다. 구급차 1대 보내겠습니다. 여기로 정차리랑 네.
 네 여기 지금 급한 건 아니고요. 허리가 아파가지고 못 움직이거든요. 남자애가. 아 그 가까운 응급실 쪽으로 모셔다 드릴까요? 네? 가까운 응급실 쪽으로. 네. 아 제 친구 위치가 어디예요? 지금 그 목동에 2차들 바로 앞이거든요. 잠시만요. 저희가 서울시 전체 전화 받고 있어서 검색을 한번 해볼게요. 저 제가 아까 전화 걸었다 바로 끊었더니 위치 조회했다고 문자 왔거든요. 아 그 근처 위치만 나오지 정확한 위치가 안 나와서 제가 검색을 한번 해봐야 되거든요. 잠시만요. 아 거기가 목동역 1번 추구 쪽에 있는 거 맞아요? 네 맞아요. 아 그럼 2차로를 앞으로 갈 거고요. 네. 네. 저희가 모든 수도권에 코로나 관련 질문 드리고 있어서 차 가는 동안 몇 가지 질문 좀 드릴게요. 아 그 계신 분 그 남성분 포함하셔서 뭐 발열이나 고열 기침 위로통 코로나 관련 증서 있으신 분 안 계시죠? 아 네 없어요. 아 확진자로 만나셨거나 자가격리 하신 분 안 계시고요? 네 네. 아 그 말씀하신 목동역 이 채도를 앞으로 가면서 전화드릴 거니까 전화 좀 받고 안내 좀 해주세요. 가까운 응급실에 모셔다 드릴게요. 네.
 네, 감사합니다. 말씀하세요. 아 네, 네, 그 저희 애기 아들이 지금 돌 조금 안 됐는데요. 아 네, 네, 열이 너무 심해서 아까 병원에서 해열제 받아온 거랑 저희 약국 거랑 이렇게 번갈아가면서 먹이는데. 먹으면은 계속 토해서 그런지 해열제 효과. 간호사분 계신데 한번 소요 상담으로 바꿔드릴까요? 아 아까 상담받았는데요. 네 상담받았는데 그 해열제를 먹으면은 계속 토해내서 열이 39도에서 안 떨어져가지고 아무래도 응급실 기다리더라도 가봐야 될 것 같아서요. 여기 서울 강남구 개포로. 강남구 개포로 예. 109길. 109길. 예. 대청 아파트. 대청 아파트. 예. 예. 예. 예. 알겠습니다. 제가 출장할 테니까 전화 잘 좀 받아주세요. 선생님. 네네. 감사합니다.
 네 지금 복통이 너무 심해서 전화 좀. 복통이요? 네. 아 선생님 배가 아프신 거예요? 선생님 본인이? 네. 알겠습니다. 선생님 주소는 어떻게 되세요? 안암동. 며칠 몇 회예요? 네. 예 구급차 지금 갈 건데요. 열 같은 건 지금 어때요? 열 증상 같은 거는? 어 열은 없는데 식은 다 없나요? 시금땀 나시고? 알겠습니다 선생님 그 부처가 지금 연근 쪽에서 출발해야 되니까 시간이 좀 걸릴 수 있어요 최대한 빨리 가라 그럴게요 예 예

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 전화 받았습니다. 예 여보세요. 저 119인데요. 예예. 예 거기 위치가 어디예요? 저 119도 나가고 있어요. 지금 그 함께하는 교회 정보 앞이거든요. 그리고 현대 부동산 앞이요. 경찰관분 현장에 계신가요? 지금? 아 저 안 계세요. 지금 저 혼자 있어가지고 저 어떻게 할지 몰려가서 가지고 전화드렸거든요. 그 지금 그분 따라가고 계신 거예요? 아 저 바로 앞에 있습니다. 현대 부동산 앞으로 가면 돼요? 아 전화 받았 지금 못 들어가서 다시 1번만 말씀해 주실 수 있어요? 현대 부동산 앞으로 가면 되나요? 예 예 그 함께하는 교회 앞입니다. 현대. 함께하는 교회요. 함께하는 교회 앞으로 갈게요. 예예 부탁드립니다. 감사합니다. 혹시 그 의식 있어요 환자분? 예 당연하죠. 네네네네. 예 알겠습니다. 예.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 한번 있어 봐. 말씀하세요. 아 여기 도봉초등학교 입구 쪽인데요. 길에. 네. 저기 자전거 사신 분이 길에 누워 계세요. 아 도봉초등학교 앞으로 가면 되죠? 네. 네. 네. 다 있는 거죠? 네? 의식이랑 이런 건 다 있는. 모르겠어요. 어. 남자분이. 네. 남자분이신 거 같은데. 눈 뜨고 있는지 안 뜨고 있는지 보여요. 그거는 잠깐만 내려야 될 것 같아요. 잠시만요. 네. 의식 있는지만 좀 해주세요. 잠깐만요. 어 야 야 움직이시기는 하세요. 아 그럼 자전거 타다가 넘어진 거네요. 이거는? 예 그러신 거 같은데 근데 지금 한가운데 누워 계시는데 지금? 예 알겠습니다. 119 그쪽으로 갈 테니까 고 앞에 있으라고 얘기해 주세요. 그러면.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 여보세요? 지금 괴로운 상태라고요? 예예예. 예. 지금 응급실 가시면 되는 거예요? 근데 추석 하셔야 되는 거예요? 가서? 그렇죠. 가서 그 그 간 막힌 거를 뚫고 추석을 해야 되거든요. 오늘 추석하는 날인데 추석을 못 했으니까. 아 그 1 9000원 임금 응급실로 이송되는데 괜찮으세요? 예예예예. 주소가 어떻게 되세요? 예 여기 구로 3동. 예예 구로 3동. 구로동이에요? 예 구로 3동. 구로 잠시만요. 예 예. 예 구로 3동. 예 한양 하이트빌라. 네 할머니 열이나 기침 뭐 코로나 관련 사항 있으세요? 아 그런 건 없어요. 그런 건 없어갖고 오늘도 병원 가셨다가 그냥 그 간이 먹히는 바람에. 저기 공휴일이라 못 들고 그냥 오셨거든요. 아 예 알겠습니다. 전화 잘 받으세요. 예예.
 수고하십니다. 여보세요. 네네. 아 여기 저거 지금 할머니가 아프셔 가지고요. 네네. 아 그래서. 어디가 아프세요? 그래서 머리도 좀 아프시고 정서 막 어지럽고 막 속도 나쁘고 막 그러신 것 같은데요. 그래요. 알겠습니다. 구급차 어디로 갈까요? 주소는요? 저 옥수 옥수 리버젠 레미안 레미안 리버젠 옥수. 옥수 레미안 리버젠. 예. 네, 집에 확진자, 자가격리자, 코로나 관련 사항 혹시 있어요? 없어요? 없는데요. 없는데요. 구급차 보내겠습니다. 전화 잘 받아주세요. 예, 예. 예.
 실례합니다. 네 선생님 안녕하세요. 저 친한 친구가 체험 체험했는지 뭔지 모르겠는데 그 체크가 있고 약을 먹고 했는데도 계속 열 열 나는 거 같다고 하는데 또 열은 없거든요. 체험 체크를 했는데. 그래서 응급실을 좀 가야 되는 정도인 것 같아요. 몸을 못 감으고 쓰러졌어요. 남자 여자요? 의식은 있어요? 의식은 네 겨우 있어요. 주소가 어떻게 돼요? 여기 청담동 자이 아파트. 말씀하세요. 청담 자이 아파트. 네, 네. 네, 그쪽으로 그 문자 보냈고요. 환자분 감기 증상이 있거나 코로나 확진자는 아니에요? 네, 아니에요. 감기 증상이 없어요. 알았으니까. 그 문자 보냈으니까 기다려주세요. 네.
 들려 봅니다. 네 여보세요? 네 말씀하세요. 네 저희 어머니가 여기 유학원에 계시는데 지금 갑자기 지금 호흡이 고단하시고 산속포화도도 안 잡힌다고 그러거든요. 산속포화도 났다고요? 네 네 네 네. 예 의식은 있어요? 아 의식 없으세요. 의식 없어요? 네. 숨도 안 쉬어요? 숨을 쉬세요. 숨을 쉬시고요? 네 굉장히 바쁘게. 바쁘게 쉰다고요? 네 네. 네 거기 주소가 어떻게 돼요? 예 하월곡동. 하월곡동. 네 로만플라자 네 요양원 요양원이 있는거죠? 네네네 두모성김 네 잠시만요 네 일단 그것도 실종했구요 의뢰지도 연결해드릴게요

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 여보세요? 소방서입니다. 아 네 여기 동천로 23길 여기 23 동천로 23길에 네 무슨 일이죠? 아 그 여기 할머니께서 걸음을 못 걸으셔가지고요. 네 어디가. 잠시만요. 잠시만요. 여보세요? 네. 예. 할머니가 여기 체장함 그때 넣으셨는데 체장함 환자인데 뭐 보호자도 없거든요. 근데 다리가 아파가지고 구름을 못 꿇거든요. 그래서 예예 저기 병행위과 한번요. 저기 하려고요. 아 응급실 가시려고요? 예예. 지금 뭐 열나거나 기침 코로나 관련 사항은 없는 거죠? 자가 경력이. 예예. 선차 맞았어요. 할머니도 선차 맞고 보호자도 다 맞고요. 보호자는 없다고 하셨죠? 아 있는데. 예 제가 지금. 예예 3차가 맞았어요 예 야 차오디 엄마 다니
 네. 수고하십니다. 여기 경로구 성신동 위하 아니 경로구 위하던 그 앞에 저기 경민사 앞이라고 아마 신고 들어온 게 있을 거예요. 경민사요? 네. 경민사. 잠시만요. 네. 이 이화동이 맞아요? 예예. 이화동 정민서가 안 나오는데 이게 무슨 일이에요? 아 거기 거기가 아니면 그린마트로 나와 있지 않을까요? 잠깐만요. 예. 어 예예. 그림마트 예 충림동 그림마트로 나와 있죠? 어 예 아까 신고 된 거 말하는 거죠? 예예. 예예. 지금 예 고재병이 왔는데. 예. 지금. 예 진료도 못 받고 있고 머리가 계속 더 아파오는데 어떻게 해야 됩니까? 진료를 왜 못 받아요? 거기서? 계속 미뤄지고 있는데. 거기서 아예 진료가 안 된다면 대기했다가 받으면 되는 거 아닌가요? 대기를 하는데 지금 이게 뭐 저 병상이 안 나온 그 있는 에. 어느 공간이 있는 거 같은데 일부러 안 받는 거 같아요. 그럼 어떻게 뭐 다른 병원 가려고 구급처 요청하시는 거예요? 지금? 아무래도 그래야 되지 않을까요? 선생님 어디가 머리가 아프다고요? 예. 뭐 폭행복 보상 당한 거예요? 아이 짠 돌로 머리로 맞았는데 그면 그게 폭행이지. 폭행 아닌가? 그럼 응급실 앞에 나와 계세요. 고대화당. 아 지금 응급실 그 천막 예 그 코로나 그 천막 찾은 데 있는데 대기소에 있는데 지금 1시간이 넘게 있는데 그걸로 가볼 테니깐요. 응급실 앞에 나와 계세요.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네, 1 2 9입니다. 말씀하세요. 여보세요. 여기 장이동. 아 주소가 어디지? 할아버지 주소가 어디지? 잠시만요. 네. 잠시만 잠시만요. 어 장이 3동에 있는 네 네. 외미안 장이 포레 카운티인데요. 잠시만요. 외미안 장이 포레 카운티 몇 동이에요? 잠시만요. 네. 네. 무슨 일이세요? 아니, 할머니가 이거 너무 아프셔서. 할머니가 어디가 괜찮으세요? 오른쪽 아랫떼랑 그 등기쪽이요. 등 쪽이요? 할머니 의식이랑 호흡은 있으시죠? 네. 할머니 최근에 코로나 관련해서 뭐 접촉했다거나 문자 받으신 거 있을까요? 할머니 코로나 접촉 받았어? 최근에? 다 받았대요. 아니 코로나 환자 뭐 접촉했다고 문자 받으신 거 있을까요? 네? 코로나 환자 접촉했다고 보건소로부터 문자 받으신 거 있냐고요? 아니요. 아니요. 아니요. 네 오늘 나가면서 전화드릴 수 있으니까 다시 한번 안내 부탁드리고요. 어 근처에 성북구 쪽에는 가까운 고급차가 없어서 강 북구 쪽에서 나가느라 한 5km 정도 떨어져 있습니다. 시간 좀 걸릴 것 같아요.
 네, 읽습니다. 어, 수고하십니다. 예. 어, 저기 그 우리 그 중 저기 저 광진구 면목로 정모팀인데요. 네. 예, 여기서 뭐 딱 오게도 떨어졌는데 뭐 좀 잠깐 병원에 가봐야 되겠는데. 주소 다시 한번 알려주세요. 주 광진구 면목로. 면목로에. 예. 잠시만요. 정호 호텔이에요? 예. 예 어디서 떨어지신 건데요? 그 위에서요. 위에 저기 떨어져서 넘어져가지고. 몇 미터 높이 몇 미터 높이에요? 한 2미터 높이. 그니까 한 의자 위에서 떨어졌어요. 의자 위에서. 근데. 의자? 1미터로 안 되잖아요. 문턱으로 떨어졌어요. 1미터 정도 높이에요? 예. 남자분이 여자분이요? 여자요. 여자분이시고 어디가 아프신 거예요? 그래서? 머리가 머리가 머리? 예. 의식은 있어요? 예 의식은 있어요. 의식은 있으시고 혹시 코로나 관련해서 열이나 기침 호흡 곤란 같은 증상은 없어요? 예 없어요. 그런 거 없으시고 선생님 관계 어떻게 되세요? 어 우리 집이요. 우리 집사람이요. 아 아내 분이시고? 예. 네 알겠습니다 선생님. 문자 보냈어요. 예. 네.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 1 1 5입니다. 말씀하세요. 아 네 수고하십니다. 아 저 다름이 아니라 지금 제 동생이 좀 아파서 어 일단 구급차를 바로 보내드리면 될까요? 그러면? 네네네. 저 부서지게 될 거 같은데. 등록 어떻게 되세요? 거기 서울 그 등록은 필운동이고요. 네 네. 필운동. 필운동. 예 예. 필운동. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 조금만 기다려주세요.
 예, 입니다. 잠깐만 여보세요. 예, 말씀하세요. 네, 여기 어르신이 쓰러져 계세요. 발탁하세요. 아, 누구 남성분이세요? 네, 남성 어르신인데. 예, 예, 예, 예, 예, 발탁하고 있어요. 격렬하고 계시고. 예, 주소가 어떻게 되세요? 위치가. 주소는 잘 위치는 잘 모르겠는데 여기 서울역 대동부동산 앞이거든요. 대동부동산이요? 네, 네. 잠시만요. 제가 검색 한번 해볼게요. 대동부동산. 네. 아 예 선생님 그 신고하셨거든요. 아 신고하셨어요? 네 빨리 와주세요. 알겠습니다. 네.
 여보세요? 여기 강일 리버파크 1003 4단지 지금 우리 아저씨가 아파가지고 지금 열이 몇 동이에요? 몇 동? 몇 호예요? 지금요 저기 수석 환자인데요 원래 코를 잘했었는데 저녁 낮에 김깁을 좀 먹고 저녁 이제 떡국 썰서 먹으러 하다가 이렇게 먹고 토하고 막 떨고 설사 싸고 지금 뭐 힘을 못 쓰고 막 있어요 열도 나신다고 하셨나요? 예 열도 예 지금 제가 제가 보니까 3 3 뭐 8.5 등 같은데요. 아 그러세요? 네. 코로나 관련성은 별도로 없으시고요? 예 그런 거는 나가지를 안 했기 때문에요. 아 그러세요? 예. 선생님 강일 리버파크라고 하셨죠? 예예. 리버파크. 리버파크 맞죠? 네네. 네 주정도 그쪽으로 보내드릴게요. 네네. 예.
 그 왜 그러세요? 저 그 그냥 여기 그 신림의 그레이라는 곳인데요. 신림의 그레이요. 그레이가 뭐 상점이에요? 뭐 술집이에요? 아니 술집이요. 술집. 예 무슨 일인가요? 아 지금 사람 쓰러지셔 가지고 예 쓰러진 분 남자분이요? 여자분이에요? 네 남자분이세요. 그레이 실린점 술집 맞죠? 네네네 맞아요. 남자분 쓰러졌고 한번 의식 앞에 출판했으니까 어, 어떻게 아픈지 의식 있는지 좀 확인 좀 해주세요. 차 가고 있는 거 같아요. 의식이 없고 숨 쉬나 가주세요. 그러면. 잠시만요. 네, 중요한 거예요. 가고 있으니까요. 숨은 쉬고 있어요. 뭐 이렇게 술을 드시다 그러신 거예요? 뭐 싸우신 거 같으신 거예요? 술 드셨어요. 뭐 완전 이사 불성 상태로 많이 드신 거예요? 그 정도까지는 아니에요? 아, 그 정도는 아니에요. 끊지 마시고 차는 출동했고요. 끊지 마시고 연결할게요. 끊지 마세요.
 감사합니다. 말씀하세요. 네 저기 저 산소가 필요한 응급 환자인데요. 네 산소가 지금 필요하시다고요? 선생님? 예 예 예 저기 이 저 저 고대 병원 고대 안아 병원 갈 건데요. 중순 환자예요. 위치 좀 알려주세요. 여기 저기 도복로? 네. 몇 층이신가요? 청기화빌라 청기화빌라 청기화빌라 누워서 지내신 분이세요? 산소가 필요한 환자인데요. 제 할아버지예요. 지금 호흡곤란이 있는 거예요? 예 호흡 곤란도 있고 여기 어깨 두기가 좀 아파서 그냥 뭐 견디지 못하네요. 의식은 있으신 거죠? 숨을 쉬시고요. 예? 의식은 있으신 거죠? 아이 그럼요. 숨도 쉬셨고요. 산소가 혹시 지금 몇 퍼센트인지 알 수 있을까요? 산소가 지금 없어요. 조금 있는데 알겠습니다. 구급대원한테 산소 필요하다고 적어서 알려드릴게요. 혹시 코로나 관련해서 해당 사항 있으실까요? 선생님? 어 없어요. 그런 거 전혀 없으세요. 알겠습니다만 전화 잘 받아주시고 그거 때문에 연락 오면 전화 아니 그 저기 산소를 갖고 와야 되는데 구급차가. 네 1번 더 말씀드릴게요. 선생님. 그 전화 화면 선생님 1번 더 말씀 좀 해주세요. 예 알겠습니다. 예.
 네, 고입니다. 아 네, 안녕하세요. 이거 주소를 먼저 말씀드려야 되나요? 네, 주소 알려주세요. 네, 여기 그 강서구 하곡동. 그 블루 모텔인데요. 네 네 네. 블루모터 무슨 일이세요? 아니 아니 저희 다름이 아니라 저희 할아버지가 몸이 지금 편찮으셔가지고 어디가 어떻게 아프세요? 어 그러니까 뭐 크게 그런건 아닌데 원래 어지러운 그런게 있으셨어요. 네. 근데 오늘 아침부터 다시 또 어지럽다고 하시고 아침에 식사를 했는데 네. 계속 지금 그 토하고 그래가지고 모텔에 계신 거예요? 할아버지가? 그니까 저희가 이제 모텔에. 그럼 가면 돼요? 모텔. 네네네. 가정집이에요? 네네네네. 아 지금 차는 보냈고요? 네네. 그 열 있거나 기침 콧물 있으세요? 할아버지? 아니요. 아니요. 그 패스 차 맞으셨어요. 아 따로 가족분들 중에 확진자나 경위자 없으시고요? 네네. 저도 지금 다 주가 맞았어요. 예. 차 보냈으니까 좀 기다리고 계세요. 네.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네 여보세요? 아 예 저 저가 지금 너무 아파가지고요. 어디 없어요? 아 오늘 해물은 먹었거든 갈비를. 네. 아 그랬는데 출산하고 토하고 했는데 배가 너무 아파요. 알겠습니다. 뭐 고급차 타고 병원에 가실 건가요? 예 그렇게 할 것 같은데요. 예 주소 불러주시면 출동 나갈게요. 예 청량 동대문구요. 동대문구. 청량 1동. 청량 1동이요? 청량 2동 에. 2주 아파트. 음. 2주 아파트 맞으시죠? 예. 예. 동대문 세무서 뒤쪽에 있고 맞죠? 거기요? 예예예. 예. 코로나 환자는 아닌 거예요? 선생님? 예. 아니에요. 예 출동해볼 테니까 전화 옵니다. 잘 받아주세요.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 글레이고입니다. 아 예 그 환자가 있으셔 가지고. 네 환자분이 남자분이에요? 여자분이에요? 예 그 남자분이시고요. 고종이 불편하신 그 암투병 분이신데. 네. 예 좀 상태가 안 좋으셔 가지고. 상태가 어떻게 안 좋아요? 의식 있어요? 없어요? 의식이요? 의식은 있으세요. 의식은 있고 숨 드시고 있는데 지금 어떤 상태예요? 어 숨이 각고 하시고요. 그. 호흡이 곤란하세요? 예 예 예 예. 예 아들님 계세요? 사위입니다. 사위이신데요? 예 주소는요? 여기 주소가 오목로 오성아트빌 예 예. 네 지금 호흡이 많이 곤란하신 상태예요? 예 그리고 이제 눈을 잘 못 드셔가지고. 혹시 거기 가족 중에 코로나 환자나 고혈 기침 인후통 증상 있는 분 있으신가요? 전혀 없습니다. 전혀 없으시고요. 고객차는 지금 가고 있고요. 제가 의료 지도해드릴 거니까 잠시 끊지 마시고요.
 어 알았다. 어 알았다. 여보세요? 네 지금 애기가요. 예 넘어져가지고 발목을 띄웠거든요. 선생님. 무너진 것 같아요. 네네네. 부탁드립니다. 지금 어 어 어 어 신동아 팀밀리 아파트. 신동아 팀밀리 아파트 몇 동 몇 동? 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네.
 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 주소를 말씀해주세요. 네. 이게 무슨 일이에요? 다 오는 거예요. 누가요? 뭐... 이틀 때. 예? 네. 말씀해 주세요. 누가요? 오늘 친구들 다 오놨네요. 예. 관절에서 오는 거 아니에요. 그 저희 뭐 소방서로 전화하셨는데. 싸우고 있다는 거예요? 싸우고 핏 많이 있어요. 핏 교수도 있어요. 그러니까 네 네 본인은 지금 아 아 아 아 아 아 아

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네 119입니다. 아 여보세요? 네 말씀하세요. 네 저희 남편이요. 네 저기 뭐지 가슴이 아파갖고 토요일 날 못 쉬고 그래서. 호흡 혼란이 있어요? 남편분이? 네 이게 기침이 심해가지고. 지금 병원 응급실로 가야 되는데 거동이 안 돼서 119로 가야 되는 거예요? 네. 제 신고 주소를 좀 알려주시겠어요? 여기 서대문구 저기 북과자동. 북과자동. 예 응압로 응압로 국가에서 현대아파트 DMC 현대아파트 신고자분 환자 계층 곳이 DMC 현대아파트 맞아요? 맞아요? 저기 환자 남편분 호흡곤란 네 네. 왜 열이 열이. 의식은 있는 거죠? 손 모시거나 이런 거 아니죠? 네. 거기가 과자 북과자 초등학교 바로 앞에 있는데 거기예요? 네. 어 거기가 보니까 건물이 크게 과자 제일 교회 앞에 있는데 거기. 네 네. 한양 아파트 가봐. 1동 있는데. 1동이에요? 혹시? 네. 한양 아파트 앞에 있는데 밑으로 내려갈 수는 있어요. 살살 걸어서. 일단 친구야 일단 차는 출동했고요. 끊지 마시고 순간 차들이 다 출동 나와서 한 5km 떨어진 데서 와서 시간이 많이 걸릴 수 있고요. 3년 동안에 의료진 연결할 거니까 끊지 마세요. 말씀해 주세요.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 여보세요? 네 119 상황실입니다. 예예. 예 남성분이세요? 그 벤치에. 남성분이 있는데 예 술을 시기 하신 것 같아요. 예 근데. 예. 지금도 보고 계세요? 예 지금도 여기 계세요. 아 움직임은 있으세요? 아 움직임 말은 해요. 뭐 여기서 주무시면 안 되세요. 그랬더니 그러면 어디서 자요 이러는데. 아직 경찰서 요청 안 하신 거죠? 예예 안 했습니다. 예 감사합니다.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 예 119입니다. 네 네 수고하십니다. 제가 65세 할아버지인데요. 예 예 병원에 지금 검사를 받으러 가는데 이불에서 일어나가지고 서면은 쓰러져서 혼자서 할 수가 없어요. 119 좀 부탁할게요. 환자가 뭐 고동이 안 돼서 119로 응급실 가야 하는 상황인 거예요? 예 예. 뭐 힘이 없어서 그런 거예요? 어지러워서 그러신 거예요? 힘도 없고 어지럽고 여러 가지 조건이 있네요. 근력도 없고. 고동 불가 위중은 괜찮은 거죠? 맞았으면 하시고 뭐 코로나 관련 뭐 열 기침은 없으신 거죠? 예 예 예. 할아버지 계신 곳 주소가 어떻게 되나요? 예 양천구 목동 아파트. 목동 신시가지 아파트예요? 예예 예예. 네네. 같이 계시죠? 환자분이랑. 예예예 같이 있어요. 주차가 출통했으니까 거기가 신목 중학교 바로 뒤에 있는 대목이 맞죠? 아니 신목 중학교 아니 아니에요. 신목 고등학교 예 신목 고등학교 예예. 알겠어요. 구청하고 있으니까 병원 준비하시고 문 열어주세요. 출통했습니다. 몇 몇 분 걸려요? 한 1.5km 떨어져 있으니까 한번 갈 것 같아요. 네 알겠습니다. 감사합니다.
 잠시만 계세요. 아 안녕하세요. 여기 지금 노량진역 5번 출구 쪽인데요. 아 어떤 아저씨께서 에스컬레이터에 넘어지셔서 찢어지셨네요. 어디가 찢어졌어요? 어 눈두덩이 좀 찢어지시고 지금 피 흘리고 계셔가지고. 노량진역 9호선 5번 출구 나가면. 5번 출구인데 지금 지하 쪽에 조금만 내려오시면 돼요. 에스컬레이터. 예 그 그 노량진역 안으로 들어갈게요. 네 감사합니다. 다음 영상에서 만나요.
 네. 119 상황실이에요. 교통사고 뭐하고 뭐하고 뭐하고 부딪쳤어요? 119 상황실이에요. 아 저 비접촉 사고. 비접촉이요? 음 갑자기 본인께서 피해자신 거죠? 제가 예. 넘어지신 거예요? 네. 지난 잠시만 제가 방초교회가 주위 건너편에 있으시다고요? 큰길 건너편이에요? 네, 큰 큰일 관광장. 여기 경찰관 분들 계시고 와주시거든요? 네, 경찰관 좀 바꿔주세요. 아, 왜요? 바꿔달라고 하셨는데. 예, 일상 상관실이에요. 아, 네, 고맙습니다. 예, 고생하십니다. 방초교회 쪽으로 지금 구구차 가고 있는데 방초교회 건너편이라고 하셨는데 그 그러면은 어디 쪽이에요? 그 방초교회 바로 그 도로 건너편에 서초 2SA 3차 있어요. 2SA 3차 고 앞이신 거예요? 네네 그쪽 들어가는 골목 어 알겠습니다. 차 그쪽으로 어 어 보냈습니다. 기침이나 열 목구멍 통증 있는지 좀 파우션 해주실 수 있으세요? 어디 없으세요? 기침이나 열 목구멍 통증 같은 코로나 증상 아 선생님 코로나 증상 있으세요? 지금? 여기다 없습니다. 알겠습니다. 차 가고 있습니다. 비접촉상으로 하고요? 예 그렇습니다. 알겠습니다. 네 수고하십시오. 네 수고하세요.
 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 어 마포구 전달이로 하이비 오피스텔 잠시만요. 전달이로 오피스텔 네 이게 어 아니면 근처에 응급차량이 거동이 안 될 때만 불리시는 건가요? 어 자력으로 이동 가능하시면 가시는 게 맞고요. 아 그래요? 기여를 얼마나 뜯었어요? 어 어 그 살이 들려요. 네 일단은 고객센터 갈 테니깐요. 갈 때까지 지혜 좀 보고 계시고 혹시 열나거나 감기 증상은 따로 없으시죠? 아 네 그냥 방금 받쳤어요. 아 그 지혜 좀 꼭 하고 계세요. 눌러가지고. 네.
 네 읽습니다. 저희가 지금 그 IBK 기업은행 여의도 홍대 쪽에 있는데요. 여의도 IBK 뭐라고요? IBK 기업은행 홍대역 쪽에 있는데요. 기업은행 어느 쪽에 있다고요? 홍대점. 홍대점 예. 네 거기서 지금 스태고가 너무 스태고가 너무 스태고가서 차가 하나도 안 적히거든요. 예. 저희 좀 도와주세요. 어떻게 도와드려요? 병원으로 못 추고 가요? 어 호텔이나 병원이나 아무 곳이나 좀 데려갈 수 있을까요? 그니까 저희는 호텔이나 집으로는 119가 왜 있습니까? 술 취한 사람들 집에 데려가는 건 아니잖아요. 아 그쵸. 병원으로 가실 거면 병원으로 집으로. 아 병원으로 데려가 주세요. 잠깐만요. 취소 거기 검색 좀 해볼게요. 네. IBK 기업은행 홍대역 지점 말씀하시는 거예요? 네. 지금 뭐 토를 했어요? 네. 여자예요? 남자예요? 여자예요. 수치자 구토 또 어떤 증상이 있어요? 그냥 길바닥에 쓰러져서 계속 토하는 상태예요. 응급실 이송 저희가 할 건데 응급실 가실 거죠? 응급실 아니고 다른 데는 못 갑니다. 네 네. 네 출동할게요. 기업은행 홍대점 앞에 계세요. 네.
 일리보 입니다. 네 저 인급한 상황이라서 병원 가야 될 것 같은데요. 누가 어디가 아프세요? 제 본인이 뭐요? 어디가 아프세요? 어 3시쯤에 갔는데 지금 일어나는 일어나는데 왼쪽이 다 마비예요. 저 왼쪽에 마비가 왔어요? 네 그래서 아예 네 주소가 어디세요? 여기 암사동 암사동 몇 번지예요? 여기 고동물 잠시만 다시. 고동물 아 예 예. 네. 로치하임이에요? 네. 네. 네. 혹시 코로나 관련 증상은 없으신 거죠? 네. 없어요. 네. 전화는 끊지 마시고요. 네. 잠시만요. 네. 네. 네. 네. 네. 네. 네.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 여보세요? 네 선생님 핸드폰 번호로 문자가 들어왔네요. 네네네네네 거기 저희 할머니가 계신데 지금 편찮으셔 갖고 막 말씀 못 하시거든요. 아 그래요? 할머니 혼자 계세요? 네네. 아 할머니 전화번호하고 성함 좀 알려주세요. 차 안 출발 시켰어요. 아 거기 잠시만요. 네. 녹색 대문으로 들어가면 있는거죠? 맞나요? 네. 핸드폰인가요? 네. 차는 출발시켰고요. 지금 할머니 혼자 계세요? 네네. 저도 지금 그쪽으로 가고 있는데요. 아 그래요. 할머니 지금 어디가 불편하신지는 모르시고요? 뭐 소화가 안 되시는 건지 숨이 안 쉬어지시는 건지 모르겠어요. 아 통화는 되긴 되는 거죠? 근데 지금은 모르겠어요. 아 그래요. 마지막 연락하시는 언제예요? 한 5분 10분 전이요. 아 그래요. 알겠습니다. 우선 우리 구급차는 가고 있고 혹시 이 문이 열리는지 안 열리는지는 모르세요? 열려 있을 건데 아 제법은 열어놔요? 그래서 제가 그것 때문에 그것 때문에 제가 가고 있거든요. 아 그래요? 우선은 그러면은 저희 구조대원분들하고 같이 나갈게요. 혹시 이거 뭐 비밀번호 아니고 그냥 키로 되는 거죠? 네 알겠어요. 우리 구조대원분들하고 그러면은 우리 구급 대원분들하고 같이 나가볼게요. 네 혹시라도 문 안 열리면은 문 파손하고 들어가는 것도 동의하세요? 예예 대원들 전화드릴 겁니다.
 예 일곱니다. 아 예 여기 상도로 30일 길 예예. 브라운수턴 맞아요? 네. 무슨 일이세요? 아 토하고 설사하고 하시는데요. 아 누가요? 아빠가요. 의식은 있으시고 구토하고 설사가 있으신데요? 어 예 지금 방금 구토하셨고 이게 한 1주일 정도 됐거든요. 구급차가 필요하신 거죠? 지금은? 네네. 네, 기원들 나가기 전에 코로나 관련해서 여쭤봐야 될 게 하나 남았어요. 최근에 기침 고유 같은 코로나 관련 증상 여행역 특이사항 혹시 있으세요? 예, 예, 없어요. 기원들 나가면 돼 전화 받으시면 다시 한번 안내해 주세요. 차 나갑니다. 예, 예, 네.
 119니다. 말씀하세요. 아 네 저기 애기가 바닥으로 이렇게 떨어졌는데 여기가 입술 쪽에 피가 나고 이빨이 풀어진 것 같은데 막 볼라 그러면 다 질어져요. 애기가 지금 몇 살이에요? 애기가 잠깐만요. 5살이지? 5살이요. 5살이고 지금 넘어져서 지금 이빨 쪽이 깨진 것 같다는 거죠? 입술 쪽이? 그러니까 예 이렇게 부러진 것 같아요. 이빨도 근데 막 안 보여지고 예. 아 일단 알겠습니다. 1번 나가볼 거고요. 주소가 어떻게 되나요? 어 어 오신다고요? 아니면 뭐 저희가 어떻게 도와드릴까요? 의료 상담이나 병원 안내 이런 걸 안내해 드릴까요? 어 오실 수 있으면 오시면 좋은데. 그러니까 저희가 가게 되면 가까운 병원 응급실로 이송을 해드리거든요. 그렇게 도와드리면 돼요. 어 어 잠깐만요. 죄송해요. 세뇌고에서 오신데 좀 나 차 타고 가서 응급실 갈래? 응 응 응급실 가서 일단 보면 되지 애가 저러니까 그럼 오시라 그런다? 예 여기 마포구 월드컵로. 예. 네. 바우하우스. 네 알겠습니다. 네 네. 뭐 아기가 코로나 관련해서 연이나 기침 민원님과 있나요? 어 없어요. 우리 아무도 네. 알겠습니다. 조금만 기다려주세요. 아 고맙습니다. 네.
 129입니다. 네. 죄송한데요. 자전거 타고 오다가 너무 자고 무릎이 그걸 왜 쪘는데. 지금 고급차가 필요하신 거예요? 의료 상담이나 병원 안내가 필요하신 거예요? 음 고급차까지 네? 고급차까지 필요하다고요. 거기 거기 거기 어디를 다쳤어요? 무릎 다쳐서? 예, 그 전골이라고 그러게 되네요. 계신 곳 주소가 어떻게 되나요? 계신 곳 주소가? 어, 암사이동. 암사이동. 네. 몇 층 몇 호에 계세요? 네. 고유차가 가고 있고 뭐 코로나 관련 뭐 열이나 기침이나 이런 건 없으신 거죠? 무릎만 다치신 거죠? 예. 고유차 가니까 문 열어주세요. 가고 있어요. 암석용.
 119입니다. 예 여기에 할머니가요. 예 의식이 없으셔 갖고요. 예 응급실 가서 해야 될 것 같아요. 예 의식이 전혀 없어요. 불러도 눈을 못 뜨세요? 반응도 없고? 예 불러도 대답도 안 하시고 그냥. 눈을 안 떠요? 뭐 소리도 안 내요? 부르면은 뭐 어 이런 대답도 안 해요? 그냥 그냥 으앙 그렇게만 계속하세요. 의식 의식이 없고 뭐 끙끙 앓는 소리만 내요? 엄마 엄마 엄마? 선생님? 네네네. 반응이 전혀 없어요? 지금은 눈을 조금 뜨신 것 같기도 한데 대답은 없으세요. 아 소리에 눈만 떠요? 아니요. 아니요. 소리에 눈 뜨는 게 아니라 지금 대답을 전혀 못하세요. 아 그러니까 부르면은 눈을 이렇게 살짝 떠요? 코 고는 소리가 떠요? 아니요. 아니요. 아니 코 고는 소리가 아니라 그냥 끊고 알리는 소리 같기도 하고 그런데 예예. 주소 알려주세요. 응? 주소. 자꾸 몸을 들고 비추세요. 예 주소 알려주시고요. 코어 보편하고 계시죠? 예 그러신 것 같아요. 주소요. 예 진관동. 네. 우물골. 네. 지번이에요. 진간동 예예예. 예예예. 당뇨 있어요? 할머니? 당뇨요? 네. 차는 보내 당뇨는 없고요. 혈압은 있으신 걸로 알고 있거든요. 아 차는 보냈는데요. 혹시 현재 열 있거나 기침 콧물 있었어요? 아우 같이 안 살아갖고요. 저도 지금 전화받고 왔거든요. 아 따로 코로나 때문에 격리 중이시거나 확진자 있거나 같은 그런 거 없고요. 3차 예 3차 다 맞으셨어요. 보냈고요. 선생님 좀 기다리고 계세요. 그니까 호흡 잘 하고 있으시죠? 예 호흡은 좀 하고 계신 것 같아요. 못 일어나시는 것 같아요. 알겠습니다. 예.
 여보세요? 1 2 9입니다. 여보세요? 1 2 9입니다. 말씀하세요. 예 여기 홍은동 극동 아파트. 네, 네. 누가 아프신 거예요? 예? 남편 어디 아프신 거예요? 많이 저기 아 중증 환자인데 지금 열이 많이 나고 근데 그저 어제 그저께 저기 코로나 검사를 받았는데 음성으로 나왔어요. 근데 지금 또 어제도 병원에 그냥 갔다 왔는데 그 전립선에 염증이 있다고 급성으로 왔다는데 그 지금 이 환자가 서울대병원을 다니니까 또 열이 나면은 그냥 서울대병원 응급실을 가라는 거예요. 그런데 지금 39도까지 열이 올라갔어요. 지금 열이 높다는 거죠? 의식이나 그런 거는 괜찮아요? 예 의식은 있는데 그런 거는 명료한데요. 네. 열이 높으시다는 거죠? 다른 거는 괜찮으시고요? 예 열이 높고 지금 중증 환자라 이 양반이. 무슨 병명이 뭐예요? 병명은 이제 간암에다가 막 그냥 간이 많이 안 좋아요. 음 간암 환자라는 거죠? 예. 산은 북동 아파트 그러면 서울대병원으로 좀 데려다 주세요. 그 병원은 병원 선정은 저희 여기서 하는 게 아니고 추동한 고급 병원에서 하는데 그거 병원에 거기로 가는지 안 가는지 그것까진 제가 잘 모르겠어요. 예 차는 나가 볼게요. 전화 잘 받으세요.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네 119입니다. 아 예 저 환자분이 저기 46살 여자분이신데요. 아 예. 예 근데 저기 저녁 아니 낮에 이렇게 한 4시로부터 식사하면서 소주 한잔을 먹었어요. 근데 어지러워 갖고 지금 일어나지를 못했거든요. 아 어지러우시더라고요? 뭐 소주 드셨죠? 네. 예? 술 드셨다고요? 네 술을 먹었는데 그런 술 먹고 챙긴 게 아니고 어지러워서. 아 알겠어요. 네. 막 예 여기가 어디냐면 오늘 통닭집 수유 오늘 통닭집 앞에 있거든요. 이름이 오늘 통닭집이에요? 네 오늘 통닭 수유 잠깐만요. 현대병원 옆에 있습니다. 아 네 잠시만요. 좀 확인 좀 해보니까. 현대병원 가기 뭐 해갖고. 네. NS 쪽이 없어갖고. 아 그래갖고 일로 전화를 갖다 119 일단 전화를 했거든요. 아 예. 서울 성심위원 입구 그쪽인 거죠? 그 건물에. 서울 성심위원이 아닌데. 그래요? 현대병원? 현대병원. 파리바게트 입구 현대병원 있는데요. 어 그 옆이라고요? 조금 거리 거기서는 조금 떨어져 있지 않아요? 현대병원에서 10m 옆에인데요. 아 10m 그 골목 들어가서 그쪽인 거잖아요. 네네네네. 오늘 됩니다. 우체국 버스정류장 그쪽인가요? 네네네네네. 알겠어요. 이쪽으로 보내드릴게요. 혹시 열나거나 기침감기 증상 코로나 격리 중이신 건 아니시죠? 그런 건 없고요. 그런 건 없고요. 네. 네. 감사합니다.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 예, 여보세요? 예, 예, 수고하십니다. 저기. 네. 예, 여기 뭐. 여기 왔더니 형이. 네, 네. 이 저기 이거 저 맥이 없네. 숨을 안 쉬어요? 예, 예. 주소 알려주세요. 예? 주소. 천 여기 저 삼계동. 예. 무슨 아파트예요? 주공 아파트요. 삼계 주공 아파트? 예, 예. 아 몇 호예요? 예예. 아 잠시만요. 선생님 고객센터 보내드렸고요. 저희가 의료지도 연결해서 응급체치 안내할 거예요. 전화 끊지 마세요. 예? 전화 끊지 마시고요. 저희가 의료지도 연결해서 응급체치 안내할 거예요. 전화 끊지 마세요. 예예예. 열쇠가 또 좋네
 1 2 5 입니다. 네 여기가 공독동 네 네 저희 어머니가 몸이 좀 불편하세요. 지팡이를 좀 짓고 계시는데. 좀 넘어지셨는데 지금 저도 연락받고 바로 왔는데 다리가 굉장히 심하게 많이 부었거든요. 아예. 아. 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 감사합니다.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 예, 읽습니다. 여기 경찰서인데요. 어디에요? 동암에 동암 파출소요. 동암 파출소인데요. 동암 파출소에. 네, 와주세요. 저 다쳐가지고. 무슨 일이세요? 경찰 업무는 다 끝나셨어요? 아니면. 아, 경찰이 저 저 진압할 때 무료급으로 진압해서 다쳤거든요. 자, 경찰 업무는 끝났어요? 안 끝났어요? 아, 이게 안 와 조사를 안 해야 되는데 이제 와주세요. 조사 진행 중이면 병원 이동이 안 될 수 있는데 괜찮으세요? 네. 교수들 나가 있으니 전화받고 잘 안내해주세요. 지금 전화번호는 어디에요?
 입니다. 무슨 일이세요? 네 여보세요? 예 말씀하신 무슨 일이세요? 아 저희 어머니가 지금 많이 생산이신데. 어머니가 어떻게 안 추우세요? 아 지금 열도 나고 저기. 네? 고열등상하고 또 어떤 증상이 있으시다고요? 대상포진 증세인데요. 대상포진 있다고요? 그런데 허리가 안 좋아서. 벗지를 못해서요. 허리 다 부시고. 네. 계신하고 주소지 어떻게 되세요? 그래서 93 아니. 여기 여기. 하블로 지금 장사고. 곰달래로? 예. 네. 네네. 그쪽으로 구호차 보내드렸고요. 기치나 열 목공원 통증 같은 코로나 증상은 없으세요? 예예 없는 것 같은데. 알겠습니다. 저 가고 있습니다. 네.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 예, 119입니다. 네, 여보세요? 네, 119입니다. 네, 저 다름이라 그 혹시 그 뇌진탕 증세가 지금 있는 거 같아서요. 무슨 증상요? 뇌진탕이요. 뇌진탕 증상요? 네. 뇌진탕 증상 여보세요? 네. 수정 그리고 저 병원에 가신다 가실 거죠? 병원에 가게 되면은 그 자리는 있나요? 아 자리는 있는지 없는지는 여기서는 확실히 아직 일단 응급실에 가죠. 아 그 뭐지 그 병상이 막 부족하다고 해서 줄어서 혹시 가서 이렇게 오래하나 해서 많이 지금 뭐 열하고 기침 같은 거 있어요? 아니요. 그냥 지금 코로나가 그냥 이거 비엿 때문에 나올 것 같고요. 기침하고 열만 없으면 뭐 금방 들어갈 수 있을 건데요. 아 네 알겠습니다. 여보세요? 네 지금 병원에 가실 거예요? 네 부탁드릴게요. 그러면 뭐 구구 쪽 보내드려요? 아 네 부탁드리겠습니다. 네 주소 불러주세요. 네 여기 서울시 동작구 성도동이고요. 네? 상도동. 주택이에요? 빌라에요? 네 빌라에요. 본인이시구요? 네. 넘어졌어요? 네 그 뭐지? 그 아래층에서 계단 한 두 발자국 남았을 때 거기 전단지 밟고 넘어졌을 때 예 예 선생님. 예 계단 낙상요. 계단 낙상 내진탕. 지금 뭐 계단 낙상 내진탕은 아니네 그죠? 계단 낙상이요. 그냥 머리 머리 통증요. 머리 통증 그리고 최근에 기침하고 열 코로나 관련해서 의심할 만한 거 혹시 있었나요? 아니요. 네 감기 증상 근데 지금 이제 비염 비염은 있고요. 코로나 관련 없고요. 예 감인서 전화하면 전화 잘 받으세요. 접시됐습니다.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 예, 좋습니다. 안녕하세요. 저 그 제가 그 신생이 좀 빨리 뛰어가지고 그 심전도 검사 받으려고 했는데 큰 병원 전화하니까 119에다가 전화를 하라고 해가지고 전화드렸습니다. 병원 안내가 병원 안내가 필요하신 걸까요? 어 그냥 저 그냥 심전도 검사만 받으면 돼가지고. 구급차 보내드려요? 병원 안내를 해드려요? 구급차 보내주시면 감사합니다. 주소 계신 거 장소 알려주세요. 병원 가시려고 전화 주신 거죠? 그러니까 지금? 네, 네. 주소 기준으로 장소 알려주세요. 지금 주소가 아 잠깐만요. 여기 주소 어디냐 어떻게 보냐. 길거리에 계시면 고객님 한 번 불러보세요. 네? 길거리에 계시면 고객님 간판 한 번 불러보시라고요. 간판이요? 예. 여기 노원역 GS25예요. 노원역 GS25이 무슨 지역이에요? GS25 잠시만요. 죄송합니다. 몇 번 출구 쪽에 있는 거예요? 2번 출구요. 2번 출구 앞에는 노원용 기회 25시로 차가 나갈 거고요. 전화 받으시고 주시고 최근에 비친 고 1 같은 코로나 관련 증상 여행용 특이사항 없으시죠? 네 없습니다. 전화 받으시면 안내해 주세요. 감사합니다.
 네, 연락 봅니다. 네, 제가요. 배가 너무 아파가지고요. 네, 잠시만요. 어, 예. 원래 지병은 없으시고 갑자기 아프세요? 아, 알겠습니다. 네, 선생님 뭐 11시간에 코로나 관련 일요 없으시고요? 예, 예. 네, 주소 말씀해주세요. 주세요? 네. 저기 저기. 네. 아이 저기 잠깐만 기다리실래요? 네. 여보세요? 여기 중산구 동일로. 동일로 네. 123길. 잠시만요. 중성구 동일로 123길. 네. 동일로 123길이요? 네. 네 맞아요 몇 층 몇 호에요? 지하에요 반지하 지하 반지하 호스는 따로 없어요? 예 호스는 없어요? 1 2 이렇게? 예 예 알겠습니다 지금 우짜 출발하겠습니다 예
 감사합니다. 네 여기 저기 저희 아버님이 지금 조금 안 좋으셔서 아무래도 1 2 9로 병원을 가야 될 것 같아요. 어디가 아프세요? 지금? 원래 혈압약을 주시는데 아 제가 밑에 찾고 묻었는데 사람을 어제부터 안 드신 거 같아요. 약이 없더라고요. 근데 오늘 공휴일도 하고 그래서 응급실 가서 좀 조치를 받아야겠고. 혹시 따른 뭐 그 숨 쉬거나 의식이 문제는 없는 거죠? 숨 쉬는 건 괜찮은데 일단은 말씀 잘 못하시고. 음 잘 거치를 못하고. 혹시 지금 사람 복용 중이시고 지금 뭐 갑자기 의식이 떨어진다거나 혹시 뭐 그런 사항은 있어요? 없어요? 지금 살짝 의식이 좀 그러신 것 같아요. 그러시죠. 잠깐만요. 여자들 지금 코로나 관련 사항은 없으시죠? 집에 자가 격리나 코로나 확진자나. 예 없습니다. 주소 어떻게 돼요? 예 저기 서울 중남구. 예. 건염 캡스빌 아파트. 예. 네 네. 자 그럼 구급차 보내겠습니다. 전화 잘 받으세요. 네 네.
 네. 여기 그 미래 성파로 미래 포레션 15단지 잠시만요. 네. 네. 네. 네. 네. 말씀해 주십니까? 아유 그 와이프가 이 가위에 좀 저기 뭐라 해야지 손목 저기 흰줄 있는 쪽 있잖아요. 네. 네 이런 이 근처 부위를 좀 많이 이렇게 적어내가지고. 가위에 흰줄 같은 거? 네. 음 뭐 혹시 자해하셨어요? 어 근데 좀 네. 음 알겠습니다. 예. 지금. 검사 보냈고요? 네. 네. 네. 네. 출혈이 있으시겠네요. 그럼 지금? 네. 출혈이 있는데 지금 어휴 지혈은 된 것 같은데. 무슨 줄 몰라가지고. 네. 코로나 관련된 거는 없으시죠? 네. 없어요. 최근에도 검사하고 음성. 음 네. 알겠습니다. 예. 저희 구급차가 지금 좀 멀리서 출발했으 선생님. 저 가락에서 출발했거든요. 관악에서요? 가락 가락. 아 가락이서요. 총파락이 있는데 예 그래서 시간이 제가 봤을 때 한 10분 이상 걸릴 것 같아요. 예. 아 네 알겠습니다. 예. 네.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 예, 알겠습니다. 네, 저희 아버지가 많이. 아버지 계세요? 네, 허리가 너무 아프셔서. 예, 예. 네, 앰블루스를 좀 불러달라고 하시. 아, 허리가 아프셔 가지고요? 예, 기존 어떻게 되세요? 동일로. 예. 180길. 예. 네, 청아시 때. 아버님 지금 열 증상 같으면 어떠세요? 그니까 저희 아버지가 술을 좀 약주를 많이 좀 하신 편이에요. 그래서 지금 소파에서 좀 많이 치워 그니까 소파에서 쓰드셔갖고 그니까 소파에 소파에 많이 소파에 부딪혀갖고 지금 누워가고 계셔요. 알겠습니다. 문자 가볼게요. 네. 감사합니다.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네 안녕하세요. 제가 식중도 오긴 거 같은데. 네네. 아 병원 가시는 거예요? 지금 다 같은 정상으로 병원에 갔거든요. 네네네. 아 오한들고. 여보세요? 5분하고. 아 네네 오한들고 9도 있어요? 네. 아 뭐 고급창을 병원 가시려는 거예요? 주소 어떻게 돼요? 강남구 천성로. 천성로. 135길. 135길에. 네네. 3 아르죸? 네네. 맞아요. 왜 열은 없어요? 몸에? 열은 없는 것 같아요. 아 따로 코로나 때문에 격리하시는 분이나 가족분들 중에 확진자 있거나. 없어요. 차는 보냈고요. 구호차가 조금 멀리서 가요. 상수동 쪽에서 좀 기다리세요. 네.
 예 감사합니다. 예 예 예 예 선생님 예 아이가 지금 넘어져서 이마에 열상이 있는 거예요? 예 선생님 위례 예 예 위례 기업 프로 지역 몇 등 몇 회예요? 알겠습 알겠습니다. 선생님 지금 고객차를 타고 병원 가보실라 그러는 거죠? 아 네 예 예 예 알겠습니다. 고객차로 그쪽으로 가볼게요. 아 네 알겠습니다.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네. 안녕하세요. 입니다. 아 예. 아이고 수고 많습니다. 새해 복 많이 받으십시오. 예. 감사합니다. 선생님. 예. 예. 다름이 아니고 저희 엄마가 지금 좀 위중합니다. 그래서. 어머니 연세 어떻게 되세요? 지금 저 100일 세요. 아 지금 호흡이 좀 곤란하시네요. 그죠? 소리가 이상하시고. 예예예. 음식은 있으세요? 예. 선생님 저희 일단 차 2대 출발해야 될 것 같아요. 주소 좀 알려주세요. 아 예. 그 저. 예. 용도동. 예 동대문구 용도동. 네. 네. 어머니 좀 호흡소리가 이상하시네요. 그죠? 예예. 예 급성 퇴렁 된 거 같는데 내가 보니까. 이거 빨리 좀 빼내야 될 것 같은데. 예 알겠습니다. 아 그러면서 이게 그. 퇴렴 퇴렴. 예예예. 그렇게 싶습니다. 급성 퇴렁으로 지금 진행되는 것 같네요. 네. 네. 지금 첫 번째로 할게요. 예예. 감사합니다. 예. 감사합니다.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 입니다. 여보세요? 예, 말씀하세요? 네, 여기 식당인데요. 예, 예. 지금 어머니가 지금 그 칼질하다가 손이 지금 확 들어가 갖고 좀 급하게 가야 될 것 같은데. 아 그럼 칼에 손을 베이신 거예요? 네. 심하신 거예요? 예, 지금. 아 예, 주소는 어떻게 돼요? 가마산로. 가마산로. 잠시만요. 영등포구 영등포구 가마산로. 아 식당 이름이 뭐예요? 한 끼 한 주기요. 한 끼 한 주? 네. 알겠습니다. 아 나 꼭 누르고 있더라고.
 네 수고하십니다. 여기 좀 급한데 환자가 생겼는데요. 계신 거 위치가 어떻게 돼요? 여기 저 저 저 봉촌 1동이요. 봉촌 1동. 단국. 선생님 그런 주소가 없는데 주소 다시 한번 확인해 주세요. 어 단곡 6길. 단곡 6길. 몇 층 몇 회요? 어 미성불리아 네 네 환자분 남자 여자요? 여자요 지금 힘이 안 찌는 것 같은데요? 얼굴이 차갑고 의식이랑 호흡이 전혀 없어요? 예 숨을 안 찌는 예 선생님 과한동 업무터치 안내하는 부처 연결할 테니까 끊지 마시고 기다리세요 네

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네, 119입니다. 119입니다. 119입니다. 말씀하세요. 여보세요? 네, 말씀하세요. 119입니다. 아 네, 여기 집에 올라가다가 계단에서 넘어졌던지. 네. 근데 지금 피를 이렇게 흘리고 있거든요. 근데 제가 입에서 흘리는 건지 여기 머리에서 부딪쳐서 흘린 건지 잘 모르겠어가지고. 누가 누가 그런 거예요? 아 친구가요. 여성이요? 남성이에요? 남자예요. 주소 좀 알려주세요. 어 여기가 잠시만요. 여기가 증가로 24락일 24라면 할 때 락일. 네네. 그리고 적혀 있거든요. 정우 정우빌라요. 정우빌라? 몇 층 가면 돼요? 몇 층? 지금 1층에 앉아있어요. 정우빌라? 네, 네. 뭐 남성 지인분이 계단에서 넘어지신 거라고요? 네, 남자아이가. 알겠어, 실패하겠습니다.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네 여기 갑자기 아버님 지금 계속 통으로 쓰러지셔 가지고 그러는데. 아 의식은 있으세요? 선생님? 네네네. 아 거기 주소가 어떻게 될까요? 여기 보강도 리버빌 아파트. 선생님 보강도 몇 번지예요? 보강도 5길 보강로 5길이에요? 5길 5길 리버빌 아파트. 네 네 네. 구급차 갈 거고요 선생님. 저희 응급실로 갈 건데 아버님 지금 혹시 열이 난다거나 감기 증상 있으세요? 그러진 않으세요. 일주일 전에 대충 나주셨었거든요. 혓도 많아세요 지금? 머리가 아프다고 그러시고 지금 계속 토 하거든요. 아 열은 안 나시고요. 네 네 네. 열은 안 나죠 어머님. 아 열은 안 나요 땀 계속. 아 부업 때 가니깐요. 전화드릴 거예요. 병원 관리 중이라고 계세요.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네 안녕하세요. 저기 환자분이 지금 허락이 떨어지고 그래서 부탁드리려고 전화드렸는데요. 일단 주소가 어떻게 되세요? 예 아리수로 강일동 아 강동구 아리수로. 아 몇 층 몇 호예요? 강일 큐브. 네, 네. 누가 그런 거예요, 선생님? 네, 저기 제 어머니요. 연세가 95세예요. 아, 할머니고 혈압이 떨어지고 지금 의식은요? 의식 같은 건 있어요? 의식은 지금 있으신데요. 혈압이 많이 떨어지고 몇 박도 지금 40 정도 뿐이야. 안 나가거든요. 아, 네. 알겠습니다. 지금 차는 출발했고요. 열이나 시키는 이런 증상이 있었나요? 코로나 관련해서? 네, 열 없었어요. 지금도 열은 없고요. 아, 네, 네. 알겠습니다. 코로나 뭐 이런 건 아니죠? 걱정 이런 거? 네, 그런 거 아니세요. 네, 조금만 기다려주세요. 가고 있습니다. 네, 고맙습니다.
 네 1 2 9 입니다. 네 네 응급 환자가 좀 미쳐서 그런데. 누가 어디 아프신 거예요? 아 이게 어디 저 일을 저 치과에서 며칠 전에 일을 내린 것 같은데 그게 막 이 부와 부와갖고 이쪽에 뚱뚱 부와갖고 아파서 견디지 못하나. 누가 그런 거예요? 저희 아들이요. 구급차 요청하시는 거예요? 네? 구급차 요청하시는 거예요? 네네네. 코로나 관련된 거 있으세요? 아니요. 주소 알려주세요. 한국고 건동 한양아파트 예 알겠습니다. 네.
 네 여보세요? 네 말씀하세요. 지금 저희 어머님이 힘이 없으셔 갖고 계속 토하시고 약간. 기륙이 없으세요? 예예예. 예 고통하고 지금 좀 어지럽고 그래요? 예 지금 자리에 힘도 없으시고 겨우 앉아계시는데 계속 지금 토하고 계세요. 예 의식은 괜찮으세요? 네 조금 네 있으세요. 대화할 수 있어요. 아 그래요? 네 주소가 어떻게 되세요? 아 잠시만요. 제가. 잠시만요. 예 천천히 하세요. 네. 다시 다시. 다시. 다시. 다시. 다시. 네 여기 성우 관악구 봉천동. 아니 여기. 칭이에요? 희난 상납이요. 어머니 열이나 코로나 관련 사항 있으세요? 열은 없는 것 같고 얼굴이 굉장히 창독해지셨어요. 그래요? 거동 힘드세요? 네. 지금 약간 누워계세요. 네. 알겠습니다. 전화 잘 받으세요. 네. 네.
 고맙습니다. 여보세요? 네 여보세요? 네. 예. 예 저 어제도 전화한 사람인데요. 네. 그 코피가 거의 지혈이 안 돼서요. 아 그래요? 구급차 보낼까요? 네 좀 응급실 좀. 본인이 본인이 그러세요? 네 네. 네 주소 어떻게 돼요? 예 난공로 25 각일. 난공로 잠깐만요. 네. 25 각일에. . 예예. 지금 뭐 코로나 관련 사항 해당 있나요? 열 기침 자가격리. 열 기침 자가격리 뭐 그런 거 있어요? 아니요 없습니다. 네. 구급차 보냈게요. 글로. 네.
 119입니다. 여보세요. 네. 네, 나 머리가 너무 아파가지고요. 머리가 아프셔가지고요? 어, 어. 잠깐만요. 선생님 저기 주소 알려주세요. 예, 논현 파출소 어디가 있어요? 예? 논현 파출소 비가 너무 많이 나요. 주소가 어디라고요? 논현 파출소 같은데요? 논현 파출소요? 예, 예. 어 잠깐만요. 신고를 하셨나요? 아까? 아까 했는데 피가 너무 많이 나와있고 아까쯤에 들었는데 피가 너무 많이 납니다. 머리에 머리에 많이 나요? 네 머리에 너무 많이 나요. 근데 저기 아까 아니 아까 안 가셨잖아요. 병원에. 경찰 분 한 번만 바꿔주시면 안 될까요? 아니 아니 아니 갔는데 전 사람들이 안 보낸다고 그래가지고요. 아니 우리도 허락을 받고 가야 될 것 같으니까 전화 한번 바꿔주시면 안 될까요? 시간 너무 많아. 머리에요? 아니 이게 녹취가 되고 있어요. 일단 선생님 저기 예예 녹취 되고 있어요. 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 안 했죠. 아니요. 경찰 분 한번 바꿔주세요. 저 한번만. 한번 물어볼게요. 한 오시면 안됩니까? 아니 와가지고 좀 안 가시면 그니까 좀 안 가면 어떻게 돼요? 그니까. 한번 바꿔주세요. 경찰 분. 한번 물어볼게요. 예. 그럼 그러겠습니다. 경찰 분들은 못 가갖고 아니 아니 그러니까 저희 아니 갔는데 경찰 분들이 못 가게 하면 또 그 구급대를 또 괜히 갔다 그냥 오는 거잖아요. 그냥. 머리가 피가 피가 나네. 근데 머리가 피가 나면은 피가 많이 났다고요? 거짓말 아니신 거죠? 예 거짓말 아닙니다. 알겠습니다. 일단 출동해 볼까요? 노연이 할 수 있더라고요. 예.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네. 여기 봅니다. 아 네. 안녕하세요. 여기 저 용산 센트럴 파크 아 몇 몇 호라고요? 다시 좀 말씀해 보시겠 네. 무슨 일이세요? 네. 우리 집사람이 갑자기 급체를 해가지고 쓰러져서 순서양병원이든 어디 응급실에 한 점 갔으면 좋겠습니다. 아. 급체로 쓰러지셨다고요? 네. 지금 의식은 있으세요? 의식은 있습니다. 네. 의식은 있으시고 알겠습니다. 코로나 증상 같은 건 없으셨죠? 평소에. 예예예 그 관계에 없어서 좀. 예예 선생님 용산 센트럴 파크 혹시 메미안 용산도 센트럴 파크 말씀하시는 건가요? 어 그냥 센트럴 파크. 신용산이 앞에 있는 건가요? 네 용산이 건너편입니다. 저 시디파크 바로 옆에 새로 새로진 아파트입니다. 작년 세월달에. 어. 용산 센트럴 파크 해링턴 스퀘어 아파트. 맞습니다. 예예예예예. 전화가면 전화 받으세요 고맙습니다.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네, 고객님. 무슨 일이세요? 여기 중간동인데요. 음평도 중간동이요. 예, 여기 국민은행 입구에 할아버지 1번 쓰러져 계시는데 어떤 아줌마가 보고 계시긴 하는데 빨리 오셔야 될 것 같은데요. 국민은행 앞이시고요. 순시라도 신청 알아보는 거 좀 봐주세요. 정상적인. 아니요. 저는 지금 지나가다 버스에서 가서 신고하는데 몸을 딱 몸이 막 못 움직이시는 것 같은지 약간. 버스 타고 간호사 신고하셨어요? 네. 일단은 차를 그쪽으로 보내드릴 거고요. 선택방을 전혀 모르시는 거네요. 그러면. 근데 제가 잠깐 멈춰서 봤을 때는 할아버지로 팔이 뒤로 뻗겨 있고 바닥에 쓰러져 계신데 이게 수치해서 쓰러진 느낌은 아니었을 때는. 근데 나이가 꽤 할아버지가 있으신데. 그쪽으로 보낼 거예요. 전화 좀 잘 받아주세요.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 옥상에서? 네 여보세요. 여기 창신동 창신동 네. 그냥 할머니가 옥상에서 넘어지셨는데 지금 움직이질 못하셔가지고 구급차를 불러야 될 것 같아서 전화드렸어요. 할머니 의식이랑 호흡 있으세요? 네 의식은 있으신데 아예 움직이질 못하셔요. 알겠습니다. 차 나갈 거고요. 최근에 코로나 관련해서 뭐 의심 증상이나 보건소로부터 접촉했다고 문자 받으신 거 있으세요? 아니요. 없었어요. 네. 대원달 나감사 전화드릴 테니까 전화 잘 받고 안내해 주세요. 네.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 아우. 여보세요? 여보세요? 무슨 일 때문에 그러셨는데 내용이 하나도 안 적혀 있어서 그러는데 아프신 분이 있나요? 집에 지금 팔 그었다고 하고 있어요 아 문이 잠겨있나요 혹시? 그건 아니고? 문이 잠겨있는데 어디 바꿔야 돼 모르겠어요 지금 같이 계신 게 아니에요? 네 그 문 밖에 문이 잠겨있고 이런 건 확인이 안 되는 거예요? 예. 누가 저 누가 팔을 그었다는 거예요? 여자분이에요? 와이프요. 와이프? 알았어. 이제 나가볼게요. 저희도 구급차. 예.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 여름이고요. 아 예 안녕하세요. 중학교 3학년인데 화이자 2차 접종하고 지금 심장 쪽에 조금 부작용이 있는 것 같아서 응급 치료 좀 가고 싶거든요. 아 국고시 합치료 하신 거 맞으세요? 예 지금 심장이 빨리 뛰고 그 달리기 하고 난 뒤 느낌이라고 하고 가끔 호흡이 조금 힘들다고 하거든요. 예 알겠습니다. 남자분이세요? 여자분이세요? 여자이고요. 여자고 주소 불러주시면 출소 나갑니다. 어 개포로 오 주거 개포 주거 네. 얼마나 걸리나요? 구급차가 지금 삼성동에 3km 거리에서 출동하고요. 네. 예. 그 가족 중인 분들 코로나 재택치료하시는 분은 없는 거죠? 네. 없어요. 예. 환자가 뭐 고열이나 기침 증세는 없고요. 네. 없어요. 예, 출동하면서 전화 옵니다. 잘 받아주세요.
 네, 일곱니다. 아 네, 여기 여기 여기 영등포 로터리 지하 상가인데요. 예. 예, 지금 젊은 남자분이 뚫어져 있는데 얼굴이 흰 오래 가지고 누워 있어요. 로터리 상가 계신 거예요? 지금? 예, 예, 예. 여기 앞에 지금. 잠시만요, 선생님. 네네네. 지금 일어나서 앉아있긴 한데 얼굴이 막 노랗고 희노랗고 그러네요. 의식은 있어요? 네? 의식은 있어요? 네 의식 있어요. 지금 일어나긴 했어요. 앉아있어요. 근데 지금. 뭐 구급차가 필요하신 상황이신 거예요? 네? 구급차가 필요하신 상황이신 거예요? 네. 뭐 지나가라고 그냥 그런 어 어 어. 도로 다시 들어 놓는데. 아 그래요? 예예예 어디쯤에 있어요? 여기 저기 타임스퀘어 바로 입구에요. 타임스퀘어 입구쪽에? 예예예 경비들 위치에 앉아있는데 남자분인가요? 예 남자분이요 젊은 사람이에요. 근데 지금 쓰러진다고요? 자꾸 앉아있다가? 아 누워있어요 예예예 지금 누워있구요? 네네 아 의식은 있다는거죠? 네네네 의식은 있어요. 네. 근데 뭐 지나가다 가게 하신 건가요? 예. 그럼 지나가시는 분이에요. 지나가시는 분인데. 선생님은 뭐 가게 상인이시고? 예. 저는 가게 있고요. 네. 알겠습니다. 선생님. 네네네. 오세요. 네.
 예 119입니다. 여보세요? 예 119입니다. 예 저 관악구 권영 아파트인데 권영 2차요. 권영 아파트요? 선생님 제가 어디 저기 환자 환자 몸이 아프다 병원에 가야 하는데. 예 선생님 저 권영 아파트예요. 혹시 번지수는 모르세요? 아 저기 저 신림이 신림 저기 신림동 권영 2차 2차 전주가 남는 거 다 부면 돼. 예 권영요. 권영 2차 아파트요. 아 아픈 데는 남자예요? 여자예요? 여자예요. 여자. 예 여성분이고요. 여성분이고 어디가 아프세요? 속이 답답하고 그래서 어지럽고 어디 잠시 거 인제 어제볼린다고 부르는 거 같으니. 예 어지럽네요. 그래서 코로나 관련해갖고요. 의심사항 같은 거 있어요? 기침하고 연락을 이런 거 있으셨어요? 없지 않고 삼산까지 다 맞았어요. 예. 권양 권양 2차 2차요. 2차 다. 선생님 거기에 그 남궁 초등학교 근처는 맞아요? 예 초등학교 남궁 초등학교 밖에서 밑에다구요. 밑에다구요? 예 알겠습니다. 빨리 잡게요. 다음에 전화하면 전화 잘 받으세요. 예.
 네 여보세요. 네 선생님 일요일 상황실이에요. 오르페오 타운 주차장으로 가면 되나요? 어 제가 주소는 잘 모르겠고요. 여기 남문시장 안에 있는 오르 오르페 오르페 온 타워. 오르페 온 타워요. 예 혹시 남자분 의식이랑 호흡이 있을까요? 어 제가 잘 모르겠는데 홈트 거리시긴 하셨고 마스크는 안 쓰시고 계셨어요. 제가 멀리서 베가지고요. 아 멀리서요? 그래서 제가 다가갈 수가 없었거든요. 아 네 알겠습니다. 저희 대원들 나가서 확인해 볼게요. 네.
 네, 119입니다. 이것도 오고 있어요. 말씀하세요. 예, 수고하십니다. 여기 사고 건 때문에요. 사고요? 문 사고요? 예, 저 여기 경찰관 분들 나와 계시고. 예. 운전자 1분 조급차. 아 네, 네. 여기 위치가 강변북로상이고 가양대교에서 성산대교 방향으로 있거든요. 잠깐만 잠깐만요. 강변북로상이고 가양 가양 어디라고요? 가양대교에서 성산대교 방향이요. 에서 성산대교 예. 대교 방향 지금 차 대 차랑 부딪친 거예요? 예 맞습니다. 차들 차고 환자는 1명? 예 1분이요. 1명이요. 선생님은 그 보험 쪽 관계자 되세요? 예 맞습니다. 알겠습니다. 출동 나가보겠습니다. 예 좀 혹시 차량 이동할 수 있어서 네 오늘 출동하시는 분한테 이 번호로 연락 1번 더 부탁드린다라고 전달만 좀 부탁드릴게요. 알겠습니다. 네.
 여보세요? 네. 여기 목련 아파트 할머니가 넘어져갖고 다리가 할머니가 넘어지셨어요? 네. 예. 그래서 다리가 못 써 못 써요. 수지도 못. 못 걸어요? 예. 못 써. 수지도 못하고 막 많이 부었거든요. 아. 잠시만요. 네. 구급차 지금 보내고요. 할머니 뭐 열 있거나 비친 콧물 있으세요? 아니요. 그렇지 않아요. 그런 거 없고 코로나 관련돼서 격리하시거나 확진자 있거나. 없어요. 지하관 복지관 다녔는데 오늘은 안 가는 거 아니거든요. 선생님 가족이세요? 네 딸이예요. 딸? 아 네 차 보내고요. 또 기다리고 계세요. 네 감사합니다. 네.
 119입니다. 여보세요? 네 말씀하세요. 연무장길 연무장길 네 제가 그 갑자기 심장이 좀 빨리 뛰어서 본인이요? 네. 네. 좀 가서 조치를 좀 쳐야 될 것 같은데 숨 쉬는 건 어때요? 네 숨은 정상이에요. 숨 쉬는 건 정상이고 그냥 심장이 빨리 뛰는 것 같아요? 네. 뭐 백신을 맞으신 거예요? 아니면 갑자기 그런 거예요? 백신 맞고 한 일주일 지났어요. 백신 맞고 일주일 지났고. 네. 네 알겠어요. 거기 집안 앞으로 가면 돼요? 아니면 건물 안에 계신 거예요? 아 오시면 잘 나갈게요. 그럼 그 앞에서 갈게요 그럼요. 네. 네.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네. 안녕하십니다. 예 지금 저희 남편이 제가 너무 복통이 심하고 열은 없거든요. 구급차 투자 하신 거예요? 예. 주소 어떻게 되세요? 서울시 마포구 동망로. 동망로. 42길. 동망로 42길에. 예. 42길에. 예. 마포 사이예요? 몇 호 몇 호예요? 네. 네.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네 여보세요. 여기 네 여기 지금 코로나 이상 반응이 있어서 구통하시고 아예 지금 거동도 못하시거든요. 코로나 이상 반응이라는 게 코로나 걸리신 거예요? 아니 아니 아니요. 주사 맞고요. 백신 맞았다는 거예요? 네네네네. 아 몇 층 몇 호요? 어머님이요? 아버님이요? 저희 할아버지요. 할아버지? 지금 의식은 있어요? 의식은 있으신데 거동도 못하시고 코피해 주시고. 열 없으시고요? 열 열 없으신 거 같아요. 네 알겠습니다. 수강하자 나가고 있어요. 네.
 예, 1급 다. 네, 저기 환자가 있어서 그러는데 좀 모아 주실 수 있어요? 주소 불러주세요. 예, 여기 동대문 청소 우선 아파트. 아, 동대문 잠깐만요. 번지서 이런 거는 모르세요? 아, 알아요. 동대문구. 예, 전동. 전동동? 예, 10길. 아, 무슨 무슨 길이에요? 10길. 아니 아니 아니 무슨 전능로 전능로 10길이에요? 잠깐만요. 잠깐만요. 전능로 10길에 예 청소를 우산 아파트 잠깐만요. 네 답신리 청소를 우산 아파트요. 예. 아프다니? 할아버지세요? 네. 할아버지 어디가 아프세요? 아 저기 소변을 못 봐가지고 소변이 안 나와가지고. 소변불능력 소변불능력이고 기침하고 기침하고 연락을 이런 건 없어요? 아니 그런 건 아니고 암 환자예요. 예 암 암 병력에 소변불능력. 예 저기 단강암인데 소변이 안 나와가지고 그래. 그리고 기침하고 열나고 코로나 그런 건 없다 그죠? 아 그런 건 없어요. 네 빨리 갈게요 접수 됐습니다.
 네, 1호입니다. 네, 안녕하세요. 저기 77쌤 할머니인데요. 예, 예. 예, 예. 어제도 그 뒷통수가 탕탕 때려서 어제 목도 운동원 응급실에 갔었거든요. 예, 예. 근데 지금 아까 혈압액 180까지 초상류가 올라가면서 저기 따고 좀 안정돼가지고 집에 들어왔는데 그 혈압액 추가로 반환을 먹으라고 해서 먹었는데 지금 사람이 계속 떨어지는데 속내증이 나신대요. 네 고급차 타고 병원 가시려고 전화 주신 거죠? 네네. 주소 알려주세요. 네 저기 응암 1동. 잠시만 응암 1동. 유성 오피오스요? 음 예. 네, 네. 네, 제가 고급차 보냈습니다. 예, 감사합니다. 예, 예.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 119입니다. 말씀하세요. 네. 네 수고하십니다. 네 선생님 여기 강호소방이고요. 예예 저희가 통화해볼게요. 네 알겠습니다. 네 여보세요. 네 여보세요. 선생님 주소가 금호동 3가? 3가? 예예. 아 금호 어머니가 몸이 너무 안좋으셔가지고 지금 부탁 좀 드릴게요. 저도 여기 촬영에 있다 보니까 여기서 연락받고 출발을 하는데 아 네 선생님 집이 한 개에요? 집이 하나에요? 문 열어놓고 어머니가 계실거에요. 알겠습니다. 지금 바로 출발할거구요. 어머니 전화번호 같은거 하나 있나요? 어머니 어머니 제가 핸드폰이 먹둥이 돼서 제 전화번호를 하나 알려드릴게요. 전화가 아니라 제가 들린건데 선생님 전화번호 알려주세요 네 알겠습니다 그럼 이 번호로 전화드릴거구요 지금 지금 출판했고 어머니가 어디가 아프신지 아세요? 저 밤새 통화하시고 코로나는 아니에요 저 3타까지 다 맞으시고 코로나는 아니신데 지금 어저께 방주 통화하시고 지금 쓰러 저 몸이 너무 안 좋으셔 갖고 지금 나한테 전화가 왔는 거예요. 예, 예, 알겠습니다. 그 현관문은 열려 있다는 거죠? 문은? 예, 예, 반 저 반주로 내려가는 문이 철문이 열려 있을 거예요. 예, 예, 예, 알겠습니다. 네, 네, 네.
 119입니다. 예, 예, 방금 전에 그 통화를 했었는데요. 네, 네. 아버님은 지금 너무 이제 기력이 없으셔가지고 너무 살이 빠지시고 지금 지금 상태 너무 안 좋아가지고 지금 응급실에 모시고 와야 될 것 같아서요. 전화드렸습니다. 네, 그 병원 가신다고 하세요? 예, 예, 가신다고 하십니다. 아 의심은 있고 기력이 저하된 거예요? 예, 예, 예, 너무 좋아 1주일 사이에 너무 급격하게 전화가 돼가지고요. 아 네, 저기 주소 알려주세요. 장동 예예 맞습니다. 몇 호예요? 열 있거나 귀신 콧물 없어요? 아버님? 예 그런 건 없습니다. 집에 코로나 때문에 정리하시는 분이나 확진되거나 그런 건 없습니다. 차는 보냈고요. 조금 기다리세요. 예 감사합니다.
 어휴. 열려갑니다. 예 여기 그 아차산에서. 통사 쪽으로 이렇게 내려가는 중간쯤에서 제 아들이 넘어졌거든요. 근데 얼굴 쪽에 코 주변으로 해가지고 좀 타박상이 심하게 난 거 와서 피가 나는데. 걸어서 내려가기 하고 있거든요. 예 지금 그 고급자 요청하시는 거죠? 네, 네. 네. 마차산에서 여기 영하사로 내려오는 길이요? 아니 아니 기원정사. 기원정사요? 예, 예, 예. 기원정사 쪽으로 가는 길인데. 기원정사 가게 지금 몇 미터 전이에요? 그 뭐 나오나요? 그니까 내려 내려오는 길인데. 예. 이정표에 뭐 나오는 거 있나요? 지금 유형표에 나오는 거는. 그 나무 계단 있는 쪽인 거 같거든요? 나무 계단이요? 예. 기원 정서 앞으로 와주시면 될 거 같은데. 기원 정서 앞으로요? 예 알겠습니다. 통화할게요. 저희 계연대 전화하면 전화 좀 받아주세요. 감사합니다.
 119입니다. 네 안녕하세요. 주소 뭐죠? 얘기 좀 해주세요. 네 안녕하세요. 저희 여성분이 팔이 조금 골절이 난 것 같아요. 팔이 이렇게 비틀어져가지고 상태가 안 좋은데 좀 와주셔야 될 것 같거든요. 저희 주소 네 잠시만요. 서초 하이츠 빌라. 예? 빌라 이름 말고 주소요. 주소. 주소 아니 이거 눌러봐. 어디야 뭐지? 아 서초구 서초대로? 예. 62길 62길. 62길. 몇 동 몇 호 잠시만요 여기 지금 신고자분은 환자분이랑 같이 있는거죠? 네 같이 있으니까 도착하실 무렵에 전화 주시면 저희가 다시 위치 안내할게요 아니 서초아이츠 빌라 O O O O 가면 되잖아요. 네 맞아요. 그 차는 나가고요. 전화 오면 잘 받아주시고 뭐 환자분 코로나 확진자거나 아니 그렇진 않아요. 네 네. 기다려주세요. 네 얼마나 출장하신데 얼마나 걸릴까요? 저희가 잠원동에서 출발했으니까요. 금방 갈 거예요. 기다려주세요. 네 알겠습니다. 빨리 와주세요.
 예. 예. 주소 좀 다시 정확히 좀 알려주세요. 예. 제기동. 예. 양명로. 그냥 양명로예요? 예. 아 이제 거기 그렇게 써 있어요? 양명로예요? 양명 중앙로예요? 양명 중앙로인지 모르겠는데 내가. 건물 이름 뭐예요? 건물 이름. 재기 고시원이예요. 재기 고시원? 재기 고시원 몇 호씩 몇 호? 예 선생님 좀 살려주세요. 예 선생님 저희가 일단 출종시켰고요. 다른 도중에 의료 수정 열어볼게요. 끊지 마세요.
 119입니다. 저 여기 수에서 쌍문으로 가는 우이교 있죠? 네? 잠시만요. 저희가 우이교? 네. 우이교? 네. 거기 바로에서 거기 지금 오토바이 그 운전하시는 분이 넘어지셔 가지고요. 오토바이 혼자 넘어진 거예요? 아니면 뭐랑 부르시죠? 그건 잘 모르겠어요. 그냥 소리가 들려가지고 뛰어봤거든요. 그 옆에 보면은 뭐 차가 부딪힌지 뭐 그런 거 확인이 안 되나요? 옆에 뭐 사고 난 건 아닌 것 같아요. 오토바이 혼자 넘어졌고 우이교 다리 위에요? 다리 전에요 바로 직전이요 다리 위랑 똑같아요. 그러면은 우이교 지나기 전에 거기가 CGV께서 우이교 지나가기 전에 그쪽이에요? 맞아요 맞아요 맞아요 맞아요. 그 남자분이 다쳤어요? 여자분이 다쳤어요? 그 분 흔식이 있어 보여요? 없어 보여요? 어디 다친지는 모르는 거예요? 아니요 손 다쳐보여요 손. 손? 예 알겠어요.
 연락 옵니다. 예 여기 농원구 동일로요. 예예. 예 영주 요양원입니다. 아 홈타 복지관인가요? 예예 그쪽으로 들어오시면 돼요. 어떤 일 때문에 그러세요? 아 지금 어르신이 지금 호흡이 좀 급해져서요. 할머니 할아버지예요? 할머니요. 잠시만요. 몇 층으로 가면 돼요? 요양원? 뭐 CPR 상황은 아니고요? 네? CPR 심정지 상황은 아니고 아니 그건 아니고 표정까지는 아니고요 요양원 이름이 어떻게 된다고 홍파 요양원? 영기요양원이요 영기? 예 아 전화 끊지 마시고요 저희 고급차 가고 있는데 혹시 뭐 코로나 관련 증세 있으신 분은 안 계시죠 요양원에? 예 없어요 아 확진자로 만나셨거나 자가격리 하신 분은 안 계시고요? 그런 분은 안 계세요 혹시 할머니 뭐 산소 끼고 계신 거예요? 아니요 아 그런 건 아닌데 갑자기 숨 쉬는 게 이상하세요? 아 그럼 저희 대원제 가고 있고요. 혹시라도 대원제 가면서 전화드릴 거고 혹시 숨 쉬는 게 더 힘들어지시고 하면은 바로 연락 주시고요. 빨리 갈게요. 예.
 네, 119입니다. 네, 여기 그 옆에 홍원 현대 아파트 버스 정류장이거든요. 네, 무슨 일이세요? 어 그 정류장 댄스에 어떤 할머니께서 굉장히 고통스러워 하시면서 이렇게 앉아 없으러 계신다 그래야 되나? 그래가지고 뭐 이렇게 하려고 그랬더니 뭐 괜찮다고 막 하는데 상황이 그런 거 아닌 것 같아서 전화드렸어요. 알겠습니다. 저희 고급차 출동하고 그분한테 119 신고했다 고급차 올 거다 이렇게만 1번만 전달해 주시겠어요? 예 알겠습니다. 얼마나 걸렸죠? 버스 기다리는 데까지는 옆에 있을 테니까. 예. 1.7km나 나오니깐요. 금방 도착은 할 겁니다. 제가 빨리 가보겠습니다. 아 예 알겠습니다. 감사합니다.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 예, 6입니다. 네, 안녕하세요. 저기 그 아버님 맥박이 너무 안 좋으셔가지고. 의식은 어떠세요? 어 아직 괜찮으세요. 지금 상소 호흡도는 94인데 맥박이 36 40 약간 뭐 그 정도 왔다 갔다 하셔서. 아니요. 맥박이 몇 회라고요? 40 40에서 왔다 갔다 하시네요. 40 정도? 보급차 보급차가 보급차 앞에서 전화 주신 거죠? 네, 근데 저희 여기가 계단이 있어요. 그때부터 불러주세요. 주소는요? 은평구 신사동. 네. 며칠 몇 주시죠? 아 여기가 단독주택이라. 여보세요? 아버님 계신 곳은? 아니요. 저희 대문 들어오면 1층이 한 6칸 정도 계단을 올라오셔야 돼서. 그래서 아버님이 거동은 전혀 안 되시는 상황이세요. 예 알겠습니다. 대문 들어가면서 전화드릴 수 있어요. 코로나 관련된 증상 여행일 특이사항 없으시죠? 아 저희 아버님 코로나로 퇴원하셨고. 언제 퇴원하셨어요? 확진 확진. 어 확진을 6일 날 받으셨고요. 그리고 서울 의료원에서 29일 날 퇴원을 하셨고. 완치 이후에 완치 이후에 퇴원하신 거죠? 네네 그리고 지금 세브란스에 그 차가 오늘 그 저기 뭐지 입원 수석이 되어 있어서 된다고 해서 가려고 하던 편인데. 우선은 병원 결정은요. 병원 결정 나중에 병원에서 만나서 환자분 성태라든지. 알겠습니다. 네, 네.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 예 이리 봅니다. 저기 저희 아빠가 숨을 안 쉬세요. 아 주소 불러주세요. 금상구 시흥동. 오토빌. 오토빌. 오토빌. 오토빌. 고급차 번 했고요. 아예 호흡이 없으세요? 호흡 없으시고 침착도 너무 하죠.
 아 네 안녕하세요. 여기 서대문구 연휴로 36길 안산 빌딩 1층 관리실이거든요. 저희 어머니가 지금 좀 유독하신 것 같아서 119 신청을 하려고 전화드렸거든요. 어머니 옆에 있어요? 네 잠깐만요. 36길 맞아요? 1층에 있고요. 어머니랑. 어디가 제일 아프세요? 어머니가? 지금 나이가 많으시 연로 하셔요. 90이 넘으셨는데 얼마 전부터 식사를 잘 못하시고 근데 막 심호흡도 안 드시고 호흡 곤란도 있으세요? 그리고 아예 눈을 못 드세요. 어 그럼 누워 계셔야 되는 거 아니에요? 지금 혹시? 네네네. 열이나 기침 코로나 관련 사항은 없는 거죠? 그런 건 없어요. 예예. 지금 그럼 1층에 관리실에 내려와 계세요? 네. 아뇨. 지금 이동이 엄마를 모시고 나가 엄마가 힘을 많이 해. 몇 층에 계세요? 어머니는 지금. 알겠습니다. 그쪽으로 구급차 보낼게요. 선생님. 네, 감사합니다. 전화 잘 받으세요. 이거.
 네. 2구입니다. 아 예. 강동구 명일동 강동구 명일동 예. 네. 몇 층이에요? 우리 아들이 쓰러져가지고 경찰들이 대놓고 갔는데 몸을 지금 못 가논는데 병원에 가봐야 되겠는데 응급실 뭐 술을 먹었어요? 모르겠어 술을 먹었는데 어쨌든 하여튼 오줌도 막 싸고 그러는데 병원에 응급실 의식은 있어요? 의식? 대화 가능하세요? 대화도 안 하고 그냥 어둠 누고 그냥 어둠 누는 거 수가 있는 것도 힘들어 하는데 호흡은요? 호흡은 괜찮은데 하여튼 응급실에 가봐야 되겠는데 어디가 왜 불편한 거냐고요? 예? 왜 불편한 거냐고요? 술을 먹었어요? 아니면 원래 몸이 불편하신 분 모르겠어요. 아침에 저기 저 아침에 나갔는데 네. 저 어 뭐꼬 천호동 어디 서러져 있다 병찰들이 데리다 주고 갔는데 병원에 응급실 가봐야 되겠네. 네. 저 통해서 확인해 볼게요. 네. 지금 오시겠어요? 의료진 연결할게요. 전화 끊지 말아주세요. 의료진 연결할게요. 혹시 여기 간다니까요. 혹시 열이 나거나 기침 코로나 관련 증상이 있어요? 아니 코로나 증상은 없고 3차까지 예방 의료진 연결할게요 의료진
 네, 여보세요? 아 선생님 서울 한방병원인데요. 환자분이 지금 갑자기 그 호흡이 없으시고 해서 해서 그. 병원이요? 대전대학교 서울 한방병원이요. 지금 성파 아니에요? 네, 맞아요. 아 지금 잠깐만요. 예, 한방병원 어떻게 되세요? 주소예요? 대전대학교 서울 한방병원이요. 그 문장 법원 로 기 법원 기요. 예 법원 로 몇 이에요? 잠시만요. 법원 로 11일. 남자 여자예요? 남자분이요. 네. 신청할 거고요. 전화 끊지 마세요. 잠시만요. 네.
 아 지금. 네 여기 지금 구 1동인가? 구 1동. 구 1동 있었다. 네 몇 팀이에요? 무슨 얘기세요? 엄마가 화장실에 들어가가지고 엎어져서 여기 턱 있는 데가 찢어졌어요. 완전 지금 이빨 있는 데랑 다 피어나고 선생님은 구급차 나갔고요. 어머니 지금 의식은 있어요? 네 의식은 그래도 좀 있어요. 선생님 깨끗한 수건 같은 거 있으면 지열 좀 하시고요. 네. 평화 아티비 맞아요? 네. 알겠습니다. 대원들 받으셔서 전화도 잘 받으세요. 네.
 수고하십니다. 아 지금 애가 팔을 못 움직여서 그러는데요. 네네. 아 이 병원을 좀 가야 될 것 같아서. 네네. 구급차 필요하신 거예요? 네네. 주소 어떻게 돼요? 서울 용산구 보강로 오길. 보강로 오길. 리버빌인가요? 네네. 집에 온 코로나 관련 사항 혹시 열기심? 없어요. 장가격리 사항 뭐 그런 것도 해당 없죠? 네 네 네. 팔이 제일 아픈 거고요 아이가요? 네 팔이 아파서 움직이지 못하고 있어요. 지금 안 움직이면 계속 울고 있어가지고. 알겠습니다. 구급차 리버벨 아파트로 구급차한테 보내겠습니다. 전화 잘 받을게요. 네. 네.
 네 경기 도쿱입니다. 강북구 우이동에 보급차 요청 아버지 싫어지셨대요. 말씀하세요. 강북구 우이동. 예 몇 분지요? 몇 분 몇 분에요? 스카이빌. 아버지 지금 의식 상태는 어떠신 것 같아요? 지금 의식이 좀 완전히 없으시진 않고요. 암 환자시거든요. 암 말기 환자. 아 예 어머니한테 전화 오신 거예요? 예예. 요양보호사 선생님도 계시고요. 예 저희 현장 전화번호 좀 불러주세요. 전화하면서 가볼게요. 아 잠시만요. 예 알겠어요. 저희 통화 한번 가볼게요. 네. 예.
 아 예예. 여보세요? 예. 여보세요? 예예예. 아 예예. 아 예예. 내가 아 움직이는 걸로 좀 전화를 또 같이 같이 같이 가겠네요. 아 아버님 어디가 좀 좋으세요? 지금 아프신 때가? 여 다리. 예예. 다리 발목이 이제 거기 좀 부어 올라와가지고. 예. 저. 콧들 못하네요. 콧들 못하네. 콧들 못하고. 아 부종 부어가지고. 이사들 못하고 그래요. 발목이 아파가지고. 예. 알겠어요. 이제 고참쪽 병원 가보실려고 그러는 거죠? 예예예. 주소가 어떻게 되세요? 여기 저. 강남구. 예. 어 삼성동. 예. 예. 며칠 몇 회예요? 아 하이치빌라. 예. 예. 예. 그런데 열 같은 건 혹시 어떻게 되세요? 지금? 열 같은 게 괜찮아요. 열은 없고? 알겠습니다. 하이치빌라. 네. 예예예 여보세요? 예? 예 얼마나 걸려요? 구급차가 한 5분 정도 걸릴 것 같네요 아 그래요? 예예 5분 덜게 안 걸린다
 예, 열립니다. 네, 네, 수고하십시오. 여기 마천역인데요. 마천역이요? 예, 예, 예. 여 사람이 쓰러져 있어요. 아 선생님 마천역 어디에 있어요? 쓰러지신 분이? 지하 1층 대학실 개찰구 있는 쪽이거든요. 아 마천역 대학실 개찰구 쪽이요? 남성분이세요? 여자분이요. 여성분. 의식 상태는 어떠신 거 같아요? 뭐 거의 의식이 없어요. 그냥 손만 흔들고 막 이러는데 술도 흔들고. 아, 술 드신 거 같아요? 호흡은 하시는 거죠? 그러니까. 네, 네, 네, 네. 아 예 선생님 저희 구구차 그쪽으로 갈 건데 그 553 마천역 말씀하시는 거 맞죠? 553 마천역 수학 2층 대학 중입니다. 알겠습니다. 선생님 전화번호가 안 떠서 그런데 전화번호 한번 불러주세요. 예. 알겠습니다. 네 저희 고객님 전화가 한번 전화만 좀 잘 받아주세요. 네. 네.
 여보세요? 선생님 그 환자분이 의식이 있어요? 아 저는 모르겠어요. 차 타고 지금 지나오다가 제가 신고를 하거든요. 그냥 누워있는 걸 보고 신고 하신 거세요? 네네. 아 예예. 그 와산교 밑에 있다는 거예요? 와산교? 예예. 그 자전거 도로상 말씀하시는 거예요? 아니요. 인도. 버스길 옆에 인도. 자전거 와상교 아래라고 말씀하시잖아요. 예예. 와상교 밑에 뒤에 아래가 아니라. 아. 택길로 예예. 예 알겠어요. 네.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네. 1 2 9 입니다. 네. 여기 저기 뭐야. 환자가 아파서 지금 1 2 9 에 전화했거든요. 남자분이요? 네. 아니 여자요. 여자분. 선생님 본인이세요? 예? 선생님 본인이세요? 아니요. 제 동생이요. 아 동생이. 네. 동생 보내드릴 테니까 주소 알려주세요. 아 저기 제보 여기 주소가 어떻게 돼요? 저기 편지보소 갖고 와 봐. 그 주소 있는 거 갖고 와봐. 동생분은 어디가 아프신가요? 배가 아프신 거예요? 어지러우신 거. 배가? 연락을 할 코로나 증상은 없어요? 예 예 주소 불러드릴게요. 망으로 68길. 망으로요? 네. 망으로 68길에. 네. 몇 층 맞으세요? 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개 1개
 네, 알겠습니다. 예, 그 아이 뭐지 여기 그 술 먹고 했는데 애가 집을 못 가고 계속 그래가지고 혹시 돈 도와주는데 애가 떨어져 있어가지고. 아 뭐 애가. 네, 사람은 이렇게 애가 아니고 사람은 이렇게 하는데 막 계속 떨어져 있어가지고요. 아 뭐 여성분이세요? 여성분? 네네, 네네네네네. 아 뭐 지금 가까운 병원으로 한번 가보실라 그러는 거예요? 아니요, 병원이 말고 애가 지금 문 열어나서 혹시 오실 수 있을까 해서요. 어 예 주소가 어떻게 되요 선생님? 야 야 여기 주소 주소 주소 주소 여기 그 수유에 주다방 건물 혹시 어딘지 아세요? 수유역이요? 네 수유에 있는 주다방 건물이요. 주담? 주다방이요 주다방 술집 이름이 주다방이요 여기 건물이에요. 아 주다방이요? 수유동에 주다방 잠시만요. 네 네. 한번 해볼게요. 네 네 검색해보세요. 오늘 술집 주다방 말씀하시는 거예요? 네네네네 맞아요. 네 맞아요 맞아요. 잠시만요. 그 선생님 지금 다른 분이 신고를 하신 것 같은데 경찰에 신고하시지 않았어요? 네 신고는 경찰에 신고할 정도는 아니었어요. 네 제가 다른 사람인데 제가 신고해서 했어요. 전화해서 호텔 글로리 1층 여자 화장실에 있는 거 맞죠? 아니 화장실이 아니고 여기 그냥 상가에 있어요. 상가로 오시면 돼요. 상가에? 제가 제가 데리고 나갈게요. 지금 선생님 거기 구급차 안 보여요? 구급차 같은 거? 앞에 앞에 사람이 너무 많아서 안 보여요 지금. 안 보여요? 지금 앞에 고급도가 지금 있는 거 같은데 지금. 그건 뭐지? 근데 그 어떤 어떤 그 구급대원분들이 나와서 다른 분들과 왔어. 다른 분. 다른 분이에요 또? 네 네 네 그쪽은 다른 사람이에요. 저희가 아니에요. 지금 다른 거 오시면 될 거 같아요. 제가 데리고 나갈게요. 네 알겠어요. 네.
 예, 여보세요? 네, 수고하십니다. 저 애기가 지금 정면이 일어나가지고요. 아 애기 정면하고 있어요? 예, 예, 예. 주소는 어떻게 되세요? 예. 네, 여기 지금 여기 어디지? 여기 마들로 31길이요. 마들로 31길 뒤에 본지는 어떻게 돼요? 잠시만요. 여보세요? 예, 예, 그 아파트 이 아파트인가요? 선생님? 예, 예, 저 그랑비 아파트. 아파트 1번 있어요? 예, 그랑비 아파트. 예 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아기 아 네 예 고맙습니다 어? 어 알았어 알았어
 네, 1 2급입니다. 말씀하세요. 네, 여기요. 청암 자이 아파트 버스 정보장 앞쪽에 건널목에 어떤 할아버지가 쓰러져 계시거든요. 아 잠시만요. 저는 길 가는 사람인데요. 할아버지요? 네, 어떤 할아버지가 건널목에서 지금 엎드려서 못 일어나시고 계세요. 여기가 청암보도 6교 있는 데예요. 청완보도 6교 잠시만요. 어 천연 창가 명가 자유 아파트 앞인가요? 네네네 여기 이거 여기 강변노랑 합쳐지는 도로 건널목 앞이요. 아 할아버님 의식이랑 어머 어머 할아버지가 넘어지셔서 팀도 나요. 빨리 좀 와주세요. 차 근처로 차는 내보냈고요. 할아버지 의식이랑 호흡은 있다는 거죠? 네네네 이런 건 아시는데 팀도 나시네요. 알겠습니다. 대원서 나가면 전화드릴 수 있으니까 전화번호 안내 좀 부탁드릴게요. 네네.
 예예예. 죄송한데요. 네. 사람이 죽을라 그래. 네 주소 알려주세요. 주소. 예. 주소. 지금 저. 예. 방압 2동. 네. 에. 아. 어디 놀이터 있죠? 어디 공원. 천다 26 천 마을버스 천다 26번 종점 밑차 못 봐서. 종점 밑차 못 봐서. 선생님 그럼 그 버스정류장 아이디라든지 뭐 그런 걸 말씀해 주세요. 그렇게 말씀하시면 못 찾아봐요. 아유. 아 천우빌라. 천우빌라요? 예. 여. 아 방안 이동. 천호빌라 천호빌라 천호빌라 천호빌라 천호빌라 천호빌라 천호빌라 천호빌라 천호빌라 천호빌라 천호빌라 천호빌라 천호빌라 천호빌라 천호빌라 천호빌라 천호빌라 천호빌라 천호빌라 천호빌라 천호빌라 천호빌라 천호빌라 천호빌라 천호빌라 천호빌라 천호빌라 천호빌라 천호빌라 천호빌라 천호빌라 천호빌라 천호빌라 천호빌라 천호빌라 천호빌라 천호빌라 천호빌라 천호빌라 천호빌라 천호빌라 천호빌라 천호빌라 천호빌라 천호빌라 천호빌라 천호빌라 천호빌라 천호빌라 천호빌라 천호빌라 천호빌라 천호빌라 천호빌라 천호빌라 천호빌라 천호빌라 천호빌라 천호빌라 천호빌라 천호빌라 천호빌라 천호빌라 천호빌라 천호빌라 천호빌라 천호빌라 천호빌라 천호빌라 천호빌라 천호빌라 천호빌라 천호빌라 천호빌라 천호빌라 천호빌라 천호빌라 천호빌라 천호빌라 천호빌라 천호빌라 천호빌라 천호빌라 천호빌라 천호빌라 천호빌라 천호빌라 천호빌라 천호빌� 아니 그 앞에 어디 공원 있어요 선일에 1126번 버스 서는데요 네 그 가고 있고요 응급처치 안내할 테니까 끊지 마세요 네 끊지 마세요 종점 종점 좀 꼽고 가세요 예 전화 잘 받으세요 예 예

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네, 즐겁니다. 아 예, 안녕하세요. 저 여기 잠실 세대역인데요. 그 저희 어떤 그 할머니분이 지금 갑자기 배가 아프다 배가 아프시다고. 네. 이제 연락을 좀. 어디로 가야 돼요? 승강장이에요? 아니면 대학실이에요? 대학실이고요. 네. 그 일단은 저희가 그 고개 안전실에다가 잠시. 그 고기한 주소에서 잠깐 숙여하려고 하는데. 알겠습니다. 선생님 영무원분이신 거예요? 알겠습니다. 출동해 보겠습니다. 네 감사합니다.
 여덟입니다. 아 네 그 저희 남편이 배가 너무 계속 아파서 혹시 응급자를 좀 들을 수 있을까 해서요. 아 예 거동 힘들어요? 아 네 저 못 못 들으려 그래서 많이 힘들어해서. 주도가 어떻게 되세요? 아 네 물레로 4가 6 4길 잠시만요. 물레로 4길이요? 잠시만요. 4길 몇 층이에요? 현대 아파트 네네. 네. 남편 뭐 열이나 기침 뭐 코로나가. 열은 안 나요. 그냥 배가 계속 아파서. 네. 고재구로 병원을 좀 해완하는데 가능할까요? 일단은 이제 수성아 구급 배원이 이제 이송 가능한 병원을 안내해 드릴 거예요. 네 구급 배원하고 상의해 보세요. 네 알겠습니다. 네 전화 잘 받으세요. 네.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네 감사합니다. 아 여보세요? 아 예 지금 그 우리 2사람 좀 어지러워가지고 점점 막 의식을 잃고 있거든요. 어디 계세요? 주소는 어떻게 돼요? 아 여기 저 신길동 레미안 팀. 네 저거요. 신길동에 레미안이고요. 맷독 매토저 예. 네 네 거의 움직일 수가 없는 상황이라 어지러워서 네 알겠습니다. 지금 코로나 관련 사항 해당 사항이 있을까요? 없습니다. 해당 사항 없습니다. 구급차에 나갈 텐데 지금 숨은 정상적으로 쉬어요? 숨? 조금 쉬긴 쉬는데 그렇게 아주 정상적으로... 아니 숨 넘어갈 거 같냐 그런 말이야 숨을 가쁘게 쉬어요? 아니면 그 정도 그런 건 아니에요. 일단 제일 아픈 게 어지럽다고 하시는 거죠? 예 어지럽고 예예. 네 차가 가고 있습니다. 대림동에서 가고 있어요. 네 네 네 네.
 일구성 하십니다. 말씀하세요. 네 저기 있잖아요. 목에 가시가 걸려갔고요. 목에요? 네 제가 말을 못하겠는데요. 병원을 가질 적은 큰 거예요? 뭐 그 거기 아침에 밥 먹다가 많이 힘들어요? 네. 주소가 어떻게 되세요? 서울 강도구 학원. 네. 네 알겠습니다. 네 차 보낼게요. 네. 네. 네.
 네. 저 여기 강남구 헌룡로 어 조금만 천천히 불러주시겠어요? 강남구 헌룡로 네, 여기 저희 아버지께서 다리 관절이 너무 아프셔서 못 움직이는데 네, 병원으로 저희가 데려갈 수 없는 상황이거든요. 장남 대시양파크예요? 네. 네. 출동하고요. 아버님 혹시 그 열이 나거나 기침 코로나 관련 증상이 있으세요? 어 지금 오아는 오셨다고 해요. 그러니까 열이랑 기침 코로나 관련 증상 있냐고요? 어 그러니까 방금 열은 나는데 다른 증상은 없어요. 알겠습니다. 코로나 확진자 아니시고요. 네. 출동하겠습니다. 네.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네 저기 여기 저기 목동 롯데캐슬. 네? 위너에요? 롯데캐슬 위너? 네 네. 네 네. 네. 네. 네. 누가 아파요? 아우 신랑이 지금 막 가슴이 아파가지고 그러는데. 가슴 통증 있어요? 네 네. 네. 네. 호흡곤란 증세도 있어요? 네 지금 예. 네 의식은 괜찮아요? 네 의식은 아직 있는데 너무 아파가지고 그래요. 예, 열이나 기침 뭐 코로나 관련 상 있으세요? 그런 건 없어요. 예, 혹시 거동 가능하시면 1층으로 내려올 수 있어요? 아 거동이 지금 좀 아 거동 힘들어요? 예, 거 일찍까지 글쎄요. 빨리 저기 저기나 대주세요. 그리고 연락 다시 주세요. 문자는 문자는 가고 있고요. 네, 네. 예, 전화 받으시면 1층으로 내려오시면 좀 빨리 갈 수 있으니깐요. 네, 네, 네, 네. 네, 그럼 내려올 수 있어요? 네, 내려갈게요. 예, 전화 전화 받을게요. 언제쯤. 네, 네. 예, 지금 가고 있어요. 감사합니다.
 예, 이겁니다. 아 예, 저기 그 사람 쓰러져 갖고요. 가족분이요? 아니면 지나가시면서 오셨어요? 아니면. 아 가족분이에요. 집이에요. 여기. 누가 누가 쓰러진 거예요? 예, 장인어른인데 여기 그. 장인어른 의식은 있어요? 없어요? 예, 지금 지금 겨우 있으신 거 같은데 저기 그 원격 수 있다 불러주시고요. 예, 그 꿈의 수 마이파크. 예. 장희동이고요. 교정지로 도착할 때까지 문자체를 안내할 거니까 전화 끊지 마시고 조금만 더 통화 당하세요 차는 나가고 있어요. 예예 지금 이제 전화 끊지 마세요 차는 나가고 있으니 잠시만요. 네 지금 이제 일식은 찾으셔 갖고 일어나셨는데 전화 돌려드려야 되니까 잠시만 기다리세요. 네네. 어. 어 전화 드리면서 걸어갈게요 마지막 남았던 1명이 통화 연결돼 버렸네요. 전화 드리면서 하라고 하겠습니다. 예. 네.
 네, 1 2 9입니다. 뭐 주소한 걸까요? 환자가 있나요? 남동생이 남동생이 지금 복통이 심해가지고요. 네, 응급실 가실 거죠? 네, 응급실 가실 거죠? 네, 주소가 아파트입니까? 일반 주택입니까? 그 빌라예요. 빌라 주소가 어떻게 돼요? 중암동 성북구 중암동. 네. 삼정 빌라 잠시만요 삼정 빌라 네 남동생이 배가 아프다고요? 네 코로나 증상처럼 머리 열이 난다거나 호끼계란 그런 건 없죠? 네 그런 건 없어요 예 의식하고 이상 없고요 네 국차 갈게요 네

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 수고하십니다. 네 여기 상계주의 2단 잠깐만요. 동호수 다시요? 네 무슨 일이죠? 네 저기 호흡곤란한 사람인데요. 누구 관계 어떻게 돼요? 아저씨요. 아 남편이요? 네. 주소지로 보급차 보낼 건데 혹시 연락은 할 게 지금 코로나 확진 때. 그런 거 넣고 지금 말이 어누라고요. 갑자기요? 새벽부터 그랬는데 병원 안 간다고 도저히 안 되겠으니까 가야할 것 같다고 그랬어요. 네 알겠습니다. 그 부산을 여기로 보내겠습니다. 지금 공릉동에서 출발했어요. 좀 기다리셔야 돼요. 알았죠?
 잘 읽습니다. 네 여기 금오이가 하이비고. 예 아 주위 아저씨가 어저껏이든 조금 안 좋으시고 그러시더니 아 지금 저녁. 네? 지금 어디가 안 좋은데요? 아 그냥 막 떨리만 해요. 열은 안 나는데. 아 그래요? 예 그래갖고 막 몸부림을 치고 계셔요. 대화는 가능하시죠? 네 네. 뭐 코로나 격리 중이신가요? 혹시? 아니에요. 아니에요? 전화 오면 잘 받아주세요. 전화드릴까요? 밖에? 아니요. 부급대원이 전화할 거에 전화 오면 잘 받으시라고요. 예 예 예. 예 예. 다음 영상에서 만나요.
 연락 옵니다. 예 수고하십니다. 예 말씀하세요. 좀 1 2분 넘은데. 아 누가 어떻게 아프신 거예요? 아 네 아픈데요. 아 어디가 어떻게 아프세요? 아이가 지금 아픈데는 대상 포증이 원래 있는데. 예예. 어 어제 그니까 어제 30일 나가서 약을 타왔어요. 그 피부과 약을 탈툰하게 먹고 그걸 어제부터 먹었는데 어젯밤부터 그냥 계속 먹는 거라 설사라가지고 죽을 진행이에요. 그 약을 먹고선? 그 약을 먹기 전에 안 그랬는데 예 그 주소가 어떻게 돼요? 주소? 여기가 천호대로 천호대로. 강동구 천호대로. 예. 예. 아 거기 몇 층 몇 층 계세요? 아 가족분들하고 그 옛날 주소가 성내동 맞아요? 아 맞죠. 내 순번에 나도 이사온지 3년분이 안되는데 아 거기가 바로 그 성내동 주민센터 앞에 있는거 맞아요? 5거리인가 4거리 예예 맞습니다. 한양교회 옆이네요 한양교회 옆에 아 저희가 모든 출동볼에 코로나 관련 질문 드리고 있는데 혹시 발열이나 고열 기침 인후통 혹시더라도 코로나 관련 문의는 없으시죠? 예 그런 거 없고요. 아 그럼 대원들이 아. 대원들이 가면서 전화를 드릴 거예요. 전화 좀 받고 안내 좀 해주세요. 전화 드리면서 갈게요. 병원 상담은 저희 구급 대원들이랑 하셔야 돼요. 예. 예.
 네. 읽습니다. 여보세요? 네. 예. 여기 저기 뭐야 어 어 여기 손님. 여기 그 젊은 친구가 이제 막 뭐 뭐야 성인이 됐다고 술 만취돼가지고 지금 정신을 못 차리고 지금 있는데요. 아 그래요? 네. 네. 지금 지금 저걸 뭐 병원에 데려가든지 하셔야 될 것 같아요. 네. 그러니까 어디냐고요? 여기가 그 삼보 프라자요. 삼보 프라자요? 삼보 프라자. 삼보 프라자? 예예. 강서 강서구죠? 예 강서구요. 예 강서구. 여기가 락스타 코인 우려 영수장이거든요? 알겠어요. 일단 확인해볼게요. 뭐 연락을 뭐 코로나 격리 중이거나 이런 건 확인 안 되세요? 뭐 그건 아닌데 애들 3명이서 놀러 왔는데요. 술이 저렇게 취한지 몰랐는데 완전 저렇게 술이 그냥 아주 인사불청 돼가지고 머신해요. 여기 여기 여기 저기 뭐야 주소는 아세요? 아 예 삼부프라자 나오네요. 예 삼부프라자. 네 알겠어요. 네. 네.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네, 여보세요? 예, 아유 지금 저희 어머니가 네. 102살이신데요. 네. 지금 상황이 지금 힘이 없어 눈을 안고 지금 안 좋아서 좀 응급실 좀 갈 수 있었는데요. 의식이 제대로 운전하세요? 예, 운전하지 않고 지금 흔절로도. 호흡은요? 호흡은 쉬고 있고요. 호흡은 쉬고 있고 구급자 1 와볼 테니까 주소 불러주세요. 주소요. 주소요. 아 강서가 허준노. 네 여기가 주홍 7단지. 잠깐만요. 끊지 마시고 가족분들 중에 코로나 환자 있어요? 코로나 재택 필요하시는 분이다. 없습니다. 예. 고급차는 일단 추동 나갔고요. 의료 안내원 연결해 볼게요. 말씀 좀 해주세요.
 입니다. 여보세요? 예 말씀하세요. 예 저기 여기 강남 한양 수장인데요. 예예. 그 휩시증이 있고 휩시증 그 스탠드 4월 12일 날 스탠드 그 4개 넣고요. 예예. 지금 21일 날 또 3번째 잘라가지고 예예. 그 2개를 더 추가했거든요. 근데 지금 막 숨이 차고 예 막 강의 증세도 있고 예 선생님 본인이 그러신 거예요? 예 예 예 고급글러니 고 그 열 것들요? 예. 심히 엄청 많이 올라오고. 열 같은 거는. 열합도요. 95에 98? 예예. 지금 제 집에 있는 열합들이. 예예. 95에 98이고. 예. 제가 나이가 66에다가. 예예. 그 지체하지마비 위급 장애인이거든요. 예예예. 그 혼자서 하고 있고요. 예. 그럼 지금 굴처또하고 병원 한번 가보시겠어요? 예 아삼병원 기록이 다 있기 때문에. 아삼병원. 부서 예 강남 수자인 몇 동 몇 회예요? 수자인. 네? 문은 현관문 열어줄 수 있는 거예요? 예. 아 현관문 열어줄 수 있고요? 어. 알겠습니다. 그쪽으로 가볼게요. 예.
 예, 여기 사람이 하나 쓰러져 있어가지고요. 남자 여자요? 남자인데요. 의식은 있으세요? 모르겠어요. 지금. 숨을 쉬나요? 꼼짝 않고 있어가지고 제가 손을 대기가 좀 그래가지고요. 숨 쉬는지도 모르시겠고? 예, 엎드려 있거든요. 위치가 어떻게 돼요? 위치가 여기가 남구로 옆 쪽에서 4번 출구 쪽 방향으로. 나오면은 저기 일반 투명 길이 하나 있거든요. 네 4번 쪽으로 가면 되는 거예요? 아니 4번 쪽에서 좀 들어와야 돼요. 근처에 뭐 보이는 가게 같은 거 없어요? 그러면? 아 가게라고 한다면 여기 무슨 건강 세상 의원 건강 의원? 예 거기 있는 방향으로 쭉 들어오는 곳이거든요. 아 그럼 골목으로 들어가야 된다고요? 예예예. 그 몇 미터 정도 들어가요? 한 대략 한 20 미터 정도. 네 건강 세상 의원 골목으로 20 미터 정도? 예예. 네 저희가 한번 가볼게요.
 네 여기 어 역삼 호텔 삼정호텔 앞에 역삼동 네네 그 달리는 코끼 갈아올게요. 러닝래빗 네 네 그 선생님 1번 닫히셔서 구급차 1대만 부탁드리겠습니다. 몇 층에 있는 런닝 레빗이요? 네네 다툼 분이 남자예요 여자예요? 남자십니다 남자분이 어디로 다쳤어요? 머리 다치셨어요? 다툼으로 인한 거예요? 예? 혹시 다툼 싸움 일어나나요? 어 자세한 내용은 잘 모르겠고 일단 다쳐갖고 신고는 했거든요? 욕설이 들려가지고요 아아 예예예 네 선생님 그쪽으로 경찰서 같이 보낼게요 역삼동 언니 메일은 맞죠? 네. 네 알겠습니다. 의식은 있고요. 네 네 의식은 있으신데? 네 네. 기다려주세요. 네.
 너를 한참 바라보다 눈을 감았어 잠시 남아있지 아니 예 여보세요. 아 119 상황실인데요. 아 예. 아 그 혹시 지금 공동동에 넘어왔는데. 네네. 주 다방 앞에 계시는 거예요? 네 잠시만 다시 말씀해 주세요. 아 주 다방 앞에 계시는 거예요? 주 다방? 네 주 다방 앞이에요. 아 예 알겠습니다. 혹시 지금 상태가 어떠신 거예요? 환자분? 지금 의식 없고요. 예예. 자극을 줘도 전혀 반응이 없어요. 아무리 떼어도 이분이 없고. 아 그래요? 네. 가족이랑 연락됐어요. 아 숨쉬는 호흡 상태는 괜찮은가요? 잠시만요 잠시만요. 호흡하고 있어요? 호흡은 하고 있어요. 아 예 알겠습니다. 그 주다방 앞으로 갈게요. 네.
 아 네 저 저희 할아버지가 지금 많이 아프셔가지고 아 네 지금 옷 막 설사 피 나는 설사하고 네 주소 주소. 네 아예 움직일 수가 없어서 들 것 같은 것도 같이 필요할 것 같아요. 들 것도 가고요. 몇 층이에요? 거기? 집에 코로나 환자나 자가격리자 있어요 없어요? 아니요 없어요. 설사하고 기력이 너무 떨어지신 거예요 지금? 아니 피인 시설사랑 어저께 새벽에 목에서 피가 나왔다고 하셨거든요. 의식 호흡은 다 있으신거죠? 네 괜찮습니다. 구급차 보냈습니다. 네 감사합니다.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 119입니다. 아 저희 그 어머니가 코로나 백신 주사 맞으셨고 지금 너무 우스우스 춥고 막 숨쉬기 힘들다고 막 그러시거든요? 의식은 있으세요? 네 의식은 있고 춥다고 계속 지금 코로나 주사를 언제 맞으셨지? 잠깐만요. 좀 말씀해주세요. 주소. 주소 저기 서울시 승파구 미래 중앙로. 미래 중. 아니 미래 광장로. 몇 동 몇 호예요? 어 미래 중앙 프로지옥. 예예예. 그 차는 나갔고요. 네네. 어떻게 해야 돼요? 지금 어머니가 좀 어느 하나 조금 뭐지? 뭐지 그 뭐야. 질환이 있으신 분이셔 가지고 어떻게 해야 되지? 그 저 일단 나갔으니깐요. 전화 오면은 잘 받아주세요. 네네. 감사합니다.
 네, 고객님. 무슨 일이세요? 네, 거기 그 코로나 3차 백신 맞고요. 예, 언제 맞으셨어요? 한 3 3 3일 됐는데. 호흡 곤란이 와서 어젯밤에도 경찰이 한번 밀리고를 불러줬었는데. 네, 여성분께 안 거리세요? 이제 언제나 도저히 안 돼서 다시 전화드렸어요. 어, 2 3일 전에 맞으셨다고요? 네. 너무 힘들어서. 네, 선생님 혹시 주소지 어떻게 되세요? 어르신. 여기 지금 제가 은평구 역말로. 예, 거기 주차장에 있습니다. 예, 예. 주차장이 몇 층에 있어요? 그냥 앞에 도로변에 있는 주차장 차 안에 있습니다. 차량 내에 계시고요. 무슨 차예요? 그냥 그 빨간 아이서티예요. 아이서디 아이서디 네 구급차 편성해서 보내드렸구요 의료지도 좀 응결할게요 전화 끊지 마세요 네

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 16입니다. 아 네 여기 지하철 5호선 천호역인데요. 5호선 천호역이요? 네. 네 천호역 강동 방향 승강장. 5호선 천호역이고 강동 방향. 승강장 3단 2번 칸 앞이고요. 네. 어르신께서 지금 그 걷기를 굉장히 힘들어하시고. 네. 네. 그러셔 가지고 다리가 그 관절 있는 쪽이 많이 아프다고 하셔서요. 아 선생님 역무원이세요? 아 3자세요. 예 앞으로 그 부터 보낼게요. 네 감사합니다.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 메인 오면 안 왔어. 예 여기 여기 싸와 싸와 빨리 나와. 싸웠다고요? 예. 어디다 치고 가세요? 지금 난구로요. 난구로. 따뜻하고. 환자 몇 명이에요? 4명 4명이에요. 환자 환자 몇 명이냐고요. 선생님. 네. 네. 네. 4명? 빨리 오세요. 4명이요? 네. 난구력 까분 추구. 쓰지 않으면 돼. 난구력 당하시고요? 네. 빨리 오세요. 네. 알겠어요. 관계가 어떻게 되는 거야?

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네. 미안합니다. 이 저 바로 날 이 환자가 생겨서 전화를 드렸습니다. 주소가 어떻게 돼요? 주소가 이 정원로 지금 몇 호예요? 예. 옛날 주소를 하게 되면요. 신림동 한자가 누구에요? 어디가 아프신거에요? 네, 걱정설사에요 본인이 아프신거에요? 아니요, 내가 아니고요, 난 누가요? 한자가 누구에요? 네, 집사람이에요 지금 의식은 있고요? 네 가족분들 코로나 장학영리나 확진 관련된 건 없어요? 없어요 네, 알겠습니다. 수정할게요 네 감사합니다.
 119 사항 신사 말씀하세요? 어 저 산소포화도가 자꾸 치고 떨어져요. 어 산소포화도가 어떻다고요? 자꾸 70 80%로 자꾸 떨어져서요. 누가요? 응급기 가야 될 것 같은데. 누가 그러신 거예요? 환자가요. 관계가 어떻게 되시는 분이에요? 아빠가요. 네. 아버님이 뭐 원래 산소 치료를 하시는 분이에요? 네 지금 산소 발생을 하고 있는데요. 아 주소가 어떻게 돼요? 여기 근창구 독북 독산로 네 60길 60길 네. 아버님 의식은 괜찮으세요? 네 의식은 있어요. 근데 숨을 잡고 막 모셔가지고 예. 코로나 관련은 없는 거죠? 어 네네네 원래 이렇게 폐쇄해서 예. 예 알겠습니다.
 119입니다. 아 예. 코로나 부작용 때문에. 코로나 부작용이라는 거예요? 코로나 확진자예요? 아니면 백신을 맞고 부작용이라는 거예요? 백신 맞고 부작용이에요. 3차 백신 맞고. 어떤 부작용이 있어요? 어 어 막 다리가 한쪽이 마비가 돼가지고. 한쪽이? 뭐 끊임없이겠어요. 어 네 주소는 어떻게 돼요? 어 여기에서 저 도공구 우이천로 오 여기 선로예요? 거기가? 우이천로 네 우이천로 가락길 사 가길? 가 라 가나 가라 라길 잠시만요. 초안 심도 브래뉴에요? 예예. 예. 병원 가실 거죠? 지금? 예예예. 예. 전화는 끊지 마시고요. 예. 아 어 다리가요. 다리가 좀 납이가 온 것 같아요. 강 다리 없어요. 하얗. 다리 1번 더 하얗게 되면서. 네 지금 호흡차는 가고 있고 의료 지도 해드릴 거니 끊지 마세요.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네 여보세요? 119 3호 이시네요? 네 여기 그 방금 전화했는데 예 그건 아직도 그쪽에 계세요? 여기 통합 아파트 어 잠시만요. 예. 세번 일로 문 앞두시고. 네. 공사 쪽으로 보내드리고 있는데 의식이랑 호흡 상태 좀 확인해 주세요. 지금 멀쩡한데 술에 취해 있어 가지고. 알겠습니다. 다시 켜야겠습니다. 네. 감사합니다.
 119입니다. 예예예. 예. 잠시만요. 예. 저희. 예. 저희 큰 애가요. 예예. 어, 백신을 맞은 지. 3일 오늘이 3일째인데요. 아들이 딸이에요? 제 딸이에요. 아, 선생님 그러니까 구급차 요청하시는 거죠? 네 21살이고요. 지금 백신 무작용으로 호흡 곤란이에요? 주소 알려주세요. 출동할게요. 현대아파트 현대 1차 아파트. 잠깐만요. 현대 1차 아파트. 예예예. 예예예 구급차 지금 출동시켰구요 예예 가는 도중에 의료지도 연결할게요 끊지 마세요 예예예

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 일로 봅니다. 아 네 안녕하세요. 그 환자가 있어서 병원을 가야 될 것 같은데. 아 가까 어디 가신 분이세요? 지금 계속 토하고 예. 너무 심해가지고. 아 가족분이세요? 네네. 그리고 혹시 그 저희가 병원 원하는 곳으로 갈 수 있나요? 기준으로. 아 저희 저희 응급차 이송 원칙은 가장 가까운 치료 가능한 응급실로 가는 게 원칙으로 돼 있고요. 네네. 병원 선정은 제가 결정할 수가 없고요. 출동 구급되고 환자 상담사가. 상태를 보고 결정하시는 거라 그 현장에 나가서 환자 상태를 보셔야 될 것 같아요. 어. 그래요? 그 가족분이 뭐 어떻게 되세요? 관계가 환자분이랑? 딸이요. 딸이요. 어머님이 약 부신 건가요? 아버님이 약 부신 건가요? 어머님? 그 주소가 어떻게 되세요? 구급처 보내드릴게요. 강서구 강화동이고요. 강서구. 강화동. 예. 네네 외충 외충에 계시나요? 건물 이름은 어떻게 되는 거예요? 아니 건물 이름이요 건물 이름 삼성 베스티빌이요 삼성 베스티빌 아 저희가 모든 출동권에 코로나 관련 질문 드리고 있어요 네네 그 혹시 가족분들 포함하셔도 발열이나 고열 기침 인후통 혹은 그냥 코로나 관련 증서 없으시고요? 아 흡증자를 접촉을 하셨거나 자가 경리 상태이신데 안 계시죠? 아 저희 대원들 전화 드리면서 갈 거니까 전화 좀 받아주시고요. 예.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 예, 고생하십니다. 아 예, 경찰관입니다. 그 저 신고 좀 하려고요. 예, 예, 예, 주소부터 알려주세요. 수요역 수요역 주황차로인데요. 맥도날드 맥도날드 수요역 맥도날드요. 아 맥도날드 앞에? 주황차로 예, 예, 예, 예. 그 유리 유리창을 손으로 깨가지고 손에 좀 침 다쳐가지고. 아 남자분이세요? 예, 남자분이요. 아 예 알겠습니다. 제가 수동할게요. 혹시 뭐 코로나 관련해서 뭐 반려주신 사이 확인되는 거 있나요? 네. 네. 네. 네. 어디 있는지 정확하게. 네. 지갑이 어느 쪽에 있어요?
 네 여기 동로구 낙원동 알리아스 모텔인데요. 여기 저희 손님 초소객 손님이 계속 아프다 아프시다고 하시면서 근데 지금 예 일어나시지 못하시는데 출중해주실 아프 어 네 어디가 아픈지는 모르시고요? 그냥 온몸이 다 아프시다고 아 그냥 일어나시지도 못하고 계속 왔다. 남자분인가요? 남자분이요. 저희가 뭐 웨트로 가야 되는데요? 네. 저 악원동. 에 에 그러니까 코로나 뭐 격리 중인 환자 아니고요? 아니 아니요. 그런 건 아니었는데 예 연락주가 그런 건 없었어요. 그러셨을 땐 그런 거. 전화 오면 잘 받아주세요. 네.
 네, 감사합니다. 말씀하십시오. 네, 아까 저기 전화했었는데 그 그 오셨다가 다시 하셨었거든요. 그래서 다시 그 뭐냐 저희 코로나 검사 결과 나오면 연락 달라고 하셔가지고. 네, 네, 네. 네, 그 결과 나온 게 진짜 음성이거든요. 아 그래요? 다리의 통증 때문에 신고하신 거죠? 네, 네, 맞아요. 아 그러면은 어디 주소가 어떻게 됩니까? 네, 기하동. 네. 네. 다리통증... 네. 예 지금 차 보냈고요. 네. 코로나 관련된 증상은 없으시죠? 뭐 기침 발열, 호흡기 질환이나 이런 그런 건 없어요. 그런 거 없고 그냥 같이 근무하시는 사무실에 학생자분이 나와서 검사를 받으셨는데 지금 좀 전에 음상 나왔다는 얘기죠? 아 네네네. 알겠습니다. 응급실 진료 받으실 건가요? 아 네. 아 예 알겠습니다. 네 감사합니다. 예.
 네, 고입니다. 아 네, 저희 지금 와이프가 지금 임시 중 한 상태인데 갑자기 피를 너무 헤매고 있어요. 피 하열했다는 거예요? 네, 네, 네, 계속 풀려요. 예, 주소는요? 예, 강동구 아 고동로. 고동로. 거기가 고덕 리엔파크 쪽에요? 네, 네, 네. 전화는 끊지 마시고요. 네네. 아 구급대가. 아아 그리고 아산병원 지금 다니고 있어요. 네 그거는 구급대원하고 상의를 하셔야 되고요. 네. 네 저희 지금 의료 지도 해드릴 거니까 끊지 마시고요. 네.
 네, 감사합니다. 아 혹시 여기 알코올 그거 돼요? 알코올이라고요? 네, 좀 알코올 좀 술 많이 먹는 사람 그거 뭐 그런 거 없어요? 여기는 뭐 긴급 신고인데요. 뭐 어디에 다치거나 그런 건 아니세요? 다친 거 없는데 좀 와 술 많이 먹으면 좀 그런 거 있잖아. 정신 나간 거 막 그런 거 있잖아요. 아 뭐 인사 불송 그런 상태예요? 네, 네, 네. 어 저. 아 좀 제가 부탁드릴게요. 저희가 나가면은 병원 응급실로 가시는데 괜찮으세요? 아 선생님 저희 아빤데 술을 너무 많이 먹으니까 이게 사람이 미쳐를 씹고 나와가지고 1월 1일부터 또 오늘 알겠어요. 혹시 모르니까 출동 나가볼 테니까 주소 예 주소 한번 불러보실게요. 아 지구대에서 전화해도 지구대에서는 그냥 보내가니까 이거 좀 심각해 진짜 예 도와드릴 테니까 주소 한번 불러주세요. 상월곡동에 상월곡동 옥탑이요. 옥탑층 옥탑 혹시나 뭐 환자분들이나 가족분들이 코로나 환자 없죠? 예 계속 나가보겠습니다.
 어 어 여기 영동소요. 아 그쪽인데 지금 땀이 나서 어떤 사람이 머리 피나서 쓰러졌어요. 쓰러졌어요. 땀이 났다고요? 땀이 쓰러지셨는데 머리 피나고서는. 남성분 1명이에요? 남성분? 남자분 2분이에요. 제가 지금 지나가다가 말리고 있는 거거든요. 알겠어요. 그럼 제가 가볼게요. 여기 라모 라모진 양고기 화루구이 점은 좀 바로 안 돼요. 화루구이요? 네 라모 라모진. 라모지? 네 라모진. 알겠어요. 네 네.
 예 여보세요? 예 여기 119구요. 그 고랑 고등학교 앞으로 출동하면 되는 거죠? 예 고랑 고등학교 앞에 바지락 흑백이 바지락 칼국수랑 간판이 있어요. 그 환자분 몇 명이에요? 한 분이요. 아 의식은 있나요 선생님? 네네. 아 예 알겠습니다. 출동할게요. 네.
 네, 1 2 9입니다. 여보세요? 예, 말씀하세요. 1 2 9입니다. 저 조용히 가요. 여보세요? 예. 예, 소방서 1 2 9죠? 예, 1 2 9입니다. 예, 예, 여기 광진구 구이 강변동. 예. 폴라트리온 13차 폴라트리온인데요. 예. 할머니가 쓰레기 해갖고 지금 쓰러져 있었어요. 몇 층 몇으로 가야 돼요? 예 그 오피스텔. 예. 예 저 입구로 정문으로 오시면 돼요. 가는 거예요? 예 이기와 저 폴라트림 앞으로 오세요. 제가 서 있을게요. 경비실에서 서 있으세요. 선생님 경비원이세요? 예. 할머니 의식 있어요? 의식 있어요? 의식이 없어요. 의식 없어요? 숨을 쉬어요? 숨을 쉬어요? 아 할머니가 오셔갖고 주변에 할머니가 오셔갖고 아직 정확한 건 모르겠어요. 저도 인제 지금 말씀 할머니 말씀 듣고 전화드렸어요. 우선은 차 안 출발 시켰고요. 숨 후 확인이 중요해서요. 저희 의료진 좀 연결할게요.
 네, 안녕하세요. 네, 여기 119인데요. 혹시 경찰 왔어요? 선생님? 예? 경찰 왔어요? 뭐라고요? 경찰 도착했어요? 경찰 수거하셨잖아요. 네, 경찰이 부르셨어요. 아, 그 환자분이 있는 거예요? 네, 지금. 거울 가실 분이? 네, 예, 예. 아, 1분이시죠? 예, 예, 1분이요. 포켓 당하신 건가요? 아니요. 아침에 지금 들어와가지고 요가실 전에 또 있는 거 아프시래요. 많이 그래요. 저희 응급실로 간다고 경찰한테 얘기 좀 해주세요. 경찰님 저기는 응급실에서 간다고 얘기해 달래요. 예 잠깐만요. 바꿔드릴게요. 네. 예 경찰관인데요. 저희 지금 대한들 나갔고요. 예 지금 여기 미아리 식당에서 식사하셨던 분이 발가락이 아프다고 하면서 못 벗고 있어요. 아 그래요? 1주일 9일 불러달라고 요청을 저희한테 해가지고 저희가 요청을 드렸고요. 지금 미야리우동집 밖에 관자 데리고 나가가지고 아 그래요 알겠습니다. 네.
 네 저기 집사람이 감사드리고 복통에 너무 시달리다가요. 지금 거의 견딜 수 없는 상황이어가지고. 지금 뭐 의식은 괜찮은죠? 의식은 괜찮아요? 예 의식은 있어요. 아 이거 거동이 힘드시고요? 예 거동 힘들고요. 예 주소 불러주세요. 어 송파구 잠실로. 예 레이스 팰리스예요? 예. 예예 안해보고 열이 나기 지금 코로나 관련 사항 있으세요? 코로나 관련은 없는데 지금 열을 뒤에 보니까 한 37. 뭐 몇 도 그렇게 나오네요. 조금 리얼은 있는 것 같아요. 아 예 알겠습니다. 전화 잘 받으세요. 예 알겠습니다. 예.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네 이리옵니다. 예 어 교통사고 났는데 숯고개로 숯고개로 예예예. 차 몇 대 사고 났죠? 어 차하고 오토파이하고 사고 났어요. 아 그래요? 오토바이 타시면 차 밑에 깔려 있는 건 아니고 의식은 있나요? 예예 의식 있어. 경찰분이 옆으로 좀 운대 놨어요. 알겠습니다. 우리 부부차 빨리 가겠습니다. 예예예
 네 여기 용산 파크자이 용산 파크자이 네 디동 네 네 디동 네 네 여자친구가 지금 배가 너무 너무 많이 아프다고 움직일 수 없을 정도라 해서 해서요. 같이 계세요? 네 네 같이 있습니다. 네, 네. 너무 아픈 생통 같다고 하네요. 네 차 나가볼게요. 찌균쌤 나고요. 네 네. 네. 나 보세요. 네 전화 잘 봐주세요. 네 네.
 119입니다. 예 여기요. 신당 2동이요. 예. 예. 저기 아버지. 지금 어디 피 많이 나시거든요? 친구들아 분. 네. 신착하시고. 예. 신착 갈 거니까 주소를 좀 말씀해 주세요. 아버지 머리 칠. 여기. 동으로는. 동으로 11. 동으로 11. 발길이요. 바람쥐할 때 다예요? 박일. 봐요. 바 바. 바 길 바람할 때 바 길이고 몇 다시 몇 시예요? 예 빨리 빨리 저 수건. 예. 성주 타운 몇 몇 도예요? 그러면 거기. 아버지! 수건으로 상처 부위 제거 교실 눌러서 지워만 도와주세요. 출동했으니까 환자분 신중시켜주세요. 흥분하지 마시고
 여보세요? 아 저기 우리 집 아저씨가요. 어지러워서 못 일어나시는데. 병원을 좀 갈라 그러는데. 좀 오시면 안 될까요? 예. 그것을 말씀하시는 거. 소소가 어떻게 돼요? 예? 여기요? 네. 저기 도봉동 럭키 아파트예요. 럭키 아파트. 럭키 아파트요? 네 네 네. 80이 넘었거든요. 네 코로나 자아경이면 확진 가진 건 없으시죠? 그런 건 없어요. 예 지금 남편분 지금 의식은 있고요? 예 의식은 있어요. 일어나질 못해요. 아 알겠습니다. 수고할게요. 네. 네.
 1라곱니다. 네 수고하십니다. 저기 자동차에 끼어갖고 무릎이 많이 부었는데요. 지금 뭐 껴있는 상태예요? 아니면은? 아니에요. 빼서 이제 집으로 올라왔는데. 네예. 지금 조금 더 움직일 수가 없고 그래서 혹시 응급실 중에 어 지금 가면 진료가 되거나 치료가 되거나. 아 갈 수 있는 응급실 찾고 계신 거예요? 아 네 그리고 구급차도 필요할 것 같고요. 못 움직여서요. 누가 다치신 거예요? 제가 본인 저예요. 아 그 계신 곳 주소 좀 알려주세요. 행당 대림 아파트. 잠시만요. 행당. 행당 대림 아파트. 네, 네. 아, 혹시 뭐 그 뭐 교통사고 나신 이후로 뭐 경찰 분들은 왔다 가셨어요? 아니요, 아니요. 예, 예. 가족차인데 문. 아, 그래요? 예, 출발을 그 안 탔는데 출발하는 바람 문 사이에 다리가 끼었어요. 알겠습니다. 저희 구급차는 갈 거고요. 예, 예. 저희가 모든 출동권에 코로나 관련 질문 드리고 있어서 차 가는 동안 제가 몇 가지만 여쭤볼게요. 아 근데 만약에 구급차 오시면은 제가 갈 수 있는 병원이 지금 현재 있기는 합니까? 저희 여기서? 저희가 갈 수 있는 가까운 응급실로 이송하는 게 원칙이고요. 병원 선정은 저희 구급 배원들이 하시게 돼 있어서 출동을 나가서 병원을 찾아봐야 될 것 같아요. 예. 아 네. 중요한 거는 이제 코로나 관련 질문을 여쭤보게 돼 있어서 몇 가지 여쭤볼 건데요. 뭐 가족분들 중에 발열이나 고열 기침 이런 호키지나 코로나 관련 증서 있으신 분 안 계시죠? 예. 아 코로나 확진자를 만나셨거나 자가 구매하시는 분도 안 계시고요? 예. 아 대원들이 전화드리면서 갈 거니까 전화 좀 받아주세요. 네. 못 걷습니다. 네. 네. 그 전화 좀 받아주세요. 예. 예.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 음 통칭이 다르. 7일 9입니다. 말씀하세요. 여보세요. 예 여기 영동포구의 양평동 삼성 아파트거든요. 몇 동이라고요? 네, 누구 어떻게 아프세요? 아, 남편이요. 지금 통증이 아까 낮에서부터 있었는데 지금 소변을 못 보고 너무 아파하네요. 아, 그러면 그 배가 아프신 거예요? 일단 소변을 못 보고? 네네, 등쪽으로 해서 앞쪽으로. 아, 네, 알겠습니다. 그럼 구급차 바로 보내드리면 되는 거죠? 네, 근데 너무 시끄럽게 저기 하지 마시고 오셨을 텐데. 네 알겠습니다. 또 현재 뭐 코로나 관련해서 열이나 기침 이런 증상 있었나요? 그런 건 없고요. 거기 그 3차까지 다 맞았거든요. 그리고 부토를 하네요. 아 네 알겠습니다. 조금만 기다려 주세요. 네 네 감사합니다.
 예, 일곱니다. 네, 여기 은평유타운 10단지 버스 정류장 근처인데요. 그 차가 그 그 은평유타운 방면으로 가다가 혼자 부딪쳐가지고 멈춰있거든요. 도로에. 승용차 아니면 무슨 차요? 네, 검은색 코스카거든요. 테라리. 지나가시면서 오신 거네요. 네네. 저희는 멀리 있는데. 저 사람은. 몇 동이 제일 가까워요? 음청리턴 10단지 근처인데. 잠시만요. 너무 머니까 근처에 있는 동 1만 불러보세요. 그 아. 네. 그니까 10단지에 10단지 안에 너무. 범위가 넓어요. 근처에 보이는 동 1만 안 와요. 제일 가까운 데 있는 동 1 불러보세요. 잠시만요. 네. 지도 1번 보고 연락드릴게요. 네. 지금 보고 있어요. 저도 지금. 네. 갈게요. 사람은 나와서 안 나왔어요? 나온 거 같거든요. 근데 저희가 네.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 119 그냥 불러주세요. 여보세요. 지금 어머니가 옆 옆 쪽이 너무 아프셔서 못 참 못 참으시켰다는데. 예예. 출동 요청하시는 거죠? 예예. 예. 주소지 불러주시면 나갑니다. 예. 신당 5동 현대 아파트. 신당 5동이요? 현대 아파트 건물이 좀 많아서 그런 정확한 주소는 모르세요? 아니 뭐 신당동 몇 번지 아니면은 뭐 무슨 노 무슨 길 다산 다산 노 다산 노 다산 노 네. 찾았습니다. 현대 아파트 그 가족 중에 뭐 코로나 확진자 있거나 뭐 재택치료자 있거나 어머니가 열나고 귀찮고 물 감기 증세는 없으세요? 예예. 네. 주통 나갑니다. 전화 오면 잘 받아주세요. 그 보호자는 1명만 따라갈 수 있나요? 네. 아마도 보험 때문에 보호자는 1명만 동승 가능한 걸로 알고 있습니다. 예.
 예. 169입니다. 예. 우리 망으로 저 아버지 주문하시는 거 같은데요? 예. 주소 다시 1번만요. 망으로. 중랑구 망으로. 예. 예. 예. 하셨습니다. 어. 망으로. 중랑구 망으로. 예. 중랑구 망으로 옛날 주소는 혹시 없으세요? 뭐 휴경동 몇 번지? 아 시 저기 중랑구 시 저기 잠깐만요. 아 저 별거 없어요? 예. 아 알았어. 아 그 저 이 번호가 좀 옛날 주소라도 알려주세요. 수경동 몇 번지. 아니 저기 상봉 저기 망으로 65 낙일. 예. 65 낙일. 아 65 낙일. 찾았습니다. 나이대가 어떻게 되시는데요? 나이 98세여 97세여. 원래 지병으로 누워 계셨나요? 어떤 상황이셨어요? 아니 오늘 아침에 아까 식사 안 하고 계속 저기 계시는데. 지금 저기 계속 못 신고자 분 계시라고요? 예예. 알겠습니다. 저희 구급차 지금 출동하고요. 예예예. 예. 의식은 없으시고 호흡 상태는 정상인지 아닌지 한번 호흡 있는지 없는지 한번 봐주세요. 호흡.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 예, 예, 고입니다. 아 예, 수고하십니다. 저 여기 합정역인데요. 합정역이고. 예, 예, 합정역이고 여기서 지하철에서 계속 올라갔다가 넘어져가지고. 아 몇 번 주구점이세요? 지금 여기 합정역에서 지금 나가는 쪽이거든요? 어디로 나가요? 제가 저기 저기 구호선인가? 이 우선은 일단 나갈 거니까. 어디 쪽으로 보면 만나 만나실 수 있을까요? 어디로 가능하면? 잠시만요. 네. 잠시 제가 이 체크 바로 전화드릴 아 잠시만요. 네, 네. 여보세요? 네, 네. 예, 일단 10번 출구 쪽으로 나갈게요. 10번 출고요? 예. 알겠습니다. 환자가 남자예요? 여자예요? 여보세요? 여보세요? 지금 루코선인 거 왔거든요? 루코선에서 지금 나가다가 엎어져가지고. 루코선에서 나가다가 엎어졌고 10번 출고 아래쪽으로 가라고 할 거고요. 환자가 남자예요? 여자예요? 여자 여자입니다. 여성분이요. 저희가 나갈 테니까 전화 오면 잘 받아주십시오. 예 턱 밑에가 좀 찢어지고 입 다리 좀. 예 알겠습니다. 같이 나가보겠습니다. 일단요.
 죄송합니다. 아 제가 집에서 야식하려고 하다가 사진을 찍었거든요. 피가 계속 나는데. 아 피 많이 나고 있어요? 네 공원은 안 열어가지고 어떻게 해서. 응급실 가보시겠어요? 혹시 가까운 응급실 어떻게. 아 저 구급차 보내드릴까요? 네. 네. 구급차 필요하시죠? 아 예. 수강 같은 거 있으면 예. 지열 좀 해보시고요. 선생님 뭐 운전하실 분 있어요? 같이 가실 분 있어요? 다름이 더 안되시면 고급차로 보내드릴게요. 네. 주소 좀 알려주세요. 어 여기 어 감성구 태진 한솔 아파트? 어 태진 한솔. 네. 네. 지금 출발할게요 선생님. 지원 좀 하고 계세요.
 네. 일요일입니다. 아 네. 여기 서대문구 남과자동 남과자동 아 저희 남편이 지금 쓰러지진 않았는데 풍이 좀 온 거 같아요. 아 증상은? 네. 증상은 어떤 증상이 있어요? 아 몸을 못 움직여요. 입도 네 입도 조금 돌아간 거 말도 잘 못해요. 아 그래요? 잠시만요. 그 토예요? 1 1 뿐이 없어요. 1도 없고 잠시만요. 수고하세요. 몸무게가 좀 많이 나가요. 거동하는 건 어때요? 한쪽으로 기울어요? 네네네네. 코로나 가진 증상은 없어요? 열이나 기침 호흡 곤란. 그건 없는데 혀가. 혀가 마비된 거 같아요. 좀. 아 그래요? 그 전화번호 좀 알려주세요. 네, 네. 빨리 좀 와주세요. 네, 일단 고객자 보냈고요, 선생님. 저희가 의료진 연계에서 응급자치 안내할 거예요. 전화 끊지 마세요. 네.
 119입니다. 예예. 여기 그 염창동 삼정 그림코 아파트 삼 뭐라고요? 삼정 그림코 아파트 잠깐만요. 삼정 예 그린코아 그린코아 예 아파트 예 그 저희 집에 그 저기 누나가 독성 장문 온거 같은데 예 그게 오면서 지금 환자가 거동이 안되서 119 은근시 가야되는거에요? 아 잠깐만요 아니면 뭐 의료상담이나 안내가 필요한지 여보세요? 예 저기 딸이요 저기 뭐야 그니까 환자가 거동이 안되서 119 은근시 가야하는거에요? 거동보다 지금 저기 뭐야 그 급성 장염에 왔는데 손이 막 마비가 오고 그래갖고요. 운전할 사람이 없어요. 집에. 그러니까 갈 수 있는 상황이 아니라서 이 고급차로 가셔야 된다는 거죠. 연결실로. 예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예예 항상 있다고 하니까 고급차 가는 동안 우리 집 연결할 것 같습니다. 아 마비라서 풀리는 것 같다고 했는데 증상 얘기해 주세요. 같이 계시죠? 환자랑. 네네네. 네. 그렇게 하세요?
 119입니다. 예 여기 지금 사람이 갑자기 화장실 가다가 정신이 없는데요. 사람이 정신이 없다고요? 쓰러지신 거예요? 그분이? 아니요. 할머니가 집에 계시는데 돌리 보러 가시다가 갑자기 정신이 있고 쓰러지셨어요. 쓰러지셨어요? 의식 있어요? 없어요? 잠시만요. 의식이 있어서요. 바꿔드릴게요. 여보세요? 의식이 있어요? 없어요? 의식이 없어요. 의식이 없고 숨 쉬어요? 안 쉬어요? 네 숨을 쉬어요. 숨을 쉬고 주소가 어떻게 돼요? 관악구 양녕로? 양녕로예요? 네. 잠시만요. 관악구 양녕로. 양녕로. 네. 거기가 벽산 블루밍이에요? 네. 예 그거 집안에 코로나 환자나 고역이 지민호통장은 없으시고요? 네. 네. 구급차는 출발했고요. 전화는 끊지 마세요. 의료 지도해 드릴게요. 네. 네.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 119입니다. 네. 아 네. 여기 지금 환자가 너무 어지러워서 그러는데 지금 말씀해 주실 수 있으세요? 환자분이 여자예요? 남자예요? 남자요. 남자분이고 어지럽고 어떤 증상이 있어요? 아 그니까 움직이지 못해요. 전혀. 그리고. 더동을 못해요? 예. 그리고 좀 몸에 마비가 오려는 것 같아요. 그냥 어리. 아내분이신 거예요? 네? 아내에요? 아내분이세요? 아니에요. 아니에요. 이제 고모고 조칸데 지금 부산에서 올라왔는데 갑자기 그렇게 며칠 전서부터 어지러워 지금 갑자기. 네, 예. 거기 주소가 어떻게 돼요? 어 홍대 홍대 홍대동. 홍대동. 홍대원 현대아파트. 네, 거기 주 주소는 모르세요? 여기 주소 어 통일로. 통일로. 네, 네, 네. 홍재원 현대아파트. 잠시만요. 홍재원 현대아파트에 몇 동이 몇 호예요? 네, 네. 예, 알겠습니다. 코로나 환자나 고열 기침 위드통 있는 분 없죠? 네? 코로나 환자나 고열이나 비침이나 일후통 예 알겠습니다. 10분 정도 걸려요.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 연락입니다. 예 여기 주공합 저 저 본동 주공합과 예 예예. 무슨 일이세요? 막 슬력으로는 막 자꾸 쓰러지고 그래서 걸어 다니지 못할 것 같아갖고 병원에 가야 될 것 같아갖고요. 아 예 그것처럼 보내드릴게요. 환자분 남자분이 여자분이에요? 남자분이에요. 지금 의식은 있고요? 예 의식은 있어요. 숙여 되려고 하시는 게 어디로 오신 거예요? 예예. 그 가족분들 포함해서 코로나 자가 겸이나 확진 관련된 건 없고요? 네네. 예 알겠습니다. 사실은 그 저기 오늘 을지 병원에 중환자실에 있다가요. 네. 퇴원을 했는데 나올 때도 사실은 몸 상태가 안 좋은 상태였는데 퇴원을 했어요. 아 네네. 근데 뭐 자기가 원하는 병원이 지금 뭐 고대병원으로 가고 싶다고 그러시는 거 같아요. 아 예 그거는 그 또한 부급 때문에 하고 한번 얘기해 보시면 돼요. 네, 네, 알겠습니다.
 119입니다. 예 안녕하세요. 여기 국도 호텔인데요. 국제 호텔이요? 국도 호텔이요. 국도 호텔이요? 예예예예. 예 무슨 일이세요? 네 다름이 아니라 저희 손님이 정리 중이신데. 예. 이분이 지금 폐기종이 있다고 하시면. 지금 식은담이 좀 많이 흐르시고 쓰러지기 직전이시라고 지금 전화를 받았거든요. 식은담 흐르고 좀 쓰러질 것 같다고요? 네 그래서 혹시 이런 경우에도 출동 가능하신지 문의차 전화드렸거든요. 어 폐기종 경력 있어요? 네 지금 폐기장 때문에 수술을 위해서 입국하셨거든요. 어 네 뭐 지금 코로나 확진자인가요? 지금 확진자는 아니죠? 아니요. 예 확진자는 아니고 입국하셨어요. 아 입국해서 격리적인가요? 네. 어 선생님 일단은 저희가 뭐 그분께서 많이 힘드셔서 지금 응급실에 가셔야 되는 상황이면 저희가 고급자한테 출동할 수 있고요. 지금 그분께서 뭐 거동이 지금 안 되시는 상황이신가요? 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 예, 일단은 지금 뭐 이분께서 열 열음 있나요? 열 있는지 없는지 확인이 안 되시죠? 네. 어 알겠습니다. 지금 지금 그럼 구급차가 필요하셔야 하는 거예요? 아 그렇죠. 일단은 이분 상태가 지금 쓰러지시기 직전이고 폐비기종이라고 말씀을 하셔서 저희도 이제 정확한 저거를 할 수 없기 때문에 일단 119에 전화를 드린 거거든요. 아 알겠습니다. 그럼 이쪽으로 저 뭐 뭐 프론터가 안 되나요? 네 일단 프론트 오시면 저희가 안내 도와드릴게요. 예 알겠습니다. 제가 구급차 신청했고요. 혹시 모르는 번호 전화하게 된 사람 잘 받으세요. 예 감사합니다.
 예 119 상황입니다. 말씀하세요. 네 지금 오한이 오고 떨려서 움직이질 못하거든요. 어머니인데. 어머니가? 네. 열이 있는 거네요? 열은 없어요. 몸이 떨리는 게 열이 나서 떨리는 증세거든요? 아 그래요? 그 배도 아프고 그렇게 가스가 트서 못 움직이니까. 거동이 힘들다고요? 주소가 어떻게 돼요? 네 그 서울 관악구 미성동. 미성동 예. 네. 네 차량 보냈구요 전화 잘 받으세요 네
 네 지금 엄마가 숨이 답답하시다고 안 서신다고 하시거든요. 지금 같이 계시고요. 네 주소지 어떻게 되세요? 여기 지금 목동 중앙동. 예. 어 잠시만요. 금호 베스트 맞으세요? 네 맞아요. 아파트. 네, 네. 고급차는 지금 그쪽으로 보내드리고 있고. 네. 기침이나 열 목구멍 통증 같은 코로나 증상은 없으세요? 네. 다른 짐 같은 것도 없으셨고요? 어 며칠 전에 수술하셨어요. 어떤 수술하셨어요? 복관경 수술이요. 자궁 빈종이랑. 자궁? 네. 네. 두 두 수술하셨어요. 복관경 수술하셨고요. 알겠습니다. 차 시켜서 가고 있습니다. 네 감사합니다. 잠시만요. 네. 물어주는 연결 좀 할게요.
 119입니다. 여보세요? 네 119에요. 예 병원 좀 하려고요. 여기 봉촌로 몇 층이에요? 지금 누가 아프신거에요? 아 뭐 잠시도 록 배가 아파가지고요 아저씨가요 남편분이요? 네 남편분이 거동이 안되서 고고차 물으시는거에요? 아니 차도 지금 콜센스도 부르니까 안되고 그랬어요 택시가 안 잡힌다고요? 네네 네 알겠습니다 혹시 남편분 코로나19에서 기침 발효 증상 보인다거나 신발의 증상 보인다거나 확신 그런 거는 없어요. 지금 배가 편찮아서 그래 배가 좀 어저께 뭘 많이 먹어가지고 네 알겠습니다. 제가 구독자 받으니까 모르는 번호 전화 1번 전화 받으세요.
 예, 수고합니다. 예, 여기 지금 사람이 좀 아파가 그러는데요. 누가 어디가 아픈 거예요? 지금 아파가 똑같고 구분헌데. 누가요? 누가. 우리 마느라가요. 어디가 아프신 거예요? 증상이요? 증상이요? 말을 안 하니까. 뭐 배가 아프신 거예요? 아니 선생님. 새벽부터 아팠는데. 네. 그니까 어디가 없어요? 아니 배도 아프고. 헐서 아프고 지금 사람이 말을 못해. 너무 아파가지고. 주소를 알려주세요. 주소 주소 주소. 네? 마천동. 아 마천동. 예. 며칠 며칠게요? 지금 코시 코로나가 있는 증상 없어요? 열이나 기침 호흡 곤란이요. 아 그런 건 없어요 3차까지 다 맞은 사람이고 예 빨리 좀 오세요 예예 예
 네 열리 겁니다. 네네 저기 간 경화 환자인데요. 지금 피를 좀 토하고 그래서. 네 주소 알려주세요. 고급차 필요하세요? 네네네 제가 어떻게 할 수가 없어서 현대 프라임 아파트. 번지수 몰라요? 현대 프라임 아파트 몇 동 몇 호예요? 네 확진된 적 있으세요? 가족분들 중에? 없어요. 예 알겠습니다. 지금 빨리 나와 볼게요. 현대 프라임 아파트 네네네 감사합니다.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 119입니다. 말씀하세요. 예 수고하십니다. 저도 경찰 때 경찰관입니다. 아 예 경찰 예예. 아 예 여기는 그 2호선이고요. 2호선 그 5번 6번 출구 쪽에. 예예. 그쪽으로 지금 저기 1구 좀 보내주셨으면 해서요. 아 지금 젊은 애인데. 예 6번 출구 쪽이고 예. 예 5번에서 6번 출구 쪽이고요. 어 그 그 젊은 애인데 한 20대 초반 같은데. 예예예. 술 먹었는지 지금 정신이 없더라고요. 아 남자분이고요. 지금 현장에 계신 거죠? 다른 분들? 알겠습니다. 일단 빨리 나가볼게요.
 네, 1호입니다. 아, 도림교인데요. 무슨 교예요? 도림교예요. 여기 앉아있어. 언니. 도림교예요. 도림교에 무슨 일이세요? 아, 도림교에 계단에서 굴러가지고요. 계단에서 넘어졌다고요? 네, 계단에서 굴러서 좀 피가 나서. 누가요? 남자 여자예요? 여자요. 네. 선생님 의식은 있어요? 네네네네. 예 어디서 피나요? 아 지금 이 머리 쪽에서 피가 나는 거 같은데. 예예예. 선생님 의식이 있다는 거죠? 네네네. 네. 도림 쪽에 선생님 그 주소 같은 건 혹시 아세요? 서울시 영등포구 도영로? 도영로? 네. 예 거기로 갈게요. 네. 어디 뭐 앉아있어
 네 여기 지금 위치가요. 중랑교 쪽으로 이제 동북완선 나가는 쪽이거든요. 동북완선 나가는 쪽이요? 네 동북완선 나가서 저기 의정부 방향으로 나가는 방향이고요. 교통사고가 나가지고 사람이 지금 누워있어요. 네? 사람이 누워있다고요? 아니 교통사고가 났다고요. 차가 자전거를 쳐가지고요. 아 차 자전거를요? 네, 빨리 오셔야 될 것 같은데요. 여기 동부 간선 상에 말씀하시는 거세요? 그니까 어 방향이 중랑역에서 동부 간선 타는 방향에서 이제 의정부 가는 방향으로 빠지는 IC에 있거든요. 위치가. 아 지금 빠지기 직전이요? 중랑교육으로? 네, 딱 그 직구예요. 네, 거기랑 차랑 어떤 차랑 자전거랑 하고 있어서 지금 1명 다쳤어요? 차랑 예, 많이 다쳤어요. 지금 누워있어요. 막. 아 뭐 의식은 있는 거 같아요? 예 의식은 있으세요. 아 예 알겠습니다. 나와볼게요. 지금 지나가신 거 같아요? 네. 예.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네, 11시가 오세요. 네네, 저희 그 아버님이 많이 좀 안 좋으신데요. 아버님 어디가 어떻게 편찮으세요? 어, 지금 말을 못 하세요. 말씀을 못 하세요? 예, 예. 의식이랑 호흡은 있어요? 예, 의식은. 숨을 쉬지 마세요. 숨을 쉬지 마세요. 숨을 쉬지 마세요. 예, 예, 예. 근데 지금 많이 좀 많이 안 좋으세요. 그래서 어떻게 되세요? 아 주세요. 여기 사근동. 네. 네네. 몇 층 몇 호예요? 네. 네. 대원들 나가면서 전화드릴 수 있고요. 아버님 최근에 뭐 코로나 관련해서 의심 증상이나 뭐 이런 거 있을까요? 아니 아니요. 그런 거는 없으시고요. 당뇨가 좀 심하시거든요. 당뇨 좀 있으세요? 예 예. 근데 어제 술 좀 드셨어요. 어제 술도 좀 드셨고? 예 예. 근데 어 일단 오시는데 소리는 엄마가 그 뾰우 뾰우 하는 거는 좀 자제를 해달라고 하시네요. 네 알겠습니다. 대형들 나가면 전화드리시니까 안내 부탁드려요. 예 좀 빨리 좀 부탁할게요.
 네. 119입니다. 안녕하세요. 그 여기 집인데요. 어 그 저희 옆에 1명이 있는데 그 갑자기 그 입영이 들리면서 엄청 어지러워서 막 그 다 통하고 근데 그 의사소통을 하시는데 걷지를 못하겠다고 하는데 이런 증세도 있나요? 아 예 그. 몇 가지 네 몇 가지 좀 여쭤볼게요. 지금 환자분이 남자분이에요? 여자분이요? 남성이에요. 아 남자분이시고 어지럽고 귀에서 이명이 들리신다고 그러신 거예요? 예 귀에서 이명이 들리고 어지럽고. 아 예 선생님 그 정확한 건 검사해봐야 되는데 보통 이석증일 때 그런 경우들이 있거든요. 이석증이요? 예 예 이석증이요. 이석증이 뭘까요? 그 귀에 그 균형 잡아주는 돌 같은 게 있는데 그게 좀 네. 빠졌을 때 그런 증상이 있다고 그래요. 근데 이건. 아 그래요? 네. 검사를 정확히 아는 거고 전화상으로는 없어요. 네. 그래서 선생님 지금 필요하신 게 뭐 구급차가 필요하신 거예요? 아니면 의료 상담이 필요하신 거예요? 아 지금 걷지 못하겠다. 병원 가봐야 될 것 같은데. 예예. 왜 움직이지 못하겠다고요? 한 걸음도. 아 예. 그 응급실 가보시려고 하신 거면 그니까 거동 그 뭐야 응급실 가보시는데 거동이 안 되시는 거면 저희가 구급차 보호해서 도와드릴 수 있는데 좀 어떻게 해드릴까요? 선생님. 그럼 구급차 필요하지? 못 들리겠지? 한 거 이제. 아 못 나와있어요. 아 못 나와있겠다 오네요. 아 그러니까 구급차 필요하신 거예요? 예 예 예 예. 아 주소 좀 알려주세요. 여기 국회대 아 영등포 국회대로. 국회대로. 네. 아크로타워스키어 나오죠? 예. 몇 동 몇 호예요? 그 환자분 최근에 발열이나 코로나 관련 사항이 있으니 여쭤봐 주실래요? 아 코로나요? 한 11월에 한번 가늠 됐었죠? 11월에 그 확진됐었다는 거예요? 네, 자료 완치됐어요. 아 11월에 확진됐었고 완치되신 거란 거죠? 그 신고하신 분은 관계가 어떻게 되세요? 아 형제예요. 아 예 알겠습니다. 그쪽으로 구급차 가볼게요. 선생님 그 도착하면 문 좀 더 열어주세요. 네, 고맙습니다.
 네, 1 2 5 더. 아 예, 지금 저희 아이가 지금 배가 너무 아프다고 지금 그러거든요. 네, 보통요. 아 여자아이, 남자아이에요? 아 그 27살 남자아이 남자예요. 남자. 네, 남자 그 보통요. 보통이고 그 최근에 그 코로나 관련해갖고 그 기침하고 열 그런 건 없죠? 아 전혀 그 그런 건 아니고 예. 주소 불러주세요. 노년동 마블하우스 예 마블하우스예요. 아 노년동 그 번지서는 모르세요? 마블하우스. 예 마블하우스요. 몇 호예요? 아니 지금 여기 주사장 문이 다쳐있어가지고 전화하시면 바로 내려갈게요. 아니 마블 하수 그래도 몇 호 몇 호예요? 알겠습니다. 가볼게요. 가면 전화하면 전화 받으세요. 예 얼마 정도 걸려요? 참 잠깐만요. 1.5길 하니까 뭐 10분 내로 금방 가요. 예. 네 네 알겠습니다. 네 네.
 네, 119입니다. 아 예, 그 저희 어머님이 토요일날 대장환 수술 후에 토요일날 퇴원하셨는데요. 지금 일주일째 옷 드시고 어제는 그냥 뭐 계속 투여해서. 네, 아 좋은 어떻게 해야 되나 해서. 네, 구급차 보내드릴게요. 응급실로 가보시겠어요? 네, 그래서 저희 양 집에 보내서 퇴원했거든요. 예 주소나 위치 말씀해주세요. 네 관악구 봉촌동. 예. 어머니 나이대가 어떻게 되세요? 78세요. 70대 어머니요. 네. 발열이나 지침 코로나 증상은 있으세요? 아니요. 없어요. 지금 열 됐거든요. 예. 고급자. 예. 고급자 출동하겠습니다. 네. 예.
 아 네 여기 그 금호동 삼가에 옛날 중앙고원병원 쪽인데요. 여기 번지가 어떻게 돼요? 금호동 삼가? 금호동 삼가. 아니요. 금호동. 네 그 카페거든요 카페 건너편에서 네 할아버지가 넘어지셨는데 피를 계속 흘리셔가지고 어 여기에 지금 금호동 3가에 안 나오거든요? 아 그럼 제가 빌라 주소로 네 빌라 이름이 뭐예요? 이도 빌라요 이도요? 이도요 이 이도? 이도 빌라? 네 네 할아버지가 쓰러져서 지금 뭐 피나요? 네 피가 계속 나가지고 봐주셔야 될 것 같아요. 네. 의식은 있어요? 없어요? 네 네 의식은 있으세요. 의식 있어요? 네 네. 아 예 알겠습니다. 혹시 술 먹은 거 같아요? 전 아버지? 아니 아니요. 그냥 여기 오르막길이어서 미끄러지셔가지고 넘어지신 것 같아요. 아 예 알겠습니다. 나와볼게요. 네 네. 네. 네.
 일일이 오사항이십니다. 말씀하세요. 네 저 엄마가 지금 숨을 쉬기가 힘들어 하시거든요. 의식은 있으세요? 의식 없는데. 의식 없어요? 주소가 어떻게 되죠? 어 자하문러 40길. 자하문러 40길. 현대빌라. 현대빌라. 네 차 보냈고요 어머니 흔들거나 이러면 반응은 있어요? 예예예 반응은 해요? 아 그냥 숨쉬기 너무 고통스러워했어요 전화 끊지 말아보세요 잠시만요 간호사 연결할게요
 수강사입니다. 네 여보세요? 네. 네 사람이 네 사람이 다쳤는데요. 어떻게 누가 남자 여자예요? 남자 분인데. 어떻게 다친 거예요? 그 사다리에서 떨어져가지고. 아 네. 예. 어 저기 지금 의식은 있나요? 의식은 있는데 지금 걷지로 걷지 통증이 너무 심하고. 예 어디가 잘 알겠습니다. 주소 어떻게 돼요? 성파구 풍요합동. 예. 네 알겠습니다 지금 구급차 보냈구요 지금 어디가 제일 아프시다고 하세요 지금? 다리가 제일 아픈거 같아요 다리가 알겠습니다 가보겠습니다
 예, 이름입니다. 아 네, 애 그 분출이 된 애기가 30살 도 이상 30살 도 열이어가지고요. 혹시 구급차 불러서 병원에 갈 수 있을까 싶어서요. 주소가 어떻게 되세요? 예, 예, 예. 네, 해버라인 2단지. . 알겠어요. 고객님 쪽으로 가볼게요. 네.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 통화 돼. 네. 일요 겁니다. 아, 여보세요? 일요 겁니다. 아, 경찰관인데요? 예. 어, 저 일반인에게 저 제학로 제학로 앞서 건물에. 네. 아마 앞치라고 좀 불러보니까 일부 좀 부탁 좀 드리죠? 넘어져서 약간 이마 쪽이 약간 피는다 보이네요? 네. 이마 쪽 피 난다고요? 약간 좀 잡친 게 보여요. 그래서 좀 치료 좀 요한답니다. 남자 여자요? 남자. 위치가 어떻게 된다고요?

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 119입니다. 네 저희 럭스 라인 마곡지구. 잠시만요. 마곡지구 어디요? 선생님? 럭스 라인. 럭스 라인 검색 좀 해볼게요. 본직수. 마곡소로. 마곡 럭스. 럭스 라인 몇 동 몇 동이요? 선생님? 네 몇 호요? 무슨 일이세요? 호흡이 좀 안 돼가지고 누가요? 여자친구요 여자친구 지금 호흡이 곤란해요? 네 말씀은 하고 사람 안하고 의식은 괜찮죠? 네 의식은 괜찮은데 호흡 좀 많이 먹었거든요 근데 갑자기 호흡이 좀 안 좋아서 네 지금 차는 보냈구요 따로 코로나 때문에 열이거나 관련된 상황이 코로나 때문에 열이거나 뭐 관련된 사항 없죠? 격리자 있거나 확진자 가족 중에 있거나? 그런 거 아니에요. 최근에 3차 맞았어요. 아 차 보냈어요? 좀 기다리세요.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 예, 이주구입니다. 네, 안녕하세요. 예, 예. 아이가 지금 좀 열나가 부딪부딪이 막 떨고 있어가지고. 어디 고열 증세가 보여서요? 고급차 필요하신 거예요? 고급차 예, 지금 좀 가봐야 될 거 같은데. 주소가 어떻게 되는데요? 예전에 경련을 잃은 적이 있거든요. 아 경련한 적이 있다고요? 예, 예전에 경련한 적이 있거든. 그니까 일단 주소를 좀 불러주시라고요. 그니까. 여기 아 어디 영등포구 도림 도림 도림동이에요? 네. 도림동 몇 층이에요? 쌍용 플래티넘 쌍용 플래티넘 식 이게 몇 살이나 됐어요? 지금? 지금 32개월 3살이에요. 32개월 알겠습니다. 그 부처 보내줄게요.
 네. 네. 네. 1 1 9에요. 네. 네. 지금 뭐 저 접속 1 들어갔는데 뭐 젊은 사람 때문에 뭐 싸웠다고 이게 내용이 뭐예요? 아 그거 경찰이 와서 잡아갔어요. 잡아갔어요? 예. 동료 파출소인가 와서 잡아갔어요. 네. 지금 그럼 이게 뭐예요? 고급차가 필요한 상황이에요? 아냐 아냐 아냐 그게 아니라 어떤 노인네 지갑을 어떤 사람이 채 갖고 가다가 거기 사람이 많으니까 막 잡았어. 그래갖고 신고를 했으니 이제 왔지 경찰이. 경찰이 수갑 채 갖고 갔어요. 아 지금 경찰 갔다는 거예요? 예예. 아 그럼 거기 현장이 아무나 없는 거예요 그럼? 그쵸. 동료 발출소에서 와서 잡아 갔어요. 아 예 알겠습니다. 예 예 고맙습니다.
 네 119입니다. 아 여기 지금 송타구 가락시장 한국청과 입구 쪽이거든요. 교통사고. 가락시장 옛날 그 고시장 한국청과 초입이에요. 그니까 여기 뭐 그 건물 바로 새 건물 바로 뒤에 한국청과 있는 데인데요. 교통사고가 나서. 뭐랑 부딪쳤어요? 택시랑 부딪쳤거든요. 아 뒤에 숨겨서 1번 있는데 다리가 아프다 그래서 일단은 그냥 지금 앉아있으라 그랬거든요. 물을 너무 아프다 그래가지고. 네 네. 지금 의식은 있으시죠? 환자분. 잠시만요. 그 보이는 가게 같은 거 있으면 1번 말씀해주실래요? 가게는 없고 여기가 아 잠깐만요. 여기 그 가락시장에 농협 건물 바로 뒤에요. 가락시장 농협 건물 뒤에요? 잠시만요. 예 이게 원래 그 아 뭐라고 해야 되지? 동문회전은 아 이거 잠깐만요. 예 잠시만요. 아 그 그 대한소방공주회관 그쪽이에요? 네 그 가까운데요. 그 농수산식품공사 바로 뒤라고 해야 되나요? 여기 옛날에 한국청과 건물이라서 그 쪽이라서. 아 선생님 일단 그럼 저희가 농협 쪽으로 그 고급자 보낼 테니까 그 보이면 그쪽으로 안내 좀 해주실 수 있나요? 네 여기서 저기 있겠습니다. 아 예 농협 쪽으로 보낼게요. 그러면. 네네 여기 농협 하나죠? 여기 혹시 농협 여러 개요? 제가 그걸 몰라가지고. 아 농협이 좀 여러 개 있긴 한데 그 금호 아파트 쪽이에요? 혹시 위치가? 우성 아파트? 아 건너편은 근호 아파트예요. 근호 아파트 건너편이죠. 네. 아 예 알겠습니다. 그럼 근호 아파트 건너편 노역 쪽으로 보낼게요. 네.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네 여보세요. 주임님 경기 남부 상황실입니다. 아 예예. 네 6013이랑 내용 들어갔어요? 아 예예 통화하겠습니다. 네. 여보세요. 아 네 여보세요. 예예. 예예. 아이가 어젯밤에 짓거려서 넘어져가지고 발목이 아프라고 그랬는데 오늘은 아예 거동을 못해서요. 아 그래요? 그 네이처일 네 맞습니다. 아 예예. 그 같이 있는거죠? 지금 환자분하고? 네네네. 아 예 알겠습니다. 그쪽은 그 최근에 코로나 관련돼서 연락은 뭐 귀신가리 증상 없는거죠? 네 없고 다 됐으면 좋겠습니다. 아 예예 알겠습니다. 그쪽으로 차량 보낼게요. 그 차량이 남부터미널역 그쪽 근처 우면동 쪽에서 출발할거거든요. 네네. 예예 참고하시기 바랍니다. 네 감사합니다
 119입니다. 아 네 여기 농연동 선생님 강남구 농연동 네네네. 네. 무슨 일이세요? 제가 살피가 너무 심하고 시곤 땀이 나고 배가 비틀리고 그런 상황이거든요. 지금 병원 가시려고 그러는 거죠? 예, 예. 네, 선생님 혹시 코로나 관련 증세 같은 거 있으세요? 고열 기침 같은 거 같은 거. 그런 거 없으시고요? 예, 3차 부스터까지 말았어요. 네, 알겠어요. 거기로 갈게요. 네, 감사합니다.
 예, 여보세요? 예, 여기 연신내인데요. 예, 예, 예. 버스에서 바람에 좀 넘어주셔갖고. 버스요? 선생님? 예, 예. 연신내역 그 버스 정류장이에요? 예, 예. 그 사항 방향은 어디 쪽 방향 쪽이에요? 여기 세경 세경고 방향. 세경고 거기도 방향고? 세명고 방향? 예, 잠시만요. 버스 번호는 어떻게 돼요? 몇 번 버스예요? 여성분이세요? 알겠습니다.
 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 응급실을 가려고 하는데요. 가능하나요? 병원 안에 계시면 안 되고요. 네, 네. 뭐 밖에 나오셔가지고 같이 번호하셔야 될 것 같은데요. 지금 같이 계신 건가요? 네, 네. 음 그러면 그 저기 발산역 앞으로 나오세요? 그쪽으로 보내드릴게요. 어 그러면 저희가 어디 나가면 되죠? 이하의별 그냥 앞으로 응급실 앞에 서 있을까요? 아니 발산역 앞으로 나오세요. 병원 안으로는 어차피 구급차가 못 가요. 거기 저희 가려라도 가까운 병원이라 거기로 가고 막 이러니까. 아 그러면 혹시 제가 그 발산역 앞으로 나가면은 응급실 가서도 다른 병원 가서도 실시간을 대기해야 되나요? 아니면 진료가 바로 가능하나요? 어 좀 병원 상황에 따라 다른 거여가지고 저희도 알기는 좀 어려운데요. 일단 뭐 이대 서울 병원 말고는 뭐 이대 뭐 동인병원이나 이대 목도병원은 뭐 딱히 환자 많다고 저희한테 들어온 건 없거든요. 그래서 자세한 건 국어 병원이랑 얘기해 보세요. 근데 또 갔는데 사람 많아가지고 병원에서 기다리라고 하는 경우도 있어가지고. 아 그럼 다른 데 가도 3시간은 안 기다리죠? 그때그때 상황에 따라 달라서 뭐라고 하면 딱히 듣기 어려운 말고요. 바로 되는 경우도 있고 오래 걸리는 경우도 있고 막 그래가지고 그때그때 달라. 아 그래요? 혹시 그럼 여 부처는 어디 병원이 어디 응급실 가능할까요? 일단 단순 부총 같은 경우는 뭐 도민병원도 응급실 있고요. 아 도민병원도 응급실 있어요? 여 근처에? 저기 감시 부총 입구 교체로요. 아 네. 아 예 그러면 저희 저희가 여보세요? 네. 네 제가 지금 이화여대 병원인데 그 발산역 이화여대 병원이 발산역 8번 출구 앞에 있잖아요. 제가 8번 출구으로 갈게요. 네 네 뭐 열쇠가거나 경치관 비증상 코로나 격리 중이신 거 없으시죠? 아 코로나 증상은 아예 없어요. 지금 막 코하고 벌어지지 못하고. 격리 상태 아니시죠? 격리 상태. 격리 상태 아니에요. 네 전화 오면 잘 받아주세요. 고객님. 네 알겠습니다. 네.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네, 여기입니다. 아, 여보세요? 네, 말씀하세요. 아, 예, 저기 자다가 말고 너무 심하게 어지럽고 네. 좀 매숙거리고 그 식은 땀 나는 거 같아가지고요. 어지럽고? 네. 석이 매숙겹고 식은 땀이 난다고요? 그 그 이석증이 좀 심한 상태인 것 같기는 한데 도저히 날 셀 때까지 기다렸다가 직접 운전해서 어디 이석증이 있으세요? 원래? 아니요. 없는데 예전에 잠깐 있었던 적이 있기는 한데요. 금방 치료됐었거든요. 네. 주소가 어떻게 되세요? 어 여기 어 상암동 그 오베리스크 2차 치매하는 주소 보통 나와요. 그 마포 질문 네. 정확한 주소가 저희 이사 온 지 얼마 안 돼서 잠깐 서울 마포구 월드컵 복로 예 상암 오벨리스크 네 네. 네. 네. 네. 네. 네. 네. 알겠습니다. 코로나 증상 같은 건 없었죠? 평소에? 네. 평소에 저는 그런 거 없었거든요. 네. 알겠습니다. 조금만 기다리세요. 네. 감사합니다.
 네. 늦습니다. 네. 저 노는 초등학교 건너편에 뒤에 뒤에 하우스 예. 논현동 네. 유닉스라고 하는 사람인데 아무 이상도 없는데 밤중에 새벽에 지금 막 먹고 내려서 물이 막 나오고 그래서 일어나서 화장실에 가서 봤더니 그냥 피가 막 쏟아주는 거예요. 누가요? 피가. 아 본인이요? 네 본인이 피가 막 쏟아져서 저건이다가 시질이다가 막. 입원에서 피가 나온다고요? 네 먹고 내려서. 목공원에서 그냥 피를 통한다는 거예요? 그렇죠. 그런데 이제 뭐 줬거든? 네. 그러면 병원을 가야 되나 지금. 네 병원 가셔야죠. 논현동. 논현 초등학교 정문 바로 군내 편에 대체 하우실하고 옆에 카 센터고 바로 옆집이에요. 그러니까 주소는 맞죠. 그렇게. 아. 아 피토 하시 본인이 환자시고 피토 하시는 거고. 예. 예. 죽으면 피가 뭐 됐어요. 뭐 코로나 증상 같은 건 없으시죠? 예. 예. 없어요 그런 거 없어요. 예. 구급차 보내드릴게요. 예. 예.
 119 다 불러줘요. 예 119 다 무슨 일이세요? 저도 전화. 여보세요? 예 119입니다. 무슨 일이세요? 아 예 여기 저기 저희 아버지가 지금 의식이 없으신 아 의식은 있으신데 저거 말씀도 못하시고 지금. 구급차 보내드릴까요? 응급실 가보시겠어요? 예. 계신 곳 주소나 위치 말씀해주세요. 여기가 성동구 응봉동. 예? 이런 거 다 주고 이런 거 다 주고. 이런 거에 지금 말씀 드리겠습니다. 그렇습니까? 예 다시 1번 말씀해 주세요. 주소. 응봉동. 예. 몇 층에 계세요? 지금 선생님 지금 전화하시는 아버님이 지금 안 좋으신거에요? 제가 아닌거에요 우리 아버님 아버님 나이대가 어떻게 되세요? 어 80 80대 예 예 구급차 출동하겠습니다 기침하고 코로나 증상은 없으신거죠? 예예 알겠습니다 출동하겠습니다 예 예
 네. 1.9입니다. 네. 안녕하세요. 여기 서대문구 세란병원인데요. 세란병원이요? 네. 지금 여기 뭐 사고가 나서 병원에 왔는데 진료가 안 되고 지금 근처에 그 그래서 사설 응급 그 이송해주시는 그쪽으로 전화를 했는데 전화가 안 돼가지고 다시 이쪽 119로 연락을 드린 거거든요. 그 사남병원에서 입원해 계시는 건 아니죠? 입원은 아니고요. 응급센터로 왔는데 여기에서 받으실 수 있는. 남자분이. 환자분이 남자분이에요? 여자분이에요? 남잔데요. 네 증상이 뭐죠? 지금 다리 경강이가 많이 눌려가지고 후려졌는지 뭐 어쨌는지 몰라요. 아 그래요? 그럼 우리가 세람병 앞으로 가면 되는 거죠? 네. 세람병 앞으로 좀 와주시겠어요? 네 차 보낼게요. 연락하나 없으시죠? 네? 연락하나 코로나 증상은 없으시죠? 네 그런 건 없습니다. 네 알겠습니다. 우리 수고한 분들 효자동 상고리 쪽에서 차 나와요. 네 그러면은 저한테 연락이 오나요? 네 우리 축구하는 대원들이 선생님 전화번호로 다시 1번 전화 1번 드릴 거예요. 확인 차원에서. 네 알겠습니다. 네.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 유료구 상하실입니다. 아 여기 실례지만. 무슨 일이시던데요? 선생님. 아니 근데 지금 제 친구가 지금. 제가 너무 아파해가지고 근데 왜 코로나가 점점 한지 지금 며칠 됐지? 며칠 됐어. 며칠 됐어. 1차 맞은지 27일이니까. 얼마 안 됐어? 네. 3일? 4일? 1차 맞은지 한 3 4일밖에 안 됐어요. 네, 네, 네. 근데 약간 술을 조금 밖에 안 마시는데 갑자기 배가 너무 아프다 그래가지고. 아 그러세요? 너무 전세기 힘들었는데. 네, 네, 네. 아 구급차 보내줄 건데 선생님 친구분이 남자 여자예요? 여자입니다. 여자 나이대는요? 92년생이요. 아 92년생이요? 그리고 지금 제가 몇 가지만 더 물어볼게요. 그 지금 무식이나 이런 건 다 괜찮으세요? 사람 알아보시고 호흡도 규칙적으로 잘 하시죠? 네, 그럼 보겠습니다. 네, 알겠습니다. 그 코로나 관련해서 뭐 확인받거나 기침 가려고요. 네, 전혀 없어요. 네, 알겠습니다. 구부차 가면 또 전화드릴 수 있으니까 전화 잘 받으시고요. 배신 3일 전에 맞고 배가 아프신 거 같아요? 네, 알겠습니다. 전화 잘 받으세요. 구부차 가고 있어요. 네. 네

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 119 계좌 여보세요. 예 여보세요? 예 말씀하세요. 예 저기. 예. 좀 제가 호흡을 운전하다가 호흡이 지금 가빠가지고 전화드렸는데. 호흡이요? 본인 운전하시다가? 예예. 거기 위치 좀 알려주세요. 고차 필요한 상황이 맞는 거죠? 예예. 화면 세우신 거죠? 예. 거기 위치 좀 알려주세요. 예. 여기가 어딘가 모르겠어. 앞에 보이는 거 아무거나 있으면 간판 같은 거 아무거나 얘기를 해주세요. 상정 같은 거. 포천 대기 쟁고기. 포천 대기. 아. 쟁고기. 4대 족발 있어요? 4대 족발? 예? 4대 족발 뭐 뽀빠이 족발 이런 데 있는 거죠? 예. 뽀빠이 족발. 예. 예. 위치. 위치 확인됐고요. 거기. 친구가 차 출동해서 가니까 상태를 물어볼게요. 원래 무슨 명이 있었어요? 아니 저기 예 뭐 없어요? 건강했는데 아 당뇨 당뇨 환자예요? 예 차종이 뭐예요? 차종 차종이 택시인데 택시 번호 색깔이랑 번호 예 주황색 예 주황색 예 번호 알려주세요. 차 번호 잠깐만요. 예 운전할 사람 없는 거죠? 혼자 계신 거죠? 예예. 예. 전차번호 뭐 1234 이렇게 예. 자세하게. 아예 내가 오늘 운전 처음 나와가지고. 차 번호는 아. 그러면 정차시켜놓으시고요. 여보세요? 깜빡이 켜고. 예예. 이상능 켜고. 예. 끊지 마시고 차 출동해서 가는 중에 의료진 연결할 거니까 저희 상세 말씀해주세요. 연결합니다. 예. 예.
 고맙습니다. 네 여기 시중 밑에 나오서 땀 난 뒤요. 네 몇 동 몇 조예요? 네. 맞죠? 네. 네 무슨 일이에요? 아 저 지금 심장은 많이 불편해요. 아 심장이 아프시려고요? 네 많이 불편해요. 네. 심장 통증이 있어요. 선생님 구급차 보내드릴까요? 네. 네 혹시 지금 열이나 기침 자가격리 확진자 코로나가 안된 상황이 아닙니다. 해당 없는 거죠? 심장만 아프신 거 안 보신 거예요? 네. 네 차 응급차 출발시켰고요. 네. 네 혼자 계세요. 문을 열어줄 수 있어요? 네. 네 전화 잘 받으세요. 네. 네.
 네 일로 옵니다. 예 예 배가 너무 아파서 병원에 좀 되더라도 해주세요. 주소 알려주세요. 여기 삼보 오피스텔입니다. 삼보 오피스텔이요? 몇? 삼보 오 주소 번지수 아세요? 잠깐만요. 자동차 시장 1길. 네 어딘지 찾았고요. 그 3호 오피스텔 몇 층 몇 호 사세요? 코로나 확진 내신 수 있어요? 없습니다. 네 좀 나와볼게요. 네.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 안녕하십니까? 남가자 아파트 쪽인데요. 서대문구 남가자 아파트 쪽인데요. 네. 네. 여기 1분 민원이 아프셔 가지고 네. 남자분이실까요? 남성분이시고 네. 어 어디가 아파 보이는지 대략 나오나요? 파우더가 서로 이제 뭐 맞아 가지고 아프다고 하거든요. 알겠습니다. 코로나 관련 확인되는 게 있을까요? 저희가 열 체크는 했는데 잠시만요. 예 체크는 문제없었습니다. 알겠습니다. 추동해 보겠습니다. 네 감사합니다.
 네, 1, 2, 9입니다. 예, 그 사람이 계단에서 지금 넘어져서 지금 넘어지는데 1, 2, 9, 2 좀 보내야 될 것 같으세요. 아 예, 계신 곳 주소나 위치 말씀해 주세요. 네, 관악구 신림동. 예. 잠시만. 그 계단에서 지금 넘어져 있거든요. 예 남자분 여자분이요? 남자요. 아 예. 내려갈 때 넘어져 계시니까 좀 막 궁금해서 내려가주세요. 지금. 예 예 빨리 좀 와주세요. 잘 출동하겠습니다. 네네. 예 지금 너무 잘.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 민재고입니다. 네 안녕하세요. 여기 노원경찰서 서울 노원경찰서 강력팀 상단대요. 네 저희 노원 태령치료센터에서 어제 무단이탈 확진자가 있어요. 중국 동포인데 그분을 저희가 구로에서 지금 잡았거든요. 그래가지고 이쪽으로 이제 송파치료센터를 옮기려고 하는데 도움을 좀 받아야 될 것 같아가지고요. 지금 어디에 계신 거예요? 그분이 그러면? 지금 구로동로 노상에 있어요. 한쪽에 좀 예 한쪽에 격리는 시켜놨어요. 거기 주소 좀 불러주세요. 정확한 주소. 구로동로. 네. 그 앞에 그 앞에 있어요? 네 앞에 노상이요. 예. 그러면 이분 송파 생활지휴센터로 이소하면 되는 거예요? 네 맞습니다. 그쪽이랑 다 통화되신 거죠? 네 거기 통화해놨어요. 혹시 이분 성함이랑 그 송파 생체 번호 좀 알려주시겠어요? 통화하신 번호? 아 그 확진자분 성함이요. 남자분이시죠? 네 중국 사람이에요. 중국 분이시고 송파 생취 혹시 전화하신 번호 좀 불러주시겠어요? 잠시만요. 아니 아니 아니 아니 하고 있어요. 네. 이쪽으로 보낼게요. 네. 다음 영상에서 만나요.
 네. 신청합니다. 여보세요. 네. 119예요. 여보세요. 119라고요. 여보세요. 말씀하세요. 안 안 돼. 네. 예. 무슨 일이세요? 아퍼요. 누가 아프세요? 내가요. 어디 아프세요? 아이고 저 저 부치게 조그만 거 하나 먹었으니. 네. 막 입이 마르고 지금 그래요. 어디가 입만 마르세요? 아니 막 목이 마르고. 네. 숨이 마르고 그래요. 급해요. 네 차 나가 볼게요. 전화 차에 받으세요. 지금 오실 거죠? 네 지금 출발할게요. 기다리라고요? 열나거나 막 그래요? 예? 열나는 거 있냐고요? 뭐 하라고요? 열나냐고요. 열 안 나요. 차 나가니까 전화 잘 받으세요. 효가 말른다고. 예 차 나가요. 예.
 네, 열려 봅니다. 야, 야 거품 물어? 네? 여기 여기. 예. 근데. 네? 아차살로. 네? 예, 보이는 건 그건데. 네. 있으면 술 많이 먹고 지금 거품 물어가지고. 누가 해요? 남자분이요? 남성이에요. 남성. 남성이 쓰러졌어요? 예, 술 먹었는데 지금 거품 물고 있어가지고. 아는 사람이에요? 아는 사람 오늘 처음 만났게 했는데 아차 진료 소리 들지 마시고요 제가 일단 고급차 먼저 보낼게요 자양동 예예예 예 잠시만요 고급차 먼저 갈게요 전화 끊지 마세요 전화 끊지 마세요 집정하시고요 주차는 출발했어요 의료진 연결할게요
 네, 네, 네. 아 네, 저희 엄마가요. 지금 85세 되신 분인데 백신 맞은 지는 25일 3차 백신 맞은 지는 25일 되셨거든요. 근데 지금 숨 쉬는 게 어제 저녁에 숨이 조금씩 못 쉬겠고 가슴 있는 데가 통증이 좀 있고. 근데 지금은 조금 심해져서요. 정신까지 혼미해지시고 있거든요. 아 그 송은 괜찮 송도 아예 힘들게 치고 계세요? 네네네네네. 주소부터 알려주세요. 고급차 나가볼게요. 아 영등포고 양평동 신종 아파트. 열이나 이런 건 1도 없으세요. 잠시만 거기가 삼한 아파트 건너편에 있는 거 맞아요? 네네네네. 아 고급차는 출발했고 갈 거고 다른 가족분들 중에 뭐. 아 그쪽으로 고급차 가고 있고요. 뭐 가족들도 통화하셔서 발열이나 고열 뭐 기침 코로나 관련. 아니요. 전혀 그런 거 없어요. 네, 네. 아 그 혹시 학생자로 만나셨거나 자가 겪는 하신 분이 안 계시고요? 아 네, 네. 없어요. 지금 뭐 대화는 가능하신 거예요? 어머님? 대화도 잘 못 해요. 아 저희 대원들이 바로 전화. 정신이 혼내지셔 갖고. 아 전화를 바로 들으면서 갈 거니까 뭐 전화 좀 부탁드리려고. 네, 네, 네, 네, 네.
 예 일주국입니다. 예 수고하십니다. 네 어머님이 예 어저께인가 그저께서부터 우리 굴을 먹었걸랑요? 예 근데 또 첫사람 몇 번 몇 번 이렇게 하시더만 오늘 또 굴을 좀 드셨어요. 근데 한 아 연세가 연세가 한 90이 월쯤 다 된 분인데 지금 기사를 너무 많이 해갖고. 아 90세 되셨는데 고급차 필요하신 거예요? 주소를 좀 불러주세요. 주소 주소. 예 그냥 왜냐면. 어머니 코로나 진단받고 이런 건 없으신 거죠? 아 그 코로나 주사는 3차까지 다 맞으셨어요. 관련이 없다는 것이죠? 예예 그것도 그런 건 아니에요. 불을 먹은 후 계속된 설사로 증세를 보이신다 이거죠? 예예예 철사를 한 10번 정도 하셔가지고. 차가 지금 동작부 쪽에서 나가야 될 것 같아요. 차가 가까운데 없어가지고요. 보내 보내드렸고 가면서 대원들이 전화드릴 수 있어요. 아 예예. 아 그러면 전화를요. 잠깐만요. . . . . .
 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 먹었더니 어지럽다고 그니까 좀 안 좋다고 속이 그래서 소파에 잠깐 앉아 있다가 어 이제 구토 증세가 나서 그랬는지 화장실에 가려고 일어났나 봐요. 저는 침대에 있어서 못 봤거든요. 근데 정황상으로 보면 그렇게 된 것 같은데 갑자기 뭐가 퐁 부딪히는 소리가 나서 나와봤더니 화장실 문하고 그 건너지 벽에 부딪혀가지고 그 꿈 소리가 난 거 같고 남편은 바닥에 길게 누워 있었거든요. 예 알겠습니다. 선생님. 한참 구통하고 난 다음에 일으켜 세워서 봤더니 뒷머리가 피가 있어가지고요. 네 알겠습니다. 일단 주소 좀 불러주세요. 서울시 성북구. 네. 네. 잠시만요. 아파트예요? 아파트나 아파트 이름. 아리랑 아리랑로. 1심 권영 휴먼 빌 아파트. 1심 권영 휴먼 빌 네. 네 알겠습니다. 호흡차 출발했고요. 일단 지금 현재 의식은 있으신 거죠? 네. 네. 네. 머리 출혈이 있으시고. 뭐 코로나 증상 같은 거 없으셨고 평소에. 없었고요. 지금 계속 저기 술 때문에 그런지 아니면은 머리를 다쳐서 그런지 모르겠는데 계속 토했다가 지금 막 앉혔거든요. 아 예 알겠어요. 지금 호흡차 금방 도착하니까 조금만 기다리고 계세요. 네. 네. 감사합니다.
 입니다. 무슨 일이세요? 예, 예, 갑자기 어두웠고 계속 소화하거든요. 좀. 누가요? 저기 뒤에서 아마 소리 나고요. 누가요? 누가요? 예, 예, 저기 부인이요. 아내분이요? 위치 좀 알려주세요. 그거 차 보내드릴게요. 예, 대림 아파트. 네. 잠시만요. 대림아파트요. 기름동 맞으세요? 예예예 맞습니다. 성북구인가요 선생님? 예예 검색 좀 해볼게요. 네 혹시 주소를 불러주실 수 있을까요 선생님? 기름동 선생님? 예예 그 이편한 세상인가요? 대림 아파트? 네네네네 아 네 알겠습니다. 몇 통 몇 호세요? 맞으시죠? 선생님? 예 알겠습니다. 그쪽으로 구급차 보내드릴 거고요. 혹시 코로나 관련해서 해당 사항 있으실까요? 아니 없어요. 접속하거나 그런 거 전혀 없으세요? 네 알겠습니다. 선생님 구급대원이 가면서 전화할 거고요. 전화 잘 받아주세요. 이편한 세상 아파트 맞으시죠? 선생님? 네 네 네

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 1 9입니다. 아 혹시 제가 오늘 병원 가서 장염 그 장염이라고 판정을 받았는데요. 어 계속 열이 나고 아까 토까지 해서 탈수 증상도 오는 것 같아요. 어 근데 너무 힘들어서 1 2 9가 와서 일어나지도 못하겠는데 잠깐 집에서 뭐 수액이라도 맞거나 그럴 수 있는 방법은 없나요? 일단은 그 해당에서 판단은 구급대가 하는 거라서 그 병원 이송할지 그거 할지는 그 해당 판단은 구급대가 하거든요. 일단 주소 먼저 불러주세요. 세문 1개 세문 1개 혹시 코로나 관련해서 비친 바래 사상 있다거나 그런 확진자 자격 있는지 이런 내용이 있나요? 어 그 일찍 그건 없고요. 작년 땜에 열흘 나는데 아까 오늘 병원에서도 검사 안 해도 된댔어요. 네 알겠습니다.
 네. 말씀하세요. 아 여기 좀 할머니가 계단을 내려오다가 넘어졌어요. 친합니다. 여 좀 빨리 와주세요. 주세요. 주소요. 어? 주소 알려주세요. 집 주소. 네네. 여기가 어 영동포구 영동포로 72길. 예. 네. 계단 몇 층이에요? 3등전자 옆에 있잖아요. 여기 대신시장. 바로 옆입니다. 빨리 와주세요. 할머니 차 출발을 하고 할머니 숨 쉬어요. 네 숨을 쉬습니다. 얼른 빨리 와주세요. 할머니 주인이에요? 아 주인입니다. 네? 네. 넘어진 할머니가 주인이라고. 집주인이 주인이라고. 네. 신고자분. 네. 그럼 신고자분 세입자고 할머니는 집주인이에요? 근데 그 영등 예예 맞습니다 예 알겠습니다 예

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 일로 갑니다. 예 여기 그 경찰병원 사거리에 예예 오토바이 생각나는 사람 누워있어요. 혹시 차량 부탁친 건 아니고요? 뭔지 확인 안 되세요? 차량 부탁친 거 같은데요? 보니까 제 멀리서 어찌 지나가다 봤는데. 아 사거리. 예 혹시 차 아래 깔려있는 건 아니죠? 아 그런 건 아닌 거 같고 누워서 아니라는 거 같아요. 아 혹시 그 어느 쪽 방향이에요? 혹시 경찰. 사거리 사거리 사거리 딱 중간에 있어요. 아 사거리? 아 알겠어요. 그럼 가볼게요. 예. 다음 영상에서 만나요.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네, 여보세요? 네, 네, 말씀하세요. 네, 여기 서울 수성초등학교 건널목에 있는 데인데요. 수성초등학교요? 네, 네, 네, 번동사월이 좀 길게 맞은편이라는 말씀이세요? 네, 네, 네, 네, 네. 수성삼월이 좀 넘어지셔 가지고 피를 더 많이 흘리세요. 어디서요? 여기 신호선 앞에서요. 아니요. 피가 어디서 나요? 눈 바로 밑에. 아 남자분이세요? 네네 할아버지인데 지금 이거 말씀하세요. 네 선생님. 거기 어디로 가면 돼요? 그 맞은편에 뭐 건물이나 상호가게 같은 거 없어요? 여기 비만 클리닉 있고 문구 펜시점 있고 상호 들어가는 입구예요. 아 상호를 말씀해주세요. 저희는 지도로 보고 있어가지고 저희가 그렇게 말씀하시는지 참기 어려워요. 상호 들어가는 입구요. 아니 가게 같은 거 하나만 말해주세요. 가게요? 명봉 안경 콘택트 예 잠시만요. 찾았어요. 그 앞으로 갈게요.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 여보세요? 네. 아 지금 여기 그 애기가 신생한데요. 전자밭에 지금 이불에 잠깐 말려가지고 지금 숨을 잘 못 쉬고 있거든요? 선생님. 몇 주 몇 주예요? 아
 1 9입니다. 말씀하세요. 네 안녕하세요. 그 저기 구급차 때문에 전화를 드렸는데요. 예예. 그 저희 아버님이 어제 운전하시다가 사고가 나셨는데. 아 예예. 지금 오른 왼쪽 갈비뼈가 좀 부러진 것 같아서 아예 움직이질 못하거든요. 아 그러면은 구급차 번 바로 보내드리면 되는 거죠? 어 네네네. 아 네 주소가 어떻게 되세요? 어 잠시만요. 네네. 여기가 동작구 양영로 양영로 23길 양영로 23길 몇층 몇호예요? 군전 아투메이션. 네. 아버지 뭐 코로나 관련해서 열이나 기침 이런 증가 있었나요? 혹시? 그런 건 없고요. 그런 건 없고요. 알겠습니다. 조금만 기다려 주세요. 바로 출산할게요. 네 감사합니다. 네.
 예, 일곱니다. 아 네, 안녕하세요. 여기 서울 그 강남구 도곡동에 있는 북클라인 양재점인데요. 북클라인 양재점? 네, 네, 잘못 다치신 분이 있어서. 남자분이요? 여자분이요? 여자분이시고요. 아 고급차 앞에서 전화 주신 거죠? 네, 네, 맞습니다. 어 북클라인 양재점 주소가 도곡동 몇 번지예요? 잠시만 기다려 주시겠어요? 예, 북동 수사 클래스 맞아요? 아 네, 맞습니다. 있는 건가요? 적당 양재점으로 전주 나갈 거고요. 잘못 다치신 거 외에 다른 뭐 다른 특이점 혹시 있으신가요? 어 아니요 그런 건 없습니다. 전주 나가볼게요. 전화 받으시면 다시 한번 안내해주세요. 네 감사합니다. 네.
 네, 아 저기 어머니께서 지금 지금 힘을 못 쓰고 너무 답답하시다 그래서. 아 호흡곤란 있어요? 어머니? 예, 원래 심부전 심부전 시술을 받을 수 있게 한 3년 정도 되셨는데. 지금 그 병원으로 가야 할까요? 아버님 아니면 가까운 데로 가야 할지 잘 모르겠고. 아 가까운 응급실로 한번 가보셔야죠. 가까운 응급실로. 아 4일날 예약해서 돼 있는데 지금 어떻게 해야 되나 그래서. 아 그래요? 그럼 우선 의료 상담으로 한번 받아보시겠어요? 그러면 상담 같은 거를? 아니요. 일단 차를 차를 보내주셔야 될 것 같아요. 아 그래요? 그럼 주소를 한번 불러주세요. 여기 목동 중앙북로 10길 예예예. 어머니가 지금 열 같은 건 어땠어요? 지금 열 증상 같은 거? 열이 있거나 그러시진 않고요. 지금 힘든 게 답답하다고 그냥 그러시고. 네. 예. 그 저 지금 저희 가볼 테니까요. 네. 네.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 예, 일로 옵니다. 여보세요? 예, 일로 옵니다. 예, 수고하십니다. 예, 선생님. 여기 좀 와주시기 전에 하나 더 전화드렸거든요. 예, 무슨 일이에요? 아. 6여간으로 온 거 같아요. 선생님 본인이요? 네. 주소 불러주세요. 고청로 33길. 대형주택 요새 가족분 포함해서 코로나지역 다녀오거나 관련 증상 있나요? 아니요 없어요 가볼게요 전화오면 잘 받으세요 사이렌 키지 말고 와주시겠어요? 예 알겠습니다 예 부탁합니다.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 예고입니다. 네 여보세요. 네. 네 안녕하세요. 저기 아빠가 지금 점수하다가 다리가 절여서 움직일 수가 없는데 혹시 네네 가능할까요? 아 보궐서 탐구인다고 하신다고요? 네네 병원에 이동하려고 하는데. 제가 알려주세요. 중계본동. 예. 삼성아파트? 삼성아파트요? 네 삼성이요. 삼성아파트. 예. 네네. 네. 코로나 관련된 건 최근에 없어지고요? 아 네 없어요. 음 차 출발 시켰고요. 제가 위치 좀 할게요. 네. 거기가 중계동. 아 알겠습니다. 일단 갈게요.
 수고하십니다. 네 저기 저기가 저기 엄마가요. 화장실에서 쓰러져가지고 그 머리가 많이 찢어졌어요. 아 의식은 있는 거예요? 지금? 네네. 주소는 어떻게 되죠? 저희가 월급 1동 공중화장실인데요. 5폐산로 3길. 5폐산로 3길에. 잠깐만요 검색중입니다 네 그 앞에 계세요? 네네네 구급차 앞으로 보낼게요 혹시 자가격리나 코로나 관련 사항 없으시죠? 네네 알겠습니다 앞으로 가고 싶습니다 구급차 보낼게요 네
 네, 안녕하십니다. 안녕하세요. 네, 말씀하세요. 네, 엄마랑 다르게 왔는데요. 네. 엄마가 아빠가 엄마가 모서리 밀쳐서 엄마 그 아빠가 엄마가 모서리 밀쳐서 네. 엄마가 내가 못하고 네? 엄마가 뭐한다고요? 엄마 얼굴이 피나여. 아 주소 알려주세요. 오목로 54길. 네? 오목로 54길. 오목로 24길에. 아 54길이요. 54길에. 네. 네. 몇 층 몇 호요? 지금 어머니랑 같이 계시죠? 네. 네. 수박하는 데 가면 문 열어주세요. 네. 아버님도 같이 계세요? 네. 네. 네? 네. 네. 네 알겠어요. 수박하는 데서 빨리 갈 테니까 우지 마시고 문 열어주세요. 네. 빨리 갈게요. 네. 네.
 네 안녕하세요. 아 여기 지금 그 어떤 분이 취해서 쓰여서 계셔가지고 전화드렸는데요. 남자 여자에요. 남성분이십니다. 어디있죠? 여기 주소가 그 서울 서초북 서초대로 77길 가게인가요? 네 손님으로 계신 분이에요? 목소리가 지금 자주 서가지고 잘 어쩌가지고 손님으로 계신 분인가요? 어 모르겠습니다 아 저희가 어떤 가게에요 선생님? 어떤 매장이에요? 네네 가게입니다 어떤 가게에요 선생님? 그.. 구사반 강남역점입니다 아 술집이에요? 네네네 남자분이 지금 쓰러져 있는데 의식이 있는지 확인해도 되나요? 어 약간 정신을 못 차리시고 가셔가지고. 네네. 주치 상태는 맞아요? 네 그런 거 같습니다. 알겠습니다. 저희가 바로 보내드릴게요. 네 감사합니다. 네.
 네, 119입니다. 네, 그 죄송한데 저희 엄마가 몸이 자꾸 떨리고 정신이 지금 막 이 아 아작해지고 완전 몸이 지금 사시다고 떨리는데 엄청 떨리시거든요. 열나요? 열은 안 나는 거 같고 자꾸 정신이 잃을 거 같다고 하시고 머리 아프고 부토예요. 아 부토도 하고 떨리고. 네, 예, 죄송한데요. 그 한글 비성로 네. 46 가기 잠시만요. 네. 46 가기 가기 래 가기 래 네. 3개 5동 잠시만요. 한글 비송으로 46 가기를 3개 5동. 네 한신 아파트예요? 네 한신 아파트 1차요. 1차 예 몇 동 몇 호예요? 네 1차 네. 어머니, 좀 떨리고 구토하신다는 거죠? 정신 잃을 것 같아요. 예, 차 나가보고요. 연락이나 그런 건 아니시다는 거죠? 네네. 숨차거나 그런 것도 아니에요? 아예 그런 건 없어요. 네, 차 나가볼게요. 전화 잘 받으세요. 네. 네.
 네, 안녕합니다. 여보세요? 예, 말씀하세요. 119입니다. 아, 내가 지금. 저 병원에 좀 가야 되겠는데요. 예, 구급차 필요한 거예요? 예, 예. 주소 알려주세요. 여기서 어디냐면요? 네, 길거리에 나와있는데요? 종로가 이 저. 이 저 지하철 타는 데 있죠? 승강장이요? 예, 그 10번 출고 앞에 있어요. 몇 번 출고? 10번 출고요. 10번 출고? 정로 5차 지하철역 10번 출고? 예 10번 출고 앞에 길거리 나와 있어요. 네 어디가 아픈 거예요? 아니 그럼 어지러워서 그래요. 어지러워서요? 연락을 한 코로나는 없어요? 예 없어요. 예 알겠습니다. 혹시 옆에 간판 보이는 거 있어요? 네? 간판? 음.. 그쪽.. 그쪽.. 간판 보이는 거 있어요? 간판? 광장 시장 같아요. 네? 광장 시장 같으라고요. 네 그 간판 뭐 보이는 거 없어요? 간판요? 네. 아휴. 제일 가까이 있는 간판 보이는 거 없어요? 수박관대 갈게요.
 1급입니다. 말씀하세요. 아 네 제가 아나필락시스 받는데요. 아 예예. 네 부어서 좀 제가 정리했는데 호흡이 하는 느낌이 들어서. 아 지금 호흡이 힘든 상태라는 거죠? 네. 예 구급차를 바로 보내드리면 될까요? 그러면? 네. 예 주소가 어떻게 되세요? 네 그 쌍문동. 예. 쌍문동. 네. 예 몇 층 몇 호에요? 알겠습니다. 지금 뭐 코로나 관련해서 열이나 기침 이런 영상 있었나요? 그전에? 어 전혀 없습니다. 네 알겠습니다. 조금만 기다려주세요. 네.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네 저희 아들이 네 30날 백신을 맞았는데 그때는 결제하다가 어저께 오늘 열이 엄청나고 편도도 붓고 막 지금 시금땀나 그러는데 어떻게 해야 될까요? 많이 심하시면 응급실을 가셔야 될 것 같은데요. 네 지금 저희 오실 수 있어요. 저희 경로구 삼평동. 잠깐만요. 네. 아니에요. 코로나 3차 맞았어요. 아 네 알겠습니다. 전화 오면 잘 받아주시고 저희 구급차는 가까운 응급실 뭐 이거 열나는 것 때문에 격리실 질려고 가능한데 한번 알아보셔야 될 것 같은데요. 그럼 어떻게 해야 돼? 서울대로 갈까 싶은데? 서울대로. 그 병원이 지금 열나는데도 아무데나 못 가요. 그러니깐 구급대학 오면 물어보세요. 친구 제분 오면은. 아 저 저기 117 아저씨자한테? 네 출동하는 구급대학 오면 물어보세요. 아 예, 알겠습니다.
 119입니다. 네 잠깐만요. 네 여보세요. 네 119입니다. 아 네 혹시 그 여기 술집에서 친구가 너무 못 움직이고 토를 너무 많이 해가지고. 네. 혹시 그 부르려고 하는데. 친구분이 지금 응급실 가서 진료 보실 건가요 선생님? 아 그 취소 못 움직여가지고 토 계속하고. 그러니까 선생님 친구분이 지금 응급실 가서 진료를 보실 거예요? 저희는 응급실로만 이송이 되고요. 자택으론 이송이 안 돼요. 네, 네, 네, 네. 지금 응급실 가실 거예요? 네, 네. 주소가 어떻게 돼요? 여기가 잠시만요. 여기 서울 서울특별시 네. 그 소대문구 연쇄 5 7 길 네. 몇 층에 있어요? 선생님 근데 저희가 간다고 하더라도 저희가 단순 술 드신 분들은 미 병원 이송 안 해요. 119에서 알고 계셔야 돼요. 네, 네, 뭐 오는 짓 있어가지고 죄송해요. 일단 선생님 어 일단 대원들 가서 확인을 할 거고요. 네. 확인했는데 그냥 단순히 술 드셔가지고 그런 거면 저희 이송 안 돼요. 알고 계세요? 네, 알겠습니다. 네.
 예 수고하십니다. 네 여기 현대아파트 무슨 일이에요? 아버님이 지금 긴급 상황이어가지고 아버지 어디 아파요? 지금 지금 거의 탄진 상태여가지고 병원에 지금 가야 될 것 같아서요. 집에 확진자 확진자 자가격리자 혹시 있어요? 없어요? 확진자 없어요. 지금 혼자까지 다 와있어서. 현대 현대우성이에요? 예 예 현대우성이요. 현대요동 하경 옆에 있는거 맞죠? 예예예예 예 구급차 보내겠습니다 의식이나 호흡 확인 좀 해주세요 의식호흡 의식호흡 하고 계세요 네 알겠습니다 구급차 출발 시켰어요 예예예

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네 연령입니다. 말씀하세요. 예 수고하십니다. 근데 지금 혼자서 양지 병원 가야 하는데. 어느 분이 어떻게 편찮으신데요? 예? 어느 분이 어떻게 편찮으세요? 뭐라고요? 어느 분이 어떻게 편찮으세요? 막 가슴 뛰고 막 허리 아프고. 어느 분이요? 예예예. 선생님. 잠시만요. 관악구 신림동. 예예예. 가야골이요. 어제 그전가 왔다 가셨는데. 몇 층 몇 호예요? 네? 몇 층 몇 호예요? 단독이에요? 아 여기 가게에요 가게 가게에요? 예예예 어느 분이 편찮으세요? 관계가 어떻게 되세요? 환자분이랑? 아니 제가 본인 아 선생님 본인이에요? 예예 본인이에요 아 네 알겠습니다. 대원들 나가면서 전화드릴 수 있고요 최근에 코로나 관련해서 의심증상이나 접착했다고 문자 받으신 거 있으세요? 아 그 그 2차까지 다 맞았어요 네 감사합니다.
 예 예주구입니다. 예 영암동 그 동양 사우난데요. 동양 사우나 예 예 예 그 저기 남탕에 예 선생님이 저기 빨리 와가지고 인류 좀 빨리 불러라 그래갖고. 자 의식이라든지 호흡 확인되세요? 아니면. 지금 여기 문을 하고 있는데 빨리 문을 하고. 내용 한번 확인해 보세요. 숨을 쉬는지 뭐 의식은 있는지 한번 봐보세요. 예 잠깐만요. 예. 아 어때요? 어때요? 어떠냐고 물어봐. 어? 이거 어떠냐고 상황이. 상황이. 환자분 앞으로 가보세요. 지금 나가고 있습니까? 아니. 지금 현재 상황이 어떠냐고 물어보잖아. 이 시계에 의식이 없는데. 여보세요? 예예. 아 지금 거의 의식이 없는데. 자 숨 쉬는 거죠. 차는 나가고. 예. 쉬는지 봐주세요. 예예. 여보세요? 옆으로 봐주세요. 선생님이. 예예예. 환자분 숨 쉬어요 안 쉬어요? 숨 쉬어? 여보세요? 아 노인 양반인데. 숨을 쉬는지 봐주시라고요. 제일 중요한 거니까. 어디 숨도 안 쉬는 거 같아요. 자 대원들 나가는 동안 응급차 차 안내할 때 환자분 옆으로 가세요. 환자분 옆으로. 예예예. 맞고요. 예예. 대원들 가면서 전화드리라고 할게요. 동양사우나 그 충암 충암 충암 충암학교 옆에 들어가는 그 골목 맞죠? 예예. 대주시장 옆으로 알겠습 차 나가고 있어요. 예예.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네, 이겁니다. 네, 저희 딸 아이가 숨이 차가지고 숨을 못 쉰다고 그러는데. 네, 딸 아이가 숨을 못 쉰다고요? 숨쉬기가 힘들어서요. 지금 병원을 가야 되는데. 갑자기 왜요? 약간 알러지 저 호흡 그게 있거든요. 지금 무슨 어디 뭐 먹고 알러지가 있어요? 아니 원래가 저기 알러지가 있어요. 먹는 게 아니라. 무슨 음식에 대한 알러지가 아니고? 네. 네. 그래서 지금 병원 가실 거고 고급 설정하시는 거예요? 네. 예. 주소가 어떻게 돼요? 은평구 신사동 행복한 집. 아니요. 주소로 주소로. 은평 터널로 7길? 네. 7길? 은평 터널로 7길에 한 집 몇 집 몇 호요? 몇 호요? 뒤에 말씀하시는 분이 그분이에요? 아니요 제가 엄마예요. 아 그 좀 전에 목소리가 들린 것 같은데 예 옆에 앉아있어요. 말을 하는데 그냥 조금 순식에 힘들다는 거죠? 힘들어요. 예 힘들어서 숨을 못 쉬고 있어요. 엠블런스 울지 마시고 몇 분 모실까요? 한 10분 정도 걸릴 것 같아요. 10분이요? 네. 사이렌 울지 말고 오세요 부탁합니다

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 예, 1 2 금다. 예, 예, 세전력입니다. 세전력요? 예, 예. 예, 세전력. 예. 고등학교에서 어떤 분이 너무 추정하고도. 예. 예, 선생님 계단 낙서 남자예요? 여자예요? 남자예요. 예, 남자예요. 계단 낙서 몇 번 출구 쪽이에요? 2번 출고요. 네, 선생님 2번 출고요. 계단 낙서. 예. 선생님 그분요 혹시 코로나 관련해갖고. 예. 에 그 기침이나 열 그런 거 있었는지 그런 건 없는 거 같아요. 예 그런 거 같고요. 선생님은 혹시 영문 영무원이세요? 혹시요? 예 예 이번 추구 이번 추구 계단요. 이번 추구 계단에 남자 예 낙상으로 선생님 이제 호흡이 오늘 나오니까는 옷을 다 벗고 있어요. 예? 위에 상의를 예 호흡이나 의식 그런 건 상관없지요? 예 지금 없는데 약간 불편해하시는 거 같아요. 낙상으로요. 네
 여보세요? 네, 네, 119인데요. 네, 네. 거기가 새마을 3구 운동포차예요? 아니면은 1970 새마을포차예요? 여기가 1979. 여기 1979 3마을 포차 아니면 3구 포차요? 그냥 3마을 포차예요. 그 3마을이 그렇게 2개가 나와요. 아 그 그 처음에 뭐라 하셨죠? 3마을 3구 운동포차가 있고. 아 그거 말고 그 두 번째 거요. 아 1970 3마을 포차? 네네. 혹시 몇 층이에요? 아 알겠습니다. 네.
 119입니다. 말씀하세요. 여기 지하철 1호선 대방역 영무실인데요. 아 예예. 네 어떤 생생분께서 열차 내리셨는데 머리가 좀 매우 어지럽다고 해서 119를 좀 불러달라고 요청을 해서 지금 연락을. 영무실로 가면 되는 거죠? 네네. 남자분이요? 남성분이요. 남자분이고 어지럽고 열이나 기침 이런 현상이 있는지 혹시 파악되나요? 코로나 관련해서. 아 잠시만요. 네네. 혹시 열이나 기침 이런 증상은 있어요? 그건 없다고 하십니다. 아 예 알겠습니다. 조금만 기다려 주세요. 네 감사합니다. 네.
 네, 일곱니다. 아 예, 배가 너무 아파서 그러는데요. 네. 병원 1번 가고 싶어서요. 주소 좀 알려주세요. 관악 드림타운. 관악 드림타운. 그리고 혹시 열이 나거나 기침 코로나 관련 증상이 있으세요? 선생님? 열은 없고 그냥 콩물이 나요. 출동하겠습니다. 코로나 확진자 아니시죠? 관악 드림타운 예.
 네, 열리 겁니다. 말씀하세요. 네, 여보세요? 여기 여기요. 저기 뭐야 동네문구 시립대로. 여기 사람이 쓰러져 갖고 지금 문 일어나서 그러거든요? 예, 예, 그 5분 마루 지하로 오시면 돼요. 5분 마루. 잠시만요. 5분 마루 지하에. 예예. 지하 공장이에요. 여기가. 공장 남자분이에요? 친구분이에요? 아니 여자분이에요. 여자분. 지금 숨 쉬어요? 예 숨도 쉬는 자꾸 잠이 온다 그래요. 갑자기 포함해서 안 됐다가 그냥 넘어졌대요. 신고자 차 출발했고요. 전 전 서울 시립대로. 예 시립대로. 예 코로나 확진된 분 없으시고요? 네 알겠습니다. 빨리 나와볼게요. 네. 나 한참 좀 쳐야 돼. 가.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네, 수고하십니다. 저기 병원 좀 모실려고 그러는데요. 병원 문의하신다고요? 네. 병원 안내 부서가 찾을 있는데 그쪽으로 돌려드릴게요. 아니요. 여보세요. 병원 좀 모실려고 그런다고요. 병원을 모신다고요? 누가 어떻게 하는 거예요? 어르신데 저기 의식이 가물가물하고요. 누가 그러신 거예요? 어머니가요. 의식처 아시시고 손 잘 달으시고 계세요? 숨은 저기 하시는데 몸을 거동을 못해요. 거동도 안 되시고. 주소지 어떻게 되세요? 신경동 항마을 아파트. 항마을 아파트요? 예. 잠시만 몇 동이에요? 신경 3동. 항마을 아파트 아파트잖아요. 그죠? 몇 동 몇 거예요? 예. 잠시만요. 양천구단 옆에 있는 항마와트 맞으시죠? 예예예. 지금 차를 편성해서 보내드리고 있고 기침, 열, 복구, 통증 같은 코로나 증상 없으시고요? 예. 통증 아직 없는데. 코로나 증상 없으시고요? 예예. 알겠습니다. 차 출동해서 가고 있어요. 그리고 어머니 지금 의식 상태가 안 좋으신 거예요? 예. 아까는 저기 많이 없지가 않은데요. 목에 거동을 못하시고 어제부터
 네 열려 봅니다. 여보세요? 예. 예 저희 신랑이 지금 너무 아파가지고 걷지도 못하고 그러거든요. 어디 아프세요? 어 다리요. 종아리 발목에서부터 거기 허벅지까지가 좀 아파서. 구복지에 떨어지는 거죠? 네네네. 주소 불러주세요. 미화동? 예. 네. 몇 층 몇 호예요? 가족분들 중에 코로나 지역 다녀오거나 관련 증상 있나요? 아니요. 관련 증상은 없는데 어저께 저희가 코로나 검사는 받았거든요. 결과는 안 나왔고요? 네. 결과는 아직 안 나왔어요. 왜 받으신 거예요? 저기 사무실에 확진자가 나와가지고 사무실에 확진자가 나와서? 네네. 선생님이요? 아니면 남편이요? 아니요. 그... 저 신랑이요. 알겠습니다. 구구창 가니까요. 전화 오면 잘 받아주세요. 네.
 네, 여보세요? 네, 말씀하세요? 예, 여기 아버지가 숨을 안 쉬셔요. 연세는 92세 되셨고요. 호흡도 없어요? 호흡은 있으신 거 같은데 지금. 예, 호흡이 비상상적이세요? 아니에요. 호흡이 있냐고. 숨은 쉬신데. 숨은 쉬시는데 어떤 증상이 있어요? 지금. 지금 가를 계속 가래 가래 그 가래 뱉으시다가 지금. 지금 눈동자가 돌아가셨어. 아유 안돼 안돼 식사 도중 눈동자가 돌아갔다고요? 예예 식사하다가 지금 석양은 생기신 것 같은데요? 네 지금 숨은 정상적으로 쉬고 있어요? 아니면 지금 정상적이에요? 숨도 숨 안 쉬는 것 같아 잘 모르겠어요. 그냥 눈동자 돌아가셨어. 호흡이 지금 정상적이신 거예요? 네 숨 안 쉬는 것 같아요. 알겠습니다. 주소 좀 빨리 알려주소 주소. 마포구 망원동? 네. 차 어디야 마포부 월드컴로 31길? 월드컴로. 31길. 31길. 아. 네. 성진센터들이에요? 어? 어 성진센터들. 어. 죄송하고요. 저희 의료 좀 연결할게요. 전화 끊지 말아주세요. 네. 아 근데 아직 유식은 있으신데? 어휴, 전화 끊지 말라고 그랬다. 이렇게 해봤어. 뭐, 누가 상처에서 그런 건지.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 일요일요. 선생님 저 눈 나가요. 예예. 배가 아파갖고 응급실까지 지금 데려다 주세요. 아 다른 데 아프신 건 없고 배만 아프신 거예요? 복동에 있어갖고. 아 그럼 계신 곳 주소 좀 알려주세요. 안암루. 이게 안암루 오시면 몇 시? 아 잠시만요. 예예. 여보세요. 아 동대문구에요? 성북구에요? 성북구요. 잠시만요. 성북구 안암루 아 거기 매튼 매튼에 계시는 거 미니하우스인가요? 예 맞아요. 예예 잠시만요 미니하우스 구급차 가고 있고요 저희가 모든 출동권에 코로나 관련 질문을 드리고 있어요 차 가는 동안 몇 가지 질문 좀 드릴게요 혹시 그 계신 분들 중에 발열이나 고열 기침 인후통 같은 코로나 관련해서 있으신 분 안계시죠 없어요 확진자를 접촉을 하셨거나 자가격리 상태이신 분이 안계시고요 예 없어요 아 대원들이 가면서 핸드폰으로 전화드릴 거예요. 전화 좀 받아주세요.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 연락 옵니다. 아 지금 애가 지금 8등에 상처가 나와서 피가 많이 났는데 그 백 병원이 왔는데 이게 꿈에는 주는 사람이 없대요. 그래서 지금 119 차를 좀 백 병원 응급실 보내주실래요? 어디 병원으로 가야 될지 모르니까 저희가. 잠시만요. 몇 살이에요? 네? 몇 살인가요? 환자분이? 24살이요. 남성분이 어떻게 다치신 거예요? 손을? 아 이거 유리창 옮기다가 이렇게 유리 그 넘어져서 깨져서 등이 닫혔어요. 아 유리가 계속 등 쪽에 닫히신 거예요? 네네네. 등 치료요? 그 상계백병원 앞쪽으로 갈 거고요? 네. 상계백병원은 진료가 안 된다는 거죠? 예예예. 그래서 이 꾸며주는 데를 병원을 모르니까 우리가 이것저것 다니면 안 되니까. 중요한 게 일단 열이 있으면은 응급실이 좀. 없습니다. 말 같은 게 없으시고요? 뭐 네 네 네. 저희 대원에 가면서 전화드릴 거고요. 가족분들 포함하시면 뭐 확진자를 접촉하셨거나 자가격림 상품이 없으시고요? 네 네 네. 지금 주변에 있는 구급차들이 다 출동 나가 있어서 한 5km 정도 떨어진 데서 가고 있어요. 좀 시간이 걸릴 것 같아요. 조금만 기다려주세요. 예. 네 그럼 응급실 앞으로 좀 와주세요. 예 전화 중에서 갈 거예요. 대원에서 전화 좀 받아주세요. 네 네 네.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 119입니다. 아 예. 예 말씀하세요. 갑자기 이제 고마 아파서 좀 도망하는데요. 지금 환자가 아파서 119로 응급실 가셔야 되는 거예요? 거동이 어려워요? 네. 주소가 어떻게 돼요? 환자분 계신 곳 주소. 구로동. 구로동. 네. 몇 번지예요? 구로 두산 아파트. 네. 몇 동 몇 호예요? 그니까 몇 몇 동에 네 네 네 네 네 네 어디가 아프신 거예요? 여자분? 배가 짝이 이렇게 아파요. 배가 아픈 거예요? 네. 뭐 주변 없었는데 갑자기 아프신 거예요? 네. 아. 뭐 요즘 코로나 관련 뭐 고열 기침 감기 증상 있으신 건 아니죠? 네 감사합니다
 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 네, 가능이 없어요? 아님 의식이 없는 거예요? 지금 의식이 없는 것 같아요. 금방까지도 제가 했는데 여기 119 20시다는 말이죠? 아니 20시건 눈을 지금 뜨고 있어요. 눈은 뜨고 있어요? 눈을 그냥 반은 뜨고 있는데 별로도 대답이 없어요. 남자예요? 여자예요? 남자예요. 제가 우리가 의지병원을 거기 다녔고 다 자세한 건 일단 예 자세한 건 그것부터 오면 얘기하시고 일단 저한테는 주소부터 좀 알려주세요. 예 여기 노원구 노원구 16개 잠깐 농구 노원로 16길 예예. 눈이 지금 안 떠지는데. 구급차 보내고 이거 숨 쉬라 중요한 거니까 다시 한번 확인해 보세요. 바로 일단 구급차는 보냈대요. 숨 쉬어요. 가슴 오르락 내리락해요. 코에 바람 나오고. 아이 아무 감각이 없는 거 없고 코가 없는 거 같은데 눈이 가방 떴는데. 가슴 오르락 내리 아니 아니면 이렇게 아프게 해서라도 막 꼬집어가지고 깨워보세요. 반응이 전혀 없는가. 막 때려가지고 깨워보세요. 때려가지고 아프게. 반응이 전혀 없어요? 예예 손도 늘어지지 않는 것 같은데 지금 얼굴은 차가워요. 얼굴이 차가워요. 일단 저기 호흡도 정상적으로 막 쓰진 않죠. 규칙적으로 일단 구급차는 보내긴 했거든요. 지금 이게 중요한 거여가지고 한번 다시 한번 확인해보세요. 가슴 쪽에 천천히 보면 오르락 내리락 해요. 이제 해요? 안 해요? 아니 아무 이상이 없는 거 같은데 지금 반응이 없는 거 같아요? 가는 동안 저희 의사 선생님 바꿔드릴게요. 끊지 마세요. 가고 있으니까 끊지 마세요.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네, 수고합니다. 네, 여기 지금 어 제 노인 1분이 쓰러지셔가지고 일하시다가. 할아버지세요? 네. 일하시다 갑자기. 예. 체크페인 같은데. 뭐가 같다고요? 어릴시죠? 예. 바로 넘 그 넘으셨어요. 근데 눈면 깜빡하시고 말씀은 못하시는 거. 아 눈은 깜빡하세요? 의식은 있어요? 말은 못하고. 어디 안 보세요? 숨은 쉬셨는데요. 예. 말을 못 하세요? 네. 말씀은 못 하세요. 떨어지신 건 아니고 넘어진 거예요? 네. 일하시다 서 있으시다가 바로 네네. 아 호흡은 괜찮으세요? 호흡은 있어야지. 호흡 괜찮아요? 잠시만요. 그 위치가 어디예요? 혹시 여기 주소 아세요? 아 여기 능동 주민센터인데. 음 능동 주민센터 앞으로 가면 돼요? 네. 그쪽 앞에 공영 주차장 있거든요. 아 능동 주민센터 앞에 공용 주차장 네 그쪽으로 가면 돼요? 네 네 이쪽으로 오시면 돼요. 네 알겠습니다.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 예, 여보세요. 여기 어. 마천동. 예, 예, 예, 예. 몇 층인데요? 무슨 일 때문에 그래요? 지금 힘이 없으시고 이거 지금 저기 하셔요. 남자분이에요? 예, 예, 예. 몸에 힘이 없으시고 병원과 병원과 병원을. 예, 예, 예. 의식이 있어요? 없어요 지금? 의식은 약간 있어요. 호흡은 정상적으로 하시고? 예, 예, 예. 알았어요. 정상적으로 하시는 거죠? 호흡은? 예. 그 후자 보내드렸고요. 네, 네, 네. 관련해서 뭐. 코로나는 아니에요. 그런 증상은 없는 거죠? 예 식은땀이 있고 열이 식은. 아 고급처 마천 그 1동 주민센터 바로 옆이네요. 고려 대원들한테 전화할 수 있어요.
 119입니다. 네 여기 강남구 다곡동에 있는 시그넘 마우스라고 합니다. 다곡동에 시그. 그 주소가 어떻게 되나요? 다곡로. 더 시그넘 마우스라고 나오네요. 예. 그 무슨 일이세요? 네 입주에 계신 분이 네 예 지금 편찮으셔가지고 어 어디가 편찮으시대요 그분이? 지금 심장이 협신증 앓고 계시거든요 네 예 지금 숨쉬기가 곤란하셔가지고 남자분이에요? 네 네 남자분이고 협신증 환자인데 호흡곤란 증세 있고 선생님하고 관계는 어떻게 되세요? 아 저는 여기 저희 회사 그 보안 근무입니다. 네. 혹시 그 분 코로나 증세나 이런 건 없으시다고 하시나요? 네 없습니다. 예 알겠어요. 그쪽으로 구급차 나가고 옆에 같이 계세요? 아니면은 그 지금 내려오셨어요? 저는 내려와 있고요. 아 예예. 예. 보호자들이 있어요. 보호자분? 그쪽에 계신 분 연락처 아무 분이나 한번 주시겠어요? 혹시 가지고 계신가요? 그럼 일단 나가볼게요 여기쪽으로 네네

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네, 일요일입니다. 말씀하세요. 네, 저기 지금 빨리 그 엄마가 쓰러지셔 가지고요. 네, 네, 네, 원래 신균 형태계 있어요. 네, 네, 위식은 지금 있는데 굉장히 급해요. 뭐 어 빨리 아 롯데캐스요? 여기서요? 저희가 네, 저희가 여기 서울 정관역 관장에서 혹시 주소 구주소나 신주소 불러주실 수 있으실까요? 네, 뭐라고요? 구주소나 신주소. 의사장대로. 의사장대로 네네네 잠시만요 아 빨리 오셔야 될 것 같은데 네 근처로 나가고는 있어요 네 몇동 몇호요? 네 대연도 나가면서 전화드릴 수 있어요 전화받고 안내 받으시고요 받으시고요. 영두포역 쪽에서 나가느라 시간이 조금 걸릴 것 같아요. 최대한 빨리 가라고 할게요. 네 빨리 와주세요.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네 여보세요. 저 제 친구가 지금 어 가을이 와가지고 좀 심한데 혹시 여기 근처에 빨리 갈 수 있는 어 어 이거 더 처치할 수 있는 병원 같은 게 혹시 있을까요? 선생님 병원 안내만 해드리면 되는 거예요? 지금 그 운구차 필요해? 구급차? 구급차 있으면 좋을 것 같아요. 주소가 어떻게 돼요? 저 신림도. 네. 퀸즈타운요. 몇 호에요? 친구분이나 선생님 본인 중에 기침 발열 있는 사람 있어요 요새? 어 기침 발열은 없어요 둘 다 기침 발열 없어요? 네네 그 다 저희 다 그 뭐냐 그 2차 접종까지 많이 했어요 네 제가 구급차 보냈고요 네네 친구한테 호흡 천천히 크게 기치시라고 하세요 천천히 천천히 크게 실 네 가고 있습니다 네 네.
 네 감사합니다. 아 네 저기 네 여기 86세. 86세 네. 네 36세 그 승인 환자로 지금 고정을 못하시는 분이신데요. 네. 어 지금 주변 되게 소랑스러운데. 자세히 좀 침착하시고요. 지금 어떤 일로 전화하신 거예요? 환자분이 아파요? 네, 네, 지금 어디 가신 거예요? 오늘 그 병원에 가서요. 요관 소재를 제거하고 오셨는데 지금 통증 정상 후소하고 소변이 안 나오고 지금 피만 나오시고요. 지금 위로관을 하고 계시는데 그 피가 위로관으로 지금 역류가 되고 있으시더라고요. 그래서 지금 응급실에 지금 가야 될 것 같아서. 위로관으로 내용물이 역류한다고요? 네 피가 피가 피가. 선생님 지금은 이어폰 쓰시고 계신 거예요? 스피커폰 쓰시고 계신 거 아니에요? 지금 거두가 울려서 하나도 안 들려요. 어 잠깐만요. 그러면 제가 그냥. 제가 여쭤볼 테니까. 직접 하시고 대표만 해주세요. 환자분이 남자예요? 여자예요? 여자예요. 의식은 있어요? 네, 네. 환자분이 갖고 계신데 지금 위로관 위로관이라고 말씀하신 게 맞아요? 네 위로관. 주소가 어떻게 돼요? 여기 어 목동 남로 4길. 몇 층 몇 호요? 목동 2층 우성 아파트 맞아요? 네네 그쵸 고객자는 보냈구요 환자분 코로나 확진자분이시거나 감기 증상은 없어요? 네네 네 고객자 보냈습니다 기다려주세요 네 응
 네, 네, 네. 여기 아버지가 갑자기 상황이 좀 안 좋아서. 아버지가요? 예, 예. 지금 어때요? 성함이. 아 모르겠어요. 지금 갑자기 선임이 급 저조되면서 지금. 지적이 없으신 거예요? 네, 네, 네. 의식이랑 부분 다 괜찮으시고요? 네, 지금 좀 빨리 좀 와주셨으면 좋겠어요. 예, 예. 주소는 어떻게 되세요? 서울시 서초구 서초동에요. 예. 네 몇주 몇 프로 가면 돼요? 네 서초동아파트 알겠습니다. 네 얼마나 걸리세요? 잠시만요 구구차가 지금 잠원에서 가니까요 최대한 빨리 가라 올게요. 네 최대한 빨리 부탁드립니다. 네
 네, 고객님. 무슨 일이세요? 여보세요? 일일 거예요? 아 네, 저기 저희 어머니가 좀 문이 안 좋으셔가지고 미식이 지금 안 돌아오시는 거 같아요. 숨은 지금 안 쉬고 계세요? 네, 숨은 쉬시는데요. 정상적으로 쉬어야죠? 네? 숨을 정상적으로 쉬고 계시냐고요? 어 약간 불안정하긴 하는데 숨은 계속 쉬세요. 호흡도 불안정하고요. 계시는 분이 어떻게 되세요? 금천구 가산도? 예. 몇 층 몇 층에 계세요? 예. 같이 계시는 거죠? 네네. 차 열어도 설정해서 보내드렸고요. 의료 지도 연결할 거예요. 전화 끊지 마세요.
 아 어 네, 1 9입니다. 여보세요? 예. 여 저 이 저 도봉역 아 도봉 지나서 빠르다 카페 예. 골목해서 저 사고 났거든요. 어떤 사고 교통사고요? 예, 예. 저 오토바이가 예. 걸어갔는데 바로 쳐가서 좀 사람이 누워 있어요? 어 빠르가게 앞으로 구급차랑 경찰이 같이 가겠습니다. 예, 예, 예. 예. 감사합니다.
 연령입니다. 예 수고하십니다. 그 뭐 좀 물어보려고 그러는데요. 지금 제가 저 그 코로나 확인돼가지고 저는 그 생활 취업 그 센터에 지금 들어와 있거든요. 네. 그리고 저 우리 집사람도 또 확인돼가지고 집에서 또 그 격리돼 있어요. 네. 근데 우리 아들내미가 지금 엄청 아픈데 우리 아들내미도 나가지는 못하거든요. 집에서. 어 예. 그 지금 편도에 온다고 그러는데 지금 한 열이 한 40도까지 올라가 갖고 지금 엄청 아픈 모양인데 어떻게 뭐 어디 뭐 그 법이 없으니까 지금. 저기 한번 가보고요. 그게 적어야지 그거예요. 그 어차피 격리 중으로 들어가는 거죠? 아드님도. 그렇죠. 근데 아들내미는 저 그 확진된 건 아니거든요. 양성은 음성으로 나왔거든요. 근데. 이게 그 격리 중이시면은 그 응급실 중에서 격리실 진료 가능한 곳으로 좀 해가지고 고급변이 한번 물어보고 갈 수 있는지 병원마다 좀 알아봐야 돼요. 그게 좀 상황이 안 좋은 경우에는 자리가 없는 경우도 있어가지고 최근에는요. 예 그러니까 좀 어디 좀. 뭐 하시려. 여 동대문 장안 1동이고요. 예 아니 아드님 계신 데가. 그러니까. 아 그래서 장안동? 개명 장안 1동. 네. 개명 1움 아파트. 네. 잠깐만요. 찾아봐야 되겠네. 개명 이름 2룸이요? 개명 개명. 개명. 큰 개명. 아 대명. 네. 개명 1움 아파트. 2음 아파트? 2룸 2룸 2룸. 2룸. 여 군자초등학교 바로 옆에 있는 거거든요. 아 그래요? 아 예. 그러네요. 예. 네. 몇 동 몇 론데네요? 공원 하나예요? 예 그렇죠. 예 하나입니다. 어 이거 알겠어요. 일단 이거 몇 호 한번 가보고요. 여기 아들 좀 성함이랑 저희가 전화번호가 좀 필요하거든요. 이건 일반 환자랑 좀 달라가지고 알려주시겠어요? 아들내여 전화번호. 네 아 전화번호. 우리 저 마누라 전화번호 가르쳐 드리면 안 돼요? 그거 한번 물어보시면 바로 되는데. 아 예 그렇게 하시던가요 그러면? 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 수가 있습니다. 부급자원이 뭐 확인하려면 전화드릴 수가 있어요. 예 예 예 알겠습니다. 일단 오면 좀 잘 받아주세요. 네 제가 한 2시간 동안인데 네 네.
 네, 수고하십니다. 고맙습니다. 네, 지금 아까 갑자기 아파서 그러는데. 어느 분이 어떻게 괜찮으세요? 아, 지금만 갑자기 연락을 그러는데. 아, 선식, 선식 때문에. 선식이요? 지나가시던 분이세요? 아니, 저 남수친군데 지금. 안녕하시고요? 네. 주소 지금 계신 곳 어디예요? 여기 주소가 단위에 상판을 하고 차요. 그럼 천천히 나오세요. 잠시만요. 천천히 말씀해 주세요. 다니엘 캄타밀라 호텔. 다니엘 캄타빌레? 잠시만 제가 부를게요. 잠시만요. 네. 주사해 주세요. 오페산로 79일. 오페산로. 네. 잠시만요. 다니엘 디자인 호텔 앞이요. 네 맞아요. 네 여기 앞에 계신 거죠? 네. 네. 네 알겠습니다. 대원들 남아있다 전화드렸으니까 전화받고 안내 좀 부탁드릴게요. 네.
 네, 여보세요? 여보세요? 네, 저기 할아버지인데 90세대 할아버지인데. 계속 설사를 하셔요. 이 열흘이 넘어서 제가 약을 한번 찾아 먹었는데 지금 거의 탈진 상태 미움도 안 드시고 그래갖고서는 아무래도 병원에 가야 될 것 같은데 걸음을 못 걸으셔요. 그래서. 네 병원으로 좀 무셨지만 아니 그전에 상계대병원에서 1번 간 적 있거든요. 그때 열흘 전에 설사로 거기 상계대 병원은 없으세요? 없으세요. 그거는 이제 음성 나왔고 네 아마 상계대 병원에 가면 주소가 강북구 미아동 몇 층 몇 호에요? 현대 아트빌라 . . . . . .

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 119입니다. 네 저기 엄마가요. 아침에 체하셨는지 어제 밤부터 체하셨는지 막 몸이 차가웠는데 오늘 좀 전에 막 엄청 토하시고서는 거의 정신을 잃으셨거든요. 의식이 없어요? 있어요? 없으세요. 의식이 없다고요? 지금? 예. 눈도 못 뜨고 있어요? 숨을. 예. 숨도 잘 모르겠어요. 옆에 보세요. 숨 배가 오르락 내리락 가슴이 오르락 내리락 하는지. 배요? 네, 예. 배하고 가슴이 오르락 내리락 하는지 숨소리가 질리는지 보세요. 오르락 내리락 안 하시는 거 같아서. 숨 안 쉬는 거 같아요? 네. 확실하게 해주세요. 그 심폐소생술 해야 될 수도 있으니까. 그 주소 불러주세요. 주소. 주소 어. 미래성대로. 미래성대로. 몇 층에 한번 확실히 보세요. 그거 배 숨시는지 안 쉬는지. 오드람은 어디다가 안 하시는데. 거기도 안 들려요? 네 너무 조용해요. 그래요? 선생님 지금 저희가 아예 안 쉰다는 거죠? 모르겠어요. 네 지금 나가니까 쫌만 기다리시고 전화 끊지 마세요.
 안녕하십니까? 네 저 고급차 필요해서 연락드렸는데요. 예 누가 아프세요? 예 어머님이 좀 아프시고요. 어머니가요? 어 좀 부족 때문에 거동을 못하세요. 지금. 아 그래요? 어머니 의식은 괜찮아요? 예 의식은 있으시고. 아 의식이니까 거동 힘드셨고요. 예 예 예 꼼짝을 못하세요. 주소가 어떻게 되세요? 마포구. 예. 합정동. 예. 여기 지금 토종로에 토종로 아 성지삼길 잠시만요 아까는 번지가 지금 헷갈려서 도로명 주소를 다시 불러주세요. 합정동 합정동 성지삼길 성지삼길이요? 네네 예 몇 층이요? 예예 어머니 열이 나기 지금 코로나 관련 사항 있으세요? 아니요. 없으세요. 그런 거 없어요? 네네. 네 알겠습니다. 전화 잘 받으세요. 네. 아 신고자 분. 네. 네 지금 거리가 조금 있어서요. 조금 걸려요. 네. 정도 떨어져 있어요. 네. 네.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 안녕합니다. 아 예 수고하십니다. 아 아 여기는 마다데레 사이집에 들어가는데요. 아 우리 저기 어 여기 장애인분이 복통을 계속 호수를 하고 있어가지고요. 그래서 응급실을 가고 싶어가지고요. 예 주소가 어떻게 되죠? 아 성북구 삼선교로 삼선교로 이길 예 그럼 몇 층 어디예요? 아 여기는 저기 예 환자분 나이대랑 성별이 어떻게 될까요? 어 60년생이고 남자분입니다. 예 코로나 관련된 건 없으시고요? 예 관련은 없습니다. 예 감사합니다.
 119입니다. 여보세요? 네. 아 이게 화재 119예요? 화재랑 뭐 구급차랑. 아 그렇죠? 어 지금 저기 어르신이 어 너무 아파서 저기 뭐야 그 응급실을 가야 될 것 같아서요. 아프신데요? 어르신이 뭐 할아버지? 할머니. 어디가 어떻게 아프세요? 어 아침부터 계속 토하고. 네. 어 그리고 뭐 다리가 이렇게 뭐 이렇게 틀어지려고 그런다고. 아 진짜 구토가 좀 심하세요? 예 아까는 좀 심했는데. 네. 뭐 이제 다리가 이렇게 막 돌아가는 거예요. 다리가 돌아간다고요? 돌아간다고. 다리가 어떻게 돌아가요? 그러니까 이 집이 집이 꼬아질다고 그런다고요. 아 다리가 아프신 거예요? 아니요. 갑자기 그러는 거예요. 이제 다리까지 이렇게 꼬아지려고 하는 거예요. 주소 알려주세요. 주소가 제기로 네. 몇 호요? 이쪽에 이게 없어요? 선생님 관계가 어떻게 되세요 할머니하고? 아 저는 저기 동대문 생활지원사거든요. 아 저는 지금 보내고요. 열 있거나 기침 콧물 있어요 할머니? 기침 콧물. 기침 콧물은 없어요. 아 코로나 때문에 격리하시거나 확진자 없으시죠? 네네네. 네. 보냈습니다. 좀 기다리세요. 네 감사합니다. 네.
 네 안녕합니다. 여기 신성 아파트인데요. 신영 아파트요? 신성 신성 아파트? 네 무슨 일이에요? 네. 119 물러달라고 그러는데요. 누가 어떻게 아픈 거예요? 병원 간다고 움직이지도 못한다고 그러네. 남자분이요? 여자분이요? 여자분이에요. 여자분? 어디가 아픈지 좀 물어봐 주세요. 어디 아파요? 네? 현실하고 있었거든요. 증후하고 가슴 쪽이 아프대요. 혹시 열은 안 나세요? 네 열은 없는 것 같아요 알겠습니다 소방원을 나가보라 그럴게요 예
 네. 예 선생님 119입니다. 예예. 예예. 그 저 아들 친구가 넘어져 있다고요? 예예. 우선 저희 구구차원 출발시켰고요. 뭐 사고 당겨요? 아 사고는 없는데 몸을 가눌 수가 없어가지고서. 몸이 안 좋아서 그러는 거예요? 아 술을 너무 애들이. 아 술 먹었어요? 네 나이 어른 애들이 술 먹어가지고. 네. 어떻게 할 수가 없어가지고. 네 저 우선은 저희 구급차는 나가고 있고요. 그 보호자가 연락이 됐나요? 아니 안 됐어요. 제가 보호자예요. 저희. 저기 친구 이제 저기니까 아들 친구니까. 네. 50만원 제가 있을게요. 네 우선 수강하는 날 나가고 있습니다. 아 얼마나 걸리죠? 대충? 한 10분 정도 걸릴 것 같아요. 예? 10분이요. 예 알겠습니다. 예.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 들려고 합니다. 아 저 지금 2호선에서 사람이 쓰러져서요. 무슨 역이에요? 지금 성주역인데 성주역에서 쪽선부 가는 방향이 6번 칸 앞에서요. 지금 남자 지구 내리시긴 했는데. 남성분이에요? 여성분이에요? 남성분이요. 그 넘어지신 거예요? 아니면 갑자기 의식 그 쓰러지신 거예요? 의식은 있으신데 지금. 약간 의사소통은 되시는데 할아버지시거든요. 아 알겠습니다. 저희가 그 쪽선 방향 6번째 카드 1번 가볼게요. 예. 네 알겠습니다.
 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . I8 is in there.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 아 네. 그건 아직도 확인이 되세요? 네 네 네. 못 일어나세요. 수 드셨어요? 모르겠어요. 수 드셔 수 드신 건지 뭐 한 건지 모르겠어요. 수 드셨겠지? 못 일어나서 근데. 목구멍 폭증 같은 코로나 증상 있는지 물어봐 주시겠어요? 아 그거 어떻게 제가 물어봐요. 그건 못 물어봐요. 예 예. 어르신인데 그냥. 모자 쓰고 세네. 말은 붙여보실 수 있겠어요? 원반 취소?

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 안녕히 계십니다. 네 제가 오늘 교통사고를 당해서. 네. 지금 너무 힘들어서 여기 서울의료원이라는 데 왔는데요. 네. 여기가 응급실이 없어가지고 가까운 응급실로 갔으면 하거든요. 보급자 요청하시는 거예요? 네. 수업 의료원 앞에 계세요? 네. 어디가 아프신데요? 팔이랑 팔이랑 다 아파요. 수업 의료원 거의 정문 앞에 계신 거예요? 네. 선생님 일단 그쪽으로 보급자는 보냈고요. 환자분 코로나 확진자 분이시거나 감기 증상은 없으세요? 네 아닙니다. 수업 의료원 앞으로 보급자 보낼 테니까 좀 기다려 주세요. 감사합니다.
 119입니다. 예 저 119죠? 저희 아버님이 갑자기 숨을 제대로 못 쉬시는데요. 숨 쉬기가 어려우시다는 거예요? 아니야 숨을 아예 못 쉬세요. 잘. 주소 불러주세요. 예 주소가 여기요. 서울시 강서구 방화동. 예. 예. 몇 층에 들어갈까요? . . . . . . . . . . . . . . . .
 네 소방서입니다. 네 혹시 선생님 본인이 아프세요? 예 예 예 뭐 홍재역 어디쯤에 계신 거예요? 다이소 있는 쪽입니다. 다이소 앞에 있어요 그럼? 예예예 역사 내에 다이소가 있는거죠? 예예예 아 찾아가보겠습니다 이거 전화 잘 받으세요 네
 119입니다. 네 안녕하세요. 네. 아 저 다름 아니라요. 아 저기 여기 월계동 저기 월계 4층 단지예요. 근데 어 이렇게 다 분 며칠째 먹지 못하고 이렇게 호글질라서요. 누가요? 선생님이요? 아니면 다른 분이요? 아니에요. 같이 동거하고 있는 분이에요. 남자분이에요? 여자분이에요? 네 아 여 남자분이에요. 남자분이 기력이 없어요? 네네네 기력이 전혀 며칠 동안을 먹지 못했어요. 네. 네 계속 고급질 하거든요. 먹은 게 없는데 고급질에서 기운이 너무 빠져가지고요. 근데 여기서 병원 가실 거죠? 주소 불러보세요. 주소. 아 아 월에 자꾸 일 안 중이. 코로나 관련 고열 기초 민호증 증상 없으시고요? 아 일단은 열은 열은 없는 것 같아요. 열 개 체크해보면. 네 월개 사슴 2단지 맞죠? 네. 예 알겠습니다. 네.
 안줘 봐 안줘 봐. 네 사장님. 예 말씀하세요. 여기 응 과자로 씻기. 네, 예. 할머니 머리 의자가. 예. 찢기셔갖고. 예. 주급차 빨리 출동 좀 해주세요. 아 할머니가 머리에서 피가 나요? 네. 지금 의식은 있어요? 네 의식은 있으신데. 찢어지셔갖고. 아 예 선생님 그거 깨끗한 수건으로 지을 좀 하고 계시고요. 그 거기가 과자로 씻기. 맞죠? 네 알겠어요 그쪽은 무호차 가고있고 최근에 발열이나 코로나 관련 사항 있으세요? 아니요 없어요 네 알겠어요 그쪽은 빨리 가볼게요 네
 네 여기 그 타임스퀘어 게이트 4번인데요. 타임스퀘어의 게이트 4번이라고요? 네 네 그쪽인데 지금 일행이 있는데 일행이 그 이전부터 허리 디스크 같은 좀 그런 의사소개는 좀 있었거든요. 그래가지고 지금 밖에 있다가 지금 택시를 타고 병원을 가려는 상황인데 지금 거의 1발짝도 못 뛰는 상황이어가지고 혹시 도와주실 수 있나 하고 전화드렸어요. 일단은 고급차가 필요하신 거죠? 네네. 서리디스크가 있으신 분이고 남자분이에요? 네네. 그 게이트 4번이라는 데가 영등포, 수상포 맞은편인 그쪽이네요? 네네 맞아요. 아 혹시 친구분이 코로나 관련 증상이나 여유 아 아니요. 그런 건 없어요. 네 알겠습니다. 몇 분 정도 기다려야 될까요? 아 고급차가 근처에 없으면 시중이 걸릴 것 같아요. 여보세요? 네 여보세요? 네, 예. 끊으셔도 돼요. 아 네 감사합니다.
 네. 안녕하세요. 그 긴급한 건 아니고 그 술 좀 많이 먹어가지고 지금 뭐 수액 같은 거 좀 맞아야 될 것 같은데 이제 가능한 데가 있나요? 아 병원 안내만 해드리면 되는 거예요? 병원 안내 어 지금 어 아니 지금 좀 막 실어갈 좀 필요할 것 같은데요. 여유가 되면은 이제. 구급처 요청하시는 거죠? 네. 맞아요. 구급처. 응급실 가시려고 전화하신 거죠? 어 네 잠시만요. 아 예예. 혹시 가능하시면은 네. 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 응 몇 층 몇 호에요? 친구분들 중에 기침 나거나 열 나거나 하는 사람들 있어요? 아니요 없어요. 가볼게요 전화 오면 잘 받아요. 네.
 네. 여보세요? 예. 일일금입니다. 말씀하세요. 여기 홍익병원 앞인데요. 예. 홍익병원 앞에요. 무슨 일이세요? 아니. 저 밥을 너무 안 먹어가지고 속이 안 좋고 머리 아프세요. 아 지금 구급자 주문하시는 건가요? 네. 아 지금 여기 홍익병원 진료가 안 돼요? 아 저 큰 병원으로 가라 그래가지고. 아 큰 병원으로요? 네. 네 알겠습니다. 지금 홍익병원 여기 본관 앞에 계신 거예요? 그 안에 들어가 있어요. 아 알겠습니다. 그것도 통화할 거고요. 그 전화하면 앞으로 나오세요. 지금 본인이 머리가 아프시다는 거죠? 아 네. 제 위도 아프고. 아 네네 알겠습니다. 통화할게요. 네.
 소방서입니다. 아 네 안녕하세요. 그 저기 청담에서 그 영동대가 어디지? 여기 영동대교 넘어오는 길에. 청담에서? 네 그 오토바이 1대가 커브로다가 쭉 쓰러지고. 그 옆에 있어요? 지금 친구자가? 아니요. 저는 차여서. 네. 차가 밀려서 바로 출발을 했는데. 네 그러면 영동대를 다 건너야 돼요? 아니 그 청담에서 건너기 전이요. 그러면은 뭐 거기 뭐 청담 그 영동대교 남단 교차로 말하는 거죠? 네 맞아요. 발이 진입하기 전에? 예 진입 직전이요. 진입 바로 직전에. 오토바이 한 대가 옆에 서주긴 했는데 혹시 몰라서 전화드렸거든요. 아 친구 들어온 건 없는데 일단 차량이 많이 다닐 텐데. 아 네 차 많이 다니고 오토바이 환자가 일단 도로 중앙에 넘어졌다가 오토바이에는 저기 갓길까지 밀려가고 오토바이 그 운전자 일어나서 갓길 가자마자 다시 쓰러지더라고요. 아 그런 걸 아까 보셨다는 거죠? 네. 일단 가는 사람. 신차를 한번 가보겠습니다. 영동대교 지나기 전에 방향에는 남해에서 북쪽으로 맞죠? 네 청담에서 영동대교 바로 진입하는 구간. 진입 구간이요? 청담에서? 미니 강남 그 간판 크게 있는 거기거든요. 미니 뭐예요? 미니? 미니 강남이라고 써져요. 네 미니 강남 예. 네 거기 앞에. 그 앞에요? 네. 틀어주세요. 알겠습니다. 거기로 가볼게요. 한번 고급차한테 보낼게요. 네. 감사합니다. 네.
 119입니다. 아 예 지금 어 환자가 고통이 너무 심해가지고 지금. 환자가 거동이 안 돼서 119로 응급시 가야 되는 거예요? 제 신고 주소가 어떻게 되나요? 예 저기 만리재고 상가예요. 2차 예예 2차 상가. 무슨 상점이에요? 그럼 거기가? 미터 보쌈이요 보쌈집이에요? 예예 상가가 붙어있는 거죠? 그러면요 예예 도로변으로 보쌈집 남자분이요? 남자분이요? 남자분 먹다가 갑자기 그러신 거고 의식이 없거나 숨 못 쉬거나 이런 건 아니죠? 코로나 관련 뭐 열 기침 감기 증상 있거나 뭐 이런 거 아니시죠? 예. 네. 알겠습니다. 구청하고 있으니까 건강 준비하시고 전화하면은 위치나 상황 설명해주세요. 가고 있습니다. 예.
 야 애기. 여보세요? 선생님. 여기 3학사로 13길. 3학사로 13길이요? 네 3학사로. 우리 애기가 12월 6일 날 학생이었고 다 나와서 어저께 질병본부에서 코로나 활자를 맞아서 맞았는데 애기가 갑자기 토하고 싶다고 했는데 지금 쓰러지고 얼굴이 하얗고요 여기 지금 몇 호예요? 몇 살이에요? 네, 중학교 3학년이요 지금 의식은 있어요? 의식은 있어요. 선생님 근데 식은 땀을 너무 흘리고요. 애기가 갑자기 하얘졌어요. 하 지금 말은 해요? 네 말은 해요. 선생님. 예 그것도 보여드리니까 지금은 뭐 코로나 장학 결혼이면 확인이 되는 건 없죠? 네 없어요. 지금은. 소통할 거고요. 네. 네 여기 잠시 후에 대해서 그만 할 거예요. 조금만 기다려 주세요. 네 선생님. 예. 네.
 119입니다. 어 여보세요? 네. 안녕하세요. 여기 시범 아파트 여의도 시범 아파트 어 몇 동이지? 어 잠시만요. 옆인데요. 옆에요? 네 큰 길가에요. 그 하단 밑에. 네. 사람 쓰러져가지고 지금 그 막 발작하시고 계신 거 같아가지고 연락드렸어요. 남자분이에요? 여자분이에요? 남자분이요. 남자분이고요. 지금 쓰러졌는데 지금 경영. 흰자 보이는 거 같은데. 예예. 네. 그분 의식도 흰자 보여요? 지금? 예. 없으신 거 같아요. 지금. 네. 선생님 전화는 끊지 마시고 그쪽으로 제가 출동할 거고요. 선생님은 모르시는 분이죠? 지나가다 본 거고. 네. 네. 지나가다 본 거고. 지금 뭐. 원효대교 아래라는 거죠? 네. 원효대교 아래쪽에 그 뭐라 그러지? 그 옆으로 빠지는 길 앞에 앞이에요. 뒤에 둬 있는데. 음 네 잠시만요. 어딘지는 알 것 같고요. 잠시만요. 전화는 끊지 말고 계세요. 네 구급차는 출발해서 가고 있고 의료 지도 해드릴게요. 그 옆에 계신 거죠?
 예, 1 2급입니다. 네, 저기 지금 병원을 빨리 가야 되네요. 주소 주소 주소 불러주세요. 주소. 종로구 종로구 평창 24길 평창 평창 그냥 평창 문화로예요? 아니고 그냥 평창 평창 24길. 잠깐만요. 평창 24길에. 네 네 네 네 네 네 네 네 네 네 네 네 네 네 8장 8장 추정이고요. 하열 하열 그리고 최근에 코로나 관련해서 의심할 만한 거 없어요? 없어요. 그거는 관련 있어서. 빨리 갈게요. 접수됐고요. 예, 빨리 갈게요. 예.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네. 해봅니다. 예. 도움이 필요하는데요. 어머님이 갑자기 의식을 그러셔가지고 아 저 이거부터 불러도 있어요. 아 서울 동자포 상도로 네. 오스탕길 상도 H1 아파트 예 고급자 보냈고요. 숨 쉬나 안 쉬나 확인해 보세요. 예 숨 쉬세요. 예 의식은 없는 거예요? 예 코로나 관련된 거 있으세요? 아니요 아니요. 의식 있어요 없어요? 의식은 좀 있었는데요. 쓰러지셨어요? 아 어저께 여기 그 팔금을 2번 보셨어요. 예 의식이 좀 떨어지나요? 아 예 전화 끊지 마세요.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네, 네. 네, 선생님 11인데요. 네, 네. 신한은행이 그 타입이 있는 쪽이에요? 아니요. 그 친환은행 반대편이고요. 그 영등포 여기 1번 출입부라고 돼 있거든요. 여기 1번 출입부로 있는데 영등포요. 그냥 거기서 거기가 그 타임스케어 쪽 맞죠? 아 예 맞아요. 맞아요. 아 그래요. 알겠습니다. 네 알겠습니다. 네. 네.
 예 독산동 그거 독산 저기 독산 저기 2동 예. 그죠? 예. 몇 층이에요? 몇 회에요? 아침에 약을 먹었는데 어느 분이요? 제가요. 지금 숨을 못 실었어요. 마비가 오고 응급출로 대리생물병원으로 빨리 오래요. 응급출로 해가지고 병원은 식동원 구급제하고 상의하시구요. 코로나 관련해서 여름나기침 있으세요? 네. 네? 여름나기침 있어요? 아니요. 지금 약 먹었더니 그렇다고요. 어제 그 피곤했거든요. 병원에서. 네 알겠습니다. 그쪽은 구청 보내드릴게요. 병원은 주성구청 상의하세요. 그리고 주소가. 독산동. 예 쉬운 대로 96길. 네 구청 가라고 했으니까 좀만 기다려주세요.
 네, 여보세요? 네, 여기가 열성 경영이시고요? 지금 경영하고 있어요? 선생님? 네, 지금 이름나 뭐지? 두 번째이고. 아, 선생님 그 주소서 불러주세요. 아, 여기 주소 주소. 여보세요? 네, 주소 불러주세요. 선생님. 예, 예, 검천구 독산로. 네. 36길. 네 월드메르딘 아파트 네 구급차 나갔고요 애기 몇 개월이에요 지금? 2개월 빠지는 24개월이에요 24개월이에요? 그러니까 22개월이라는 거죠 지금? 네 선생님 일단 구급차 나가는 동안 애기 주변에 다칠만한 물건 다 치우시고요 지금 호흡하는 거 어때요? 호흡 잘하고 있어요? 호흡하는 거요? 정상적으로 하고 있어요? 아니면 숨쉬기 힘들어해요? 어 뭐 지금 호흡은 불하고 좀 잔들었어요. 그래요? 선생님 고급처 금방 가니깐요. 조금만 기다려주세요. 네. 네.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네. 수고하십니다. 여보세요? 예예. 예. 여기 환자에 있는데요. 예예예. 주소 어떻게 되세요? 여기 그 강남구 앞구정동. 예예예. 현대아파트. 현대아파트 예. 예예예. 어느 분이 안 좋으신데요? 저희 아버지거든요. 아 예예예. 여기 카톨릭 통화병원으로 갈 거예요. 의식은 있으세요? 네? 의식은 있고 말씀은 하시는 거예요? 아버님? 네네네. 아 예. 어디가 편찮으신데요? 아 저희 아버지가 입원했다가 그 소변줄을 끼고서 퇴원하셨는데요. 네 그 소변줄에서 피가 많이 나와서. 예예예 알겠습니다. 알겠습니다. 그래서 가야 되는데. 피자 관련해서 뭐 두층 간격 바로 된 상태 있을까요? 없습니다. 아 없어요? 네. 여보세요? 죄송하지만 그 사이렌 좀 꺼주고 오셨으면 되는데. 예 알겠습니다. 네 도착하시면 전화 주시나요? 예 아마 전화할 수도 있어요. 전화 잘 받아주시고. 네. 네 알겠습니다.
 네, 여기 사람이 쓰러져서요. 정신이 지금 있었거든요. 남성분이세요? 아 여성분이요. 여성분이 지금 의식이 어때요? 의식이랑 호흡 같은 건 어때요? 지금 의식이 의식이 없어요. 의식이 없고 호흡은 가슴이 오래내내락거리에요? 예예. 아 호흡을 하시고? 네. 지나가다 보고 의식을 하신 거예요? 아니요. 저희 식구예요. 식구. 아 가족이시군요? 네. 주소 좀 불러주세요. 네, 저기 성파구 5군동. 예. 예, 몇 주 몇 호예요? 예, 예. 알겠어요. 구부차 출발할 건데 그거 한번 흔들어보세요. 선생님 눈 뜨시는 반응 같은 거 있으시지? 아 예, 알겠습니다. 예, 한번 봐보세요. 한번 흔들어서. 지금 눈 뜨고 있어요? 지금? 아 눈은 뜨시고 계세요? 아 눈은 못 뜬데요. 지금. 아 호흡 가슴이 정상적으로 오르락 거리락 거시는 건 맞는 거죠? 호흡이 약해요. 호흡이 약해요? 전화 끊지 마세요. 제가 의료 상담원서 연결 드릴 테니까요. 네, 네.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 들려오입니다. 네 제가 그 한양대학병원에서 수술받고 퇴원을 했는데 제가 배를 이제 꼬맨 게 있거든요. 근데 거기서 갑자기 물이 나와가지고요. 배에서 수술한 그 부위에서요? 예. 개복은 아니고 이제 어쨌든 제가 이제 구멍을 뚫는 걸 했었는데 그거를 이제 꼬매고 제가 퇴원할 때 그거를 실밥을 푹 나왔었거든요. 아 실밥을 안 물고 나왔는데 예. 진짜 안 푼 채 이제 제가 한 2주 후에 가야 하는데 거기서 물이 나오기 시작하는 거예요. 오늘 지금요. 네. 한양자학교분 같은 경우에는 뭐 응급 전화가 따로 있는 게 아니어서 네. 제가 그 상부인과 쪽으로 제가 수술을 받은 거라 네. 상놀이 랑 연결을 좀 했으면 좋겠는데 어떤 방법이 있을까 해서요. 병원이랑 연결을 해달라고요? 네. 네. 그 상품이니까 예 그 병원 이게 연락하는 한 라인은 없어요. 아 그래요? 예 그 한양대 병원 제가 일단 아니면 구급차를 보내드릴까요? 아 어떡하죠? 이 구급차는 어떤 어떻게 사용하면 되는 거고 뭐 비용차는 비용은 따로 없고요. 네 병원까지 병원 음료수로 유송을 해드려요. 아 그래요? 제가 한양대학병원에서 어쨌든 어쨌든 아 통화를 아예 뭐 좀 할 수 있는 방법이 없으면 가야 하는 거겠죠? 예 그니까 거기서는 이제 일반 민원인 전화는 다 못 받으시거든요. 아예 안 되더라고요. 지금. 네 그럼 회원님이 바꾼 곳이라서 일반 민원 전화를 받으실 거 없어요. 네 네 네. 네 그러면. 네 네 그럼 그렇게 해주시겠어요? 예 예 주소지 알려주세요. 여기 송파구 동남로 3길 동남로 3길 잠시만요. 3길 건물 이름은 없으세요? 네 네 네. 예 고객님 그 병원은 이제 구급자랑 의논을 하시고 제가 일단 그쪽으로 구급자로 보내드릴게요. 네네 얼마나 걸릴까요? 음 선생님 거리는 1.7km 10분 안 걸리실 거고요. 지금 예 준비하시면 될 것 같아요.
 감사합니다. 네 저희 지금 아버지가 옆구리 이렇게 해서 못 이용하시는데 이거 아버지가 주소 불러주시면 구급차 보낼까요? 네 저기 미아동. 네. 잠깐만요. 집에 코로나 환자나 자가격리자 해당 사항이 있어요? 없습니다. 네, 구급차 보낼게요. 네.
 네, 여기 룩입니다. 아 예, 여기 침대에서 떨어졌는데요. 침대에 떨어졌는데 안 떨어졌어요? 아행분이 떨어졌어요? 뭐 떨어졌어요? 어 집사람이 떨어졌어요. 못 해야 돼요. 제가. 아 거동불가예요? 어디 다쳤어요? 거동불가 허리. 허리 다쳤어요. 아 엉덩이 부상이요? 예예예. 아님께서 주소 말씀해주세요. 여기 가볼게요. 응급실 가기로 하시는 거죠? 네네. 네, 주소 말씀해주세요. 수유동. 수유동 예. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
 알겠습니다. 네 여기 혹시 신귤력인데요. 신귤력이요? 네네네 신귤력 지하철인데. 네. 어떤 분이 1호선에서 5호선 넘어가는 쪽에서 에스컬레이터에서. 네. 어 어떤 할아버지가 머리를 닫히면서 피를 흘리시고 오시는데. 의식은 있어요? 네 의식은 있어요. 아 거기가 1호선에서 5호선 넘어가는 환승하는 데 쪽이에요? 에스컬레이터? 네네네. 아 네. 그러시면 꼭 머리에서 피가나요? 네. 아 예 알겠습니다. 그쪽으로 나가볼게요. 전화 좀 받아주세요. 네 알겠습니다. 예.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 아 네. 네 여기 합동역인데요. 그 머리를 좀 다쳐가지고 혹이 났거든요. 저희 신고자분 본인이요? 아니요. 그 신고분이요. 여자분이에요? 네 여자예요. 머리 쪽에 혹이 났다고요? 어떤 부터 넘어졌어요? 네 넘어졌어요. 아 그래요? 뭐 피 나거나 그래요? 피는 안 나는 거 같은데 호흡이 호흡 좀 커요. 호기가 그래요? 지금 합정역 어디 쪽이에요? 합정역 10번 출구 쪽이요. 10번 출구요? 네. 그 앞으로 가면 돼요? 네. 예 알겠습니다. 혹시 친구분 열이나 기침 코로나 관련 사항 있어요? 아니요. 없어요. 예 합정역 10번 출구 갈 테니까 거기 전화 받으세요. 네. 예 출구 앞에요. 네. 네. 감사합니다.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네. 여보세요? 여보세요? 아 예 저희 고급차 가고 있는데요. 네. 지금 밖에 나가 계신 거예요? 아니 안 해요. 근데 몸을 못 하셔서. 아 그래요? 술 많이 드셨어요? 네네네. 예 알겠습니다. 저희 빨리 가라고 할게요.
 네 여기 주소가 강원대 정문 앞인데요. 강원대 대학교. 네. 그 노인분 한 분이 쓰러져 있어 가지고 일어나지는 못하세요. 남자 여자요? 남자분이요. 근데 몸이 좀 안 좋으신 것 같은데. 남자분이 쓰러져 있다는 거요? 네. 네 의식이 있어요? 네 약간 의식은 있으신데 몸이 어딘가 안 좋으신 것 같아요. 지금. 차 나가볼게요. 여보세요? 예 차 나가볼게요. 병문 앞으로 가볼게요. 아 이거 여기가 어디였네요. 하늘간 아 이것도 아 여기 주소가 어떻게 하는 거야. 병문 앞으로 가볼게요. 안내 좀 해주세요. 네 전화 받아서. 네. 감사합니다.
 괜찮은 거야. 원래. 아 네 저희 Y2가 30 30 어 6주인데요. 양수가 계속 틀려가지고. 예. 구급차 보여드릴까요? 네. 주소 알려주세요. 네 저기 신월 시영 아파트고요. 신월 시영 아파트요? 네. 예 몇 동 몇 네 알겠습니다. 출동 잠깐만 끊지 마세요. 네 뭐 괜찮은데요. 네. 네. 네. 네. 구급차 출동했고요. 가는 도중에 의료지도 연결 한번 해드릴게요. 네. 괜찮아요.
 여보세요? 예 말씀하세요. 예 사람 떨어져가지고 여기 도봉로 114 도봉로 몇 길이에요? 도봉로 114 길이요? 예. 지금 써야 돼 빨리 오라고요 예 알겠어요 뭐 때문에 그러세요? 아 사람 써야 돼 지금 와이프가 아 지금 의식이 있어요 없어요? 없어요 지금요 의식 없어요? 네 숨을 쉬어요 안 쉬어요? 아 지금 쓰고 있는거 같아요 빨리 오라고요 그니까요 지금 어떻게 다 자자세요 지금 제가 하나부터 여기까지 아 예 가고 있고요 몇 층이에요? 지금 내가 있을게요 이 층으로요 아 알겠습니다 전화오면 내려오세요 감사합니다.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 아 네 여보세요? 그 여기 도로에 예 남자분이 계시는데. 네. 쓰러져 계세요. 근데 고동을 아예 못하셔가지고. 알겠습니다. 구급차가 빨리 가보고요. 젊으신 분인가요? 아니면 뭐. 연생만 좀 드셨는데 이러다가 여기 이렇게 차 지나가면은 쉬실 거 같아가지고. 저희가 빨리 가보겠습니다. 감사합니다.
 아 네 저희가 그 자하문로 저희 직원분이 지금 갑자기 움직일 수가 없어가지고 몸이 좀 안 좋아져서 위급실을 좀 가야 될 것 같거든요. 네 주소가 어떻게 돼요? 예 자하문로 7길 자하문로 몇 길이요? 7길이요. 7길 네. 시장이고요. 네. 환자는 다리 보행은 가능해요. 근데 상체가 다리여서 움직이질 못하고 입을 시간이 없어서. 남자분이에요? 네. 남자분이고 지금 어디 쪽이 아프다는 거죠? 오른쪽 어깨가 벌렸는데 점점 숨차고 힘들어하더라고요. 보행은 아직까지는 보행은 가능해요. 여름이나 교체 뭐 코로나 관련 사항이 있어요? 그거는 아니고요. 얼마 전에 저 병행외과 가서 다 치료는 받고 있었는데 오늘 상황이 더 심각해진 거예요. 네 알겠습니다. 좌암로 출기 네 전화 잘 받으세요. 네
 네, 알겠습니다. 아 네, 다름이 아니고 지금 그 어 아는 형 1명이 신장이 지금 빨리 뼈가지고 지금 빈 맥이 와가지고 잠시 이렇게 누워있는데 어 그 복용했던 약이 이제 다이어트 보조제랑 이제 조증 약을 좀 복용을 했었어요. 네 그리고 나서 지방감이랑 이제 고혈압도 있고요. 그런 상태에서 이제 카페인을 복용을 했었는데 갑자기 심장에 무리가 와서 그런지 지금 170까지 심박수가 올라갔다가 지금 120까지 떨어졌는데 지금 계속해서 심박수가 그 이하로 떨어지질 않고 있어요. 선생님 말씀 중에 죄송한데 지금 의료 상담 요청하시는 거예요? 아니면 구구차로 요청하시는 거예요? 어 의료 상담을 요청. 어 어. 의료 상담이요? 혈압을 좀 재고 싶어서. 아 혈압을 재고 싶다고요? 네네네네. 잠시만요. 주소가 어떻게 되시나요? 어 마포구 대흥동. 네. 앞으로 오시면 제가 그 나갈게요. 앞으로. 네. 네 알겠습니다. 수정에서 확인해 볼게요. 네 감사합니다.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 예. 여보세요? 일구성 하시고 이렇게 뭐 위층 관계 2층 주민 때문에 신고하신 게 하나 있으시죠? 예예예. 현관문은 열렸어요? 안 열렸어요? 그 집? 열려 있어요. 아 혹시 뭐 쓰러지는 사람이 보여요? 아니면? 보여요. 아 미동은 없으시고? 예예. 많이 좀 건드려붙지는 않았는데. 아 예 알겠습니다. 저도 나아보겠습니다. 예. 예. 도착 안 했죠? 예? 경찰 제가 도착 전이죠? 예예. 알겠습니다. 차 나가 볼게요. 예.
 여보세요? 예 여기 119 상하실인데요. 네네네. 선생님 그 화단실 문은 열려 있는 거예요? 아니요. 그 문도 저희가 열어야 되는 거예요? 주광장. 예 안에서 열어줄 수 있는 거예요? 네 들어갈 수는 있는데. 그 안에서 화단실 문 열어줄 수 있는 거예요? 개인 그 1칸 그 본인 칸만 닫아놓은 거예요. 그니까 거기로 열 수 있냐고요? 아 그거 못 열는 못 열 거 같은데 그 안에서 안 열고 안에서 안 열고 계신 거예요? 네, 네, 네, 울면서 있어서 문을 못 열면은 저희가 한번 해볼게요 잠시만요. 네 한번 여쭤보세요. 네, 괜찮으세요? 네. 아 저기 괜찮다고는 하는데 되게 오랫동안 되게 고통스러워하면서 울고 있었거든요. 아 그래요? 일단 알겠습니다. 대답을 하신다 이거죠? 네 네 네 네 네 네. 사람이 가니까 또 조용히 있는 척해요. 아 그래요. 알겠습니다. 네.
 네, 이리구입니다. 여보세요? 네, 말씀하세요. 네, 여보세요. 어머니가 저 타박성을 이겨가지고 병원에 가야 되는데 좀 일려고 출장하십시오. 누가 본인이 아프신 거예요? 아니요. 어머니가. 어머니가 어디가 어떻게 아프신 거 넘어지셨어요? 네, 너무 머리가 좀 깨지셔가지고. 머리에서 피가 나고 있어요? 예, 환불 나가지고 지금 꾸메여 꾸메 거예요. 꾸메야 돼. 출장하고요. 주소 좀 알려주세요. 여보세요? 어 방화대로 공동 방화대로. 강서구 방화대로. 몇 층이에요? 유원 펠리츠예요? 유원 펠리츠. 예예예. 혹시 어머니가 열이 나거나 코로나 관련 증상이 있으세요? 아 코로나 관련 없는데 예방은 안 안 하셨어요. 코로나 확진자 아니시고요? 예예 코로나 확진자가 아닌데. 이건 필기체. 교통하겠습니다. 예예예.
 네. 여보세요? 네. 아 한 저기 제가 아 먼저 번에 아 얼마 됐지? 고객님께요? 고객님. 네. 여기로. 네. 전화 제가 바꿨는데요. 네. 이석증 이석증 이석증이 돼가지고 먼저는 왜 그런지 못하든 죄송하고요. 예. 이미 대차고 이제 한옹진 동원에서 이렇게 해서 좀 계속해서 나와서 이렇게 하고. 코로나 관련된 거 있으세요? 예 주소 알려주세요. 여기 주소? 네. 네. 중구 다산동. 네. 다산로. 예. 32번 길. 예? 예. 32번 길. 남산타운 아파트예요? 그렇죠. 몇 동 몇 호요? 네. 아 예. 고급차 요청하시는 거예요? 네네. 아 예. 알겠습니다. 네.
 네, 일곱니다. 예, 지금 제가 팔 다리를 못 쓰고 있거든요. 왜요? 어디가 붙여서요? 아 그냥 모르겠어요. 지금 어쨌든 늦지를 못하고 서 있어 있지를 못해요. 지금. 그니까 팔 다리 양쪽 다 못 쓰고 계신다고요? 뭐 뭐 마비가 있는 거예요? 예, 예, 예. 마비가 있는 거예요? 사지가? 네네네. 네네네. 아, 잠시만요. 주소 좀 알려주세요. 보급자 요청하시는 거죠? 네. 네 주소요? 음 석영 정성북구 석영로 2길 네. 서양 아파트 네 네 네. 뭐 뭐 하시다고 하신 거예요? 선생님? 네? 뭐 하시다고 그렇게 아프신 거예요? 그냥 갑자기 그랬어요. 어저께 아프고 싶어서. 아 갑자기 그래요? 뭐 코로나 관련해서 열이나 기침 호흡 곤란 같은 건 없어요? 네 그런 건 없어요. 그런 건 없고 네 알겠습니다. 선생님 두 번째 보냈어요. 네

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네 선생님입니다. 어 네 안녕하세요. 네 네 선생님. 네 네. 다시 손톱을 깎다가 네 살을 찝었어요. 예 살 찝어가지고. 예. 찝어가지고. 예 선생님 지금 병원 가보시겠어요? 예 지금 병원 가보시겠어요? 그래서 이거 병원에 지금 가야 되는데. 그래서 음식. 응급사 거는 안 되는 거죠? 응급실이요? 네. 응급실은 다 안 되는 건 아니에요. 뭐 열이 있거나 하신 경우에 안 되시는 거고요. 네? 열이 있거나 호흡기 증상이 있는 경우에 안 되시는 거고요. 네. 고급차 보내드릴까요? 네? 고급차요. 그러니까 응급차를 하는 게 나을까요? 왜냐하면 제가. 예. 아이 체험 힘드시면 고급차 타고 가시고요. 네? 네? 아이 체험이 힘드시면 고급차 보내드릴게요. 고급차 보내드리는 게 나을 것 같아요. 예. 그 주소 알려주세요. 네. 그 운전차 부르면은 뭐 저희가 뭐 비용 부담 같은 걸 해야 되는지. 없어요. 선생님. 그 병원비만 있어요. 병원비만 있어요. 병원비만 있어요? 예 선생님 아이 많이 아픈 거 같은데 교재를 안 써 알려주세요. 저기 여기 구로 산동에 한신 1 플러스 잠시만요. 선생님 아이 몇 살이에요? 선생님 아이 땜에 아이 울음소리 때문에 잘 안 들려요. 아이 몇 살이에요? 아 애기가 그 아직 돌이 안 지났거든요. 아 아직 애기예요? 돌이 안 지났어요. 기억이 안 들어요. 예 지금 문자 보내드릴게요. 잠시만요. 네 전화 끊으셔도 돼요.
 예 여보세요. 저기 저희 애기 아빠가 술 먹고 저 바깥에 한 대에서 조금 자고 집에 왔는데 저거 지금 소리 지르고 정신을 조금 물러놓은 것 같아요. 병원 가야 될 것 같아요. 몇 층이에요? 도로까지. 고호차 갔고요. 지금 남편분 나이 때는요? 예. 지금요. 62년생이요. 62년생이시고? 예. 지금 뭐 그 고호차 갔는데 몇 가지만 더 물어볼게요. 지금 의식이 없어요? 의식은 있어요. 있는데 절대 소리 질러요. 의식은 있는데 소리 지른다고요? 네. 소리 지르고 그리고 호흡은요? 호흡은 괜찮은 것 같아요. 근데 지금 막 정신이 없는 것 같아요. 아 일단 알겠습니다. 일단 부서에 가고 있으니까 전화 잘 받으시고요. 예예예. 최근에 뭐 콧나 관련해서 뭐 치킨 가래 콧물이나 뭐 확진받으신 거. 그런 건 없고요. 혹시 당뇨 같은 거 있어요? 당뇨. 당이 조금 있어요. 아 당뇨 당뇨 있다고요? 예 이제 당뇨 약 먹어요. 네 알겠습니다. 일단 확인 체크는 안 해보셨죠? 지금. 예예예. 네 알겠습니다. 일단 잘 받으세요. 예예.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 119입니다. 말씀하세요. 아 그 카드 좀 배워서 그러는데요. 주소가 장승배기로 여기서 한번 출동해 주셨으면 해서요. 몇 층 몇 터로 가면 돼요? 아 그 길에서 할 게 없어요. 길에서. 아 네 알겠습니다. 일단 빨리 한번 나가볼게요. 그 환자 여지나 기침 이런 증상 있나요? 코로나 관련해서? 아 아니 그런 건 없어요. 아 네 선생님 확인이 다치신 거죠? 아니 아니요. 딴 사람 우리 일하러 온 사람이. 네 알겠습니다. 조금만 기다려주세요.
 119입니다. 혹시 방화 11단지 119 접수된 거 있나요? 방화 11단지 쪽이요? 네. 잠깐만요. 선생님이 계신 곳 위치랑 거의 똑같은 거 같은데요. 뭐 재난 사항은 지금 접수된 건 없습니다. 아 접수된 거 없어요? 네 선생님 쪽에서 위치가 맞는데 뭐 어떤 사항이 있으세요? 네 할아버님이 부르셨는지 머리도 피곤하세요. 아 저희가 나가서 도와드릴게요. 그러면. 아 네 알겠습니다. 예 몇 동 몇 호로 가야 돼요? 그냥 입구 앞이거든요? 할게요. 할아버지 음식은 괜찮으세요? 네 지금 앉아 계세요. 일단은. 머리가 피가 흘러가지고. 앞으로 구급차 조통해 볼게요. 네.
 여보세요? 예 119인데요. 예. 머리 아프다 신고하신 분이에요? 예예. 위치 어디예요? 주소 집에 계신 거예요? 예 지금 집인데요. 어 내가 여고 이사 왔고 이 주소를 잘 물었는데. 그러면 그 문 앞에 나가면 주소 다 써 있어요. 요즘에는 숫자 그것 좀 불러주실 수 있어요? 문 앞에 나가면요? 아 숫자 붙어 있잖아요. 건물 앞에 그 파란 색깔로 숫자 크게 붙어 있는 거 있잖아요. 쇠로 된 거. 예예예. 뭔지 아시죠? 뭐 말하는지 제가. 예예. 예 숫자 그거랑 글씨랑 다 불러주시면 찾아갈 수 있거든요? 이게 어딨냐면요. 나도 이거 이사 없고 위치를 잘 모르거든요? 그리고 저기 가만히 있어봐라 이게 어디냐면 고대병원에 가자면 그 정문 있죠? 어 그거 대하약국이라고 거리로 오세요 그러면 내가 그리로 나갈게요 대하약국? 예 정문 앞에 대하약국이 있어요? 저기 고대병원 정문 앞에 대하약국? 예 내가 그리로 나갈게요 대하? 예 대하. 대하 약국? 예. 거기 있어요? 검색이 안 되네요. 대하 약국은? 대하 약국인가? 대하 약국은 검색이 안 돼요. 대하 약국도 아니죠. 일단 정문 앞에 있는 약국이 있다는 거죠? 그쪽으로 오신다고? 예예. 가까워요? 아 저기 저기 고대병은 정문 앞에 내가 나갔어요. 아 금방 나올 수 있어요? 가까워요? 예 예 예 예 예. 아 그럼 거기서 기다리세요. 병원 가시려는 거죠? 예. 아 알겠습니다.
 예, 일요구입니다. 네, 안녕하세요. 저희 아버님이 3차 그 백신 맞으시고 몸이 조금 안 좋으셔서. 아, 공항이 좀 안 좋으셔서요? 네, 네. 어디가 아프신 거예요? 뭐 어지럽고 뭐 그러신 건가요? 네, 그 속도 안 좋으시고 머리도 아프시고 네, 정신적으로 네, 공항 공항이랑 이제 그런 것도 조금 오셨거든요. 공항장 장애 증세도 살짝 보이시고. 네, 우울증 우울증도 있고. 주소가 어떻게 돼요? 서울시 강서구 화곡 2동 예. 네. 그리고 1광 월드메이션 1광 월드메이션 네네네. 아 알겠어요. 아버님 뭐 알겠습니다. 부착 보내드릴게요. 재원들. 네. 감사합니다. 전화드릴 수 있어요? 화곡동에서 남아있죠? 예. 네.
 119입니다. 아 네 여기 지금 길에 사람이 쓰러져서 신고하려고 그러는데요. 여자 할머니요. 할머니 의식은 있어요? 네 의식 있어요. 아 의식 없어 보여요. 의식 없어 보여요? 거기 주소가 어떻게 돼요? 선생님? 여기 여기 도로 표시권 보니까 영등포로 72길 거리 사이요. 영등포로 72길에 이 사이거든요? 아 일단 수육현이 잡는데 차 나갔고요. 팬이 좀 앞에 계시다는 거죠? 네 바로 팬이 좀 있죠. 할머니님 혹시 이렇게 보면 숨을 쉬고 있는 것 같아요? 네 살짝 움직이시는데 피를 좀 돌리세요. 어디서 얼굴에서요? 모르겠어요 저희가 지금 차라서 아 그래요 알겠습니다 제가 나가서 확인할게요. 네
 119입니다. 네 여기 111동. 네 어머님이 좀 몸이 좀 안 좋아서 그런데 115 차 1만 보내주실 수 있나요? 어디가 안 좋으신데요? 어머니? 그냥 몸이 안 좋아요. 지금 좀. 뭐 의식은 있나요? 네. 아 뭐 전체적으로 안 좋으시단 말인가요? 아 좀 어질렀고 그래요. 아 네 열나거나 기침감. 원래 약간 내경색이 좀 있어서. 네 코로나 격리 중이신 거 없으시죠? 연락은 한 지침 감지 증상이나. 네 코로나 증상은 없어요. 아 격리 중이신 것도 아니시고요? 네 알겠습니다. 바로 보내드리고요. 여기 몇 층으로 가면 되나요? 여기 좀 안 집이 안쪽이라. 네 전화 오면 잘 받아주시고 그런 거는 고급대원한테 한번 설명해 주세요. 전화드릴 거에요. 네 네.
 네, 1 2 5 입니다. 네, 여기 상파를 맞았었는데요. 지금 몸이 너무 가볍고 충만 없이 됐다는데. 좀 와주 어찌했네. 누가 그런 거예요? 저기 우리 이모가요. 언제 맞은 거예요? 며칠 2 3일 된 거 같은데요. 주소 알려주세요. 네? 주소요? 주소요? 강북구 주공 5단지 건동 주공 5단지. 네. 네. 거기 강북 소방서 바로 뒤에 있는 거 맞나요? 네네네. 강북 소방서 바로 뒤에 있는. 예. 구급차 보내고 응답처치 부서 연결할게요.
 네, 저기요. 저희 지금 아버지가. 네네. 계단에서 넘어지셔갖고. 네, 지금 뭐 의식이 없으세요? 아니요. 아니 그 그 정도까지는 아니시고요. 네, 선생님. 병원을 병원에 가봐야겠는데. 아, 위치 좀 알려주시겠어요? 네, 여기 강북구 번 2동. 번 2동이요, 선생님. 네. 주공 아파트. 주공 아파트. 예예예 계단에 계신건가요 집에 계신건가요? 아 지금 집에 집에 오셨어요 네 저희 잠깐 검색좀 해볼게요 선생님 강복구 번역 혹시 주소를 다 불러주실 수 있으실까요 선생님? 번동 주공아파트 OO라고 하면 안나오나요? 거기가 강복구 맞으세요 선생님? 네 맞으... 5단지인가요 주공아파트 선생님? 예예예예 위치가 아예 전혀 안나와서요 선생님 한성운수 버스 뒤쪽에 있는 아파트인데. 제가 검색을 해보고 말씀드릴게요. 선생님 잠깐만 전화 끊지 말아주세요. 예. 네 찾았어요. 선생님 그 번동주공 아파트 맞으시죠? 네 그쪽으로 차 보내드릴 거고요. 선생님 차 출발했고요. 혹시 코로나 관련해서 해당 사항 있으실까요? 아니요. 없어요. 3차까지 다 맞으셨어요. 네 알겠습니다. 선생님 저희 구급차 출발했고요. 전화 좀 잘 받아주세요. 네 알겠습니다.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네, 옵니다. 아 제가 길 앞 3분 거리인데요. 집 앞이라고요? 네, 3분 거리인데요. 제가 너무 추워서 그런지 모르는 게 지금 도저히 지금 다리가 마비된 상태여가지고 지금 걸을 수가 없어가지고 길거리에 지금 무릎 꿇고 도저히 앉아 있는 상황이거든요. 다리가 안 움직인다고요? 네 다리가 안 흔들겨서 아 쭈그려 앉아 있는데 이게 걸을 수가 없으면 부착해 주셔야 필요한데요. 그 일단 주소 주소 어떻게 될지 아실까요? 아 남부순간료요. 여기 집원 앞이라는 거요? 길가? 네. 잠깐 뭐. 저 몸이 마비된 거 같이 다리가 붙어가지고요. 네 알겠습니다. 저희 갈 테니깐요. 기다려 보세요. 고객님. 혹시라도 좋아지시면 다시 전화하세요. 그 언제쯤 도착할 수 있나요? 여기 과신민역이거든요. 저희가 남곡에서 출발했으니깐요. 그 10분 15분 이렇게 걸릴 것 같아요. 기다려주세요. 네 알겠습니다.
 여보세요? 예, 신부자분 저희가 도와드리려고 하잖아요. 그 간판 다른 거 하나 불러봐요. 소술대문이고요. 그니까 소술대문 말고 다른 거. 버금세우. 예? 버금세우. 버금세우. 버금세우 앞이에요? 예? 거기 앞에 그 어디가 아파요? 지금. 아 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 저 예. 예 알겠습니다. 지금 나가 볼 거고 코로나 확진 된 적 있어요? 없어요? 없어요. 저 주소 삼색한지 맞아서요. 예 알겠어요. 지금 나와 볼게요. 예. 감사합니다.
 감사합니다. 무슨 일이세요? 그 저희 장모님이. 네. 그 잠이 하신다고 수면제를 드셨는데. 네 수면제를 많이 드신 건가요? 그러니까 이게 몇 알을 드신지 몰라요. 어저께 수면제를 약을 받아오셨다고 하는데. 신경 안 면적. 의식 있으신 건가요? 아니 지금 흔들어서 막 깨우는데. 네. 약간 새근새근 코는 보시고 약간 움찔이네요. 아 통증에만 반응한다는 얘기신 거죠? 선생님 그 위치 알려주세요. 구급차 보내드릴게요. 네 여기가 대체 아파트 네 잠시만요. 네 몇 동이세요? 맞으시죠? 선생님? 네. 네. 네. 네. 네. 그쪽으로 구급차 보내드릴게요. 선생님 같이 계시는 거죠? 네 지금 여기 아침에 제가 보관한 게 한 10시쯤인 것 같아요. 제가 통화하고 나서 하나씩 계시라고 그랬는데 지금 와 보니까 지금 약이 약통이 다 비해 있어서 이게 얼마큼 뛰어진지 모르는데 흔들어 깨어도 안 일어나요 지금. 그러니까 저희가 직접 일단 지금 보급대 그쪽으로 출발했어요 선생님. 네네네 알겠습니다. 혹시 전화 끊지 마시고요 코로나 관련해서 뭐 확진자 접촉하거나 해당 사항 있으실까요? 없습니다. 없습니다. 그 선생님이 같이 계시는 거죠? 문 열어주실 수 있는 거죠? 네 네 여기 앞에 있습니다. 저희가 문 여실 수 있는 거죠? 선생님? 아 예 예 그러면 여기 같이 있고 여기 집사람도 같이 있고 장인원은 같이 있고. 네 네 알겠습니다. 고급차로 출발할 거예요. 선생님. 저희가 친절히 가면서 전화를 걸 거예요. 전화 좀 잘 받아주세요. 예 알겠습니다.
 119입니다. 예 여기 그 누랑진 2동. 잠시만요. 누랑진 2동. 예 예. 예 몇 층이세요? 네, 무슨 얘기신가요? 그 할머니가 넘어지셔가지고요. 네. 곤립하게 병원 좀... 아, 지금 거동이 전혀 안 되시는 거예요? 예, 예, 그랬습니다. 아, 혹시 집 안에서 넘어지신 거예요? 예, 화장실에서 넘어지신 거예요. 아, 그래요? 의식은 다 있으시고요? 예, 예, 감사합니다. 구급차 나갔고요, 선생님. 할머니 혹시 지금 열나거나 감기 증상 있으세요? 그런 건 없어요, 저는. 그런 건 없으시고? 격리 상태 아니시고요? 예, 예. 아, 구급차 전화드릴 거예요. 전화서 다 들을 수 해요. 예. 감사합니다.
 네, 일부러. 예, 강원 소방입니다. 들어갔나요? 예, 예, 들어갔습니다. 예, 서울 용산구 쪽 신변 확인 요청 건입니다. 예, 여보세요? 예, 신고자분 말씀하세요. 네. 용산구 용산동 2가. 네. 다시 한 번만 말씀해. 네, 맞아요. 맞아요. 친구가 뭐 남자친구분이에요? 전 남친이요. 남자친구 전 남친 남자친구분께서 지금 수면제를 복용 먹었다고 이렇게 연락이 왔다 이거죠? 남자친구 성함이 어떻게 되세요? 네. 핸드폰 번호 불러줄 수 있어요? 소방차 그쪽으로 한번 나가볼게요. 네. 네. 네.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네. 알겠습니다. 잘 몰라야지. 네. 말씀하세요. 신고자분. 네? 말씀하세요. 신고자분. 예예예. 지금 차를 개가 아파가지고. 좀 늦건줄 모르겠는데요. 여기 월계 주공 아파트인데요. 네. 월계 주공 몇 동 몇 호예요? 월계 주공. 아내분이 배 아프시데요? 예예. 의식이랑 호흡 있으시고 코로나 확인 는 적 있어요? 아니요. 예 알겠어요. 월계주공. 예예예. 예 알겠어요. 나와 볼게요. 예. 감사합니다.
 예, 일구부다. 예, 여보세요? 예, 말씀하세요. 예, 저기 다름이 아니라 허리 쪽이 너무 심해서 아파서요. 누가 그러신 거예요? 아, 저기 저희 신랑인데. 뭐 지금 구급차가 구급차가 필요해서 전화 주신 거예요? 예, 그 계단을 내려갈 수가 없어서. 예, 주소 알려주세요. 네, 관악 남부 순환로 202길. 자, 남부 순환로? 202길. 네네. 지금 몇 쪽이세요? 하이빌 하이빌로 금액이 맞을까요? 네네네. 코로나 관련해서 여쭤볼게 하나 남았어요. 최근에 가족분 포함해서 지친 코로나 관련 증상 여행역 특이사항 있으신가요? 아니 없습니다. 네. 그래도 출동합니다. 전화 받게 되시면 다시한번 안내해주세요. 차 나갑니다. 네. 감사합니다.
 네 119입니다. 여기 잠원동이요. 예. 예 그런데요. 환자가 지금 있어서 서울대 5일 날 예약이 돼서 미리 지금 와 있었는데 상태가 안 좋아서 지금 글리 가려고 그러는데 돼요? 서울대로? 응급실 가보시려고 하시는 거예요? 네네네. 아 일단은 선생님 병원은 그 구급 대환인 환자분 상태 확인하고 그 병원 선정하게 되어 있어서 무조건 아니 왜냐면 차트가 차트가 거기다 있어서. 네 일단 말씀 좀 들어보세요. 일단 무조건 그쪽으로만 갈 수 있다고는 말씀을 못 드리고 일단 저희가 가서 확인을 해봐야 돼요. 그 환자분이 남자분이 여자분이에요? 여자분이요. 여자분이시고 어디가 불편하신 거예요? 장이 외식용을 해서 저기 저 검사를 뭐 저 조직권. 했던 지금 상태가 하얗고 피를 쏟아서. 아 뭐 여자분이 배 아프시다는 거고 뭐 피똥을 쏘신다는 거예요? 그렇지. 아 예 알겠습니다. 일단은 예 전문정 구급차 가볼 거고 환자분 최근에 발열이나 코로나 관련 사항 있으셨어요? 없습니다. 예 알겠습니다. 그쪽 구급차 가볼게요. 선생님 의식은 있으시죠? 환자분 지금. 예예예. 리치빌 맞아요? 리치빌? 아니 리치빌 옆에 재산 빌딩. 재산 빌딩. 네네네. 네 알겠습니다. 그쪽 빨리 가볼게요. 네. 네.
 네. 네. 봅니다. 아 네. 혹시 구급차 좀 보내주실 수 있을까요? 아기 애기 애기가 네? 주소 알려주세요. 여기가 서울시 뭐지 관악구 중앙동이고요. 어어 갈까? 중앙동. 네. 파크 셰르빌이에요. 네. 올해 8살 된 남자이거든요. 네. 배가 아프다고 해서 지금 보라매 전화는 했는데 진료는 받을 수 있다고 들었거든요. 일단 저희 나가보고요. 병원에 보라매병원 갈 수 있을지 없을지는 몰라요. 현장 구급변이랑 다시 말씀 나눠보세요. 네. 차 지금 나가고 있고요. 중앙동. 네 맞아요. 네 맞아요. 파크 세르빌 200. 확진된 분 없으시죠? 네네네 검사 받았고 음성이라고 그랬어요. 네.
 119입니다. 네 119죠? 네. 저기 치매 환자가 한 3일가량 아예 식사가 안 되고. 네. 아직 잠도 못 주무시고 해서 응급실에 가서 뭐 진정제라도 맞고 수액을 맞으셔야 일단 생명 유지가 될 것 같아가지고요. 그 보동이 안 되시고 뭐 이제 항모성 이런 환각을 보는 증상이 있어서 그게 될 도움을 받아서 병원에 가야 될 것 같아서요. 아까 그 남자 분한테 여쭤보긴 했었거든요. 아 주소 확인하셨어요? 선생님? 주소 불러주시겠어요? 네. 혹시 환자분 지금 열나거나 감기 증상 같은 거 있으세요? 아 할아버님이요? 그런 거 전혀 없고요. 백신 3차까지도 아쉬웠어요. 아 저희 대원들 전화드릴 거고요. 저희 응급실로 갈 건데 그 응급실에서 단순히 그냥 수행만 맞는 건 안 될 수도 있어요. 참고하시고요. 네. 어 부급 때 전화드릴 거니까 전화 좀 더 받으세요. 네 선생님 근데 그 수행만 맞는다는 게 안 된다는 게 어떤 뜻입니까? 응급실은 당장에 지금 필요한 응급 진료를 보는 곳이라서 네. 수행만 받고 싶어요 하면 아 진료. 아 뭐 그런 뜻은 아니고요. 이제 지금 생명의 연결 연장이 돼 있잖아요. 체중이 3일 사이에 뭐 7 8% 가까이 빠졌거든요. 아 지금 의식은 다 있으신 거죠? 환자분? 의식은 있으신데 이제 환자도 보셔서 뭐 전혀 그런 게 안 되거든요. 아 그래요. 알겠습니다. 그런데 금방 가니깐요. 좋은 걸 준비하고 계세요. 예 감사합니다. 네.
 여보세요? 응 지금 어디 아파요? 응 어디가 아파요? 응 엄마는 어디 있어요? 엄마? 응 응? 하하하 오 응 예 알겠습니다 가서 확인해 볼게요 거기. 예 알겠습니다 가볼게요. 예.
 네. 1등급 입니다. 애기가 경기를 치고 지금 그래서 거기 가야 될 거 없거든요. 손이랑 다 말려가지고요. 네. 지금 빨리 와주시겠어요? 네. 차는 출발시켰고요. 지금 애기 경련한다고 그 서울대 저 수학과. 네. 그리고요. 네 그랑빌 아파트요 네 맞아요 네 5살 아니 3살이에요 지금 혹시 열나요? 네 열나요 소방관들 나와있고 간혹은 저희 의사선생님 연결할 거예요 네? 의사선생님 연결할 거예요 차 안출발을 주셔서 네 잠깐만요 의사선생님 연결합니다 네네
 네. 169입니다. 네. 169입니다. 네. 여기 용광지구대 경찰관인데요. 아 예. 선생님. 네. 지금 주치자 1분이 보호 조치가 돼 있는데 계속 몸을 떠시면서 이렇게 누워 계시거든요. 저 용광지구대 안에 계시는 거예요? 네네. 맞습니다. 용광 주민센터 옆에 있는 거가 용광지구대인가요? 네. 맞습니다. 주민센터로 붙어있는데요? 남자분이요? 네네. 혹시 저 들어오실 때 체온 체크 해보셨나요? 네. 열은 없었어요? 네. 열은 없었습니다. 네. 알겠습니다. 수강을 나와 볼게요. 네. 예. 고생하십시오. 네.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네, 알겠습니다. 네, 알겠습니다. 여보세요? 예, 예, 네, 도착이죠? 지금 여기 미래 미래고시원에 계신 거예요? 예, 예, 예, 그런데 이제 제가 왜냐하면 그 경찰서고 있잖아요. 예. 경찰서고로 가서 좀 기다려 말라고. 지금 본인이 다리가 없으신 거예요? 그 저기 저거 두 번째 발가락이 장려가 있어가지고 좀 이거 좀 문제가 있는 것 같은데 아 그거 일을 못 하겠어요. 일을. 네, 일을 보시면 여기 지금 몇 층에 있는 거예요? 네? 예, 예, 예, 예. 코로나 상황이다. 네, 전자 번호 좀 하다가 그거 와야죠. 예, 코로나 관련된 건 없고요? 아 그거는 저기 저거 그 사탈 수 또 다 있고요. 아 네, 네. 아 예 알겠습니다. 수고할게요. 예.
 잠깐만 앉아서 봐. 아 앉아서 봐. 여보세요. 119입니다. 네. 네. 고 앉아서 봐요. 네 아까 전화해 준다는데. 네. 구급자가 필요한 거네요. 구급자가 필요한 거예요? 아니요. 선생님 소리 취해가지고 지금 전주로 왔다 갔다 갔다 이제 집에 좀 보내줘야 돼가지고 좀 막 저 중앙선 넘으러 갈라고. 구급차 갑자기 다 주거세요? 구급차요? 네? 구급차? 네 해가지고 집에 좀 보내줄까 하거든요. 지금 소리 취하지 중앙선 막 전달리고 해요. 전주로 왔다 갔다요. 네 알겠습니다.
 네. 여기 자양동 자양동 몇 층이 어떠세요? 네, 무슨 일이세요? 네, 애가 아픈데 어제 체험생활도 계속 닦거든요. 네. 근데 얼굴색이 똑같고 사람의 비용무처럼 살이... 그래가지고... 네, 지금도 계속 배가 아프신 거예요? 네, 배도 아프... 네? 네, 배도 너무 아프고 네. 그니까 상황이 나아질 생각보다 해서. 예 알겠어요. 고객차 보내드릴게요. 뭐 코로나 증상 같은 건 없으셨죠? 평소에. 예 없었어요. 예 알겠습니다. 조금만 기다리세요. 네.
 예 119입니다. 네 신고자분 잠시 기다리세요. 주인님 경기 부품입니다. 이관됐나요? 네 들어갔어요. 네. 여보세요? 예 119에 서울인데 말씀해 보세요. 예 그 출동 요청 때문에 전화를 드렸는데요. 예 대림동인가요? 예 대림동. 예. 아 잠깐만요. 네 네 네 저희 아이가 그 자해를 하고 하는 습관이 있는데 네 친구랑 통화를 했는데 자해를 했나봐요 근데 치고 안 먹는다고 이렇게 예언을 했어요 남자아이에요? 네 남자아이 남자아이 남자아이 이름이 뭐예요? 섬인이에요 아 성함 성함은 어떻게 불러주실까요? 그쪽으로 가볼게요. 그리고 그 그니까 혼자 계신 게 아니라 친구랑 같이 계신 거죠? 아니 혼자 있어요. 혼자 혼자 혼자 있는데 혼자 있는데 저기 친구랑 통화를 이제 기인하고 통화를 했는데 그러면 아드님 잠깐만요. 아드님 전화번호 좀 1 불러줄 수 있어요? 전화번호. 전화번호 잠깐만요. 잠깐만요. 나가볼게요. 여보세요? 그쪽으로 나갑니다. 대원들. 그쪽으로 나갑니다 대원들. 출동했어요.
 네 119입니다. 여보세요. 119입니다. 말씀하세요. 말씀 없으시면 통화 종료하겠습니다. 여보세요. 예 선생님 119인데 무슨 일이세요? 아 여기 오토바이 타시는 분들이 저기 넘어지셔 가지고 여기 그래서 못 잊으셔 가지고 전화드렸는데. 아 오토바이 뭐 단독 사고예요? 네 혼자 넘어지셨어요. 예 환자분 몇 명 1명인 거예요? 그러면? 1분 네네. 위치가 어디예요? 여기 아차산 휴먼시야예요. 그러니까 그 큰 도로 앞에요. 3시만요? 예예. 지금 환자분 의식은 있어요? 네네 많이는 안 다치셨는데 다리를 좀 다치셔가지고. 어디가 제일 아프시래요? 다리? 다리 오른쪽 다리. 아 예 아차산 휴먼시아 그 큰길 쪽으로 가면 된다는 거죠? 예 큰 도로변 앞에 예. 잠시만요. 그쪽으로 구급차 가볼 거고 환자분한테 최근에 뭐 발열이나 코로나 사항 있었냐고 하면 여쭤봐 주실 수 있나요? 네. 없으시대요. 예 알겠습니다. 그 신고하신 분 관계가 어떻게 되세요? 저 지나가는 사람이 차를 들려다가. 아 예 알겠습니다. 그쪽으로 구급차 가볼게요. 그 구급차 그쪽으로 이쪽으로 안내만 좀 해주실 수 있나요? 안내만 좀 해주실 수 있나요? 그 이쪽이라고. 아 예예 오시면 돼요 있을게요. 아 예 알겠습니다. 빨리 가볼게요. 예.
 네 열립니다. 네 여보세요. 예 말씀하세요. 예 여기 애기가 목이 삐끗해갖고 좀 움직이지도 못해요. 예 의료 상담이 필요하세요. 구급차가 필요하세요. 구급차가 필요할 것 같은데 애기가 못 움직여갖고 주소 알려주세요. 주소가 어떻게 되겠지? 집이. 연설원 17일. 연설원 17일. 네. 연설오 17개 예. 아기 몇 살이에요? 4살이요. 4살 아기 몇 남자아이에요? 네. 지금 숨 쉬어요? 예 숨 쉬어요. 목이 못 꺾였다고요? 목 부상. 아 목이 꺾인 게 아니고요. 애기가 목이 아파갖고 움직이질 못해요. 예 아버지세요? 지금 전화하시는 분? 네 네. 예 신고자분 그 코로나 확진 된 분 가족 중에 없으세요? 네 없어요. 예 면소로 17개 네.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 예, 됐습니다. 여보세요? 예, 말씀하세요. 여기 저기 강남 고중학교 앞에. 삼성 아파트. 예. 예, 삼성 아파트. 1단지. 저기. 예. 삼성 아파트가 혹시 그 가동 나동으로 있는 그 상. 여기 저기 여기 강남고등학교 정문 앞에 아 정문 앞에 그 1차 1동 1동짜리 그거 말씀하시네요. 예 예 예 예 예 할머니가 오늘 치워내셨는데 또 나 잠깐 잠 주세요. 지금 화장실 하다 넘어 주셔 가지고 너 어디 피가 막 나는 얼굴 얼굴에서요? 아니면 머리에서요? 내 머리에 머리에서 의식은 의식은 있어요? 없어요? 그냥 정신 정신은 있어요? 없어요? 정신이 있는 것 같기도 하고 아 가족분이신 거죠? 가족분. 숨 쉬는지 잠시만 숨 쉬는지가 제일 중요하니까 숨 쉬는지. 숨요? 숨은 쉬셔요. 숨은 쉬셔요. 할머니나 가족분들 코로나 관련된 증상 여행력 특이사항 없으신 거죠? 네. 네. 지금 삼성 아파트 일단. 네.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네 다름이 아니라 지금 그 안경제를 과다 고용한 사람이 있어서요. 아 가족이에요? 네. 어 구급차가 나가서 도와드릴까요? 어 네 지금 자고 있긴 한데 안경제를 한 20일치 정도로 먹었거든요. 20알이요? 네. 20알은 아니고 20 봉지요? 네 20 봉지요. 아 그래서 지금은 호흡은 하고 있는데 지금 잠에서 안 일어나요? 혹시 그러면? 네 지금 안 일어나요. 알겠습니다. 남들 여자예요? 여자요. 여성이고 혹시 자살 의도성 있어요? 아니요. 화나서 먹은 건지 아니면은 뭐 잘못해서 먹은 건지 의도적으로. 안 좋은 안 좋은 일이 좀 있긴 했거든요. 아 의도적으로 먹었네요. 주소 불러주세요. 네 여기 강서구. 네. 마구 중앙 3로. 그 미일 스테이트. 네. 아 마곡해 스테이트. 네. 잠깐만요. 코로나 환자는 아니세요? 네 아니에요. 아 여기 경찰이랑 같이 가봐야 돼서요. 같이 나가고요. 의료 안내원 한번 연결해 볼게요. 네. 의료 안내원이 다 통화 중이네요. 잠깐만 전화 끊지 말아 보세요. 네. 임성형은 임성형은. 괜찮아? 어. 우리 안내는 다 통화 중이네요. 잠깐만 기다려 볼게요. 차는 보냈습니다. 네. 어. 감사합니다.
 119입니다. 네 여기 강동구고요. 강일리버파크 구단지 무슨 일이에요? 아 여기 지금 어머니가 좀 갑자기 경력 일으키시면서 쓰러지셔 가지고 숨을 조금 힘들게 쉬고 계시거든요. 네 죄송하고요. 간호사하고 의료진과 연결과에 전화 끊지 마세요. 잠시만요. 네. 가족분들 코로나 장학연이나 확진 관련된 건 없어요? 없어요. 없어요. 네 전화 끊지 마세요. 잠시만요. 네. 다음 영상에서 만나요.
 일일곱니다. 아 예 저 여기 어 사람이 좀 쓰러져 있어가지고. 길에 쓰러져 있어요? 길거리에요. 예. 남자분이 대답하세요? 남자요. 의식은 전혀 없어요? 아 지금 일일이 있으세요. 근데 몸을 못 가는 소리 같아서. 선생님 거기 위치가 어떻게 돼요? 저희가 어디로 가면 돼요? 여기 1대 1대 아티블리지 여기 옆에 방문이거든요. 잠시 혹시 거기 직원 주소는 모르세요? 지번 주소요? 지번 아 여기 오금로 1요. 오금로. 네? 오금로. 네네네네. 그 앞이에요? 예예. 아 보급대 간다고 얘기 좀 해주시고요. 어디가 아픈지 한번 물어보실 수 있나요? 아 죄송해요. 사장님 여기 혹시 어디가 아프세요? 아 일단 지금 말을 잘 못하시는 거 같아서. 아 그래요. 알겠습니다. 예예예.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 예. 선생님 저기 저희 어머니가 예. 오줌 못 일어나서 저 바지로 오줌 싸시고 저 정신이 있는데 예. 저기 어지러워서 못 일어나시거든요. 아 어지럽고 지금 기력이 없으신 거예요? 예. 어 주소가 어떻게 되세요? 여기 용인도포구 도림도 도림도 예. 예예 몇 층 몇 호요? 일반 주택인데요. 단독이요? 지번 단독이고? 알겠어요. 구급차 지금 그쪽으로 갈 건데요. 어머니 열 같은 건 있으세요? 열. 열 쪽 열은 없어요. 아 그 고열은 없고? 알겠어요. 구급차 지금 가니까요. 병원 갈 준비하고 계세요. 예예 알겠습니다. 고맙습니다. 한글자막 by 한효정
 일대요? 무슨 일이요? 네 여보세요? 네 말씀하세요. 네 그 다름이 아니라 저희 동생이 남동생이요? 여동생이요? 여동생인데요. 예 어떻게 안 좋은 거예요? 아 얘가 애가 우울증이 원래 좀 있는데 이게 정신과 약 자체가 다 아예 없어가지고 지금 아예 감정 조절 자체가 안 되고 막 지금 막 애가 막 자살 기도를 할 정도로 지금 좀 심각하거든요. 아 지금 자살 시도를 하고 있어요? 아니 시도는 아니고요. 자살 시도가 우려되는 말씀이시죠? 네. 우려가 되기 때문에 저희가 서울시 강북구 한찬로 109 각일 각일 지금 볼게요. 지금 약 자체가 없어서 약을 먹었는데도 통제가 안 되거든요. 구원동 하이치빌라 맞으세요? 네. 네 맞습니다. 몇 층 몇 호예요? 19호 자편 상해서 보내드렸고요. 경찰서 그쪽으로 같이 갈 거예요. 전화 잘 받아주세요. 경찰이요? 예. 네.
 연락입니다. 여보세요? 예 말씀하세요. 예 그 넘어져가지고 좀 얼굴을 많이 다쳤는데. 예 고기 제가 보내드릴까요? 예 좀 보내주시면 좋을 것 같아가지고. 예 주소가 어떻게 돼요? 고통로 22길. 여기 길가에 어디 집 안에 계시는 거예요? 아 그 안쪽은 있는데 길가 쪽까지만 오셔야 될 것 같아요. 예. 아 인 거예요? 그럼요? 네, 네, 네. 환자분은 남자분, 여자분이에요? 남자분이요. 지금 의식은 있고요? 아, 예. 괜찮은데 얼굴이 또 살고 있어요. 아, 예, 예. 코로나 사업형이나 확진 관련된 건 없고요? 예, 예. 예, 알겠습니다. 금방 지도할게요. 네, 감사합니다. 네.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 119입니다. 여보세요? 네 말씀하세요. 대주동. 네? 의평구 대주동. 네. 네. 어. 네? 잠시만요. 회원님 대주동 몇 번째 번지부터 얘기해 봐요. 번지만. 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 여기는 삼성 월드빌인데. 아이 참 아유 그게 아니라요. 네. 다시 불러줄게요. 다시 불러줄게요. 네 불러보세요. 대수동. 네. 아 어떻게든 예 무슨 일인데요? 아 지금 병원을 바라보는 몸이 아파서요. 누가 아파요? 제가요. 어디가 아파요? 아니 지금 어디 아파서 지금 뭐 말도 못 듣는 거 지금요? 그니까는 어디가 가장 죽을 거 같은데요? 아 머리 아프고 지금 뭐 막 흔질러요. 머리가 아프고 어지럽고 그래요? 그렇게 얘기하시면 좋겠어요. 그래요? 그냥 머리가 아프고 어지러운 거예요? 네 막 흔질러요. 아 저 뭐 흔질해서 갔다가 하는데. 알았어요. 선생님 뭐 코로나 관련 증상 같은 거 있어요? 열나거나 재채기하거나 뭐 그런 거 있어요? 없어요? 그럼 없어요. 그럼 없어요. 가족 중에도 없고요? 아우. 혹시 가족 업체는 다 나갔거든요. 네 알았어요. 네.
 예. 일요일 구사이신다 말씀하세요? 네. 예. 저기 서울의료원에 왔는데 응급 치료 안 한다 그래갖고 네. 네. 어 그래갖고 택시 타고 왔는데 여기서 서울대학병원을 가야 될 것 같아요. 구급처가 필요하시다는 거예요? 예. 예. 예. 누가 어떻게 아프신 건데요? 음 집사람 그 치매 걸렸는데 많이 아픈가 봐요. 토하고 막아놨는데 구토하고 어디 뭐가 걸렸다고요? 장염. 장염 문증서가 있다고요? 예예. 서울 의료원 앞쪽으로 차 보낼게요. 예. 병원은 구급병원이 선정하니까요. 구급병원 만나서 맞춰보세요. 예 감사합니다.
 1입니다. 말씀하세요. 아 네 안녕하세요. 저희 어머니가 어 오늘 지방에 계셨는데 오늘 신경이라 저희 서울에 오셨는데 약간 예 간성군수가 온 것 같아요. 어머니가 간성군수 증강이요? 일단 주소가 어떻게 되세요? 여기 강남구 개포로 110길에 잠시만요. 개포로 111 몇 층 몇 층 몇 호? 네. 어머니가 단성물 수 증상이 있으신 거고 열이나 기침 이런 증상이 있었나요 어머니가? 그건 없을 테요. 아 네 알겠습니다 조금만 계산해 주세요. 네.
 수고하십니다. 네 어 저 애가 연락을 속이 되게 안 좋아하는데요. 안 좋다 하는데요. 네. 그 그래서 걱정돼서 코로나 검사를 받았는데 코로나는 아니라고 하거든요. PCR 검사 맞으셨어요? 아니면 간이 검사 맞으셨어요? 피씨 뭐였지? 항원 검사요. 병원에서 하는 검사요? 네. 네 그거 음성은 나왔고요. 네 그건 괜찮게 나왔는데 열이 그리고 낮에는 떨어졌다 다시 또 열이 오르면서 너무 힘들어하거든요. 네 혹시 뭐 구급차라도 보낼까요? 그렇게 해서 병원에 응급실을 가야 할 것 같아서. 그래요? 주소 어떻게 돼요? 여기 어 증산로 15길. 증산로 15길에. 미성 아파트예요? 네 맞습니다. 네 움직일 수 있을 것 같아요. 아이가 4살이에요? 환자분이? 아아 제 19살이요. 19살? 아 정말. PCR 검사는 언제 받으신 거예요? 오늘 낮에 받았는데 내일 모레 체격할 거여서 1시간 만에 나오더라고요. 아아. 일단은 구급차를 먼저 보냈습니다. 전화 이거 잘 받으십시오. 아셨죠? 이 번호로 받으십시오. 네 그러겠습니다. 네, 부급차가 가면서 전화할 겁니다. 네, 감사합니다.
 네, 알겠습니다. 무슨 일이세요? 빨리 보내주시겠어요? 잠시만요. 선생님 조금만 천천히 말씀해주실 수 있으실까요? 독산동. 와주세요. 선생님 무슨 일이신가요? 아니 좀 아니 좀 아니 좀 빨리 와주시면 감사하겠습니다. 머리가 터진 거 같아가지고. 머리가 터졌다고요? 네. 누가요? 아이 친척분인데 좀 빨리 와주시겠어요? 의식 없어요? 의식 있어요? 의식? 네 의식은 있고 지금 그냥 머리가 좀 많이 터진 거 같아요. 피가 지금 피가 다 돼가지고. 알겠습니다. 그 구입자 출발했고요. 선생님. 남자 그 남자분이세요? 여자분이세요? 남자예요. 삼촌이에요. 임대 아파트 맞으세요? 네. 알겠습니다. 그쪽으로 고급차 출발했었는데 전화 잘 받아주시고 있으신 거 맞으신 거죠? 네. 지금 네. 네. 알겠습니다. 네. 관련해서 해당 사항 있으세요? 아니요. 없어요. 그런 거 전혀 없으시고요. 네. 고급차 출발했어요. 전화 끝. 네. 전화 잘 받아주세요. 네.
 예, 열고입니다. 노원 포창 끝판왕 앞이요. 어디요? 노원 포창 끝판왕 앞이요. 포차, 포차 끝판왕? 노원 포차 끝판왕. 포차 끝판왕? 네. 예, 뭐 무슨 일이에요? 후기 너무 안 좋아요. 어디가 안 좋다고요? 후기 너무 안 좋아요. 본인이요? 네네. 네, 그 포차 끝판왕 앞으로 가볼게요. 네. 여기에 뭐 코로나 지역 다녀오거나 관련 증상 있어요? 없어요. 예 알겠습니다. 가볼게요. 네.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

おやすみなさい 예, 여기 저기 어머니가 저기 많이 저기 지금 놀리셔가지고. 아, 고급차 필요하세요? 아니, 아니요. 여기 경찰관 나와 계시고요. 저 저 저 일단 경찰에 지금 119 불렀는데 지금 외관상은 크게 안 다치셨어요. 아, 그러니까 저희 지금 접수받았는데. 여기 119인가요? 여긴 119고요. 아. 지금 고급차는 필요 없다고 기재가 돼 있는데 차량이 움직여서 안 된다고 해서요. 네. 차가 뭐 어떤 상황이에요?ちょっとも、拠点をこうやって少し 빼やはるのか?え、あんに、僕の検査の検査の検査は来ました。僕の検査の検査は来て、 지금 저 화물차 그 저 뒤에 적재함은 밑으로 들어가가지고 예 지금 뭐 외관상은 지금 저기 닫히신 것 같지는 않은데 많이 놀라셔가지고 아 저 이거 소방 쪽에서는 어떤 차가 나가야 될까요? 고급차가 뭐 필요 없으신다고 하니까 고급차 안 보이는데 지금 인내군데 예? 예 여기 한번 나가서 봐야 되지 않아요? 그래도 그래도 예 그러면 한번 나와보셔요. 이거 지금 예 저기 많이 놀리셔가지고 그러니까요. 네 알겠어요. 그럼 구급처만 나갈게요. 네 네 구급처만 나오시면 될 거에요. 네.
 지구입니다. 예 저기요. 며칠 잠을 못 자가지고요. 신고자분께서요? 예 제가 신고자. 예. 네네 그래서요? 머리가. 앞뒤로 땡. 머리가 아프고요. 목이 땡기고 저거 하는데 제가 원래. 저기 먹는 약이 있어요. 네. 저기 신경 정신과에서. 정신건강사에서 약을 먹는데 그 약을 먹어도 지금 잠이 안 돼가지고 좀 어제 날 밤샜고 오늘 또 그러네요. 불안해서 지금 도저히 못 있겠어요. 신고자분 지금 병원 응급실 가실 거예요? 예. 이쪽으로 구급자 보낼 거고요. 주소가 어떻게 되세요? 북한 SK 북한산시티. 네 SK 북한산시티. 네 그쪽으로 보호처 보낼 거고요. 요즘 코로나 때문에 그러는데. 코로나 관련해서 내린 날 기침 있으세요? 코로나 증상이 있으세요? 코로나 증상은 없어요. 그건 없으시고요? 예 귀가 붓고 잠을 안다가 귀가 붓고 목이 붓고니까 코로나는 아니에요. 백신을 수요일날 월요일날 맞았어요. 네 그쪽으로 보내드릴게요. 좋은 하루 되세요.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 예, 여기 지금 엎어져가지고 팔이 좀 많이 좀 다친 거 같은데요. 어, 누가요? 여기 여기 동생이요. 동생이? 주소 주소가 어떻게 되세요? 여기 서울 서초구 잠원 아니 반포동. 예. 예. 예, 가족분들 중에 코로나 지역 다녀오거나 관련 증상 있나요? 아니요. 없어요. 예, 고거 제가 가볼게요. 예 저기 뭐 좀 보목 가져와야 된다고 좀 말씀해주세요. 아 예 알겠습니다. 전화 오면 잘 받으세요. 가볼게요.
 여보세요? 여기 청구 아파트 몇 동? 네 빨리 좀 와주세요. 아 빨리 좀. 무슨 일이에요? 무슨 일. 잠요 잠요 저 일단은 쓰러졌어요. 저 일단. 숨으셔요 지금? 네? 숨으셔요? 네. 누가 누가 쓰러진거 남편 누가? 남편 집에 뭐 코로나 환자 없죠? 없어요. 응급차 갈 거고요. 전화 끊지 마세요. 왜 우시는 거예요? 저도 아파요. 일단 가고 있어요 저희. 네 빨리 우세요. 숨 정상적으로 쉬는 거 맞죠? 숨요? 통아빠 통아빠. 전화 끊지 마세요. 그럼. 통아빠.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네 저기 어 아까 통화하셨던 분이 아니신 것 같은데 저희 여기 마포구 도화동 우성 아파트 여기 신고자분 아까 우체 상담센터로 넘어갔잖아요. 네 그래서 거기서 여쭤보니까 응급실하고 치료를 같이 하는 데가 뭐 격리실이 있대요. 응급실하고 같이 이제 운영하는 곳이 그래가지고 그 요청을 하시면 된다고 얘기를 듣고 다시 전화를 드렸거든요. 아 구급차요? 네. 아 예 누가 아픈 거예요? 저희 남편이고요. 아 네 어떻게 아프세요? 아 지금 그냥 열이 나고. 어 지금 저희가 이제 다리를 오늘 갑자기 오늘 다리도 못 움직여서 지금 일어날 수가 없거든요. 어 다리 통증이 심하대요? 아니 통증이 아니라 이거 병 때문에 그런 거거든요? 아 무슨 병이 있어요? 자계통 위축증이요. 자계통이요? 다요. 다. 마늘 다. 예예. 다계통. 다계통? 위축증. 위축증이라는 병이 있어요? 예. 그게 휘지평인데 신경계 그 자율신경계하고 손해 위축이 같이 오는 거예요. 예. 그러다 보니까 지금 다리가 갑자기 오늘 다리도 원래는 워커를 자꾸 걸었었는데. 예. 오늘 아예 걸치지 못한. 아. 이제 다리 통증도 있다는 거죠? 예. 다리가 힘이 없다는 거죠. 아 아 다리에 힘이 없어서요? 네네네. 아 제가 응급실 가시면 되는 거예요? 그럼? 예 응급실 응급실 가는데 지금 코로나 검사를 해야 된다고 그때 그래 그래가지고. 아 네네. 지금 열기쯤에 경리실 가서 해야 되거든요. 네 경리실. 예 경리실. 예 주소가 어떻게 되세요? 예 도하동 우성 아파트. 잠시만요. 네. 마포구. 도하동. 도하동이요? 예 도화요. 도화? 도화동? 몇 번지예요? 여기가 3개로. 아 도화동 몇 번지인지 몰라요? 네네. 잠시만요. 도화동 무슨 아파트예요? 우성 아파트요. 우성 아파트요? 네네네. 아 예 알겠습니다. 전화 잘 받으세요. 네.
 안녕하십니까? 예 어머니가 열이 많이 나시고 막 우환이 오신데 더버버려 떠져가지고요. 의식은 있어요? 예 의식 있으신데. 호흡콜러는 없으신데요? 호흡콜러는 없는 지금 온도가 39도까지 가갖고. 환송포화도 되는 게 있어서 되니까 95 정도 나오거든요. 대신 주소가 어떻게 돼요? 여기 종로 종로구 승인 2동. 몇 층 몇 호요? 등록이에요? 네 아 예 그쵸. 밑에 밑에는 3사람들이 있고. 근데. 일단 그쪽으로 거기다 보냈고요. 환자분. 네네네. 그거는 확신자는 아니란 말씀이시죠? 확신자 아니신데. 저기. 일단 보급 착용하고 접근하겠습니다. 기다려주세요. 네네네.
 119입니다. 네 여기 코코인츠 바리쉐라톤 여기 호텔인데요. 호텔 이름 좀 다시 한번 얘기해 주시겠어요? 폭포 폭포? 예. 코코인츠 바리쉐라톤 강남전이요. 바리쉐라튼이요? 네 바이 바이 쉐라튼이요. 바이 쉐라튼. 어 도산대로. 예 무슨 일인가요? 제가 숨을 갑자기 못 쉬어가지고. 몇 호에 계세요? 몇 호? 여자 호흡곤란 일단은 뭐 과업일 수도 있는데 일단 차는 출동했고요. 차 가는 동안 의료진 연결할게요. 성함 말씀해 주세요.
 예, 이리 와봅니다. 아, 예, 안녕하세요. 어, 제가 그 지치적인 게 좀 있는데. 예. 예, 그 지금 결석이 생겨서 좀 통증이 많이 오거든요. 어, 배가 아프다는 거예요? 예, 그렇습니다. 오른쪽 옆구리 아랫배가 아픈데. 아, 예, 그 주소 불러주세요. 가볼게요. 예, 여기가 도봉구. 도봉구, 도봉동. 예. 예, 현대성 아파트. 현대성. 예, 예. 예 현재 성우 아파트. 예. 예 요새 가족분 포함해서 코로나 지역 다녀오거나 관련 증상 있나요? 아니요. 그 저희 부모님 다 그 접종하셨고요. 저도 접종했습니다. 이체까지 하고 그리고서 뭐 그 의심되는 곳에 방문하거나 그러지는 않았습니다. 구급차 가볼게요. 전화 오면 잘 받으세요. 네 감사합니다.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네 안녕하세요. 저기 성신병원 가야 되는데. 네. 네 오시면 안 될까요? 근데 덮지를 못해요. 앉지도 못하고. 누가 아프신 거예요? 어 엄마가 할머니요. 네 어머니 어디 아프세요? 허리가 또 골절되신 거 같아요. 아 허리 골절 추정돼요? 네. 이제 모르시겠고요. 신호 좀 알려주세요. 성내동. 네. 어 6 성내로 6과길 성내로 6과길에 네. 건물 이름은 없고요? 네. 예. 지금 고객센터 수강하고요. 혹시 어머님은 연락이거나 뭐 콜센터 연락이 없으시고요? 예. 걷지도 못하고 안 찍도 못해요. 예. 알겠습니다. 저희 둘 거 같이 네 감사합니다. 네.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 여보세요. 여보세요. 진정하시고 무슨 일이에요? 여기 안 들어. 네. 여보세요. 아니에요. 아니에요. 끊어요. 무슨 일이에요? 무슨 일. 여보세요? 맞으시고요? 아니에요. 아니에요. 무슨 일이신 거예요? 여보세요? 여보세요? 무슨 일인 거예요? 아 엄마가 지금 어머니께서 아 엄마가 지금 지금 좀 끊겨서 숨을 잘 보시고 막 이러셔가지고 꼬꼬라 있으시고 계신 몇 호요? 몇 호? 예 여기 도이 헤어라고 있거든요. 도이 헤어요. 헤어샵 헤어샵. 헤어? 헤어샵? 네. 예. 예. 의식은 어때요? 의식 있어요? 없어요? 어머니. 아 의식은 있으신데. 엄마 지금 고요랄이 좀 있으시고. 침도 좀 안 좋으시거든요. 그래서. 다 출장에서 가고 있어요. 기침이나 열 묵기 같은 코로나 때문에. 아 그런 건 없으시고요. 2차 3차까지 다 맞으셨고요. 알겠습니다. 시작하고 있으니까 전화 잘 받아주시고요. 네 감사합니다.
 119입니다. 말씀하세요. 예 여기 강서구요. 예. 음 강서로 잠시 보면. 예. 어이 저 제가. 어 허리도 아프고. 예. 어. 술도 많이 먹었는데. 예. 허리가 허리가 안 좋네. 허리가 아프시다고요? 그럼 뭐 구급차로 그 운동실 한번 가보시겠어요? 네 일단 주소 주소는 양진빌라죠? 양진빌라. 네 양진빌라 몇 호예요? 예. 코로나 관련해서 열이나 기침 이런 증상인가요? 그런 건 없습니다. 그런 건 없고요. 일단 알겠습니다. 현관문 열어줄 수 있죠? 네. 네 알겠습니다. 조금만 기다려주세요. 네.
 네, 감사합니다. 말씀하세요. 예, 예, 다름이 아니라 지금 저기 뭐야. 네, 어머님이 코로나가 걸렸다고 지금 연락이 왔는데요. 제 동생이 환자거든요. 네, 집에 혼자 있는데. 그 그래서 저기 입원을 시켜야 될 것 같아서 계속 코로나 걸릴 조사를 좀 받아야 될 것 같아서. 동생분이 지금 아프신 건가요? 예, 예, 아퍼요. 자가 격리자세요? 예 자가격리자는 아닌데 제가 몸이 불편해가지고 움직이지 못해요. 그니까 동생분 제가 응급실 가길 원하셔서 생각하신 거 많으세요? 아니 지금 집에 있거든요. 그니까 동생은 지금 병원 응급실 가시려고 생각한 거 맞으세요? 예 예 예 일단은 예 예. 동생분 그 선생님 위치 좀 알려주세요. 동생 계신 분 위치요. 예 서대문구 연희동. 잠시만요 연희동이요. 예예 지금 혼자 있어요 문을 못 열을텐데 문 열어놨어요 문을 열어놨단 얘기신거죠? 동생분은 어디가 불편하신데요? 다리가 못 움직여요 지금 다리가 아프셔서 신고하신거 맞으시죠? 동생분 혹시 자가격리자세요? 자가격리자 아니라니깐요 어머님이 걸려있었기 때문에 둘이 생활을 하거든요 어머님이 저희 동생을 돌보고 있는데 어 몸에 감기 기운이 있어가지고 병원에 갔더니 제가 코로나 확진자라고 판결이 나서 동생분 아니시라는 거죠? 자가격리자도 아니시라는 얘기신 거죠? 아직은 아니고 저희 조사는 받아야 될 거 같아서 그 다리 아프시다고 해서 저희가 구급차 보낼 거고요. 선생님 그쪽 현장에 계신 분 전화번호 혹시 알 수 있을까요? 아니 전화를 못 받아요. 전화 전화 못 받으세요? 예 예 예 그럼 선생님한테 연락을 하면 되는 건가요? 네 그렇죠. 근데 저는 지금 다른 데 와 있고요. 일단 저희 구급대가 나가서 확인해 보라고 할게요. 자가격리자는 아니시란 얘기신 거죠? 선생님 알겠습니다. 예예예예예예 구급자 통화 전화 누를 수 있거든요. 선생님 저 통화할 수 있거든요. 전화 좀 잘 받아주세요. 예예 전화 오면 제가 잘 받을게 건물 맞나요? 예? 건물 맞아요? 거기가? 네 알겠습니다. 예.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 예, 여보세요? 예, 여기 저기 어디야. CU 관악 신림점 CU요? CU 관악 신림 어디? 에 관악 관악 신림 신림점요? 예 CU 관악 실림로. 실로로요? 실림로점. 예 여보세요? 그 아픈 사람이 남자예요? 여자예요? 예? 예 남자분이요. 예 어디가 아프세요? 배 아프다고 죽을라 그래요. 예 복통이고요. 그리고 코로나 관련해서 그 의심할 만한 건 없어요? 비침하고 열 그런 건 없어요? 어 그런 거 없어요. 빨리 와주세요. 신고하시는 분은 뭐 친구분이세요? 아니에요. 지나가는데 너무 차단 119 불허다고 그랬어요. 예 알겠습니다. 다음 주에 전화 한번 전화 좀 좀 혹시 받아주세요. 예. 예 빨리 오세요.
 입니다. 네 안녕하세요. 여기 중환지구 아까 저희 공동 대응 요청 관련해가지고 공동 대응 요청하셨는데 그 요구도자 찾아가지고 위치값 알려드렸습니다. 예 자살하려고 한다면서 약 먹었다고. 아 예 선생님 그 주소는 어떻게 되시죠? 뉴슬라모텔 그 선생님 서울쪽 맞아요? 네네 영등포 삼가요. 영등포 삼가? 저희 직원 없는데 지금? 잠시만요. 요청자가 9시 58분쯤에 요청 왔구요. 9시 58분쯤에 저희가 요청한거에요? 예예. 잠시만 제가 한번 찾아볼게요. 영동 부서방서 출동이요. 아 예. 아 그 자살하려고 약 먹었다고 그 모텔 거기 말씀하시는 거죠? 네, 네, 맞아요. 그 선생님 거기 그 위치가 나와가지고 그쪽으로 다시 나가야 되는 거죠? 저희 그러면. 네, 네, 지금 발견해가지고. 아 예예. 그러면 지금 고급대만 필요한 거예요? 지금? 예예. 아 예. 누구 실낭 어떻게 주소가 어떻게 되죠? 거기가? 어 영등포 삼가 쪽이거든요. 삼가에 주소는 모르시는 거예요? 예예. 잠시만요. 저 검색해볼게요. 네. 아 예. 주소 확인됐고. 지금. 예. 그 상태는 어때요? 지금? 지금 일단 신선 안전재랑 술이랑 먹은 게 아니라 정확한 거는 저희가 와서 확인하셔야죠. 아 예 알겠습니다. 거기 때문에 한번 갈게요. 예 감사합니다 고생했어요.
 네 여보세요? 네 119 상황실이고요. 수강차는 출동하고요. 어머니가 혹시 열이 나거나 기침 코로나 관련 증상 있으세요? 약간 있습니다. 열은 한 38도 정도였고요. 열은 있으시고 뭐 코로나 확진자예요? 그건 아니죠? 아니요. PCR 검사를 그저께 하셨는데 어저께 음성으로 나왔어요. 어제 음성 나왔다고요? 네네네 근데 이제 발진은 그전에 시작이 되셨고 병원은 이제 그때 가신 거예요. 어제. 어제 번호가 음성 결과 나왔다고요? 예 문자로 받아가지고 가지고 계시더라고요. 알겠습니다. 저희 출동 회원이 어머니한테 전화하라고 얘기할게요. 네 네.
 네. 1 2 9 입니다. 네. 혹시 응급차 호출 가능한가요? 예. 무슨 일이 이제 누가 아프신가요? 아 저희 이제 그 할머니가 예. 그 화장실 좀 넘어지셔 가지고 허리가 좀 아프셔 가지고 예. 응급실로 가보시겠어요? 네. 가려고 하거든요. 예. 주소나 위치 말씀해 주세요. 주소가 강북구 예. 번 이동 예. 네. 네. 네. 네. 몇 층에 계세요? 여기 단독이에요. 할머니 나이대가 어떻게 되세요? 뭐 70대 80대 어떻게 되세요? 90대세요. 90대 할머니요? 네. 30년생이시군요. 네. 네. 고급차 보내드리고요. 발열이나 치킨 같은 코로나 증상은 특별히. 아 그런 건 따로 없어요. 알겠습니다. 고급차 출동하겠습니다. 병원가실 준비하고 계세요. 네. 예.
 일로 갑니다. 무슨 일이세요? 네 여기 송파구 월드 탁구장인데요. 네. 네 여기 탁구장인데. 네 네. 머리를 V C였어요. 탁구를. 네. 키가 좀 많이 나요. 그 탁구대의 머리를 남자 분이세요? 여자요. 잠시만요. 무슨 탁구장인가요 선생님? 월드 탁구장이요. 저희 검색 좀 해볼게요 선생님. 네. 그 옆에 주유소 있는데 맞아요 선생님? 이 주유소 있냐? 앞에? 어 근처에 있어요. 주유소. 그 몇 층으로 가면 돼요? 월조 탁구장? 선생님 뭐 아시는 분이신 건가요? 아니면 선생님 직원분이신 건가요? 어 아니요. 그냥 모르는 사람이에요. 옆에 있어요. 아 그 그 여자분이 머리에 턱구리에 부르쳤다고요? 네. 알겠습니다 그쪽으로 구급차 보내드릴게 그 의식은 있으신거죠? 네? 의식은 있으신거죠 선생님? 네 있어요 네 알겠습니다 선생님 그쪽으로 구급차 보내드릴게요 네
 네 여보세요? 아 예 여기게요. 은평구 신사동 신사동 네네네. 은평구 신사동 네네네. 몇 층 몇 호예요? 한샘 빌라 맞아요? 한샘빌라. 예 맞습니다. 예. 무슨 일이죠? 그 병원 가려고 그러는데요. 예 누가. 저희 집사람이. 네. 네. 어디가 어떻게 안 좋으세요? 차 출발 시켰고요. 예. 그. 가슴이랑 등기랑 지금 주말 못 쉴 정도로 지금. 예 코로나 관련된 건 없으시고요? 코로나 관련일 수도 있어요. 지난번에도 한번 그랬었는데. 코로나 확인된 적 있어요? 아니요. 그렇진 않습니다. 주사 맞은 이후에. 아 주사 맞은 이후에? 그 의식은 있죠? 네 네. 네 한세블라. 네 알겠습니다. 출고할게요. 예. 네 네.
 일로그입니다. 어 지금 환자가 병원에 가야 되는데 움직이도 못해서 그러는데 좀 도와주실 수 있나요? 예 누가 아픈 거예요? 우리 집사람이요. 아 내 분이 어떻게 아파요? 의식이 없어요. 의식이 없고 숨은 안 쉬어요? 숨은 쉬어요. 예 숨을 쉬고 의식이 없는데 지금 아픈 데가 그럼 없는 거예요? 어디 쪽이. 정신이 아프라고 그러거든요. 정신 통증이 있어요? 예예예. 지금 아예 아무 말도 못 해요? 말은 좀 하는데 잘 못 알아듣겠어요. 의식이 혼미한 거예요? 그럼? 예예예. 예. 안 해본 열이나 기침 뭐 코로나 관련 사항 있어요? 예. 그런 상황은 아니고요. 그런 거 없어요? 주소 어떻게 되세요? 네. 중계동 노원구 중계동? 중계동. 노원구 한글 주성목 한글 주성목? 예. 팔길 팔길 네. 잠시만요. 여기 벽산 아파트에 맞아요? 대림벽산. 네 대림벽산. 네 네. 네 알겠습니다. 전화 잘 받으세요. 예.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 아 이래가 좀 가만히 있어. 네 여보세요? 어 169에요. 말씀하세요. 아 네네 안녕하세요. 예 3일 대중 목욕탕인데요. 아 그 저희가 서울시 전체 전화 받고 있어서 혹시 주소 아시는 주소 좀 불러주시겠어요? 네 네. 저희가 서울시 전체 전화 받고 있어요. 그 주소 혹시 무슨 부 무슨 동에 계신 거예요? 아 마포구 망원동 3일 대중 목욕탕 마포구 망원동. 주소는 모르시면 검색을 해볼게요. 네, 네, 네. 상의 대중 모기탕. 네, 어떻게 때문에 그러세요? 아, 어르신이 넘어졌는데 병원에 가셔야 되고 머리 좀 다치신 것 같고요. 몇 층으로 가야 돼요? 남탕으로 가면 되는 거예요? 네, 남탕이요. 네, 네, 네. 몇 층에 있어요? 남탕이? 뭐 의식이랑 호흡 괜찮으시고요? 할머니? 호흡하고 그런 게 괜찮아요. 아, 알겠어요. 그 뭐 남탕으로 갈게요. 예. 네, 네, 네, 네, 네. 어? 억지로 이렇게 세우지 마시지
 네, 읽습니다. 말씀 없으면 끊습니다. 아 네, 여보세요? 네, 무슨 일이에요? 아 여기 오토바이 타고 가시다가 넘어지셨는데. 예 뭐 교통사고여요? 교통사고는 아니고요. 교통사고도 아니고 혼자 그냥 넘어오어요? 네네. 어디 앞인가요? 지금 여기 금오 스포츠 센터 앞에 LG 25C 편의점이 있는데요. 센터 앞에 LG 25C 편의점이 있어요? 네 센터 바로 맞은편이에요. 금오 스포츠 센터 바로 맞은편에. 맞은편으로 가보겠습니다. 고급차. 네 지금 일어나셨긴 한데 좀 상태가 많이 많이는 아닌데 좀 안 좋으신 것 같아요. 네.
 예, 입니다. 무슨 일이세요? 네, 저 지금 항암 치료를 받고 계신데 어제부터 일어나지를 못해서요. 아버지 숨 쉬는 거 사람 알아보는 거 어때요? 예, 그거는 되고 있어요. 의식하고 호흡은 있으신데. 예, 예, 예, 예, 거동을 못 하셔서. 아버지 숨쉬가 떨어져서 그러신 거예요? 예, 예, 신경이 없으셔서 병원을 가야 될 것 같은데. 지금 저기가 안 되네요. 네, 되세요? 예? 주소지가 어떻게 되세요? 여기 서울 금천구 시흥산동. 몇 층 몇 호예요? 단백질. 예. 기침이나 열 복구공 통증 같은 코로나 증상 없으시고요? 예. 없어요. 알겠습니다. 차 가고 있습니다. 아 예. 알겠습니다. 감사합니다.
 네 안녕하세요. 여기 경찰관인데요. 지금 여기 주소가 어 대우 대우 미래사랑 한국전력 앞인데. 대우 미래사랑 한국전력이요? 네네네. 잠시만 예. 지금 술 넣고 넘어지셨는데 보도블록 그 톡치 하나 온 거에 머리를 심하게 찢으셨군요. 남자분이에요? 네네 남자분이요. 추려 있어요? 추려는 없어요. 음 낙상이시고 머리다. 아 대우 미래사랑 3차 오피스텔 앞에 말씀하시는 거예요? 네네 거기 앞에 한국전력 사이에 도로에 지금 있거든요? 오피스텔하고 한국전력 아 요 가운데 도로. 네 네 네. 네네. 아 예 그러면 경찰서에 있는 곳으로 가면 되죠? 네네네. 네 알겠습니다. 네.
 예 119입니다. 아 예 사람이 좀 다쳐 갖고 그러는데요. 아 뭐 어떻게 뭐 교통사고예요? 아니면 어떻게 다 지금 넘어진 거예요? 어떻게 다친 거예요? 예예 넘어요. 낙상 그냥. 예예. 환자 남자분이 여자분이에요? 남자분이요. 남자분 어디 허리 아프시대요? 다리 아프시대 물어봐 주시겠어요? 아니요. 코 코 코가 좀 적어서. 안면 부상 피나요? 예예. 의식은 괜찮은 거죠? 뭐 숨 못 쉬거나 뭐 의식 없거나 뭐 코로나 관련 기준 이런 거 없으신 거죠? 예예예예 내 신고 주소가 어떻게 되나요? 여기 오류중학교요. 오류중학교. 정문 앞이시죠 그러면? 예예예 오류중학교 정문 앞으로 갈게요. 예예예 조차 고객님 손을 들어주세요. 가고 있어요. 예예
 쌍몽교. 네 열립니다. 네 여기 쌍몽조인데요. 네. 오토바이 타고 가시는 분이 좀 넘어져가지고 일어나지 못하고 있거든요. 네. 주소 쌍몽교. 쌍몽교 대광교에 바로 앞이에요. 예 그 혼자 넘어졌어요? 네 네 혼자 넘어졌어요. 아니 차랑 차가 좀 못갔고. 예 뭐랄까? 차가 부딪혔는데 차는 지금 가버렸어요. 그래서 넘어진 분이 이렇게다가 차는 가버려가지고 제가 어디 남자분 남자분 의식호흡 있어요? 네 의식호흡 있어요. 지금 근데 좀 아파가지고 일어나지 못한지 도와주고 있어요. 네.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네, 여보세요? 네, 말씀하세요. 아, 저 너무 아파서 그런데요. 네, 주소 알려주세요. 주소가요? 아, 서울 근청구 가산동? 네. 아, 몇 번지. 잠깐만요. 아. 아 아 아 아 금천구 가산동 네. 몇 호 몇 호예요? 그 아니 고시태인데요. 고시태 몇 호예요? 네. 네. 배가 부르면서 계속 설사하고 토하고 식읍받나고. 하... 네. 네. 지금 차 나왔고요. 네. 네. 네. 노블 레지더스요. 노블... 노블... 네 알겠습니다. 저기요. 거기 올라오실 때 핀번호 누르거든요. 네. 네. 네. 감사합니다.
 네, 수고하십니다. 여기 서울 서초입 박수소인데요. 네, 여기 지금 주치자가 와 있는데 몸을 좀 심하게 따라와가지고. 남자예요? 여자예요. 여자. 아 그러시고. 예. 지금 온도는 체온 체온은 지금 35도 나오거든요. 겉에온이에요? 35도로 나오고 몸을 좀 심하게 떨어가지고 의식은 괜찮고요? 의식은 있어요. 예 알겠습니다. 유치하겠습니다. 예

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네, 여기 사고 나서. 아 예. 뭐 환자 있으신 거죠? 네, 오토바이 아마 넘어지셔 가지고. 여기 서울 도봉구. 네. 상동. 잠시만요. 서울. 아 이게 뭐야. 서울 창림 초등학교 앞이거든요. 아 창림 초등학교 앞으로 가면 되나요? 네 네 네. 아 네 혹시 환자 1분이신가요? 네 차랑 오다가 브레이크 밟아서 너무 있으셨는데. 아 음식은 있으시죠? 네 근데 다리가 네 사진 좀 부탁드릴게요. 아 네 네 네.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네. 여보세요. 네 여기 119예요. 그 여자친구분이 실시했다고 이렇게 신고를 주셨는데 어디가 아픈 거예요? 아 정신을 못 들어가지고. 예 고급자가 필요한 거죠? 병원 가실 거죠? 지금 구급차 가고 있어요. 그 3번 출고 앞에 있나요? 홍대? 예 알겠어요.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 예, 여보세요? 예, 말씀하세요. 예, 여기가 어 그 저희 아버님이 어제 예 그 성신병원에서 일주일 동안 입원 입원하셨다고 어제 퇴원을 하셨는데 괜찮다가 갑자기 지금 막 떠시고 춥다 그러시거든요. 오한이 오신 거예요? 오한? 예 그래서 저기 저 성신병원으로 전화를 했더니 뭐 갑자기 열이 나라 그런다 그러는데 열도 지금 안 나거든요. 근데 하여튼 그 응급질로 빨리 왔으면 좋겠 저 와서 무슨 질병이 있으신 분이에요? 병이요? 병은 모르겠어요. 갑자기 그 뭐 때문에 입원했다가 전화하신 거예요? 무슨 무슨 질병 때문에? 그 저기 뭐죠? 장기의 아니 일단 뭐죠? 이거 어디서 피가 새서 쓰레기 있어서 이 뭐죠? 그 혈압하고 혈압이 떨어지고 그다음에 빈혈 뭐 이렇게 해가지고 그래서 입원했다가 지금 뭐 어제 태원하신 음 그 주소 좀 알려주세요. 주소. 예 여기 저 천호 3동. 네네. 주소 확인 한번 해볼게요. 강동구 청호동 제가 모듬출동권에 코로나 관련 질문 드리고 있는데 가족분들 계신 분들 중에 발열이나 고열 기침이 코로나가 있는지 안계시고요. 확진자나 자가격량이신 분들 안계시고요. 대원들이 핸드폰으로 전화 드리면서 갈 거예요. 전화 좀 받아주세요. 감사합니다.
 주소가 어떻게 되죠? 주소 영수증. 아 예 여기 술 드시고 좀 넘어지신 고객님 있어가지고 사람이. 남성이에요? 여성이에요? 남성분이요. 한 60대 후반. 남성분. 넘어졌다고요? 예예. 어디를 다치셨어요? 아니 뭐 다친 것 같지 않고 넘어지셔갖고 좀 앞에서 엠블런스 불러 1, 2분 불러달라고 그러셔가지고요. 예 신고자분은 지나가다 발견하신 거예요? 아 저 마트에서 일하는데 마트 앞에서 넘어지셔 가지고. 예 거기 주소 좀 알려주세요. 주소. 예 주소가요. 진흥로 은평구 진흥로 1길 예예. 푸르네 마트 앞입니다. 푸르네 마트요? 네 출장하겠습니다.
 예 지금 아저씨가 가슴 통증이 예 너무 심해가지고 계속 아프다 그래서 저번에도 간 적이 있는데 또 중간에 또 몇 주소지가 어떻게 되세요? 여 여의대방로 이길 보라매교에 수도 요구 옆에 보라매교 옆에 여의대방로 이길 몇이라고요? 몇 층 몇 쪽에 계세요? 기침이 약간 목구멍 통증만 똑바로 가진 상황 없으세요? 네 그런건 아니구요 넘어져갖고 이 그 가슴 가슴팍 뼈가 아무래도 조금 다친 것 같은 간 것 같은데 후차 보내드렸구요 전화 드릴 수 있으니까 전화 좀 받아주세요 예예예
 네, 연락합니다. 아 네, 네, 네, 지금 환자가 내 진단인 거 같아서. 누가요? 지금 연말에 그 숨 먹고 장난치다가 지금 머리를 심하게 발꿈치로 맞았어요. 어 예. 발꿈치로 맞아가지고 지금 그 맞으신 분이 지금 머리를 고통을 심하게 호소하고 있는데. 어 예, 그니까 친구예요? 누구예요? 친구예요. 주소가 어떻게 돼요? 네 서원길 다시 41길 그 청년 캐슬이라고 하면 바로 나오거든요. 청량? 천년 캐슬. 천년 캐슬이요? 네네네. 주소 좀 찾아볼게요. 네. 네. 네 몇 호예요? 네 뭐 기침 발열 이런 건 없었어요? 뭐 친구 분이. 네네네. 네네. 한번 가볼게요. 네. 감사합니다.
 여보세요? 예 선생님 여기 119인데요. 아 지금 가고 있고요. 거기 인테리어 팰리스 호텔 앞이에요? 위치가? 예 3월이. 예예. 아 혹시 거기 지금 다치신 분이 택시 기사 1분이세요? 네? 다치신 분이 택시 기사님 1분이세요? 병원 가실 분이? 예예. 아 선생님 혹시 버스 운전자세요? 아니면 지나가다 오세요? 버스 운전자세요? 경찰은 왔어요? 아직 안 왔습니다. 아직 안 왔어요? 그 사거리에서 사고 난 거예요? 세관 사거리? 예. 알겠습니다.
 네. 1 2 9입니다. 말씀하세요. 네. 여기 저기 장안동 11 해피틸이 2차인데요. 잠시만요. 장안동. 11 해피틸이 2차요. 아 지금 저희가 12 해피틸이 2차가 여기 이 가은빌 앞에 여기 SK 텔레콤 장안 사고 앞에 있는 건가요? 네네네네. 네 잠시만요 네 음식을 먹고 지금 위경련이 장염 설사도 하고 막 그래가지고 지금 아저씨가 신랑이요 남편분이요? 네 네 설사랑 장염증상이요? 네 네 그 남편분 혹시 의식이랑 호흡은 다 있죠? 네 아 그런 거 전혀 없어요. 산책까지 다 맞았어요. 네. 맞으시죠? 네. 대원들 나가면서 전화드릴 수 있으니까 전화는 안내 좀 부탁드릴게요.
 소방서입니다. 소방서입니다. 예. 여기 여기 석산동인데요. 아 벌써 너무 그러는데 경제 좀. 주소 다시 예 뭐라고요? 네, 몇 층에 있어요? 여기 경대로 좀 저기 해주세요. 아니 일단은 몇 층에 있어요? 여기 밖에 나와 있어요 지금. 어디 아파요 그럼? 지금 머리 아파가지고 토하려고 하고. 선생님 본인이 그러세요? 네, 올 것 같아서 지금. 연락이나 기초 확진자 자가격리자 해당 있어요 없어요? 없어요 그런거 네 구급차 보낼게요 좀 기다리세요 중화동에서 갑니다 중화동에서 네 주사 다 받고 그랬는데 네 머리가 아픈다고 알겠습니다 원래 머리 수술해가지고요 바꾸면 아픈게 수술하거나 병원 그거는 구급대한테 말씀하셔야 돼요 아셨죠? 네 구급대 갑니다 네
 수고하십니다. 여보세요? 네. 아 아 아 여기요. 뭐지? 여기 어디 있네가? 옆에 뭐 보이는 거 없어요? 여기 개봉 충전소 거기거든요? 개봉. 충전소요. 그 SK 개봉 충전소. SK 행복 충전소? 어 그런 거 같아요. LPG 증명서. 아 네. 정말로. 네. 맞아요. 무슨 일이에요? 거기 앞에. 아 여기 그 뭐지 운전하는데 그 자전거 사고 가시는 분이 되셨거든요. 뭐래 뭐랑 사람이랑? 아니요. 차랑 그 자전거랑요. 자전거랑? 보호차 가볼게요. 가스 증명 앞에 SK. 네.
 네 119입니다. 여보세요? 예 119입니다. 말씀하세요. 여기 저기 속천 호수에 속천 호수에 이거 카페 있는데 그 앞에 어떤 그 노숙자 같은 분인데 연소가 좀 있으신 분인데 그 들어오는 자고 있는 건지 뭐 기절한 건지 모르겠어요. 근데 이 층위에 이대로 그냥 놔두게 되면은 잘못하면 동사할 수도 있겠다 싶어서 지금 신고를 하는 거거든요. 아이 그 뭐 카페 거리 그 지금 계신 곳에 뭐 보이는 가게 같은 거 하나 말씀해 주세요. 어디로 가면 돼요? 저희가? 에 또 여기가 JB KB? J J B 아우트 카페 제이비. 석천 호수. 제이비 바운스 카페. 시그니엘 시그니엘 호텔. 에 현관 정면으로 있는 카페 있어요. 시그니엘 호텔 정문이요? 예 저 저 시그니엘 호텔. 에 현관에서 정면으로 정면으로 카페가 있거든요. 시그니엘 호텔 정면에 카페. 예. 예 그쪽에. 석천. 석천 호수 쪽으로. 아 정면에 카페 석촌 5구 쪽으로 그 남자분이 쓰러져 있다는 내용인 거죠? 예 근데 움직이기는 움직이는데. 내가 이거 신고하는 거는 입술 위에 그냥 놔두게 되면 혹시 동사할 수. 아 예 알겠습니 몇 가지 좀 여쭤볼게요. 그러면 그 저희가 그쪽으로 구급차 가게 되면 안내 좀 해주실 수 있어요? 아 안내. 아니 바로 여 저 카페 옆에 바로 누워 있어요. 예 그니까 그쪽으로 지금 보급자 보낼 건데 그 현장에 계시면서 얼마나 얼마나 걸리죠? 한 5분 정도면 도착할 것 같아요. 알았습니다. 5분 동안 우리가 여기 기다리고 있을게요. 네 알겠습니다. 선생님. 예.
 아 네. 남자분이시고요. 그 낮에 어지럽게 좀 있어서 되게 많이 어지럽다고 호소를 하셨는데 지금도 또 너무 어지럽게 심하셔서 저 자녀인데요. 딸인데 저한테 전화를 주셨어요. 어 어 잠시만요. 도남동이요? 예. 한신 한진 아파트? 한신 한진 아파트요? 예예. 네네 지금 아빠 계시고 엄마 같이 계시고 계시거든요. 전화번호 불러주세요 제가 현장에 전화해볼게요. 아 누구 전화번호를 알려주세요. 현장에 현장에 받을 수 있는 전화번호. 아 잠시만요. 네. 엄마 번호를 알려주세요. 예예예. 네. 알겠어요 이제 통화 한번 더 가볼게요. 네 감사합니다.
 예, 16입니다. 여보세요? 예, 예. 여기 저 어 여기 가만 있어봐. 아 여기 저 아 여기 여기 가만 있어봐 주소가 좀. 아 대현 몇 개 대현 몇 개 아파트 대현도 없어 이 서대문구 대현도 몇 개 아파트. 지금 몸이..뭐..뭐..애가..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐..뭐 없어요. 없어요. 얼굴이 끊었고 일단. 호흡도 이 확인이 안 되는 상황이죠? 일단 번호 올렸고요. 저희 응급처치 하실 분 연결을 해드릴 테니까 잠깐 끊지 말아 보세요. 잠깐 끊지 말아 주세요.
 네, 1. 예, 말씀하시죠. 사람이 가다가 좀 소리 치워졌는데 그러다가 전봇대에 머리를 박았는데 여기 여기 콧 위쪽이 좀 찢어진 것 같아가지고요. 피해가 나서 와가지고. 주소 알려주세요. 가까이 보이는 간판 뭐 보여요? 아 여기 우리은행 성수지점이요. 잠시만요. 저 볼게요. 우리은행 성수 지점이요? 성수 IT 지점이에요? 네 IT 지점이요. IT 지점 골목길 안에 있는 거? 네 여기 예. 일단 알겠습니다. 거기 남자분 길 가다 이마 찢어졌다고요? 아 남자분은 여성분. 아 여성분이요? 지금 나와 볼게요. 길 길 가다 보시는 거죠? 네.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 예 여보세요. 아 예 선생님 119예요. 예예예. 예예. 저희 그 경찰 쪽에서 저 교통사항 왔다고 연락받고 저희 구급차 가고 있는데요. 예예예. 그 위치가 어디. 그 위치가 여기 상황심이 센트라스라는 오피스텔이거든요. 센질 아파트 가운데 있는 센트라스 오피스텔이요. 센질하고 센트라스 오피스텔하고 사이 길인 거예요? 그러면은? 아니요. 거기 밑에 스타벅스 커피숍이 있을 거예요. 위치상 보시 눌러보시면. 스타벅스요? 예예예. 센트라스 그 상가 쪽에 스타벅스 커피 거 맞은편이요. 길. 알겠습니다. 예예 알겠습니다. 수고하셨습니다.
 129입니다. 아 지금 아들이 이거 손을 유리에 다쳤는데. 탑니다. 이게. 유리에 손부상 7월이 많아서 그런 거예요? 예예예. 절단되거나 이런 건 아니죠? 예 많이 찢어서. 네 네 손가락이 절단되거나 이런 건 아닌 거죠? 지금 7월이 많고. 예 그 중에서 손등에서 손등에서. 예 거기 일단 위치 좀 알려주세요. 일단 고객청 할 테니까. 여기에 어디지 여기가? 월계 3호 아파트예요? 예 월계 3호. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네.
 네. 여기 주덕교 병원인데 응급실인데. 여기서 그 세브란스로 가라는데 택시도 잘 안 잡히고 응급차 와주시면 안 될까요? 병원에 이송된 상태에서는 다른 특히 응청선무 같은 경우는 다른 교통관이 있을 거예요. 사설 보호차라든지. 그걸 이용하시는 게 맞고요. 지금 어떤 상태예요? 환자는? 지금 그 자결통으로 네? 온몸이 타오르는 거 같아요. 누가 그러신 거예요? 딸이요. 15살 중이. 15세 딸이. 예 15살 딸. 예 자결통이 있어가지고. 자결통? 예 온몸이 타오르는 거. 지금 온몸이 타오르는 고통이 있으신 거예요? 예 그래서 지금 그지도 못하고. 고통 닫으시고요. 네. 자결통 이거 따로 진단받은 게 있으신 거예요? 아니요. 1달밖에 안 돼가지고 그냥 진동제로 먹었는데 오늘은 너무 심해가지고. 아 이게 진단받은 병명이에요? 네. 일단은 청구병원 쪽으로 구급자 편성해보는데요. 잠시만요. 알겠습니다. 차 출통시켰고요. 기침이나 열 목구멍 통증 같은 코로나 증상은 없으신 거죠? 네, 예, 예. 열도 없고요. 네. 알겠습니다. 네. 하고 있습니다.
 네. 아우. 3달 전에 또 모든 길이 있어요. 어디가 어떻게 아프세요? 허리가 너무 나빠요. 주소 좀 알려주세요. 아, 네. 은평구. 은평구. 금천구. 예. 금하로 24 다길. 금하로 24 다길. 몇 층이에요? 세진비자. 네. 혹시 열이 나거나 기침 코로나 관련 증상이 있으세요? 아 그거 없고 백신 맞고 지금 허리가 작고. 네. 세진빌라 출동하겠습니다.
 예 예 예 으흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐흐� 여기서 아무것도 접지가 안된대요. 돌풍이랑. 병원으로 가라는데. 걷지도 못해요. 아 코로나 관련된 거 있으세요? 예, 없어. 알겠습니다.
 119입니다. 네 여보세요. 네. 네 애기가 지금 열이 좀 많이 나고 중이염이라서 약을 먹고 있는데 지금 연휴라서 병원에 못 가서 와주셔야 될 것 같은데. 열이 한 몇 도예요? 39.5도에서 38도 사이로 왔다 갔다 하는데 해열제는 먹였는데요. 몸을 좀 바르르 떨리고 몸 색깔이 약간 약간 파래지는 것 같아서 지금 전화드렸거든요. 네, 예, 그 주소가 어떻게 돼요? 네, 여기 성북구 서울 성북구. 네. 도국문노. 네. 팔 가길. 팔 가예요? 팔. 네. 가나다랄 때 가. 네. 팔 가기. 몇 층에 몇 호예요? 네, HK 팰리스. 아기가 남자아이에 몇 개월이에요? 네 남자아이고요. 지금 18개월 정도 됐어요. 네 알겠어요. 선생님 그쪽으로 갈게요. 근데 일단 열이 있다 보니까 병원 선정은 좀 오래 걸릴 수도 있어요. 네 알겠습니다. 네.
 예, 여기 그 모욕탕인데요. 예, 예. 할아버지가 주셨거든요. 아 지금 의식 상태 어때요? 지금? 지금 제가 확인은 다 안 했는데 연락이 와가지고 좀 불러달라고 해가지고. 아 예, 선생님 주소는 어떻게 돼요? 모욕탕? 오목탕이요. 오목탕 몇 층에 있는거죠? 아 저희 출동 전에 그쪽으로 바로 갈건데요. 지금 의식상태가 중요하니까 의식상태는 좀 파악해서 다시 전화 좀 한번 해주세요. 예. 예.
 . . . . . . . . . . . . . . . . . I don't know what the fuck I don't know I don't know I don't know I don't know I don't know I don't know I don't know I don't know I don't know
 네, 고객님. 무슨 일이세요? 예, 저기. 여기 잠깐 내려가. 응급으로 좀 병원을 가야 될 것 같아서. 어떻게 아프신 거예요? 어 차에서 내려가 약간 그 충격에 의해서 머리 쪽에 이마 쪽에 좀. 찢어져서 치료를 좀. 네, 맞습니다. 네. 네. 머리 오셨다고요? 이마 쪽에요. 그 눈썹 쪽에 근데 좀 지금 피가 많이 나가지고. 수건으로 지여 좀 해주세요. 어떤 문자에다 그러셨어요? 우선 뭐 대중교통 택시 내리다가 했는데 약간 그 주치원 걸로. 본인께서 그런 거예요? 다른 남자분이 여쭤보내요. 같이 동행자 와이프가. 아내분이에요? 네. 대신고 주소나 정확한 위치 정보 좀 주세요. 8번 출고 바로 앞이에요. 장암평역. 장암평역. 장암. 예. 8번 출고 앞이고요. 예. 택시기사는 앞에 아직 있죠? 택시 기사님이요? 예. 아니 없어요. 거기가 내리다 그랬어요. 예. 내리다가? 예. 넘어지셔 가지고? 예. 맞습니다. 알겠습니다. 일단 차 보내드렸고. 코로나 증상은 없으신 거죠? 아 그 전혀 없어요. 그 3차 3차까지 다 맞은 상태여서. 예. 알겠습니다. 차 측정이나 가고 있습니다.
 네 열립니다. 여보세요? 네 저 여기 저 그 뭔가 저 강동구 올림픽로 올림픽로 예. 네. 저 발목이 젖히려고 저 저 저 뭔가 길 파는 게 발목이 젖히려가지고 걷지도 못해요. 아우. 앞이에요? 에트필. 네? 네? 네? 그 T 스테이션 천호 사거리 좀 지금 본인이 발목 접귀를 넣었다는 거예요? 예예 심하게 했으려고 부열라 이제 부열라 예 알겠습니다. 저희 코로나 확진 된 적 있어요? 아니요 예 플레이스테이션 천호 좀 앞으로 갈게요 예 감사합니다. 감사합니다.
 네, 이륙입니다. 네, 안녕하세요. 수고하십니다. 저 지금 호암동 주민인데. 예. 차 타고 지나가다가 그 호암 전기 그 상가 옆에. 예. 지금 사람 1명이 쓰러져서 누워 계시는데 그 취객인 것 같아요. 예. 저는 이미 차 타고 지나 와서 그렇긴 하는데 지금 네, 약간. 그 뭐 죽을 수도 있을 것 같아가지고 신고 드렸거든요. 저 호암 전기요? 네 후암 전기 후암 소방센터 옆에 잠깐만요. 후암 전기? 네 잠시만요. 저도 집어볼게요. 그 오패트라는 카페 앞에 있는데 오패트? 네 오패트 카페 앞에 있고 후암동 119 센터가 있어요. 후암동 안전센터가 있다는 거예요? 네 후암동 여기 119 센터 있어서 아까 거기로 전화를 드렸던 119에 전화를 해야 된대요. 그럼 오패트 앞으로 가면 돼요 저희가? 어 그 오패트 건너편에. 그 용산. 아 후암 전기. 네 후암 전기. 그 앞으로 가면 돼요? 네 그 건물에 쓰러져 계셨었어요. 후암 전기로 가면 되는 거죠? 네네 맞습니다. 알겠습니다. 가볼게요. 예 감사합니다. 남자였어요? 여자였어요? 남자분이요. 아저씨요. 알겠습니다. 예 감사합니다. 네.
 실례합니다. 말씀하세요. 네 여기 중양구 신내 1점 맞으세요? 선생님. 네네. 몇 몇 호세요? 예 지금 그 제가 내경 속을 알았었는데. 네. 어지럽고 막 식은땅 나고 병원 좀 가려고요. 선생님 본인이 어지럽고 식은땅 난다는 거죠? 네네네. 네 그쪽으로 구급차 보내드릴게요. 혹시 코로나 관련해서 해당 사항 있으실까요? 아니 저는 그런 거 없어요. 다 맞았어요. 네 네 네 지금 나가있을 거예요. 지금 구급차 출발을 보냈고요. 선생님. 그것 때문에 전화할 거예요. 전화 좀 잘 받아주세요.
 아 여기 저기 승용차에 그 여성분이 치웠거든요. 아 교통사고 난 거예요? 그 위치가 어딜까요? 위치가? 역삼동. 아 그 앞으로 가면 될까요? 혹시 그 뭐 차 아래 깔려있고 뭐 이런 건 아니죠? 아 예 알겠습니다. 아 고급차 그쪽으로 갈게요. 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아 아
 네, 안녕하십니까? 아, 안녕하세요? 그 애기가 지금 놀다가 제 장난감 자동차를 박았는데 그 위에가 찍어진 거 같아요. 친구자분 고급차가 필요하세요? 아니면 병원 안내가 필요하세요? 의료 상담이 필요하세요? 응급실을 가야 될 거 같은데 저희가 탈을 타고 가면은 들어가실까요? 주소 알려주세요. 친구자분. 저희 탈을 타고 가면요. 성동구? 용닭동? 저희 응급차 와가지고 응급실 가길 원하시는 거 네네네 집어 그 아이 몇 살이에요? 지금 21년생이에요 네 한 살 한 살 아이 같은 살이에요? 남자에요 네 지금 차 나가고 있고요 앞니가 부러진 것 같아요? 그런 것도 아닌 것 같아요 그 치아에 순상해간 것 같다는 거죠? 아니요 치아가 아니고요 그 위에 위천장 위에 연결된 곳 있잖아요 네 거기가 찢어진 것 같아요. 피가 안 넘쳐요. 예, 추려야 알겠어요. 지금 차 나가고 있고요. 신고자분. 저희 나가면서 그 의사 선생님도 연결해 드릴 거니까 잠시만요. 지금 차 나가고 있고 1.8km 전에 출발했고요. 그 주소 한번 확인할게요. 용답도 네, 네. 의사 선생님 연결해 드릴게요. 전화 끊지 마세요. 네, 네.
 네 저기 여기 한신 2차 저희 아버님이 지금 조금 상태가 안 돼서 성모병원을 가야 될 것 같은데. 어떤 며시인데요? 아 지금 뭐지? 거동이 안 되셔서. 의식은요? 의식은 있으시 좀 왔다 갔다 하셔야 지금. 아 그래요? 어 알겠습니다. 주소가 어떻게 되죠? 예. 짜이래는 안 소리는 안 나게 보이고. 한신 2차 아파트. 한신 2차가 신반포 2차인가요? 아 그니까 신반포로 23길. 아 맞네요 거기로 보내드릴게요 그 숨은 잘 쉬고 계시죠? 네 숨은 되시고요 연락을 나거나 기침감기 아 그런거 전혀 없을 아니 그렇지 않으세요 알겠습니다 전화 오면 잘 받아주시고 자세한 내용은 구급대원이랑 얘기하세요 예 예 예
 말씀하세요. 네 네 수고하십니다. 저 저 집사람이 집안에서 이렇게 좀 넘어섰는데 팔이. 팔 목적이 지금 많이 지금 저 저 이렇게 좀 뼈가 잘못됐는지 지금 좀 좀 못하거든요. 아 그럼 그 구급차 바로 보내드리면 되는 거죠? 네 주소가 어떻게 되세요? 여기가 국회대로 54길 네 몇 주면 되요? 안에는 코로나 관련해서 열이나 기침 이런 일상 있었나요? 그런 건 없습니다. 저희 3차 30까지 다 끝났어요. 아 네 조금만 기다려 주세요. 그 앞으로 스태어 맞죠? 네 맞습니다. 아 네 알겠습니다. 네. 네.
 119입니다. 말씀하세요. 예 지금 허리를 다쳐서 움직일 수가 없는데요. 예 119 가능할까요? 아 일단 주소가 어떻게 되세요? 예 도봉구 덕능로 61길. 덕능로 1길이요? 예 61길. 아 61길. 예 그 다음 되시라고요? 몇 층 몇 호예요? 한성 엑스빌. 누가 허리를 다친 거예요 지금? 저희 형부가 짐 들다가 허리를 다쳤어서 움직이지를 못하셔가지고 차는 지금 출발했고 환자분이 열이나 기침이나 증상이 있나요? 아니요 그런 건 없어요. 3차까지 다 맞으셨고요. 알겠습니다. 네 감사합니다.
 네, 지금 방안실입니다. 말씀하십시오. 아, 저희 지금 술 먹고 넘어져가지고 턱이랑 이빨이 턱에 파이고 이빨이 깨져서 그런데 네네네. 가까운 응급실로 들어주실 수 있나요? 네, 선생님 본인이 환자분이세요? 아니요, 아니요. 지금 성이 다쳐가지고 아 네 지금 어디로 저 보내드릴까요? 저희 성산이교 쪽으로 보내주실 수 있나요? 성산이교요? 네 성산이교 지금 다리 위에 계신 거예요? 아니요 아니요 지금 집에 있는데 일단 찾고 나가려고요 아 집에 계시라고요? 네네. 집이 집주소가 어떻게 되시는데? 성산 성산동 네네. 몇 호라고요? 네. 네 지금 차 보냈고요. 혹시 뭐 코로나 관련된 증상하고 확진자 동선이 겹치시거나 네 그런건 없어요. 그런거 전혀 없으세요? 네. 아직 이지빌라인가요? 이지빌라에요 이지빌라에요. 이지빌라. 알겠습니다. 네 감사합니다.
 1 2 5니다. 여보세요? 예. 예 코로나 아 걸렸는데 지금 어 애가 지금 숨을 수 수가 없다는데 어떡하죠? 그 누가요? 남자분 여자분. 남자예요. 숨 쉬기 어렵다는 거죠? 네네네네. 의식은 의식은 있어요? 네네. 가슴도 아프다고 그래요? 네네네. 그 남자분이 재택치료하고 계신 분은 병상을 대기 받으신 분이요. 재택치료하고 있어요. 어제 아침에 양석 자기가 나와가지고. 네 네 지금 재택치료하고 있거든요. 그 주소 좀 불러주세요. 서울시 도봉구. 네. 동명로. 동명로. 네 몇 층 몇 호요? 신창 아파트. 예. 네. 저희 차 나왔고요. 네. 그 아프시다는 이름이랑 생년월일 이름. 어 관계가 어떻게 되세요? 제가 엄마예요. 차는 나왔고요. 네. 전화 오면 잘 받아주세요. 네 감사합니다.
 예 읽습니다. 네 그 어머님이. 예예. 지금 숨이 안 쉬어 있으시는데요. 호흡이 힘드신 거예요? 예예. 어디에 위치가. 강서구 내발산동이요. 그 다음에 주소. 마구 수면삭 방법. 네. 어머니 의식은 있는 거죠? 예 있으신데 전에. 호흡이 힘드시고. 네 뇌경색 증상이 있으셔가지고. 예예. 응급실 가게 될 거 같은데 제가 전화드린 이유가 뭐냐면. 예예. 그 아사업병원 심장 내과에서 스트레스를 하셨어요. 일단 구급차를 보내드릴 테니까 병원은 대원들하고 얘기를 나눠 상의해 보셔야 될 거 같아요. 어머니 코로나 진단받고 이런 건 없으신 거죠? 없어요. 아 수명상파크 출동합니다. 예.
 네, 여보세요? 네. 예, 예, 말씀하세요. 여기 영등포역 앞인데요. 예예예. 어떤 분이 찍어서 있고 계셔가지고. 아, 누구 남성분이세요? 네. 지금 의식이랑 호가 어떠신 거 같아요? 어, 움직이시는 거 같은데 어떤 분이 출근해달라고 하셔가지고. 아, 선생님 영등포역 어디 쪽으로 가야 돼요? 어 여기가 몇 번 출고냐면요. 예. 그 영등포가 바로 앞에 있잖아요. 롯데비스 들어가는 쪽. 아 3번 출고 쪽에? 그 바로 앞에 계신 거예요? 네. 알겠습니다. 그쪽으로 가볼게요. 네.
 예. 이리입니다. 아 저 여기 저 삼성대면. 예. 당산. 당산동 5가. 어 당산동 5가. 삼성대면. 예. 예 무슨점 그러세요 지금 저 이 예 요즘 못하려면 예 아 갑자기 생각을 안 났다고 그러는데 예 이 그 배에 침 늘어가지고 예 이 돌 속에 돌이 있어가지고 예예 배가 부신거에요 지금 예예 누가 누가 그러신거에요 누가 저 우리 우리 와이프가 아 부인께서 지금 배가 많이 아프신다는 거에요? 그래서 내일 삼성병원으로 간의를 한 건데 너무 급해서 아 너무 아프셔 가지고? 알겠어요. 지금 고객차 그쪽으로 보낼 건데요. 아유 고맙습니다. 아내분 아내분 지금 열 같은 건 혹시 어때요? 열 증상 같은 거는? 열 같은 건 다 통하고 다 통했어요. 열은 없어요? 열은? 한 시간 한 시간 다 한 잔쯤에 열은 없으신 거죠? 열 열 열 같은 건 없으신 거죠? 열? 열? 예, 열 열. 열 열? 응. 열은, 열은 당연히 열은 없지. 열은 없는 거 같아요. 아, 예 알겠습니다. 손이 차고 그랬거든. 예, 불차 지금 가니까 병원 갈 준비하고 계세요. 예, 그 저 저 저 저 실제 있는데 저 저거 돌이 들어있는 거 그건 뭐라 그러지. 예, 예, 예, 예 돌이 들어있어가지고. 예, 예, 예, 예. 알겠어요. 예, 감사합니다.
 119입니다. 아 예 여기 아기가 갑자기 발사하더라고요. 열이 좀 나고 지금 지운이 터졌는데요. 네 예. 찾았어요? 지금? 의식은? 고용? 예 약간 정렬한 거 같아요. 주소가 어떻게 돼요? 예 여기 기름동 레미안 센터피스 저희가 레미안 기름 센터피스 아파트예요? 네 잠시만요 전화는 끊지 마시고요 네 아이가 의식저하도 있는 거예요 몇 살이에요 지금 지금 24개월이고요 방금 열성 방년은 한 2분 정도 한 것 같아요 그리고 지금은 약간 터져 있어요 네 지금 구급차는 나가고 있어요. 네 네 잠시만 의료 지도 해드릴 거니까 끊지는 마시고요. 네
 네 여 민주들 고시원인데요. 어디 고시원이요? 저거 여그가 광원로. 광원로. 광원로 50. 네? 어떤 그 무슨 일 때문에. 무슨 일 때문에. 아 여기 지금 뭐야 밑에 저거 미주창군씨가 틀렸었는데 지금. 아 여기 저거 사장님 저거 지금 상태가 어떠신 거예요? 다치신 거예요? 아, 벽대에서 그냥 앉아가지고 일을 하질 못 한다니까요. 의식이 있어요? 없어요? 남성분이에요? 동분이에요? 아, 지금 의식은 있어요. 넘어지신 거예요? 네, 넘어졌었나 봐요. 우리 밖에 나와있었는데 지금 혼자 넘어있을다고요. 아, 혹시 뭐 보호차 가고 있는데 뭐 출혈 같은 거 있어요? 네? 출혈은 아직 없어요. 출혈은 없어요? 예, 예. 아, 잠시만요. 그 위치 한번 찾아볼게요. 위치는 나왔고요. 네 저 빨리 좀 불러주세요. 월드 고스트회 맞아요? 예예 아니 미니빌. 미니빌? 예. 광원로? 동인빌딩. 동인빌딩. 잠시만요. 아 그 글로 가고 있어요. 혹시 뭐 코로나 관련 경제 있으신 분 안 계시죠? 네 그런 건 없어요. 그냥. 올라가야 되죠 이거? 예 알겠어요 빨리 갈게요. 환경에 의식 호흡 상태 다 괜찮은 거 맞죠? 예 예 의식은 있어요.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 예. 고생하십니다. 말씀하세요. 아 예. 시간이 숨을 못 쉬어가지고 갑자기 너무 힘들어야 하는데. 예. 알겠습니다. 그 주소 어떻게 되세요? 선생님. 어 방학 중. 잠시만요. 위창 보고요. 방학 중. 위창을 볼게요. 선생님. 이 몇 층 몇으로 가면 돼요? 아 다세대 남편 분께서 의식은 어떠세요? 식은땀 흘리고 기침을 하고 가슴이 너무 쪼여워서 예 알겠습니다. 그 혹시 열도 나세요? 열은 없어요. 코로나 관련해서? 아 열은 없으시고 어 그거 없고 지금 식은땀이 나고 주병도 없으신데 갑자기 그러시는 거예요? 네네 아 예 알겠습니다. 제가요 의식이 없거나 그런 거는 아닌데 힘이 없어서 어떻게 혼자를 못하겠어가지고 아 예 알겠습니다. 저희가 응급처 좀 알려드릴 테니까 전화 끊지 마세요. 선생님 전화시켜겠습니다.
 119입니다. 네 수고하십니다. 여기가요. 그 신내동 그 중단구청 앞에 신내동 성모정형외과. 네 무슨 일이세요? 예예. 급히 좀 출통 좀 해주세요. 누가 어떻게 아프신 거예요? 지금 자꾸 숨을 못 쉬어요. 아 누가 남자분이세요? 여자분이세요? 여자 여자 여자 66세 여자. 성모 정형외과 의원 건물 맞죠? 예예. 그 건물 네. 의식은 괜찮으시고요? 예. 저 의식은 괜찮고요. 다리가 지금 고장 나서 다리가 부러져가지고 다리 1를 못 쓰기 때문에. 알겠습니다. 선생님 그 환자분이 코로나 관련자는 아닌 거예요? 아 아닙니다. 아닙니다. 없습니다. 알겠습니다. 네. 알겠습니다. 전화 오니까 전화 주세요. 예예.
 119입니다. 네 환자가 그 뭐지? 응급 차량 좀 할 수 있을까 해서요. 환자가 거동이 어려워서 119로 응급실 가셔야 되는 거예요? 계신 곳 주소 알려주세요. 환자분 계신 곳 주소. 여기 서대문 고공운동. 네. 환자는 본인이세요 아니면 가족분이세요? 가족이요. 아, 아내분이세요? 어머님이세요? 아버님이세요? 와이프요. 아내분. 어디가 어떻게 아프신 거죠, 지금? 원래 세브란스 병원을 지금 다니고 있었는데 네. 네, 근데 거기에 지금 아픈 곳. 지금 가장 아픈 곳. 지금 복수처에서 암 환자거든요. 아, 무슨 암 환자세요? 어, 잠시만요. 예 거기 암센터에서 종양내과 암 환자인데요. 복수치료를 마지막 받고 온 지가 열흘이 넘었는데요. 거동도 못하고 지금 뭐 볼리지 못하고. 무슨 암 환자세요? 무슨 암? 심장암이요. 심장암. 심장암 환자인데 복수가 찬 상태라서 거동 상태라서 거동이 안 된 상태. 네 지금 거의 탈수 증상이에요. 탈수 증상도 있고요. 네. 뭐 의식이나 호흡 같은 건 괜찮으신 거죠? 네 뭐 코로나 호흡 기준으로. 네 코로나 아무 열 기침 뭐 이런 것도 없으시고요. 네 독수랑 탈수 증상 때문에만 그러신 거고요. 네 네 네. 고차 홍운동. 네 네. 가고 있으니까 병원 준비하시고 문 열어주세요. 가고 있어요. 네.
 여보세요? 예, 119예요? 지금 수강했고요. 환자 상태는 확인 가능한가요? 현재? 아니 제가 지금 여기 와서 저기 관리자한테 신고하려고 올라왔어요. 아 예, 알겠습니 환자 뭐 일주 없거나 숨 못 쉬거나 이런 거 아니죠? 그런 건 아닌데 그냥 그냥 확 쓰러져가지고서 그냥 자고 있어요. 쓰러진 상태 알겠어요. 그럼 주통에서 확인하시면 주통 감사드립니다. 네, 네. 네. 딱 갈게요.
 네 여기 3단지인데요. 주공 3단지인데요. 아 근데 환자가 지금 이제 그 응급실에 가야 될 것 같은데. 네 주소 좀 알려주겠어요? 여기 도봉구 도봉로. 도봉로. 여기 주공 3단지. 어디 무슨 주공이에요? 여기 창동이요. 창 1동. 창 1동 주공 3단지. 예예. 예 누가 어떻게 아프세요? 아 여기 환 저기 산모가 아니 산모 아니 애기 났지. 배가 너무 아파가지고 잠시만요. 여보세요? 예 누가 보신 거예요? 아 저희 딸이요. 딸인데 애기 엄마인데 지금 저기 배가 너무 아프다 그래가지고 병원에 가야 될 것 같아서요. 여보세요? 저희가 서울 전역을 다 받아요. 그래서 아파트 이름 정도는 바로 얘기해 주세요. 상동 주봉이라고 그랬죠? 상동 주봉 상단지. 예 알겠습니다. 차 보냈어요. 여기 저기 조금 움직일 수 있으니까 지금 내려가 있을게요. 애기가 있어서. 네네네 얼마 한 10분 걸려요? 썸문동에서 지금 출발시켰어요. 한 10분 정도. 알겠어요.
 네 고생하세요. 여기 서초 2 파출소 예 고생 많으신데 고생이 계세요? 예 여기 주취도 이제 정신 잃은 여성분이 있으신데 몸을 좀 많이 떨어먹고 사진 좀 드린다고. 오한 증상 있으시고요? 의식적으로? 예 예. 예 의식은 있는데 오한이 좀 있어요. 아 의식은 있고 오한증상. 예. 서초 2 파출소라고 하셨죠? 예 맞습니다. 잠시만요. 예. 아 전화번호 이쪽 뜨는게 지금 서초 경찰서로 떠요. 우리 서초 입하철소 주소가 어떻게 되세요? 서울로 서울로 음 지금 차 결정해서 보내드렸고 전화 드릴 수 있는데 혹시 지팀이나 목구멍 통증은 없으신거에요? 그건? 예 지금 채운하고 측정했는데 이상은 없어요. 이상 없으신군요. 알겠습니다. 참 축하합니다. 예 고맙습니다. 수고하십시오.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 예, 누구입니다? 아 예, 저기 환자 1분 있어갖고 집인데요. 여기 예, 누가 아파요? 어머 어머님이신데요. 네. 어머님이신데 지금 원래 암 치료 중이셨는데 네. 지금 많이 안 좋으셔갖고 의식을 거의 의식이 떨어져요? 아니 아까 여기도 의식이 한 3 40% 좀 있으셨는데 지금 더 떨어지신 것 같아요. 그래서 지금 여기가 저기 강서구 방아 1동 3종 코어 아파트요. 방화동 3종 아파트요. 3종 아파트 몇 동 몇 호요? 그냥 동 1고요. 몸이 너무 차가워서요. 가족분들 중에 코로나 지역 다녀오거나 관련 증상 있나요? 아니 전혀 없어요. 현재. 없으세요. 예예. 방안 1동. 삼정 아파트 치면 되는데. 길이 샘이 뭐야? 삼정? 아 삼정 그린코아? 예예. 알겠습니다. 삼정 그린코아. 가볼게요. 예예 고맙습니다. 네. 감사합니다.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네. 안녕하세요. 그 갑자기 2 30분 전부터 오른쪽 옆구리가 너무 아프더라고요. 구호차 주소하세요? 네네. 주소 알려주세요. 여기가 동작구 상도 3동 네. 우리 빌라. 우리 빌라. 잠시만요. 네. 네. 남자 여자 여자친구? 여자분이세요. 여자분. 옆구리 통신이요? 네. 네. 연락하나 코로나 관련 증상 있나요? 어 아니요 없으세요. 네. 의식이나 그런 것도 다 괜찮으세요? 네 괜찮으십니다. 네. 차 나가볼게요. 전화 잘 받으세요. 네. 감사합니다.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 예 1 9입니다. 예 여기 저 광서구 양천론데요. 양천론? 예예. 양천론에? 그레이스 잠시만 기다려 보세요. 그레이스 예예. 예예. 이게 지금 2사람이 갑자기 상태가 많이 안 좋아서. 숨쉬기라든지 숨쉬기 힘드세요? 아니면 어디가 안 좋아서요? 숨쉬기가 힘들고요. 통화가 떨어지고. 통화도 몇 나왔어요? 85 6 이렇게 나와요. 5에서 6 의식은 있으신가요? 예? 의식은 있으신 거예요? 의식은 있고 그런데. 아버님 자 그 분이 빨리 나감 전에. 자 제 말씀 들으세요. 코로나 관련된 증상 여행용 특이사항 있었어요? 혹시? 그건 없었어요. 총 코로나까지 3차마다 늦게 됐어요.
 119입니다. 네 여기요. 네. 당뇨 환자인데 뭐 어떻게 되는지 모르겠네. 나는 자꾸 저기 일부 좀 와주셔야 되겠어요. 누가 누가 당뇨 환자예요? 남편이요? 딸 저기 48살 된 딸. 딸이 48살인데 당뇨 환자인데 어디가 아프대요? 뭐라고 한다면 난 못 알아듣겄어. 그래서 그 댕기는 병원에다 전화 했더니요. 네. 미국 불러갖고 응급실로 가라 돼. 일단은 주소 불러주세요. 주소. 여기 남현동. 남현동? 남현동. 네. 남현동 가맣고 남현동 승방 10길. 승방식길. 네 저기요. 아 3원 하이츠빌라. 무슨 하이츠빌라요? 네. 3원 하이츠빌라. 저희 혹시 따님이나 가족분들 코로나 관련해서 기침 마련 전산 있다거나. 그거 아니에요. 그거 없어요? 당뇨에 대해서 합병증은 와요. 일단 알겠습니다. 모르는 번호 전화 받으세요. 모르는 번호 전화 전화 받으시라고요. 전화 받으라고? 네. 그 공사 지도했으니까 모르는 번호 전화 전화 받으세요.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 예 예 그 오피스텔 이름이 뭐예요? 여보세요? 네 제가 아까 이거 도폐 다 안 해도 오고요. 네 그니까요. 거기가 어디냐고요. 고산자로 29번제 네 고산자로 고 3자로 20. 잠깐만요. 고 3자로. 네. 아까 고 3자로 20 필요해. 네. 알아요. 끊지 마세요. 나 어디서 아무나 나 이제 내 집 갔다 오면 어디서 나 주로 받아야지. 여보세요. 저 출발했고요. 그 몇 층이에요? 아 여기 저기 여기 건너 있어요. 아 그냥 폭행을 당했다고요? 최근에 코로나 관련된 건 없죠? 네 저희 나와드 테니까 앞에 계세요. 전화드려 봐주세요. 예.
 119입니다. 예 제가 누구한테 맞아가지고 눈이 반 감겼는데 좀 빨리 와주실래요? 예 거기 위치가 어떻게 되죠? 여기가 위치가 그 경희대 경희대 경희대 경희대학교 아니에요? 네 경희대학교 동대문구 회계로 네 경희대학교 어디쪽으로 가야되요? 학교가 크잖아요 어 경희대학교 그 그 고대쪽으로 가는쪽에 회기록 지금 눈이 이렇게 감겨가지고 눈이 아 흩어났는데 선생님 그러니까요 뭐 법과대학 뭐 대강당 뭐 중앙도서관 어디쪽이에요? 어 수학 동대문구 회기록 회기록 예. 잠깐만요. 빨리 와주실래요? 동시에 고급차는 제가 출동 요청했고요. 회기로 식량 경희대점이라고 그 대학교 안은 아닌데요. 맞으세요? 탑출소 앞이고요. 회기로 앞으로 가면 되는 거 맞아요? 네, 지금 급해서 그런데 예, 선생님 코로나 환자는 아니신 거죠? 예, 아닙니다 예, 출동했으니까 전화할 거예요, 잘 받아주세요 네
 실례합니다. 네 여기 지금 어 영등포 3개 영등포로 3개 이게 오목교 코어 네이런스 네. 문 앞인데요 여성분이 좀 복부에 좀 누워있으세요? 숨을 쉬고 있어요? 숨을 쉬고 있네요. 손은 다칠게요 일단 선생님 그쪽으로 국제 보낼게요. 환자분 의식 대화는 가능하신가요? 네 그 대화는 가능한 상태로 위시드릴 수 있는 거예요? 그냥 틀어져 주세요. 숨 마시고 있고. 그쪽으로 고객님께 보냈습니다. 기다려주세요.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네. 네. 말씀하세요. 아, 지금 본인이요? 잠시만요. 아, 근데 지금 음북스 가셔야 되는 거죠? 네. 저 머리를 심하게. 머리를 부딪쳤어요? 네. 잠시만요. 7월 있진 않아요? 예 7월은. 예 문을 열어주실 수 있어요? 문 열어주실 수 있어요? 어 없어요. 그냥 누워있어. 지금 못 움직이고 누워있어요? 네 잠시만요. 그러면 비번 알려주시면 저희가 혼자 계신 거예요? 네. 예 주소가 어떻게 되시죠? 수능선파크 4단지예요? 음 비밀번호가 집 비밀번호가요? 네 네. 예 기호는 없어요? 숫자만 누르면 돼요? 네 네 네. 숫자가 기호 같은 거 안 누르고 네 알겠습니다. 가서 혹시 문자면 다시 전화드릴게요. 받아주세요
 네 그 그 그 가슴 통증이 너무 심해가지고. 그 백신 도작용 때문에 그런 거 같은데. 혹시 그 119 거 좀 보내주실 수 있나요? 네 지금 친구가 본인이 그래요? 아니요. 저는 아니고. 옆에. 네. 옆에 누가 아프니까? 아 옆에 여자친군데. 여자친구가요? 네 숨을 지금 걸고. 호흡받는 친구가 있다고요? 네. 순식이 되어있으라고. 네. 일식은 괜찮은데. 네. 순서가 어떻게 돼요? 여기 장안복꽃로. 잠시만요. 장안복꽃로요? 네. 여기 희경. 장안복꽃로예요? 네. 네. 희경행복 아파트거든요. 아 몇 동 몇 개요? 네 친구 열이나 코로나 발생 있어요? 아니요 없어요. 네 알겠어요. 혹시 거동 가능하나요? 네? 거동. 네 1층까지 내려가실 수 있습니다. 전화 받으면 1층 내려가세요 그럼. 네. 예.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 실례합니다. 아 네 죄송한데요. 여기 그 미도관 1자가 있어가지고 촬영을 하고. 어디신데요? 주소가 강남구 도곡동. 네. 조금만 진정하시고 똑바로 1번씩 불러주세요. 아 예. 아 예. 아 예. 아 예. 아 예. 아 예. 아 예. 아 예. 아 예. 아 예. 아 예. 아 예. 아 예. 아 예. 도곡동이요? 아 예. 아 도곡 카운티? 예. 지우엘 카운티 인자 지우엘 카운티? 일단 바로 보내드릴게요. 무슨 어떻게 하는 환자인데요? 아 저기 암 환자인데요. 입원을 하고 있다가 항암 치료 받고 퇴원을 했는데. 지금 어디가 안 좋으신데 지금? 지금 잘 못하고 허리 아프고 배 아프고 해서 뭐든지 가요. 의식도 좀 많이 저하되어 있고요. 숨을 쉬시는 거예요? 네 그런 거는 괜찮은데 사병원 군단 사병원 쪽으로 가서 입원을 해볼 건데 네. 저기요. 차정은 응급실로 아 예. 일단 자세한 거는 구급대환이랑 얘기하세요. 제가 여기서는 병원은 정해드리기 어렵고요. 구급대환이 보고하는 거고 저희는 죄송한데 원래는 근거리 응급실로 이용하게 돼 있어서 자세한 건 구급대환이랑 얘기하셔야 돼요. 상태랑 뭐 제가 하는 거랑 얘기해 보시고. 아 예. 연락 나거나 기침 감기 증상 코로나 정리 중이신 거 같으시죠? 그런 거 어저께 입원했다가 회원했다가 다시 입원하니까. 네. 알겠습니다. 전화 오면 잘 받으시고 자세한 내용은 구급대원이랑 얘기하셔야 돼요. 네. 알겠습니다.
 119입니다. 예 수고하십니다. 여기 장희동인데요. 그 환자가 있어가지고 쓰러져갖고 지금 어저께 새벽에 쓰러졌는데. 집에 있는데 뭐 계속 머리가 막. 그분이 여자분이에요? 남자분이에요? 여자예요. 지금 의식은 있고 호흡도 하는데 머리가 아프다 그러는 거예요? 예예 밥도 못 먹고. 지력이 없고. 쓰레기 쓰레기 안 돼있다가 쓰러졌었거든요. 네 주소가 어떻게 되나요? 송북구 장월로 이길. 장월로예요? 예. 네. 네. 네. 네. 네. 혹시 가족 중에 코로나 환자나 고여기침 인원증증서에 있는 분 있어요? 네 없습니다. 예 아드님 되시죠? 예. 아니 저 여기 아는 지인이에요. 지인이에요? 예 알겠습니다. 예. 예.
 네, 즐겁니다. 네, 낮에 한번 전화해서. 네. 어 저기 했는데 죄송해서 또 전화했어요. 지금 또 아프다고. 누가요? 우리 아저씨가. 어디가 아프신 거예요? 예. 여기 배 배가 아프대요. 아까 3시쯤에 가서 그 오줌이 안 나오고 그래서. 깨고 와서 괜찮았거든요. 근데 자다가 또 아파가지고 어떻게 할 수가 없어서 전화드렸어요. 아 또 병원에 가보시라고 하시는 거예요? 예. 잠시만요. 소환주택 맞아요? 네네. 잠시만요. 주소가 역촌동에 파안주스테 혹시 보다 관련해서 열이나 기침 호흡관련 같은 건 없어요? 예 없어요. 그런 건 없고 그 역전동에 예 역 역말로 역말로? 네. 잠깐만 잠시만요. 지금 신주소 말씀하시는 거예요? 구주소 말씀하시는 거예요? 신주소요. 구주소로 할까요? 예 구주소 말씀해 주세요. 구주소는 역촌동. 그냥 신주소로 할게요. 아까도 신주소로 했는데. 영말로. 아 예 알겠습니다. 선생님. 시작할게요. 네. 네.
 1 2 9 입니다. 여보세요. 1 2 9 에 말씀하세요. 너무 아파서 그래요. 여보세요. 1 2 9 에요. 예. 너무 아파서. 네. 너무 아파서요. 네. 그래서 저랑 가실 거예요. 너무 아파서요. 친구 3 분. 여보세요? 너무 아파서 그래요. 그래서 지금 병원 응급실 가실 거예요? 네 너무 아파서. 주소 불러주세요. 이 찍혀 나온 거 없어요? 네 주소 불러주세요. 주소 봐요. 네. 잠시만요. 네. 광고리노 가만있어. 주소가요. 네 말씀하세요. 네. 아이 주소가 여기네. 서울특별시 중구. 중구? 중립로 2길. 중립 공정 빌라 중립로 2길 예 중립로 공정 빌라 공정 빌라 예 신고자분 지금 어디가 아프세요? 허리가 많이 아파요 허리가 많이 아프세요? 예. 네 그래서 그래서 지금 병원 응급실 가신다는 거죠? 너무 아프니깐요. 네 병원 응급실 가실 거죠? 예. 그쪽으로 보급자 보낼 거고요. 혹시 코로나 관련해서 열 기침 있으세요? 예? 코로나 관련 증상이 있으세요? 열 기침 그런 건 없어요. 코로나는 1차까지 다 맞았어요. 제가. 네 그쪽으로 보기차 보내드릴게요 조금만 기다리세요 병원 가신다고 해서 보기차 보내드린거에요

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 119입니다. 여보세요? 저 동아부라 아파서 상계동. 네? 상계 3개 3동. 상계 33동이요? 아니 상계 3동. 동아부라 아파서. 무슨 일이네요. 내가 내가 그 중고 같으니까. 네? 빨리 좀 빨리 중고가 세지로 중고가 지금 빨리. 예예 미안합니다. 나 2일이 잘하는데 어디 아프는데? 아이고 뭐 못 시겠어요. 어디가 아프신거죠? 자살을 하고 하시겠다고 하시는거에요? 아 걸은거 못 걸어 지금. 동아프라 아파트 어디가 제일 아파요? 어디가 제일 아파? 아우 오면 왜 아우 오면 열이나 기침이나 이런 거 없으신 거죠? 열 기침 열 코로나 무섭잖아요. 열 기침 이런 거 없으신 거죠? 술 드신 거죠? 술 술 나보다
 네, 읽습니다. 작년 1잔인데요. 네, 네. 막 가슴이 막 바빴다고 숨기기 힘들어갖고. 저희 어디로 가야 돼요? 주소 알려주세요. 방학 1동. 네. 몇 층 몇으로 가야 되나요? 제가 밖에 나가 있을게요. 코로나 관련 고요 기증 관련 증상 같은 거 없으시죠? 어저께 코로나 검사 맡았는데 음성 문자 날라왔거든요. 네, 잘 나왔습니다. 네.
 네, 여보세요? 네, 듣고 있습니다. 무슨 일이세요? 애기가 경기가 좀 있는 것 같아요. 열 나요? 아니요. 열은 안 나요. 지금 몇 살이에요? 7살 남자의 여자예요? 여자예요. 여호호 호흡은 잘하고 있죠? 네네. 예 그 주소 불러지 빨리 나가서 도와드릴게요. 여기 중국도 샤인 소아과예요. 샤인 소아과? 네네. 예 주소지 모르시니까 제가 한번 검색해야 됩니다. 잠깐만 기다리세요. 네. 샤인 소아과. 샤인 소아 청소년과 의원 나옵니다. 네 맞아요. 아 몇 층에 지금 계세요? 병원 안에 있어요. 병원 안에 그러면은 뭐 소아과에서 어떻게 치료가 안 돼요? 네 응급실 바로 가셔야 될 거 갔다 가셔서. 알겠습니다. 코로나 관련 코로나 관련 환자는 아니시고요? 아니에요 아니에요. 예 알겠습니다. 전화 끊지 마세요. 의료 안내원까지 연결해 볼 거예요. 네.
 네, 누구입니다. 말씀하세요. 여보세요? 아 여기 사고 났거든요? 뭐랑 뭐랑 사고 났어요? 지금 오토바이랑. 오토바이랑. 오토바이랑. 네. 제 차랑 다 왔거든요? 아 차랑이요? 네, 네. 환자분 몇 명이에요? 지금 1명이요. 지금 딸이 왔어요. 위치 어디예요? 지금 반포 레미안이요. 반포 레미안이요? 네네 그냥 앞에 보이는 가게 상호명이나 이런거 하나 불러주시겠어요? 신한은행이요 신한은행이요? 네네 환자분 남자야 여자에요? 남자요 남자분이요 차 나가고 있구요 의식이랑 호흡 다 있으신거죠? 네네네 아 네 신고자분은 차량 운전자분이시구요? 네 맞습니다 네 알겠습니다 차 나가고 있어요 네

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네. 네. 네. 여보세요? 여보세요? 119 상황실입니다. 아 예 선생님 안녕하세요. 예. 숨 안 쉬시는 거예요? 예예. 아 전화 끊지 마시구요. 실패 안내할거니까 끊지 말고 기다리세요.
 네 읽습니다. 아 이거 죄송합니다. 여기 저 화복동 아줌마가 지금 아파가지고 물경량이 되는데 지금 뒤뚤고 있는데 병원에 좀 가야 될 것 같아요. 반복 보관 많이 아프시고 몇 층으로 복잡을 나가면 돼요? 그 위층이거든요. 위층이 뭐 3층 건물이 이제 지하층이기 때문에 코로나 진단받고 열기증 가리 이런 증상은 없는 거죠? 네 그런 건 없습니다. 알았습니다. 국차가 화곡동에서 나갈 거예요. 대원들 가면서 전화드릴 수 있습니다. 네 고맙습니다.
 안 괜찮아? 여보세요? 아 여보세요? 네 할머니가 넘어지셔 가지고. 그 주소가 어떻게 되시죠? 아 동남동 포리나 아파트. 네. 어디를 다치셨어요? 다리가 오른쪽 다리가 많이 아프시다고 하시거든요. 허벅지 있는데요. 엉덩이 있는 데랑. 허벅지 다리요. 여기 다리. 일단 그쪽으로. 활동시켰는데. 혹시 열나거나 기침하거나 코로나 증상 이런 거 있으셨어요? 심하거나 코로나 증상 이런 거 있으셨어요? 아 그런 건 없고요. 근데 할머니가 백신은 안 맞으셨거든요. 네 상관없고. 네 일단 그런 증상은 지금 없으시다는 거죠? 할머니? 예. 알겠습니다. 지금 일단 집단할게요. 네.
 예. 예. 저 119 상황실인데요. 선생님 그 아까 그 2시 중 2시 중 중에 구급자 출장했었잖아요. 예예. 그 병원은 안 가셨어요? 왜? 지금 가시고 지금 막 다리가 너무 예를해요. 지금. 지금은 가실 거예요? 예 예 예. 예 알겠습니다.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네, 119입니다. 말씀하세요. 여기 홍대 수취 폴목인데 사람은 없죠? 주 다방 있는데 하나만 넘어. 무슨 다방이요? 주 다방이요. 주 다방. 주 다방이라는 곳이에요? 네, 네, 홍대 쪽이에요. 주 다방이요. 괜찮아요. 여자야 남자예요? 남자분이 지금 혼자 넘어가지고. 네, 머리에. 의식은 있어요? 네? 의식은 있어요? 의식? 네, 네, 네, 네, 네, 네, 네. 선생님 주 다방 말고 다른 거는 뭐 없어요? 1 9 4 3이요. 1 9 4 3? 네. 저 앞으로 가고요. 남자분 의식은 있고 머리 쪽에서 치료하시려는 거죠? 네. 혹시 대화 가능하세요? 뭐라고요? 대화 대화 가능하세요? 아니 아니요. 그. 코로나 관련 그 그 분 뭐 일행들 없어요? 네네. 잠깐만요. 이쪽으로 그냥 와주실래요? 아 제가 이쪽으로 여기 여기 앉아있어 앉아있어. 저희 저희 보호복 착용으로 갑니다. 이쪽에 앉아 앉아 앉아 앉아 앉아 앉아
 예, 1 6 9입니다. 1 6 9입니다. 여보세요? 예, 말씀하십시오. 1 6 9입니다. 예, 사거리 미래 미래 타워 앞인데요. 어디 사거리요? 왕신이 사거리요. 예, 미래 타워 앞에 무슨 일이에요? 아 저희 어머니가 갑자기 좀 쓰러지셔갖고. 의식 있으세요? 예, 조금 있어요. 조금. 아 우선 우리 차는 출발 시켰고요. 예, 예. 숨 쉬는 거 괜찮으세요? 숨 쉬는 거? 예, 근데 좀 어머니가 좀 많이 편찮으시거든요. 원래? 아 그래요? 예. 차는 나가고 있어요? 나가고 있는데 지금 어디가 안 좋으신 거예요? 지금 의식 정신을 못 차리시는 거 같애. 눈동자가 지금 틀렸어요. 조금. 불러도 전혀 대답 못 하세요? 아이 그 정도는 아닌데 눈이 많이 틀렸어요. 저 아드님이 물어 저 불르면은 대답은 하시고 아드님 알아봐요? 예예. 아 알겠어요. 미래 타워라고요? 예 미래 타워 왕십리 4벌이요. 왕십리 저 왕십리역 있는데 거 오거리 말씀하시는 거죠? 예예. 오거리에 있는 저 미래 타워? 예 미래 타워 옆에 9번 출구 앞에 9번 출구 앞에 아 차 나가고 있어요. 예예

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네 119입니다. 무슨 일이세요? 아, 이리 몰라요. 아, 이리 몰라요. 아, 이리 몰라요. 안녕, 안녕, 안녕, 안녕. 안녕, 안녕, 안녕, 안녕. 충격이 왔어, 충격하시고. 네, 무슨 일이세요? 예. 저기. 예. 그 틀어졌어요. 의식 있어요? 없어요? 쓰러지신 분이? 예. 의식이 지금 어 저희 쪽은 모르는 것 같아요. 할 생각이 없었어요. 의식이 저한테 숨 쉬세요? 숨. 예. 숨 쉬는데 지금 그. 왜 쇼꼬박이셨어요? 예. 음 일단 알겠습니다. 기다리고 계시고요. 예. 그 구로에서 금방 갈 거니까. 기다려주시오.
 수고입니다. 아 네 여기 저기 그 응급 환자가 있어서 전화드렸는데요. 남자분이 여자분이 환자분이요? 예 할머니예요. 저희 엄만데. 네. 어머니 어디가 없으세요? 아 원래 내경색 그 환자인데요. 그 갑자기 그 예 지금 팔다리가 갑자기 힘이 빠지면서 지금 저기 침대에서 내려오다가 그 홍성실 하려다가 너무 콩초리 나서 넘어져서 네네. 그런데 다림 탈림이 다 빠졌 다림이 다 빠져갖고 지금 못 일어나시거든요. 거기 주소가 어떻게 되죠? 지금 병원 응급실 가실 거죠? 네네네. 주소요? 아파트예요? 신정 네 신정 이탠하우스. 이탠하우스. 3단지. 3단지. 예 그렇지. 네네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 잡아서 침대에 눕혀놨는데 그 예 저기 다리에 힘이 빠졌는데 넘어지면서 머리도 콩 소리가 났는데 의식은 의식은 괜찮으신데 다리에 힘이 다 빠져서. 지금 구급차 가라고 했으니까 조금 기다려주세요. 네.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 예, 여기 7호선 그 어린이 대공원 방향 수영장이거든요. 그니까 7호선 어린이 대공원 여기에요? 예. 아니 아니 분자역이요. 분자역이요. 분자역이에요? 내렸어요 지금? 방향은 방향은 어디 방향인데요? 어린이 대공원 방향이요. 방향이고 몇 다시 몇 지점이에요 그러면? 여기가 5 다시 레레베이터 앞이에요. 5 다시 1 지점? 예. 그 뭐 아프신 분이 있어요? 그 여기 할머니 분이 학습하시다가 그 공간에 다리를 놓고 넘어지셨어요. 아 넘어지셨어? 다리가 아프다 그러시거든요. 다리를 다리가 아프신 것 같아요? 예예예. 군자역으로 문자 보내드릴게요. 예. 군자역 승강장 방향 거리 이동 방향 5 다시 1 지점 네. 출동합니다. 예.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 여보세요? 선생님 주소 아시면 구 주소를 한번 말씀해 보세요. 저기 기름동 네. 네 알겠습니다. 감사합니다.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네. 수고 많으세요. 네. 네. 말씀하세요. 네. 여기 양천구 오목로 19길에 제일 아파트 양천로 오목로 19길에 네. 무슨 아파트요? 제일 아파트 제일 아파트 네. 어떤 것 때문에 그러세요? 네. 저희 아버님이 심부전증을 앓고 계시는데 심이요? 심이요? 심 심혈관 심부자증 네 근데 지금 어떠세요? 아버님이요? 예 투석도 하고 계시고 하는데 상태가 좀 안 좋으셔 가지고요. 의식 있어요? 없어요? 의식은 다 있으세요. 네 상태가 안 좋다는 거죠? 의식은 있어서 네 저희가 가게 되면 병원 응급실로 갈 거고요. 혹시 치료자분하고 아버님하고 가족분들 코로나 관련해서 여린아기팀 있으세요? 없어요. 그런 거 없으시고요? 네네. 양천로 오목문 19길. 19길에. 제일아파트. 네네. 아 네 알겠습니다. 어 그 그게 제일아파트가 제일캐슬인가요? 예. 제일캐슬아파트. 아 네 알겠습니다. 그쪽으로 공유장 보내드릴게요. 네. 감사합니다.
 예, 옵니다. 아 여기 여기 은빛 아파트. 집 앞에 앞에서 다 죽어가요. 은빛 아파트 몇 동 몇 호요? 남자분이요? 여자분이요? 우리 아저씨요. 의식은 있어요? 예? 의식은. 그. 은빛 아파트가 맞아요? 요 요 요 은빛 아파트. 그 무슨 구 무슨 동 무슨 아파트요? 은빛 아파트. 은빛 아파트에. 어이가 나 기다려. 그 차 보냈고. 얼른 문자 와주세요. 그 차는 보냈고요. 잘 받아주세요. 전화 오면 잘 받아주세요. 네.
 예. 예 119에요. 예 여보세요. 여보세요. 예 그 바로 앞에 거에는 건물 이름 하나 좀 얘기해 주세요. 네. 바로 앞에 거에는 건물 이름 하나 얘기해 주세요. 저희 지금 가볼 테니까요. 건물이요? 네네. 네 사거리 한의원이라고 있거든요. 사거리 한의원? 네 아니면은 그 답심리 쪽 BYC나 그 답심리 동원 맞아요 거기? 네 답심리 사거리요. 차영석 사거리 가기 전 답심리 사거리요. 가볼게요. 네.
 감사합니다. 아 네 어머니께서 지금 몸 저기 뭐 쓰러지셔 가지고 혹시 119 좀 부탁 빨리 좀 부탁 좀 드릴 수 있을까요? 주소 어떻게 돼요? 강동구 준천동. 네. 매칭 매터예요. 네, 네. 계단이 좀 있어요. 쪼끔. 어머니 숨으셔요? 예, 예. 지금 좀 빨리 오시면. 아 빨리 갈 건데 옆에 계세요? 어머니? 아니 지금 저는 이제 바로 가중 중이고 지금 약간 몸이 이제 약간 의식이 약간 왔다리 갔다리 하시는. 네 차는 나가고 있고요. 네. 길동에서 출발해서 가고 있어요. 혹시 지금 현장에 연결할 수 있는 전화번호 하나 있나요? 현장이요? 예 어머님 혼자 계세요? 아니 아버님 옆에 계세요. 지금 빨리. 차는 가고 있어요. 예 010. 저도 지금 저도 가고 있으니까 오시면 될 것 같은데. . 알겠습니다. 잠깐 할게요.
 예, 1급입니다. 예, 신월 1동 시티 하우스인데요. 신월 신월 1동에 있는 시티 하우스요? 예, 예. 네, 하우스 몇 몇 호예요? 와이프가 턱인데 찢어져 가지고 그러는데 좀 고청해 주시면 안 되시나? 예, 응급씩 응급씩 가야 될 거 같아가지고. 예, 여자분요. 예. 턱요. 턱. 예, 예. 지저짐요. 그리고 코로나 관련해서 의심할 만한 거 혹시 없었나요? 이 연락을 기칭 나고 이런 건 없어요? 예 없어요. 없어요. 선생님 그게 시티하우스가요. 예예. 그게 본지 수는 모르시나요? 양 양천구시 월종로 31길 30 월 월종로예요? 월종로? 예 31길 월종로. 쉽게 알았어요. 예 접수됐고요. 있어요. 접수됐고 빨리 갈게요. 예 예 가면서 가면서 전화하면 전화 잘 받으세요.
 네 여기서 밤뿌 풀. 밤뿌 풀은 집 아파트. 밤뿌 풀은 집. 우리 집사는. 예? 예? 사모님 있어요? 의식 있어요? 없어요? 사모님? 있어요? 좀 빨리 좀 빨리 좀 의식은 있어요? 네 알겠습니다. 이쪽으로 할 거고요. 친구자분 네 친구자분하고 사모님하고 별이나 계침 있어요? 없어요? 여기 계침 아니 뭐 저기 아 친구자분 지금 구구 차량 가라고 했고요. 네 저희 반포 프로젝트 네. 사모님하고 선생님하고 코로나 관련 증상이 있어요? 없어요? 아니. 그런 거 없어요. 지금 사모님 무슨 약을 드신 거예요? 약을 얼마나 드신 거예요? 원래는 정치과 약을 먹고 있는데요. 네. 한 알 먹었을 때 열 개를 먹었대요. 그러니까 열 알 드신 거예요? 네. 지금 의심이 있는 거죠? 네. 그쪽으로 전화 받는 사람이고 아까 통화 중에 거기서 안 하고 있으니까 조금만 기다려 주세요. 네. 반포 푸르지역 신고자분 조금만 기다려 주세요.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네, 네, 감사합니다. 와이프 양수가 터져서요. 네, 구급차 여쭤던 거예요? 네, 네. 주소가 어떻게 돼요? 어, 고동로 20 나길? 20 나길? 몇 층 몇 도예요? 그 가족분들 중에 코로나 관련 지역 다녀오거나 관련 증상 있나요? 아니요, 없습니다. 네, 구급차 가볼게요. 네. 다음 영상에서 만나요.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네. 아 네. 제 동생이 성함을 거어서. 여자분이에요? 지금 의식 같은 거 괜찮아요? 네. 괜찮아요. 주소 말씀해 보세요. 어 도봉구 아 33길. 도봉로 33길에. 몇 층 몇 호예요? 북한산 그랑빌이에요? 거기 혹시? 앞으로 가면 돼요? 네 알겠어요 좀 기다리세요
 네, 감사합니다. 무슨 일이세요? 네, 여기 할머니가 네, 쪽이 안 좋고 아무것도 지금 못 드시고 계셔갖고 병원에 가려고 하거든요. 아 네, 응급실 가시려고요. 선생님. 네. 지금 식사도 못한다는 네, 거동 힘드신가요? 선생님. 네, 네, 네. 위치 좀 알려주세요. 아 구산동 서울시 은평구 구산동. 구산동 잠시만요. 구산동 네. 몇 층으로 가면 될까요? 그 명칭 가치비 맞아요? 네 맞습니다. 어머니 그 할머니 의식은 있으신 거죠? 네. 그 혹시 코로나 관련해서 해당 사항 있으실까요? 학생사에 접촉하거나 그런 열이 나거나 그런 증상 있으실까요? 없어요. 선생님은 관계가 어떻게 되세요? 딸이에요 아 따님이세요? 알겠습니다. 그 부터 출발했고요 선생님 전화 좀 전화주세요 네
 119입니다. 네 안녕하세요. 여기 광화문역인데요. 이번 출고 방향에 있는 교고 문구 쪽 방향인데 데이트 앞에서 어르신께서 계단에서 넘어지셔 가지고요. 남자분이요? 여자분이요? 남자분이시고요. 피를 좀 흘리시고 계세요. 어디서 피가나요? 머리에서요. 머리 부상이에요? 네 의식은 있으시고요. 예 의식 있고 말도 하시고 지나가다 본 거예요? 네 저 영무원이어 가지고요. 예예. 거 2반 출구 그 지하과로 내려가는 그 앞인 거예요? 네네 맞습니다. 거 게이트 앞이요. 게이트 앞이라는 게 거 내려가는 쪽 말하는 거죠? 네네 맞습니다. 네 알겠어요. 네.
 네 읽습니다. 예 어디가 괜찮으신 거죠? 어디가 아프세요? 수시 힘드세요? 아니면 기운이 없으세요? 주소 불러주세요. 주소는요? 청파 청파로 47 낙일 자 조그만 최초 청파로 47 낙일 납이할 때 낙일인가요? 네. 그리고요? 청바파 급 1인가요? 몇 토예요? 몇 토예요? 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 예, 1번입니다. 네, 그 중앙대 병원 응급실 앞인데요. 네, 제가 지금 그 머리가 저리면서. 아, 지금 필요하신 내용은 뭐 다른 병원 안내가 필요하세요? 아니면. 네, 네, 다른 병원으로 좀 빨리 가야 될 것 같아요. 병원 안내 병원 안내 병원 안내 부서로 연결해 드릴까요? 그러면. 네, 네. 병원 안내 부서 전화 연결합니다. 아, 직접 접종은 안 되세요? 병원 병원은 병원 응급실 앞에 계시는 거 아니세요? 네 맞아요. 중앙대 병원은 왜 조치가 안 된대요? 그 환자가 너무 많아가지고. 환자가 많이 기다려서 다른 병원 가시는 거면 거기서도 뭐 더 진료 시간이 단축될 수도 있다 뭐 그런 말씀은 못 드려요. 뭐 어차피 다른 병원 상황이나 마찬가지고 이동 시간까지 다 고려를 하셔야 되기 때문에 119를 이용한다고 해서 뭐 진료 대기 시간이 단축되진 않는다 그 점은 알고 요청을 하셔야 됩니다. 네 지금 머리가 아프시. 머리가 아프시다고요? 네. 뭐 이 지역이 너무 저리고 바쁘거든요. 계속 나가보게 할 건데요. 전화 잘 받고 안녕하세요. 아까 제가 말씀드린 내용은 뭐 인지를 하고 계셔야 됩니다. 뭐 시간 더 걸릴 수도 있다는 건지 알고 계셔야 돼요. 최근에 코로나 관련된 증상 여행령 뭐 특이사항 같은 건 없으셨던 거죠?
 네, 119입니다. 여보세요? 네. 저희 엄마가 너무 아프셔 가지고. 어디 아파하세요? 그 백신을 맞았는데 어지럽고 토할 것 같고 못 걷겠다고 하셔 가지고요. 예, 그 언제 맞았어요? 월요일이요. 월요일 몇 차 맞았어요? 3차요. 예 거기 주소 좀 알려주세요. 어 천호대로 193길 이룸 3차 아파트. 잠시만요. 천호대로 193길. 네. 아 예 길동 3차 이룸 아파트. 네. 예 이거 몇 동. 네 호수 아 동 하나짜리에요? 네 네 어머님 혹시 키친가래 열 증상 있어요? 아니요 없어요 자격정리 중 아니시구요? 네 네 네 이룸 아파트 OO 맞으시죠? 네 네 예 구급차 그쪽으로 가고 있고 구급차 가면서 연락하니까 연락 잘 받으세요 네

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네, 이데부입니다. 아 네, 저기 지금 바닥에 얼굴을 박았는데 얼굴이 찢어져서요. 그래서 넘어지신 거예요? 네, 좀 피가 많이 나요. 아 그래요. 위치 좀 알려주세요. 고기 잡아볼게요. 여기 홍대 싱크홀이라고 치면 바로 앞이. 싱크홀? 싱크홀이라는 눈물이 뭐. 홍대 홍대 싱크홀이요. 싱크홀 잠깐만요. 남자분이 다 치셨어요? 네, 남자분이 다 쳤어요. 알겠어요. 혹시 앞으로 가볼게요. 네. 네 감사합니다.
 119입니다. 아 저 119죠. 지금 119차 좀 빌려주세요. 환자가 뭐 거동이 안 돼서 119 9차 로 응대실 가야 되는 거예요? 네, 네, 네. 그럼. 환자분 계신 곳 주소가 어떻게 되나요? 그러면 일단. 어 기름 뉴타운 성북구 기름 뉴타운 4단지. 뉴타운 4단지. 환자는 본인이 다른 분이세요? 아니요. 엄마예요. 엄마 집에 있는데 엄마가 지금 119 물어달라고 하거든요. 어디가 아프시대요 어머니? 약을 잘못 먹었는데 약 사방 받은 게 거기에 약 부정인 것 같아요. 어 그니까 현재 아픈 곳이 어디래 뭐 어지러운지 뭐. 지금 힘이 아프세요. 힘이 갖고 오바이친하고 지금. 네. 어머니 전화번호 좀 알려주시겠어요? 전화해볼게요. 전화해 보면서 출동해 볼게요. 뭐 비밀번호 못 열어주거나 이런 건 아니죠? 어 그럼 못 열어주면 아니요. 그럴 수도 있을 것 같아요. 현관 비밀번호 알려주세요 그러면은. 네. 제가 그냥. 네 그리고 이제 저희 현관 저희 집 문 앞에 오면. 뭐라고요? 네 네네 제가 확인할게요. 1층 현관이 1층에 가 기본이 네네 네네네네 전화해보고서 출동할게요. 네 빨리요.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 날아일 9입니다. 여보세요. 날아일 9입니다. 아 네 여기 가닥시장 버스정류장 중앙 중앙 거기인데 아저씨 분이 지금 눈 위쪽이 좀 찢어지셔 가지고 취지로 일단 지어를 하고 계시긴 한데 그 넘어지셨어요? 모르겠어요. 저는 바뀌고 나서 를 봐가지고. 아 그 분 혹시 의식은 있으세요? 네 의식은 있고 지금 차 타고 다른 데도 가시려고 하시네. 떠나면 저희가 현장 그 얘기해 주세요. 그 구급차 간다고 가지 마시라고 조금만 기다려 달라고. 아 근데 뭔가 도망가시려고 하는 것 같고 지금 전화 통화를 하고 계시는데. 아 안 해 안 해. 아 예 현장 떠나면 저희가 구급차 가도 어차피 이렇게 처치가 안 돼서요. 지금 확실히 가시는 거예요? 그분? 네 지금 자리에는 안 다 계세요. 근데 제가 통화하는 거 보고 막 고망가지려고 하는 거 같고 제가 보니까. 얘기만 전달해 주시겠어요? 그분이 가시면 뭐 어쩔 수 없는데. 네네네. 여기 그 그쪽 여기 중앙파선에서 그 경기도 쪽으로 나가는 방향이거든요. 방향 아니고 예예. 지하도로 와가지고. 아 예 그 끊지 마시고요. 아저씨한테 얘기해만 해주시겠어요? 네 24010. 아 예 예. 예 그 위치는 찾았고요. 네 선생님 여기 온다니까 잠시 계시겠어요? 괜찮다고 하시는데. 아. 그 현장 첫질만 해드린다고 얘기해 주세요. 그러면. 현장에서 첫질만 해드린다고 하시나요? 아. 아. 아. 아. 아. 네. 여보세요? 예. 여보세요? 네 현장에서 응급처지만 하고 잠깐 계시라고 말을 했어요. 아 예 알겠습니다. 예 곧자 곧주로 갈게요.
 1일입니다. 말씀하세요. 아 여보세요? 네. 서울 의료원인데요. 서울 의료원이요? 네. 고객님 차 좀 보내주세요. 아 네네. 응급실 앞으로 가면 응급실 앞으로 가면 돼요? 아 앞에 앞에 정문 쪽으로 나가 있을게요. 그럼 정문 앞에 계시는 거고 어디가 앞이신 거예요? 저 우측 옆구리 갈리뼈. 갈리뼈 쪽. 예 알겠습니다. 지금 차는 출발시켰고요. 선생님 열이나 기체 인증 있나요? 코로나 관련해서? 좋고요. 예 고 병문 앞에 계세요. 그러면.
 네, 일요구입니다. 어제 어저께 응급실 저기 성신동에 갔다 왔는데요. 네. 또 더 아파가지고. 본인이 아프신 거예요? 예, 예. 본인이. 어디가 아프신 거예요? 지금 막 열나고 머리도 아프고 어저께도 다 다 씻을 것 같고 그랬는데. 네. 코로나 그 주사 맞고요. 15일날 맞았는데 그때도 응급실 갔다 왔는데 그 이후로 5일 전시 아니까. 어제도 머리가 띠를띠 아프고 그래서 갔다 왔는데. 이상이 딱 오는데 자고 나니까. 이쪽 얼굴이 또 이렇게 막 눈이 처음에 코로나 치사 맞고 그런 거 마냥 또 그렇게 하고. 지금 머리가. 지금 머리가 아프고 열 나시는 거예요? 열? 네 열도 나고. 체온 적으셨어요? 혹시? 어 체온기가 없어도. 아 그래요? 주소 좀 알려주세요. 주소. . . . . . . . . . . . . . . .
 안녕히 계십니다. 무슨 일이세요? 아 제가 여기 전개 병원 1 6시가 와 있는데요. 주택이 주택이 많이 틀렸어요. 네. 그래서 그 한양대 병원 1 6시 안내받아서 달력을 했으니 전화를 걸었더니 그냥 제가 반응 안 되니 아마 엠블러스가 신고가 있었나 봐요. 그래서 1 6시 통해서 오라는데요. 어떻게 전화했죠? 어 그 한양대 병원에 전화했더니 1 6을 타고 오라 그랬다고요? 근데 전원을 하려면 뭐 뭐 뭐 이게 일단 연결이 돼 있다고 제가 간 공인대로 간다고 하니까는 손에서 그렇게 오라고 그렇게 많이 하던데요. 지금 일단은 어 일단은 그쪽 병원 응급실 앞으로 구속차가 필요하신 거죠? 선생님 네네네. 동생분 눈 밑에 찢어지셨다고요? 네 넘어져가지고 찢어져가지고 날이 찢어져가지고 손을 해야 될 것 같아요. 아 그 응급실 앞에 계신 거예요? 선생님? 아니요. 저는 여기 건너병원 응급실 앞에 있는데 건너병원 응급실 그 치료가 안된다고 아 아 그니까 선생님 동생분 어디 계세요? 동생분 동생분 지금 건너병원 응급실 앞이요. 아 그럼 응급실 앞으로 차 보낼게요. 선생님 그 혹시 코로나 관련해서 해당 사항 있으실까요? 선생님 아니 없어요. 여기 백신 주사는 안 맞았어요. 휴대폰 번호 하느라고 그래서 휴대폰 번호 했거든요. 일단은 선생님 그 그쪽으로 저희가 구급차 보낼게요. 그 구급자 회원이랑 통화를 해보셔야 될 것 같아요. 그 이제 한양대 병원에서 구급차 타고 오라 그랬죠? 119 타고 오라 그랬다고요? 119 연결이 돼있고 가게도 있습니다. 그래가지고 모르고 어 그렇게 하려고 하여튼 제가 동생을 데리고 가는 게 안 되나 봐요. 그니까 아 선생님은 건대병원에 계신 게 아니라 동생분은 건대병원에 계신 거예요? 선생님은 지금 어디 계세요? 저희가 같이 있어요. 아 같이 있는 거죠? 알겠습니다. 그럼 선생님한테 연락하면 선생님이 전화 받으시는 거죠? 동생분이 같이 있어서요. 예예예 예 그쪽으로 일단 구급차 지금 출발하고 있고요. 선생님 그것 때문에 가면서 전화할 거예요. 전화 좀 잘 받아주세요. 네 네 감사합니다.
 네 수고하십니다. 그리고. 어디 아프세요? 네 저기 제가. 그 생리가 되게 심하거든요. 양이. 그래요? 아프신 거예요? 생리. 아니 아픈 게 문제가 아니 아픈 게 문제가 아니라요. 네네. 생리를 상당히 과자 치료를 해요. 아 그래요? 네 근데 그것 때문에. 병원에서 약을 받아서. 예예. 철근제를 먹고 있는데 근데 이게 철근제라는 게 그냥 조금씩 조금씩 서치해서 보충하는 거잖아요. 근데 제가 지금 생리를 너무 많이 해서 티가 부족해조던지. 병원에 가보셔야겠네요. 머리가 깨질 것 같고 지금 털 것 같고 어디로 쓰러져서 갔거든요. 주소 불러주시면 구급차 보내겠습니다. 저 근데 그 구급차 받아서 병원 가면 수요일 바로 해주실 수 있을까요? 그냥 그 병원에다 말씀하시면은 병원 사정이든지 병원에서 아마 알아서 하실 거예요. 저희가 일단은 응급상에서 제가 해드릴 수 있는 건 응급차 보내는 거거든요. 근데 코로나 검사 때문에 안 받아주지 않을까요? 코로나 검사 뭐 있어요. 혹시 해당 사항 아니 그런 건 없는데. 아니 그런 건 없는데. 아니 그런 건 없는데. 응급실에 바로 못 들어간다고 요즘 제가 들어서요. 일단은 어 구급대 아프면은 병원에 가셔야 되는 게 맞는 거니까. 구급대를 일단 보낼게요. 예 좀 보내주세요. 예 주소 어떻게 돼요? 여기 1원역 있는 가람 아파트고요. 가람 아파트 몇 동 몇 동? 네. 열이나 기침 확진자나 자가격리자 없는 거 맞죠? 네. 어지러워서 지절할 것 같아요. 네. 차 보냈습니다. 네. 고맙습니다.
 여보세요? 네 여기 여기 사무실이고요. 주소가 어떻게 됩니까? 여보세요? 네 잠깐만요. 네 주소는 불러드릴 수 있는데. 네. 기숙에 벌레가 들어가서 너무 아프거든요. 예 병원에 가보셔야 될 것 같은데 주소가 어떻게 되죠? 아 병원에 가봐야 될 거 알긴 아는데. 네. 지금 시간이 새롭기잖아요. 응급실 가보셔야 될 것 같은데요? 아 아침 밟아야 하죠. 네? 아침이 밝아요. 아침까지 기다릴 수 있겠어요? 아니 근데 근데 시간도 그렇고. 예. 그 아침이 아프고 어떡하죠? 일단 제가 구급차 보내드리고 의료 상담을 제가 연결해 드릴게요. 주소가 어떻게 됩니까? 서울시 성구 성동. 예. 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 시간에도 응급실 다 합니다. 네. 아니 아빠도 다 부모님께 다 잡고 있고 그런데. 아이 뭐 그거야 말씀드리고 가면 되죠. 몇 살인데요? 성인이긴 한데 그래도. 성인이에요? 네. 저희 뭐 코로나 관련된 증상이 있어요? 기침 발열 호흡기 질환 같은 거 없으시죠? 네 근데. 예예. 아침 밟고서 가고 싶어요. 그럼 일단 의료 상담원 연결해 드릴게요. 전화 끊지 말고 좀 기다려 주십시오. 감사합니다.
 지금 아빠가 넘어졌어요. 머리에서 피가 나는데 숨은 쉬고 있어요. 지금 막 일어났어요. 근데 조금 어지럽다고 하네요. 네, 네. 계단에서 굴렀어요. 지금은 물 마시고 있는데 이거 응급실로 가봐야 할까요? 피도 지금 멎었어요. 네, 네. 나이는 49살이세요. 어떻게 해야 할지 모르겠어요.
 동생이 콩 가지고 놀다가 코에 들어가서 한쪽 코가 막혔어요. 아무리 빼보려 해도 안 빠져요. 어떻게 해야 할까요? 동생이 너무 힘들어하네요.
 119조 제가 지금 열이 열이 올랐어요. 몇 도냐면은 38도 정도 돼요. 머리가 아프고 좀 띵한 것 같아요. 오하니 좀 들어요. 어떻게 해야 할까요?
 아까 가다가 머리를 박았는데 처음에는 괜찮다가 지금 3시간 정도 지났는데 머리가 어지럽고 속이 메스꺼워요 어떻게 해야 할까요?
 화장실에서 미끄러워서 엉덩방아를 찍었어요. 그러고 꼬리뼈가 계속 아파요. 점점 아픈 것 같은데 응급실을 가야 할까요?

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 열리고입니다. 여보세요? 네. 예 여기 천중로. 네. 예. 제가 좀 호비. 예. 상속도가 너무 떨어져서 이게 호비 좀 힘드셔 갖고. 아 혹시 뭐 확진자는 아니시고요? 예? 확진자 코로나. 아니요. 아니요. 예 아니시고 상속도가 어느 정도 나오세요? 원래는 그 보조장비 하시면 95까지 나왔는데 지금 오늘 거의 아침부터 85일 정도가고요. 네, 네, 선생님 의식은 있으세요? 예, 예, 예, 예, 예, 지금 이제 병원에서 이제 뭐 85 계속 유지되면은. 예, 뭐 열은 없으시고요? 예, 열은 없습니다. 예, 지금 고급자 출발하고요. 고생하셨습니다.
 네 저기 여기 방대로 13길 네네네. 몇 네네. 구급차 좀 보내주세요. 아 잠깐만요. 건물 이름이 있어요? 네 없어요. 건물 이름이 없고 누가 어떻게 아픈 거예요? 아 저희 엄마께서 손이 안 서신다고. 아 의식은 괜찮으신 거예요? 네네네네. 아 코로나 환자는 아니시고요? 예 아니에요. 네. 예 구급차 요청 중이고요. 주소가 방배로 13길. 아 잠깐만. 예 출동하면서 전화 올 겁니다. 잘 받아주세요. 네네.
 예, 일곱입니다. 여보세요? 예, 말씀하세요. 아 애가 지금 일어나지도 못하고 지금 발언도 안 좋아. 자녀분 말씀하세요? 예, 예, 예, 예. 사이는 대충 어떻게 되세요? 그 중학교 1학년인데요. 아 의식은 의식은 어때요? 의식은 있는데 지금. 구급차 필요하시면 주소 먼저 불러주세요. 주소는요? 예, 그 암사동. 예. 예. 라인 아파트. 라인 아파트. 예, 예, 예, 예. 그 앞으로 오시면 되거든요. 예? 몇 초에 계시는 거예요? 불러주세요. 그냥 예. 예. 지금 말하고 하면 대답은 의식은 대답은 해요? 뭐 돼요? 대답하는데 지금 계속 그 효과 더 굳어간다고. 굳어가는 거 같아요. 알겠어요. 차는 출동을 시켰고 저희도 도착할 때까지 응급 조치를 안내할 거예요. 전화 끊지 마세요.
 네, 읽습니다. 네, 여기 저기 뭐지? 저희 아버지가 지금 의식이 없으시거든요? 아, 숨을 쉬고 있는지 확인해 보시겠어요? 숨은 쉬세요. 숨은 쉬시고. 숨은 쉬신데 아무리 깨워도 못 일어나시거든요? 아, 뭐 눈 눈을 안 뜨세요? 눈을 예, 눈을 안 뜨시고 자꾸 눈이 뭐지? 저절로 이렇게 자꾸 여기거든요? 주소 좀 알려주세요. 예. 마치 1도? 네. 도예요? 네. 혹시 코로나 관련해서 열이나 기침 호흡 곤란 같은 건 없어요? 아 예. 그건 없으시 기침 그런 건 없으세요. 자학행위증 아니시고 확인증 아니시죠? 네네 네 선생님 그거 고객센터 보내드렸고요 네 저희가 의료진 연결해서 응급처치 안내할 거예요 전화 끊지 마세요 네네 알겠습니다

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네. 여보세요? 잠시만요. 9일로예요? 9일로예요? 9일로요. 9일로 11길. 9요. 9일로 11길. 네. 가족분들 중에 코로나 확진자 지역 다녀오거나 기침 발열 이런 거 있나요? 아니요. 없습니다. 네. 가볼게요. 네.
 네, 수고하십니다. 여보세요? 아 여기 공룡로 두산이 비콘 아파트 앞에 창거린데요. 네. 여기 교통사고가 나가지고 지금 차량 RV 차량이랑 오토바이랑 사고가 났거든요. 다치신 분 1분이세요? 네. 아 혹시 의식은 있어요? 아 예, 있는데 지금 다리 쪽을 다치신 것 같아요. 아 차 밑에 깔려 있거나 그렇지 않죠? 그렇지는 않아요. 지금 창거리 쪽이라서 많이 교통이 혼자 갈 것 같아 빨리 오셔야 될 것 같아요. 비콘아파트 앞이요? 비콘아파트 앞에 준호야구 네 네
 네, 네, 네. 말씀하세요. 아 네, 그 주무시다가 술 좀 드시긴 했는데 갑자기 배 복통을 좀 심하게 요구하셨 그 그 말씀하셔가지고 견디지 못하고 계시는데 혹시 오실 수 있을까요? 누가 그러신 거예요? 아버지가? 저희 아버지께서. 네, 주소가 어떻게 돼요? 네? 주소가 어떻게 돼요? 여기 구로동로 15길 구로동로 15길 몇 층 몇 호에 창원 아트빌라예요? 예 맞아요. 예 차량 보냈고요. 병원팀에 하고 계세요. 네 감사합니다.
 아 네 여기 지금 방에도 예 이게 요런 결정이 원래 있었던 사람인데 그건 지금 뭔지 지금 막 이게 불러가지고 어떻게 할 수가 없어요. 아 남편이 그러신 거예요? 네네. 네, 네. 알겠어요. 아버님. 아버님 열은 어때요? 열 같은 거는? 열은 없어요. 열은 없고? 예, 코로나 센터도 맞았어요. 그러면 밑으로 내려가면 어떡해요? 내려오실 순 있겠어요? 아우, 뭐 어떻게 빨리 털고리도 내려가야지. 알겠어요. 지금 잠실에서 고착하니까요. 천천히 내려가 계세요, 그러면. 얼마나 걸려요? 잠시로 안전해서 한 5분 정도 걸릴 것 같아요. 그런데 진통제 좀 놔둘 수 있어요? 차에서? 아 그건 진통제는 저희가 따로 못 놔드리고 병원을 가셔야 돼요. 그럼 바로. 어디로 가야 되나 진통제 놔두면 병원이? 그 그때가 가면은 그 때랑 한번 상의를 한번 해주세요. 예예. 예.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네, 갑니다. 아 예, 여기 위치가요. 네, 네. 예, 예, 저희 어머님이 갑자기 오른쪽하고 왼쪽 오른쪽 한쪽이 지금 힘을 못 쓰셔가지고 병원을 못해 가야 될 것 같은데. 우측으로 팔다리가 마비가 왔어요? 예예. 예예. 의식은 있나요? 예예. 주소 어떻게 돼요? 아 몇 층 몇 층 몇 층. 집어 번지 집 하나예요? 예예. 아 차는 지금 보냈고요. 몸에 열 있거나 짐 콧물 있으세요? 어머니? 그런 건 없어요. 집에 격리하시는 분이나 확진자 있거나. 그런 거 없어요. 네. 구호차 보냈으니까 좀 기다리고 계세요. 네.
 네. 16입니다. 말씀하세요. 청량리 신현대 아파트 맞아요? 몇 동 몇 호요? 무슨 일이세요? 지금 저희 어머니가 일어났는데 움직이시는 못하고 말을 못하시고 의식은 있어요? 의식은 있으세요. 의식은 있는데 말씀을 잘 못하시고 말씀을 아예 못하시고 움직이질 못하세요. 잠시만요. 그런데 보니까 옷을 쌌는데 이거 어떻게 옷을 갈아입혀가지고 가야 돼요? 어떻게 해야 돼요? 일단 구급차 나갈 거고요. 어머니 뭐 옷을 챙겨가시던가 그러시면 될 것 같고요. 어머니 의식이랑 호흡은 있다는 거죠? 네 그렇죠. 호흡은 괜찮아요. 하품도 하고 뭐 이런 데 말을 못 하시고요. 최근에 코로나 관련해서 코로나 관련해서 뭐 접촉했다고 문자 받으시거나 의심 증상 같은 거 있으셨어요? 아니 아니 그런 거 없어요. 집에만 계시는 거니까는. 네 네 대원들 나가면서 전화드릴 수 있으니까 전화받으면 안내 좀 부탁드릴게요. 네. 네.
 어, 네, 제가 본인인데 지금 조건이. 어, 몇 층 몇 호예요? 지금 열 증상 같은 거 있어요? 아니 지금 살짝까지 있는 것 같아요 열은 없고? 열은 없어요 지금 알겠어요
 네. 권학 권학 권학 드림타운 아파트 네 예예예 네 알겠습니다. 코로나 관련된 거 없으시죠? 그런 거 아무것도 없어요 지금 현재 예 알겠습니다 예
 네 죄송합니다. 네 천호지구대 경찰관입니다. 네 저희 천중로 네네. 아 지금 신고 요청하는 거예요? 예예예. 네 앞에 민원인 한 분 계신데 얼굴이 청백하고 숨이 가쁘고 몸이 너무 안 좋다고 지금 119 불러달라고 하시거든요. 남자분이에요? 남자분입니다. 예 지금 차 나가고 있고요. 예예. 예 천호지구대죠? 예 천호지구센터입니다. 예 알겠습니다. 지금 나와 볼게요. 네.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네 경비할 수 있거든요. 경비할 수 있던데. 네 여보세요? 여기 만복국수집이거든요. 아 그 경부선 터미널인데요. 아 고속 터미널? 네네네. 경비 경비 네. 어떤 일 때문에 오세요? 어떤 분이 숨을 못 쉬시고 지금 지금 아예 쓰러지셨거든요. 남성분에 옆에서 홀딱이는 남성분인데 좀 체구가 있으세요. 그 만복국수라고요? 네 경부선 터미널에 1층에 만복 주출집이라고 있거든요. 잠시만요. 검색했고요. 네 조금만 빨리 와주세요. 지금 숨 넘어가신 것 같아 보이거든요. 빨리 찾아봐요. 이 뭐 경로를. 가는 가고 있고요. 경부선 쪽? 네네네. 1층 쪽에 있나요? 네. 1층에. 지금 전화 끊고 숨을 아예 못 쉬어요? 제 눈에는 홀딱이 주는 걸로 보이셔서 먼저 쓰러져서 그러는지 모르겠는데.
 예, 연락입니다. 어, 여기 위치가 어떻게 돼요? 여기 선희 유치원 앞이거든요. 쌍문도. 선희 유치원이요? 선희 유치원이요. 선희. 선희 유치원? 네, 네. 아, 무슨 일이에요? 아, 여기 교통사고 나셔서 오토바이 운전자가. 오토바이랑 차랑 그럼 부딪친 거. 네, 네, 네, 네, 네. 오토바이랑 차랑 오토바이 운전자 차 밑에 깔려있는 건 아니고요? 아 오토바이에 잠깐 눌렀었는데 지금 덥기는 하시거든요. 아 그래요? 차 밑에 깔려있는 건 아니죠? 우리가 차를 클레이크로 그려진 건 아니에요. 그건 아니에요. 예 천이 유천 앞으로 가면 돼요? 네, 네, 네. 알겠습니다. 20만원 빨리 다 할게요. 네.
 아 네 여기 도림사거리 미니스톱인데요. 도림사거리 미니스톱. 네 그 할머니 쓰러지셔 가지고. 할머니 어디 아프시면 물어봐 주실 수 있나요? 어디 아프세요? 아. 할머니. 어디 말 못해요? 네. 네. 빨리 와주세요. 전혀 없으신 거예요? 그러면? 네네네. 아 숨 쉬나 봐주세요. 차 가고 있으니까요. 숨 쉬나 봐주세요. 숨 숨 쉬나 봐 봐. 네 숨만 쉬는데요. 좀 앞에 있고. 끊지 마시고요. 할머니 의식 없고 호흡만 있고 끊지 마시고 차 출동했고요. 차 가는 동안에 의료진 연결할 거예요. 상태 말씀해 주세요. 네. 끊지 마세요. 연결합니다. 네.
 119입니다. 말씀하세요. 아 예 수고하십니다. 다름이 아니고 우리 저기 할머니가 예 혼자 계신 분인데 지금 넘어져가지고 다리가 막 움직이지를 못하거든요. 아 거기 주소가 어떻게 되세요? 여보세요? 예 주소 좀 알려주세요. 3 6 7 북과자동이요. 서대문구 북과자동. 예예. 잠깐만요. 예. 여보세요. 네네. 앞으로 가면 되는 거예요? 연합 빌라. 아니 할머니로 이동으로 해줘야 돼. 들것이 와야 될 것 같던데. 네, 네, 네, 네. 네, 알겠습니다. 할머니 지금 코로나 관련해서 열이 다 차신 이런 생각인가요? 아니, 코로나는 아니에요. 혼자까지 다 백신 했어요. 아, 예. 알겠습니다. 조금만 기다려주세요. 네.
 119입니다. 아 여보세요? 네 여보세요? 네 저 저 어머니가 돌아가셔가지고. 아 선생님 제 주소 좀 불러주실래요? 예 구로동 한심 휴플러스 아파트고요. 한심 휴플러스 아파트. 네. 네 선생님 저희가 지금 고급차는 보냈고요. 네. 네 저희 의료진 연결해주시니까 끝이 가고 기다리세요. 네. 감사합니다.
 예예. 예 선생님 119인데요. 예예. 119 가고 있는데 누가 누가 널 떨어지신 거예요? 저기 딸이요. 딸이? 아 지금 의식이랑 호보기 다 괜찮아요? 예예 얘는 괜찮아요. 머리가 어디가 아프냐? 어디가. 어디가 아프냐? 다리 팔. 어떻게 어떻게 다쳤어? 어? 어? 어떻게 어디? 어떻게 다쳤어? 어디 다리는 괜찮아? 다리? 다리 괜찮냐? 어떻게 어디서? 어? 어? 어? 예. 딸 좀 봐주세요. 어? 하고 있어요. 어머니. 지금 어디 계세요? 지금 어디? 여기요. 저기요. 저 6일날. 계단. 예. 예. 이래요 2 아 아 아 아

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네. 이별구입니다. 여보세요? 네. 네. 네. 수고하십니다. 여기 그 중랑도 용마산로 백길에 예. 무슨 일이세요? 예. 아버님이 지금 배가 막 아프시다고 그러는데. 예. 어 그 응급실 좀 가봐야 될 것 같은데. 아 예. 구급차 보내드릴게요. 용마산로 백길 그다음에 네 부모님 나이대가 어떻게 되세요? 일은 일곱 올해로 저기 올해 2월 1일이니까 일은 몇월 예 삼경마트 예예예 맞습니다 예 지번은 맞으시고요 열기증 코로나 같은 증상은 있으세요 없으세요? 아니 그런거 없어요 아 예 알겠습니다. 그쪽으로 보내드리겠습니다 네네 예예 감사합니다.
 네. 여기 한남동 한남동 네. 현대빌라 네. 아 제가 저번 주 목요일에 백신을 맞았는데 구급차 필요하세요? 의료 상담이 필요하세요? 아 모르겠어요. 잘. 구급차 보내주실 수 있을까요? 네. 어디가 아파요? 어 갑자기 가슴이 너무 답답하고 심지리가 좀 힘들어서요. 지난주 목요일 날 맞았다고요? 네. 예 지금 차 출발했고요. 저희 나가면서 의사 선생님 연결 드릴게요. 전화 끊지 마세요. 네.
 네 안녕하세요. 저 그 저희 할아버지께서 낙상하셔서 머리에 출혈이 있고 어 약간 어지러움증 호소하는데 어떻게 해야 될지 어 고급차가 출동해야 될 것 같은데요. 머리를 낳으셨으니까 주소 좀 알려주세요. 여기는 서울시 강남구 남부 순항로 363길 몇 층 몇 몇 층 몇 초예요? 네 맞습니다. 그냥 빌라입니다. 출동하고요. 할아버지가 혹시 열이 있거나 기침 코로나 관련 증상이 있나요? 없습니다. 출동하겠습니다. 네 감사합니다.
 아, 여보세요? 네, 말씀하세요. 아, 네, 여기 사당자의. 어. 네. 네, 무슨 일인가요? 아, 네. 저희 엄마가 지금 또 못 일을 마시게 돼가지고. 어, 네, 뭐 의식이 없는 거예요? 어디로 오신 거예요? 아 의식이 없는 게 아니고요. 그 허리를 다치셨는데. 허리 기증 때문에? 네네네. 허리 부상으로 뭐 의식 괜찮고요. 네. 뭐 코로나 관련한 열 기증 당기증이나 이런 거 없으신 거죠? 네네. 그래서 가고 있으니까 같이 계시죠? 네. 여러분들 가고 있으니까 문 열어주세요. 허리 때문에만 아파서 거동이 안 되시고 119로 응급식 가야 되는 거죠? 네네. 가고 있어요. 네.
 네 연류부입니다. 여보세요? 예 말씀하십시오 연류부입니다. 예 시흥동 지금 갑자기 와이프가 어지럽게 하면서 손이 고가지고 아 저 열은 안 나세요? 열 나거나 코로나는 없어요? 예방접종 2차까지 다 맞았는데. 네 열은 없어요? 예 지금 열은 없어요. 지금 딱 나고. 네 알겠습니다. 손이 좀 곱아지고. 예 우리 수방관들 나가고 있으니까 조금만 기다리세요. 다 출발했어요. 말미사관이 앞에서 출발했습니다. 예.
 119입니다. 말씀하세요. 예, 힘드세요? 예예. 여기가 좀 많이 아픈데요. 아 일단 주소가 어떻게 되세요? 광복고 오현노 9길. 오현노 9길. 월드비를 났어요? 예예. 누구 어떻게 아프신 거예요? 제가 백신 맞고 저희도 2번 처음에 하고 2번 짠도 고생을 많이 했거든요. 예예. 그런데 지금 3번째 맞은데 일주일 됐거든요. 이제 많이 부어갖고 약도 받아 먹고 했는데 지금 저거 하고 제가 헬스증이 있어요. 예 그래갖고 가슴과 등이 너무 많이 아파서 아프게 바로 출발할 거고요. 선생님 열이나 기침 같은 증상 있나요? 혹시? 기침을 안고 열이 좀 있는 것 같긴 한가 모르겠어요. 현관문 좀 열어주세요. 그러면. 예예. 저기 나갈게요.
 여보세요? 네 안녕하세요. 119 상황실인데요. 신당 누리센터가 신당동 주민센터 여기 있는 거 맞죠? 네 그런 거 그 신 저희 어디 잘 모르겠는데 신당 누리센터 있는데 이거 아 네 신당동 주민센터 맞는데 맞아요. 아 혹시 그 남자분 혹시 의식이랑 호흡 있는지 확인. 아셨는데 피해가 조금 흘리지는 것 같고 어떤 남성분이 편의점에서 뭘 사라지신 것 같거든요. 아 네 알겠습니다. 저희 대원들 나가서 한번 확인해 볼게요. 위치 확인이랑 위치 확인 때문에 전화드렸어요. 아 네 감사합니다.
 예 여기 지금 애가 갑자기 경기에서 기절했거든요. 몇 층이에요? 지금 빨리 좀 와주세요 빨리요 네 출동하고요 혹시 지금 숨은 쉬고 있어요? 지금 막 눈이 막 뒤로 가고 막 있어요 지금 애 아빠가 지금 가슴 누르고 있거든요 출동하고요 저희 의료진 연결할게요 전화 끊지 말아주세요 전화 끊지 마세요
 네 여보세요? 네, 네, 네. 네 차량이 독립이 돼 있어서 차량이 독립이 돼 있어 갖고 차가 차가 차차가 이제 차량이 깔려 있진 않죠? 네 깔려지진 않았어요. 지금 지금 뚫어진 건 뚫어지진 않는데 지금 좀 완전 심하게 바왔거든요. 차 가니까 전화를 잘 받으세요. 네 알겠습니다.
 네, 여보세요? 네, 말씀하세요. 네, 저 지금 길 지나가다가 어떤 1분이 그냥 넘어지셨는데 화분의 머리를 좀 지셔 가지고. 지금 뭐 어떻게 그 구급대원 와야 될 것 같아서 전화할까요? 아 예, 저 어디 앞이에요? 주소 확인되나요? 저기 여기 잠시만요. 예. 여기가 신흥로 7길 남자분이요? 여자분이에요? 남자분이요. 네 지금 의식은 있고요? 네 알겠습니다. 수고할게요. 네.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 여보세요. 네, 여보세요. 아 친구가 지금 공황장애가 심하게 와서 숨이 안 쉬신다고 지금 약 먹었는데. 예, 주소 알려주세요. 의료 상담이 필요하세요? 구급차 필요하세요? 뭐야, 야, 주소 주소. 여기 그 목동사 그 목동사 거리 옛날에 동방주유소 있어가지고. 아 어 건물 건물 밖으로 나가면요. 건물에. 잠시만요. 네네네. 건물 밖으로 나가면 건물 벽에 붙어있어요. 도로명수수. 잠시만요. 아니 아니 대박 대박. 잠시만요. 건물 밖으로 나가시면 건물 벽에 도로면으로서 붙어있어요. 네네. 여기 곰달래로 59길. 곰달래로 59길. 몇 층 몇 호예요? 아 여기 그 길 났데 바로 내가 올게요. 네 그 아니 그게 아니고 그 돌개당 바로 위에 집 하나 있는데 거기예요. 네 알겠습니다. 코로나 걸린 사람 없고요?
 여보세요. 여보세요. 119예요. 여보세요. 예 119예요. 예 119라고요. 119. 예 아. 어디 아프세요? 아 다 아파요. 예? 다 아파요. 주소가 어떻게 돼요? 모르겠어요. 예? 모르겠다. 주소를 알아야 가죠? 아 저도 잘 모르겠어요. 지금 여기가 어디가. 집 아니에요? 네. 밖에에요? 안에. 그러니깐요. 지금 집 어디 뭐 나와서 뭐 혹시 말 못해요? 네. 위치를 알아야 어디라도 가죠? 아 모르겠어요. 주소 좀 생각해보세요. 주소 찾아서 빨리 가게 안 그러면 빨리 못 간다니깐요. 아 모르겠어요. 주소를 알려주셔야 빨리 가죠. 주소 어떻게 돼요? 잘 모르겠어요. 주소를 모른다고 하면 안 된다니깐요.
 네 열령입니다. 여보세요. 예 말씀하세요. 여기 시내가 있는 분인데요. 아니 참 뇌경색 있는 분인데요. 네. 갑자기 정진출을 놓으면서 주소 알려주세요. 구부차 보내드릴게요. 양산길 관악구 양산길. 관악구 양산길. 양산길. 몇 층 몇 층예요? 저기 창동 이발관 앞으로 오시면 돼요. 단독집이에요? 아니요. 창동 이발관 앞으로 오시면 돼요. 이발관 이 앞 앞집에 네. 이발관 아 이발관이라는 거예요? 네. 2달간 앞으로 차 오시면. 네. 글리 갈게요. 예. 남 할아버지가 지금 갑자기 쓰러졌어요? 네. 정신이 왔다 갔다 하시고. 예. 원래 뇌정대기 있는 분인데요. 지금 숨 쉬어요? 네. 근데 좀 위험할 위험할 거 같아가지고요. 예. 코로나 하시는 적 있어요? 네. 없어요. 그 아내분이세요? 지금 전화하시는 분? 아니요. 아들예요. 아들? 네. 예 지금 차 나가고 있어요. 네. 그 양산길 앞으로 갈게요. 네.
 네. 일요국입니다. 말씀하세요. 예. 저는 그 음식 배달하는 사람인데요. 지금 여기 구로에 버거킹 그 배달하는 요 저기 구로 구로 버거킹점 앞에 어떤 여성구에 울고 계신데 좀 구조를 해줘야 되지 않을까 싶어서 걱정이 좀 돼서 전화드렸습니다. 버거킹 앞에 여자가 울고 있는 거고요? 예예. 뭐 어떤 일 때문에요? 모르겠습니다. 저는 지금 배달하고 지나가는 일인데. 예 버거킹이요? 잠시만요. 예 예. 예 알겠습니다. 나와볼게요. 거 버거킹 2개 있거든요? 부산은행 앞에 있는 거예요? 여기가 어 저 예. 사이드 앞에 있는 거예요. 케이 그 하나은행 맞은편에 있어요. 아 예 알겠습니다. 어딘지 알아요. 나와볼게요. 예 예. 예 감사합니다. 감사합니다.
 입니다. 여보세요. 네 말씀하세요. 예 여기는 시비아 요양원입니다. 네. 근데 우리 어르신이 지금 저녁 식사 하시다가 약간 경련처럼 있으셔가지고. 남성이에요? 남성이에요? 네? 남자분이세요? 경련하고 있다고요 지금? 약간 몸을 떠시는데. 네. 의식 반응이 지금 없으셔요. 입을 안 여시고 눈도 안 뜨시고. 몸에 약이. 숨을 쉬고 있어요? 숨 쉬고 계셔요. 주소 좀 알려주세요. 여기 은평구 증산로. 은평구 증산로. 15길. 예. 예예예. 몇 층에 몇 층으로 가면 돼요? 저희. 정문으로 들어오셔서 아 실비아 요양원 정문으로 들어오셔서 몇 층으로 보내세요? 정문으로 와서 주차함 끝까지 들어오셔요 몇 층이냐고요? 여기 어르신 계신데는 올라가면 되는 거 아니에요? 네네 맞습니다 일단 들어오셔야 되거든요 얼마나 걸리실까요 선생님? 바로 출동할게요 준비해드릴게요 감사합니다
 네, 감사합니다. 말씀하세요. 아 예, 저 어머니가 안 좋으셔서 지금 병원 가려고 그러는데요. 네, 선생님 그 위치가요. 한나라에 8차 맞으세요? 예, 예, 맞습니다. 어머니 지금 상태가 어떠신데요? 아 지금 말도 못하고 좀 좀 그래요. 그 호흡은 있으세요? 예, 호흡은 있고 뭐 저기 여름 괜찮아요. 그니까 지금 의식은 있으신다는 기력 저하신 건가요? 선생님? 아니 저기 눈은 뜨고 계시는데요. 네, 네, 네. 전에도 한번 이래갖고 폐렴 증세 같은 증세가 이렇게 말을 안 하고 이렇게 됐었거든요. 네, 선생님 그쪽으로 구급차 보내드릴게요. 혹시. 얼마나 걸립니까? 잠깐만요. 선생님 코로나 관련해서 해당 사항 있으실까요? 네, 코로나 검사해야 돼요. 그 확진자세요? 아니요. 확진자가 아니고. 네, 알겠습니다. 엄마가 암 환자예요. 암 환자. 아 암 환자세요? 예, 예. 지금 위주로 있다는 얘기신 거죠? 예, 예. 지금 구급차 출발했고요. 선생님. 제가 주변에 구급차가 없어서 봉천동에서 차가 가고 있어요. 한 2km 정도 떨어진 데서 가고 있어서요. 선생님. 한 적어도 10분은 좀 넘게 걸릴 수 있어요. 그 교통 사항에 따라 달라지기 때문에요. 예, 예 알았습니다. 저희 선생님 한나에 8차 맞으시죠? 예, 예, 예 동 잡고 성자로 37 김에. 네, 그쪽으로 구급차 출발했고요. 신고자분 전화 좀 잘 받아주세요. 부급 회원이 가면서 전화할 건데요. 혹시 모르니까 핸드폰 번호 하나만 알려주시겠어요? 알겠습니다. 선생님. 감사합니다.
 네 119입니다. 네 말씀 좀 부탁드리는데요. 네. 네 안정제 좀 맞으려고 하는데 제가 혼착을 못하겠어요. 구급차가 필요하신 상황이세요? 네. 응급실로 이송 응급실로만 이송 가능한데. 네. 불러드릴까요? 네. 주소 어떻게 되세요? 와우산로. 와우산로. 30일에 칭 홍대 스토리 원룸텔 잠시만요. 홍대 스토리 원룸텔 네. 지금 어디가 뭐 어떤 게 제일 힘드세요? 진상제를 원래 먹고 사는 사람인데요. 네. 뭔가 먹었는데 숨을 못 쉬겠고 안정이 안 되고 불안해. 아 네 알겠습니다. 대원들 나가면서 전화드릴 수 있으니까 전화 좀 안내 좀 부탁드릴게요.
 어제는 어차피. 어제는 여기. 네 여보세요. 네. 예 여기 은평의 마을인데요. 은평의 마을이요? 네 네. 네 무슨 일이세요? 아 여기 지금 환자가 지금 삼성토화도가 안 잡히고 의식을 계속 좀 잃어가는 것 같아서 전화드렸어요. 사람 또 지금 85 60이 정도밖에 안 나와서요. 어 남자의 여자요? 남자분이요. 그 선생님 은평의 마을이라는 거죠? 네네. 구산동에 있는 거요. 은평구 구산동에 있는 거요. 은평의 마을 남자 여자예요? 남자분이고요. 네. 남자 남자 분이고 몇 층으로 가야 돼요? 예? 네네. 예. 라는 거죠? 산소 포화도 났고 의식 떨어졌어요? 의식이 있어요 원래? 아직은 아직은 있으신데 네 지금 막 없어지시는데 반응이 잘 안 보이시려고 그래요 네 차 먼저 차별하고요 네네 인급처치도 연결할게요 끊지 마세요 네
 네, 여보세요. 입니다. 아 네, 여기 저기 오키인데요. 어디요? 선생님? 강남에 강남에 옥티요. 옥티요? 옥티? 네네네, 강남 옥티요. 옥티가 뭔데요? 아 술집인데. 주소 불러드릴까요? 아 옥티 강남점이요? 네네, 나오네 하시니까 무슨 일인데요? 아 지금 한 명이 제가 술을 술을 갑자기 못 쉬겠다고 얘기를 해가지고 사실 너무 답답하다고 해서 그래서 이제 좀 병원을 바로 가고 싶다고 얘기하는데 좀 안 좋은 거 같아서 말을 했을 텐데 잠시만요 선생님 선생님 그 술 마시다가 기절하신 분이에요 혹시? 네? 술 마시다가 기절하신 분? 아니야 술 안 아니야 그런 거 아니에요 그런 거 아니에요 아 그 근처에 보급차 7종이 있어가지고 같은 거인가 해가지고요 남자분이세요? 남자분인데 그런 건 아니에요 네 숨 호흡이 곤란하대요? 네네네네 남자친구분이? 네네 지금 의식이랑 이런 건 다 있는 거예요? 네네네네 아 지금 그 뭐 거기 뭐 주점 몇 층에 있는 거예요? 네 네 네 내려갈 수 있어요 내려갈 수 있어요 아 일단은 차는 글로 보냈고요 네 따로 뭐 코로나 관련된 뭐 그런 건 없죠? 그런 건 아니에요 차 보냈어요 선생님 조금 기다리세요 고급차에서 전화 올 거예요 네 네

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네 수고하세요. 여보세요? 네 저 119 성함입니다. 무슨 일이세요? 저기 여기 요구리스타워에요. 네. 저기 그 오줌이 안 나와서 응급비를 좀 가야 하겠는데. 선생님 본인이 소변이 안 나온다고요? 예 소변이 잘 나와서 며칠 전에도 1번 갔었는데. 어떻게? 노블레스 타워 1차 네 맞아요 일단 그쪽으로 구급자 전 보냈고요 예예 환자분 감기 증상이 있거나 코로나 확진자는 아니에요? 감기 증상이 있거나 코로나 확진자는 아니에요? 그건 아니에요 일단 구급자 전 보냈습니다 만나보세요 전입변 2대를 수술했는데 그 후유증이에요 전차 보내는 사람이고요 출동한 구급자한테 환자분 과거력이 돼서 말씀해 주세요 저는 출동한 구급배원이 아니라 차를 보내낸 사람이니까 출동한 구급배원이랑 병원 선정이랑 환자분 상태에 대해서 말씀 나누세요.
 아 여보세요? 저기 지금 역전을 해내거든요. 여기 술을 마신 애가 토를 했는데 정신을 못 차려요. 지금 그분이 응급실로 가셔야 되는 거예요? 기가 도움이 필요하신 거예요? 지금 그냥 정신이 없어요. 정신이 없이 쓰러져 있어요? 네 그냥 진짜 아예 정신이 없어요. 네 그냥 토를 하고 아무것도 못 해요. 신고자분 거기 위치 좀 알려줘요. 무슨 어디라고 어디 앞이라고 하셨죠? 신림 사거리 역전 할메요. 역전 할메요? 네 지금 빨리 오셔야 될 것 같아요. 신림 할메 차 가고 있으니까 잠시만 볼게요. 역전 할메. 지금 눈에 초점이 없거든요. 예 알겠습니다. 신림 할메 술 너무 많이 먹으면 그럴 수 있으니까 너무. 그렇습니다. 네 지금 근데 누워있거든요. 요. 편하게 누워 편하게 누워있게 해주세요. 손나 잘 쉬게 누워있게 해주시고. 컷 때문에 입이 막혔어요. 이 이 숨 쉬게 입 벌려주세요. 숨 잘 쉬게 남자분이 여자분이에요. 남자분요. 남자분 숨 잘 못 쉬는 거 같아요? 끊지 마시고 차 출동했고요. 의료진 연결할 거니까 신고자분 신착하시고 신고자분 네. 신고자분 숨 잘 쉬게 의료진 연결할 거예요. 끊지 마세요.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 1 9입니다. 말씀하세요. 네 저기 엄마가 많이 아프신데 그 혹시 코로나를 접종을 안 했었거든요. 그런데 이동은 가능한가요? 어 뭐 지금 병원 응급실 지금 혹시 뭐 열 같은 건 알아요? 어머니가 열이나 기침 이런 증상. 그런 건 아닌데. 없고 그냥 일단 복지도 안 맞았는데 어디가 아프신 거예요? 지금? 지금 몸살 비슷한 거 같은데. 네, 네. 저희 뭐 물도 잘 못 마시고. 예. 그러고 계시거든요. 누워만. 아 주소 알 수 있을까요? 음 잠시만요. 예, 예. 어 노원구. 예. 월계로 40차 가길. 잠시만요. 월계로 44 각일 네. 청구빌라 왔어요? 예. 청구빌라 맞습니다. 지금 같이 계신 거 아니에요? 선생님 그러면? 저는 저는 답심리에 있는데. 아 예예. 그러면 어머니 전화번호? 네. 네. 전화번호 알려주세요. 전화번호가 네. 네네. 아 네 알겠습니다. 제가 나가면서 전화 한번 해볼게요 그러면 어머니한테. 그러면은 제가요. 예예. 하나 오빠가 갈 수 있거든요. 예예. 그러면은 좀 알려드려도 될까요? 오빠 번호. 아 그럼 그냥 오빠 번호를 알려주세요. 그게 나을 것 같은데. 예. 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네
 네. 여기가 저 부가연로 4가지 부가연로 4가지에 잠시만요. 몇 초에 계세요? 예 큰일이 되세요. 조금 들어와야 돼요 한 5m 5m 10m 정도 들어와야 되는데 제가 지금 걷지도 못해요. 어떻게 안쪽으로 오신거에요? 병원에 있다가 24일날 세원도 했었거든요. 어떻게 안쪽으로 오신거에요? 복수가 지금 많이 차가지고 네. 숨이 차고. 숨쉬기가 곤란하고 다리도 많이 아프고. 그리고 엉덩이에 또 욕탕이 나가지고. 여러 가지 여러 군데가 좀 안 좋은데. 문 열려 있어요? 예? 문 열어놓을게요. 문 열어놓을게요. 차 가니까 전화 잘 받으시고 기침 열 목구멍 통증 같은 코로나 증상 없으신 거죠? 코로나 증상이요. 코로나 증상 없으시죠? 예 없어요. 네 알겠습니다. 예.
 네 이럽니다. 예 다름이 아니고요. 집사람이 중앙동 14길인가? 몇 장 몇 합니까? 아까 1 불러갖고 집사는 술을 너무 취하고 저도 취하고 옥탑까지 올려야 하는데 옥탑방 4층이에요 1층에 집을 집사랑이 있는데 제가 올리기가 힘들어갖고 저도 먹고 하다 보니까 그리고 지금 일찍에 부터 다 하고 이제 청소 다 했는데. 예. 올리시다가 올리기가 뭐였는데 같이 올릴 수 있는 도움을 받고자 하고 싶어서 전화드렸습니다. 아 아내분이 주치상태가 있는데 올라가지 못 가는 상태예요? 예. 아 목놀 못 가는 상태예요? 병원에 갈 상황일 수도 있겠네요? 아 그런 건 아니고요. 아 일단은 주소가 중인 건 원평 원평구 응암로 14일이. 맞습니다. 아 혹시 코로나 관련 증상 뭐 15개 층 오는 거 없으세요? 그런 건 상관없어요. 부스 타고 2 다 다 맞았어요. 아 그래요? 1 1 1 2가 왔었는데 여기 옆에서 그 저 저 공원에서 여까지 제가 업고 왔어요. 네 그리고 그 그 앞전에 그 택탁을 공원까지 제가 업어서 왔고 또 여기서 여기 예. 도저히 도움받았다면 없어서 전화드렸습니다. 아 알겠습니다. 일단 나가볼게요. 심장분. 예. 예. 예. 예.
 119입니다. 119입니다. 말씀하세요. 예 다름이 아니고 저희 어르신이 지금 고열 나면서 갑자기 쓰러지셔가지고. 예 의식이 있어요? 없어요? 아 있으신데 거의 눈을 못 뜨세요. 지금. 저 의식이 혼미예요? 예예. 갑자기 쓰러진 거예요? 아버지예요? 아니 아니 저는 저기 사위입니다. 사위. 아 사위고요? 예예. 네 장현아 어른이요? 아니 장모님이요. 장모님. 장모님이요? 지금 뭐 지금 어디 뭐 다쳤어요? 지금 화장실 앞에 그냥 눕혀 놨어요. 아 선생님 뭐 숨은 괜찮아요? 호흡은? 예 호흡은 괜찮으실 것 같아요. 주소가 어떻게 돼요? 막감이나 여기 900 어 아파트예요? 중관 3로 진관 3로 예 예 예 300 몇 년 예 정모님 열이나 주시면 코로나 관련 사항 있어요? 아니 없습니다. 저희가 다. 근데 열은 나세요. 지금 열은 몇 도예요? 지금? 지금 재봐야 될 것 같은데? 아 다시 심해요? 막 땀 흘리시고 그러시면 되세요. 아 예 알겠습니다. 여기. 네 알겠습니다. 전화 잘 받으세요. 네. 예.
 무슨 일이세요? 여보세요? 119예요. 예 선생님 안녕하세요. 저기 그 열이 심한 환자가 있어서 성해병원으로 갈 건데 좀 도움 좀 주세요. 열 증상 말고 또 어떤 증상이 있어요? 신고자분? 예 열이 39도 이상 올라가고 몸이 막 떨리고 영재가 됐어요? 네네네. 신고자 분 누가 어떻게 아프신 건지 다시 말씀해 주세요. 예, 제 남편이 그 45년생인데 어제부터 열이 있었어요. 38초 정도. 코로나가 발생한 건 없으시고요? 코로나인지는 모르겠어요. 그래서 빨리 가보려고요. 병원 쪽하고 연결 연락이 됐다고요? 예, 예. 성해 성해병원으로요. 일단은 지금 계신 곳 주소 알려주세요. 예 여기가 그 관악구 광신길. 예. 예. 예 저희가 경비실 앞으로 내려갈 순 있어요. 잠시만요. 신분이 차를 지금 파손해서 보내드리고는 있는데. 네. 응원 증상이 있으시면 요즘에는 진료가 안 되는 가능성이 좀 높아요. 네. 오늘 차 보내드렸고 의식 호흡은 괜찮으신 거예요? 예? 움직이나 호흡은 괜찮아요? 예예 괜찮아요. 다른 기존 있으셨어요? 이게 원래 그 신혈관 그 저기 스탠 시술도 하고 뭐 그래서 병원에서 늘 검사하고 있거든요. 알겠습니다. 차 출동시켰다고 말씀드렸고 네. 한번 더 전화드릴 수 있어요. 기침 목구멍 통증은 없으세요? 예 그런 거는 전혀 없고요. 몸이 그냥 몸살처럼 너무 몸만 아프다고 그러네요. 가입하셔서 잘 받으세요.
 네, 감사합니다. 무슨 일이세요? 네, 저기 그 집에 어머님이 계시는데요. 네네. 좀 오늘 지금 열이 많이 나시고 네, 지금 어머님. 밖에 외출을 안 하시거든요. 근데 열이 많이 나시고 기력이 없으셨고 지금. 의식은 있으세요? 의식이 없어요. 의식이 없다고? 수문도 안 써요? 원래 치매가 있으셔가지고 나이가 많으세요. 80. 선생님 위치 알려주세요. 구급차 보내드릴게요. 위치요. 저기 어 방화대로 48길. 잠시만요. 방화대로 48길 맞으세요? 네 네 네 네 네 네 네 네 네 네 네 네 네 네 네 잠시만요. 그쪽으로 구급차가 출발한 게 잠시만 확인 좀 해볼게요. 아 저 처음 전화한 거예요. 지금 구급차 출발했고요. 선생님. 어머님 의식이 없다고 하셔서요. 저희 오류진 좀 연결 좀 할게요. 잠깐만 전화 끊지 말고 기다리세요. 의식은 원래 저기 저기 저 계속 주무셔갖고 낮에 계속 주무시길래 잠이 많으시나 갑자기 열이 나지고 그래서. 평소에도 대화가 안 되세요? 평소에는 대화가 가능하신 거죠? 예예예. 치매가 있자 갖고 그렇게 하는데. 오늘 갑자기 의식이 떨어지신 거죠? 어제 어제부터 갑자기 좀 밥을 잘 안 먹어갖고 그래서 좀 행설조사를 하시더니 오늘 좀 누워 계시다가 예예.
 119입니다. 네 뭐 좀 여쭤보려고 그러는데요. 예. 산모인데요. 예. 아직 임신 초기고요. 의료 상담이시면 저희 의료진 연결해드릴까요? 의료 상담은 아니고요. 예예예. 지금 출혈이 있는데요. 예. 지금 가장 가까운 데가 삼계 백병원이거든요. 예. 근데 이 백병원을 가면 제가 지금 막 애기가 있어서 애 아빠는 집에 있어야 되고 저만 가야 되는데. 예. 어 가면은 뭐 이렇게 수속 밟고 그다음에 코로나 검사고 이런 게 있을까요? 어 예 그 부분은 저희 안내부서를 통해서 한번 상담을 받아보셔야 될 것 같고요. 네 아니면은 구속차를 부르려고요. 제가 지금 치료를 있어서 막 걸어다니고 가서 혼자 가서 수속을 받고 뭐 코로나 검사를 하고 이럴 수 있는 사항이 아니거든요. 예 일단은 구속차를 바로 보내드릴 수는 있거든요. 신고자분. 네 어떻게 하는 게 나을까요? 예 혼자 만일에 가시는 상황이시면 구급차를 타고 가셔서 대원들이 좀 도와드리고 수습받고 그다음에 상계 백병원이 되는지 안 되는지도 지금은 확인을 해야 되거든요. 모르니까요. 네. 병원이 수시로 바뀌기 때문에 상황이요. 그 부분도 대원들이 도와드려서 가능한 병원 그다음에 임산부시기 때문에 이제 임산부 받을 수 있는 병원이 있는지 그것도 확인해야 되기 때문에요. 그러면은 좀 119로 좀 불러주세요. 계신 곳 위치나 주소 말씀해 주세요. 여기 상계 주공 16단지고요. 예 몇 동 몇 호세요? 계단 몇 호요세요? 비상 계단으로 살살 내려갈 수는 있거든요. 예 잠시만요. 사이린도 조용히 요청하고 구급차 어디 있나 확인해 보겠습니다. 잠시만요. 제일 가까이 있는 구급차는 방학동에 1대밖에 없거든요. 거기도 출동할 거고요. 지금 그럼 몇 주신 거예요? 초기시면? 지금 내일이 6주요. 6주. 그 다음에 발열이나 지침 코로나 같은 증상은 특별히 다 없으신 거고요. 알겠습니다. 구급제에 출동하고요. 병원 가실 준비하고 계세요. 사이렌 울리지 말아달라고 요청하겠습니다. 그럼 언제 제가 내려가면 될까요? 아마 대원들이 전화드릴 거고요. 3km 떨어져 있으니까 한 10분 정도면 도착할 수 있을 겁니다. 예 예 출동하겠습니다.
 119입니다. 근데 여기 동구 골든 아파트. 동구 골든 아파트요? 네. 네. 우리 애기가. 몇 호요? 아기가 여기 언제지? 누가 아픈거에요? 여보세요? 네 12월 28일날 이거 수사를 맞았어요 백신? 네 백신... 이건 뭐지? 예예예 백신이요. 그래 코로나 백신이요? 코로나 백신을 맞았는데요. 애가 계속 잠만 자고 밥도 안 먹으려고 하고 근데 잤는데 댁에 티가 조금 묻어 나왔어요. 지금 어디가 아픈 거예요? 자녀분 몇 살인데요? 96년생이에요. 96년생이면 20대? 예 근데 얘가 장애인이라 애기가 말을 못해요. 장애이가 있어요? 남성 여성? 남자인가요? 말을 못해요. 어디가 아픈지도 뭐라고 말할지도 모르고 이런데 이렇게 하면 어떡해요 병 가야 되지 않겠어요? 지금 상태가 어디가 안 좋은 거예요? 막 평소랑 틀려요? 응사랑 틀리죠 밥도 안 먹으려 그러고 네 그냥 계속 잠만 자요 아 그래서 선생님 뭐 지금 병원을 이송하시려는 거예요? 구급차 타 병원 가보시려는 거예요? 네 그러고 얘가 자는데 목에에 피가 못해 나와요 음 어디서 피가 나는 거예요? 입? 얼굴? 이래서 나왔는 거겠죠? 벽에 묻었으니깐요. 아 일단 구급차 그쪽으로 보낼게요. 뭐 집에 따로 코로나 때문에 뭐 격리하시는 분이나 확인도 없으시죠? 열이거나 그런 건 없어요. 에 구급차 보냈어요. 선생님 좀 기다려 보세요. 차 보냈어요. 끊고 기다려 보세요.
 네, 알겠습니다. 네, 수고하십니다. 제가 아까 전화드렸었는데요. 구토가 너무 심해가지고요. 구토요? 예, 웬만하면 혼자 병원을 가보려고 했는데 제가 혼자 있거든요. 아, 혼자 병원을 가기 너무 힘들어가지고요. 부탁드려도 될까요? 구토가 하신다는 거죠? 구토? 네 어지럽고 구토가 계속 구토를 3시간째 해가지고 어지러워가지고요. 주소 어떻게 되세요? 루봉구 시루봉로 22길 22길에 몇 층이에요? 몇 층? 제가 1층까지 내려갈게요. 호르마 관련 다른 증상은 없어요? 다른 증상은 없고요. 3차 부스터 샷 12월 17일 날에 맞았어요. 차 나가주세요. 전화차 가주세요. 네.

Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

 네 119입니다. 말씀하세요. 어 여기 지나가는데. 네. 여기 증산역 뒷골목이거든요. 여기 가게가 뭐 부동산 있고 희망 부동산 있고. 아 잠시만요. 희망 부동산이요? 잠시만요. 아 금산구 증산동. 여기 1 4번 출구 3번 출구 요 뒤쪽 라인인 거죠? 네 희망 부동산 뒤에 횟집 있거든요. 희망 부동산 뒤쪽 횟집이요. 횟집 그 옆에 뭐 만두가게인가 노란색 집인데. 네. 그 그 문 앞에 사람이 쓰러져 있어요. 아 남자분이요? 여자분이에요? 남자분이요. 지나가다가 그냥 쓰러져 걸어가다가 그냥 쓰러졌다고 하던데. 아 그냥 걸어가서 앞에 쓰러졌대요? 예 검은색 옷 입고 검은 가방. 잠시만요. 젊은 사람 같아요. 혹시 의식이랑 호흡 있는지 확인 가능할까요? 아 저 제가 지금 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차 차
 여보세요? 네, 저 할머니가 그 못 일어나셔서. 지금 같이 계세요? 할머니 의식이 없나요? 어 네, 의식은 없고 호흡은 있으신데. 예, 예. 주소가 어떻게 되세요? 예. 고자 보내드릴게요. 잠시만요. 관악구 운처로 34길에. 네네 에메랄드 아파트인가요? 할머니 호흡은 정상적으로 하시는거죠? 네 호흡은 정상적으로 하시는데 산소포화도가 좀 낮고요 몇이 나와요 산소포화도가? 92 나오고 있어요 92 간호사하고 의료질도 연결할거에요 전화패스 라디오 잠시만요 네 자가격이나 확진 관련된 건 없으시죠? 어.. 자가격이? 없어요 지금 아직 네 코로나 관련된 건 없고요 잠시만요
 예 예제구입니다. 예 지금 전에 전화했던 사람인데요. 예 예. 간호 예 간호사 번호하고 통화를 했는데. 병원을 가야 할 것 같다고 하더라고요. 고급차가 필요하신 거예요? 예 예 저희 어머니 거두기 불편하시는데 3청 서울 병원으로 가야 해서요. 어떻게 돼요? 서울시 상북구. 예 예. 동서문동 4가. 예. 송산 아파트. 송산 아파트? 예. 예. 어머니가 어디가 아프신 거예요? 아 저희 어머니가 치매가 있으시고 어 저기 한 달 저기 한 3주 전 중에 병원에 입원을 해서 약 2종 하던 중에 저기 대변하고 방광룡 중에 저 간념이 있으셔 갖고 그걸 낫는 과정에서 저기 격리에 격리하고 그러느라고 한 20 동안 움직이지를 못하셔 갖고 지금 병원 다 나오셨는데 거름이 원활하지가 않으세요. 없으시단 말씀이세요? 아 그니까 지금 증세가 거름 되란 말씀이시죠? 코로나 뭐 이런 건 없으신 거고 따로 발견은 알았습 구급처 나갑니다.
 불러 거거든? 차 키는 여기다 둔 거가? 어. 아 네 저기 저희 지금 조금 좀 급한 상황이라 조금 그 응급 대원분께서 좀 오셔야 될 거 같은데. 그 미아동. 몇 동 몇 동 몇 호예요? 아 동은 하나고요. 지금 음식 먹다가 급 체한 것 같은데 지금 같이 있던 일행이 여자분이에요? 남자예요. 남자고사 26세예요. 지금 의식 있고 호흡 있어요? 지금 계속 배가 아프다고 계속 통증을 호소하고 있거든요? 예, 지금 자출발했고요. 코로나 확진 된 분 거기 계신 분들 중에 있어요? 아, 없어요. 지금 다 2차까지 다 맞았습니다. 예 미아동. 예. 차 나왔어요 2.5km 남았어요. 예. 네.
 네, 혹시 주이세요? 이 쇠나파 코로나 그 주사 맞고 아이가 지금 후유증쯤에 가수 통증이 온다고 전화드렸었거든요. 그래서 거기서 소개해 준 병원으로 전화하니까 어디에도 지금 받아줄 수가 없대요. 그러니까 지금 아이는 가수 통증이 점점 피해진다고 하니까. 네. 저희 2, 2, 9 차를 보내주시겠어요? 지금 계신 곳이 어디예요? 여기가 코오롱 한천로. 한천로 동대문구에요? 아뇨 아뇨 성북구요. 성북구 한천로. 호롱아파트. 잠시만요. 강북구 한천로. 성북구요 성북구. 잠시만요. 호롱아파트라는거죠? 네네. 잠시만요. 몇 동 몇 호예요? 아파트 입구로 비워갈 거니까요. 지금 2층에 대기하신 거라고요? 지금 차를 편성해서 보내드리고 있어요. 시민문역 고 옆에 있는 코로나 아파트 맞으시죠? 맞아요. 기침이나 열 목구멍 통신 같은 코로나 지금 상관없으세요? 상관없어요. 백신 맞고 그러신다고요? 네. 알겠습니다.
 119입니다. 여보세요. 119입니다. 예 예 여기 농협인데요. 네네. 그 어떤 노인분이 올라가시다가 좀 넘어지셨는데 못 일어나세요. 농협 어디? 창동 농협 하나로 맡아요. 창동 농협이요? 예 하나로 맡아요. 예. 그 정문으로 들어오면 바로 있어요. 평동농협 하나로 맞추신 쪽 하나로 맞추? 예. 정문으로 가면 돼요? 예예예예예. 어 할머니가 아프시다고요? 예예예예. 지금 안전은 되셨는데. 네네. 어디가 불편하신지는 모르시고요. 잠깐만요. 어디가 어디 불편하세요? 어디 불편하세요? 예? 요 잠깐만요. 요 하나 어 다리 다리는 하지 말고. 1 2 으쌰. 요 앉아보세요. 저기 지금 이런 소식인 이런 소식인 하셨어요. 어 아니면 여기 여쭤보시고. 네네. 여쭤보고. 구급차장 병원 가시는 건 맞죠? 선생님. 잠깐만요. 의사를 여 여 전 여쭤보고 잠깐만요. 구급차 문자로 들려드릴까요? 구급차? 구급차가 선생님 구급차가 집으로는 이송을 못하고요. 병원으로 가야 돼요. 병원. 1번 사진 찍어보셔야 될 것 같은데. 아 그 책에 붙어 오면 내가 말 좀 예 불러드릴까요? 예 불러드릴까요? 내가 어디 왔다 갔다 왔다 갔다 왔다. 아니 여기 아니 아니 여기서 걸렸어요. 예. 1 2번 나오세요. 여기 문자. 불러드려요? 불러드려요? 지금 119예요. 불러드려요? 아 잘 모르겠어요. 네. 네. 네. 잘 모르겠어요. 어 그러면 불러드릴게요. 여기요. 잘 모르겠다고. 예예. 예. 여기서 이렇게 가시다가 넘어졌어요. 선생님 하나로부터 전문으로 갈게요. 안쪽으로. 예예예. 예예예예.
 여기 번일동 신진빌라 천천히 좀 불러주세요. 주소 좀. 번일동이요? 네. 잠시만요. 맞아요? 네. 네. 신진빌라. 예. 아버지가 갑자기 막 절절절 떠서서 두드러기 올랐다가 열이 막 오르시는 것 같거든요. 오한.. 오한 증세.. 네 오한이 너무 심해요. 막 손이 손발이 막 절절로 떠서 온몸이 빨갛고 네 오한 증세 말고 뭐 다른 거는 없죠? 전신에 두드러기 때문에 아까 응급실을 다녀오셨는데 네 그것 때문에 두드러기도 있고요 지금? 네 아버지 의식이나 호흡은 괜찮아요? 호흡이 조금 가쁘세요. 살까. 호흡이 가쁘다고요? 의식은 괜찮습니까? 네. 일어나서 옷 입고 계세요. 아 네. 아버지 열이나 지금 기침 뭐 코로나 관련 사항 있으세요? 아니 없습니다. 3차까지 다 받으셨어요. 네 알겠습니다. 그거부터 출동할 거고요. 네. 네 전화 잘 받으세요. 네. 네. 먼저 가기 썼다고요?
 네 여기 뭐라고 해야 돼요? 덕구정역 현대주유소 있는 데 쪽인데요. 현대주유소요? 네네 검색 좀 해볼게요. 네 새 서울 주유소 아니에요? 선생님? 어 새 서울 주유소요? 어 그 현대 아파트 건너편. 어 극동 타워. 네네네. 무슨 일이세요? 거기 네. 고픈데. 뭐 어떻게. 뭐 누가 아프신 거예요? 네. 티가 흐르는 것만 느껴지고 나머지는 잘 모르겠어요. 누군데요? 모르시는 분? 아 저예요. 지금 전데. 선생님이. 관절은. 네. 관절은 움직이는데. 낙상하셨어요? 아니요. 그 칼날에 베어가지고 베었는데. 어 칼을 어디를? 손에? 손? 엄지요. 엄지요. 네. 네. 네. 아 손을. 엄지 안쪽 손바닥 베이신 거예요? 엄지 손바닥을 베이신 거예요? 네. 손바닥. 근데 뼈가 다 보여가지고요. 손바닥을요? 칼에 베이신 거예요? 네. 아 병원 가시려고 하는 거예요? 구급자로? 네 근데 많이 찢어져가지고. 네. 뜨가 보이거든요? 음 열이거나 그런 건 없으세요? 네 없어요. 뭐 하시다가 베인 거예요? 그 건축 정동 작업하다가. 네. 이렇게 들어가가지고. 네 컸다 커요. 아 네 잠시만요. 차에 딱 보냈고요. 그 주유소 앞에 계세요? 네. 네.
                                 file_name  \
0    651e464d69a4f266f0626820_20220101.wav
1    651e464d69a4f266f062681a_20220101.wav
2    651e464d69a4f266f062681b_20220101.wav
3    651e464d69a4f266f062680e_20220101.wav
4    651e464d69a4f266f0626815_20220101.wav
..                                     ...
824  651e464d69a4f266f0626a16_20220101.wav
825  651e464d69a4f266f0626a18_20220101.wav
826  651e464d69a4f266f0626a21_20220101.wav
827  651e464d69a4f266f0626a22_20220101.wav
828  651e464d69a4f266f0626a23_20220101.wav

                                         transcription
0    {'text': ' 네, 119입니다. 말씀하세요. 아 네, 그 계속 토로 해가지고...
1    {'text': ' 감사합니다. 무슨 일이세요? 아 네 여보세요? 네 말씀하세요. ...
2    {'text': ' 여보세요? 예예. 왜 애가 갑자기 지금 시선을 이렇게 며이셔죠?...
3    {'text': ' 네 여기 저 방산 센트럴 아이터크. 잠시만요. 방산 센트럴 아이...
4    {'text': ' 네 그 어 여기가 보문동 자이 아파트거든요. 보문 파크뷰 자이요...
..                                                 ...
824  {'text': ' 불러 거거든? 차 키는 여기다 둔 거가? 어. 아 네 저기 저희...
825  {'text': ' 네, 혹시 주이세요? 이 쇠나파 코로나 그 주사 맞고 아이가 지...
826  {'text': ' 119입니다. 여보세요. 119입니다. 예 예 여기 농협인데요....
827  {'text': ' 여기 번일동 신진빌라 천천히 좀 불러주세요. 주소 좀. 번일동이...
828  {'text': ' 네 여기 뭐라고 해야 돼요? 덕구정역 현대주유소 있는 데 쪽인데...

[829 rows x 2 columns]

In [ ]:
df

,file_name,transcription
0,651e464d69a4f266f0626820_20220101.wav,"{'text': ' 네, 119입니다. 말씀하세요. 아 네, 그 계속 토로 해가지고..."
1,651e464d69a4f266f062681a_20220101.wav,{'text': ' 감사합니다. 무슨 일이세요? 아 네 여보세요? 네 말씀하세요. ...
2,651e464d69a4f266f062681b_20220101.wav,{'text': ' 여보세요? 예예. 왜 애가 갑자기 지금 시선을 이렇게 며이셔죠?...
3,651e464d69a4f266f062680e_20220101.wav,{'text': ' 네 여기 저 방산 센트럴 아이터크. 잠시만요. 방산 센트럴 아이...
4,651e464d69a4f266f0626815_20220101.wav,{'text': ' 네 그 어 여기가 보문동 자이 아파트거든요. 보문 파크뷰 자이요...
...,...,...
824,651e464d69a4f266f0626a16_20220101.wav,{'text': ' 불러 거거든? 차 키는 여기다 둔 거가? 어. 아 네 저기 저희...
825,651e464d69a4f266f0626a18_20220101.wav,"{'text': ' 네, 혹시 주이세요? 이 쇠나파 코로나 그 주사 맞고 아이가 지..."
826,651e464d69a4f266f0626a21_20220101.wav,{'text': ' 119입니다. 여보세요. 119입니다. 예 예 여기 농협인데요....
827,651e464d69a4f266f0626a22_20220101.wav,{'text': ' 여기 번일동 신진빌라 천천히 좀 불러주세요. 주소 좀. 번일동이...
828,651e464d69a4f266f0626a23_20220101.wav,{'text': ' 네 여기 뭐라고 해야 돼요? 덕구정역 현대주유소 있는 데 쪽인데...

In [ ]:
df.head(10)

,file_name,transcription
0,651e464d69a4f266f0626820_20220101.wav,"{'text': ' 네, 119입니다. 말씀하세요. 아 네, 그 계속 토로 해가지고..."
1,651e464d69a4f266f062681a_20220101.wav,{'text': ' 감사합니다. 무슨 일이세요? 아 네 여보세요? 네 말씀하세요. ...
2,651e464d69a4f266f062681b_20220101.wav,{'text': ' 여보세요? 예예. 왜 애가 갑자기 지금 시선을 이렇게 며이셔죠?...
3,651e464d69a4f266f062680e_20220101.wav,{'text': ' 네 여기 저 방산 센트럴 아이터크. 잠시만요. 방산 센트럴 아이...
4,651e464d69a4f266f0626815_20220101.wav,{'text': ' 네 그 어 여기가 보문동 자이 아파트거든요. 보문 파크뷰 자이요...
5,651e464d69a4f266f062682f_20220101.wav,{'text': ' 1월 1일부터. 아 네 저기 지금 요양원이에요. 네 근데 그 어...
6,651e464d69a4f266f0626869_20220101.wav,{'text': ' 여보세요? 예 선생님 119 입니다. 네네. 예 선생님 아 부모...
7,651e464d69a4f266f062680f_20220101.wav,{'text': ' 119입니다. 예 저 119죠? 네네. 아 여기 아저씨가 자리를...
8,651e464d69a4f266f0626819_20220101.wav,{'text': ' 119 입니다. 여보세요? 예. 예 여기 노인장반이 좀 저 쓰러...
9,651e464d69a4f266f062681f_20220101.wav,{'text': ' 네. 일로 봅니다. 아 네. 그 이거 제가 예 저거 운기차 좀 ...

In [ ]:
df.to_csv("dataset_whisper-3.csv")

### (2) 오디오 데이터 추가 수집(제작) 및 변환

* 문서 요약 함수로 생성

In [ ]:
#7.8는 응답속도가 너무 느려서 2.4로 줄여서 해야될듯

trnas_model_name = "LGAI-EXAONE/EXAONE-3.5-7.8B-Instruct"

trnas_model = AutoModelForCausalLM.from_pretrained(
    trnas_model_name,
    torch_dtype=torch.bfloat16,
    trust_remote_code=True,
    device_map="auto"
)
tokenizer = AutoTokenizer.from_pretrained(trnas_model_name)

# Choose your prompt
prompt = "Explain how wonderful you are"  # English example
prompt = "스스로를 자랑해 봐"       # Korean example

messages = [
    {"role": "system", "content": "You are EXAONE model from LG AI Research, a helpful assistant."},
    {"role": "user", "content": prompt}
]
input_ids = tokenizer.apply_chat_template(
    messages,
    tokenize=True,
    add_generation_prompt=True,
    return_tensors="pt"
)

output = trnas_model.generate(
    input_ids.to("cuda"),
    eos_token_id=tokenizer.eos_token_id,
    max_new_tokens=512,
    do_sample=False,
)
print(tokenizer.decode(output[0]))

In [ ]:
def text_summary(input_text):
    # 시스템 역할과 응답 형식 지정
    system_role = "당신은 응급상황에서 어떠한 상황인지 파악하고, 증상을 간단한 키워드로 요약하는 어시스턴트입니다. 응답은 다음의 형식을 지켜주세요 {\"summary\": \"텍스트 요약\", \"부위\": \"다친 부위\", \"증상\": \"관련 증상\"}"

    # 입력데이터를 EXAONE-3.5에 전달하고 답변 받아오기
    messages = [
    {"role": "system", "content": system_role},
    {"role": "user", "content": input_text}]

    input_ids = tokenizer.apply_chat_template(messages,
    tokenize=True,
    add_generation_prompt=True,
    return_tensors="pt")

    output = trnas_model.generate(
    input_ids.to("cuda"),
    eos_token_id=tokenizer.eos_token_id,
    max_new_tokens=256,
    do_sample=False,)

    # 응답 받기
    response = tokenizer.decode(output[0])

    match = re.search(r'json\n(.*?)\n', response, re.DOTALL)
    if match:
       json_str = match.group(1)
       print(json.loads(json_str))
    else: raise ValueError("JSON 데이터를 찾을 수 없습니다.")
    # 응답형식을 정리하고 return
    return json.loads(json_str)

In [ ]:
'''
# 기본 포맷
# 시스템 역할과 응답 형식 지정
system_role = "당신은 응급상황에서 어떠한 상황인지 파악하고, 증상을 간단한 키워드로 요약하는 어시스턴트입니다. 응답은 다음의 형식을 지켜주세요 {\"summary\": \"텍스트 요약\", \"부위\": \"다친 부위\", \"증상\": \"관련 증상\"}"
input_text = "지금 아빠가 넘어졌어요. 머리에서 피가 나는데 숨은 쉬고 있어요. 지금 막 일어났어요. 근데 조금 어지럽다고 하네요. 네, 네. 계단에서 굴렀어요. 지금은 물 마시고 있는데 이거 응급실로 가봐야 할까요? 피도 지금 멎었어요. 네, 네. 나이는 49살이세요. 어떻게 해야 할지 모르겠어요."
# 입력데이터를 EXAONE-3.5에 전달하고 답변 받아오기
messages = [
{"role": "system", "content": system_role},
{"role": "user", "content": input_text}]

input_ids = tokenizer.apply_chat_template(messages,
tokenize=True,
add_generation_prompt=True,
return_tensors="pt")

output = trnas_model.generate(
input_ids.to("cuda"),
eos_token_id=tokenizer.eos_token_id,
max_new_tokens=128,
do_sample=False,)

# 응답 받기
# print(tokenizer.decode(output[0]))
response = tokenizer.decode(output[0])
match = re.search(r'json\n(.*?)\n', response, re.DOTALL)
if match:
    json_str = match.group(1)
    print(json.loads(json_str))
else: raise ValueError("JSON 데이터를 찾을 수 없습니다.")
print(json.loads(json_str))
'''

'\n# 기본 포맷\n# 시스템 역할과 응답 형식 지정\nsystem_role = "당신은 응급상황에서 어떠한 상황인지 파악하고, 증상을 간단한 키워드로 요약하는 어시스턴트입니다. 응답은 다음의 형식을 지켜주세요 {"summary": "텍스트 요약", "부위": "다친 부위", "증상": "관련 증상"}"\ninput_text = "지금 아빠가 넘어졌어요. 머리에서 피가 나는데 숨은 쉬고 있어요. 지금 막 일어났어요. 근데 조금 어지럽다고 하네요. 네, 네. 계단에서 굴렀어요. 지금은 물 마시고 있는데 이거 응급실로 가봐야 할까요? 피도 지금 멎었어요. 네, 네. 나이는 49살이세요. 어떻게 해야 할지 모르겠어요."\n# 입력데이터를 EXAONE-3.5에 전달하고 답변 받아오기\nmessages = [\n{"role": "system", "content": system_role},\n{"role": "user", "content": input_text}]\n\ninput_ids = tokenizer.apply_chat_template(messages,\ntokenize=True,\nadd_generation_prompt=True,\nreturn_tensors="pt")\n\noutput = trnas_model.generate(\ninput_ids.to("cuda"),\neos_token_id=tokenizer.eos_token_id,\nmax_new_tokens=128,\ndo_sample=False,)\n\n# 응답 받기\n# print(tokenizer.decode(output[0]))\nresponse = tokenizer.decode(output[0])\nmatch = re.search(r\'json\n(.*?)\n\', response, re.DOTALL)\nif match:\n    json_str = match.group(1)\n    print(json.loads(json_str))\nelse: raise ValueError("JSON 데이터를 찾을 수 없습니다.")\nprint(json.loads(json_str))\n'

* 저장된 text를 하나씩 불러와서 요약하고 다시 저장하기

In [ ]:
import re
response = []
for i in range(len(df)):
    input_text = df['transcription'][i]['text']
    print(input_text)
    summary = text_summary(input_text)
    response.append(summary['summary'])

 네, 119입니다. 말씀하세요. 아 네, 그 계속 토로 해가지고. 어느 분. 어 어 병원은 지금 움직일 수가 없어서. 어느 분이 계속 토로 하세요? 아 저희 언니요. 언니가요? 네. 토하시고. 네. 우리 쪽이랑 호흡은 다 있어요? 네. 아 네, 보급차 보내드릴 건데 주소가 어떻게 되세요? 강서구. 네. 화공로 18길. 잠시만요. 화공 18길. 강서 뉴 타워. 잠시만요. 강서 뉴 타워. 네. 아 잠시만요. 언니분이랑 동생은 최근에 뭐 코로나 관련해서 의심 증상이나 뭐 접속했다고 문자 받으신 거 없으시죠? 아 네 알겠습니다. 배원도 나가면서 전화드릴 수 있으니까 전화 한번 안내 좀 부탁드릴게요. 아 네 알겠습니다.
{'summary': '언니가 구토 증상을 보이고 있으며, 호흡에는 문제가 없음.', '부위': '위장', '증상': '구토'}
 감사합니다. 무슨 일이세요? 아 네 여보세요? 네 말씀하세요. 무슨 일이세요? 아 지금 뭐 현압을 해보니까 현압이 너무 높아요. 누구야 선생님이요? 네 177이 넘고 지금 막 그 약간 말이 안 나오고 춥고 막 그러거든요. 조금만 보내드릴까요 선생님? 네 여기 아우 힘들어요. 말이 어눌하신 거예요? 말이 하는 게 어려운 거예요? 아 추워요 지금. 그냥 추운 거예요? 말이 어누라 그냥 한쪽으로 힘 빠지는 건 없으시죠? 네 추워요. 네 구급차 위치 좀 보내드릴 구급차 좀 보내드릴게요. 위치 좀 알려주실 수 있으실까요? 네 여기 포르주아 아파트. 하곡 포르주아 맞으세요? 선생님? 네. 맞으세요? 네 네. 혹시 근데 코로나 관련해서 뭐 확진자를 접촉하거나 그러신 거 있으세요? 아니요. 코로나 주사를 제가 화요일 날 맞았어요. 네. 아 그러는데 한 3일만은 괜찮았는데 어제서부터 약간 하락이 올라가더라고요. 선생님 그쪽으로 하구 프로지오 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 네. 혹시 모릅니다. 문 좀 열어두세요. 선생님. 전화 구급회원들 가면서 전화할 거고요. 전화 잘 받아주세요. 알겠습니다. 감사합니다.

KeyboardInterrupt:

In [ ]:
for i in range(len(df)):
    try:
        input_text = df['transcription'][i]['text']  # 'text' 필드 확인
        if not isinstance(input_text, str):
            raise ValueError(f"Invalid input format at index {i}: {input_text}")

        summary = text_summary(input_text)
        response.append(summary)
    except Exception as e:
        print(f"Error at index {i}: {e}")
        response.append(None)

{'summary': '언니가 구토 증상을 보이고 있으며, 호흡에는 문제가 없음.', '부위': '위장', '증상': '구토'}
{'summary': '갑작스러운 고혈압 상승, 말 어눌함, 추위 느낌, 약간의 의식 저하 의심', '부위': '전신', '증상': '고혈압 (177 이상), 말 어눌함, 추위 느낌, 의식 저하 의심'}
{'summary': '성인 남녀가 갑자기 의식을 잃고 눈동자가 고정된 상태로 바닥에 쓰러졌으며, 호흡은 있으나 불규칙적일 가능성이 있음.', '부위': '전신', '증상': '의식 상실, 고정된 눈동자, 호흡 있음 (불규칙 가능성)'}
{'summary': '집사람이 복부에서 탈장 증상을 보이고 있습니다.', '부위': '복부', '증상': '탈장'}
{'summary': '할아버지가 집 안에서 쓰러져 움직이지 않고 있습니다.', '부위': '전신', '증상': '의식 불명, 무반응'}
Error at index 5: Expecting property name enclosed in double quotes: line 1 column 80 (char 79)
{'summary': '사망 의심되는 환자, 과거 며칠 전 사망 추정', '부위': '전신', '증상': '의식 상실, 호흡 없음'}
{'summary': '남편이 계단에서 떨어져 발목 부상 의심, 다리 굽힘 증상 지속', '부위': '발목', '증상': '다리 굽힘, 통증'}
{'summary': '남성 노인이 왼쪽 골반 골절로 쓰러졌으며, 코로나 관련 증상은 없음.', '부위': '왼쪽 골반', '증상': '골절, 쓰러짐'}
{'summary': '아버지가 호흡곤란을 겪고 있으며, 현재 구급차가 도착한 상태입니다.', '부위': '전체', '증상': '호흡곤란'}
{'summary': '아랫배 통증이 시작되어 점점 심해지고 있음', '부위': '아랫배', '증상': '지속적인 복통'}
{'summary': '심한 복통 호소', '부위': '복부', '증상': '복통'}
{'summary': '전신 통증으로 인해 거동이 불편한 상태, 의식은 있으나 명확한 의사소통 어려움', '부위': '전신', '증상': '전신 통증, 의사소통 어려움'}
{'summary': '칼에 의한 찔림 사고 발생', '부위': '다리', '증상': '깊은 칼상, 출혈'}
{'summary': 'HPV 백신 접종 후 전신 부종 및 발열 증상 발생', '부위': '전신', '증상': '부종, 발열'}
{'summary': '백혈병 환자로, 최근 헤르페스 감염으로 인해 눈 시력 저하 및 두통 증상 발생, 서울대병원 응급실 이송 필요', '부위': '눈, 머리(두통)', '증상': '시력 저하, 두통, 헤르페스 감염'}
{'summary': '직원이 식은땀을 흘리고 어지러움을 호소하며 청력 저하를 경험하고 있습니다. 코로나 증상은 없습니다.', '부위': '전체적 (특히 내이 또는 중추신경계 관련 가능성)', '증상': '어지러움, 청력 저하, 식은땀, 창백함'}
{'summary': '남성 손님이 머리 통증을 호소하고 있으며, 다른 증상은 없다고 함.', '부위': '머리', '증상': '두통'}
{'summary': '전화 통화 중인 사람이 건물 밖으로 나가는 데 어려움을 겪고 있으며, 힘이 없다고 표현함.', '부위': '전체적인 상태', '증상': '힘 없음, 이동 어려움'}
{'summary': '취한 남성이 노원역 교보타워 뒤쪽 전주 콩나물 국밥 전문점 근처에 쓰러져 있으며, 의식이 흐릿하고 잠꼬대를 하고 있습니다.', '부위': '전신', '증상': '의식 불명확, 잠꼬대'}
{'summary': '남성 직원이 명동의 매장에서 철문에 의해 손이 찢어지는 부상을 입었습니다.', '부위': '손', '증상': '찢어짐, 끼임'}
{'summary': '심한 복통으로 인해 거동이 불가능한 상태', '부위': '복부', '증상': '심한 복통'}
{'summary': '남성 환자가 가슴 통증을 호소하며, 프라이어 팰리스 아파트에 위치해 있습니다. 환자는 남편이며, 통증이 심하지만 걷는 것이 가능합니다.', '부위': '가슴', '증상': '가슴 통증, 걷기 가능'}
{'summary': '오른쪽 옆구리 갑작스러운 통증', '부위': '오른쪽 옆구리', '증상': '갑작스러운 통증, 발열/기침 없음'}
{'summary': '문에 부딪혀 머리에서 출혈 발생', '부위': '머리', '증상': '출혈'}
{'summary': '89세 여성 환자, 갑작스러운 다리 부종 및 통증 호소, 의식과 호흡은 정상이나, 최근 코로나 관련 접촉자 정보는 없음', '부위': '다리', '증상': '심한 부종, 통증'}
{'summary': '남자 환자가 계단에서 굴러 떨어져 의식은 있으나 호흡이 불규칙하고 현재 호흡이 불분명한 상태', '부위': '전신 (특히 머리와 척추)', '증상': '의식 있음, 호흡 불규칙, 호흡 곤란 의심'}
{'summary': '어르신이 버스 안에서 쓰러져 일어나지 못하고 있으며, 다리 통증으로 인해 힘이 없음.', '부위': '다리', '증상': '의식 있음, 다리 힘 빠짐, 통증'}
{'summary': '할아버지가 의식이 있는 상태로 연신교회 옆 세븐일레븐 건물 내부에 누워 계심', '부위': '전신', '증상': '의식 있음'}
{'summary': '여자분이 무릎과 손을 경미하게 다쳤으며, 코로나 관련 증상이나 접촉자는 없음.', '부위': '무릎, 손', '증상': '경미한 외상'}
{'summary': '아내분이 코로나 백신 접종 후 심한 통증과 고열을 호소하고 있습니다.', '부위': '전신', '증상': '통증, 고열'}
{'summary': '호흡 곤란을 호소하며, 최근 코로나 관련 증상이나 의심 증상은 없다고 함', '부위': '전체', '증상': '호흡 곤란, 수면 장애'}
{'summary': '할머니가 의식을 잃고 호흡은 하고 있지만 반응이 없는 상태입니다.', '부위': '전체', '증상': '의식 상실, 호흡 유지'}
{'summary': '차에서 내린 후 의식을 잃고 앞으로 쓰러진 남성', '부위': '전신', '증상': '의식불명, 호흡가능성 있음'}
{'summary': '허리 통증 호소, 최근 코로나 백신 접종 (22일)', '부위': '허리', '증상': '통증'}
{'summary': '어머니가 감을 먹고 식중독 의심 증상을 보이며, 힘이 없어 일어나지 못하고 말도 제대로 하지 못하는 상태입니다.', '부위': '전신', '증상': '식중독 의심, 근력 약화, 발음 어려움'}
{'summary': '아버지가 심한 복통과 식은땀, 흑변, 가벼운 두통을 호소하며 응급 상황을 요청하셨습니다.', '부위': '복부', '증상': '복통, 식은땀, 흑변, 두통'}
{'summary': '딸이 심한 복통을 호소하고 있어 구급차를 요청했습니다.', '부위': '복부', '증상': '급성 복통'}
{'summary': '코로나 확진 이력 있으며, 최근 예방 접종 완료. 과거 국내 접촉자 있었으나 격리 해제 후 일정 기간 경과.', '부위': '전체', '증상': '없음 (증상 언급 없음)'}
{'summary': '어머니께서 오한, 추위, 몸살 증상을 보이고 있으며, 코로나 관련 증상은 없다고 합니다.', '부위': '전체적인 몸', '증상': '오한, 추위, 몸살'}
{'summary': '응급 상황이 해소되었으나, 상태 변화에 주의 필요', '부위': '전체', '증상': '없음'}
{'summary': '다리가 갑자기 움직여 고통을 호소하는 가족이 오성아파트 근처에서 발생', '부위': '다리', '증상': '갑작스러운 움직임, 통증'}
{'summary': '어머니의 상태가 급격히 악화되어 응급 처치 필요성이 제기되고 있으나, 아버지의 거부로 인해 의료진의 개입이 어려움.', '부위': '전체적 (증상에 따른 특정 부위 미상)', '증상': '상태 악화, 의식 변화 의심'}
{'summary': '고관절 통증으로 인해 이동 및 배변이 어려움', '부위': '고관절', '증상': '통증, 이동제한, 배변곤란, 발열 없음'}
Error at index 44: JSON 데이터를 찾을 수 없습니다.
{'summary': '외상으로 인해 심각한 출혈이 발생한 것으로 보임', '부위': "전신 (특히 언급된 '꽉 찢어짐' 부위는 불명확)", '증상': '출혈, 의식은 있으나 위급 상황'}
{'summary': '할아버지가 식사 중에 의식을 잃었다가 회복되었으나 다시 의식을 잃어가는 상태입니다.', '부위': '전체', '증상': '의식 소실, 간헐적 의식 회복'}
{'summary': '집사람의 목 통증과 가슴 벌렁거림 호소', '부위': '목, 가슴', '증상': '목 통증, 가슴 벌렁거림'}
{'summary': '노인 남성 환자, 혈전 증상 호소, 최근 코로나 증상 없음, 백신 접종 완료', '부위': '전신 (특히 뇌 관련 의심)', '증상': '혈전, 인지 기능 저하 의심'}
{'summary': '사망 의심, 의식 없음', '부위': '전신', '증상': '의식 상실'}
{'summary': '음주 상태의 여성 승객이 호흡 곤란을 호소하며 일어나지 못하고 누워있음', '부위': '전체', '증상': '호흡 곤란, 의식 저하'}
{'summary': '뒤에서 오토바이에 의해 교통사고를 당한 운전자', '부위': '전신 가능성 있음 (구체적인 부위 미상)', '증상': '다치긴 했으나 구체적 증상 언급 없음, 구급차 요청'}
{'summary': '길가에서 남녀 두 명이 쓰러져 일어나지 못하고 있는 응급 상황', '부위': '전신', '증상': '의식 불명, 움직임 불가'}
{'summary': '의식 불명 상태의 노인이 누워있음. 의사소통 어려움. 원인 불명 (술 섭취 여부 불분명)', '부위': '전체', '증상': '의식 불명, 의사소통 불가'}
{'summary': '갑작스러운 가슴 통증으로 인해 응급 상황 발생, 이전에 특정 진단을 받은 적 있음', '부위': '가슴', '증상': '갑작스러운 가슴 통증, 통증으로 인해 즉시 도움 요청'}
{'summary': '환자는 호흡은 정상이지만, 일어나려는 의지가 있으며 머리에 약간의 열감을 호소하고 있습니다.', '부위': '머리', '증상': '두통, 열감 없음'}
{'summary': '응급 상황 발생 중, 구체적인 증상 언급 없음', '부위': '정보 부족', '증상': '정보 부족'}
{'summary': '어머니가 저녁 식사 후 어지러움과 저혈압 증상을 호소하며 병원 이송 필요 요청', '부위': '전체', '증상': '어지러움, 저혈압'}
{'summary': '할아버지 호흡곤란, 의식 있음. 당뇨 및 심장질환 병력 있음. 현재 발열이나 기침은 없음.', '부위': '호흡기', '증상': '호흡곤란, 의식 명료, 당뇨, 심장질환 병력'}
{'summary': '173차 접종 후 발열 지속 (39도 이상), 병원 이송 필요', '부위': '전신', '증상': '고열'}
{'summary': '어르신이 심한 복통을 호소하고 있습니다.', '부위': '복부', '증상': '심한 복통'}
{'summary': '남성 환자가 숨 쉬기 어려움을 호소하며 가슴 통증을 느끼고 있음. 최근 코로나 검사 이력 있으나 음성이었으나 증상이 악화됨.', '부위': '가슴', '증상': '호흡곤란, 가슴 통증'}
Error at index 62: Expecting property name enclosed in double quotes: line 1 column 56 (char 55)
{'summary': '술에 취한 남성이 추운 날씨에 독산역 1번 출구 근처 자판기 옆에 앉아 있는 상태입니다.', '부위': '전신 (전반적인 상태 확인 필요)', '증상': '술취함, 추위 노출'}
{'summary': '자전거 사고로 쓰러진 환자, 의식 불명 상태', '부위': '전체적인 상태 (구체적인 부상 부위 미상)', '증상': '의식 불명, 움직임 불가, 호흡 상태 미상'}
{'summary': 'HDC 건물 앞 도로에서 택시와 일반 차량 간 급성 교통사고 발생. 운전자는 의식이 있으나 목 통증으로 구급차 요청', '부위': '목', '증상': '목 통증'}
{'summary': '얼굴 상처를 입은 남성 2명이 현장 이송을 요청했습니다.', '부위': '얼굴', '증상': '상처'}
Error at index 67: JSON 데이터를 찾을 수 없습니다.
{'summary': '남성이 의식은 있으나 몸을 떨고, 배설물을 동반한 상태로 쓰러져 있음', '부위': '전신', '증상': '의식 있음, 떨림, 배설물 배출'}
Error at index 69: JSON 데이터를 찾을 수 없습니다.
{'summary': '고속도로 주행 중 호흡곤란 증상 발생, 숨 쉬기 어려움', '부위': '전체', '증상': '호흡곤란, 숨 가쁨'}
{'summary': '수면제 과다 복용 의심, 용산동 2가 거주', '부위': '전신', '증상': '과다 복용 관련 증상 (구체적 증상 언급 없음)'}
{'summary': '환자는 몸을 움직일 수 없다고 호소하며, 여자친구가 동반하고 있으며 여자친구는 머리 부상을 입었다고 언급함.', '부위': '전신 (움직임 불가), 머리 (부상 의심)', '증상': '무력증, 머리 부상 의심'}
{'summary': '오토바이 간 충돌 사고 발생, 두 명의 부상자 발생', '부위': '전신 (구체적인 부위 미상)', '증상': '의식 불명 (2분 동안), 이후 의식 회복'}
{'summary': '버스 정류장에서 의식이 있지만 중증으로 보이는 남성이 떨어져 있는 상태였음.', '부위': '전신', '증상': '의식 있음, 중증 의심, 추위 노출'}
{'summary': '손에 상처가 생겨 출혈이 심하며, 의식은 명료하고 다른 감염 증상은 없음.', '부위': '손', '증상': '출혈, 상처'}
{'summary': '여자 두 명이 의식을 잃고 구토 증상을 보임. 남자 두 명은 의식이 있으며 호흡은 정상임. 외부 출혈은 확인되지 않음.', '부위': '전체적인 상태 (특정 부위 미상)', '증상': '의식 상실 (여성), 구토, 호흡 정상 (남성)'}
{'summary': '화장실에서 넘어져 머리 부상 및 기타 부위 골절 의심, 의식은 있으나 기억 상실', '부위': '머리, 기타 부위 (구체적인 부위 미상)', '증상': '머리 붉어짐, 기억 상실'}
{'summary': '71세 여성이 백신 3차 접종 후 고열(39도)을 보이고 있으며, 의식은 명료합니다.', '부위': '전신', '증상': '고열, 의식 명료'}
{'summary': '의식 불명 상태, 항암 치료 중인 환자', '부위': '전신', '증상': '의식 없음, 의사소통 불가, 항암 치료 중'}
{'summary': '3차 백신 접종 후 오한, 추위 느낌, 몸살 증상으로 거동이 어려움', '부위': '전체적인 몸', '증상': '오한, 추위 느낌, 몸살'}
{'summary': '신장 기능 저하로 인한 심각한 증상으로 고대 구로병원 이송 필요', '부위': '전신 (특히 신장)', '증상': '신장 기능 저하, 의식 저하 (30점 미만)'}
{'summary': '입장 통증으로 인해 거동이 불편한 상태', '부위': '입장', '증상': '통증, 거동 불편'}
{'summary': '33세 남성이 어지러워 의식을 잃은 상태로 강남 터미널에서 여수로 이동하던 중 증상이 시작되었다.', '부위': '전체적인 증상 (특히 중추신경계 관련)', '증상': '어지러움, 의식 불명, 취한 상태 후 발생'}
{'summary': '6살 아이가 내장증으로 응급 상황에 처해 있으며, 현재 호흡 중이지만 어려움을 겪고 있음.', '부위': '내장 (구체적인 부위 미상)', '증상': '내장증, 호흡 곤란'}
Error at index 85: Expecting property name enclosed in double quotes: line 1 column 85 (char 84)
{'summary': '아이가 아프고 호흡에 어려움을 겪고 있어 응급 상황으로 보입니다.', '부위': '전반적 (특히 호흡 관련)', '증상': '호흡곤란, 아동의 통증 호소'}
{'summary': '응급 상황으로 인해 식사와 약 복용이 불가능하며, 응급실 방문 필요.', '부위': '전체적인 상태 (구체적인 부위 미상)', '증상': '통증, 식사/약 복용 불가'}
{'summary': '술을 마신 여성이 호흡곤란을 호소하며 낑낑거리는 모습을 보임. 최근 코로나 감염 이력 있음 (자가격리 완료).', '부위': '전신', '증상': '호흡곤란, 낑낑거림, 의식은 있으나 호흡 곤란으로 어려움'}
{'summary': '아기가 알레르기 반응으로 인해 증상이 악화되었으며, 발진과 발열이 동반됨', '부위': '전신 (특히 피부)', '증상': '알레르기 반응, 피부 발진, 발열 (38도~40도)'}
{'summary': '시아버님의 정확한 증상은 알려지지 않았으나, 며칠 전 건강검진 후 몸이 좋지 않다고 한다.', '부위': '전체', '증상': '전반적인 불쾌감, 건강검진 후 악화'}
{'summary': '22세 여성이 몸살 증상으로 병원에서 처방받은 약을 복용 후 갑작스러운 통증과 운동실 방문 권유를 받았으나 현재 발열은 없는 상태입니다.', '부위': '전체적인 몸살 증상', '증상': '갑작스러운 통증, 몸살'}
{'summary': '남자 친구가 갑자기 넘어져 의식이 흐릿하고 귀 통증을 호소하며 코로나 증상과 유사한 두통을 느끼고 있습니다.', '부위': '머리, 귀', '증상': '의식 저하, 귀 통증, 두통'}
{'summary': '아저씨가 일주일 동안 식사를 하지 않아 영양 상태가 우려되며, 현재 가까운 응급실 접근성에 대한 정보를 찾고 있음', '부위': '전신', '증상': '식욕부진, 영양실조 의심'}
{'summary': '아내분이 초밥 섭취 후 심한 통증을 호소하며 탈진 상태로 쓰러져 있습니다.', '부위': '전신', '증상': '심한 통증, 탈진, 의식은 있으나 움직임 불가'}
{'summary': '응급 상황 발생, 구체적인 부상 내용은 불명확, 빠른 출동 요청', '부위': '불명', '증상': '부상 의심'}
{'summary': '소주병으로 인해 머리 부상을 입은 여성 환자 발생, 의식은 있으나 출혈이 심함', '부위': '머리', '증상': '출혈, 의식 있음'}
Error at index 97: JSON 데이터를 찾을 수 없습니다.
{'summary': '고객이 구토 중이며 기력이 약해 움직이기 어려움. 의식은 있음. 코로나 감염 여부는 아님.', '부위': '전체', '증상': '구토, 기력 저하'}
{'summary': '아저씨가 감기 후 의식은 있지만 혼란스러워하며 폭력적인 행동을 보이고 있으며, 식욕 부진과 변비 증상을 보임.', '부위': '전신', '증상': '혼란, 폭력성 행동, 식욕 부진, 변비'}
{'summary': '남편이 호흡 중단 및 의식 상실 상태', '부위': '전체', '증상': '호흡 중단, 의식 상실'}
{'summary': '다리 부상으로 인한 통증 호소', '부위': '다리', '증상': '통증, 걸림'}
{'summary': '어머님이 의식이 없고, 현재 입으로 숨을 쉬고 있지만 숨이 약간 거칠다. 과거 발열 증상이 있었으나 현재는 호전 중이다. 가족 중 코로나 확진자는 없다.', '부위': '전체적인 상태 (의식, 호흡)', '증상': '의식 저하, 거친 호흡, 과거 발열'}
{'summary': '8개월 여아, 목에 이물질 걸려 숨 쉬기 어려움, 현재 호흡 곤란 상태', '부위': '목', '증상': '이물질 걸림, 호흡 곤란, 입 오물거림'}
{'summary': '노숙자가 서울역 파출소 지하도(우체국 쪽)에서 넘어져 눈을 크게 다쳐 칠상 상태입니다.', '부위': '눈', '증상': '칠상, 붓기'}
{'summary': '쓰러짐', '부위': '전체', '증상': '쓰러짐, 어지러움 가능성'}
{'summary': '심한 가슴 통증, 심장 부위 통증으로 인해 수업 참석 불가', '부위': '심장', '증상': '심한 가슴 통증, 호흡 곤란 가능성'}
{'summary': '배 통증으로 인해 거동이 불편한 상태', '부위': '복부', '증상': '심한 복통'}
{'summary': '할아버지가 사우나 남탕에서 의식 저하 상태로 쓰러졌으며, 호흡은 있으나 말을 제대로 하지 못함.', '부위': '전신', '증상': '의식 저하, 호흡 있음, 의사소통 어려움'}
{'summary': '딸이 갑자기 심한 통증을 호소하며 걷지 못하고 있음. 의식은 있음.', '부위': '전신 (구체적인 부위 미상)', '증상': '통증, 보행곤란'}
{'summary': '어지럼증 호소, 열 없음', '부위': '전체', '증상': '어지러움'}
{'summary': '가스 팽창감, 손발 저림, 가벼운 호흡 곤란 의심', '부위': '전신', '증상': '가스 팽만감, 손발 저림, 호흡 곤란 의심, 코로나 증상 없음'}
{'summary': '생후 2개월 아기가 코로나 확진 후 발열(38.5도), 처지는 증상을 보임. 의식은 있으나 잠을 자고 있음. 호흡은 정상적임.', '부위': '전신', '증상': '발열, 처짐, 의식 있음'}
{'summary': '폐암 환자로 상태 악화, 호흡 곤란 및 의식 저하 증상 보임', '부위': '전반적 (특히 호흡 관련)', '증상': '호흡곤란, 의식 저하, 말하기 어려움, 눈 깜빡임 감소'}
{'summary': '심정지 환자 발생, 위치 확인 중', '부위': '전체', '증상': '심정지'}
Error at index 115: JSON 데이터를 찾을 수 없습니다.
{'summary': '다리 부상으로 인해 이동이 불가능한 상태', '부위': '다리', '증상': '다리 통증, 이동 불가'}
{'summary': '자전거에서 넘어져 구토 증상을 보임', '부위': '전신 (구체적인 부상 부위 미상)', '증상': '구토, 의식 있음'}
{'summary': '락스 섭취로 인한 중독 의심', '부위': '전신', '증상': '의식 있음, 락스 섭취 (반컵 정도)'}
Error at index 119: JSON 데이터를 찾을 수 없습니다.
{'summary': '저혈당으로 인한 의식 저하 및 호흡 곤란 의심', '부위': '전신', '증상': '저체온, 무반응 (깨우기 어려움), 호흡 곤란 (기식적 호흡), 침 흘림, 식은 땀'}
{'summary': '심장 질환자(페이스메이커 삽입)인 환자가 가슴 통증을 호소하며 응급실 방문 필요성을 언급함', '부위': '가슴', '증상': '가슴 통증 (조임, 압박감)'}
{'summary': '치매 환자 어머니가 수면 장애와 식사 거부로 인해 영양 상태가 악화되고 있으며, 응급실 치료 필요성 문의', '부위': '전신', '증상': '수면 장애, 식사 거부, 기력 저하, 잠재적 저혈당 위험'}
{'summary': '임산부가 허리 통증을 호소하며 응급실 방문 요청', '부위': '허리', '증상': '심한 통증'}
{'summary': '83세 남성이 옥산빌라에서 미끄러져 넘어지며 머리와 가슴을 다쳤습니다. 현재 의식은 있지만 가슴 전체에 통증을 호소하고 있습니다. 호흡은 정상입니다.', '부위': '머리, 가슴', '증상': '넘어짐, 머리 부딪힘, 가슴 통증'}
{'summary': '언니가 항문으로 하혈(혈변)을 하고 있으며, 다리 골절과 함께 혈압이 떨어지고 있습니다.', '부위': '항문, 다리', '증상': '하혈(혈변), 골절, 저혈압'}
{'summary': '방해물(소액) 의심으로 인한 응급 상황, 이동 제한 가능성', '부위': '전체', '증상': '이동 제한 (고급차 진입 어려움), 약간의 보행 가능'}
{'summary': '어머니가 갑자기 움직임이 불가능해졌으며, 이전에는 식사와 보행이 어려웠으나 최근에는 기저귀 착용과 대소변 조절 문제가 발생했습니다.', '부위': '전신', '증상': '움직임 장애, 대소변 장애, 과거 식사 및 보행 어려움'}
{'summary': '아버님이 넘어져서 현재 상태가 좋지 않음. 현장 주소는 화공로 31층임.', '부위': '전신', '증상': '넘어짐, 상태 악화'}
{'summary': '여자분이 롯데캐슬 근처 롯데카페 플라자 앞에서 자동차에 치여 부상당했습니다.', '부위': '부위 명시되지 않음', '증상': '의식 있음'}
{'summary': '여자친구가 샤워 중 넘어진 사고로 머리 뒤쪽에 출혈과 찢어짐이 발생, 의식 불명 상태', '부위': '머리 뒤쪽', '증상': '출혈, 머리 찢어짐, 의식 불명'}
{'summary': '무릎 부상으로 인한 통증, 병원 방문 거부 중', '부위': '무릎', '증상': '통증'}
{'summary': '68세 남성 환자가 고열로 인해 거동이 불편하여 응급실 방문이 필요함. 최근 감기 증상이 있으며, 2주 전 코로나 부스터샷 접종 후 발열 발생. 어제 코로나 PCR 검사 결과 음성 판정 받음.', '부위': '전체', '증상': '고열, 감기 증상'}
{'summary': '집사람이 갑자기 다리에 쥐가 나서 움직임이 제한되고 통증을 호소함', '부위': '다리', '증상': '쥐, 움직임 제한, 통증'}
{'summary': '아버님이 자택에서 의식을 잃은 상태입니다.', '부위': '전체', '증상': '의식 상실'}
{'summary': '20세 남성이 경기 중 갑자기 의식을 잃고 호흡이 멈춘 응급 상황', '부위': '전체적인 상태 (의식 상실, 호흡 중단)', '증상': '의식 상실, 호흡 중단'}
{'summary': '20개월 아기가 해외 약품 과다 복용 후 의식은 있으나 불안정한 상태', '부위': '전신', '증상': '약물 과다 복용'}
{'summary': '할아버지가 과도한 음주로 인해 균형을 잃고 넘어지며 얼굴에 부상을 입었으며, 혼란스러운 상태로 이동 중입니다.', '부위': '얼굴', '증상': '부상, 혼란, 균형 감각 상실'}
{'summary': '어르신의 의식이 불안정하고, 식사 및 약 복용이 불가능하며, 통증 자극에 반응하지 않음.', '부위': '전신', '증상': '의식혼란, 식욕부진, 수분 섭취 불가, 통증 무반응'}
{'summary': '여성 환자가 어지러움을 호소하며 의식은 있는 상태입니다.', '부위': '전체', '증상': '어지러움'}
{'summary': '배 아픔으로 인한 응급 상황', '부위': '복부', '증상': '배 아픔'}
{'summary': '오토바이 사고 발생, 운전자 의식불명 상태', '부위': '없음 (전체적인 사고 상황)', '증상': '의식불명'}
{'summary': '지병이 있는 환자가 갑자기 악화되어 구급차로 이송 필요', '부위': '전체', '증상': '지병 악화, 의식 있음, 기침, 발열 (코로나 관련 증상 없음)'}
{'summary': '환자는 거동이 불편한 상태로, 중앙대 병원 응급실 입원이 불가능하여 다른 병원으로 이송 필요. 주요 증상은 장기간 식사 부족으로 인한 기력 저하.', '부위': '전신', '증상': '기력 저하, 장기간 식사 부족'}
{'summary': '호흡 곤란 호소, 종종 발생했으나 오늘 더 심해짐', '부위': '호흡기', '증상': '호흡 곤란, 말하기 어려움'}
{'summary': '왼쪽 발목 부상으로 걷기 어려움, 계단에서 굴러 넘어짐', '부위': '왼쪽 발목', '증상': '통증, 보행 불가'}
{'summary': '와이프가 허리 통증으로 인해 움직임이 제한되어 병원 이송 필요', '부위': '허리', '증상': '움직임 제한, 통증'}
{'summary': '심폐소생 필요 의심, 의식불명, 호흡정지', '부위': '전신', '증상': '호흡정지, 의식불명'}
{'summary': '코로나 확진자로 자가 치료 중인 분의 상태가 악화되어 혈압 상승과 가슴 통증이 발생했습니다. 보건소와의 연락이 원활하지 않은 상황입니다.', '부위': '가슴', '증상': '혈압 상승, 가슴 통증'}
{'summary': '의식 불명 상태로, 일어날 수 없으며 호흡은 있음', '부위': '전체', '증상': '의식 불명, 호흡 있음'}
{'summary': '오른쪽 다리 통증 지속, 응급실 방문 후 차도 없음, 보행 어려움', '부위': '오른쪽 다리', '증상': '통증, 보행곤란'}
{'summary': '암 환자로 유방암 치료 중이던 여성이 갑자기 다리에 마비 증상이 발생하여 응급실 이송 요청', '부위': '다리', '증상': '다리 마비, 의식 있음'}
{'summary': '술 취한 사람이 계속 소란을 피우고 있으며, 이전에 출동했던 인원이 다시 필요함.', '부위': '전신', '증상': '소란, 음주'}
{'summary': '9살 남자아이가 왼손 손에 상처로 인한 출혈이 있음.', '부위': '왼손 손', '증상': '출혈, 상처'}
{'summary': '마루에서 넘어져 거동이 불편하며, 통증을 느끼지 못하는 상태', '부위': '엉덩이', '증상': '움직임 제한, 통증 무감각'}
{'summary': '술을 섭취한 후 저혈압 의심, 혼란스러움 표현', '부위': '전체적', '증상': '저혈압 의심, 혼란, 의사소통 어려움'}
{'summary': '어지럼증, 구토감, 땀 흘림, 쓰러질 것 같은 느낌 호소', '부위': '전체', '증상': '어지럼증, 구토, 땀 과다, 현기증'}
{'summary': '갑작스러운 어지러움과 통증 호소, 코로나 증상 없음', '부위': '전체', '증상': '어지러움, 통증'}
Error at index 158: Expecting property name enclosed in double quotes: line 1 column 57 (char 56)
{'summary': '호흡 중단, 의식 없음', '부위': '전체', '증상': '호흡정지, 무반응'}
{'summary': '자전거 사고로 인해 의식은 있으나 일어나지 못하는 노인 남성이 양계천 산책로에 떨어져 있습니다.', '부위': '전신 부상 의심 (구체적 부위 미상)', '증상': '의식 있음, 일어나지 못함'}
{'summary': '아이가 허리 통증을 호소하며 응급 상황으로 연락', '부위': '허리', '증상': '통증'}
{'summary': '한쪽 다리 괴사 및 통증으로 응급 상황, 병원비 부담으로 치료 지연 중', '부위': '양쪽 다리', '증상': '괴사, 통증, 의식 혼미'}
{'summary': '아버지가 허리 통증으로 인해 침대에서 움직이지 못하고 소변 조절에 어려움을 겪고 있습니다. 최근 병원 진료를 받았으나 호전되지 않았으며, 발열이나 기침 등의 코로나 증상은 없습니다.', '부위': '허리', '증상': '움직임 제한, 소변 실금'}
{'summary': '전신 통증, 식욕부진 5일간 지속, 코로나 확진으로 재택치료 중', '부위': '전신', '증상': '전신 통증, 식욕부진, 코로나 확진'}
{'summary': '구급차 도착 예정, 격리 중인 사람들에게 발열이나 기침 등의 증상은 없음. 보건소 연락 필요, 병원 선정 문의 중', '부위': '전체', '증상': '발열, 기침: 없음'}
{'summary': '환자는 성격병으로 인해 원래 월요일까지 수술이 불가능했으나, 상황 변화로 인해 서울 프라임 병원으로 응급 이송 필요. 사설 구급차 이용 권장.', '부위': '전체적인 상태 언급 없음', '증상': '성격병 관련 증상, 응급 수술 필요성'}
{'summary': '어머니가 심한 복통을 호소하고 있습니다.', '부위': '복부', '증상': '급성 복통'}
{'summary': '지속적인 호흡 곤란으로 응급실 방문 필요, 진정제 투여 필요성 언급', '부위': '전체', '증상': '호흡 곤란, 진정 필요'}
{'summary': '움직이지 못하고 누워있는 상태, 호흡 곤란 및 가래 끓는 소리', '부위': '전신', '증상': '호흡곤란, 가래 끓는 소리, 식욕부진, 의식 저하'}
{'summary': '할아버지가 쓰러져 있으며 움직임이 있고 눈을 뜨고 있지만 얼굴에 피가 묻어있다는 보고가 있었으나 확인되지 않았습니다.', '부위': '전신', '증상': '의식 있음, 움직임 있음, 출혈 의심 (확인 필요)'}
Error at index 171: Expecting property name enclosed in double quotes: line 1 column 57 (char 56)
{'summary': "본인은 눈 통증을 호소하며, 동생의 상태는 현재 경미하며, 주소 확인 중 어려움을 겪고 있음. 주소는 '금호산 2길'로 언급되나 정확한 위치 파악이 어려움. 거주지는 지하임.", '부위': '눈', '증상': ['눈 통증', '기억 상실 (동생 관련)']}
{'summary': '아파트 근처 사거리에 위치한 화장실 내에서 노인 여성이 의식은 있으나 몸을 움직이지 못하고 있는 상태입니다.', '부위': '전신 (특히 하체)', '증상': '의식 있음, 운동 불능, 추운 환경'}
{'summary': '위통과 구토 증상으로 인해 병원 방문 필요', '부위': '위', '증상': '위통, 구토 (7회), 전신 통증'}
{'summary': '소주병 관련 싸움으로 인한 응급상황, 다수의 부상자 발생 가능성', '부위': '전신 (구체적인 부위 미상)', '증상': '부상, 혼란'}
{'summary': '70대 여성 환자, 어지럼증으로 걷기 어려움, 응급 상황으로 병원 이송 필요', '부위': '전체', '증상': '어지럼증, 보행 불가'}
Error at index 177: JSON 데이터를 찾을 수 없습니다.
{'summary': '쥐가 나온 후 사람이 갑자기 아프다고 호소', '부위': '전체적', '증상': '발작, 기가 찬 느낌'}
{'summary': '98세 여성 환자가 숨이 차서 호흡곤란을 호소하고 있습니다.', '부위': '전체', '증상': '호흡곤란, 숨 가쁨'}
{'summary': '고혈압 환자인 할머니가 의식은 있으나 호흡 곤란을 호소하고 있으며, 혈압이 급격히 하락하고 있습니다.', '부위': '전신', '증상': '호흡곤란, 혈압하강(고혈압), 의식유지'}
{'summary': '직원이 요리 중 칼에 베어 심한 출혈이 있음', '부위': '손/손가락', '증상': '심한 출혈, 통증'}
{'summary': '형이 발을 헛디뎌 칼에 찔려 출혈이 있으며 움직임이 제한적입니다.', '부위': '발', '증상': '출혈, 움직임 어려움'}
{'summary': '계단에서 넘어져 다리가 부러짐', '부위': '다리', '증상': '움직이지 못함, 통증'}
{'summary': '오토바이와 차량의 충돌 사고 발생, 오토바이 운전자 다리 부상', '부위': '다리', '증상': '다리 불편'}
{'summary': '할머니 고객님이 얼굴, 특히 머리 쪽에서 심각한 출혈을 보이고 있습니다.', '부위': '머리', '증상': '심각한 출혈, 의식 있음'}
{'summary': '아내가 갑작스러운 심한 아랫배 통증과 허리 통증을 호소하며 구급차를 요청했습니다.', '부위': '아랫배, 허리', '증상': '갑작스러운 심한 통증'}
{'summary': '심장 통증, 호흡 곤란, 두통 발생. 코로나 백신 접종 이력 있음.', '부위': '심장', '증상': '심장 통증, 호흡 곤란, 두통'}
{'summary': '배 왼쪽, 대장 부근의 심한 통증과 함께 출혈 의심 증상 발생', '부위': '복부 (대장 부근)', '증상': '심한 통증, 출혈 의심, 발열 없음'}
{'summary': '어머니가 어지러움을 호소하며 움직임이 제한적입니다.', '부위': '전체', '증상': '어지러움, 움직임 장애'}
{'summary': "여성 고객이 운영하는 '요리왕 짬뽕 전문점'에서 손님이 갑자기 쓰러져 도움을 요청했습니다. 음식 섭취 중이었으며, 코로나 관련 증상 여부는 확실하지 않습니다.", '부위': '전신', '증상': '쓰러짐'}
{'summary': '여자분이 두산 아파트 옆 영광교회 근처에서 넘어져 오른쪽 다리를 심하게 다쳤습니다.', '부위': '오른쪽 다리', '증상': '심한 통증, 골절 의심'}
{'summary': '테이블 붕괴 사고 발생 중, 다수의 부상자 발생 가능성 있음', '부위': '전신 (구체적 부위 미상)', '증상': '다수 부상자 의심, 출혈 없음 보고'}
{'summary': '외국인 친구가 아침에 구토 후 발열(37.5도) 증상을 보임', '부위': '전체', '증상': '구토, 미열'}
{'summary': '여학생이 의식은 있으나 호흡이 빠르고 눈이 떨림 증상을 보임.', '부위': '전체', '증상': '빠른 호흡, 눈 떨림, 의식 있음'}
{'summary': '급성 허리 통증으로 인해 움직임이 제한됨', '부위': '허리', '증상': '급성 통증, 움직임 불가'}
{'summary': '25개월 아기 고열 (39도~39.5도) 지속', '부위': '전신', '증상': '고열, 대책 취하고 있음 (자세한 내용 미상)'}
{'summary': '폐암 환자로 호흡 곤란 증상 발생, 의식은 명료함', '부위': '전체', '증상': '호흡 곤란'}
{'summary': '배 통증으로 인해 이동이 어려움, 화장실 이용 어려움', '부위': '복부', '증상': '배 아픔, 이동 어려움'}
Error at index 199: Expecting property name enclosed in double quotes: line 1 column 87 (char 86)
{'summary': '갑작스러운 어지러움으로 인해 균형을 잃고 도움을 요청함', '부위': '전체', '증상': '어지러움, 균형 감각 상실'}
Error at index 201: JSON 데이터를 찾을 수 없습니다.
{'summary': '코로나 검사 결과 음성이지만, 수면 장애, 고열, 두통 증상 발생', '부위': '전체', '증상': '고열, 두통'}
{'summary': '남성이 건대 동문회관 앞에서 의식은 있으나 일어나지 못하는 상태로 쓰러졌습니다.', '부위': '전신', '증상': '의식 있음, 일어나지 못함'}
{'summary': '노인 여성이 의식을 잃고 구토 증상을 보임', '부위': '전신', '증상': '의식 소실, 구토'}
{'summary': '노인 여성이 화장실에서 넘어져 갈비뼈 부상을 입었습니다.', '부위': '갈비뼈', '증상': '심한 통증, 거동 불가'}
{'summary': '언니가 몸을 제대로 지탱하지 못하고 있으며, 우울증 약 복용 중으로 손의 움직임이 제한적입니다.', '부위': '전신', '증상': '균형 상실, 운동 기능 저하, 우울증 약 부작용 의심'}
{'summary': '급성 복통 호소, 코로나 감염 이력 없음', '부위': '복부', '증상': '급성 복통'}
{'summary': '어머니가 무릎 관절 수술 후 일어나다가 거동이 불가능해졌습니다.', '부위': '무릎', '증상': '거동 불가, 통증'}
{'summary': '위 통증, 발열', '부위': '위', '증상': '위통, 발열'}
{'summary': '등 통증으로 인해 어려움을 겪고 있으며, 의식과 호흡은 정상입니다.', '부위': '등', '증상': '등 통증'}
{'summary': '여성이 마로니 공원에서 넘어져 술에 취했으며, 안면에 경미한 출혈이 있음. 혼자 있음.', '부위': '안면', '증상': '넘어짐, 술취함, 경미한 출혈'}
{'summary': '집회 행진 중 차량과 충돌하여 다리 부상을 입은 환자가 있습니다.', '부위': '다리', '증상': '충돌 부상'}
{'summary': '딸이 위와 대장 출혈로 인한 지속적인 출혈로 어지러움증이 심하고, 이전에 수혈 권유를 받았으나 이행하지 못함', '부위': '위, 대장', '증상': '출혈, 어지러움증, 의식은 있으나 어지러움으로 인해 움직임 어려움'}
{'summary': '8개월 아기가 높은 곳에서 떨어져 울다가 그쳤으나 머리 부상 의심으로 응급 처치 필요', '부위': '머리', '증상': '떨어짐, 울음, 머리 부상 의심'}
{'summary': '와이프가 호흡곤란을 호소하며 움직이지 못하고 있음. 혈신증 병력 있음. 코로나 감염 의심 없음.', '부위': '전신', '증상': '호흡곤란, 움직임 제한'}

In [ ]:
response

['언니가 구토 증상을 보이고 있으며, 호흡에는 문제가 없음.',
 {'summary': '언니가 구토 증상을 보이고 있으며, 호흡에는 문제가 없음.', '부위': '위장', '증상': '구토'},
 {'summary': '갑작스러운 고혈압 상승, 말 어눌함, 추위 느낌, 약간의 의식 저하 의심',
  '부위': '전신',
  '증상': '고혈압 (177 이상), 말 어눌함, 추위 느낌, 의식 저하 의심'},
 {'summary': '성인 남녀가 갑자기 의식을 잃고 눈동자가 고정된 상태로 바닥에 쓰러졌으며, 호흡은 있으나 불규칙적일 가능성이 있음.',
  '부위': '전신',
  '증상': '의식 상실, 고정된 눈동자, 호흡 있음 (불규칙 가능성)'},
 {'summary': '집사람이 복부에서 탈장 증상을 보이고 있습니다.', '부위': '복부', '증상': '탈장'},
 {'summary': '할아버지가 집 안에서 쓰러져 움직이지 않고 있습니다.', '부위': '전신', '증상': '의식 불명, 무반응'},
 None,
 {'summary': '사망 의심되는 환자, 과거 며칠 전 사망 추정', '부위': '전신', '증상': '의식 상실, 호흡 없음'},
 {'summary': '남편이 계단에서 떨어져 발목 부상 의심, 다리 굽힘 증상 지속',
  '부위': '발목',
  '증상': '다리 굽힘, 통증'},
 {'summary': '남성 노인이 왼쪽 골반 골절로 쓰러졌으며, 코로나 관련 증상은 없음.',
  '부위': '왼쪽 골반',
  '증상': '골절, 쓰러짐'},
 {'summary': '아버지가 호흡곤란을 겪고 있으며, 현재 구급차가 도착한 상태입니다.',
  '부위': '전체',
  '증상': '호흡곤란'},
 {'summary': '아랫배 통증이 시작되어 점점 심해지고 있음', '부위': '아랫배', '증상': '지속적인 복통'},
 {'summary': '심한 복통 호소', '부위': '복부', '증상': '복통'},
 {'summary': '전신 통증으로 인해 거동이 불편한 상태, 의식은 있으나 명확한 의사소통 어려움',
  '부위': '전신',
  '증상': '전신 통증, 의사소통 어려움'},
 {'summary': '칼에 의한 찔림 사고 발생', '부위': '다리', '증상': '깊은 칼상, 출혈'},
 {'summary': 'HPV 백신 접종 후 전신 부종 및 발열 증상 발생', '부위': '전신', '증상': '부종, 발열'},
 {'summary': '백혈병 환자로, 최근 헤르페스 감염으로 인해 눈 시력 저하 및 두통 증상 발생, 서울대병원 응급실 이송 필요',
  '부위': '눈, 머리(두통)',
  '증상': '시력 저하, 두통, 헤르페스 감염'},
 {'summary': '직원이 식은땀을 흘리고 어지러움을 호소하며 청력 저하를 경험하고 있습니다. 코로나 증상은 없습니다.',
  '부위': '전체적 (특히 내이 또는 중추신경계 관련 가능성)',
  '증상': '어지러움, 청력 저하, 식은땀, 창백함'},
 {'summary': '남성 손님이 머리 통증을 호소하고 있으며, 다른 증상은 없다고 함.', '부위': '머리', '증상': '두통'},
 {'summary': '전화 통화 중인 사람이 건물 밖으로 나가는 데 어려움을 겪고 있으며, 힘이 없다고 표현함.',
  '부위': '전체적인 상태',
  '증상': '힘 없음, 이동 어려움'},
 {'summary': '취한 남성이 노원역 교보타워 뒤쪽 전주 콩나물 국밥 전문점 근처에 쓰러져 있으며, 의식이 흐릿하고 잠꼬대를 하고 있습니다.',
  '부위': '전신',
  '증상': '의식 불명확, 잠꼬대'},
 {'summary': '남성 직원이 명동의 매장에서 철문에 의해 손이 찢어지는 부상을 입었습니다.',
  '부위': '손',
  '증상': '찢어짐, 끼임'},
 {'summary': '심한 복통으로 인해 거동이 불가능한 상태', '부위': '복부', '증상': '심한 복통'},
 {'summary': '남성 환자가 가슴 통증을 호소하며, 프라이어 팰리스 아파트에 위치해 있습니다. 환자는 남편이며, 통증이 심하지만 걷는 것이 가능합니다.',
  '부위': '가슴',
  '증상': '가슴 통증, 걷기 가능'},
 {'summary': '오른쪽 옆구리 갑작스러운 통증', '부위': '오른쪽 옆구리', '증상': '갑작스러운 통증, 발열/기침 없음'},
 {'summary': '문에 부딪혀 머리에서 출혈 발생', '부위': '머리', '증상': '출혈'},
 {'summary': '89세 여성 환자, 갑작스러운 다리 부종 및 통증 호소, 의식과 호흡은 정상이나, 최근 코로나 관련 접촉자 정보는 없음',
  '부위': '다리',
  '증상': '심한 부종, 통증'},
 {'summary': '남자 환자가 계단에서 굴러 떨어져 의식은 있으나 호흡이 불규칙하고 현재 호흡이 불분명한 상태',
  '부위': '전신 (특히 머리와 척추)',
  '증상': '의식 있음, 호흡 불규칙, 호흡 곤란 의심'},
 {'summary': '어르신이 버스 안에서 쓰러져 일어나지 못하고 있으며, 다리 통증으로 인해 힘이 없음.',
  '부위': '다리',
  '증상': '의식 있음, 다리 힘 빠짐, 통증'},
 {'summary': '할아버지가 의식이 있는 상태로 연신교회 옆 세븐일레븐 건물 내부에 누워 계심',
  '부위': '전신',
  '증상': '의식 있음'},
 {'summary': '여자분이 무릎과 손을 경미하게 다쳤으며, 코로나 관련 증상이나 접촉자는 없음.',
  '부위': '무릎, 손',
  '증상': '경미한 외상'},
 {'summary': '아내분이 코로나 백신 접종 후 심한 통증과 고열을 호소하고 있습니다.',
  '부위': '전신',
  '증상': '통증, 고열'},
 {'summary': '호흡 곤란을 호소하며, 최근 코로나 관련 증상이나 의심 증상은 없다고 함',
  '부위': '전체',
  '증상': '호흡 곤란, 수면 장애'},
 {'summary': '할머니가 의식을 잃고 호흡은 하고 있지만 반응이 없는 상태입니다.',
  '부위': '전체',
  '증상': '의식 상실, 호흡 유지'},
 {'summary': '차에서 내린 후 의식을 잃고 앞으로 쓰러진 남성', '부위': '전신', '증상': '의식불명, 호흡가능성 있음'},
 {'summary': '허리 통증 호소, 최근 코로나 백신 접종 (22일)', '부위': '허리', '증상': '통증'},
 {'summary': '어머니가 감을 먹고 식중독 의심 증상을 보이며, 힘이 없어 일어나지 못하고 말도 제대로 하지 못하는 상태입니다.',
  '부위': '전신',
  '증상': '식중독 의심, 근력 약화, 발음 어려움'},
 {'summary': '아버지가 심한 복통과 식은땀, 흑변, 가벼운 두통을 호소하며 응급 상황을 요청하셨습니다.',
  '부위': '복부',
  '증상': '복통, 식은땀, 흑변, 두통'},
 {'summary': '딸이 심한 복통을 호소하고 있어 구급차를 요청했습니다.', '부위': '복부', '증상': '급성 복통'},
 {'summary': '코로나 확진 이력 있으며, 최근 예방 접종 완료. 과거 국내 접촉자 있었으나 격리 해제 후 일정 기간 경과.',
  '부위': '전체',
  '증상': '없음 (증상 언급 없음)'},
 {'summary': '어머니께서 오한, 추위, 몸살 증상을 보이고 있으며, 코로나 관련 증상은 없다고 합니다.',
  '부위': '전체적인 몸',
  '증상': '오한, 추위, 몸살'},
 {'summary': '응급 상황이 해소되었으나, 상태 변화에 주의 필요', '부위': '전체', '증상': '없음'},
 {'summary': '다리가 갑자기 움직여 고통을 호소하는 가족이 오성아파트 근처에서 발생',
  '부위': '다리',
  '증상': '갑작스러운 움직임, 통증'},
 {'summary': '어머니의 상태가 급격히 악화되어 응급 처치 필요성이 제기되고 있으나, 아버지의 거부로 인해 의료진의 개입이 어려움.',
  '부위': '전체적 (증상에 따른 특정 부위 미상)',
  '증상': '상태 악화, 의식 변화 의심'},
 {'summary': '고관절 통증으로 인해 이동 및 배변이 어려움',
  '부위': '고관절',
  '증상': '통증, 이동제한, 배변곤란, 발열 없음'},
 None,
 {'summary': '외상으로 인해 심각한 출혈이 발생한 것으로 보임',
  '부위': "전신 (특히 언급된 '꽉 찢어짐' 부위는 불명확)",
  '증상': '출혈, 의식은 있으나 위급 상황'},
 {'summary': '할아버지가 식사 중에 의식을 잃었다가 회복되었으나 다시 의식을 잃어가는 상태입니다.',
  '부위': '전체',
  '증상': '의식 소실, 간헐적 의식 회복'},
 {'summary': '집사람의 목 통증과 가슴 벌렁거림 호소', '부위': '목, 가슴', '증상': '목 통증, 가슴 벌렁거림'},
 {'summary': '노인 남성 환자, 혈전 증상 호소, 최근 코로나 증상 없음, 백신 접종 완료',
  '부위': '전신 (특히 뇌 관련 의심)',
  '증상': '혈전, 인지 기능 저하 의심'},
 {'summary': '사망 의심, 의식 없음', '부위': '전신', '증상': '의식 상실'},
 {'summary': '음주 상태의 여성 승객이 호흡 곤란을 호소하며 일어나지 못하고 누워있음',
  '부위': '전체',
  '증상': '호흡 곤란, 의식 저하'},
 {'summary': '뒤에서 오토바이에 의해 교통사고를 당한 운전자',
  '부위': '전신 가능성 있음 (구체적인 부위 미상)',
  '증상': '다치긴 했으나 구체적 증상 언급 없음, 구급차 요청'},
 {'summary': '길가에서 남녀 두 명이 쓰러져 일어나지 못하고 있는 응급 상황',
  '부위': '전신',
  '증상': '의식 불명, 움직임 불가'},
 {'summary': '의식 불명 상태의 노인이 누워있음. 의사소통 어려움. 원인 불명 (술 섭취 여부 불분명)',
  '부위': '전체',
  '증상': '의식 불명, 의사소통 불가'},
 {'summary': '갑작스러운 가슴 통증으로 인해 응급 상황 발생, 이전에 특정 진단을 받은 적 있음',
  '부위': '가슴',
  '증상': '갑작스러운 가슴 통증, 통증으로 인해 즉시 도움 요청'},
 {'summary': '환자는 호흡은 정상이지만, 일어나려는 의지가 있으며 머리에 약간의 열감을 호소하고 있습니다.',
  '부위': '머리',
  '증상': '두통, 열감 없음'},
 {'summary': '응급 상황 발생 중, 구체적인 증상 언급 없음', '부위': '정보 부족', '증상': '정보 부족'},
 {'summary': '어머니가 저녁 식사 후 어지러움과 저혈압 증상을 호소하며 병원 이송 필요 요청',
  '부위': '전체',
  '증상': '어지러움, 저혈압'},
 {'summary': '할아버지 호흡곤란, 의식 있음. 당뇨 및 심장질환 병력 있음. 현재 발열이나 기침은 없음.',
  '부위': '호흡기',
  '증상': '호흡곤란, 의식 명료, 당뇨, 심장질환 병력'},
 {'summary': '173차 접종 후 발열 지속 (39도 이상), 병원 이송 필요', '부위': '전신', '증상': '고열'},
 {'summary': '어르신이 심한 복통을 호소하고 있습니다.', '부위': '복부', '증상': '심한 복통'},
 {'summary': '남성 환자가 숨 쉬기 어려움을 호소하며 가슴 통증을 느끼고 있음. 최근 코로나 검사 이력 있으나 음성이었으나 증상이 악화됨.',
  '부위': '가슴',
  '증상': '호흡곤란, 가슴 통증'},
 None,
 {'summary': '술에 취한 남성이 추운 날씨에 독산역 1번 출구 근처 자판기 옆에 앉아 있는 상태입니다.',
  '부위': '전신 (전반적인 상태 확인 필요)',
  '증상': '술취함, 추위 노출'},
 {'summary': '자전거 사고로 쓰러진 환자, 의식 불명 상태',
  '부위': '전체적인 상태 (구체적인 부상 부위 미상)',
  '증상': '의식 불명, 움직임 불가, 호흡 상태 미상'},
 {'summary': 'HDC 건물 앞 도로에서 택시와 일반 차량 간 급성 교통사고 발생. 운전자는 의식이 있으나 목 통증으로 구급차 요청',
  '부위': '목',
  '증상': '목 통증'},
 {'summary': '얼굴 상처를 입은 남성 2명이 현장 이송을 요청했습니다.', '부위': '얼굴', '증상': '상처'},
 None,
 {'summary': '남성이 의식은 있으나 몸을 떨고, 배설물을 동반한 상태로 쓰러져 있음',
  '부위': '전신',
  '증상': '의식 있음, 떨림, 배설물 배출'},
 None,
 {'summary': '고속도로 주행 중 호흡곤란 증상 발생, 숨 쉬기 어려움', '부위': '전체', '증상': '호흡곤란, 숨 가쁨'},
 {'summary': '수면제 과다 복용 의심, 용산동 2가 거주',
  '부위': '전신',
  '증상': '과다 복용 관련 증상 (구체적 증상 언급 없음)'},
 {'summary': '환자는 몸을 움직일 수 없다고 호소하며, 여자친구가 동반하고 있으며 여자친구는 머리 부상을 입었다고 언급함.',
  '부위': '전신 (움직임 불가), 머리 (부상 의심)',
  '증상': '무력증, 머리 부상 의심'},
 {'summary': '오토바이 간 충돌 사고 발생, 두 명의 부상자 발생',
  '부위': '전신 (구체적인 부위 미상)',
  '증상': '의식 불명 (2분 동안), 이후 의식 회복'},
 {'summary': '버스 정류장에서 의식이 있지만 중증으로 보이는 남성이 떨어져 있는 상태였음.',
  '부위': '전신',
  '증상': '의식 있음, 중증 의심, 추위 노출'},
 {'summary': '손에 상처가 생겨 출혈이 심하며, 의식은 명료하고 다른 감염 증상은 없음.',
  '부위': '손',
  '증상': '출혈, 상처'},
 {'summary': '여자 두 명이 의식을 잃고 구토 증상을 보임. 남자 두 명은 의식이 있으며 호흡은 정상임. 외부 출혈은 확인되지 않음.',
  '부위': '전체적인 상태 (특정 부위 미상)',
  '증상': '의식 상실 (여성), 구토, 호흡 정상 (남성)'},
 {'summary': '화장실에서 넘어져 머리 부상 및 기타 부위 골절 의심, 의식은 있으나 기억 상실',
  '부위': '머리, 기타 부위 (구체적인 부위 미상)',
  '증상': '머리 붉어짐, 기억 상실'},
 {'summary': '71세 여성이 백신 3차 접종 후 고열(39도)을 보이고 있으며, 의식은 명료합니다.',
  '부위': '전신',
  '증상': '고열, 의식 명료'},
 {'summary': '의식 불명 상태, 항암 치료 중인 환자',
  '부위': '전신',
  '증상': '의식 없음, 의사소통 불가, 항암 치료 중'},
 {'summary': '3차 백신 접종 후 오한, 추위 느낌, 몸살 증상으로 거동이 어려움',
  '부위': '전체적인 몸',
  '증상': '오한, 추위 느낌, 몸살'},
 {'summary': '신장 기능 저하로 인한 심각한 증상으로 고대 구로병원 이송 필요',
  '부위': '전신 (특히 신장)',
  '증상': '신장 기능 저하, 의식 저하 (30점 미만)'},
 {'summary': '입장 통증으로 인해 거동이 불편한 상태', '부위': '입장', '증상': '통증, 거동 불편'},
 {'summary': '33세 남성이 어지러워 의식을 잃은 상태로 강남 터미널에서 여수로 이동하던 중 증상이 시작되었다.',
  '부위': '전체적인 증상 (특히 중추신경계 관련)',
  '증상': '어지러움, 의식 불명, 취한 상태 후 발생'},
 {'summary': '6살 아이가 내장증으로 응급 상황에 처해 있으며, 현재 호흡 중이지만 어려움을 겪고 있음.',
  '부위': '내장 (구체적인 부위 미상)',
  '증상': '내장증, 호흡 곤란'},
 None,
 {'summary': '아이가 아프고 호흡에 어려움을 겪고 있어 응급 상황으로 보입니다.',
  '부위': '전반적 (특히 호흡 관련)',
  '증상': '호흡곤란, 아동의 통증 호소'},
 {'summary': '응급 상황으로 인해 식사와 약 복용이 불가능하며, 응급실 방문 필요.',
  '부위': '전체적인 상태 (구체적인 부위 미상)',
  '증상': '통증, 식사/약 복용 불가'},
 {'summary': '술을 마신 여성이 호흡곤란을 호소하며 낑낑거리는 모습을 보임. 최근 코로나 감염 이력 있음 (자가격리 완료).',
  '부위': '전신',
  '증상': '호흡곤란, 낑낑거림, 의식은 있으나 호흡 곤란으로 어려움'},
 {'summary': '아기가 알레르기 반응으로 인해 증상이 악화되었으며, 발진과 발열이 동반됨',
  '부위': '전신 (특히 피부)',
  '증상': '알레르기 반응, 피부 발진, 발열 (38도~40도)'},
 {'summary': '시아버님의 정확한 증상은 알려지지 않았으나, 며칠 전 건강검진 후 몸이 좋지 않다고 한다.',
  '부위': '전체',
  '증상': '전반적인 불쾌감, 건강검진 후 악화'},
 {'summary': '22세 여성이 몸살 증상으로 병원에서 처방받은 약을 복용 후 갑작스러운 통증과 운동실 방문 권유를 받았으나 현재 발열은 없는 상태입니다.',
  '부위': '전체적인 몸살 증상',
  '증상': '갑작스러운 통증, 몸살'},
 {'summary': '남자 친구가 갑자기 넘어져 의식이 흐릿하고 귀 통증을 호소하며 코로나 증상과 유사한 두통을 느끼고 있습니다.',
  '부위': '머리, 귀',
  '증상': '의식 저하, 귀 통증, 두통'},
 {'summary': '아저씨가 일주일 동안 식사를 하지 않아 영양 상태가 우려되며, 현재 가까운 응급실 접근성에 대한 정보를 찾고 있음',
  '부위': '전신',
  '증상': '식욕부진, 영양실조 의심'},
 {'summary': '아내분이 초밥 섭취 후 심한 통증을 호소하며 탈진 상태로 쓰러져 있습니다.',
  '부위': '전신',
  '증상': '심한 통증, 탈진, 의식은 있으나 움직임 불가'},
 {'summary': '응급 상황 발생, 구체적인 부상 내용은 불명확, 빠른 출동 요청', '부위': '불명', '증상': '부상 의심'},
 {'summary': '소주병으로 인해 머리 부상을 입은 여성 환자 발생, 의식은 있으나 출혈이 심함',
  '부위': '머리',
  '증상': '출혈, 의식 있음'},
 None,
 {'summary': '고객이 구토 중이며 기력이 약해 움직이기 어려움. 의식은 있음. 코로나 감염 여부는 아님.',
  '부위': '전체',
  '증상': '구토, 기력 저하'},
 {'summary': '아저씨가 감기 후 의식은 있지만 혼란스러워하며 폭력적인 행동을 보이고 있으며, 식욕 부진과 변비 증상을 보임.',
  '부위': '전신',
  '증상': '혼란, 폭력성 행동, 식욕 부진, 변비'},
 {'summary': '남편이 호흡 중단 및 의식 상실 상태', '부위': '전체', '증상': '호흡 중단, 의식 상실'},
 {'summary': '다리 부상으로 인한 통증 호소', '부위': '다리', '증상': '통증, 걸림'},
 {'summary': '어머님이 의식이 없고, 현재 입으로 숨을 쉬고 있지만 숨이 약간 거칠다. 과거 발열 증상이 있었으나 현재는 호전 중이다. 가족 중 코로나 확진자는 없다.',
  '부위': '전체적인 상태 (의식, 호흡)',
  '증상': '의식 저하, 거친 호흡, 과거 발열'},
 {'summary': '8개월 여아, 목에 이물질 걸려 숨 쉬기 어려움, 현재 호흡 곤란 상태',
  '부위': '목',
  '증상': '이물질 걸림, 호흡 곤란, 입 오물거림'},
 {'summary': '노숙자가 서울역 파출소 지하도(우체국 쪽)에서 넘어져 눈을 크게 다쳐 칠상 상태입니다.',
  '부위': '눈',
  '증상': '칠상, 붓기'},
 {'summary': '쓰러짐', '부위': '전체', '증상': '쓰러짐, 어지러움 가능성'},
 {'summary': '심한 가슴 통증, 심장 부위 통증으로 인해 수업 참석 불가',
  '부위': '심장',
  '증상': '심한 가슴 통증, 호흡 곤란 가능성'},
 {'summary': '배 통증으로 인해 거동이 불편한 상태', '부위': '복부', '증상': '심한 복통'},
 {'summary': '할아버지가 사우나 남탕에서 의식 저하 상태로 쓰러졌으며, 호흡은 있으나 말을 제대로 하지 못함.',
  '부위': '전신',
  '증상': '의식 저하, 호흡 있음, 의사소통 어려움'},
 {'summary': '딸이 갑자기 심한 통증을 호소하며 걷지 못하고 있음. 의식은 있음.',
  '부위': '전신 (구체적인 부위 미상)',
  '증상': '통증, 보행곤란'},
 {'summary': '어지럼증 호소, 열 없음', '부위': '전체', '증상': '어지러움'},
 {'summary': '가스 팽창감, 손발 저림, 가벼운 호흡 곤란 의심',
  '부위': '전신',
  '증상': '가스 팽만감, 손발 저림, 호흡 곤란 의심, 코로나 증상 없음'},
 {'summary': '생후 2개월 아기가 코로나 확진 후 발열(38.5도), 처지는 증상을 보임. 의식은 있으나 잠을 자고 있음. 호흡은 정상적임.',
  '부위': '전신',
  '증상': '발열, 처짐, 의식 있음'},
 {'summary': '폐암 환자로 상태 악화, 호흡 곤란 및 의식 저하 증상 보임',
  '부위': '전반적 (특히 호흡 관련)',
  '증상': '호흡곤란, 의식 저하, 말하기 어려움, 눈 깜빡임 감소'},
 {'summary': '심정지 환자 발생, 위치 확인 중', '부위': '전체', '증상': '심정지'},
 None,
 {'summary': '다리 부상으로 인해 이동이 불가능한 상태', '부위': '다리', '증상': '다리 통증, 이동 불가'},
 {'summary': '자전거에서 넘어져 구토 증상을 보임',
  '부위': '전신 (구체적인 부상 부위 미상)',
  '증상': '구토, 의식 있음'},
 {'summary': '락스 섭취로 인한 중독 의심', '부위': '전신', '증상': '의식 있음, 락스 섭취 (반컵 정도)'},
 None,
 {'summary': '저혈당으로 인한 의식 저하 및 호흡 곤란 의심',
  '부위': '전신',
  '증상': '저체온, 무반응 (깨우기 어려움), 호흡 곤란 (기식적 호흡), 침 흘림, 식은 땀'},
 {'summary': '심장 질환자(페이스메이커 삽입)인 환자가 가슴 통증을 호소하며 응급실 방문 필요성을 언급함',
  '부위': '가슴',
  '증상': '가슴 통증 (조임, 압박감)'},
 {'summary': '치매 환자 어머니가 수면 장애와 식사 거부로 인해 영양 상태가 악화되고 있으며, 응급실 치료 필요성 문의',
  '부위': '전신',
  '증상': '수면 장애, 식사 거부, 기력 저하, 잠재적 저혈당 위험'},
 {'summary': '임산부가 허리 통증을 호소하며 응급실 방문 요청', '부위': '허리', '증상': '심한 통증'},
 {'summary': '83세 남성이 옥산빌라에서 미끄러져 넘어지며 머리와 가슴을 다쳤습니다. 현재 의식은 있지만 가슴 전체에 통증을 호소하고 있습니다. 호흡은 정상입니다.',
  '부위': '머리, 가슴',
  '증상': '넘어짐, 머리 부딪힘, 가슴 통증'},
 {'summary': '언니가 항문으로 하혈(혈변)을 하고 있으며, 다리 골절과 함께 혈압이 떨어지고 있습니다.',
  '부위': '항문, 다리',
  '증상': '하혈(혈변), 골절, 저혈압'},
 {'summary': '방해물(소액) 의심으로 인한 응급 상황, 이동 제한 가능성',
  '부위': '전체',
  '증상': '이동 제한 (고급차 진입 어려움), 약간의 보행 가능'},
 {'summary': '어머니가 갑자기 움직임이 불가능해졌으며, 이전에는 식사와 보행이 어려웠으나 최근에는 기저귀 착용과 대소변 조절 문제가 발생했습니다.',
  '부위': '전신',
  '증상': '움직임 장애, 대소변 장애, 과거 식사 및 보행 어려움'},
 {'summary': '아버님이 넘어져서 현재 상태가 좋지 않음. 현장 주소는 화공로 31층임.',
  '부위': '전신',
  '증상': '넘어짐, 상태 악화'},
 {'summary': '여자분이 롯데캐슬 근처 롯데카페 플라자 앞에서 자동차에 치여 부상당했습니다.',
  '부위': '부위 명시되지 않음',
  '증상': '의식 있음'},
 {'summary': '여자친구가 샤워 중 넘어진 사고로 머리 뒤쪽에 출혈과 찢어짐이 발생, 의식 불명 상태',
  '부위': '머리 뒤쪽',
  '증상': '출혈, 머리 찢어짐, 의식 불명'},
 {'summary': '무릎 부상으로 인한 통증, 병원 방문 거부 중', '부위': '무릎', '증상': '통증'},
 {'summary': '68세 남성 환자가 고열로 인해 거동이 불편하여 응급실 방문이 필요함. 최근 감기 증상이 있으며, 2주 전 코로나 부스터샷 접종 후 발열 발생. 어제 코로나 PCR 검사 결과 음성 판정 받음.',
  '부위': '전체',
  '증상': '고열, 감기 증상'},
 {'summary': '집사람이 갑자기 다리에 쥐가 나서 움직임이 제한되고 통증을 호소함',
  '부위': '다리',
  '증상': '쥐, 움직임 제한, 통증'},
 {'summary': '아버님이 자택에서 의식을 잃은 상태입니다.', '부위': '전체', '증상': '의식 상실'},
 {'summary': '20세 남성이 경기 중 갑자기 의식을 잃고 호흡이 멈춘 응급 상황',
  '부위': '전체적인 상태 (의식 상실, 호흡 중단)',
  '증상': '의식 상실, 호흡 중단'},
 {'summary': '20개월 아기가 해외 약품 과다 복용 후 의식은 있으나 불안정한 상태',
  '부위': '전신',
  '증상': '약물 과다 복용'},
 {'summary': '할아버지가 과도한 음주로 인해 균형을 잃고 넘어지며 얼굴에 부상을 입었으며, 혼란스러운 상태로 이동 중입니다.',
  '부위': '얼굴',
  '증상': '부상, 혼란, 균형 감각 상실'},
 {'summary': '어르신의 의식이 불안정하고, 식사 및 약 복용이 불가능하며, 통증 자극에 반응하지 않음.',
  '부위': '전신',
  '증상': '의식혼란, 식욕부진, 수분 섭취 불가, 통증 무반응'},
 {'summary': '여성 환자가 어지러움을 호소하며 의식은 있는 상태입니다.', '부위': '전체', '증상': '어지러움'},
 {'summary': '배 아픔으로 인한 응급 상황', '부위': '복부', '증상': '배 아픔'},
 {'summary': '오토바이 사고 발생, 운전자 의식불명 상태', '부위': '없음 (전체적인 사고 상황)', '증상': '의식불명'},
 {'summary': '지병이 있는 환자가 갑자기 악화되어 구급차로 이송 필요',
  '부위': '전체',
  '증상': '지병 악화, 의식 있음, 기침, 발열 (코로나 관련 증상 없음)'},
 {'summary': '환자는 거동이 불편한 상태로, 중앙대 병원 응급실 입원이 불가능하여 다른 병원으로 이송 필요. 주요 증상은 장기간 식사 부족으로 인한 기력 저하.',
  '부위': '전신',
  '증상': '기력 저하, 장기간 식사 부족'},
 {'summary': '호흡 곤란 호소, 종종 발생했으나 오늘 더 심해짐',
  '부위': '호흡기',
  '증상': '호흡 곤란, 말하기 어려움'},
 {'summary': '왼쪽 발목 부상으로 걷기 어려움, 계단에서 굴러 넘어짐',
  '부위': '왼쪽 발목',
  '증상': '통증, 보행 불가'},
 {'summary': '와이프가 허리 통증으로 인해 움직임이 제한되어 병원 이송 필요',
  '부위': '허리',
  '증상': '움직임 제한, 통증'},
 {'summary': '심폐소생 필요 의심, 의식불명, 호흡정지', '부위': '전신', '증상': '호흡정지, 의식불명'},
 {'summary': '코로나 확진자로 자가 치료 중인 분의 상태가 악화되어 혈압 상승과 가슴 통증이 발생했습니다. 보건소와의 연락이 원활하지 않은 상황입니다.',
  '부위': '가슴',
  '증상': '혈압 상승, 가슴 통증'},
 {'summary': '의식 불명 상태로, 일어날 수 없으며 호흡은 있음', '부위': '전체', '증상': '의식 불명, 호흡 있음'},
 {'summary': '오른쪽 다리 통증 지속, 응급실 방문 후 차도 없음, 보행 어려움',
  '부위': '오른쪽 다리',
  '증상': '통증, 보행곤란'},
 {'summary': '암 환자로 유방암 치료 중이던 여성이 갑자기 다리에 마비 증상이 발생하여 응급실 이송 요청',
  '부위': '다리',
  '증상': '다리 마비, 의식 있음'},
 {'summary': '술 취한 사람이 계속 소란을 피우고 있으며, 이전에 출동했던 인원이 다시 필요함.',
  '부위': '전신',
  '증상': '소란, 음주'},
 {'summary': '9살 남자아이가 왼손 손에 상처로 인한 출혈이 있음.', '부위': '왼손 손', '증상': '출혈, 상처'},
 {'summary': '마루에서 넘어져 거동이 불편하며, 통증을 느끼지 못하는 상태',
  '부위': '엉덩이',
  '증상': '움직임 제한, 통증 무감각'},
 {'summary': '술을 섭취한 후 저혈압 의심, 혼란스러움 표현',
  '부위': '전체적',
  '증상': '저혈압 의심, 혼란, 의사소통 어려움'},
 {'summary': '어지럼증, 구토감, 땀 흘림, 쓰러질 것 같은 느낌 호소',
  '부위': '전체',
  '증상': '어지럼증, 구토, 땀 과다, 현기증'},
 {'summary': '갑작스러운 어지러움과 통증 호소, 코로나 증상 없음', '부위': '전체', '증상': '어지러움, 통증'},
 None,
 {'summary': '호흡 중단, 의식 없음', '부위': '전체', '증상': '호흡정지, 무반응'},
 {'summary': '자전거 사고로 인해 의식은 있으나 일어나지 못하는 노인 남성이 양계천 산책로에 떨어져 있습니다.',
  '부위': '전신 부상 의심 (구체적 부위 미상)',
  '증상': '의식 있음, 일어나지 못함'},
 {'summary': '아이가 허리 통증을 호소하며 응급 상황으로 연락', '부위': '허리', '증상': '통증'},
 {'summary': '한쪽 다리 괴사 및 통증으로 응급 상황, 병원비 부담으로 치료 지연 중',
  '부위': '양쪽 다리',
  '증상': '괴사, 통증, 의식 혼미'},
 {'summary': '아버지가 허리 통증으로 인해 침대에서 움직이지 못하고 소변 조절에 어려움을 겪고 있습니다. 최근 병원 진료를 받았으나 호전되지 않았으며, 발열이나 기침 등의 코로나 증상은 없습니다.',
  '부위': '허리',
  '증상': '움직임 제한, 소변 실금'},
 {'summary': '전신 통증, 식욕부진 5일간 지속, 코로나 확진으로 재택치료 중',
  '부위': '전신',
  '증상': '전신 통증, 식욕부진, 코로나 확진'},
 {'summary': '구급차 도착 예정, 격리 중인 사람들에게 발열이나 기침 등의 증상은 없음. 보건소 연락 필요, 병원 선정 문의 중',
  '부위': '전체',
  '증상': '발열, 기침: 없음'},
 {'summary': '환자는 성격병으로 인해 원래 월요일까지 수술이 불가능했으나, 상황 변화로 인해 서울 프라임 병원으로 응급 이송 필요. 사설 구급차 이용 권장.',
  '부위': '전체적인 상태 언급 없음',
  '증상': '성격병 관련 증상, 응급 수술 필요성'},
 {'summary': '어머니가 심한 복통을 호소하고 있습니다.', '부위': '복부', '증상': '급성 복통'},
 {'summary': '지속적인 호흡 곤란으로 응급실 방문 필요, 진정제 투여 필요성 언급',
  '부위': '전체',
  '증상': '호흡 곤란, 진정 필요'},
 {'summary': '움직이지 못하고 누워있는 상태, 호흡 곤란 및 가래 끓는 소리',
  '부위': '전신',
  '증상': '호흡곤란, 가래 끓는 소리, 식욕부진, 의식 저하'},
 {'summary': '할아버지가 쓰러져 있으며 움직임이 있고 눈을 뜨고 있지만 얼굴에 피가 묻어있다는 보고가 있었으나 확인되지 않았습니다.',
  '부위': '전신',
  '증상': '의식 있음, 움직임 있음, 출혈 의심 (확인 필요)'},
 None,
 {'summary': "본인은 눈 통증을 호소하며, 동생의 상태는 현재 경미하며, 주소 확인 중 어려움을 겪고 있음. 주소는 '금호산 2길'로 언급되나 정확한 위치 파악이 어려움. 거주지는 지하임.",
  '부위': '눈',
  '증상': ['눈 통증', '기억 상실 (동생 관련)']},
 {'summary': '아파트 근처 사거리에 위치한 화장실 내에서 노인 여성이 의식은 있으나 몸을 움직이지 못하고 있는 상태입니다.',
  '부위': '전신 (특히 하체)',
  '증상': '의식 있음, 운동 불능, 추운 환경'},
 {'summary': '위통과 구토 증상으로 인해 병원 방문 필요', '부위': '위', '증상': '위통, 구토 (7회), 전신 통증'},
 {'summary': '소주병 관련 싸움으로 인한 응급상황, 다수의 부상자 발생 가능성',
  '부위': '전신 (구체적인 부위 미상)',
  '증상': '부상, 혼란'},
 {'summary': '70대 여성 환자, 어지럼증으로 걷기 어려움, 응급 상황으로 병원 이송 필요',
  '부위': '전체',
  '증상': '어지럼증, 보행 불가'},
 None,
 {'summary': '쥐가 나온 후 사람이 갑자기 아프다고 호소', '부위': '전체적', '증상': '발작, 기가 찬 느낌'},
 {'summary': '98세 여성 환자가 숨이 차서 호흡곤란을 호소하고 있습니다.',
  '부위': '전체',
  '증상': '호흡곤란, 숨 가쁨'},
 {'summary': '고혈압 환자인 할머니가 의식은 있으나 호흡 곤란을 호소하고 있으며, 혈압이 급격히 하락하고 있습니다.',
  '부위': '전신',
  '증상': '호흡곤란, 혈압하강(고혈압), 의식유지'},
 {'summary': '직원이 요리 중 칼에 베어 심한 출혈이 있음', '부위': '손/손가락', '증상': '심한 출혈, 통증'},
 {'summary': '형이 발을 헛디뎌 칼에 찔려 출혈이 있으며 움직임이 제한적입니다.',
  '부위': '발',
  '증상': '출혈, 움직임 어려움'},
 {'summary': '계단에서 넘어져 다리가 부러짐', '부위': '다리', '증상': '움직이지 못함, 통증'},
 {'summary': '오토바이와 차량의 충돌 사고 발생, 오토바이 운전자 다리 부상', '부위': '다리', '증상': '다리 불편'},
 {'summary': '할머니 고객님이 얼굴, 특히 머리 쪽에서 심각한 출혈을 보이고 있습니다.',
  '부위': '머리',
  '증상': '심각한 출혈, 의식 있음'},
 {'summary': '아내가 갑작스러운 심한 아랫배 통증과 허리 통증을 호소하며 구급차를 요청했습니다.',
  '부위': '아랫배, 허리',
  '증상': '갑작스러운 심한 통증'},
 {'summary': '심장 통증, 호흡 곤란, 두통 발생. 코로나 백신 접종 이력 있음.',
  '부위': '심장',
  '증상': '심장 통증, 호흡 곤란, 두통'},
 {'summary': '배 왼쪽, 대장 부근의 심한 통증과 함께 출혈 의심 증상 발생',
  '부위': '복부 (대장 부근)',
  '증상': '심한 통증, 출혈 의심, 발열 없음'},
 {'summary': '어머니가 어지러움을 호소하며 움직임이 제한적입니다.', '부위': '전체', '증상': '어지러움, 움직임 장애'},
 {'summary': "여성 고객이 운영하는 '요리왕 짬뽕 전문점'에서 손님이 갑자기 쓰러져 도움을 요청했습니다. 음식 섭취 중이었으며, 코로나 관련 증상 여부는 확실하지 않습니다.",
  '부위': '전신',
  '증상': '쓰러짐'},
 {'summary': '여자분이 두산 아파트 옆 영광교회 근처에서 넘어져 오른쪽 다리를 심하게 다쳤습니다.',
  '부위': '오른쪽 다리',
  '증상': '심한 통증, 골절 의심'},
 {'summary': '테이블 붕괴 사고 발생 중, 다수의 부상자 발생 가능성 있음',
  '부위': '전신 (구체적 부위 미상)',
  '증상': '다수 부상자 의심, 출혈 없음 보고'},
 {'summary': '외국인 친구가 아침에 구토 후 발열(37.5도) 증상을 보임', '부위': '전체', '증상': '구토, 미열'},
 {'summary': '여학생이 의식은 있으나 호흡이 빠르고 눈이 떨림 증상을 보임.',
  '부위': '전체',
  '증상': '빠른 호흡, 눈 떨림, 의식 있음'},
 {'summary': '급성 허리 통증으로 인해 움직임이 제한됨', '부위': '허리', '증상': '급성 통증, 움직임 불가'},
 {'summary': '25개월 아기 고열 (39도~39.5도) 지속',
  '부위': '전신',
  '증상': '고열, 대책 취하고 있음 (자세한 내용 미상)'},
 {'summary': '폐암 환자로 호흡 곤란 증상 발생, 의식은 명료함', '부위': '전체', '증상': '호흡 곤란'},
 {'summary': '배 통증으로 인해 이동이 어려움, 화장실 이용 어려움',
  '부위': '복부',
  '증상': '배 아픔, 이동 어려움'},
 None,
 {'summary': '갑작스러운 어지러움으로 인해 균형을 잃고 도움을 요청함',
  '부위': '전체',
  '증상': '어지러움, 균형 감각 상실'},
 None,
 {'summary': '코로나 검사 결과 음성이지만, 수면 장애, 고열, 두통 증상 발생',
  '부위': '전체',
  '증상': '고열, 두통'},
 {'summary': '남성이 건대 동문회관 앞에서 의식은 있으나 일어나지 못하는 상태로 쓰러졌습니다.',
  '부위': '전신',
  '증상': '의식 있음, 일어나지 못함'},
 {'summary': '노인 여성이 의식을 잃고 구토 증상을 보임', '부위': '전신', '증상': '의식 소실, 구토'},
 {'summary': '노인 여성이 화장실에서 넘어져 갈비뼈 부상을 입었습니다.',
  '부위': '갈비뼈',
  '증상': '심한 통증, 거동 불가'},
 {'summary': '언니가 몸을 제대로 지탱하지 못하고 있으며, 우울증 약 복용 중으로 손의 움직임이 제한적입니다.',
  '부위': '전신',
  '증상': '균형 상실, 운동 기능 저하, 우울증 약 부작용 의심'},
 {'summary': '급성 복통 호소, 코로나 감염 이력 없음', '부위': '복부', '증상': '급성 복통'},
 {'summary': '어머니가 무릎 관절 수술 후 일어나다가 거동이 불가능해졌습니다.',
  '부위': '무릎',
  '증상': '거동 불가, 통증'},
 {'summary': '위 통증, 발열', '부위': '위', '증상': '위통, 발열'},
 {'summary': '등 통증으로 인해 어려움을 겪고 있으며, 의식과 호흡은 정상입니다.', '부위': '등', '증상': '등 통증'},
 {'summary': '여성이 마로니 공원에서 넘어져 술에 취했으며, 안면에 경미한 출혈이 있음. 혼자 있음.',
  '부위': '안면',
  '증상': '넘어짐, 술취함, 경미한 출혈'},
 {'summary': '집회 행진 중 차량과 충돌하여 다리 부상을 입은 환자가 있습니다.',
  '부위': '다리',
  '증상': '충돌 부상'},
 {'summary': '딸이 위와 대장 출혈로 인한 지속적인 출혈로 어지러움증이 심하고, 이전에 수혈 권유를 받았으나 이행하지 못함',
  '부위': '위, 대장',
  '증상': '출혈, 어지러움증, 의식은 있으나 어지러움으로 인해 움직임 어려움'},
 {'summary': '8개월 아기가 높은 곳에서 떨어져 울다가 그쳤으나 머리 부상 의심으로 응급 처치 필요',
  '부위': '머리',

In [ ]:
response_df = pd.DataFrame({'summary':response})
response_df

                                               summary
0                     언니가 구토 증상을 보이고 있으며, 호흡에는 문제가 없음.
1    {'summary': '언니가 구토 증상을 보이고 있으며, 호흡에는 문제가 없음.'...
2    {'summary': '갑작스러운 고혈압 상승, 말 어눌함, 추위 느낌, 약간의 의...
3    {'summary': '성인 남녀가 갑자기 의식을 잃고 눈동자가 고정된 상태로 바닥...
4    {'summary': '집사람이 복부에서 탈장 증상을 보이고 있습니다.', '부위'...
..                                                 ...
825  {'summary': '급체로 인한 복통 호소, 의식과 호흡 유지 중', '부위':...
826  {'summary': '백신 접종 후 아이가 근육통을 호소하고 있으며, 현재 증상이...
827  {'summary': '노인이 농협 정문 근처에서 넘어져 일어나지 못함', '부위'...
828  {'summary': '아버지가 갑작스러운 오한, 발열, 두드러기 증상을 보이고 있...
829  {'summary': '엄지 손바닥에 칼에 의한 깊은 상처, 출혈 있음', '부위'...

[830 rows x 1 columns]

In [ ]:
response_df.to_csv("whisper-3_EXAONE_response.csv")

In [ ]:
label_class = pd.read_csv('/content/drive/MyDrive/KT_aivle/미니프로젝트/2024.11.18_미니프로젝트_6차_4일차_실습자료/2024.11.19_미니프로젝트 6차_5일차 실습자료/중증도 카테고리.csv', encoding='euc-kr')
label_class

       구분1      구분2                 구분3 등급
0     물질오용  물질오용/중독             중증 호흡곤란  1
1     물질오용  물질오용/중독                  쇼크  1
2     물질오용  물질오용/중독        무의식(GCS 3-8)  1
3     물질오용  물질오용/중독            중등도 호흡곤란  2
4     물질오용  물질오용/중독             혈역학적 장애  2
...    ...      ...                 ... ..
2024    일반    경증 호소  만성 말초성 중증 통증(8-10)  4
2025    일반    경증 호소    만성 중심성 경증 통증(<4)  5
2026    일반    경증 호소    급성 말초성 경증 통증(<4)  5
2027    일반    경증 호소       만성 말초성 통증(<8)  5
2028    일반    경증 호소       경증 증상호소, 비특이적  5

[2029 rows x 4 columns]

In [ ]:
label_class = label_class.fillna("")

In [ ]:
# 등급 매기기 함수 정의
def assign_grade(response, label_class):
    response_symptoms = response['증상'].split(', ')
    # 등급 초기화
    assigned_grade = None

    # 각 증상에 대해 label_class에서 매칭된 등급 찾기
    for symptom in response_symptoms:
        matched_rows = label_class[label_class['구분3'].str.contains(symptom, na=False)]
        if not matched_rows.empty:
            # 현재까지 할당된 등급과 매칭된 등급 중 더 낮은 등급 선택
            grade = matched_rows['등급'].min()
            if assigned_grade is None or grade < assigned_grade:
                assigned_grade = grade

    # 등급이 없는 경우 '등급 없음'으로 설정
    response['등급'] = assigned_grade if assigned_grade is not None else '등급 없음'
    return response

# 분류 함수 정의
def classify_response(response_data, label_class):
    data_f = []
    for i in range(len(response_df)):
        # ai를 사용하여 응급 상황 요약 생성
        AI_response = text_summary(response_df['summary'][i])
        # 생성된 응답을 바탕으로 등급 매기기
        response_with_grade = assign_grade(AI_response, label_class)
        data_f.append(response_with_grade)

    # 데이터프레임으로 변환 및 저장
    data_df = pd.DataFrame(data_f)
    return data_df

response_data = response.copy()

# 분류 수행 및 결과 저장
classified_data = classify_response(response_df, label_class)
print(classified_data)

TypeError: can only concatenate str (not "dict") to str

### (2) 전국 병원 응급실 정보 수집

#### 데이터 수집

In [ ]:
# path 확인
path

'/content/drive/MyDrive/KT_aivle/미니프로젝트/2024.11.18_미니프로젝트_6차_4일차_실습자료/'

In [ ]:
# 응급실 데이터 수집하기
# 응급실 목록정보 조회

url = 'http://apis.data.go.kr/B552657/ErmctInfoInqireService/getEgytListInfoInqire'
serviceKey = ''    # 여러분의 일반 인증키(Decoding)

params = {
    'serviceKey': serviceKey,
    'pageNo': '1', 'numOfRows': '1000',  # 전체 응급실 수가 500여개 됨. 1000개면 충분
    'format': 'xml'
}

response = requests.get(url, params = params)

# 정상 수행 되었다면 200
print(response)

<Response [200]>

In [ ]:
# response xml에서 주요 정보 찾기
root = ET.fromstring(response.text)

data = []

for item in root. findall('.//item'):
    duty_name = item.findtext('dutyName') #기관명
    duty_addr = item.findtext('dutyAddr') #주소
    # 필요한 정보 추가
    latitude = item.findtext('wgs84Lat')
    longitude = item.findtext('wgs84Lon')

    # 빈 리스트 data에 딕시너리 형태({'칼럼이름':값, ...})로 저장(추가)
    data.append({'기관명' : duty_name, '기관주소': duty_addr, '위도' : latitude, '경도': longitude})

# 데이터프레임으로 변환
df_basic =  pd.DataFrame(data)

In [ ]:
df_basic

,기관명,기관주소,위도,경도
0,(의)내경의료재단울산제일병원,울산광역시 남구 남산로354번길 26 (신정동),35.54823820112527,129.30701143429678
1,(의)서일의료재단기장병원,부산광역시 기장군 기장읍 대청로72번길 6,35.23602946449906,129.21649161387128
2,(의)성세의료재단 뉴성민병원,"인천광역시 서구 칠천왕로33번길 17 (석남동, 신석로 70(석남1동, 성민병원))",37.5089936801167,126.669478649026
3,(의)영문의료재단다보스병원,"경기도 용인시 처인구 백옥대로1082번길 18, 다보스종합병원 (김량장동)",37.234641294534285,127.21049868474802
4,(의)효심의료재단용인서울병원,경기도 용인시 처인구 고림로 81 (고림동),37.240316373,127.2144914405
...,...,...,...,...
521,효산의료재단안양샘병원,"경기도 안양시 만안구 삼덕로 9 (안양동, 안양샘병원)",37.39340413136221,126.92447734066778
522,효산의료재단지샘병원,"경기도 군포시 군포로 591 (당동, (G샘병원)군포샘병원)",37.35864464913468,126.94735972779895
523,효성시티병원,부산광역시 해운대구 해운대로 135 (재송동),35.18541271514478,129.12145899191526
524,흑룡의원,인천광역시 옹진군 백령면 백령로 831,37.959524356,124.6654985764
525,희명병원,서울특별시 금천구 시흥대로 244 (시흥동),37.45567063464179,126.90056251863875

In [ ]:
!pip install geopy

In [ ]:
from geopy.geocoders import Nominatim
import time

In [ ]:
geolocator = Nominatim(user_agent='chiricuto')

# 주소에서 위도와 경도를 찾는 함수
def get_coordinates(address):
    try:
        simple_address = address.split(",")[0].split("(")[0] # 주소에서 상세한 부분을 제거하여 더 단순화
        location = geolocator.geocode(simple_address)
        if location is not None:
            return location.latitude, location.longitude
        else:
            print(f"주소를 찾을 수 없습니다: {address}")
            return None, None
    except Exception as e:
        print(f"오류 발생: {e}, 주소: {address}")
        return None, None

# 데이터프레임에 위도와 경도 추가
for i, row in df_basic.iterrows():
    latitude, longitude = get_coordinates(row['기관주소'])
    df_basic.loc[i, '위도'] = latitude
    df_basic.loc[i, '경도'] = longitude
    time.sleep(1)

# 결과 출력
print(df_basic)

주소를 찾을 수 없습니다: 경기도 용인시 처인구 백옥대로1082번길 18, 다보스종합병원 (김량장동)

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=%EA%B2%BD%EC%83%81%EB%82%A8%EB%8F%84+%EA%B1%B0%EC%B0%BD%EA%B5%B0+%EA%B1%B0%EC%B0%BD%EC%9D%8D+%EC%A4%91%EC%95%99%EB%A1%9C+91&format=json&limit=1

주소를 찾을 수 없습니다: 경상북도 김천시 모암길 24 (모암동)

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=%EA%B2%BD%EC%83%81%EB%B6%81%EB%8F%84+%EC%95%88%EB%8F%99%EC%8B%9C+%ED%83%9C%EC%82%AC2%EA%B8%B8+55+&format=json&limit=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=%EA%B2%BD%EA%B8%B0%EB%8F%84+%EA%B4%91%EB%AA%85%EC%8B%9C+%EB%94%94%EC%A7%80%ED%84%B8%EB%A1%9C+36&format=json&limit=1

주소를 찾을 수 없습니다: 전라남도 구례군 구례읍 동편제길 4
주소를 찾을 수 없습니다: 전라남도 순천시 조례1길 24 (조례동)
주소를 찾을 수 없습니다: 전북특별자치도 김제시 서암4길 45 (서암동)
주소를 찾을 수 없습니다: 전라남도 보성군 미력면 가평길 36-17

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=%EA%B2%BD%EA%B8%B0%EB%8F%84+%EB%B6%80%EC%B2%9C%EC%8B%9C+%EC%98%A4%EC%A0%95%EA%B5%AC+%EC%86%8C%EC%82%AC%EB%A1%9C+726&format=json&limit=1

주소를 찾을 수 없습니다: 경기도 부천시 오정구 소사로 726, 지하4층~지상5층 (원종동)
주소를 찾을 수 없습니다: 경상북도 상주시 상서문로 53 (남성동)
주소를 찾을 수 없습니다: 경상남도 함안군 칠원읍 용산2길 45-13

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=%EA%B2%BD%EA%B8%B0%EB%8F%84+%EA%B0%80%ED%8F%89%EA%B5%B0+%EC%84%A4%EC%95%85%EB%A9%B4+%EB%AF%B8%EC%82%AC%EB%A6%AC%EB%A1%9C+267-177&format=json&limit=1

주소를 찾을 수 없습니다: 경기도 가평군 설악면 미사리로 267-177

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=%EC%A0%84%EB%9D%BC%EB%82%A8%EB%8F%84+%EC%97%AC%EC%88%98%EC%8B%9C+%EB%AC%B4%EC%84%A0%EB%A1%9C+95+&format=json&limit=1

주소를 찾을 수 없습니다: 전라남도 영암군 영암읍 오리정길 8
주소를 찾을 수 없습니다: 충청남도 예산군 예산읍 신례원로 26
주소를 찾을 수 없습니다: 경상북도 김천시 신음1길 12 (신음동)
주소를 찾을 수 없습니다: 전라남도 보성군 벌교읍 남하로 12
주소를 찾을 수 없습니다: 전라남도 신안군 비금면 송치길 155-11
주소를 찾을 수 없습니다: 충청북도 음성군 금왕읍 음성로1230번길 10
주소를 찾을 수 없습니다: 전라남도 순천시 우명길 42 (연향동)

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=%EC%A0%84%EB%9D%BC%EB%82%A8%EB%8F%84+%EC%97%AC%EC%88%98%EC%8B%9C+%EC%8C%8D%EB%B4%89%EB%A1%9C+70+&format=json&limit=1

주소를 찾을 수 없습니다: 전라남도 장성군 장성읍 역전로 171
주소를 찾을 수 없습니다: 경상남도 창원시 의창구 용동로57번길 8 (사림동)
주소를 찾을 수 없습니다: 강원특별자치도 철원군 갈말읍 명성로 208-0
주소를 찾을 수 없습니다: 충청북도 청주시 서원구 1순환로 776-0 (개신동,충북대학교병원)

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=%EC%B6%A9%EC%B2%AD%EB%B6%81%EB%8F%84+%EC%B6%A9%EC%A3%BC%EC%8B%9C+%EA%B5%AD%EC%9B%90%EB%8C%80%EB%A1%9C+99-0&format=json&limit=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=%EC%B6%A9%EC%B2%AD%EB%B6%81%EB%8F%84+%EC%B6%A9%EC%A3%BC%EC%8B%9C+%EA%B5%AD%EC%9B%90%EB%8C%80%EB%A1%9C+99-0&format=json&limit=1

주소를 찾을 수 없습니다: 경상남도 창녕군 창녕읍 교리1길 2
주소를 찾을 수 없습니다: 경기도 파주시 탄현면 평화로574번길 17, (의)청학의료재단 파주성모병원.요양병원
주소를 찾을 수 없습니다: 광주광역시 광산구 용아로 259 하남성심병원 (산정동)
주소를 찾을 수 없습니다: 울산광역시 동구 대학병원로 25, 울산대학교병원 (전하동)
주소를 찾을 수 없습니다: 강원특별자치도 홍천군 홍천읍 산림공원1길 17
                 기관명                                            기관주소  \
0    (의)내경의료재단울산제일병원                      울산광역시 남구 남산로354번길 26 (신정동)
1      (의)서일의료재단기장병원                         부산광역시 기장군 기장읍 대청로72번길 6
2    (의)성세의료재단 뉴성민병원  인천광역시 서구 칠천왕로33번길 17 (석남동, 신석로 70(석남1동, 성민병원))
3     (의)영문의료재단다보스병원       경기도 용인시 처인구 백옥대로1082번길 18, 다보스종합병원 (김량장동)
4    (의)효심의료재단용인서울병원                        경기도 용인시 처인구 고림로 81 (고림동)
..               ...                                             ...
521      효산의료재단안양샘병원                  경기도 안양시 만안구 삼덕로 9 (안양동, 안양샘병원)
522       효산의료재단지샘병원               경기도 군포시 군포로 591 (당동, (G샘병원)군포샘병원)
523           효성시티병원                       부산광역시 해운대구 해운대로 135 (재송동)
524             흑룡의원                           인천광역시 옹진군 백령면 백령로 831
525             희명병원                        서울특별시 금천구 시흥대로 244 (시흥동)

            위도          경도
0    35.548538  129.305706
1    35.234664  129.215478
2    37.509355  126.671129
3          NaN         NaN
4    37.245068  127.218638
..         ...         ...
521  37.397804  126.915755
522  37.372789  126.942672
523  35.177160  129.186879
524  37.974239  124.694594
525  37.455674  126.900558

[526 rows x 4 columns]

In [ ]:
df_basic

,기관명,기관주소,위도,경도
0,(의)내경의료재단울산제일병원,울산광역시 남구 남산로354번길 26 (신정동),35.548538,129.305706
1,(의)서일의료재단기장병원,부산광역시 기장군 기장읍 대청로72번길 6,35.234664,129.215478
2,(의)성세의료재단 뉴성민병원,"인천광역시 서구 칠천왕로33번길 17 (석남동, 신석로 70(석남1동, 성민병원))",37.509355,126.671129
3,(의)영문의료재단다보스병원,"경기도 용인시 처인구 백옥대로1082번길 18, 다보스종합병원 (김량장동)",NaN,NaN
4,(의)효심의료재단용인서울병원,경기도 용인시 처인구 고림로 81 (고림동),37.245068,127.218638
...,...,...,...,...
521,효산의료재단안양샘병원,"경기도 안양시 만안구 삼덕로 9 (안양동, 안양샘병원)",37.397804,126.915755
522,효산의료재단지샘병원,"경기도 군포시 군포로 591 (당동, (G샘병원)군포샘병원)",37.372789,126.942672
523,효성시티병원,부산광역시 해운대구 해운대로 135 (재송동),35.177160,129.186879
524,흑룡의원,인천광역시 옹진군 백령면 백령로 831,37.974239,124.694594
525,희명병원,서울특별시 금천구 시흥대로 244 (시흥동),37.455674,126.900558

In [ ]:
# 응급실 데이터 수집하기
# 응급실 기본정보 조회

url = 'http://apis.data.go.kr/B552657/ErmctInfoInqireService/getEgytBassInfoInqire'
serviceKey = ''    # 여러분의 일반 인증키(Decoding)

params = {
    'serviceKey': serviceKey,
    'pageNo': '1', 'numOfRows': '1000',  # 전체 응급실 수가 500여개 됨. 1000개면 충분
    'format': 'xml'
}

response = requests.get(url, params = params)

# 정상 수행 되었다면 200
print(response)

<Response [200]>

In [ ]:
# response xml에서 주요 정보 찾기
root = ET.fromstring(response.text)

data = []

for item in root. findall('.//item'):
    duty_name = item.findtext('dutyName') #기관명
    duty_addr = item.findtext('dutyAddr') #주소
    # 필요한 정보 추가
    latitude = item.findtext('wgs84Lat')
    longitude = item.findtext('wgs84Lon')
    hvec = item.findtext('hvec')

    # 빈 리스트 data에 딕시너리 형태({'칼럼이름':값, ...})로 저장(추가)
    data.append({'기관명' : duty_name, '기관주소': duty_addr, '위도' : latitude, '경도': longitude, '응급실':hvec})

# 데이터프레임으로 변환
df_em =  pd.DataFrame(data)

In [ ]:
df_em

,기관명,기관주소,위도,경도,응급실
0,경희대학교병원,서울특별시 동대문구 경희대로 23 (회기동),37.5938765502235,127.05183223390303,16
1,건국대학교병원,서울특별시 광진구 능동로 120-1 (화양동),37.54084479467721,127.0721229093036,6
2,중앙대학교병원,서울특별시 동작구 흑석로 102 (흑석동),37.50707428493414,126.96079378447554,15
3,순천향대학교 부속 서울병원,서울특별시 용산구 대사관로 59 (한남동),37.53384172231443,127.00441798640304,20
4,이화여자대학교의과대학부속목동병원,서울특별시 양천구 안양천로 1071 (목동),37.53654282637804,126.8862159683056,30
...,...,...,...,...,...
995,수연세안과의원,"서울특별시 서초구 서초대로77길 54, 서초더블유타워 5, 6층 (서초동)",37.502506415764955,127.02484127797528,None
996,서초좋은의원,"서울특별시 서초구 서초중앙로 238, 306호 (반포동, 삼호가든상가)",37.5029619493601,127.012070984447,None
997,베스탑비뇨기과의원,"서울특별시 송파구 올림픽로 269, 2층 221호 (신천동, 롯데캐슬골드)",37.5144273491608,127.100611434725,None
998,연세이김마취통증의학과의원,서울특별시 송파구 송파대로30길 5 (가락동),37.4944808900047,127.118048260052,None
999,오렌지정형외과의원,서울특별시 송파구 마천로 271 (마천동),37.4978050655343,127.147108511955,None

In [ ]:
df_merged = pd.merge(df_basic, df_em, on=['기관명', '기관주소'], how='inner')
df_merged

,기관명,기관주소,위도,경도,응급실
0,가톨릭대학교여의도성모병원,"서울특별시 영등포구 63로 10, 여의도성모병원 (여의도동)",37.51827233800711,126.93673129599131,17
1,강남고려병원,서울특별시 관악구 관악로 242 (봉천동),37.4856188363947,126.956781703053,10
2,강남베드로병원,"서울특별시 강남구 남부순환로 2649, 베드로병원 (도곡동)",37.485612179925724,127.0395873429168,None
3,강남힐병원,"서울특별시 관악구 남부순환로 1449, 강남힐병원 (신림동)",37.4816513439454,126.911648078471,None
4,강동경희대학교의대병원,서울특별시 강동구 동남로 892 (상일동),37.5520459324005,127.157084787845,12
...,...,...,...,...,...
57,한림대학교한강성심병원,"서울특별시 영등포구 버드나루로7길 12 (영등포동7가, 한강성심병원)",37.52346674579277,126.91033000120589,30
58,한양대학교병원,서울특별시 성동구 왕십리로 222-1 (사근동),37.559944533564746,127.04488284061982,10
59,혜민병원,서울특별시 광진구 자양로 85 (자양동),37.535315660180416,127.08360130258502,10
60,홍익병원,"서울특별시 양천구 목동로 225, 홍익병원본관 (신정동)",37.52844147447355,126.8636640030062,8
61,희명병원,서울특별시 금천구 시흥대로 244 (시흥동),37.45567063464179,126.90056251863875,4

In [ ]:
# csv 파일로 저장(인덱스 제외)
df_basic.to_csv('df_basic_true.csv', index=False )

In [ ]:
# 응급실 데이터 수집하기
# 응급실 기본정보 조회

url = 'http://apis.data.go.kr/B552657/ErmctInfoInqireService/getEmrrmRltmUsefulSckbdInfoInqire'
serviceKey = ''    # 여러분의 일반 인증키(Decoding)

params = {
    'serviceKey': serviceKey,
    'pageNo': '1', 'numOfRows': '1000',  # 전체 응급실 수가 500여개 됨. 1000개면 충분
    'STAGE1' : '서울특별시', 'STAGE2':'강남구',
    'format': 'xml'
}

response = requests.get(url, params = params)

# 정상 수행 되었다면 200
print(response)

<Response [200]>

In [ ]:
response.text

In [ ]:
# response xml에서 주요 정보 찾기
root = ET.fromstring(response.text)

data = []

for item in root. findall('.//item'):
    duty_name = item.findtext('dutyName') #기관명
    # 필요한 정보 추가
    hvgc = item.findtext('hvgc') #입원실
    hvec = item.findtext('hvec') #응급실
    hvidate = item.findtext('hvidate') #입력일시
    # 빈 리스트 data에 딕시너리 형태({'칼럼이름':값, ...})로 저장(추가)
    data.append({'기관명' : duty_name, '응급실': hvec, '입원실': hvgc, '갱신일자': hvidate})

# 데이터프레임으로 변환
df_em =  pd.DataFrame(data)

In [ ]:
df_em

                  기관명 응급실  입원실            갱신일자
0  연세대학교의과대학 강남세브란스병원  -6  127  20241118160826
1              삼성서울병원  -8  482  20241118161110